### ISSUE TITLE
Alignment sorting issue

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#100]
There is a minor issue with sort-by-base.  See pic below,  the rows with blanks at the sorted position shouldn't be there (shouldn't see that white space).   I sorted with alt-click.

![screen shot 2015-05-11 at 11 14 19 am](https://cloud.githubusercontent.com/assets/933148/7568131/14f56af6-f7cf-11e4-8468-47fa56d73e06.png)

**Comment by jrobinso** [comment]
Possibly related to #105

**Comment by turner** [comment]
Closed with commit 4ad7ce2b
