### ISSUE TITLE
variable which has igv.js version number?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1000]
@jrobinso   
Just now trying to debug an igvR problem remotely I wish that I knew how to obtain, in Javascript, the commit date and version number of the igv.js I had built into my package.  

Sorry if this is already documented and maybe many times discussed.

  How can I do this?

 - Paul

**Comment by jrobinso** [comment]
Unfortunately you can't.  I haven't figured out a good way to do this yet but thanks for the reminder.

**Comment by jrobinso** [comment]
I've fixed this going forward, the build process now injects a version and commit hash.   The commit date is not available in a reliable way.   You get this info with the function igv.version().
