### ISSUE TITLE
programmatically control "soft-clips"?

### ISSUE THREAD

**Issue by petermchale** [igvteam/igv.js#1002]
Is it possible to programmatically control the "soft-clips" menu option for an alignment track in igv.js? One can manually turn on soft clips for an alignment track using the "gear" menu, but is there a corresponding (undocumented?) property in the alignment track "options" (https://github.com/igvteam/igv.js/wiki/Alignment-Track)?

**Comment by jrobinso** [comment]
Yes,

```showSoftClips: true```

I will update documentation.

**Comment by petermchale** [comment]
Wonderful! Thanks!
