### ISSUE TITLE
Slow rendering of pacbio alignments

### ISSUE THREAD

**Issue by petermchale** [igvteam/igv.js#1004]
Here are two igv reports. Chrome renders the first in a handful of seconds. Chrome didn't render the second (I stopped waiting after about a minute). This surprised me given that the second is only 4.5MB larger than the first, which is 4.5MB. The second differs from the first in the addition of an extra alignment track (pacbio). 

Is this expected behavior? 

http://home.chpc.utah.edu/~u6018199/4.5M.html
http://home.chpc.utah.edu/~u6018199/9M.html

**Comment by petermchale** [comment]
Great! 

Would you mind sticking the edited version of igv.js (the one you created with a threshold on the number of indels to render) on a server. so that I can reference at:

https://github.com/igvteam/igv-reports/blob/b1e221e99bc2779f3360a2240f4dbad1f9fc8ca8/igv_reports/templates/variant_template.html#L15

in my local copy of igv-reports? 

I'd appreciate that as it would tide me over until your official fixes arrive.

**Comment by jrobinso** [comment]
Yes, you can use the snapshot build

https://igv.org/web/snapshot/dist/igv.min.js.

You'll need to remake your reports with the following in the track config
for the pacbio bams.  The larger the threshold the faster it will load.

hideSmallIndels: true,
indelSizeThreshold: 10,

**Comment by petermchale** [comment]
That works. Thanks!

... though at first the pacbio track did not render because the track name
was "HG00514.pbmm.lra", which appears to be hardcoded into the minified js:

https://github.com/igvteam/igv.js/search?utf8=%E2%9C%93&q=HG00514&type=

**Comment by jrobinso** [comment]
Hah, yikes must have had a bed day.  I'll take care of that,  we can't ask everyone to name there pacbio bam files "HG00514.pbmm.lra" :)

**Comment by jrobinso** [comment]
@petermchale This is now released as igv.js v2.3.3

**Comment by petermchale** [comment]
Thanks @jrobinso
