### ISSUE TITLE
Browser is not rendering tracks anymore

### ISSUE THREAD

**Issue by jimhavrilla** [igvteam/igv.js#1005]
Hey again, long time no speak.

If you remember me, I made the [CCR Browser](https://s3.us-east-2.amazonaws.com/ccrs/ccr.html).  The source code is at that link.  I was previously using (as instructed) the version of IGV.js at https://igv.org/web/current/dist/igv.js.  Now, a user has told me the browser was not rendering as that link no longer exists.  I searched through your release repository and after some effort found this version: https://igv.org/web/release/current/dist/igv.js.  And since the path seems to be written similarly, I'm guessing it is more or less the same version.

However, it does not render BED12, BED or VCF format correctly.  It gives an error saying `Index file not found. Check track configuration`.  But the wig files render correctly. So I then decided to upgrade to 2.2.2 that seems to work except it does not properly render wigs. I tried your latest release, hoping it will have a fix, [2.3.2](https://igv.org/web/release/2.3.2/dist/igv.js).  Then I get a different error, "Error accessing resource: https://s3.us-east-2.amazonaws.com/ccrs/tracks/gnomad-vep-vt.vcf.gz.tbi Status: 0" and now it _only_ shows the wig files strangely and looks like this:

![image](https://user-images.githubusercontent.com/6568964/67260583-16ef4100-f46a-11e9-9b5d-c07bdd183e49.png)

However, there are 14 tracks which normally load and this makes no sense.  
I have correctly used the tracks as instructed at https://github.com/igvteam/igv.js/wiki/Tracks-2.0 for some time, and have not changed that code at all since it worked previously.  And now local file upload does not work either.

I'm really at a loss because I don't know what to do.  It worked finally, I hadn't made any changes since January, and I really would like to just leave it there and have it work.

Any help would be appreciated, preferably a permanent release of the version that used to work that was at the old file path.

**Comment by jrobinso** [comment]
Hi Jim,

I don't know what i told you previously but processes have evolved over the
years.  For a stable project that isn't changing I suggest you nail to a
version and stay there, don't use soft links like "current" which can
change. Instructions are at  https://www.npmjs.com/package/igv.   The
latest release is https://cdn.jsdelivr.net/npm/igv@2.3.2/dist/igv.min.js,
but that should be equivalent to what you are using.

Your website is loading from
https://igv.org/web/release/2.2.2/dist/igv.min.js.  However, the console
errors are coming from something at webpack://./tmp/igv-cjs.js, that
appears to be the code it is using.   I have no idea what that is.

**Comment by jrobinso** [comment]
Do you have CORS enabled on all these tracks?  I tried running your page locally and I see lots of errors like this in the console. 

Access to XMLHttpRequest at 'https://s3.us-east-2.amazonaws.com/ccrs/tracks/Homo_sapiens.GRCh37.75.gtf.gz.tbi' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by jrobinso** [comment]
Or perhaps these files aren't tabix indexed.  If they aren't, please add "indexed: false" to your config, that will prevent this error.

**Comment by jrobinso** [comment]
I can't fit it all in 1 screenshot but here's what I see when running your page locally.   Looks normal.  Also local files working.  This is using IGV 2.3.2.   I'll attach my copy of your page as well.

<img width="1452" alt="Screen Shot 2019-10-21 at 10 58 53 PM" src="https://user-images.githubusercontent.com/933148/67261685-9246f780-f456-11e9-8e24-8acea4c27057.png">
<img width="1504" alt="Screen Shot 2019-10-21 at 10 58 34 PM" src="https://user-images.githubusercontent.com/933148/67261686-9246f780-f456-11e9-8c65-9c933c929b25.png">
[ccr.html.zip](https://github.com/igvteam/igv.js/files/3753984/ccr.html.zip)

**Comment by jimhavrilla** [comment]
Hey @jrobinso, good to hear from you again (and so quickly!).

So I don't know what `webpack://./tmp/igv-cjs.js` either...but I updated the site to 2.3.2 as instructed and just to be safe deleted the CORS headers I had in place and replaced them with near identical ones (just added HEAD method I think) and now it seems to be working, so I guess this is issue is closed?

So now this file path is permanent, safe, and will not be changed correct, `https://igv.org/web/release/2.3.2/dist/igv.js`?

You guys really made it look nicer in the last few updates by the way (save SVG is a _nice_ touch)!

Cheers,
Jim

**Comment by jrobinso** [comment]
Well this is bizzare,  it worked for a while (see screenshots),  now all the files are blocked by CORS restrictions.   This is from the server, really has nothing to do with IGV.   How are you handling CORs.

**Comment by jimhavrilla** [comment]
Oh, I just answered you, see above.  If it is not working for you now at [this link](https://s3.us-east-2.amazonaws.com/ccrs/ccr.html) please let me know.

**Comment by jrobinso** [comment]
Messages crossing,  I guess whatever you did with CORS blocked access to localhost and that's why I see errors now.    Use the CDN urls as suggested earlier and in the readme and NPM instructions, not the igv.org ones,  both should be safe but the CDN is more safe.   If we loos our funding and go away the CDN urls will still be there.

**Comment by jimhavrilla** [comment]
I will do that, thanks.  Hey, is there something I can add that will allow localhost AND online use?  My CORS headers are currently as such:

    <?xml version="1.0" encoding="UTF-8"?>
    <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
    </CORSConfiguration>

Since you seem to be WAY more experienced than me at CORS, is there something I should be adding?

**Comment by jrobinso** [comment]
I'm not sure what you mean by online use but here is our policy, allows any origin, as does yours, so I don't see where the local host issue is coming in but it might be with the AllowedHeader tag.  I'm a little surprised you policy is working with such a restricted AllowedHeader list,  but some headers are not affected by CORS.  That could cause problems, although that would have nothing to do with igv version.  

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>Content-Length</ExposeHeader>
    <ExposeHeader>Content-Type</ExposeHeader>
    <ExposeHeader>Content-Range</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

```

**Comment by jimhavrilla** [comment]
Okay, I have now tried that, and I can still remote access, but not localhost access for me either.  S3 has been a nightmare with this honestly.

**Comment by jimhavrilla** [comment]
Ok, I think I got it.  This is mindblowing to me.  The answer is [here](https://stackoverflow.com/a/28569497/3705490) at least for me.  I couldn't run the Browser on Chrome or Opera locally, opened in Safari, _same_ CORS headers and *BAM* it worked.  So weird.

**Comment by jrobinso** [comment]
So weird,  I've never had a problem with localhost.    But if you found some combo that works just go with it, until someone changes the rules again.

**Comment by jimhavrilla** [comment]
True
