### ISSUE TITLE
API to remove track and remove ROI

### ISSUE THREAD

**Issue by pratibha-strand** [igvteam/igv.js#1013]
We have APIs to loadTrack and loadROI. It will be good to expose APIs for removing them as well.

**Comment by jayfmQQ** [comment]
In the latest version(igv@2.3.3),  you can use `browser.removeTrackByName(name)` to remove a exists track.

**Comment by pratibha-strand** [comment]
@jayfmQQ Thanks for the update. But we still do not have an API to remove ROI.

**Comment by pratibha-strand** [comment]
@jrobinso Can you include API to removeROI in the next release. Thanks.

**Comment by jrobinso** [comment]
Thanks @pratibha-strand for the PR.   I'm leaving this open until we release and update the wiki doc.  Also - note to self - we should add a similar method to BaseTrack for the track-specific ROIs.
