### ISSUE TITLE
Error on downloading svg in with bam file in "Zoom in to see features" mode

### ISSUE THREAD

**Issue by stefan-leye** [igvteam/igv.js#1014]
When I try to download an svg image, with a bam file (alignment track) where features are not shown because it is zoomed out too far, I get the following exception:

> Uncaught (in promise) TypeError: Cannot read property 'maximum' of undefined
at CoverageTrack.draw 
at Object.BAMTrack.draw
at ViewPort.draw

**Comment by helgathorv** [comment]
Released with igv.js 2.3.3
