### ISSUE TITLE
bigWig rendering issue: coverage gaps appear/disappear at different zoom levels

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1017]
Hi Jim,
I've been looking at wig tracks, and I often notice gaps at intermediate zoom levels that disappear when I zoom in or out by several levels. For example if I load the attached .bigWig file at `chr22:16,647,802-16,651,870`:
[test.chr22.bigWig.gz](https://github.com/igvteam/igv.js/files/3829376/test.chr22.bigWig.gz)
(it's gzipped because github only allows .gz uploads here)

 using this track config:
```
tracks: [
              {
                type: 'wig',
                url: 'gs://my-bucket/test.chr22.bigWig',
                name: 'test',
                format: "bigwig",
              },
 ```

I see 
![image](https://user-images.githubusercontent.com/6240170/68555510-1e1bc600-03fc-11ea-8330-b7634c91d599.png)

but when I zoom into `chr22:16,648,210-16,649,249`, the gaps above the TPTEP1 exon disappear:

![image](https://user-images.githubusercontent.com/6240170/68555575-620ecb00-03fc-11ea-90ec-9690a9c1d8a0.png)

Not sure if it matters, but my IGV container box width is 1662px, and the IGV version is current master.

**Comment by jrobinso** [comment]
Thanks I'll look at it.  I agree that doesn't look right.

**Comment by jrobinso** [comment]
Pushed a fix,  if you are building from source you can pull and try now.   I'll get this in the next release, early next week.

**Comment by jrobinso** [comment]
BTW the error was an ill-advised optimization.   The idea was to not draw a wig feature if it would occluded by an earlier drawn feature.   I'm still not completely sure why this wasn't working, but the performance gain was modest at best so I removed this.

**Comment by bw2** [comment]
Thanks for the quick fix.
