### ISSUE TITLE
custom reference is not supported in v 2.3.5?

### ISSUE THREAD

**Issue by polojacky** [igvteam/igv.js#1022]
Hi, I want to use local reference since the speed of the amazon cloud is not so fast. I followed the wiki (https://github.com/igvteam/igv.js/wiki/Browser-Creation) and replaced 'genome' option with 'reference'.  But it seems in v2.3.5 'genome' option is required and I failed. I also tried loadGenome function but it gave the error "loadGenome is not a function". So what should I do to use a customed reference? Thanks!

**Comment by jrobinso** [comment]
Hi, please post the configuation javascript you used.   See http://igv.org/web/release/2.3.5/examples/customReference.html for an example of a custom reference.

**Comment by polojacky** [comment]
Thanks jrobinso, I used the same configuration as you posted. Finally, I tried it out by using a local genome.json file with 'genomeList' option. I'll do more test to find out why 'reference' option is not ok for me.

**Comment by jrobinso** [comment]
reopen with more details if you continue to have this problem.   Details would include the output to the java console, and if possible a test case we can reproduce it with.   I should add that technically there is no such thing as a "local" reference, all references are by URL.
