### ISSUE TITLE
Add support to draw horizontal line in bg/bw tracks

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#1023]
Hi Jim,

We (@docwarren) would like to add functionality to draw horizontal 'guide' lines on any given track (mainly bg,bw).  See attached screenshot.

Do you think such a feature would have wide appeal?  If so happy to PR.

To implement, we were considering adding a new track param (halign) that can take in an array of values where a horizontal line will be drawn across the track.  Ideally one could also control the line-type (solid, dotted etc) and even the color.  

Param input could then be something like a object'
halign: [{"y":100,"color":"blue","line_type":"dotted"},{"y":200,"color":"red","line_type":"dotted"}]

[](url)
![horizontal_line](https://user-images.githubusercontent.com/8889420/69264337-f951ec00-0b7b-11ea-93e2-5f548d491b32.png)

**Comment by jrobinso** [comment]
This looks reasonable, and useful, but for line_type check to see what canvas options there are.  I'm not sure myself, possibly you would find this in strokeStyle.

**Comment by blajoie** [comment]
Will do - more soon @jrobinso

**Comment by docwarren** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash

**Comment by blajoie** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash
> @blajoie I don't think we should try to do this for all tracks. Its only relevant for tracks that have a numerical y axis.

Yes exactly, this is only logical for 'data' tracks.  bedgraph/wig

**Comment by docwarren** [comment]
@blajoie We will need to update the wiki if these changes are accepted

**Comment by jrobinso** [comment]
This has been merged
