### ISSUE TITLE
Minimize track height IF view > visibilityWindow

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#1024]
@docwarren

Example:
Bam track is set to visibilityWindow: 30000 and height:400.  When the user zooms out to a 40kb interval, the bam track correctly turns off, however the bam track remains with a height:400.  Would it make sense to minimize any track to ~50 if the track is currently disabled due to visibilityWindow (freeing up more useable screen space).  Then once the user zooms back and and a track is re-enabled, dynamically adjust the track height back to the set value.

**Comment by jrobinso** [comment]
I see the point, but visibility window applies to all tracks (not just bams) and I don't think we want them jumping up and down as various thresholds are passed.   I do see the point, especially for BAMs, but we need to think a bit how to implement it.

**Comment by blajoie** [comment]
Agreed, it does need some thought.  Perhaps it could be implemented in such a way to only adjust track heights when there would be a big gain (e.g. when a track height is >300, the logic would then bring it back down to a 100-200 height)? Most other tracks already set to a <300 height would stay as is? That way the amount of tracking being resized could be minimized.

**Comment by jrobinso** [comment]
I discussed it with Helga,  our thought is to have an "autosize" option
with min and max bounds, and just let the track do what it needs within
those bounds (shrinking to smallest possible).  I think this is easy to
explain, and covers other cases.  What are your thoughts?

**Comment by blajoie** [comment]
Love it!  That would solve our use case beautifully.

**Comment by jrobinso** [comment]
We already had this feature, duh, had forgotten about it.  But it wasn't working for the case of "out of visibility window".  That's now fixed.  Config parameters are as follows (example)

```
                    autoHeight: true,
                    minHeight: 50,
                    maxHeight: 500,
```

**Comment by blajoie** [comment]
Awesome, thanks again!
