### ISSUE TITLE
How to use the index file for seg file?

### ISSUE THREAD

**Issue by shenjia1** [igvteam/igv.js#1025]
My seg file is too large. I want to use the index file. But I used the command below to get the index file:
tabix -b 3 -e 4 -s 2  XXX.seg.gz
But it doesn't work.

**Comment by jrobinso** [comment]
Hi, sorry for the delayed response,  I'm traveling for the holidays, will look at this when I return.

**Comment by shenjia1** [comment]
Thanks. Could you please tell me whether the lasted version support the indexed seg files?

**Comment by jrobinso** [comment]
No version of IGV or igv.js supports indexed seg files.  When I return after new years I will investigate if it is possible to supporting it.   I'm not aware of any software that supports this, but it might be possible.

**Comment by jrobinso** [comment]
I just pushed support for this, we will release it in a few days as 2.5.0.

The tabix command would be the following.  -S1 is neccessary to skip the header line
```
tabix -S1 -s2 -b3 -e4 XXX.seg.gz 
```
Before running tabix you have be sure your file is sorted by chromosome (sequence) then start position.

See http://igv.org/web/snapshot/examples/seg.html  for an example

**Comment by shenjia1** [comment]
Thanks, I will try it.
