### ISSUE TITLE
Example CRAM file, locally saved, crashes browser

### ISSUE THREAD

**Issue by valleema** [igvteam/igv.js#1026]
Hello!

I am testing out `igv.js` with [this example](https://igv.org/web/release/2.3.5/examples/cram.html) and it works well, with the s3 files:

```javascript
url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram',
indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai',
```

The web page is super light (around 3 MB, if we trust the browser's devtools) and works nicely.

However, to simulate my project (using Laravel), I locally downloaded them, and used them this way:

```javascript
url: 'storage/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram',
indexURL: 'storage/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai',
```

Laravel has seen that I required those files:
```bash
[Wed Nov 27 15:20:48 2019] 127.0.0.1:57418 [200]: /js/igv.min.js
[Wed Nov 27 15:20:48 2019] 127.0.0.1:57419 [200]: /js/igv.min.js.map
[Wed Nov 27 15:20:49 2019] 127.0.0.1:57429 [200]: /storage/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai
[Wed Nov 27 15:20:49 2019] 127.0.0.1:57430 [200]: /storage/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram
```
and the IGV div is loaded (and the grey spinner... well, spins), but the page weight exceeds 2 GB (according to browser's devtools) before it freezes my whole computer, and crashes my browser.

I tried opening the file in IGV standalone app and everything is fine.

Is it a problem of my server, not handling files as the distant S3 does?

**Comment by jrobinso** [comment]
Yes, most likely.  Possibly your server is ignoring the Range header and trying to load the entire file.   See here for server requirements,  CORS does not apply if the data and page is loaded from the same domain.    https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements

**Comment by jrobinso** [comment]
I see Laravel is based on PHP.  Here is some PHP that properly handles the range header, or at least properly enough for the various IGVs (I used it).  This snippet reads from remote files using curl, but you could modify it to do something similar with local files.  The key thing is to only return the byte range requested, not the entire file.

```
<?php
//ini_set('display_errors', 1);
//ini_set('display_startup_errors', 1);
//error_reporting(E_ALL);

header("Access-Control-Allow-Origin: *");
header('X-Frame-Options: SAMEORIGIN');
header('Cache-Control: no-cache');
header('Pragma: no-cache');
header('X-Content-Type-Options: nosniff');
header('X-XSS-Protection: 1');
header('Content-Type: application/octect-stream');

$query = $_SERVER['QUERY_STRING'];
parse_str($query, $output);
$position = $output['position'];  // value
$length = $output['length'];
$file = $output['file'];

$end = intval($position) + intval($length);
$ch = curl_init();
$range = $position . '-' . strval($end);
//echo $range;
curl_setopt($ch, CURLOPT_URL, $file);
curl_setopt($ch, CURLOPT_RANGE, $range);
curl_setopt($ch, CURLOPT_BINARYTRANSFER, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($ch);
curl_close($ch);
echo $result;


?>

```

**Comment by jrobinso** [comment]
I posted a snippet to do range requests with PHP but realized it was not exactly what you need.  If you do a web search you should find an implementation.   You need to parse the range header, then read and return in the request only the bytes requested, not the entire file.  Most servers will do this for you, including simple ones like flask and Node's http-server.

**Comment by valleema** [comment]
Thank you @jrobinso, I will look into it.

**Comment by valleema** [comment]
Hi @jrobinso,
For those encountering the same problem:

I tried with MAMP and it works beautifully. 
So it was the `php artisan serve` which cannot handle CORS (as of today).

Cheers!
