### ISSUE TITLE
Error on removing browser

### ISSUE THREAD

**Issue by stefan-leye** [igvteam/igv.js#1027]
Sometimes, when a running IGV browser is removed (shortly after creating, e.g. if the user switches views), igv.js throws the following error:

> Error: "Uncaught (in promise): TypeError: this.trackViews[0].$viewportContainer is undefined
TrackView
_callee9$
tryCatch
invoke
defineIteratorMethods/</prototype[method]
asyncGeneratorStep

This probably results from the DOM element being not visible, before the IGV browser is correctly disposed.

**Comment by jrobinso** [comment]
You're probably correct.
