### ISSUE TITLE
Ability to specify color and opacity for wig tracks

### ISSUE THREAD

**Issue by docwarren** [igvteam/igv.js#1028]
Hi Jim,

When doing an IGVGraphics.fillRect its possible to specify a properties object that modifies things like strokeStyle. However this is not possible for drawing a point with IGVGraphics.fillCircle.
We like the idea of modifying opacity quite a bit because when you have multiple overlapping features they stack up and are darker where more overlap occurs and lighter where less overlap occurs. Mind if I add this?

Could also be useful to have an IGVGraphics function that resets to default values for color, opacity, strokeStyle etc, so that you always know that there are no left over context settings when you draw something (or is this already covered somehow?)

including @blajoie

Best
Andrew

**Comment by jrobinso** [comment]
That was an oversight,  I just pushed an update.  I don't know how to reset a context's properties to defaults other than creating a new one, but all these methods reset the context to values they had prior to the call with this

```
ctx.save();
...
if (properties) ctx.restore();
```

**Comment by blajoie** [comment]
Awesome - thanks Jim - this will help us quite a bit!

**Comment by docwarren** [comment]
Thanks Jim.

**Comment by docwarren** [comment]
Any chance you could modify line 201 in wigTrack
`IGVGraphics.fillCircle(ctx, px, py, pointSize / 2, {fillStyle: color, strokeStyle: color});`
I don't seem to have permission to push a new branch.
