### ISSUE TITLE
"Cannot read property 'tabix' of undefined" error message when a user logs in but doesn't doesn't have permissions to access a particular Google bucket path

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1030]
![image](https://user-images.githubusercontent.com/6240170/70394299-f94a4c80-19c1-11ea-8ec2-add5680bf7a7.png)

![image](https://user-images.githubusercontent.com/6240170/70394301-fcddd380-19c1-11ea-9816-81e9c8357c6a.png)

When I look at igv.js:26825 it's

![image](https://user-images.githubusercontent.com/6240170/70394305-036c4b00-19c2-11ea-8020-0e5bdd58e7dd.png)

**Comment by jrobinso** [comment]
Hi @bw2, as communicated by email I couldn't reproduce this exactly, however commit 5645557cda1eed1ed686d41aa3f68574cb583afb should solve the problem.  Merge this into your branch and try again.   Thanks.

**Comment by bw2** [comment]
I think this is fixed now.
