### ISSUE TITLE
setCustomCursorGuideMouseHandler is not called when mouse clicks outside the content div

### ISSUE THREAD

**Issue by pratibha-strand** [igvteam/igv.js#1035]
Can we call this when the mouse clicks on viewport container but outside content div?

<img width="1160" alt="Screenshot 2019-12-11 at 5 09 58 PM" src="https://user-images.githubusercontent.com/24718636/70618520-1ccafc80-1c39-11ea-9882-a794b5d08828.png">
<img width="1160" alt="Screenshot 2019-12-11 at 5 10 06 PM" src="https://user-images.githubusercontent.com/24718636/70618531-22c0dd80-1c39-11ea-92bc-a6b0f4cad893.png">

**Comment by jrobinso** [comment]
@pratibha-strand This should be fixed now, can you pull and try?

**Comment by jrobinso** [comment]
@pratibha-strand ignore last message, now deleted, we need to do more testing.

**Comment by jrobinso** [comment]
Fixed with commit 2487f50ae02257741436b27fec9f4d4e399661fb
