### ISSUE TITLE
autoHeight value is not true by default for alignment track in IGV 2.2.0

### ISSUE THREAD

**Issue by sjsachinrj** [igvteam/igv.js#1037]
In previous version  of IGV.js this value is true by default. Do we need to set it true explicitly for v2.2.0

**Comment by jrobinso** [comment]
@sjsachinrj In what version do you find autoHeight defaulting to true?

**Comment by sjsachinrj** [comment]
@jrobinso In v1.0.8 .Also in IGV is document default value for this field is specified as true.
After looking into IGV code i found that v2.2 default track height is assigned to track config.height which were missing in v1.0.8

**Comment by jrobinso** [comment]
Yes, the documentation was wrong, its been corrected.
