### ISSUE TITLE
Less alignments reads are shown in IGV.js(v2.3.5) compared to IGV desktop 

### ISSUE THREAD

**Issue by sjsachinrj** [igvteam/igv.js#1044]
In IGV desktop around 40 reads are shown where as in IGV.js only 5 reads is shown. Please see screenshot for both viewer
IGV Desktop viewer 
![image](https://user-images.githubusercontent.com/31273045/71166496-df89ee80-2278-11ea-93e0-6bd4eedd0963.png)

IGV.js(v2.3.5) viewer

![image](https://user-images.githubusercontent.com/31273045/71166538-fd575380-2278-11ea-9a83-3503d6343617.png)

Could you please look into this issue

**Comment by sjsachinrj** [comment]
Sorry for confusion, there is very large blank space between intermediate reads which i haven't noticed. So now in  both viewer reads count is same just in IGV.js reads are  rendered in reverse  order of  Desktop. 
Can you please tell reason for such behavior?

**Comment by jrobinso** [comment]
Could you explain what you mean by "read order"?

**Comment by jrobinso** [comment]
I don't have your data so I can't tell you why there is a gap, but in general the order of reads is arbitrary.  You should not expect IGV desktop and igv.js to have the exact order.
