### ISSUE TITLE
Side by Side Comparison to IGV in Wiki

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv.js#1045]
My collaborators asked what features are in common and unique between IGV desktop allocation  and IGV.js. It would be convenient to have a table with ticks in it to show what feature each software has.

**Comment by jrobinso** [comment]
We've thought about that but there are too many features in IGV desktop, and its a moving target on both sides.  Its easier to respond to specific questions,  if you have a list of features you would like to see I can say yes/no/future wrt igv.js.

**Comment by DarioS** [comment]
Not sure what the most popular features for biologists are, since I'm not one. I was thinking of a table of a dozen or so features. Perhaps it's something for the distant future to include.

**Comment by jrobinso** [comment]
Most people asking this question are interested in what IGV desktop features are in igv.js, and the answer is generally all of them that have been requested.  The problem with a table is its static, and implies some fixed answer.   No one should make a decision wrt igv.js based on such a table, if there is a missing feature they should rather request it.    With respect to major features igv.js is fairly complete with the following exceptions.   (1) support for the sample information table,  (2) some pacbio / 3rd gen features,  and (3) support for bisulfite sequencing.  These are not prioritized yet, no or few requests for these,  but they will eventually be ported.
