### ISSUE TITLE
hg38 gene track always 70 pixels high

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1047]
Using ```https://cdn.jsdelivr.net/npm/igv@2.3.5/dist/igv.min.js``` (2.3.2 also) the track options shown below always produce a gene track 70 pixels high.  It is likely to be my error - any suggestions?

![image](https://user-images.githubusercontent.com/2480712/72393970-62bc2a00-36e9-11ea-9a23-2a31ab88dc13.png)

![image](https://user-images.githubusercontent.com/2480712/72394024-9434f580-36e9-11ea-88d1-abdaac020582.png)

**Comment by jrobinso** [comment]
@paul-shannon There is no way to control the height of the hosted genome gene track.  The height settings have no effect outside the context of a track,  the global settings you are trying won't work.

You can get around this by defining a "reference" object in lieu of using genomeId.  For hg38 use this, and add your track height settings or anything else you want:
```
  {
    "id": "hg38",
    "name": "Human (GRCh38/hg38)",
    "fastaURL": "https://s3.dualstack.us-east-1.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa",
    "indexURL": "https://s3.dualstack.us-east-1.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa.fai",
    "cytobandURL": "https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/annotations/cytoBandIdeo.txt.gz",
    "tracks": [
      {
        "name": "Refseq Genes",
        "format": "refgene",
        "url": "https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz",
        "indexURL": "https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz.tbi",
        "visibilityWindow": -1,
        "removable": false,
        "order": 1000000
      }
    ]
  }```

**Comment by paul-shannon** [comment]
Thanks, Jim.  I will use the approach you suggest.
