### ISSUE TITLE
Hide navigation controls

### ISSUE THREAD

**Issue by el1jaC** [igvteam/igv.js#1048]
Hi all,
I wonder if there is a way to hide the topbar with all of controls (like search, show/hide cursor, etc.) with an API or function, without editing the CSS file.

Thanks in advance :)

**Comment by turner** [comment]
There is a igv browser configuration setting to do that named `showControls`. Set it to `false` to hide the controls:

```
            const options =
                {
                    genome: "hg19",
                    locus: "myc",
                    showControls: false
                };

```

**Comment by el1jaC** [comment]
Thank you turner :)
I'll try it soon!
