### ISSUE TITLE
ERROR: range-byte header was ignored for url

### ISSUE THREAD

**Issue by romanzenka** [igvteam/igv.js#1049]
This is basically the same issue as #680. 

We are doing some testing, so we are loading very small files. 

Chrome seems to give up asking for tiny file slivers, instead delivers entire file contents all at once.

IGV.js considers this a serious error and reports it.

Technically it is not an issue that you got more data than what you asked for! 

I will try to make a tiny PR that will return a subset of the loaded data, just so IGV can proceed without erroring out.

**Comment by jrobinso** [comment]
@romanzenka I've never seen Chrome do this.  Are you sure its not your server?  It is an issue in many cases, for example a 300 GB bam file.

**Comment by romanzenka** [comment]
I am using the built-in python server on a tiny VCF file. I guess it could be the server giving up, good point, will do more reading about it. It serves ranges just fine but once the ranges get small, it gives up.

**Comment by jrobinso** [comment]
I think this is resolved, re-open if not.
