### ISSUE TITLE
Sort by base not working correctly

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#105]
Sort-by-base in alignment track is flaky.   It will usually appear to do the right thing once, but easily gets out of whack continuing to sort by "alt-click".

**Comment by david-ma** [comment]
Is this issue still open?
And is #105 related to #100?

How do you reproduce #100?

**Comment by jrobinso** [comment]
Yes,  I opened this so its not forgotten,  but haven't got to it yet.  Possibly related to #100, not sure how to reproduce.  Feel free to take a crack at it.

**Comment by turner** [comment]
Closed with commit 4ad7ce2b
