### ISSUE TITLE
[TypeError: Cannot read property 'end' of undefined] on MT locus

### ISSUE THREAD

**Issue by crashete** [igvteam/igv.js#1051]
Hello,

We've been using igv.js for a while now with no issues, but recently I've stepped on an error trying to visualize MT data on the viewer. 

I've changed the reference from hg19 to b37 and, while I can browse data from chromosomes 1-22, X or Y, trying to search for anything MT-related (from whole MT to a specific locus) drops an error in Dev Tools "igv.js:53433 Uncaught (in promise) TypeError: Cannot read property 'end' of undefined".

Current browser config is:

```
{
                    showNavigation: true,
                    showRuler: true,
                    reference: {
			                id: "b37",
					fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/b37/human_g1k_v37.fasta",
					cytobandURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/b37/b37_cytoband.txt"
				},                            
                    tracks: [
			{
				name: "Genes",
				type: "annotation",
				format: "bed",
				sourceType: "file",
				url: "include/gencode.v18.collapsed.bed",
				indexURL: "include/gencode.v18.collapsed.bed.idx",
				displayMode: "EXPANDED"
			},
                        {
                            name: "Reads",
                            type: "alignment",
                            format: "bam",
                            sourceType: "file",
			    url: "",
			    indexURL: "",
                            colorBy: "strand",
                            visibilityWindow: 1000000,
                            displayMode: "EXPANDED",
			    showSoftClips: true
                        }

                    ]
                }
```
Using 2.3.5 build from https://cdn.jsdelivr.net/npm/igv@2.3.5/dist/igv.min.js

So far I've tried displaying only the reference in a 'fresh' browser creation with the same issue happening. As far as I know, MT is currently supported, right? 
I'm a bit lost here, so any insight about this issue will be appreciated. If you need any more info, feel free to ask.
Thanks!

**Comment by jrobinso** [comment]
I'll look into it.   Are you able to search for MT loci here:
http://igv.org/app/ ?

**Comment by crashete** [comment]
Hi Jim, 

No, I can't. It drops the same error on the console.
![image](https://user-images.githubusercontent.com/5757138/73524246-06594a00-440d-11ea-8829-48e307bf7c20.png)

Tried also with Firefox to discard that the issue is related with the browser. This one drops TypeError: f[(f.length - 1)] is undefined @ igv.js:53432:8

Haven't got time yet to go further into debugging this, but I just realized that once I've searched for MT loci, the error drops whenever I resize the window. 

I'm guessing you have no issues searching for MT, so this feels weird. I'll try to dig a bit more around this in the weekend.

**Comment by jrobinso** [comment]
OK I see the error in the console also but it really doesn't affect
anything.   It still goes to the locus requested.   It is erroring
trying to draw the cytoband,  there is no cytoband defined for MT.   i will
correct that but for me at least this is a harmless error.

**Comment by crashete** [comment]
Thanks for the fast fix Jim. Actually the error on the cytoband drawing was also causing the other tracks to not render, so it wasn't as harmless as it might look. All good now, thanks again!
