### ISSUE TITLE
how to accelerate to open? 

### ISSUE THREAD

**Issue by yubau1112** [igvteam/igv.js#1052]
my case:
http://203.73.62.11:2020/yubau_test/HLA/HLA42_20200130/alignment/HLA_H9-12_S6.html

![image](https://user-images.githubusercontent.com/45645173/73635725-17b98500-469f-11ea-8ab5-199c6de87f06.png)

spend time: 27s

how to accelerate to open? 

thanks!

**Comment by jrobinso** [comment]
Faster server?  What is serving this file? It took almost a minute to just
load the html page before loading the cram file.

**Comment by yubau1112** [comment]
I use apache as a web server.

I hope that data can be load into igv at the same time when the webpage is opened, but I think this is difficult. This function has greatly solved my problem, thank you!
