### ISSUE TITLE
Igv "search" crashes my pc.

### ISSUE THREAD

**Issue by el1jaC** [igvteam/igv.js#1053]
Hi all,
I embedded the IGV browser js in Java Webview.
In a partiular case, when i open the view and I load the BAM (+BAI), when i launch the igv.search method my PC is completely freezed and I must reboot it.

There is any solution about the memory/CPU usage limitations?
Do you need any other information about my system?

Best,
Elia

**Comment by jrobinso** [comment]
See if you can reproduce the problem from the igv web application at
igv.org/app.  You can load the same files and go to the same locus there.
 This will help isolate the problem.

**Comment by el1jaC** [comment]
Updating igv.js to the latest version resolves my issue, and igv seems to be very faster :)

My previous version was 2.2.14, and i saw you have improved the igv performance on big depth coverage files.

Could this be the reason?

**Comment by jrobinso** [comment]
@el1jaC Yes, of course it could be the reason.   Generally you should always try a recent version before posting an issue, we assume you are using the most reason version when you post here.

**Comment by el1jaC** [comment]
@jrobinso yes, from now we will try to stay updated with igv js new versions :)

Thanks a lot.
