### ISSUE TITLE
Add ability to set data range & autoscale for coverage track

### ISSUE THREAD

**Issue by yubau1112** [igvteam/igv.js#1054]
![image](https://user-images.githubusercontent.com/45645173/73670466-38f09480-46e4-11ea-8734-ba4aa68ef3bc.png)

![image](https://user-images.githubusercontent.com/45645173/73670496-46a61a00-46e4-11ea-93f4-ef77ce0f3414.png)

how to auto adjust coverage height when using igv.js?

thanks!

**Comment by jrobinso** [comment]
I assume you mean coverage scale.  Did you try right-clicking over the track?  Select "set data range" from the menu.

**Comment by yubau1112** [comment]
Yes, but I mean using  igv.js not windows IGV

thanks!

**Comment by jrobinso** [comment]
Sorry, my confusion.   There is currently no way to set this in igv.js.  I will re-open this and change the title and treat it as a feature request.
