### ISSUE TITLE
Don't redraw tracks when user zoom or drag action doesn't change viewport coordinates. 

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1056]
It would be nice if the code that triggers track redraws could check whether a drag or zoom action actually changed coordinates before triggering. Currently, if you are zoomed out to chromosome level, clicking zoom-out doesn't do anything, but the track draw functions still get called.
Same thing for trying to drag to the left when you're already at the left edge of the chromosome.
gCNV draw takes a couple seconds at chromosome level, so the UI becomes briefly unresponsive in a confusing way when zoomed all the way out and accidentally dragging or zooming too many times.

**Comment by jrobinso** [comment]
@bw2 should be fixed.   As a side note -- redrawing after a drag is triggered if autoscale == true even if the cached image is not out of view.  This is necessary because the data in view might change.   But redrawing is no longer triggered if view coordinates or zoom have not changed.

**Comment by bw2** [comment]
great, thanks
