### ISSUE TITLE
Add new global gear menu item that shows the track's source file path

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1057]
Add a new gear menu item to all tracks called "Source File Path"  (or "Track Info" or similar) which would bring up a dialog that shows the full file path and any other basic metadata not already visible in the UI.

I can't think of any other info to include except maybe (if easily available)
the source file date-last-modified, file size, and total number of features?

**Comment by jrobinso** [comment]
Wow this is a year old.   I think the place for that is the popup text on the track label.

**Comment by bw2** [comment]
that makes sense

**Comment by jrobinso** [comment]
@bw2 This has actually been in place for a long time, I had forgotten about it, but it is up to you to set the meta data for display in a "description" field for the track.    You can set anything you want in this field, and it can include html.   It can even be a function.    I will change the default behavior to include the full path,  if you provide a "description" it will override the default.  The other file meta data you suggest is not available in javascript in general.

**Comment by jrobinso** [comment]
I added the file url to the default metadata, you get it when you click on the track label.
