### ISSUE TITLE
variant track popover data missing

### ISSUE THREAD

**Issue by petermchale** [igvteam/igv.js#1060]
When I click on a `variant` track at the location of a variant, I find that `popoverData` is empty:
![Screen Shot 2020-02-10 at 4 51 48 PM](https://user-images.githubusercontent.com/19557137/74201431-ffa9ae80-4c26-11ea-921b-12e811cdca85.png)
 
Expected behavior is for `popoverData` to contain the values of the various fields in the corresponding row of the vcf file, as that is what https://github.com/igvteam/igv.js/blob/master/dev/1kg-vcf.html 
does when I run `http-server`. 

As a "positive control", `popoverData` does contain expected data when I click on an `annotation` track at the location of an event contained in the bed file: 
![Screen Shot 2020-02-10 at 4 52 08 PM](https://user-images.githubusercontent.com/19557137/74201484-34b60100-4c27-11ea-8929-043e540e6129.png)

Is this a bug, or am I mis-using the interface somehow? 

PS. I'm using the following code to access the popover data: 
![Screen Shot 2020-02-10 at 5 05 40 PM](https://user-images.githubusercontent.com/19557137/74201702-b017b280-4c27-11ea-9e4d-fb5fa5397114.png)

**Comment by jrobinso** [comment]
The following works as expected for me.   I'll probably need a reproducible test case from you to figure out what's going on.

```
 const options =
        {
            showNavigation: true,
            locus: "chr1:155,160,475-155,184,282",
            genome: "hg19",
            tracks: [
                {
                    "url": "https://s3.amazonaws.com/1000genomes/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz?versionId=null",
                    "indexURL": "https://s3.amazonaws.com/1000genomes/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi?versionId=null",
                    "name": "1KG Sites"
                }
            ]
        };

    igv.createBrowser(igv_custom_track_popover.get(0), options)
        .then(function (browser) {
            browser.on('trackclick', function (track, popoverData) {
               console.log(popoverData);

            });
        });
```

**Comment by petermchale** [comment]
In my case, I had included the key-value pair `displayMode: "collapsed"` in the `tracks[0]` object. Removing that key-value pair caused `popoverData` to get populated. 

The following however suggests to me that `popoverData` should have contained something even in "collapsed" mode: 
https://github.com/igvteam/igv.js/blob/f20804acf30cc7031427a6a456717d8d65bb6884/js/variant/variantTrack.js#L274
Is a null `popoverData` expected behavior in "collapsed" mode?

**Comment by jrobinso** [comment]
No, null is not expected, that is a bug.

**Comment by jrobinso** [comment]
OK, pretty sure I fixed this with last commit but re-open if not.

**Comment by petermchale** [comment]
Fixed. Thanks.
