### ISSUE TITLE
htsget endpoint path is partially hardcoded

### ISSUE THREAD

**Issue by GrishaH** [igvteam/igv.js#1061]
We are testing a deployment of htsget using your genome browser.
We are currently having issues with a section of code that is hardcoding a section of the endpoint path as `/reads/`.
Our understanding of the htsget spec is that `/reads/` and `/variants/` are recommended, but other alternative names may be used.
Would it be possible to expose this as a parameter in the tracks? So the user can specify an alternative endpoint path.

https://github.com/igvteam/igv.js/blob/0a465785d1426006ff85555f7972ddee0a22ff18/js/bam/htsgetReader.js#L52

**Comment by jrobinso** [comment]
Hmm, the text does say "recommended",  the open API specification implies it is required:  http://samtools.github.io/hts-specs/pub/htsget-openapi.yaml

Yes it can be a parameter, in fact maybe nothing should be hardcoded and "self.config.endpoint" should include '/reads/'.    @lbergelson do you have any thoughts on this?

**Comment by jrobinso** [comment]
Here's a proposed solution that will keep backward compatibility with the current implementation,  htsget alignment resources will be specified as follows.  

```
            {
                type: 'alignment',
                sourceType: 'htsget',
                url: 'http://35.196.212.220',
                endpoint: '/reads/',
                id: 'genomics-public-data/platinum-genomes/bam/NA12877_S1.bam',
                name: 'NA12878'
            }
```

**Comment by GrishaH** [comment]
Thanks for making the new changes, we were wondering if it is likely the new commit would be pushed to a release of igv.js in the near future? It's possible for us to use the version in master, but we would prefer to work with an official release if possible.

**Comment by jrobinso** [comment]
I will be doing a release this weekend or early next week.

**Comment by GrishaH** [comment]
Thank you for the help.

**Comment by jrobinso** [comment]
Thanks for the test data.   The igv.js htsget reader expects to get the same bam "header" on every request for a given resource.  This is to avoid decoding the header every time.   Also, behavior will be in general unpredictable if the header varies on every request.  

In my test I'm using "hg19" which uses "chr1, ..." naming, so 2 requests are made (see explanation below).   On the first request the header returned is 154457 bytes in size, on the second its 154274.  The second isn't actually parsed, its skipped, but the difference in size is throwing everything off.    Jumping around the genome the header length seems to vary on every request.   

I can relax this assumption and just parse the header every time,  I think the time saving from skipping it is probably minimal,  however if it changes in any important way behavior is going to be unpredictable.  Do you have an explanation as to why the header is changing?


-----
**Note** 

There is no "get header" method in the htsget API.  I've requested one a few times but in its absence igv.js has to guess at the chr naming convention.  For example, if the reference using "chr1" that will be tried initially, if no alignments are returned but the header is it is parsed to determine the chr naming convention and the request re-tried.  This is why you might see 2 requests for the initial query.  Once a valid header is returned and parse this should not occur again.
