### ISSUE TITLE
Unable to view tracks on local server via htsget

### ISSUE THREAD

**Issue by GrishaH** [igvteam/igv.js#1062]
Unfortunately, data doesn't seem to load when requesting data from our own htsget server.
Using the Network Developer tools in-browser, I'm able to see that 2 requests are made, one to retrieve the htsget json that includes the URL to follow, and the other to actually retrieve the data using said url. (In fact, there's two copies of the two requests being made at the same time, one for chromosome "1" and another for "chr1", with "1" being the correct one. I'm assuming this is intentional?) 
Using curl, I can confirm that the URL from the payload is valid and does return data when tested.

There is another issue in that trying to use the tracking bar at the top usually causes the browser to load forever and become unresponsive. This doesn't seem to happen in the examples given.

**Comment by jrobinso** [comment]
I'm not really able to debug your server, do you see any errors in the console?     If you can capture the results of the requests with curl, zip, and share them maybe I can simulate your server to see what's happening.

I don't know what you are referring to wrt  "the tracking bar".

**Comment by GrishaH** [comment]
We are still having issues with reads not displaying in the viewer, and we have prepared an example and the steps we have taken so that you can see what we have done so far.

We began by building the required js and min.js files from the instructions on the Github, cloning latest release (master) and building it. The required .html file is set up the same as the ones given in the examples, using a local igv.min.js file as the script, with the options that are passed through being the main change.
 
For instance, for our main test we are using the options:
```
        var options =
        {
            "reference": {
            "id": "1000Genomes_hs37d5",
            "name": "1000Genomes_hs37d5",
            "fastaURL": "/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa",
            "indexURL": "/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa.fai"
            },
            "locus": "1:100,000-100,200",
            "tracks": [
                {
                    "type": "alignment",
                    "sourceType": "htsget",
                    "url": "http://[INSTANCE_IP]:9090/npg_ranger",
                    "endpoint": "/ga4gh/sample/",
                    "name": "NA12878",
                    "id": "NA12878",
                    "format": "bam"
                }
            ]
        };
```
 
 
The page would load with no errors reported in the console.
 
The current error we're struggling with is regarding Reads disappearing when you pan past a certain point. For instance, the options given above have reads vanish around `1:100,206-100,406` and `1:99,580-99,780` at 201 bp zoom. Zooming out allows you to see more and pan further, but reads still tend to vanish past a short range.

Changing the location to something like `182,108,604-182,109,604` allows a larger section to be visible without the reads vanishing, but then other areas vanish, i.e. the previously tested area of `1:100,000-100,200` is entirely invisible after this search.
 
Using the Network Developer Tools in-browser, we can see the requests being made, one for redirection and one for the actual sample file. Testing these URLs from the browser either using curl or a htsget client, we can see that both are valid and return data, so nothing appearing in the genome viewer doesn’t make any sense to us. We are fairly confident our server is sending the right data back to the browser.


We would be happy to provide a URL to the test server we are currently running in a private message if you would like to have a look.

**Comment by jrobinso** [comment]
@GrishaH Sorry I thought I responded to this.  yes could you provide a test URL, and steps to reproduce if different than above.  You can send it by email to igv-team (at) broadinstitute.org.

**Comment by jrobinso** [comment]
@GrishaH I responded to this on #1061 .  It should be fixed now.  Your server is returning a lightly different header  on each request, this was not expected.
