### ISSUE TITLE
Support load bam file from server.

### ISSUE THREAD

**Issue by lkalbert001** [igvteam/igv.js#1066]
I use the igv.js by docker image decoy/igv-webapp. 
But when I load bam file, I can't find the button loading bam from the host that running the server.
How can I do to make it have this function?

Thank you very much.

**Comment by jrobinso** [comment]
Hi,  I don't understand your question,  there is no button to load a bam file.  If you want to configure custom tracks you need to do that yourself.

Also I don't know the docker image you are referring too.

**Comment by lkalbert001** [comment]
What I want to do is loading 'track' from a host that the igv-webapp is running on. I think the server is running on the host, so it should have an entrance to get the bam file in the host. 
Tracks -> 
- Local File
- Dropbox...
- URL
- [Server]  # This is what i need.

And I a newer to use igv-webapp don't know how to configure it.
I hope you can give me some advice, more kindly an updated igv-webapp code in GitHub that supports this function.

![image](https://user-images.githubusercontent.com/34129931/75404988-354cd800-5947-11ea-8b8e-858f4b4d8830.png)

**Comment by jrobinso** [comment]
The server might be running on the host, but igv-webapp is a client application and has no visibility on the server.  It is running on the client.  In fact, due to web security restrictions it has no visibility of files on even the client, but that is not relevant.
