### ISSUE TITLE
Amino Acid sequences

### ISSUE THREAD

**Issue by kzoabi** [igvteam/igv.js#1069]
Hello guys,
I would like to know if there an example that shows Amino Acid sequences (if this is supported by igv.js) on any track when zooming in?

Thanks a lot,
Khaled Zoabi

**Comment by jrobinso** [comment]
Hi Kaheld,  this is not yet supported.

**Comment by kzoabi** [comment]
Hi Jim,
Thanks for the effort you make in order to make the IGV.JS better.
I see the following example while I explore the internet and I think it belongs to your tool.
Please see the amino acids sequence on the exon:
![igv with amino acid](https://user-images.githubusercontent.com/3586425/80943808-b6fe2d80-8df0-11ea-9e22-94431f604c9a.png)

How can I see this in the IGV.JS viewer?

Thanks,
Khaled

**Comment by desouzareis** [comment]
Hi @jrobinso,
Thanks for your expertise and dedication supporting the igv.js!

In some cases the 3-frame translation from the sequence track gear menu differ from the transcript. It would be really helpful if this feature were implemented.
<img width="1411" alt="image" src="https://github.com/igvteam/igv.js/assets/29407033/795d81d5-87fd-45bb-a1ed-bba7ef69ffee">

Thanks.
