### ISSUE TITLE
Assumption made on header caching for BAMs for htsget requests

### ISSUE THREAD

**Issue by GrishaH** [igvteam/igv.js#1070]
Continuing on from the issue at #1061 , and specifically the comment on https://github.com/igvteam/igv.js/issues/1061#issuecomment-593584840 ,
It is our understanding no presumptions can be safely made regarding the bam headers for raw data from an htsget request.

BAM headers are not guaranteed to be the same between different requests, and while this assumption was relaxed, we have worries that this assumption may still be present elsewhere and may clash with other implementations performing specific requests.
 
In our implementation is very likely two requests for exactly the same region will return similar headers. But changing the region, even for one base, will very likely result in a different header. We build the bam file on the fly, every bam we return just includes the reads in the region requested. This may change with other implementations but the main point is that the behaviour is not guaranteed by the htsget spec.

The spec tries to allow for some implementations to support caching using the class field, but the class field is optional, which we do not support as our data travels as a single payload (being a full bam/cram/sam file).

If there are any concerns in that we might be misunderstanding the specification, please let us know. We would be happy to chat with the other teams working in the implementations and agree about what to do next.

**Comment by jrobinso** [comment]
Hi @GrishaH , sorry, I did not mean to alarm you.   It is unlikely you will encounter problems, but theoretically if the header can change anything can change, for example the sequence dictionary, or read group.   As long as you don't change the sequence dictionary to, for example mouse from human,  it should be fine.  Actually as currently coded igv.js would not crash even in this instance, but the results would be hard to interpret, this is what I mean by "unpredictable".

As a developer I would certainly have the expectation that identical queries to the same resource would return identical results,  but this is no longer assumed.

**Comment by jmtcsngr** [comment]
Hi @jrobinso , I think our confusion comes from now being sure why some htsget requests seem to work correctly in the viewer, but others do not show any reads. We can manually check all requests and they return valid data, so we assume the viewers is having problems displaying them.

**Comment by jrobinso** [comment]
@jmtcsngr Is this still a problem?  The error was a wrong assumption in igv.js that the bam header would not be changing between requests, that is now fixed.   If you are still having issues with the latest code (version 2.4.0) please open a new issue.   Sorry for any confusion.  Thanks.

**Comment by jmtcsngr** [comment]
@jrobinso My bad, @GrishaH just confirmed it is working for us. I got stuck with the idea it was still pending. Thanks for the help!
