### ISSUE TITLE
Change minimumBases ?

### ISSUE THREAD

**Issue by Z-Zen** [igvteam/igv.js#1072]
This isn't really an issue but I could not find anywhere on the wiki or the internet about my question. In which file should I change the `minimumBases` parameter ?

Thanks in advance !

**Comment by jrobinso** [comment]
Hi, sorry but offhand I don't recognize "minimumBases", in what context do
you find this parameter?  Also, what do you mean by "file"?

**Comment by Z-Zen** [comment]
@jrobinso thanks for replying and sorry if I somewhat misconfused you. In the browser configuration [here](https://github.com/igvteam/igv.js/wiki/Browser-Configuration-1.0), it states the default value for the option `minimumBases` is 40. I was wondering how can I change this threshold so that we can see features without zooming a lot in IGV since our servers have a lot of memory.

Thanks !

**Comment by jrobinso** [comment]
Ahh,  you want to change "visibilityWindow" in your track configuration,
see https://github.com/igvteam/igv.js/wiki/Tracks-2.0.   You don't set this
globally, but per track.

Minimum bases just sets a value beyond which you cannot zoom.   For example
you can't zoom into a 10 base window.   The wording there is confusing, I
will work on it.

**Comment by Z-Zen** [comment]
I see ! Thanks for the explanation @jrobinso ! sorry if my question was too simple. I am closing it now.

**Comment by Z-Zen** [comment]
I have an additional question @jrobinso, I uploaded a VCF file on IGV and I would like to set the "visibilityWindow" to maximum, is it possible ? If yes, could you please guide me to which file I should modify ? 

Thanks in advance.

**Comment by jrobinso** [comment]
@Z-Zen I don't understand what you mean by "which file", what are you referring to?   You configure igv.js through the configuration object, have you looked at the documentation?

**Comment by Z-Zen** [comment]
@jrobinso I seem to be lost in Javascript. I installed IGV-web by cloning github, building the source code and then starting IGV. I did read the documentation before. By re-reading it again, I realized that igv.js has a different name in my dist folder:

![image](https://user-images.githubusercontent.com/19333943/75999897-2ba51080-5f03-11ea-9669-77797d4136dc.png)

When I was reading the documention, I saw it mentioning igv.js though I couldn't find the file.

**Comment by jrobinso** [comment]
I see, you are asking about igv-webapp, that's a different project with its own issue tracker.   igv-webapp is an application, as opposed to a component for developers like igv.js.   To change the visibility window of a track use the menu (click the gear icon for the track).

**Comment by Z-Zen** [comment]
I understand better now and sorry for not mentioning it before. Is there a way to change it systematically ?

**Comment by jrobinso** [comment]
Currently no, there is no configurable global setting for this.

**Comment by Z-Zen** [comment]
Alright, thanks for the reply

**Comment by jrobinso** [comment]
Open an issue here for "global visibilityWindow setting".
