### ISSUE TITLE
4th column of bed file not displayed

### ISSUE THREAD

**Issue by petermchale** [igvteam/igv.js#1075]
In release 2.3.5, the 4th column of a bed file annotated intervals in the browser and was accessible as popover data from the console: 

`chr1    7829887 7830126 name=trf;period=54;copy_number=4.4;percentage_match=87;percentage_indel=1`

![Screen Shot 2020-03-09 at 11 04 55 AM](https://user-images.githubusercontent.com/19557137/76239462-3b6c6f80-61f7-11ea-8ac8-d7ef18aeccd4.png)

![Screen Shot 2020-03-09 at 11 05 09 AM](https://user-images.githubusercontent.com/19557137/76239474-41625080-61f7-11ea-865c-747270f0f872.png)

However, in release 2.4.0, the annotation does not appear in the browser and is not accessible from the console: 

![Screen Shot 2020-03-09 at 11 07 37 AM](https://user-images.githubusercontent.com/19557137/76239576-6bb40e00-61f7-11ea-9524-f445e567b16f.png)

![Screen Shot 2020-03-09 at 11 07 49 AM](https://user-images.githubusercontent.com/19557137/76239589-7078c200-61f7-11ea-8982-28360c79fcca.png)

The configuration in both cases is: 

`                {
                    type: "annotation",
                    format: "bed",
                    url: "static/data/public/simple_repeats.bed.gz",
                    indexURL: "static/data/public/simple_repeats.bed.gz.tbi",
                    displayMode: "expanded",
                    name: "tandem repeats",
                    height: 40,
                },`

Is this a bug?

**Comment by jrobinso** [comment]
That looks like a bug, I will look into it.

**Comment by petermchale** [comment]
@jrobinso Any luck with this issue? It persists in version 2.4.1. Here are the test data: 

https://drive.google.com/file/d/1ABm7is5obPBNaF_F4XdTPj_qHwiaHqsn/view?usp=sharing
https://drive.google.com/file/d/1mC5q4whdJ_KWYSEemBkO-ePmQbe5I-pK/view?usp=sharing

**Comment by jrobinso** [comment]
@petermchale Are you using one of the event APIs?  Directly accessing "popoverData" in init.js is not supported in any event, implementation details like that can and will change.    I need to document and nail down the event APIs, which I will start on tomorrow, but could you tell me exactly how you are getting access to "popoverData"?

**Comment by jrobinso** [comment]
@petermchale I just pushed a fix for this.   I assume you are using a track click event here to get popoverData,  however if you are not please let me know how you are getting the popover data.

The name field of your bed file looks like a gff attribute string.  If that is your intent you can use the IGV desktop ```#gffTags``` directive at the beginning of the file to have the contents parsed and added as feature attributes.   Otherwise it will be parsed for a name property only, and the string stored as the attribute "nameField".   The screenshots below illustrate the difference.  
<img width="405" alt="Screen Shot 2020-03-27 at 9 16 12 AM" src="https://user-images.githubusercontent.com/933148/77776701-a85f7200-700b-11ea-9d30-1fe3bbfc6a6b.png">
<img width="757" alt="Screen Shot 2020-03-27 at 9 15 51 AM" src="https://user-images.githubusercontent.com/933148/77776703-a9909f00-700b-11ea-937c-dc62c87dac39.png">

**Comment by petermchale** [comment]
@jrobinso I'm loading igv.js via a HTML script tag (in your flask server). So I would need a URL for an updated `igv.min.js` to test your commits. 

This makes me think that it would be easier for you and me if I were using the `http-server` that comes packaged with this repo, since then I wouldn't need to request a HTTP link. Would you agree?

**Comment by petermchale** [comment]
Yes, I was using the `trackclick` event API: 

```
            browser.on('trackclick', function (track, popoverData) {
                console.log('track.type = ', track.type)
                console.log('track.url = ', track.url)
                console.log('popoverData =', popoverData)

                if (!popoverData || !popoverData.length) {
                    return false // no popover
                }

                if (track.type === 'annotation' || track.type === 'alignment') {
                    let markup = "<table class=\"igv-popover-table\" style=\"width: 600px;\">";
                    popoverData.forEach(function (nameValue) {
                      if (nameValue.name) {
                        // we have a name-value pair
                        markup += "<tr><td class=\"igv-popover-td\">"
                                  + "<div class=\"igv-popover-name-value\" >"
                                  + "<span class=\"igv-popover-name\">" + nameValue.name + "</span>"
                                  + "<span class=\"igv-popover-value\" style=\"max-width: 600px;\">" + nameValue.value + "</span>"
                                  + "</div>"
                                  + "</td></tr>"
                      } else {
                        // not a name-value pair
                        markup += "<tr><td>" + nameValue.toString() + "</td></tr>";
                      }
                   })
                   markup += "</table>"
                   return markup
                }

                return undefined // default popover rendering
             })
```

**Comment by jrobinso** [comment]
You would still need a link,  sorry I should have included it

```
<script type="text/javascript" src="https://igv.org/web/snapshot/dist/igv.min.js"></script>
```

**Comment by petermchale** [comment]
Would the build step at https://github.com/igvteam/igv.js#building not generate an updated igv.min.js that incorporates the commits you made to this repository?

**Comment by jrobinso** [comment]
That should work fine.

You can avoid the need to build by using the snapshot build, available
here:  https://igv.org/web/snapshot/dist/igv.min.js

**Comment by petermchale** [comment]
The following works. Thanks for resolving the issue. 

> @petermchale I just pushed a fix for this. I assume you are using a track click event here to get popoverData, however if you are not please let me know how you are getting the popover data.
> 
> The name field of your bed file looks like a gff attribute string. If that is your intent you can use the IGV desktop `#gffTags` directive at the beginning of the file to have the contents parsed and added as feature attributes. Otherwise it will be parsed for a name property only, and the string stored as the attribute "nameField". The screenshots below illustrate the difference.
> <img alt="Screen Shot 2020-03-27 at 9 16 12 AM" width="405" src="https://user-images.githubusercontent.com/933148/77776701-a85f7200-700b-11ea-9d30-1fe3bbfc6a6b.png">
> <img alt="Screen Shot 2020-03-27 at 9 15 51 AM" width="757" src="https://user-images.githubusercontent.com/933148/77776703-a9909f00-700b-11ea-937c-dc62c87dac39.png">
