### ISSUE TITLE
igv.js in react

### ISSUE THREAD

**Issue by shihai832** [igvteam/igv.js#1076]
Can igv.js be used with react? if so, is there something I can download?

**Comment by jrobinso** [comment]
Many people use igv.js with react.  I don't understand what you mean "is
there something I can download".

**Comment by shihai832** [comment]
I mean if there is an example you are aware that I may find in github to
get me start?

Thanks,
shihai

**Comment by bw2** [comment]
A number of previous Issues have examples such as 
https://github.com/igvteam/igv.js/issues/891#issuecomment-552225941

**Comment by jrobinso** [comment]
Thanks @bw2 .  Sorry @shihai832 I thought I had responded but I see that I have not.  A web search "igv.js and react" brought this up, looks like what you need:  https://github.com/eweitz/igv.js-react

**Comment by shihai832** [comment]
Thanks a lot
