### ISSUE TITLE
Support GWAS Manhattan plots

### ISSUE THREAD

**Issue by qpyuan** [igvteam/igv.js#1078]
Hi, I made a a simple GWAS file ("test.gwas") with columns "CHR", "BP", "SNP",	"P". After I load this "test.gwas" file to the standalone IGV under Windows 10, the manhattan plot was displayed nicely as I expected. My "test.gwas" file contains:
CHR	BP	SNP	P
chr1	865584	G/A	0.32191
chr1	865738	A/G	0.38702
chr1	874336	T/G	1
....

But when I put the following setting for igv.js, I couldn't get anything displayed (I can get sequence reads displayed if I use bam files in a similar setting). My track setting for igv.js was:
tracks: [
                {
                    format: 'gwas',
                    url: '/test.gwas', 
                    indexed: false,
                    name: 'LNG GWAS'
                }
            ]

Please let me know the correct setting for display manhattan plot  with gwas file.

Thanks,

qpyuan

**Comment by jrobinso** [comment]
@qpyuan Manhattan plots are not supported in igv.js.   Supported track types are documented here.  I will rename this issue to "support gwas manhattan plots".

**Comment by jrobinso** [comment]
@qpyuan This will be supported in the next release, or now if you want to pull and build.

**Comment by qpyuan** [comment]
Thanks.
