### ISSUE TITLE
igv.js hanging on latest version

### ISSUE THREAD

**Issue by anderspitman** [igvteam/igv.js#1082]
Have there been any breaking changes to the config API in the past 6 months or so? We have a barebones HTML wrapper for igv.js (you can see the version I'm trying to get working here: https://github.com/anderspitman/igv-static/blob/update-igv/index.html). All it does is take the IGV config as a URL parameter config= in the JSON format, and passes it to IGV. This has been working well, but we're running into problems with certain cram files, which seem to be fixed in the latest version. However, it's now hanging. Here's an example URL you can use to observe the behavior:

[Link 1](https://s3.amazonaws.com/static.iobio.io/stage/igv.iobio.io/index.html?config={%22showIdeogram%22:true,%22reference%22:{%22fastaURL%22:%22https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta%22},%22locus%22:%22chr21:45712947-45713007%22,%22tracks%22:[{%22name%22:%22Variants%22,%22type%22:%22variant%22,%22format%22:%22vcf%22,%22url%22:%22https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz%22},{%22type%22:%22alignment%22,%22url%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam%22,%22indexURL%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam.bai%22,%22name%22:%22Proband%22},{%22type%22:%22alignment%22,%22url%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam%22,%22indexURL%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam.bai%22,%22name%22:%22Mother%22}]})

And here's an example with the old version that works fine:

[Link 2](https://igv.iobio.io/?config={%22showIdeogram%22:true,%22reference%22:{%22fastaURL%22:%22https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta%22},%22locus%22:%22chr21:45712947-45713007%22,%22tracks%22:[{%22name%22:%22Variants%22,%22type%22:%22variant%22,%22format%22:%22vcf%22,%22url%22:%22https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz%22},{%22type%22:%22alignment%22,%22url%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam%22,%22indexURL%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam.bai%22,%22name%22:%22Proband%22},{%22type%22:%22alignment%22,%22url%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam%22,%22indexURL%22:%22https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam.bai%22,%22name%22:%22Mother%22}]})

**Comment by jrobinso** [comment]
@anderspitman Breaking api changes will be indicated by a change to major number.  There have been none in the last 6 months.

Both links are working for me, although there are some long latency delays at times with the bam (note those are bams, not crams).     Do you have something that hangs reliably?   Also, you mentioned "certain cram files",   if cram is the issue provide a link with a cram file if possible, it uses a different library, although there have been no changes in the last 6 months.

**Comment by jrobinso** [comment]
OK I've now observed both links hanging.   There are some long latencies with the Amazon requests, I don't know if its an igv.js bug or network issue.   See screenshot.     Investigating

<img width="1681" alt="Screen Shot 2020-03-26 at 3 11 18 PM" src="https://user-images.githubusercontent.com/933148/77701775-44d63580-6f74-11ea-82bd-add86967df1e.png">

**Comment by jrobinso** [comment]
In the time it took to compose the last comment the server responded and both links are now working.   This is strange.  How long have you observed this?  If you're able to test with locally hosted files please try that and let me know.    I'll setup some tests.   And also, are you using released versions of igv.js, or building from a release tag?   There are no release numbers on these so I don't know what I'm testing.

**Comment by jrobinso** [comment]
Well now both links are really snappy.

**Comment by anderspitman** [comment]
We've pretty much always had intermittent issues with igv.js. It usually manifests as tracks failing to load. It's never been consistent enough or high enough priority to debug, but we thought we had identified a consistent failure mode with the "certain crams" I mentioned. But we're now observing those files sometimes working even on the old version. The 2nd link above is running version 2.4.1, loaded from the jsdelivr link provided in the igv.js readme. I'll see if I can track down the other version.

**Comment by anderspitman** [comment]
**1st link is 2.4.1

**Comment by anderspitman** [comment]
Unfortunately it's not entirely clear which version we're currently running in production. Best guess is a git build from 2019-01-17 (to fix cram support, coincidentally).

**Comment by anderspitman** [comment]
We don't necessarily need to worry about that older unofficial release, unless it's helpful for you. I'll try testing 2.4.1 with locally hosted files (bams and crams) and report back on that.

**Comment by jrobinso** [comment]
What I observed when it was hanging was very slow latency on those S3 buckets.   I don't know why your S3 buckets should be slower than anyone else's but requests would just hang in "pending" state for up to a minute or more.    I think you next step is the right one, try with local files or rather files hosted on a local server.     

Yes we don't need to worry about the older releases.

**Comment by jrobinso** [comment]
@anderspitman I've been trying your 2 test links periodically and occasionally they are slow, then a few minutes later fine.  No pattern wrt link 1 vs link 2.   I don't know if this is productive at the moment, as I'm sure you are aware the internet generally is at max capacity now.   

I am using this opportunity to look for bottlenecks, deadlocks, etc.

**Comment by jrobinso** [comment]
@anderspitman I have a theory on this case, which might also apply to your other cases.  I assume those VCF files are indexed, but you don't supply an indexURL.   Try supplying one, like this

        "tracks": [{
            "name": "Variants",
            "type": "variant",
            "format": "vcf",
            "url": "https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz",
            "indexURL": "https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz.tbi"
        }

**Comment by anderspitman** [comment]
@jrobinso thanks for the continued debugging. I'm pretty sure we're always provided the indexURL, but I'll double check

**Comment by jrobinso** [comment]
It wasn't in the link you sent me to debug, adding it made a big difference.

**Comment by anderspitman** [comment]
Oh I misread that and thought you were referring to the alignment indexes. I agree, it appears to be working great when I set the tbi. Any guesses what's going on here?

**Comment by jrobinso** [comment]
Yes, as you didn't supply an index it loaded the entire VCF.    This was
also preventing connections for the alignments proceeding at times, they
were held in "pending" state until the VCF was loaded.  I'm not sure why
that is, the browser should allow up to 6 simultaneous connections, but it
appeared to be the case.

**Comment by anderspitman** [comment]
That makes sense, but any idea why I'm only seeing that behavior with the newer version?

Also I didn't realize that S3 doesn't support HTTP2, which is disappointing.

**Comment by jrobinso** [comment]
I don't recall how old your other version is, at one point we tacked on
".tbi" if the index was missing.   That was dropped some time ago, it
causes lots of problems, however, particularly with dropbox and google
drive but also signed urls of all stripes, in addition to complex code.
   I'm looking at restoring the "tbi" case in limited circumstances, but
it's very hacky to try to do this.    On local files with the
desktop application it's easy, just check that the file exists.

So at one point you could get away with this for your URLs, although the
indexURL has always been required.    I'm looking at printing console
warnings when vcf.gz files are encountered without an index,  that would
have helped in this case.   I think a popup error message would be too
intrusive.    Likewise I don't think we should require them,  some VCF
files are small.

**Comment by anderspitman** [comment]
Makes sense. We've encountered very similar issues in the past. In any case, I'm pretty sure we've discovered the root cause of this issue. Thanks!
