### ISSUE TITLE
Show arc with bedpe file

### ISSUE THREAD

**Issue by chuckzzzz** [igvteam/igv.js#1083]
Hi, 

I am trying to show arcs with bedpe file. Based on #828 , this feature is supported after 2.1 release. I have already read the igvwiki page and load the file with the following configurations. However, the bedpe files are not displayed as anticipated.  

A screenshot of what's displayed currently:
![screenshot](https://user-images.githubusercontent.com/39171423/77992922-ed212c80-72db-11ea-8acf-efbbca7dbaa9.jpg)

Current configuration:
    type:"annotation",
    format:"bedpe",
    name:cluster_name+"_bedpe",
    url:bedpe_file,

Version of igv.js used:
 <script src="https://cdn.jsdelivr.net/npm/igv@2.4.0/dist/igv.min.js"></script>

Thanks!

**Comment by jrobinso** [comment]
I can't see your screenshot.   Please zip up a reproducible test case

**Comment by jrobinso** [comment]
Sorry, didn't mean to close that.

**Comment by jrobinso** [comment]
Please try track type "interaction", not "annotation".     BTW where to you see that this is supported from 2.1?

**Comment by chuckzzzz** [comment]
Hi. Thanks for the quick reply. It seems like GitHub is taking a while for the screenshot to upload. 

On issue #828 you said: 
"Hi, we don't yet support arcs from bed files, only bedpe files. This is scheduled for the 2.1 release early in the new year." 
I assume this means the bedpe files, if not both, can do the arc thing after 2.1 release.

**Comment by chuckzzzz** [comment]
I tried the "interaction" type and it worked. Thanks! 
I did not see this type being mentioned in the wiki. Maybe it's helpful to mention it. 

Thanks once again!

**Comment by chuckzzzz** [comment]
Hi, one additional question before the issue closes. 

Where can I find relevant documentation for "interaction" type since it's not mentioned in the wiki? For example, can I adjust the height of the arcs or flip the arcs' opening?

Thanks!

**Comment by jrobinso** [comment]
I will work on some documentation, this was never officially released
despite the intention to do so.   In the meantime here's what you can set,
arcOrientation takes a boolean.

arcOrientation      // true for up, false for down
thickness           // default is 2
color                      // default is "rgb(180,25,137)"

**Comment by chuckzzzz** [comment]
Great thanks! Can I also adjust the height of the arcs?

**Comment by jrobinso** [comment]
Adjust the height of the track.
