### ISSUE TITLE
Support for continuation-based APIs in REST calls

### ISSUE THREAD

**Issue by kbruskiewicz** [igvteam/igv.js#1089]
To prevent bad actors from attempting to get gigabytes worth of data at once from a single call, our REST API uses continuations, and passes a 'continuation token' which can be evaluated to the next batch of data that is within a given region but smaller than the size of that region total.

So for instance, if I query for a 10,000bp region, the API will first pass one call of up to 5000 SNPs with a continuation token, and I would have to call the API again with that token to get the remaining 5000 SNPs.

Would it be possible to add a way of overriding the query-handler in e.g. a sourceType like CustomServiceReader to provide an implementation that can use such calls?

**Comment by jrobinso** [comment]
This is too specialized a use case for me to take on.  I think what makes sense is to allow a custom "source" object for a track, in place of a url.   The object would need to implement 2 functions,  a constructor that takes the track "config" as an argument,  and the readFeatures(chr, start, end) method.   This would provide maximum flexibility.    The "CustomServiceReader" could be used as a template to get started.

**Comment by kbruskiewicz** [comment]
Would a possible point of control being passing in a new 'load' type? For instance, CustomServiceReader currently uses `igvxhr.load`, but at the same level of scoping there is `loadJson`, `loadArrayBuffer`, `loadString`... the addition would be a config parameter called something like `loader` with `igvxhr.load` being the default.

**Comment by jrobinso** [comment]
No, that would be too disruptive,  however in my proposal you will be supplying a source object, it can do anything you want, including not loading anything at all just returning random features.

**Comment by jrobinso** [comment]
I've pushed an example of a custom "reader" to dev/custom-reader.html and examples/custom-reader.html.    It allows you to specify a  "reader" object with a new ```reader``` track property. 
This is work in progress, and won't get released immediately.   I have to pivot to IGV desktop now,  but the implementation is unlikely to change so you can start using it from the snapshot.   

You can implement your continuation / paging strategy in your reader, or anything else you need to do.  It is the most general extension point available.  The readFeatures method should return ```{chr, start, end}``` at a minimum,  ```{chr, start, end, value}``` for track types needing numeric values (e.g. pvalues in GWAS).   Other common properties are ```name``` and ```color```.  **Important**: coordinates are UCSC "zero" style, so first base in the genome is start=0, end=1.

The "config" object passed to the reader is the configuration object for the track.  It is suggested that you add any custom properties your reader will need to an embedded object  (e.g. ```confg.readerProperties```  to avoid name conflict with track properties.   This detail might change before ultimate release.

Example
```
    /**
     * A custom feature reader implementation
     * Required methods:
     *    constructor
     *    readFeatures
     */
    class CytobandReader {

        constructor(config) {
        }

        async readFeatures(chr, start, end) {

            const response = await fetch(`https://lk85l6ycte.execute-api.us-east-1.amazonaws.com/dev/testservice/bands?chr=${chr}&start=${start}&end=${end}`,
                {
                    headers: {'Content-Type': 'application/json'}
                }
            );
            if (!response.ok) {
                throw Error(response.statusText);
            } else {
                return response.json();
            }
        }
    }


    const config = {
        genome: "hg38",
        tracks: [
            {
                name: "Cytobands",
                type: "annotation",
                displayMode: "collapsed",
                reader: new CytobandReader({})
            }
        ]
    }

    igv.createBrowser(igvDiv, config)
        .then(function (b) {
            console.log("IGV browser created");
        })
```

**Comment by kbruskiewicz** [comment]
Thank you, this has worked well for me.

**Comment by kbruskiewicz** [comment]
@jrobinso is it possible to override the behavior where IGV dispatches multiple queries for data outside the visibility window?

Rather than IGV dispatching multiple queries, I want to call the data within the extended window directly in a single call.

**Comment by jrobinso** [comment]
@kbruskiewicz  I'm not following you.  What do you mean by "multiple queries", and also "data outside the visibility window"?     There is no concept of an "extended window", what exactly do you want to do?

**Comment by kbruskiewicz** [comment]
Nevermind, the error was on my end.

**Comment by jrobinso** [comment]
@kbruskiewicz can this be closed?
