### ISSUE TITLE
Support for visualizing multi-sample vcfs

### ISSUE THREAD

**Issue by man4ish** [igvteam/igv.js#1091]
Hi,
I am using below javascript code for visualizing multisample vcf but it does not seem to be working. 
Below are links for the data source.

**location for mutlisample vcf:** https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjfzNHEouHoAhWxknIEHW3yBbUQFjAAegQIAhAB&url=ftp%3A%2F%2Fftp.1000genomes.ebi.ac.uk%2Fvol1%2Fftp%2Fphase3%2Fintegrated_sv_map%2FALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf.gz&usg=AOvVaw0tTt5eHzpoWSwCwp-EkYXi

**location for reference genome:** https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwi3tYn8ouHoAhWGgnIEHfpLCokQFjAAegQIARAB&url=ftp%3A%2F%2Fftp.ncbi.nlm.nih.gov%2Frefseq%2FH_sapiens%2Fannotation%2FGRCh37_latest%2Frefseq_identifiers%2FGRCh37_latest_genomic.fna.gz&usg=AOvVaw20VimMXhNziN2JxflMtm8t

**IGV code is below:** 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
    <title>igv.js</title>
    <script src="dist/igv.min.js"></script>
</head>
<body>
<p>
<h1>GNOMAD VCF file</h1>
<div id="igvDiv" style="padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray"></div>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        var options =
            {
                // Example of fully specifying a reference genome.  We could alternatively use  genome: "hg19"
                reference:
                    {
                        id: "hg19",
                        fastaURL: "http://localhost:8000/data/GRCh37_latest_genomic.fna"
                    },              
                tracks:
                    [
                        {
                              type: "variant",
                               format: "vcf",
                               url: "http://localhost:8000/data/ALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf.gz",
                               indexURL: "http://localhost:8000/data/ALL.wgs.mergedSV.v8.20130502.svs.genotypes.vcf.gz.tbi",
                              name: "snps.vcf",
                               squishedCallHeight: 1,
                              expandedCallHeight: 4,
                              displayMode: "squished",
                             visibilityWindow: 1000
                      }
                   ]
            };
        var igvDiv = document.getElementById("igvDiv");
        igv.createBrowser(igvDiv, options)
            .then(function (browser) {
                console.log("Created IGV browser");
            })
    })
</script>
</body>
</html>

Regards

**Comment by jrobinso** [comment]
Could you please explain more fully what you mean by "not working"?  Are there any console errors?  Also, what version of IGV are you using?

**Comment by man4ish** [comment]
It just show one track and no sample information. Below is image from web output.

![multi_sample](https://user-images.githubusercontent.com/6385968/79055330-3f3a4a00-7c1a-11ea-8693-221d7a30974d.png)

**Comment by jrobinso** [comment]
That's perfectly normal.  do you see the message "Zoom in to see features"?
