### ISSUE TITLE
no effect after changing resources/genomes.json

### ISSUE THREAD

**Issue by iiiir** [igvteam/igv.js#1093]
Hi,
Sorry for the naive question. I really want to get this work but have not been successful after try many times.

I was able to set up igv-webapp.
By running 
`npm start` I can get it running. However I have two issues:
1. except hg19 (the default?), everything else will give error:
![image](https://user-images.githubusercontent.com/4137873/79183788-4fdbf300-7dc7-11ea-8417-04cdb53a8490.png)

2. I cannot change any of the genome list (or the track lists):
I modified my `resources/genomes.json` to by deleting all other genomes:
![image](https://user-images.githubusercontent.com/4137873/79183896-9c273300-7dc7-11ea-987c-a85066f0fba1.png)

but the genome drop down menu will not change. 

similarly i modified `resources/tracks/trackRegistry.json`, and will not have effects.

Thank you very much,
Shuoguo

**Comment by jrobinso** [comment]
@iiiir I see you closed the issue, did you resolve your problem?
