### ISSUE TITLE
invalid file signature while loading track from uploaded file

### ISSUE THREAD

**Issue by sumeet030990** [igvteam/igv.js#1094]
I have created a functionality where user will upload a file(.gz file) and the tracks will get loaded from that
But I am getting the error 

> Error: **invalid file signature:60,104**
>     at Zlib.Gunzip.decodeMember (igv.js:14690)
>     at Zlib.Gunzip.decompress (igv.js:14643)
>     at arrayBufferToString (igv.js:18831)
>     at igv.js:18771

My code:
```
let config= {
            "name": "Homo_sapiens.GRCh38.99.abinitio.gff3.gz",
            "format": "refgene",
            "url": "http://127.0.0.1:8000/storage/uploads/5/Homo_sapiens.GRCh38.99.abinitio.gff3.gz",
            "visibilityWindow": -1,
            "removable": false,
            "order": 1000000
        };

browserGlobal.loadTrack(config); 
```

**Comment by jrobinso** [comment]
First the format should be gff3, not "refgene", assuming the file is a gff3 file.  

Could you zip and upload a reproducible test case?

**Comment by sumeet030990** [comment]
changed the format to gff3, still getting the same issue,

Files that I am trying to upload
[5.zip](https://github.com/igvteam/igv.js/files/4491038/5.zip)

**Comment by jrobinso** [comment]
Try loading your gff from this url and tell me what happens.   If that doesn't work post your complete html file (zipped), or at least the complete javascript code as you did above (with the url below).

https://www.dropbox.com/s/d8kwa1cyotpiswz/Homo_sapiens.GRCh38.99.chromosome.12.gff3.gz?dl=0

**Comment by jrobinso** [comment]
Check the content type on your server's response, it should be ```application/octet-stream```.  If its gzip that would cause this error, the browser would gunzip the file before igv.js ever saw it.    Otherwise carefully check the response headers from the dropbox hosted file with what your server is sending.   I assume the dropbox hosted link is working, it does for me.

**Comment by sumeet030990** [comment]
working 
```
let config= {
            "name": "Homo_sapiens.GRCh38.99.abinitio.gff3.gz",
            "format": "gff3",
            "url": "https://www.dropbox.com/s/d8kwa1cyotpiswz/Homo_sapiens.GRCh38.99.chromosome.12.gff3.gz?dl=0",
            "visibilityWindow": -1,
            "removable": false,
            "order": 1000000
        };

browserGlobal.loadTrack(config); 
```


not working 
error: invalid signature
```
let config= {
            "name": "Homo_sapiens.GRCh38.99.abinitio.gff3.gz",
            "format": "gff3",
            "url": "http://127.0.0.1:8000/storage/uploads/5/Homo_sapiens.GRCh38.99.abinitio.gff3.gz",
            "visibilityWindow": -1,
            "removable": false,
            "order": 1000000
        };

browserGlobal.loadTrack(config); 
```

**Comment by jrobinso** [comment]
Yes, there is something wrong with your server.   As I said above, compare the response headers carefully between the working and non-working server.  I suspect its the content-type.   What server are you using?

**Comment by jrobinso** [comment]
Also check the response itself (in Chrome or Firefox developer tools).

**Comment by sumeet030990** [comment]
l```
et config= {
            "name": "Homo_sapiens.GRCh38.99.abinitio.gff3.gz",
            "format": "gff3",
            "url": "http://127.0.0.1:8000/storage/uploads/5/Homo_sapiens.GRCh38.99.abinitio.gff3.gz",
            "visibilityWindow": -1,
            "removable": false,
            "order": 1000000
        };

browserGlobal.loadTrack(config); 
```
ahh, yes the problems seem to be related to server as
when I am using this URL (mentioning statically) then its throwing me CORS error
but on my server I have handled the CORS.
all my other Api's are working properly
Can you please shed some light on this.

**Comment by sumeet030990** [comment]
I am only getting error while I am uploading gz file
![gz error](https://user-images.githubusercontent.com/48065274/79719619-987e3980-82fc-11ea-9c85-4bf7e3e24f02.png)

**Comment by sumeet030990** [comment]
if I am extracting the content from gz (inside getting gff3 file) and uploading that, then it's working fine. I also tried .tbi & .bb file those are also working fine, jut getting error with .gz file

**Comment by jrobinso** [comment]
@sumeet030990 Are you reading the responses I am giving you?  I have already explained to you how you might go about debugging this.  It is a problem with your server.    Please try what I have suggested already before posting replies.
