### ISSUE TITLE
Broken dropbox url for examples/gwas.html data

### ISSUE THREAD

**Issue by RichardBruskiewich** [igvteam/igv.js#1095]
Data not on dropbox at specified location?

**Comment by jrobinso** [comment]
Sorry about that.  Fixed.   The example file was gunzipped, edited, and regzipped.  To DB this was a new file, and created a new hash.   The filename in a DB url is meaningless, you can put anything you want there,  I had forgotten this.

**Comment by RichardBruskiewich** [comment]
> Sorry about that. Fixed. The example file was gunzipped, edited, and regzipped. To DB this was a new file, and created a new hash. The filename in a DB url is meaningless, you can put anything you want there, I had forgotten this.

No worries Jim. Just reported this so it could be fixed, since the project we are working on at our side (with Broad) needs the GWAS view.  BTW, IGV is great! Love it!
