### ISSUE TITLE
Features count upper limit is hardcoded 

### ISSUE THREAD

**Issue by onursumer** [igvteam/igv.js#1098]
It might be better to make this value configurable: https://github.com/igvteam/igv.js/blob/2962eec3a3d4f7681f5cd0736574a1dfeb82d746/js/feature/featureSource.js#L155

In cBioPortal we ran into [this issue](https://github.com/cBioPortal/cbioportal/issues/7416) after upgrading to the latest igv.js version. We needed to fork the repo and [manually change](https://github.com/cBioPortal/igv.js/pull/1/commits/7463b89b6aecf2028767b88e28dc3b0ec1d245be) the hardcoded value as a temporary workaround.

**Comment by jrobinso** [comment]
Ah yes, good point.  I had forgotten about that.  We could probably just eliminate this, but at least make it configurable.

**Comment by jrobinso** [comment]
This issue should be resolved with 2.7.0, limit is now MAX_SAFE_INTEGER
