### ISSUE TITLE
IGV Layout exceeded div

### ISSUE THREAD

**Issue by yaronmiz** [igvteam/igv.js#1100]
Hi,
I am embedding IGV browser in a div with a limited width/height. I noticed that IGV exceeded the div area and slides outside.
Is it by design/bug? how to overcome this?
![image](https://user-images.githubusercontent.com/14225261/80713977-f5e46880-8afc-11ea-846a-208213b80c76.png)

**Comment by jrobinso** [comment]
What is your screenshot illustrating?   

It will be difficult to give you advice without access to the page, is there a public page you can point us to?

**Comment by turner** [comment]
The igv.js browser has a minimum width of approximately 572 pixels. Height will increase or decrease based on how many tracks are loaded.
