### ISSUE TITLE
Empty roi bed might interrupt the main track display 

### ISSUE THREAD

**Issue by SimonLi5601** [igvteam/igv.js#1101]
If the ROI bed was pushed, but the file doesn't exist or simply empty, it will prevent the main track to display. In a previous version, e.g. 2.2.3  it's quite optional if the bed doesn't exist, just ignore it.

**Comment by jrobinso** [comment]
Can you be a little more specific.  What do you mean by "pushed"?

**Comment by SimonLi5601** [comment]
Sorry, it seems a false alarm due to my local environment. I will close this.
