### ISSUE TITLE
Fix typos in `api-2.0/Browser-Control-2.0.md`

### ISSUE THREAD

**Issue by serverhorror** [igvteam/igv.js#1104]
There are a few typos in `api-2.0/Browser-Control-2.0.md` that break the formatting.

Not sure how to send this as a PR but here's a diff you can apply if you clone the wiki locally:

* [Fix_typos_in_`api-2_0_Browser-Control-2_0_md`.patch.txt](https://github.com/igvteam/igv.js/files/4598251/Fix_typos_in_.api-2_0_Browser-Control-2_0_md.patch.txt)

Here's the same thing as text only:

    Index: api-2.0/Browser-Control-2.0.md
    IDEA additional info:
    Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
    <+>UTF-8
    ===================================================================
    --- api-2.0/Browser-Control-2.0.md	(revision 34a12015fae39890fb45eb38b561d9e188e71fca)
    +++ api-2.0/Browser-Control-2.0.md	(date 1588930625477)
    @@ -102,7 +102,7 @@
     Zoom in by a factor of 2 
     ```
         browser.zoomIn();
    -``
    +```
     Zoom out by a factor of 2 
     ```
         browser.zoomOut();
    @@ -116,29 +116,27 @@
     ```
        
     To target a specific igv browser instance
    -
     ```
         browser.visibilithChange();
    -    
    +```    
        
     To support integration with the host app the following browser method is provided: 
     
    -* setCustomCursorGuideMouseHandler(mouseHandler)
    +* `setCustomCursorGuideMouseHandler(mouseHandler)`
     
     #### setCustomCursorGuideMouseHandler ####
     
     Pass genomic location and mouse location with respect to trackContainer to host app.
     The data is transmitted as the cursor guide is manipulated across the track container.
     
    -```
     Parameters:
    -bp - cursor-guide location. base-pair units.
    -start - track start location. base-pair units.
    -end - track end location. base-pair units.
    -interpolant - cursor-guide location. 0 - 1 units.
    -
    +* `bp` - cursor-guide location. base-pair units.
    +* `start` - track start location. base-pair units.
    +* `end` - track end location. base-pair units.
    +* `interpolant` - cursor-guide location. 0 - 1 units.
    +```
         browser.setCustomCursorGuideMouseHandler(({ bp, start, end, interpolant }) => {
    -        
    +        //...    
         });
     ```

**Comment by turner** [comment]
Thanks for find this. We've made the edits.
