### ISSUE TITLE
Option to show/hide bam and coverage track

### ISSUE THREAD

**Issue by highlei** [igvteam/igv.js#1106]
In IGV desktop, when I load a bam file, I will get two tracks: "mRNA.bam" and "mRNA.bam Coverage" [fig1.jpg]. I can remove mRNA.bam track by click the track name [fig2.jpg].  Then I will just keep bam coverage track [fig3.jpg].
How can I do like this in igv-webapp?
![fig1](https://user-images.githubusercontent.com/38762527/81670164-cf69ea00-9479-11ea-97cf-5086a0858ae1.jpg)
![fig2](https://user-images.githubusercontent.com/38762527/81670144-c7aa4580-9479-11ea-8397-6e5326bc45e1.jpg)
![fig3](https://user-images.githubusercontent.com/38762527/81670156-cc6ef980-9479-11ea-94a2-fa665b9a5905.jpg)

**Comment by jrobinso** [comment]
Hi, currently the webapp does not have this option.    I'm unsure if you are asking about igv.js the javascript component, or the webapp at igv.org, but neither have this option currently.

**Comment by jrobinso** [comment]
renamed issue

**Comment by turner** [comment]
PR https://github.com/igvteam/igv.js/pull/1169
