### ISSUE TITLE
Track data as File / Blob or Buffer objects

### ISSUE THREAD

**Issue by gungorbudak** [igvteam/igv.js#1107]
I came up with the following function `readFileAsFileObject` that does some preprocessing and the result can be visualized by IGV.js for a `GFF.GZ` file but the same method doesn't seem to work for `BAM` and `BAI` data. Browser loads it silently but there is nothing shown on the browser (IGV Desktop can open and visualize). Is there an option to do so, I need to provide a local file path like `/Users/path/to/data` to define some tracks.

Function doing the preprocessing:

```javascript
const fs = require("fs");
const atob = require("atob");

function readFileAsFileObject(path, contentType) {
  const content = fs.readFileSync(path, { encoding: "base64" });
  const data = atob(content);
  const uInt8Array = new Uint8Array(data.length);
  for (let i = 0; i < data.length; ++i) {
    uInt8Array[i] = data.charCodeAt(i);
  }
  const blob = new Blob([uInt8Array], { type: contentType });
  return new File([blob], path, { type: contentType });
}
```

Working `GFF.GZ` example:

```javascript
...
        name: "Genes",
        url: readFileAsFileObject("/path/to/file.gff.gz", "application/gzip"),
        displayMode: "EXPANDED",
        nameField: "gene",
        height: 150,
        removable: false,
...
```

The `BAM` and `BAI` example:

```javascript
...
        name: "Alignments",
        type: "alignment",
        format: "bam",
        url: readFileAsFileObject("/path/to/file.bam", "application/gzip"),
        indexURL: readFileAsFileObject("/path/to/file.bam.bai", "application/octet-stream"),
...
```

Thanks!

**Comment by jrobinso** [comment]
I'm not sure what you are running in node and what you are running in the browser.  You can't use "fs" in the browser obviously, and you can't use file paths to read local files in a browser.   

If you are asking a node question, the mime type for bams should not be application/gzip, rather application/octet-stream,  or nothing at all if that's an option in node.

**Comment by jrobinso** [comment]
To elaborate on the mime type, in the browser setting "application/gzip" will cause the browser to gunzip the bam file before the javascript sees it.   A bam file is not meant to be gunzipped.   Node might be doing the same thing, I can't say for sure, but that is my theory.

**Comment by gungorbudak** [comment]
@jrobinso The way I obtained these MIME types was through the below command (on macOS):

```
$ file -b --mime-type file.bam    
application/gzip
```

But I actually figured out that the issue was I mixed up the genome version in the reference file and in the alignment file. After correcting it, IGV.js could load the file. IGV desktop didn't care that though.

I tried both `gzip` and `octet-stream` for the `BAM` file and both worked. It could be that there is no difference for the code.

Thanks much!

**Comment by jrobinso** [comment]
Yes macOS will think a bam is gzip mime type, because it is in fact gzipped.  See the bam spec of more details  But if a server returns "gzip" as the type to the browser it will gunzip it before javascript sees it.   This is a known problem with certain apache configurations.   I have no idea what node does, apparently nothing, which is what we want.

I'm unclear what you are doing exactly, are you loading files in a browser, or is this a node application?   Do you have this work in github?   I would like to know, it sounds interesting.

**Comment by gungorbudak** [comment]
I see I’ll take a note of that behavior. Thanks.

I’m investigating genome browser options for a desktop app built with Electron. It is not on GitHub but it is still JavaScript with reading file from disk instead of a server. It’s for small genomes so the reference can be packed into the software. I’ll also look at the performance as well by loading many tracks.

**Comment by jrobinso** [comment]
OK, cool.  I wrapped igv.js in electron once several years ago, didn't pursue it.

We have another project,  github.com/igvteam/igv-reports, that takes bam and other data and packs it into the html page itself.   To support this there's an option to supply the data for tracks as a data uri.
