### ISSUE TITLE
gCNV track needs example data

### ISSUE THREAD

**Issue by brwnj** [igvteam/igv.js#1108]
I can't seem to recreate anything resembling the image in #1055. If you give the gcnv track type a series similar to what's stated in the initial pull req you get disjointed horizontal lines. Is there something I'm missing to connect the points?

Edit: It seems there was data available at some point at https://github.com/igvteam/igv.js/blob/7c8dab50408022ebfab7cbb3a6889c5b16c1fa27/dev/gcnv.html#L34

Edit 2:
Your intervals need to immediate proceed the previous, e.g.:

```
chr1	1	2	99	80	75
chr1	3	4	87	81	79
chr1	5	6	89	85	81
```

**Comment by jrobinso** [comment]
Perhaps @bw2 can provide us some sample data.

**Comment by bw2** [comment]
@brwnj the track was designed around bed files where each row's chrom-start-end represents an exon. 

This is an example bed file with chr22 data for ~150 samples:
[gcnv_track_example_data.zip](https://github.com/igvteam/igv.js/files/4660372/gcnv_track_example_data.zip)

If you go to  `chr22:23,850,132-23,888,290` it should look like

![image](https://user-images.githubusercontent.com/6240170/82518299-1183d300-9aed-11ea-8061-7577f24ab1ce.png)
with this track config:
```
              {
                type: 'gcnv',
                format: 'gcnv',
                name: 'example track',
                url: '/public/gcnv_track_example_data.chr22.bed.gz',
                indexURL: '/public/gcnv_track_example_data.chr22.bed.gz.tbi',
                height: 200,
                min: 0,
                max: 5,
                autoscale: false,
                highlightSamples: {
                  "RP-1425_BON_B17_29_1_D1_v1_Exome_GCP": "blue",
                  "RP-1425_BON_B18-97_3_D1_v1_Exome_GCP": "red",
                },
                onlyHandleClicksForHighlightedSamples: false,
              },
```

The track draws 2 line segments for each row-sample pair:
[one for the exon](https://github.com/igvteam/igv.js/blob/master/js/gcnv/gcnvTrack.js#L170)
and another one [connecting it to the previous exon](https://github.com/igvteam/igv.js/blob/master/js/gcnv/gcnvTrack.js#L158). 

If you're using gCNV, the gCNV output needs to be post-processed into this bed format. 
(I'll see if I can get the code for this at some point and post it).

**Comment by jrobinso** [comment]
Thanks for the data @bw2 .   I forgot the status of this track, we didn't officially document or release it I guess.   If its stable we can do so for the next release,  I'll defer to you on that.   I'm heads down on the grant renewal, there won't be any releases before mid june barring a must-fix bug.

**Comment by bw2** [comment]
Hi Jim, this track is ready to go, but no rush - whenever you have time to release it works for me. 
I'd like to add these 2 changes at some point, but they can be independent of the release date.
- add the y-axis value to the popup when clicking on a sample, and maybe also the chrom-start-end. Currently it only shows the sample name and line color.
- add a method for updating config settings (for example which samples are highlighted) without needing to remove and recreate the track.
