### ISSUE TITLE
info on session file

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#1109]
Hi Jim!

Just a quick question.
I'm trying to generate a `sessionURL` blob using an external service to feed into igv.js using the query parameters.
So far so good but I have a few questions
- is the blob just base64 encoded? or zlib encoded? (docs say base64, code refers to zlib?)
- which fields should the string contain? I'm assuming we're starting from a json string here.

Sorry if all of this is referenced somewhere, but I can't seem to find it.
Thanks for the info!
Cheers
M

**Comment by jrobinso** [comment]
@matthdsm  The blob is a compressed, uuencoded,  igv.js session json.    The json format is described in the wikis, its the standard config objects but "json-ified" (basically use strings for property names).   Once you have the json string here is the code,  in stringUtils.js, that compresses it.   I could expose this as a tiny NPM node project.   Note the replacements after UUENCODING to make the string safe as a URL parameter.

```
function compressString(str) {
    const bytes = [];
    for (var i = 0; i < str.length; i++) {
        bytes.push(str.charCodeAt(i));
    }
    const compressedBytes = new Zlib.RawDeflate(bytes).compress();            // UInt8Arry
    const compressedString = String.fromCharCode.apply(null, compressedBytes);      // Convert to string
    let enc = btoa(compressedString);
    return enc.replace(/\+/g, '.').replace(/\//g, '_').replace(/=/g, '-');   // URL safe
}
```

**Comment by jrobinso** [comment]
@matthdsm actually you can do this with node and igv-utils,  I just pushed an example here:  https://github.com/igvteam/igv-utils/blob/master/examples/sessionBlob.js.

**Comment by matthdsm** [comment]
Hi Jim

Great! Thanks for the example! It's a huge help!

Cheers
M
