### ISSUE TITLE
[feature request] Arc diagrams with height proportional to value

### ISSUE THREAD

**Issue by mkadlof** [igvteam/igv.js#1114]
Is it possible to add arc diagrams with height proportional to its log(value) to igv.js version? It already works in stand alone version, but would be great if you add it also for website version.

Here is data format example:
```
chr1    3    5    chr1    7    9    2
chr1    6    8    chr1    16    18    1
chr1    10    11    chr1    14    16    3
```

Columns description:
chr1id, begin1, end1, chr2id, begin2, end2, value

And example of expected result:
![image](https://user-images.githubusercontent.com/4080632/83415643-b07aca00-a41f-11ea-8500-384158d2b626.png)

Value is usually integer, but according file spec in general it could be any string:
https://bedtools.readthedocs.io/en/latest/content/general-usage.html#bedpe-format

For more examples look in Fig1. in https://www.sciencedirect.com/science/article/pii/S0092867415015044

**Comment by jrobinso** [comment]
Not currently, I suppose you are the first to request this.    I will add it.

**Comment by mzager** [comment]
Jim, I'm curious if you got a chance to implement this feature...  Thanks for all your contributions.  This is a great project.

**Comment by jrobinso** [comment]
Some support pushed.  Still need "log" option.

**Comment by mzager** [comment]
Jim - Per your recommendation, I began investigating BED formats for storing Cis-coaccessibility networks. I was able to identify one that represents the data well "bigInteract" - https://genome.ucsc.edu/goldenPath/help/interact.html - Example #2.  When compared to the bedpe format this structure seems to have two advantages 1) it can be indexed. 2) it renders the start and end of the arcs as spans/rectangles.  Are you aware of this format / have you considered integrating it?  Thanks again for all your help.  It's very much appreciated.

**Comment by jrobinso** [comment]
@mzager I agree that's the way to go if your data is too large for the non-indexable bedpe format.   RE the rendering, that is a separate consideration orthogonal to the format,  IGV desktop has this as an option I think.    Yes I've investigated it and there is a parser for "interact" although its probably not tested,  you are the first to mention this format.    Could you open a new issue for "support for interact and bigInteract",  I'd like to keep this one on topic and will be finishing it today.   Its nearly finished, I just need to add options to the gear menu.   Here's an example, this is the data (I think) from the CTCF paper referenced somewhere in this thread:  https://igv.org/web/snapshot/examples/bedpe-proportional.html

**Comment by mzager** [comment]
That's great thanks @jrobinso.   The CTCF paper was actually from @mkadlof who I know is still interested in integrating it.  I will open a new issue for "support for interact and bigInteract".  My dataset is significantly larger with some tracks approaching 150mb in bedpe format.  I am currently working on re-encoding the data in biginteract format and would be happy to help getting this feature integrated however you see fit.  Thanks again!

**Comment by jrobinso** [comment]
This is now implemented (not released, but pushed to master).  An example using the CTCF data from the paper referenced above follows.  The example also illustrates other properties you can set.

```
{
                   url: "https://s3.amazonaws.com/igv.org.demo/GSM1872886_GM12878_CTCF_PET.bedpe.txt",
                    type: "interaction",
                    format: "bedpe",
                    name: "CTCF PET - proportional",
                    arcType: "proportional",
                    color: "rgb(0,200,0)",
                    alpha: "0.05",
                    logScale: true,
                    showBlocks: true,
                    max: 80,
                    visibilityWindow: 10000000
                }
```
