### ISSUE TITLE
[Feature Request] Custom groupings and legends for annotation tracks

### ISSUE THREAD

**Issue by kbruskiewicz** [igvteam/igv.js#1115]
Hello Jim,

Currently I'm seeing support for intervals in annotations, however I'm uncertain as to how intervals are stacked or ranked when they overlap on the same segment.

Would it be possible to support custom groupings and orderings of intervals if they happen to exist on the same track, but overlap over the same region? So e.g. all of the features with a given property are on one row, for a different property on another... etc.

Additionally if intervals are threaded in this way, a nice-to-have would be a legend that indexes these rows, however I know that there is already support for named intervals on annotation tracks.

This is a graphic illustration of the above:
![split_track](https://user-images.githubusercontent.com/955221/83434763-eb650980-a3ef-11ea-98a2-138093d23eda.PNG)

**Comment by jrobinso** [comment]
This is fairly complex, the standard solution for this is to break the features into multiple tracks.
