### ISSUE TITLE
Separating identification from name

### ISSUE THREAD

**Issue by kbruskiewicz** [igvteam/igv.js#1116]
Tracks are currently identified by their name, and IGV supports deleting tracks by name. But names seem to override or act as aliases for labels. So if I wanted to enforce a unique ID for tracks, and I wanted a potentially non-unique display label, I can't separate those concerns.

Would it be possible to use a form of labeling separate from the name?

**Comment by loicmasson2** [comment]
I'm not sure what is your use case for non unique display label but you can extend your tracks with whatever you want.
For example I use defaultActive to display a certain set of tracks when my page opens.
```
  tracks.push(
    {
      ....
      // non igv properties
      defaultActive: true,
    },
  );
```
And then instantiate igv with only those tracks.
```
const igvOptions = {
      reference: {
        id: 'hg19',
        fastaURL: referenceGenome.fastaUrl,
        indexURL: referenceGenome.fastaUrlIndex,
      },
      locus,
      tracks: tracks.filter((track) => track.defaultActive),
    };
```

What you can do:
- add a label field to your track.
- list all the labels attached to the css class `igv-track-label`
- override the name text with your new label field

**Comment by jrobinso** [comment]
@kbruskiewicz I've addressed this by generalizing the existing "findTracks" function, and exposing a previously hidden method  "removeTrack".   I've pushed an example to https://github.com/igvteam/igv.js/blob/master/dev/findTracks.html, snippet below.   However before I can release this I need to solve another problem, discovered while testing this.  Removing a track while data is being loaded results in an error.  

```
                const tracksToRemove = browser.findTracks(function (track) {
                    return track.name.includes('H3K27');
                });
                for (let t of tracksToRemove) {
                    browser.removeTrack(t);
                }
```

**Comment by jrobinso** [comment]
@kbruskiewicz To clarify removing tracks by anything other than name is now a 2 step process.  (1) use findTracks to get an array of tracks to remove  (2) iterate over array and call removeTrack for each one.  Above is an example of using a function.   I also introduced a new special property, 'id', which is copied from the track config object to the track.   There is no requirement that "id" be unique among tracks, its just another property, but you can make it unique.   Then, as in the example html referred to above you can find the track you want to remove as 

```
browser.findTracks("id", "1234")
```

Assuming you are sure there is 1 and only 1 match you can just call

```
browser.removeTrack(browser.findTracks("id", "1234")[0]))
```
