### ISSUE TITLE
Force query over cache

### ISSUE THREAD

**Issue by kbruskiewicz** [igvteam/igv.js#1118]
Is it possible to not use caching for a reader?

**Comment by jrobinso** [comment]
At the moment no.   Could you describe your use case?    There are 2 levels of caching, one would be easy to turn off one would be hard.  When an offscreen image is drawn a pointer to the collection of features is drawn to support popup text.   That is the hard one, unless you also wanted to disable popup text.

**Comment by kbruskiewicz** [comment]
The popups are disabled (I overrode the handler).

The use-case is that I have hooks that execute whenever my custom reader completes a query. This corresponds to a shift in the region which implies a shift in the data: using the hook I spill this data  over to another component on the page.

Since I only control the reader but not the feature cache, if there are elements in the feature cache it skips over the reader and my hooks don't fire. Ideally, if I disabled the cache, the reader would always query and then my other behavior would fire.

I'm also exploring using the `locuschange` event but would prefer forcing use of the reader.

**Comment by jrobinso** [comment]
This should be easy, but I'm engaged on other projects right now.  Here's something to try.   Add a config property "disableCache".   The test starting around line 173 of FeatureSource to check the property as follows.  The explicit test for true will have the effect of defaulting to false.   I don't have time to test this right now but it should work, let me know.  Will work on a better implementation later.

```
            if (this.config.disableCache !== true && 
                this.featureCache &&
                (this.static || this.featureCache.containsRange(genomicInterval) || "all" === chr.toLowerCase())) {
                return this.featureCache;
```

**Comment by kbruskiewicz** [comment]
I think it works.
