### ISSUE TITLE
set track height and displayMode on the gene model track of a reference genome 

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1119]
With the hg38 reference genome, a Refseq Genes gene model track is displayed.   It defaults to EXPANDED displayMode, and a trackHeight of 70. 
Is there an option field for setting the displayMode to, for instance, COLLAPSED?  Or maybe there is a function for that in the javascript API?

thanks!

**Comment by jrobinso** [comment]
You would use the full "reference" object instead of the "genome" id
shortcut.

**Comment by paul-shannon** [comment]
Makes sense, thanks Jim.   Is there an easy way to find out all the fields implied by a genome id?  To get all those specs, in order to create a full reference object?

**Comment by jrobinso** [comment]
Here's what we use

https://s3.amazonaws.com/igv.org.genomes/genomes.json

**Comment by paul-shannon** [comment]
all set.  thanks!

**Comment by paul-shannon** [comment]
one more question if I may.  Can you give me a pointer to documentation or filename for javascript API for after the fact manipulation of track height and displayMode?

**Comment by jrobinso** [comment]
Documentation is here: https://github.com/igvteam/igv.js/wiki.  However
there is no API for track manipulation post creation.   Create a new issue
for that, or rename this one.   I don't have a sense of what would be
involved to support that off the top of my head.

**Comment by paul-shannon** [comment]
Let's defer.  If this seems worthy of a request, I'll create a new issue.
Thanks, Jim.
