### ISSUE TITLE
Custom Reference Genome not Loading

### ISSUE THREAD

**Issue by hmgill** [igvteam/igv.js#1120]
Hi, 
I was trying to view my custom genome w/ igv.js, but it seems like there is a problem with loading the fasta and fai files, as nothing loads in the IGV viewer. 

The URLs are given below & the html file is attached. Thanks!
https://sysbio.informatics.iupui.edu/primer_project/genomes/sarscov2/sars_cov_2.fasta.
https://sysbio.informatics.iupui.edu/primer_project/genomes/sarscov2/sars_cov_2.fasta.fai

[sars_igv.txt](https://github.com/igvteam/igv.js/files/4782919/sars_igv.txt)

**Comment by jrobinso** [comment]
It looks like the server at sysbio does not include CORS headers in the responses, or to put it another way they do not allow javascript programs to access those files.  As a workaround you can download the files and host them on the same server you are hosting igv.min.js on, or alternatively if they are public I will just put them on one of our servers and send you a link.

**Comment by hmgill** [comment]
Hi jrobinso, 

Thanks for your response. 
I'll contact my webserver admin to see what solution there is to the CORS issue. Thanks for offering to put them up on one of your servers for the time being; the files are public info. Would it be too much to add two other files for a track as well (below)?
https://sysbio.informatics.iupui.edu/primer_project/genomes/sarscov2/forward_s.bed.gz.
https://sysbio.informatics.iupui.edu/primer_project/genomes/sarscov2/forward_s.bed.gz.tbi
 
Appreciate your help!

**Comment by jrobinso** [comment]
I'm happy to do it but you can also just put all those files in the root directory of your web app (the directory containing sars_igv.html) and reference them by their file name, or in a data subdirectory and reference them as for example
```
data/sars_cov_2.fasta
```
etc.  The paths would be relative to your html page.    This assume you have a server, file URLs won't work.

If you want us to host them give us more information on what they contain, and who owns or produced them for attribution.

**Comment by hmgill** [comment]
Hi, 

Just tried including the relative path and that worked! Maybe I had read it wrong, but I though I came across some material stating only URLs mapping to the data files would work. 

Thanks for all the help

**Comment by jrobinso** [comment]
A relative path is a URL, it is in fact a relative URL.  Maybe we should point this out in the documentation, I will leave this open as a documentation reminder.
