### ISSUE TITLE
auto loading

### ISSUE THREAD

**Issue by shihai832** [igvteam/igv.js#1121]
How do I automatically load genomics and tracks without using the file load? Meaning each time I open browser, it automatically load the some file to display. Thanks, shihai

**Comment by jrobinso** [comment]
I don't understand your question.  igv.js does not have a "file load", that is the responsibility of the enclosing application.   igv.js is just a component.  Are you sure you are posting to the right repository?

**Comment by shihai832** [comment]
When I refresh the igv local site, all the files including the tracks
disappeared. I like to show some tracks and genome as default after I
refresh the site or start the site again. Is there a way to do it?

Shihai

**Comment by jrobinso** [comment]
@shihai832  probably not, but first you need to tell us more about your configuration.  How are you embedding igv.js?   Where are your files located (local file system or from a web server)?  Why don't you just configure the tracks and genomes you want in the IGV config?

**Comment by shihai832** [comment]
File is on local file system. I use the igv.js download from GitHub
directly with "npm start"

Shihai

**Comment by jrobinso** [comment]
@shihai832 No you cannot do this with files on the local file system.   Also I think you are confused, there is no "npm start" script for igv.js, perhaps you mean igv-webapp?  In any event this is not possible.
