### ISSUE TITLE
Travis CI build passes with error

### ISSUE THREAD

**Issue by eweitz** [igvteam/igv.js#1122]
The Travis CI build passes, but the test suite throws an error and exits without having succeeded any tests.

From https://travis-ci.org/github/igvteam/igv.js/builds/699569998:
```
 igv@2.5.5 test /home/travis/build/igvteam/igv.js
> node runTests.js
[log] Loaded 1 chunks out of  1
[log] No index entry for chr: noSuchChromosome
Error: Test run could not finish in 100000ms
    at Timeout.setTimeout [as _onTimeout] (/home/travis/build/igvteam/igv.js/node_modules/node-qunit-puppeteer/index.js:172:58)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
The command "npm test" exited with 0.
cache.2
store build cache
Done. Your build exited with 0.
```

I can reproduce this in my local clone by running `npm install .` then `npm test`.

Any ideas what the issue might be?  

I'm developing support in igv.js for using the Ensembl REST API as a search backend, and having a truly passing build would help me know I haven't broken anything.

**Comment by jrobinso** [comment]
Looking into it.   It looks like one of our tests depends on an EBI server
that is timing out.   I will rewrite that one.   Testing some things, such
as htsget,  need to rely on external services unfortunately.

A good way to check tests is opening "test/runTests.html" in a web
browser.

Its disappointing Travis "passes" this, maybe something wrong with our
setup?

**Comment by jrobinso** [comment]
OK I disabled the failing htsget test.   I cannot find a reliable server to test it against and we don't have resources to run one just for tests.
