### ISSUE TITLE
Can't display vcf file for snps

### ISSUE THREAD

**Issue by shihai832** [igvteam/igv.js#1127]
I am trying to display attached vcf files for snps. The track loaded but nothing came up. 

[S_aureus_ER04823_3A_025720.repeat_mask.fasta.fai.zip](https://github.com/igvteam/igv.js/files/4826446/S_aureus_ER04823_3A_025720.repeat_mask.fasta.fai.zip)
[parsnp.vcf.gz.tbi.zip](https://github.com/igvteam/igv.js/files/4826447/parsnp.vcf.gz.tbi.zip)
[S_aureus_ER04823_3A_025720.repeat_mask.fasta.zip](https://github.com/igvteam/igv.js/files/4826448/S_aureus_ER04823_3A_025720.repeat_mask.fasta.zip)
[parsnp.vcf.gz](https://github.com/igvteam/igv.js/files/4826449/parsnp.vcf.gz)

**Comment by jrobinso** [comment]
What do you mean "nothing came up".   Did you zoom to a region you know should have a snp?    Please give us a test case  (html or at least track config) and exact steps to reproduce.

**Comment by shihai832** [comment]
I used the igv-web for testing. First I loaded the fasta file and it's fai.
I can see the sequence. Then I loaded the parsnp.vcf.gz and its tbi. The
track is there but I can any snps.

shihai

**Comment by jrobinso** [comment]
I see.  Its a bit confusing, what yo uinitially see is a "whole genome" view.  As your fasta has only 1 contig this is confusing.  Zoom into somewhere specfic, for example  u00000crpx_c_025720:2,854-14,890

**Comment by shihai832** [comment]
Thanks a lot.

shihai

**Comment by shihai832** [comment]
Is it possible to set a different color for A,T,G,C,- when display VCF
files? The reason I use VCF instead of BAM is because BAM loads much slower
than VCF.

shihai

**Comment by jrobinso** [comment]
No its not

**Comment by jrobinso** [comment]
BTW you have 2 contigs, but one is very small.   When configuring this in igv.js you might want to set

```
 wholeGenomeView: false
```

**Comment by shihai832** [comment]
Thanks a lot. For display snps with different colors, what input file
besides bam file I can use?

**Comment by shihai832** [comment]
Bam file loads very slow for large sequences.

**Comment by jrobinso** [comment]
I don't know how to answer the question you are asking.  BAMs and vcfs are fundamentally different things.   You load a BAM file to see the alignments.  VCF files do not contain alignments.    Secondly, assuming your bam files are indexed they should load nearly as fast as VCF files.      There is no file format that displays "snps" with different colors.
