### ISSUE TITLE
rendering issue with UIKIT3 

### ISSUE THREAD

**Issue by VivekTodur** [igvteam/igv.js#1128]
Hi,

IGV is not getting rendered properly in the presence of UIKIT3 framework. Screenshot is attached for your reference. If I am taking out UIKIT3.css its working fine as expected. Any guidance to resolve [this...](url
![igv_display_problem](https://user-images.githubusercontent.com/12067550/85658842-6d83dd80-b6d1-11ea-9ba3-92819887634d.png)
)

**Comment by jrobinso** [comment]
@VivekTodur could you zip up and attach an html page demonstrating the problem?  I do not know that "UIKIT3" is but if you can give us an example we will look at it.

**Comment by jrobinso** [comment]
@VivekTodur never mind, it was easy to find.   UIKIT is redefining lots of global css rules, for example it is globally redefining canvas max-width, box-sizing, vertial-alignment and other rules.    This will cascade down to everything in the page.   There might be something here that will help.     https://getuikit.com/docs/avoiding-conflicts

**Comment by jrobinso** [comment]
@VivekTodur if you pull from the master branch and build it might work.   No guarantees.    When a toolkit applies global rules to elements its hard to work around.
