### ISSUE TITLE
Problem rendering two tracks mapping on the same range

### ISSUE THREAD

**Issue by martina-g** [igvteam/igv.js#1129]
Hi,
I'm having issues in correctly rendering tracks handled with a module I wrote to display tracks from a custom format. 
Track 1
<img width="963" alt="track_1" src="https://user-images.githubusercontent.com/66132177/85862209-bdda6880-b7c1-11ea-8ede-076456939080.png">
Track 2
<img width="932" alt="track_2" src="https://user-images.githubusercontent.com/66132177/85862253-cf237500-b7c1-11ea-8181-2b6f1586f82f.png">
Both tracks
<img width="1201" alt="two_tracks" src="https://user-images.githubusercontent.com/66132177/85862309-e19dae80-b7c1-11ea-82e9-3ad2daed506c.png">
As you can see, there is a problem in visualising both tracks together. 
Track 1 does not have any mismatch in the range 0-40, on the contrary Track 2 does have mismatches in the same range. 
When they are visualised together also Track 1 shows mismatches, even if it doesn't. What is happening is that, for some reason, at each position where Track2 has a mismatched base, Track1 corresponding base is not displayed in grey even if it matches the reference genome. This does not happen in the packed rows below.
![issue](https://user-images.githubusercontent.com/66132177/85878830-a018fd80-b7d9-11ea-9380-05e5a6f3483c.png)
Could you provide some help?
Thank you in advance

**Comment by jrobinso** [comment]
Could we see the code for rendering these tracks?  And an example html would help also.

**Comment by martina-g** [comment]
I edited the first post with more infos.
My changes to the igv.js library:
**bamSource.js**

```
BamSource.prototype.getAlignments = async function (chr, bpStart, bpEnd) {
    try {
        [..]
        } else {
            if ("mpegg" == this.config.format) {
                var alignmentContainer = await this.mpeggReader.readAlignments(chr, bpStart, bpEnd)
            } else {
                var alignmentContainer = await this.bamReader.readAlignments(chr, bpStart, bpEnd)
            }
            let alignments = alignmentContainer.alignments;
           [..]
    } catch (e) {
      [..]
    }
```
**mpeggReader.js**

```
MpeggReader.prototype.readAlignments = async function (chr, bpStart, bpEnd) {
    var chrNames = ['chrM'];
    var chrIndex = chrNames[chr];

    const alignmentContainer = new AlignmentContainer(chr, bpStart, bpEnd,
        this.config.samplingWindowSize, this.config.samplingDepth,
        this.config.pairsSupported, this.config.alleleFreqThreshold);

    const url = this.config.url

    const newFile_mpegg = await igvxhr.loadString(url);
    const done = BamUtils.decodeMpeggRecords(newFile_mpegg, alignmentContainer, chrNames, chr, bpStart, bpEnd, this.filter);

    alignmentContainer.finish();

    return alignmentContainer;
}
```
The decodeMpeggRecords() function returns an alignmentContainer object with correct data for both tracks.
What am I doing wrong? 
Right now I can't make an example html..

**Comment by jrobinso** [comment]
Impossible for me to say, I can't really even interpret your tracks, what type of track are the "boxy" rectangles above the alignment records?  Alignments are drawn in the file BamTrack.js.

**Comment by jrobinso** [comment]
Oh I see, the block track is coverage.  It looks strange at 2X.   I actually don't see anything wrong with those screenshots, they look correct to me.    The grey rectangle representing the alignment does not show any mismatches.    The coverage track highlights locations where more than 20% of the reads show a mismatch.   In your case it is 50% as you only have 2 reads.    This is exactly how the coverage track works, so everything is correct.
