### ISSUE TITLE
Show all bases (mismatch bases) and show center line 

### ISSUE THREAD

**Issue by Nitin123-4** [igvteam/igv.js#1131]
How can we enable the following: 

1. mismatch bases in igv.js even after enabling I can't see mismatch bases. 
2. How to enable the show center line?
3. igv.js: Is it downsampling by default?
4. Coverage details on mouseover?
5. Exon number on the annotation track?

**Comment by Nitin123-4** [comment]
Sorry Just saw the updated version covers point 1, 3, 4

**Comment by jrobinso** [comment]
* RE 2, I thought there was a config parameter for that but there is not.   We will add one.
* The annotation track does not support exon numbers.

**Comment by Nitin123-4** [comment]
Point 2: working now: after adding:

showCenterGuide: true

Thanks

**Comment by jrobinso** [comment]
Thanks for testing that.   I will update the documentation.
