### ISSUE TITLE
Always throws exception of undefined genome,

### ISSUE THREAD

**Issue by shingocat** [igvteam/igv.js#1133]
Hi,

I used my local reference fasta file and had indexed fasta file by samtools.  I used reference property to set myself reference. However there are always throwed this exception. The igv.js version is 2.6.2. How to fix this issues. 
Many Thanks.
 
Uncaught (in promise) TypeError: Cannot read property 'genome' of undefined
    at Browser._callee4$ (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:62389)
    at tryCatch (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:1747)
    at Generator.invoke [as _invoke] (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:1966)
    at Generator.prototype.<computed> [as next] (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:1800)
    at asyncGeneratorStep (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:2428)
    at _next (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:2450)
    at igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:2457
    at new Promise (<anonymous>)
    at Browser.<anonymous> (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:2446)
    at Browser._ref7 (igv.js;jsessionid=94A7F0C5897D7757D0CA8AB7393462C1:62424)

**Comment by jrobinso** [comment]
There's not enough information there for us to help you.   If possible zip up a test case that reproduces the problem.   If that is not possible at a minimum post your igv configuration here.      Also try using the un-minified "esm" igv distribution, this will yeild a better error message.   To do that comment or remove the <script> tag that is loading igv.min.js,  then replace the script tag with your IGV configuration with the following 2 lines

```
<script type="module">

    import igv from 'https://cdn.jsdelivr.net/npm/igv@2.6.2/dist/igv.esm.js'

```

After doing that post the error message again.

**Comment by shingocat** [comment]
Hi jrobinso,

The following statements are used to set options for igv.js.

var igvDiv = document.getElementById('n82Q56');
var options =  {
showNavigation: true,
reference: {
name: "Agrobacterium tumefaciens ASM97156v1",
fastaURL: 'http://10.200.24.108/longterm/Agrobacterium_tumefaciens/Reference/AGB_1593606940987_2/AGB_1593606940987_2.fasta',
indexURL: 'http://10.200.24.108/longterm/Agrobacterium_tumefaciens/Reference/AGB_1593606940987_2/AGB_1593606940987_2.fasta.fai',
},
tracks: [ 
{
name: 'Genes Annotation',
type: 'annotation',
format: 'gff3',
sourceType: 'file',
url: 'http://10.200.24.108/longterm/Agrobacterium_tumefaciens/Gff/AGB_1593657144993_4/AGB_1593657144993_4.gff3.gz',
indexURL: 'http://10.200.24.108/longterm/Agrobacterium_tumefaciens/Gff/AGB_1593657144993_4/AGB_1593657144993_4.gff3.gz.tbi',
displayMode: 'EXPANDED',
height: '300',
searchable: 'true',
}
]
};
igv.createBrowser(igvDiv, options).then(
function (browser) {
igv.browser = browser;
console.log('Created IGV browser');
});

And I copy the igv.js into my web root folder and import the igv.js by "<?script type="text/javascript" src="igv/igv.js" ?>" on my index page. 

When I changed to use "igv.esm.js", there are two exceptions.
![image](https://user-images.githubusercontent.com/1930416/86567113-61373480-bf9d-11ea-92f7-1b26c6d83960.png)

**Comment by jrobinso** [comment]
Please follow my instructions exactly.   If you're having difficulty following them zip up your html and attach it.
