### ISSUE TITLE
[Feature Request] add support for interact and bigInteract

### ISSUE THREAD

**Issue by mzager** [igvteam/igv.js#1134]
I am hoping to render cis-coexpression regulatory networks in IGV.JS.   From my research, the best example of what I am trying to implement is the second example on this page. 

https://genome.ucsc.edu/goldenPath/help/interact.html#:~:text=The%20interact%20file%20format%20has,be%20viewed%20on%20a%20chromosome.&text=The%20second%20row%20of%20the,not%20represented%20by%20an%20arc.

@jrobinso Let me know how I can help!

**Comment by jrobinso** [comment]
OK @mzager this is mostly done.   If you want to jump in and finish here's what's left.   No pressure

* visual indication of inter-chromosomal features.   Currently these are just skipped.
* Support for UCSC "directional" concept,  I think they use a dashed line for features that run "right to left" if the track is marked directional, but I haven't looked closely.

I don't know what the best marker is inter-chr are,  perhaps just a block or vertical line.    I don't like the UCSC right-angle connectors, they are distracting.    For "interact" format there will be 2 entries in the file for inter-chromosomal features, 1 on each chromosome.

If you have time and inclination to try this in the next week  I will put more details here.  There is test data in the repository from UCSC (there examples).

**Comment by mzager** [comment]
Thank you so much.  I'll start familiarizing myself with the code base next week and see if I can't integrate these features.

**Comment by jrobinso** [comment]
@mzager I don't know if those features (inter-chromosomal and direction) are important to your application, if not don't worry about it.   If you want to do something with that,  the only functions involved should be the draw functions (drawNested and drawProportional) of InteractionTrack.

**Comment by jrobinso** [comment]
Full support is released in 2.7.0
