### ISSUE TITLE
a quantitative track with annotation as well?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1139]
I often have quantitative, non-continuous data.  I do not know how to render the quantitative measure as height AND have annotation fields as well.  

A straightforward example of this is scored ChIP-seq peaks called by MACS2.   With extra annotation fields included, I could either display that annotation in a popup, or capture the track-click event and display the annotation using my own ui.  

My current clunky solution is to display two tracks, one bed, and one wig(or bigwig or bedgraph).  Extra annotation goes in the bed track, quantitative in the wig track.   

Is there a better solution?

**Comment by jrobinso** [comment]
@paul-shannon Thats not clunky at all, in my opinion.  You could develop a special composite track but it would amount to that in the end.

**Comment by paul-shannon** [comment]
@jrobinso  Good to know  I  was not missing out on an existing solution.  Thanks, Jim.
