### ISSUE TITLE
Can't read in binary data by EJS

### ISSUE THREAD

**Issue by mshrngci118** [igvteam/igv.js#1142]
![image](https://user-images.githubusercontent.com/40280869/88701866-721c2700-d0bf-11ea-87ff-abb471c90b59.png)

**Comment by jrobinso** [comment]
Sorry I don't know what EJS is.

**Comment by mshrngci118** [comment]
I should have explained it more. EJS is Embedded JavaScript. It is a simple templating language that generate HTML markup with plain JavaScript.
https://ejs.co/

**Comment by jrobinso** [comment]
The problem is probably your igv.js configuration.  If you can zip up a reproducible test case I can run I will look into it.

**Comment by mshrngci118** [comment]
I could't figure out about the configuration.
So, I attached minimal code and directory structure.

[demo.zip](https://github.com/igvteam/igv.js/files/4991846/demo.zip)

"dependencies": {
    "body-parser": "^1.19.0",
    "ejs": "^3.1.3",
    "express": "^4.17.1",
    "request": "^2.88.2"
  }

**Comment by jrobinso** [comment]
Your original post said igv.js "cant read binary data".   I don't see any binary data.

You should not specify a format for the track ("bed") if you are supplying the features directly.   That could cause issues.  Otherwise the configuration looks ok.,  but of course I don't know what "inputData" resolves to.

Sorry I can't help you with EJS.

**Comment by mshrngci118** [comment]
Sorry that I made you misleading by the title.
What I meant was RefSeq's mRNA annotation data coming from IGV, is not rendered properly on the viewer panel.
I couldn't find out the exact reason why I'm getting this error message, but I thought it meant for failing to compile or build the RefSeq data during the process of rendering...

**Comment by jrobinso** [comment]
If you can capture the html that is generated and save it as a static page that might help you diagnose the problem.  I do see a problem with your locus string, there shouldn't be a space after "16:".
