### ISSUE TITLE
IE doesn't support for..of statement

### ISSUE THREAD

**Issue by kzoabi** [igvteam/igv.js#1143]
Hello guys,
I hope you're doing well!

I've started using version 2.5.2 few weeks ago and our team face a problem with IE that prevented showing up the IGV on screen.
The developer tool of Internet Explorer show us that the problem is in line:
[canvas2svg.js#L343](https://github.com/igvteam/igv.js/blob/0c8f6982bc4cc8756bfa5cf3c962ff81faf08284/js/canvas2svg.js#L343)
This issue happens because of using: for (**let** key **of** ...) 
that IE doesn't support. (Error: SCRIPT1004: Expected ';')

Please let me know if there is a workaround or a fix for that.

Thanks a lot,
Khaled

**Comment by jrobinso** [comment]
We do not support IE,  however you might be able to get it to work with Babel.   What version of IE are you targetting?   Also, how are you including igv?  The built artifact igv.min.js is already Babel translated for ES5.

**Comment by kzoabi** [comment]
Hi Jim,

I use IE 11 and I use npm install to include the tool, I just add the igv dependency like this: **"igv": "^2.5.2"**

Khaled

**Comment by kzoabi** [comment]
Hi Jim,
What is the correct way to import it in order to let IE11 use the ES5 version of igv? I realized that importing it using: 
_import igv from 'igv/dist/igv.esm'_
still importing the ES6 version

Thanks,
Khaled

**Comment by jrobinso** [comment]
You should use a script tag for "igv.js" or "igv.min.js" as indicated in
the README.md.   This will install an ES5 version.   It might work on
IE11,  I don't know,  you would have better odds with Edge.

If it doesn't work you might be able to build a version that does by
changing the babel rules in the ".babelrc" file and rebuilding  "npm run
build".   The current rules are supposed to target all browsers with at
least 1% share,  but I'm not sure IE11 will meet the 1% threshold.   If not
you can use more aggressive transforms,  you would consult the Babel
documentation for that.   If you get this working please update this issue
for the benefit of others.   Thanks.

**Comment by jrobinso** [comment]
To clarify, you cannot use "import" at all you have to include its with a
<script....   tag.  This is documented in the README.     Import is an es6
feature.

**Comment by kzoabi** [comment]
Thanks Jim, I'll try that!

**Comment by kzoabi** [comment]
Hi all,
I'm using Angular 7 and have used igv like this:
import igv from 'igv/dist/igv.esm'
which imports the ES6 version.

I got this error in IE11:
![image](https://user-images.githubusercontent.com/3586425/90360751-3264b180-e065-11ea-8381-405b3c8889a8.png)
Says:
`Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)`

IE11 supports only ES5. In order to use 'igv.min.js' in my project the only way that helped me (after trying some others) was to put this script into 'assets' directory and adding the following to my code:

1. I create an interface with the name IGV in my local typings declaration file:
`declare var igv: IGV;
interface IGV {
  createBrowser(divElement: any, options?: any): any;
  numberFormatter(number: any): any;
}`
2. I used the following code to load the script from my component.ts file:
`declare const igv: any;

@Component({
  selector: 'component-igv',
  templateUrl: './igv.component.html',
  styleUrls: ['./igv.component.scss']
})
export class IgvComponent {
constructor() {
    super();
    this.loadScript();
  }

  loadScript() {
      const scriptElement = document.createElement('script');
      scriptElement.src = 'assets/scripts/igv.min.js';
      scriptElement.type = 'text/javascript';
      const headElements = document.getElementsByTagName('head');
      headElements[0].appendChild(scriptElement);
  }
}`

Only this helped me to fix the IE11 problem with igv.js.

References:
[https://angular.schule/blog/2019-02-third-party-libraries-and-widgets](https://angular.schule/blog/2019-02-third-party-libraries-and-widgets)
[https://stackoverflow.com/questions/60808435/adding-scripts-after-angular-8-compiled-scripts-main-js-polyfill-js-etc](https://stackoverflow.com/questions/60808435/adding-scripts-after-angular-8-compiled-scripts-main-js-polyfill-js-etc)

Thanks,
Khaled Zoabi

**Comment by jrobinso** [comment]
@kzoabi thanks for posting your solution,  I'm sure it will help others.
