### ISSUE TITLE
problems when editing output SVG file in Illustrator

### ISSUE THREAD

**Issue by rysterzhu** [igvteam/igv.js#1147]
I want to amend the output SVG file in illustrator, but it has too many masks and groups.
Is it possible to output a simple vector diagram? 
Or is there an easier way to edit the output SVG vector diagram?

**Comment by jrobinso** [comment]
@rysterzhu You opened an issue in igv.js,  the javascript igv component, can you tell me what version you are using?

**Comment by rysterzhu** [comment]
> @rysterzhu You opened an issue in igv.js, the javascript igv component, can you tell me what version you are using?

I am using igv-jupyter, version 0.9.8

**Comment by jrobinso** [comment]
Ok, so no that is the SVG igv provides.
