### ISSUE TITLE
416 "Unsatisfiable Range" for VCF file with no variants

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#1148]
I'm trying to upgrade from v2.2.2 to the latest and I'm now getting an error that I wasn't previously.  I have a VCF file with metadata but no actual variant data, and when included in v2.2.2 it loads as an empty track but now on v2.6.2/3 I get an "Unsatisfiable Range" error and the track is excluded from the visualization. My browser console shows that the requests for this file have a status code of 416:

Request Headers:
```
GET /analysis/4720/VCFs/Variants_Passing_Filters_R1.freebayes.ann.vcf.gz?someRandomSeed=0.gmy70pv6dru HTTP/1.1
Host: 192.168.220.128
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
Accept: */*
Referer: http://192.168.220.128/visualize-igv/job/4720/sample/188?context=detail
Accept-Encoding: identity
Accept-Language: en-US,en;q=0.9
Cookie: csrftoken=qhJ1JD7IHBMt2APcPR0DQJjtTntekZWnA5jOKID99MpFSK6D1dLP6jgzfUYF41EE; sessionid=o8iq8p52w0tfqeke6mcf6r38iixx2erj
Range: bytes=9007199254740991-9007199254741016
```

Response
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>416 Requested Range Not Satisfiable</title>
</head><body>
<h1>Requested Range Not Satisfiable</h1>
<p>None of the range-specifier values in the Range
request-header field overlap the current extent
of the selected resource.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at 192.168.220.128 Port 80</address>
</body></html>
```

All of my other tracks load just fine, and after dismissing the error the visualization acts normally. Attached is the VCF that causes the error.

Edit: Change upload to include the index file

[NoVariantsVCF.zip](https://github.com/igvteam/igv.js/files/5008320/NoVariantsVCF.zip)

**Comment by jrobinso** [comment]
I can't reproduce this in the master branch, if the problem recurs in the master branch or later releases please include some instructions to reproduce.    Thanks for the test file.   The next release will be 2.7.0.
