### ISSUE TITLE
Possible to add two colors to same track?

### ISSUE THREAD

**Issue by hmgill** [igvteam/igv.js#1149]
Hi, 

Apologies since this is a simple question. I was wondering if it were possible to annotate (+) and (-) strands in the same track with different colors? 

Thank you!

**Comment by jrobinso** [comment]
@hmgill Sorry for the delay.  What type of track?   Its possible to supply a second color for "wig" type tracks as field "altColor".   However this doesn't work for "annotation" type tracks. 

I will look into supporting this for annotation tracks.   Then the issue becomes what to do with features that are not stranded.  I suppose they would get the default or positive strand color.

**Comment by hmgill** [comment]
Hi @jrobinso, 
Sorry, yes, I did mean annotation tracks. Thanks for looking into it!

**Comment by jrobinso** [comment]
This is done, available in the master branch and to be released with 2.7.0.   The parameter is "altColor".
