### ISSUE TITLE
Saving SVG problem

### ISSUE THREAD

**Issue by dppss90008** [igvteam/igv.js#1150]
I am hoping to save the results into SVG file.
However, some problems raised in the console.

<img width="1276" alt="2020-08-04 110956" src="https://user-images.githubusercontent.com/34399929/89248750-11529880-d643-11ea-9b85-c44e9997e3e9.png">

The SVG file did not show the wiggle track.
<img width="726" alt="註解 2020-08-04 111107" src="https://user-images.githubusercontent.com/34399929/89248813-3a732900-d643-11ea-85b8-cc3aff6c5441.png">

Could you help me with this problem?
Thanks!

**Comment by jrobinso** [comment]
What version of igv.js are you using?

**Comment by dppss90008** [comment]
I think it is the lastest one.

<script src="https://cdn.jsdelivr.net/npm/igv@2.6.2/dist/igv.min.js"></script>

**Comment by jrobinso** [comment]
I haven't seen this error before, its hard to say what is causing it from a screenshot.    Could you give us a test case to reproduce it?  If those files are public on the web you can just zip up you html page and attach it here,  or paste in the javascript configuration you used to start igv.js.

**Comment by dppss90008** [comment]
Here are my HTML code and the track files.
https://drive.google.com/file/d/139M7CE_kvRvAjaUAnotL4Ag2gmNaWn4P/view?usp=sharing
Thanks for your time.

**Comment by jrobinso** [comment]
OK, thanks, I can reproduce the problem.   We'll look into it.

**Comment by jrobinso** [comment]
This should be fixed now,  use version 2.6.4.

**Comment by dppss90008** [comment]
Yes, it works!
Thank you so much!
