### ISSUE TITLE
Long loading time / memory error for "larger" bam files

### ISSUE THREAD

**Issue by sklas** [igvteam/igv.js#1151]
Hi,

I am running igv.js inside an R shiny app and the files are served via a lighttpd server.
In principle it is running smoothly, but when it comes to bam files with a high coverage it takes several minutes to load or even quits caused by exceeding memory.
I tried the same files at https://igv.org/app/ loaded via local file and its immediately loaded, so it might just be something misconfigured on my side.
Any advice on this?

Best,
Steffen

**Comment by jrobinso** [comment]
Hi Steffen,
I'm not familiar with the lighttpd server but from your symptoms I would
guess it is not respecting the "range byte" headers in the requests and
just returning the entire bam file.   Perhaps lighttpd needs to be
configured to support range byte requests.

**Comment by sklas** [comment]
I checked that, but using curl it looks like it handles it correct.
But I also tried with apache2 and the behavior is the same (It also accepts range requests with curl). 
The network monitor in chrome shows that its loading the whole files. 
In this case it is paired end Illumina data with a coverage between 2.000 and 8.000 and pacbio data with a coverage of ~ 750 on a ~ 14kb reference. Are such high coverages problematic?

The igv frame looks like this:
```
  <!DOCTYPE html>
  <html lang='en'>
  <head>
  <script src='js/igv.min.js'></script>

<script>  $(document).ready(function() {
    var div = $('#igvDiv')[0],
    options = {
      showNavigation: true,
      showRuler: true,
      locus: '%s:1-1000',
      reference: {
        fastaURL: '%s'
      },
      tracks: [
       {
         type: 'alignment',
         name: 'LR',
         format: 'bam',
         height: 350,
         samplingWindowSize: 100,
         samplingDepth: 100,
         url: '%s',
       }, {
         type: 'alignment',
         name: 'SR',
         format: 'bam',
         colorBy: 'tag',
         colorByTag: 'pt',
         samplingWindowSize: 100,
         samplingDepth: 100,
         height: 350,
         url: '%s',
       }]
      };
    igv.createBrowser(div, options);
});
function updateLocus(location) {
  igv.browser.search(location)
};
  </script>
 </head>
 <body>
  <div id = 'igvDiv'>
  </body>
  </html>
```

**Comment by jrobinso** [comment]
You need to use indexes for the fasta and bam, otherwise yes it will load
the entire file.   With indexes the size of the bam (or fasta) does not
matter.

**Comment by sklas** [comment]
I also tried to explicitly give the path to index files, but it doesn't change the behavior.
For the reference its the output from "samtools faidx" and specified using "indexURL" right below "fastaURL".
For the bamfiles its also specified using "indexURL" below the "url" tag.
Are these tags correct?

**Comment by jrobinso** [comment]
I assume you've review our wiki and examples?   Your fasta doesn't matter much as its small and will load entirely without a problem, but for large bam files you need to set indexURL.
