### ISSUE TITLE
igv-web. Normalize Coverage Data

### ISSUE THREAD

**Issue by jslpzNGS** [igvteam/igv.js#1153]
Congratulations for such a wonderful tool! igv-web!

I would like to know whether it would be possible to normalize coverage tracks as we do in igv desktop application. I mean by selecting View>Preferences>Tracks tab and selecting the Normalize Coverage Data checkbox (This normalization option multiplies each value by [1,000,000 / (totalReadCount)]).

Best regards and congratulations again!!

  Jose

**Comment by jrobinso** [comment]
This has been pushed to master, will be released with 2.7.0.  The option works as follows,  a value of "normalize: true" will multiple values by  1.0e6 / totalReadCount  IFF totalReadCount is available.   In other words for TDF format files created with igvtools.   Alternatively a scaleFactor can be set for any wig track data source, all values will be multiplied by the scale factor.   Example follows

```
                {
                    name: "Coverage TDF",
                    url: "../test/data/tdf/BRAF_C.bam.tdf"
                },
                {
                    name: "Normalized Coverage TDF",
                    url: "../test/data/tdf/BRAF_C.bam.tdf",
                    normalize: true
                },
                {
                    name: "Scaled Coverage TDF",
                    url: "../test/data/tdf/BRAF_C.bam.tdf",
                    scaleFactor: 2.0
                }
```
