### ISSUE TITLE
Overlay tracks

### ISSUE THREAD

**Issue by kikegoni** [igvteam/igv.js#1154]
Hi Jim,

First of all thank you very much for this implementation of IGV in web applications, it is really valuable. 

I was just wondering whether you have planned to add a feature that enables to overlay two or more tracks as it is possible with the Desktop IGV Application. 

Best regards,

Enrique

**Comment by jrobinso** [comment]
@skycolloredo IIRC there are no type restrictions, but I don't think non-wig tracks have been tried.   I'm working on IGV desktop this week and don't have time to investigate now, but here's the track config from one of our examples.  

```
                    {
                        name: "Merged",
                        height: 50,
                        type: "merged",
                        tracks: [
                            {
                                "type": "wig",
                                "format": "bigwig",
                                "url": "https://www.encodeproject.org/files/ENCFF000ASJ/@@download/ENCFF000ASJ.bigWig",
                                "color": "red"
                            },
                            {
                                "type": "wig",
                                "format": "bigwig",
                                "url": "https://www.encodeproject.org/files/ENCFF351WPV/@@download/ENCFF351WPV.bigWig",
                                "color": "green"
                            }
                        ]
                    }
```

**Comment by skycolloredo** [comment]
Thanks!

**Comment by jrobinso** [comment]
@skycolloredo Do let me know how it works.   I split my time between IGV desktop (Java)  and igv.js (javascript) and have found I can't just jump back and forth on a dime,  I hope to return to a block of work on igv.js in the next few weeks and can look more deeply then.

**Comment by skycolloredo** [comment]
No luck on merging two different types, but works great with two wig files. 

One other question, is it possible to specify a custom min/max on the merged track? When I add min/max to the tracks, they seem to be disregarded.

**Comment by jrobinso** [comment]
I'll look into that when I get a chance.  Did you try setting min/max on
the merged track itself?

**Comment by turner** [comment]
Overlay tracks have been added in 08e62c70
