### ISSUE TITLE
Don't create sessions with local File references -- was  "need better error reporting when session includes local files"

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#1155]
[ ] If a session includes a local track, the following error message is presented:
"url must be either a 'string', 'function', or 'Promise'. Actual type: object"
Needs to be more informative. 

[ ] If a session includes a genome loaded from a local file, there's no error message at all.

**Comment by jrobinso** [comment]
The best fix for this is to not create such sessions.   They cannot be created by hand.  This can be done in the methods that convert objects to json,  for example ```browser.toJson()``` and methods it calls.  If a local file is used for any URL throw an error to be caught and handled by the client.    URLs can appear in the following fields.   

* genome (reference)
    * fastaURL
    * indexURL

* tracks
    * url
    * indexURL

**Comment by turner** [comment]
Closed with commit 1c2f3c449d72636da3ed30f600ce167dce528874
