### ISSUE TITLE
A method that clear all existing browser instances

### ISSUE THREAD

**Issue by haoyuanli** [igvteam/igv.js#1156]
Hello, I wonder if we could add something like this that removes all existing browser instances, and (assume importing as igv in ES6) can be revoked as simple as  `igv.removeAllBrowsers()` 

```
/**
 * This function allows the removal of all existing IGV browser instances.
 */

function removeAllBrowsers() {
    allBrowsers.forEach(function (browser) {
        removeBrowser(browser);
    })
}
```

I think the use case will mostly be in in React or some other scenarios where we want to avoid the direct manipulation of DOM elements through Javascript.

Right now, there is sort of a way to move an instance by doing `igv.removeBrowser(igv.getBrowser())`, but this seems to be for internal use, and I feel like having something else might be better

**Comment by jrobinso** [comment]
yes, good suggestion.
