### ISSUE TITLE
Viewing variants from a database

### ISSUE THREAD

**Issue by amanpatel** [igvteam/igv.js#1158]
Increasingly a lot of pipelines now load information directly a warehouse or a database. Viewing variants directly from this database would be an awesome feature, especially the ease at which you can query/filter variants in a database.

Does IGV have a method to achieve this? Currently, I'm looking at overriding the VCF parser, and the range queries requests to achieve something like this.

Any guidance or direction would be appreciated!

**Comment by jrobinso** [comment]
There is support for customized readers and customized web services.     I think the simplest approach would be to implement a custom "reader".  It has 1 required method

```
async readFeatures(chr, start, end)
```

In your case the method should return variant features.  Unfortunately variant objects aren't documented other than by examining code, but its what vcfparser returns.   See  "dev/custom-reader.html"  for an example.

There's also customized webservice support, a similar (older) idea, but the custom reader is more flexible.

Can you expand on your generalization "increasingl a lot of pipelines...".   What specific pipelines?  Where is this happening? The centers I support are for the most part still generating VCFs.

**Comment by amanpatel** [comment]
That pretty much answers my addressed my needs. I will update this post with some code later on in hopes it can help someone else.
