### ISSUE TITLE
Can't see the label on uploaded tracks

### ISSUE THREAD

**Issue by gujarwasia** [igvteam/igv.js#1161]
Why i can't see the label on tracks uploaded to my application but same file shows the label when uploaded to igv.org.
below is example.
![Custom App](https://user-images.githubusercontent.com/11008949/90529183-0d6d5d00-e191-11ea-929e-c6ad56ea64b5.JPG)
![Default IGVApp](https://user-images.githubusercontent.com/11008949/90529190-0e9e8a00-e191-11ea-854c-2fe4dcf0e468.JPG)

**Comment by jrobinso** [comment]
What version of igv.js are you using?

**Comment by gujarwasia** [comment]
> What version of igv.js are you using?

"igv@2.3.5"

**Comment by jrobinso** [comment]
Well the current version is 2.6.2, so that could be part of the reason.

**Comment by gujarwasia** [comment]
thanks issue fixed after version upgrade
