### ISSUE TITLE
multiple copies of reference track

### ISSUE THREAD

**Issue by petermchale** [igvteam/igv.js#1167]
Hi Jim, 

I've created a web app at: https://igv-grid.surge.sh .

When one clicks on a thumbnail, an igv browser instance is mounted. However, on subsequent thumbnail clicks, additional reference tracks appear, which is not desired behavior. 

How can I "correct" this? Could this have anything to do with a note on https://github.com/igvteam/igv.js/wiki/Browser-Creation that reads “the genomeList is globally shared by all igv browser instances on a page” ?

Relevant code is at: https://github.com/petermchale/igv-grid/blob/3409a398447bb39fc6c6d385acb00f04584ed7d2/web-app/src/components/IGV.vue#L39-L54

Thanks, 
Peter

**Comment by jrobinso** [comment]
Are you calling "createBrowser" on each click?  Its not clear to me.   This could be a bug I will see if I can simulate it.   However if you are going to call "createBrowser" on each click you should remove the previous one first.   Otherwise you are going to have a memory leak at minimum.  

Another option would be to create an igv "browser" once,  then load session objects.    A session object is a restricted subset of the config options sent to create browser, the restrictions won't affect your app (mostly no functions or promises as attribute values).   This is not documented, apologies I am way behind on documentation, but you would call

```
browser.loadSessionObject(options)   
```


The genomeList comment just means that all browsers (you can have multiple instances) on a page shares the same list of predefined genomes  (e.g. hg19) from which to select.

**Comment by jrobinso** [comment]
Also, what version of igv.js are you using?  With later version calling createBrowser multiple times will simply append new browsers to the container div, as shown in the screenshot.   I can see how something like this might have happened with older versions, but they would be quite old.   Could you check your igv version?   Here's the code I used to try to simulate your situation

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <link href=img/favicon.ico rel="shortcut icon">
    <title>IGV - Dev</title>
    <link href="css/dev.css" rel="stylesheet" type="text/css"/>

</head>

<body>

<button id="createBrowserButton">Create Browser</button>

<div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>

<script type="module">

    import igv from "../js/index.js";

    const igvDiv = document.getElementById("igvDiv");

    document.getElementById("createBrowserButton").onclick = function () {

        const options =
            {
                genome: "hg38",
                locus: "chr10:10,266,643-10,266,904",
                tracks: [
                    {
                        type: 'alignment',
                        format: 'bam',
                        url: '../test/data/bam/indel_test.bam',
                        indexURL: '../test/data/bam/indel_test.bam.bai',
                        name: 'HG00514'
                    }

                ]
            };

        igv.createBrowser(igvDiv, options)
            .then(function (browser) {
                console.log("Created IGV browser");
                window.igvBrowser = browser;
            })
    }

</script>

</body>

</html>

```

<img width="1641" alt="Screen Shot 2020-08-27 at 10 48 25 PM" src="https://user-images.githubusercontent.com/933148/91526092-b6196c00-e8b7-11ea-873a-05f3c25ef990.png">

**Comment by petermchale** [comment]
Thanks for pointing me to `igv.removeBrowser`; I now call that before the `igv.js` instance is destroyed. 

Thanks also for pointing out that the `this.tracks` array is accumulating elements. Turns out that this is happening in the igv.js codebase. To see this, one can insert the following code: 

```
    console.log('before igv.createBrowser called: ')
    for (let i = 0; i < callSets.length; i++) {
      console.log(`callSets[${i}].tracks`, JSON.parse(JSON.stringify(callSets[i].tracks)))
    }

    igv.createBrowser(this.$refs.igv, options).then(browser => {
      this.browser = browser
      // console.log('browser info:', browser)
    })

    console.log('after igv.createBrowser called: ')
    for (let i = 0; i < callSets.length; i++) {
      console.log(`callSets[${i}].tracks`, JSON.parse(JSON.stringify(callSets[i].tracks)))
    }
```
... and then click on the left thumbnail in the "True positives" track (for example), at which point you'll see: 

<img width="694" alt="Screen Shot 2020-08-28 at 5 14 20 PM" src="https://user-images.githubusercontent.com/19557137/91621875-f2010f80-e951-11ea-89cd-c358f2c656ae.png">

This wouldn't be a problem when clicking on different thumbnails except that `callSets` points to an imported object: 

```
import callSets from '@/assets/thumbnails.json'
...
  data () {
    return {
      callSets,
      ...
    }
  },
```
and imported objects are cached by the browser. So every time a new thumbnail is clicked, and a new Vue component instance is created, the `callSets` object that was used (and changed) in the previous Vue component instance is re-used (and changed again). Curse of the cache. 

The work-around is to give `igv.js` an `options.tracks` that points to a *deep copy* of `this.tracks` so that `callSets`, though cached, is never changed: 

```
import { cloneDeep } from 'lodash'
...
    const options = {
      showIdeogram: true,
      reference: { fastaURL, indexURL },
      locus: this.locus.coordinates,
      tracks: cloneDeep(this.tracks)
    }
```

But I have to say that it was surprising to discover that `igv.createBrowser` was altering the `options` object that is fed into it. Unless altering `options` has some use-case I am unaware of, it might be worth considering creating a deep-copy of `options` in the code that implements `igv.createBrowser` before any changes are made to `options`.  That would eliminate unexpected side-effects like the one I describe here.

**Comment by jrobinso** [comment]
A deepCopy of options is a good idea,  I I would rather not use lodash but could find an implementation.    Its not straightforward though in the general case.   The options object can be complex with promises and functions as allowed values, and even the data itself as arrays of objects which may or may not be a good idea to copy (they can get really large).   This can probably all be handled with some customized deep copy.   In the meantime consider what you are doing as defense in depth.

**Comment by jrobinso** [comment]
Reopening as a reminder re copying the config.  This might be a useful starting point, with some customization needed:  https://github.com/davidmarkclements/rfdc.   General rule might be most normal fields are copied, but functions and promises are referenced (obviously), and perhaps data arrays are referenced.

**Comment by petermchale** [comment]
I'm curious: why not use `cloneDeep` from lodash?

**Comment by jrobinso** [comment]
Well, 2 reason.  We don't use lodash, but secondly we cannot blindly clone deep for reasons enumerated above.    It might be a starting point though if it handles promises and functions.   In any event we will not be copying large data structures, such as data URIs and arrays of features directly passed, so some cloning customization will be required.

**Comment by jrobinso** [comment]
After several attempts I am giving up on copying the config.  We allow too many options for this to be tractable, including not only embedding data and feature objects directly in the config, but supplying functions, promised, and custom object instances for various properties.   Not only do all objects have to be copied but potentially the prototype chain as well.   For simple json-like configs its easy, but in general its not.
