### ISSUE TITLE
Error: input buffer is broken

### ISSUE THREAD

**Issue by hong16** [igvteam/igv.js#1173]
Hi,

There is one error when I use the igv 2.2.14 to load bam files. Most files can be load successful, but some files losing. The error message has shown below.
![image](https://user-images.githubusercontent.com/33014091/92850628-4068e080-f41f-11ea-9a88-14ef55d57d31.png)

Script:
igv.browser.loadTrack({
                                type: "alignment",
                                format: "bam",
                                name: bamname,
                                url: bamfile,
                                indexURL: bamfile+".bai",
                                height: 100,
                                minHeight: 50,
                                maxHeight: 200,
                                autoHeight:true,
                                visibilityWindow: 50000,
                                colorBy: "strand",
                                order: "Number.MAX_VALUE",
                        });

By the file, the bam file can be load successful on PC IGV.

Looking forward to your reply.
Thanks,
Best regards!

**Comment by jrobinso** [comment]
igv 2.2.x is over a year old.  If you can reproduce the error with the latest release please re-open the issue.    I will need access to a test file and instructions to reproduce the error.

**Comment by hong16** [comment]
Hi,
    When I updated the version to 2.6.6, I got the below error info. Are there some differences in the input parameters between these versions? 
![image](https://user-images.githubusercontent.com/33014091/92859762-0a7d2980-f42a-11ea-8109-f7218a365f0d.png)


Thanks.

**Comment by jrobinso** [comment]
Yes,  there is no igv.browser global anymore.    You need to retain the browser created with "createBrowser" is you want to interact with it.  

```
        let myBrowser;
        igv.createBrowser(igvDiv, options)
            .then(function (browser) {
               myBrowser = browser;
            })
```
or

```
    const myBrowser =  await igv.createBrowser(igvDev, options)
```

you can simulate the previous behavior by setting a global like this

```
igv.createBrowser(igvDiv, options)
    .then(function (browser) {
          igv.browser = browser
...
```

or use await.

**Comment by hong16** [comment]
Thanks a lot!
But there is the same problem in my browser. I find that the problem not in all locals, just as below shows, failed to load one input of AT2G17340, but successful for other genes.
![image](https://user-images.githubusercontent.com/33014091/92864756-153abd00-f430-11ea-9bdd-b78788808c17.png)
![image](https://user-images.githubusercontent.com/33014091/92864896-3d2a2080-f430-11ea-9928-20480da346c5.png)

**Comment by jrobinso** [comment]
OK, to look into this further I'll need a reproducible test case (with data) that I can run.   I can't make anything out by looking at screenshots.   

You might try re-creating your bam index.

**Comment by hong16** [comment]
I tried to rebuild the bam index, but the problem still exists.

Input bam file: [https://drive.google.com/drive/folders/1-GCNMDHpcbyMmG8Eck3gsSmParwfJbjK?usp=sharing](url)

CreateBrowser:
`options = {
                showNavigation: true,
                showRuler: true,
                reference: {
                        "id": "TAIR10",
                        "name": "TAIR10",
                        "fastaURL": "data/Ath_ChrAll.fa",
                        "indexURL": "data/Ath_ChrAll.fa.fai",
                },

                tracks: [
                        {
                                name: "GFF",
                                type: "annotation",
                                format: "gff3",
                                sourceType: "file",
                                url: "data/Ath11.gff3.gz",
                                indexURL: "data/Ath11.gff3.gz.tbi",
                                order: "Number.MAX_VALUE",
                                visibilityWindow: 10000000,
                                displayMode: "EXPANDED"
                        },
                ]

        };

igv.createBrowser(div, options)
    .then(function(browser){
        mybrowser = browser;
        });
`

Add tracks:
` mybrowser.loadTrack({ //igv.browser.loadTrack
                                type: "alignment",
                                format: "bam",
                                name: libID,
                                url: bamfile,
                                indexURL: bamfile+".bai",
                                height: 100,
                                minHeight: 50,
                                maxHeight: 200,
                                autoHeight:true,
                                visibilityWindow: 50000,
                                colorBy: "strand",
                                order: "Number.MAX_VALUE",
                        });
`

**Comment by jrobinso** [comment]
Thanks, but that's not quite a reproducible test case.   I probably don't need the gff file,  I would need the fasta.    Also the indexes (bam and fasta).    Also give me exact coordinates in the form of  chr:from-to to reproduce the problem.   I will try to look at it tomorrow if I get everything.

**Comment by hong16** [comment]
Thanks, the bam file (also the index file) in google drive: [https://drive.google.com/drive/folders/1-GCNMDHpcbyMmG8Eck3gsSmParwfJbjK?usp=sharing](url),
error local:    chr2:7,541,313-7,544,383
The reference is TAIR10 fasta (Arabidopsis).

**Comment by jrobinso** [comment]
@hong16 I can't access that drive, you need to grant me access.   I sent a request.

**Comment by hong16** [comment]
https://drive.google.com/drive/folders/1-GCNMDHpcbyMmG8Eck3gsSmParwfJbjK?usp=sharing   I changed the permission of the folder, please try again.

**Comment by jrobinso** [comment]
Sorry for the delay.   This works fine for me, as you can see at this
link:  https://tinyurl.com/yyetwnjz

**Comment by hong16** [comment]
OK, thanks.
