### ISSUE TITLE
Detect onclick events that happen within the browser

### ISSUE THREAD

**Issue by haoyuanli** [igvteam/igv.js#1174]
Is there a recommended programmatic way of detecting onClick events that happen within the igv.js browser? Or it would just be something similar to attaching an onClickEvent Listener to the browser instance.

Thanks

**Comment by jrobinso** [comment]
Did you look at the documentation?  https://github.com/igvteam/igv.js/wiki/Events

**Comment by haoyuanli** [comment]
Sorry! Clearly I didn't. 😀
