### ISSUE TITLE
Is GWAS track misplaced by a couple pixels potentially?

### ISSUE THREAD

**Issue by haoyuanli** [igvteam/igv.js#1183]
This could totally be something wrong on my end, but i thought I'd ask to make sure.

When I was rendering a GWAS file, I saw something like this

![image](https://user-images.githubusercontent.com/18109953/93948341-0c30d200-fcf3-11ea-98a0-8fdc6b2a8249.png)

It appears that the minimum of the dots are somewhere a couple pixels below 2, though the minimum of the dots should be 2, calculated by the -log10(p-value), as far as I know.

For your reference, I have attached the compressed gwas file below.

[COVID19_HGI_ANA_B1_V2_CHR1.gwas.zip](https://github.com/igvteam/igv.js/files/5264649/COVID19_HGI_ANA_B1_V2_CHR1.gwas.zip)

The config is listed as below

```
      tracks: [
        {
          type: 'gwas',
          format: 'gwas',
          name: '',
          url: '',
          indexed: false,
          height: 300,
          columns: {
            chromosome: 1,
            position: 2,
            value: 5,
          },
          dotSize: 2.2,
        },
      ],
```

My apologies in advance if I made some stupid mistake somewhere.

PS. I do need to get a new pair of glasses, that's for sure.

**Comment by haoyuanli** [comment]
![image](https://user-images.githubusercontent.com/18109953/94046502-9a559880-fd85-11ea-86bf-d4b68b947fd2.png)

Maybe the y-axis was shifted up by two pixels

**Comment by jrobinso** [comment]
Thanks for the report, and test dat.  I will get to it asap.  From your screenshot it does look misaligned.
