### ISSUE TITLE
Hide/Show tracks?

### ISSUE THREAD

**Issue by amanpatel** [igvteam/igv.js#1185]
Is it possible to just hide & show tracks in the browser? My use case is somewhat related to the visibilityWindow setting. It might be a good experience for the user to just see certain tracks based on the (zoom level).

I can probably use removeTrackByName() and then subsequently use addTrack(), but I'm sure this would cause the initialization to happen again (i.e. delays for rendering).

**Comment by amanpatel** [comment]
Ok, one method of achieving this (although this feels dirty) is to update the height of the track you want to adjust via this call:

```
browser.trackViews[3].setTrackHeight(0, true, true);
```

**Comment by jrobinso** [comment]
That might cause divide by zero and other issues, especially for numeric tracks, probably harmless for feature tracks.    There's no really clean way to do this right now.

**Comment by amanpatel** [comment]
Makes sense!. Thanks for the quick response. I'll close the issue for now.
