### ISSUE TITLE
Support bedpe/interact track input using a JSON object

### ISSUE THREAD

**Issue by senzhaocode** [igvteam/igv.js#1190]
Hi igv-js developers ,

Now I am trying to input bedpe format track using a **JSON** object, for example
```
{
  type: "interaction",
  format: "bedpe",
  name: "test - proportional",
  features: [{"chr1":"chrX", "start1":22385, "end1":22387, "chr2":"chrX", "start2":23286, "end2":23288, "name":"e871822f", "score":1}, {"chr1":"chrX", "start1":96049, "end1":96049, "chr2":"chrX", "start2":24240615, "end2":24240615, "name":"6245251c", "score":1}, {"chr1":"chrX", "start1":244617, "end1":245039, "chr2":"chrX", "start2":247876, "end2":248256, "name":"3a0fe106", "DEL","score":1}, {"chr1":"chrX", "start1":249414, "end1":249453, "chr2":"chrX", "start2":249475, "end2":249475, "name":"306724c1", "score":1}],
  arcType: "proportional",
  color: "rgb(0,200,0)",
  alpha: "0.05",
  logScale: true,
  showBlocks: true
}
```
However, it does not work with an error report **"undefined is not an object (evaluating 'e.toLowerCase')"**. It will be very appreciated that a JSON format for **bedpe** input could be accepted (as I see JSON format for **bed** and **bedgraph** input are supported very well). Thank you for the help

**Comment by jrobinso** [comment]
I just pushed support for this to master.  It will be released within the next week.
