### ISSUE TITLE
Is it possible to save the IGV output in formats other than SVG? 

### ISSUE THREAD

**Issue by rdbcasillas** [igvteam/igv.js#1199]
Hello,

I am able to use renderSVG() function and it works quite well. But researchers using the tool are bothered by the fact that they have to convert SVG to PNG on their own. Are there any plans to add this functionality? What is the recommended way to achieve this? 

Thanks!

**Comment by jrobinso** [comment]
Take a screenshot with an external tool, or find an svg -> png converter.  I'm sure there are some.   There are no plans to build this into igv.js,  it would be quite complex if possible at all to do this from javascript in a web page.

**Comment by rdbcasillas** [comment]
Thanks @jrobinso. I was able to convert the output from igvbrowser.toSVG() by writing it into a Canvas using [canvg](https://github.com/canvg/canvg) and then using [FileSaver.js](https://github.com/eligrey/FileSaver.js/) to save as PNG.

**Comment by jrobinso** [comment]
@rdbcasillas Thank you for the tip, that is a neat trick.
