### ISSUE TITLE
Red locus box incorrect on initial browser display

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#1208]
The red locus box is off on the initial browser display.   This is most evident when setting the initial locus to a whole chromosome, the red box implies a zoom to about 95% of the chromosome, when it should not appear at all.   Open dev/igv-dev.html for an example.

<img width="1674" alt="Screen Shot 2020-10-28 at 2 36 45 PM" src="https://user-images.githubusercontent.com/933148/97499604-6133b980-192b-11eb-8586-23b24947e497.png">

**Comment by turner** [comment]
This PR will fix this https://github.com/igvteam/igv.js/pull/1209
