### ISSUE TITLE
Can not scroll to the next gene

### ISSUE THREAD

**Issue by jnedzel** [igvteam/igv.js#121]
I'm not sure if this is a bug or a feature.

1) Open on GTEx test installation: http://vgtxportaltest.broadinstitute.org/home
2) Open browser on gene ACTN3.
3) Using right mouse button, start to scroll left and right.  You can't scroll beyond the ends of gene 11.  I assumed that if I kept moving to the right that it would scroll to gene 12.

**Comment by jrobinso** [comment]
Jared,  I don't know what you mean by "using the right mouse button" to scroll.    I can pan left and right (click and drag)  no problem.  Could you clarify?

**Comment by jnedzel** [comment]
Jim:

I'm sorry I wasn't clear.  When panning left and right, I can't get beyond
the end of the chromosome.  For example, if I pan to the right on
chromosome 10, I would expect to be able to pan onto chromosome 11.  I
don't know if this is a feature or a bug.  If that is not the expected
behavior, then just close this ticket.

Jared

On Tue, Jun 9, 2015 at 10:23 PM, Jim Robinson <notifications@github.com>
wrote:

> Jared, I don't know what you mean by "using the right mouse button" to
> scroll. I can pan left and right (click and drag) no problem. Could you
> clarify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igvteam/igv.js/issues/121#issuecomment-110561487>.
>



-- 
Thanks,

Jared

**Comment by helgathorv** [comment]
IGV's panning has always (desktop and web versions) worked just within a chromosome.  The chromosomes aren't connected, so I don't think it makes sense to pan such that you see, in a single view, the tail end of one chromosome and the beginning of another.

**Comment by jrobinso** [comment]
Ahh, yes that's correct,  you cannot pan beyond the end of a 
chromosome.   I would not call it a feature or a bug,  its just how it 
is.  Same is true of igv desktop, and every other genome browser that I 
am aware of.
