### ISSUE TITLE
Search a position

### ISSUE THREAD

**Issue by aardes** [igvteam/igv.js#1219]
Dear IGV team,

In the new version, I am seeing a new behavior which I am not sure it's correct or not.

Use to be when I searched for a position on IGV online it visualizes the alignment in the center of the screen like what we see in desktop IGV.

![image](https://user-images.githubusercontent.com/12953535/99154234-82780200-26ae-11eb-961c-8498af4c1c54.png)

While in the new version when I looking for a position it shifted to the right side of the screen and it does not match with the centerline 

![image](https://user-images.githubusercontent.com/12953535/99154222-6b391480-26ae-11eb-97ea-2f12843f2593.png)

Thanks in advance.

Regards
Amin

**Comment by jrobinso** [comment]
I identified the issue, it will be fixed in the next igv.js point release at the end of the week.
