### ISSUE TITLE
eQTL browser hangs

### ISSUE THREAD

**Issue by jnedzel** [igvteam/igv.js#122]
1) Go to GTEx test installation: http://vgtxportaltest.broadinstitute.org/home
2) Enter ACTN3 in search box in Genetic Association panel.
3) In the table Significant SNP-Gene eQTL Association for Gene ACTN3, on the third row (for SNP rs1815739), select the "eQTL Browser" link.

The eQTL browser opens up, but the gene track doesn't appear and the browser is hung.  The browser won't scroll.  It won't respond to zooming in or out.

I've experienced this hanging intermittently.  After using the eQTL browser for a period of time, it just hangs.  I'm not seeing errors in the console.

**Comment by jrobinso** [comment]
This looks like a portal problem,  please create a standalone html file that reproduces it.

**Comment by khadley** [comment]
Reproduced in file "dev/gtex-122.html".

**Comment by jrobinso** [comment]
Proper way to detach and reinsert a div

                $("#myDiv").detach($(igv.browser.div));
...
                $("#myDiv").append($(igv.browser.div));
