### ISSUE TITLE
bed file format issue with trailing comma in exons list

### ISSUE THREAD

**Issue by gaitat** [igvteam/igv.js#1222]
Regarding a bed file, there are cases where there is a trailing comma ',' at the end of the `blockSizes` and `blockStarts`.
This causes the following code in ucsc.js 
```
    if (!(exonSizes.length === exonStarts.length && exonCount === exonSizes.length)) {
        return feature;
    }
```
to succeed ending prematurely the parsing of the exons.

If you think this is a valid issue, may I suggest changing
```
    const exonSizes = tokens[10].split(',');
    const exonStarts = tokens[11].split(',');
```
to
```
    const exonSizes = tokens[10].replace(/,$/, '').split(',');
    const exonStarts = tokens[11].replace(/,$/, '').split(',');
```
in order to eliminate the trailing comma ',' from the two lists.

**Comment by jrobinso** [comment]
Yes, thank you for the fix.
