### ISSUE TITLE
Searchable annotation tracks are not working

### ISSUE THREAD

**Issue by hrehrauer** [igvteam/igv.js#1227]
We load our own reference together with bed and gtf files. Things worked fine but now we get the error this.config.browser is undefined and the features are in the end displayed but not searchable. fyi. our code is:

`<!DOCTYPE html>
  <html lang="en">
    <head>
    <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
          <meta name="description" content="">
            <meta name="author" content="FGCZ">
              <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
                
                <title>igv.js</title>
                
                
               
                <script src="https://cdn.jsdelivr.net/npm/igv@2.7.1/dist/igv.min.js"></script>
                  
                  </head>
                  
                  <body>
                  
                  
                  <div id="igv-div" style="padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray"></div>
                    
                    <script type="text/javascript">
                      
                      document.addEventListener("DOMContentLoaded", function () {
                        
                        const config =
                          {
                            reference: {
                              id: "GRCm38.p6",
                              fastaURL: "https://fgcz-gstore.uzh.ch/reference/Mus_musculus/GENCODE/GRCm38.p6/Sequence/WholeGenomeFasta/genome.fa",
                              indexURL: "https://fgcz-gstore.uzh.ch/reference/Mus_musculus/GENCODE/GRCm38.p6/Sequence/WholeGenomeFasta/genome.fa.fai",
                              wholeGenomeView: true
                            },
                            tracks: [
                              {
                                type: 'alignment',
                                format: 'bam',
                                url: 'https://fgcz-gstore.uzh.ch/projects/p3397/STAR_51639_2020-11-13--20-37-31/PTcre-_PM3.bam',
                                indexURL: 'https://fgcz-gstore.uzh.ch/projects/p3397/STAR_51639_2020-11-13--20-37-31/PTcre-_PM3.bam.bai',
                                samplingDepth: '2000',
                                alignmentRowHeight: 10,
                                colorBy: "strand",
                                name: 'PTcre-_PM3',
                                showSoftClips: true,
                                filter: {duplicates: false}
                              },
                              {
                                name: "Genes",
                                type: "annotation",
                                format: "gtf",
                                sourceType: "file",
                                url: "https://fgcz-gstore.uzh.ch/reference/Mus_musculus/GENCODE/GRCm38.p6/Annotation/Release_M23-2019-11-05/Genes/transcripts.only.gtf",
                                displayMode: "EXPANDED",
                                name: "GRCm38.p6 Genes",
                                searchable: true
                              },
                              {                                     
                                name: "exons",    
                                type: "annotation",
                                format: "bed",    
                                sourceType: "file",
                                url: "https://fgcz-gstore.uzh.ch/reference/Mus_musculus/GENCODE/GRCm38.p6/Annotation/Release_M23-2019-11-05/Genes/genes.bed",
                                displayMode: "EXPANDED",
                                name: "GRCm38.p6 Exons",
                                searchable: true  
                              }
                            ]
                          };
                        
                       const igvDiv = document.getElementById("igv-div"); 
                        igv.createBrowser(igvDiv, config)
                        .then(function (browser) {
                          console.log("Created IGV browser");
                        })
                        
                      });
                    
                    </script>
                      
                      </body>
                      
                      </html>
`

Can you please help? The error message is:
`TypeError: this.config.browser is undefined
    value textFeatureSource.js:233
    e textFeatureSource.js:224
    h runtime.js:63
    _invoke runtime.js:293
    S runtime.js:118
    gr runtime.js:747
    o runtime.js:747
`
Best 
Hubert

**Comment by jrobinso** [comment]
Which version of igv.js are you using?

**Comment by hrehrauer** [comment]
We are using
`            <script src="https://cdn.jsdelivr.net/npm/igv@2.7.1/dist/igv.min.js"></script>
`
best
hubert

**Comment by hrehrauer** [comment]
In fact we are unsure, if we should run our own igv.js or if it is save to refer to your server?
best
hubert

**Comment by jrobinso** [comment]
Running from the server is fine, that is a permanent URL for that release.   Version 2.7.1 is a very recent release, I'm searching now to see when this bug was introduced.

**Comment by jrobinso** [comment]
I found the problem and it will be fixed in this weekends release (2.7.2).   In the meantime, do you recall the release you were using that was working?  It looks like 2.6.8 should not have this problem, but I'm not certain.

**Comment by hrehrauer** [comment]
unfortunately, I don't know the release that was still working. ;-(
We probably used it succesfully in September.
many thanks
hubert

**Comment by jrobinso** [comment]
Well the fix ill be released this weekend, as 2.7.2,  but if you need a faster solution the "2.6.8" version should work.

**Comment by hrehrauer** [comment]
thanks. we will give it a try next week.
best
hubert

**Comment by hrehrauer** [comment]
any news on when it will be rolled out?

**Comment by jrobinso** [comment]
Soon, apologies for the delay.   Could you test the distribution here to verify it works for you?

http://igv.org/web/snapshot/dist/

**Comment by jrobinso** [comment]
Just released as 2.7.2
