### ISSUE TITLE
BED file with a space delimiter misses the first annotation

### ISSUE THREAD

**Issue by gaitat** [igvteam/igv.js#1228]
I have these two bed files:

BED file with a space delimiter
```
chr2 0 1
chr2 2 3
chr2 4 5
chr2 6 7
chr2 8 9
```

BED file with a tab delimiter
```
chr2	0	1
chr2	2	3
chr2	4	5
chr2	6	7
chr2	8	9
```

I load them into igv with:
```
            tracks: [
                {
                    name: "spaces",
                    type: "annotation",
                    format: "bed",
                    indexed: false,
                    // delimiter: ' ',
                    url: "http://127.0.0.1:8081//examples/annotation_edge_data_with_spaces.bed",
                },
                {
                    name: "tabs",
                    type: "annotation",
                    format: "bed",
                    indexed: false,
                    // delimiter: '\t',
                    url: "http://127.0.0.1:8081//examples/annotation_edge_data_with_tabs.bed",
                },
            ]
```

but the first annotation of the bed file with spaces does not show up. (I use a `locus: "chr2:1-20"`)

It doesn't seem that specifying the `delimiter` key makes a difference.
Even If I add 100 to the genomic location, I dont see a difference. The first annotation in the bed file with spaces does not get drawn.

**Comment by jrobinso** [comment]
Thanks for the report.   Its not specified at UCSC, but the general consensus seems to be that bed files should be tab delimited.  For sure a space delimited bed file will not work with many tools.   Having said that, as its not specified we have tried to be whitespace agnostic, and I will fix this.

**Comment by jrobinso** [comment]
See, for example https://bedtools.readthedocs.io/en/latest/

**Comment by gaitat** [comment]
Maybe this is helpful. Just observed that when I add a line with `#` on top of the BED file with a space delimiter, then it works fine. i.e.
```
#
chr2 0 1
chr2 2 3
chr2 4 5
chr2 6 7
chr2 8 9
```

**Comment by jrobinso** [comment]
Yes I see the issue, it a little bit tricky to fix but I will get to it in
the next release, there is a point release already tested and it won't make
that one.   By the end of the month.   In the meantime a leading header
line will work as you discovered.   Or just make the files tab delimited.
 Most tools that accept bed files are going to assume tab delimitation,
bedtools requires it for example.

**Comment by gaitat** [comment]
Thanks
