### ISSUE TITLE
saving session not working

### ISSUE THREAD

**Issue by noamshoresh** [igvteam/igv.js#123]
I loaded tracks in 3 different ways: from ENCODE, from a file, using a file url.
Regardless, trying to save a session resulted in a page showing the following text:

<?php 

$filename=($_POST["filename"]);
$content=($_POST["downloadContent"]);

header("Content-disposition: attachment; filename=". $filename);
header("Content-Type: application/octet-stream; charset=utf-8");

echo $content;

?>

**Comment by turner** [comment]
This is a live server bug. Session saving works correctly in my dev environment

**Comment by helgathorv** [comment]
Andrew Texeira in IT has fixed this.  Saving sessions now works.
