### ISSUE TITLE
searchable problem

### ISSUE THREAD

**Issue by dppss90008** [igvteam/igv.js#1233]
Hi jrobinso:

I am trying to make the track "searchable"

tracks: [{
          name: "Gene",
          type: "annotation",
          format: "gff3",
          url: "http://127.0.0.1:8000/static/IGV/TAIR10_GFF3_genes3.gff",
          displayMode: "EXPANDED",
          searchable: true,
        },

while I changed the searchable property into true, an error raised
![image](https://user-images.githubusercontent.com/34399929/100085215-bd382200-2e86-11eb-9d4f-8be4bd60c248.png)
![image](https://user-images.githubusercontent.com/34399929/100085315-dccf4a80-2e86-11eb-80ee-a14a723487f8.png)

There is an error that I can't load the track
(if searchable: false, no error raised, and the track can be loaded)

Could you help me with this problem?
Thanks!

**Comment by jrobinso** [comment]
I think this is fixed, and will be released soon.  Could you try igv.js
from this test distribution to verify it works for you?
http://igv.org/web/snapshot/dist/

**Comment by jrobinso** [comment]
The fix was just released in 2.7.2

**Comment by dppss90008** [comment]
Thanks jrobinso ! it is fixed !
