### ISSUE TITLE
gCNV track (and maybe other tabixed feature tracks): feature parser fails when lines are longer than bgzBlockSize

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1235]
I pulled in recent igv.js changes and saw some of my gCNV .bed files stopped rendering. It turned out to only be an issue for  the largest files (those with ~1000 samples). The underlying cause is that featureFileReader (https://github.com/igvteam/igv.js/blob/master/js/feature/featureFileReader.js#L122) returns data strings shorter than a complete line, and featureParser then fails to find a '\n'.  I was able to fix this by increasing maxSize by something like 5*bgzBlockSize. 
I will break up my files into smaller sizes to avoid the issue, but it would be great if igv.js could detect this scenario and print a console.error or warning, such as if the first line in the file doesn't contain a "\n".

**Comment by jrobinso** [comment]
That is a large line!  Could you send me a test file for this case?  A file with just a couple of lines would be ideal.   Thanks.

**Comment by bw2** [comment]
Sure, [example.zip](https://github.com/igvteam/igv.js/files/5623084/example.zip)

```
            {
                type: 'gcnv',
                format: 'gcnv',
                name: 'example',
                url: `${rootUrl}/gcnv_large.bed.gz`,
                indexURL: `${rootUrl}/gcnv_large.bed.gz.tbi`,
                height: 200,
                min: 0,
                max: 5,
                autoscale: false,
                onlyHandleClicksForHighlightedSamples: false,
              },
```

**Comment by jrobinso** [comment]
This should be fixed
