### ISSUE TITLE
Navigating via backbutton results in duplicate tracks.

### ISSUE THREAD

**Issue by jnedzel** [igvteam/igv.js#124]
1) Navigate to: http://vgtxportaltest.broadinstitute.org/home/
2) Enter ACTN3 in Gene Association search box
3) In the Single Tissue eQTL table, in the 2nd row, for rs509556, select the eQTL browser link on the right column.
4) Hit the "Home" menu item at the top left.
5) Hit the browser back button.

Now there are two Muscle_Skeletal tracks.

**Comment by jrobinso** [comment]
How is the back button implemented (what are you actually doing)?

**Comment by jrobinso** [comment]
This is almost certainly a portal issue,  e.g. calling "loadTrack" 
twice,  or literally reloading the page.

**Comment by khadley** [comment]
This was from calling loadTrack without clearing the browser of its previous contents first when coming to the page.

This has been fixed by creating a new browser each time we come to the page and instantiating it with the tracks we want to see initialized.
