### ISSUE TITLE
Feature Request: allow feature track config to be updated after track has been added

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1240]
Currently, if I want to change a setting in the track config, I remove and then re-add the track with the updated config. It would be nice if there was a method that allowed me to update the config & rerender the track.

**Comment by jrobinso** [comment]
@bw2 Could you elaborate on why you would want to change the "config" object, rather than a particular property of a track?

**Comment by bw2** [comment]
My code uses React, so it's easier to do track state updates without worrying about which particular property changed. 
Also, more generally, it seems like a useful feature to be able to update multiple properties and repaint once.

**Comment by jrobinso** [comment]
The possible issue is config initialization wasn't designed for this,  it is not the same thing as reloading a track with fresh state, although it might be close or identical in many situations.  I'll look into the PR more carefully later just asking.

**Comment by bw2** [comment]
I might be missing deeper issues, but moving initialization code out of the track constructors didn't take much work and seemed like an ok thing to do regardless of whether it's used for this.

**Comment by jrobinso** [comment]
@bw2 Yes I think its safe, what I'm saying is rerunning the initialization code at a later date will not necessarily bring you to the same state as reloading the track, which is what you are replacing.  Just a warning.

**Comment by jrobinso** [comment]
Done

```
track.updateConfig(config)
```
