### ISSUE TITLE
sort for insertion and soft-clip reads

### ISSUE THREAD

**Issue by GSYongWu** [igvteam/igv.js#1244]
When we used igv.js, we found that the ‘sort by base ’ support for SNV and deletion is very good, but the sorting for insertion and fusion soft-clip reads is very unfriendly. The java version is very friendly to these, I hope that the next version can use these two functions better.

**Comment by jrobinso** [comment]
Could you state what version of igv.js you are using,  and also what is unfriendly about it?

**Comment by GSYongWu** [comment]
Thank you for your reply!
The version was updated yesterday and used v2.7.4, but the problem has not been solved.

for fusion, sort cannot put soft clip on top, as follows:
![image](https://user-images.githubusercontent.com/34832292/101849192-2790d800-3b92-11eb-97b9-7f5369bd1645.png)

for insertion, sort cannot put insert bases on top,
![image](https://user-images.githubusercontent.com/34832292/101849264-4f803b80-3b92-11eb-8171-2116a8b73aeb.png)

In the Java version, this is all fine，did I set it wrong?

**Comment by jrobinso** [comment]
Insertions and deletions are now included in the "sort by base" option.  Insertions are between bases, but for purposes of sorting they are assigned to the base to the right of the insertion.

Sort-clips are not considered when sorting,  either in IGV desktop or here.    Soft clips are not part of the alignment, they have no genome location.
