### ISSUE TITLE
working more dynamically with variation data

### ISSUE THREAD

**Issue by GuilhemSempere** [igvteam/igv.js#1245]
Hi

I am thinking of integrating IGV.js into a web application that manages variation data hosted in a MongoDB database. This system relies on the database for filtering variants and finally allows to export to VCF (or other formats) once the user is happy with his filtering.	

However, because of obvious data-size and processing-time considerations, I would like to avoid having to generate a full VCF (+index) before being able to show any data in IGV. The idea would be to be able to let IGV grab variant data corresponding to the currently displayed range by implementing in my app a layer that would dynamically generate a partial VCF according to the queried range. I understand that IGV extracts from the tabix file the byte-range corresponding to the variants it needs to get hold of, and then specifies this as a Content-Range header when reading the vcf.gz file.

My problem is obviously that if no full VCF is generated in the first place, my app has no way of building a byte-based index. Thus my question is, does it sound feasible to make this work by using something like "line-number" as a content-range unit?

Thanks!

**Comment by jrobinso** [comment]
I would suggest implementing a custom data "source" or custom "reader" to access a webservice on your end.     See custom-webservice and custom-reader in the examples folder.   You custom object will return "variant" object.    The variant object is rather complex, but you can avoid dealing that complexity by using the Variant constructor or "createVCFVariant" method in js/variant/variant.js in your custom source or reader.
