### ISSUE TITLE
In read insertion marker obi-one?

### ISSUE THREAD

**Issue by dnil** [igvteam/igv.js#1247]
Thank you for developing a lovely and highly useful program!

One of our users @ielvers found what appears an off-by-one, or a 5'/3' drawing issue in the insertion marker positioning? The change is GTAAG -> GTAAAG in the reads, but insertion is shown as G|TAAG insead of GT|AAG.

It may just be that the line is drawn to the "left" of the base at the position, although indel variants would normally be leftAligned, but the hover label on the insert line also hints at an off by one, as it is one position short of the vcf one?

See below picture:
![97680538-2058b380-1a97-11eb-870c-67d8adb43702](https://user-images.githubusercontent.com/758570/102876820-0b205580-4446-11eb-9fd6-b3647f7b5b1a.png)

![Screenshot 2020-12-22 at 12 30 18](https://user-images.githubusercontent.com/758570/102884511-fcd83680-4451-11eb-812b-089c6e271799.png)

and vcf:
![Screenshot 2020-12-22 at 12 32 37](https://user-images.githubusercontent.com/758570/102891429-76762180-445e-11eb-901c-645a28ef48d1.png)

This is as integrated in our third-party portal Scout (IGV.js 2.5.4 currently; original issue here: https://github.com/Clinical-Genomics/scout/issues/2170) but I'm at a loss as to how anything we do would affect the display here.

A quick test with 2.7.4 on our staging environment shows roughly the same, thought I didn't have the same variant to compare with. Here instead a fairly messy one from a test case (NA12882 - CEPH/UTAH PEDIGREE 1463), also shown on the desktop version of IGV 2.6.2 for macOS:
![Screenshot 2020-12-22 at 13 55 33](https://user-images.githubusercontent.com/758570/102891345-4fb7eb00-445e-11eb-9c36-541e6de6a51e.png)

Note how the insertion point is shown (as in the VCF) as TT|GG in desktop, but as T|TTG in IGV.js.

I suspect you can easily find a frameshift/insertion variant to compare to in a local file, but otherwise let me know and we can try to arrange something. Thanks a bunch!

**Comment by jrobinso** [comment]
Thanks I'll try to simulate this, it might be post-holiday.   In cases of
discrepancy the desktop is more likely correct.
