### ISSUE TITLE
Support for htsget+CRAM?

### ISSUE THREAD

**Issue by oyvinev** [igvteam/igv.js#1252]
Hi,

We are considering implementing htsget, and are happy to see that igvjs supports the htsget protocol. However, am I understanding the code correctly in that CRAM over htsget is not supported? If so, is there anything blocking this?

https://github.com/igvteam/igv.js/blob/8b1d63c0b477385ca2815cbe19d031f6f0804ca7/js/bam/htsgetReader.js#L42

**Comment by jrobinso** [comment]
I'm not sure I understand the question,  there is nothing in principal that would block this but the code to support it needs to be developed.   I doubt I would personally have time for it, there is not enough (or any until now) demand to justify its prioritization over other open issues, but would consider a pull request.

**Comment by jrobinso** [comment]
Closing, nothing really to do here.
