### ISSUE TITLE
Annotation File Coloring by Feature

### ISSUE THREAD

**Issue by aram10** [igvteam/igv.js#1256]
I am working with GFF/GTF files and am trying to display data in different colors based on a value in the file's attributes column (9). How do I do this? I tried adding 'field' and 'palette' attributes to the file configuration where I specified a GFF attribute in 'field' but this does not seem to work.

**Comment by jrobinso** [comment]
You can't do this with igv directly, the only way to do this is to add an explicit "color" attribute to column 9.

**Comment by aram10** [comment]
I tried that as well, an example is as follows:

`NC_045512.2	20CVa_018_CV19_S25	Non-coding Transcript	241	241	.	.	.	sample_id "20CVa_018_CV19_S25"; mutation "T"; color "#ff0000";`

That didn't work.

**Comment by jrobinso** [comment]
I don't think the color value should be quoted

**Comment by jrobinso** [comment]
Actually that doesn't look like a valid GFF file, in particular the column 9 syntax.   If you zip and attach an example GFF3 file that isn't working I will look into it.

**Comment by aram10** [comment]
Are you sure? I'm using this: https://useast.ensembl.org/info/website/upload/gff.html

IGV seems to be able to render the file fine

**Comment by aram10** [comment]
Ok, I got it to work with GFF3, the format looks identical except for column 9

**Comment by jrobinso** [comment]
Yes, the difference in all of these is column 9.   GFF2 should never be used, its long deprecated.  I am going to keep this issue open as a reminder to add support for Ensemble style GTF (there are 4 GTF format descriptions out there, actually 5 GenCode has a variant).
