### ISSUE TITLE
Is it possible to hide track name?

### ISSUE THREAD

**Issue by aram10** [igvteam/igv.js#1257]
The track name is blocking information on the track, and I can't find a suitable solution other than changing the name to " ".

**Comment by jrobinso** [comment]
Did you notice the "Track Labels" toggle in the toolbar?

**Comment by aram10** [comment]
Yes, I see that, thanks. Is there a way that I can have this selected by default upon page load?

**Comment by jrobinso** [comment]
After initializing the igv "browser" you can call
```
browser.hideTrackLabels()
```
