### ISSUE TITLE
Load directory of files into tracks

### ISSUE THREAD

**Issue by aram10** [igvteam/igv.js#1259]
Hello, is there a way to tell IGV to create tracks for all files in a directory, with the same config settings? I have ~300 annotation tracks for SARS-CoV-2 and I am trying to avoid having to insert these by hand.

**Comment by jrobinso** [comment]
Do you mean IGV desktop or igv.js?  Either way the answer is no, and it would be impossible with a web app in any event.   I would suggest writing a script to generate the required json.
