### ISSUE TITLE
Issue displaying a gene track

### ISSUE THREAD

**Issue by northwestwitch** [igvteam/igv.js#1261]
Hello! 
I apologize in advance if this has been discussed/solved.  We've recently updated to version 2.7.4 and and we noticed a strange behavior when trying to display a gene coordinate from this track: 

```
HG19GENES_FORMAT = "bed"
HG19GENES_URL = (
    "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz"
)
HG19GENES_INDEX_URL = (
    "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz.tbi"
)
```

If you open the browser at the following coordinates: chr14:55,369,194-55,369,443 (gene GCH1) then you won't see any gene, but if you zoom a bit out the gene will appear, and will stay there if you zoom back in to where you started.

Thanks for the help!
Chiara

**Comment by dnil** [comment]
It seems to work as before in version 2.7.0, but change in 2.7.1 onwards all the way to development. Something with the index change perhaps?

**Comment by jrobinso** [comment]
Thanks for the report, I will look into it.

**Comment by jrobinso** [comment]
Hi,  sorry for the delay.   I can't reproduce this,  the example below shows the gene upon loading, as shown in the screenshot.   Can you try this and tell me if it works for you?

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
    <script src="https://cdn.jsdelivr.net/npm/igv@2.7.4/dist/igv.min.js"></script>
    <title>igv.js</title>
</head>

<body>

<h1>Issue 1261</h1>

<div id="igvDiv" style="padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray"></div>

<script type="text/javascript">

    document.addEventListener("DOMContentLoaded", function () {

      var options =
            {
                // Example of fully specifying a reference .  We could alternatively use  "genome: 'hg19'"
                genome: "hg19",
                locus: "chr14:55,369,194-55,369,443",
                tracks:
                    [
                        {
                            type: 'annotation',
                            format: 'bed',
                            url: 'https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz',
                            indexURL: 'https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz.tbi'

                        }
                    ]
            };

        var igvDiv = document.getElementById("igvDiv");

        igv.createBrowser(igvDiv, options)
            .then(function (browser) {
                console.log("Created IGV browser");
            })
    })


</script>
</body>
</html>
```

<img width="1761" alt="Screen Shot 2021-02-10 at 7 53 19 PM" src="https://user-images.githubusercontent.com/933148/107600805-ad082700-6bd9-11eb-909b-80867d73f635.png">

**Comment by zareifar** [comment]
Hi IGV team,

I have a similar issue as @northwestwitch. In my IGV browser, before I set the annotation track autoHeight to true, everything worked fine. However, now that the height of the annotation track is set to auto, for some locations, sometimes the canvas is not rendered properly. Sometimes it is just blank and sometimes it is not covering everything. Strangely, for the same locations, this behavior is not consistent. In any case, if the browser window is resized or the user zooms in and out, it renders properly.

**Comment by jrobinso** [comment]
@zareifar This looks to be a separate issue, can you open a new ticket?  You can cut and paste.   Also,  when tell us the version you are using, and if possible some steps we can take to reproduce the problem.

**Comment by northwestwitch** [comment]
Dear Jim, the provided code works for me, see screenshot:

![image](https://user-images.githubusercontent.com/28093618/107739880-328af480-6d0a-11eb-954d-8db480f25251.png)

When I first modified our portal page by switching igv.js versions (2.7.0 vs 2.7.4) then the same window didn't show the gene:

![image](https://user-images.githubusercontent.com/28093618/107740713-125c3500-6d0c-11eb-8c10-003250628cb2.png)

But then, looking at your example HTML page I've realized that in our code we have an extra parameter for the gene track: 
`visibilityWindow: 300000000,` . After removing it, the gene back!

![image](https://user-images.githubusercontent.com/28093618/107742537-7d5b3b00-6d0f-11eb-9d24-b0e25deeb76e.png)

Thank you so much for your help. We're switching to version 4.7 now!

**Comment by zareifar** [comment]
Thanks @jrobinso for your reply. Here is a link to the issue: [Issue#1264](https://github.com/igvteam/igv.js/issues/1264)

**Comment by jrobinso** [comment]
@northwestwitch Thank you for that detail on the visibilityWindow,  I am able to reproduce the problem now.   That is a bug, visibilityWindow should not have that effect.   You might consider waiting a few days before updating as I am working on a fix for that now.    I am planning to release this and a few other bug fixes next week as 2.7.5.

**Comment by northwestwitch** [comment]
Ok! I was convinced I had it fixed by removing the visibilityWindow parameter! Of course we'll upgrade to the new release as soon as you publish it, but now I'm curious: what does the visibilityWindow param do, and in which situations do we need it?

**Comment by jrobinso** [comment]
@northwestwitch Removing visibilityWindow does fix it in this case, but it was a side effect.  The visibilityWindow sets the maximum genomic region (the "window") for which features will be visualized.  If you zoom out past this window you will get a "zoom in to see features" message in the track.   It is needed for very dense tracks, such as dbSNP,  for which loading an entire chromosome of data would overwhelm the browser.   If it is missing, and the track is indexed,  data is loaded for entire chromosomes.   

For most annotation tracks this is not needed, its mainly for snp and variant (VCF) tracks. that have many millions of records.
