### ISSUE TITLE
Performance issues with large volume of annotation tracks, merging tracks

### ISSUE THREAD

**Issue by aram10** [igvteam/igv.js#1265]
Hello,

I have roughly 300 different tracks of mutational data corresponding to 300 different samples of the novel coronavirus. The file format is GFF3. Currently I have all of these tracks loaded through the configuration file, but this is causing very long loading times. The reason I don't conglomerate them into one track is because it is important to have the vertical axis correspond to the different samples, and that dimensionality is lost if all the info is in one track. Is there a way to have all of these files loaded onto one track, but with different rows corresponding to each of the different files? Alternatively, is there a less resource-intensive way that I should be configuring these tracks?

**Comment by jrobinso** [comment]
The best format or what you describe is VCF with genotype (sample) columns.   That does exactly what you want.    Currently however igv.js does not show the sample names,  you can get them by mousing over but they aren't displayed.   We are working on that however.   

Are these files tabix indexed?   That will only help with zoomed in views of the variants,  if you want to get a view of the entire sequence (zoomed all the way out) tabix wouldn't help.   In that case gzipping them might help somewhat.    However the main problem is 300 different files have to be accessed which means 300 http requests at minimum.   Most web servers allow only a few active connections per client at a time,  so there is going to be a bottleneck.

**Comment by aram10** [comment]
But even with VCF, if I understand you correctly, there will still be 300 different tracks? Or is it one track that parses all 300 files? If the bottleneck still ends up being with http requests instead of time to render then it sounds like it wouldn't make a difference.

**Comment by jrobinso** [comment]
The would be one file, which will produce 300 rows of variants (1 per sample).

**Comment by jrobinso** [comment]
How large are these files (what is the sum total of their size)?

**Comment by aram10** [comment]
Roughly 2 mb.

**Comment by jrobinso** [comment]
Oh that's tiny.   Is that gzipped?

**Comment by aram10** [comment]
No. If that is relatively small, then why do you believe the performance issues arise?

**Comment by jrobinso** [comment]
You would need to profile that,  I don't have access to your system and anyway you haven't quantified the "performance",  so it would be just wild guessing on my part.   But I suspect its what I said,  300 http requests each with overhead.    You can get some idea with Chrome or Safari development tools by watching the network requests.    The first thing to do is gzip all the files, that should speed things up a bit.

**Comment by aram10** [comment]
Alright, thanks. The original source file that I used to generate the individual annotation tracks is a MUT file (which, if I understand correctly, IGV does not support). Are there any good existing pipelines for a MUT to VCF conversion, or would I need to do this myself?

**Comment by jrobinso** [comment]
I don't know, a web search might turn something up.    I had support for .mut on my radar then the issue was closed by the poster.  Was that you?  .mut is a quite old and I think deprecated format from the TCGA project (I know I worked on it), and there hasn't been any requests for it save one, which again was closed..    .maf is likely to get supported first.

On your side gzipping the files is first step,  then determining where the time is being spent using Chrome or other development tools.   Also it's always helpful to get numbers rather than subjective things like "slow".   100 ms is slow to some people.

**Comment by jrobinso** [comment]
Some useful info on web performance, instructions are for Mozilla tools but Chrome is similar. https://developer.mozilla.org/en-US/docs/Web/Performance/Understanding_latency

**Comment by aram10** [comment]
For everything to be fully loaded in its current state, roughly 20 seconds. But I appreciate the avenues you have recommended and will pursue them further. I consider this resolved.

**Comment by jrobinso** [comment]
20 seconds would be ~ 150 ms per file, if I did the math right.   That seems like high latency, but I don't know your network environment.   In any event its very easy to time this with browser development tools.   Again gzip all the gff3 files.

**Comment by jrobinso** [comment]
@aram10 Is this data public, or are you building a public website?   I thought of another solution using a custom data source, or custom reader.    You would use this by concatenating all your gff3 records into a single file,  with the sample identified by an attribute (column 9).   A custom data source would read this file at once, then piece out the records to each track based on the attribute.   I'm intrigued by this and would be willing to put together an example if you could share a few of your files,  I don't need all 300 of them.

**Comment by aram10** [comment]
We are building a public website. I've attached a ZIP of a handful of the files.

[gff3files_sample.zip](https://github.com/igvteam/igv.js/files/5992078/gff3files_sample.zip)

**Comment by aram10** [comment]
We already use column 9 in GFF3 to identify the sample.

**Comment by jrobinso** [comment]
OK, give me a day or two,  I think I can make this work.

**Comment by aram10** [comment]
Brilliant! Thanks for your dedication.

**Comment by jrobinso** [comment]
@aram10 I can't unzip the samples, it looks corrupt.   The size is only 5kb.

**Comment by aram10** [comment]
My apologies, I've rezipped them and attached it.
[Uploading gff3files_sample.zip…]()

**Comment by jrobinso** [comment]
@aram10 Give this a try.  First unzip it, copy it to your webserver leaving the directory structure intact, enter <url to your server/example.html> in a web browse, and see if it works.   To use it with your full dataset 

* concatenate all gff3 files 
* remove the header lines (starts with sequenceName, this is not legal gff3.  Alternatively put a leading # symbol on the line)
* edit example.html and set the "url" value to point to your consolidated file
* add sample tracks as illustrated in the example

Let me know how this works.  
[example.zip](https://github.com/igvteam/igv.js/files/5992781/example.zip)

**Comment by jrobinso** [comment]
@aram10 Also, if you can share your original "mut" file I will look at supporting that, and be done with this gff3 hack.  It should be straightforward.

**Comment by aram10** [comment]
I've attached it here. Sorry for the delay, busy week for me, I will take a look at your gff3 fix as soon as I can.
[mutfile.txt](https://github.com/igvteam/igv.js/files/6003414/mutfile.txt)

**Comment by aram10** [comment]
What did you mean by the genotype (sample) columns of a VCF file?

**Comment by jrobinso** [comment]
See. https://samtools.github.io/hts-specs/VCFv4.2.pdf,    however this is unnecessary as I will add support for "mut" shortly.

**Comment by aram10** [comment]
Ok sounds good, please let me know when you do and I would be more than happy to try it out.

**Comment by jrobinso** [comment]
@aram10 I'm working on this now.   Could you give me your coloring scheme, which I assume is based no "type".   Thanks.

Also, what software produced this file?

**Comment by aram10** [comment]
We based the coloring on the alternative base pair for SNPs, and had one coloring for insertions/deletions, but we do have labels for mutation type in the data (synonymous, missense, etc.) and we are open to having those have some indication as well. The file was generated through a Python script reading Excel documents. Here are the colors:

A: rgb(69, 193, 38)
T: rgb(237, 52, 31)
G: rgb(192, 108, 29)
C: rgb(39, 22, 194)
indel: rgb(170, 29, 192)

**Comment by jrobinso** [comment]
OK, maybe there should be 2 options, color by alt allele or color by mutation type.   It would be confusing, I think, to try to color by both.

**Comment by aram10** [comment]
Yes, I agree.

**Comment by jrobinso** [comment]
Actually any track that will take a "color" field will take a function.   Since this is a non-standard mut file, with alt allele in "notes",  I think we can use the function option.   It is the most flexible.   It will look something like

```function(feature) { switch:  'A' === feature.notes return rgb(...    etc```

**Comment by aram10** [comment]
Ok, I see. What is non-standard about the MUT file?

**Comment by jrobinso** [comment]
@aram10 Well the problem with these formats is that there are a number of standards.   The description I have from TCGA does not define columns beyond "type".    Perhaps a "notes" column, and other columns, are common but I don't think we can guarantee the "notes" will always have alt alleles.    Having an option to color by an arbitrary columns is not a bad idea, but for now using a function in the config will be the fastest solution.

BTW what software produced this file?

**Comment by aram10** [comment]
I did not personally produce this file, but to the best of my knowledge one of my collaborators wrote the Python to do it.

**Comment by jrobinso** [comment]
I should be able to wrap this up sometime tomorrow,  its basically working now.    We will need a new igv.js release prior to a production release on your side but that should be no problem.    Do you have a time frame for releasing your website or more specifically this visualization?

**Comment by aram10** [comment]
For this particular aspect of it, we do not have a cemented time frame yet.

**Comment by jrobinso** [comment]
This is fixed now with support for "mut" files (issue #1255).   Here is the test file from your "mut" file, edit the fasta and mut file URLs as needed.  I included a "color" function to illustrate how you can customize color, if you remove it you will get default coloring (by mutation type).   Also note there were some issues with the mut file you shared, noted in #1284, and repeated here.   This needs addressed if you are going to use this file type.  "**_there are 2 extra tabs in the header (first line) of the mut file you supplied which mess up the popup text. The first is between the "type" and "gene" headings, then there is a tab after the last column_**."

```
        const options =
            {
                showSampleNames: true,
                sampleNameViewportWidth: 150,
                reference: {
                    "id": "ASM985889v3",
                    "name": "Sars-CoV-2 (ASM985889v3)",
                    "fastaURL": "https://s3.amazonaws.com/igv.org.genomes/covid_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna",
                    "indexURL": "https://s3.amazonaws.com/igv.org.genomes/covid_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.fai",
                },

                tracks: [
                    {
                        format: 'mut',
                        type: 'mut',
                        url: '../Downloads/mutfile.txt',
                        height: 700,
                        displayMode: "EXPANDED",
                        color: function (f) {
                            const allele = f.getAttribute("notes");
                            if (!allele || allele.length !== 1) {
                                // Assumed indel
                                return 'rgb(170, 29, 192)';
                            } else {
                                switch (allele) {
                                    case 'A':
                                        return 'rgb(69, 193, 38)';
                                    case 'T':
                                        return 'rgb(237, 52, 31)';
                                    case 'G':
                                        return 'rgb(192, 108, 29)';
                                    case 'C':
                                        return 'rgb(39, 22, 194)';

                                }
                            }
                        }
                    },
                    {
                        "name": "Annotations",
                        "url": "https://s3.amazonaws.com/igv.org.genomes/covid_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.gff.gz",
                        "displayMode": "EXPANDED",
                        "nameField": "gene",
                        "height": 150
                    }
                ]
            }
```
