### ISSUE TITLE
When used with the vxe-table component, an error will be reported

### ISSUE THREAD

**Issue by bigbigJ** [igvteam/igv.js#1269]
When the project uses igv and vxe-table at the same time, igv will have this error:Uncaught (in promise) TypeError: Cannot convert object to primitive value

I can't find the reason, it makes me very confused

**Comment by bigbigJ** [comment]
I guess it is related to the utils library? Both vxe-table and igv have utils libraries, may their function names be repeated?

**Comment by jrobinso** [comment]
I don't know anything about xve-table, but  igv.js's libraries are encapsulated, the function names are not visible in global ("window") scope.     I can't really help you with the minimal information provided.

**Comment by bigbigJ** [comment]
> 我对xve-table一无所知，但是igv.js的库是封装的，函数名称在全局（“窗口”）范围内不可见。提供的最少信息对我真的无能为力。

That's a pity, I will continue to explore
