### ISSUE TITLE
Make SNPs on GTEx tissue tracks clickable to create a pop-over

### ISSUE THREAD

**Issue by khadley** [igvteam/igv.js#127]
Can this be done or would this take too long and there should be a code freeze?

I'll add information on what should show up in the pop-over here.

**Comment by jrobinso** [comment]
Does this refer to a clicking the name to get general information on the track,  or clicking the dots for details?   The latter will not be done until the data is served from Tim's webservice, which I understand is planned.   The former can be done with a configuration option.

**Comment by khadley** [comment]
This is clicking the dots for details. I'll followup with Tim and Ayellet about the web service and if it's already made or planned for after next week.

**Comment by khadley** [comment]
The pop-over information wanted is:
    1) SNP (rs id)
    2) p-value
    3) Beta/Effect Size
    4) Tissue name

Do you already have the SNP (rs id) and the p-vaue from plotting them into the track, and the tissue name from figuring out which track is being created?

Do you need a webservice that just provides effect value or do you need a web service that provides all data?

**Comment by jrobinso** [comment]
The only thing in the "bin" files are the location and p-value, nothing else,  so we either have to change file formats or use the webservice for all the data.   Since the plan is to move to a web service its not worth changing file formats at this late stage.   When the webservice is functional adding the popup will be trivial.

**Comment by khadley** [comment]
We'll be waiting until after next week to worry about this. Without the rs id information it doesn't seem like it'll be very useful so we'll worry about implementing the web service and putting in the data after the meeting. Thanks.

**Comment by jrobinso** [comment]
Actually we did have snp id,  so this is implemented with the exception of Beta/Effect size
