### ISSUE TITLE
How to use local genome and vcf?

### ISSUE THREAD

**Issue by tuh00621** [igvteam/igv.js#1272]
Is there a way to load a genome and vcf from local files? I only see loading from URL for variants and a small list of genomes.

**Comment by jrobinso** [comment]
igv.js is not an end-user tool, it is a component for developers.   What are you trying to do, are you building a website or portal embedding igv.js?

**Comment by jrobinso** [comment]
To answer your question, documentation is here:  https://github.com/igvteam/igv.js/wiki.   Any field that will take a URL will take a File blob object,  you will need to provide buttons or other means for your users to browse files using the standard Javascript classes.   The File object can be passed to igv.js.

**Comment by tuh00621** [comment]
@jrobinso I'm using an edited igv.js-flask in Google Colab to display a temporary webpage to view a VCF generated by a pipeline earlier in the notebook.
I've gotten the VCFs to load with the webpage (the vcf and the index had to be in a specific folder to be seen), but am now working on loading the reference genome from a fasta.
Thank you for the link to the wiki; I'll be experimenting with loading the fasta.

**Comment by jrobinso** [comment]
You'll need to use URLs,  but since you are using flask that shouldn't be an issue.    Reference genome doc is here https://github.com/igvteam/igv.js/wiki/Reference-Genome

**Comment by tuh00621** [comment]
@jrobinso Thank you for the help! I figured out how to add a custom fasta as a reference genome as well as a custom vcf track.
