### ISSUE TITLE
BW tracks not showing

### ISSUE THREAD

**Issue by gujarwasia** [igvteam/igv.js#1273]
Hi I am using igv.js version 2.7.4,

I have upload a BW file which is working in igv web as shown below in first pic but in my application it is not working please suggest, 2nd pic of my application.
![igv,web](https://user-images.githubusercontent.com/11008949/109159318-7bc35580-779a-11eb-85fa-0c05d487d92c.JPG)
![myapplication](https://user-images.githubusercontent.com/11008949/109159338-80880980-779a-11eb-9de0-49db1aec6dfd.JPG)

**Comment by jrobinso** [comment]
Closing for lack of response
