### ISSUE TITLE
Cursor position tooltip

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#1275]
It would be nice if a tooltip showing the cursor position showed up after a moment of hovering. Such as `bp` in the `setCustomCursorGuideMouseHandler` handler. Not always easy to tell, even with a cursor guide. Thoughts?

**Comment by jrobinso** [comment]
I agree that would be useful.   We would not have it on all the time though,  tooltips get really annoying if you don't want them.  I can think of 2 possibilities,  have it on when the cursor guide is on,  or have it on all the time but in the "ruler track" only.  @turner @helgathorv  any thoughts?

**Comment by turner** [comment]
I like it. I would add a time out to the tooltip of a few seconds. We could, if required, make that timeout length configurable.

**Comment by athomson-archerdx** [comment]
Thanks @jrobinso , I think either of those would work well. I really like the idea of it being in the ruler track so the tooltip doesn't get in the way :+1:

**Comment by helgathorv** [comment]
I also like the idea of it being in the ruler track.

**Comment by jrobinso** [comment]
@athomson-archerdx This is implemented now, but I just realized it is with neither option we proposed earlier.   You will see the genomic position if "cursor guide" is turned on, in the ruler track.      Its pushed to master but not released.
