### ISSUE TITLE
Three-Frame Translation doesn't seem to work for custom reference tracks

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#1276]
When attempting to view the three frame translation using custom reference tracks such as the attached, the translation doesn't show anything when viewing forward and doesn't line up properly when viewed in reverse. The translation data displays fine in JBrowse, is my index file missing something?
[sample_reference.zip](https://github.com/igvteam/igv.js/files/6071906/sample_reference.zip)

**Comment by jrobinso** [comment]
I'll look into it, it should work, if not its a bug I will try to fix for the next release.

**Comment by jrobinso** [comment]
There were 2 issues,  "N" was not properly handled, resulting in an exception which stopped drawing.  Also lower case bases caused an error in reverse translation.
