### ISSUE TITLE
Quality Scores for all bases in a read

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#1277]
Can you please add a way to view all Base Quality scores for a read? Ideally, something similar to the Sequence and Quality section of JBrowse as below, but just a list of raw scores like the View Read Sequence modal would work as well.

![Screen Shot 2021-03-02 at 2 30 07 PM](https://user-images.githubusercontent.com/38264214/109718061-15588180-7b64-11eb-9160-c92f784fb8ac.png)

**Comment by jrobinso** [comment]
This is not likely to get prioritized anytime soon.   If JBrowse does it I suggest you use that.   The colors are alpha-shaded by quality, which gives you some indication if you turn on "show all bases".

**Comment by athomson-archerdx** [comment]
Thank you, I'll see if the alpha shading is a suitable workaround for us :+1:
