### ISSUE TITLE
Cannot import the library in a react app

### ISSUE THREAD

**Issue by zareifar** [igvteam/igv.js#1278]
I have created a react app using create-react-app script and I was using IGV JS library version 2.7.4 in it. When I updated the IGV JS library to the latest version, I am not able to import it into the react app and I get the following error:

    Module not found: Can't resolve 'igv' in '/home/frontend-dev/igv-project/src/components/IGVBrowser'

I am using the following import statement:

import igv from "igv";

I can find the library installed in node_modules folder, but I'm not sure what has changed that prevents the app from finding the igv folder. However, when I revert back to version 2.7.4, everything works fine.

I know this is not an igv.js issue and it works fine outside the react app, but I have been trying to figure this out for days and haven't got a solution yet. Any suggestions are appreciated.

**Comment by jrobinso** [comment]
Ahh, I see the probable cause.    One or all of the following lines probably need added to package.json,  I'm not sure why they were removed.   This will require a new release which I will do today (it will be 2.7.8).    

```
  "main": "dist/igv.esm.js",
  "browser": "dist/igv.js",
  "module": "dist/igv.esm.js",
```

**Comment by jrobinso** [comment]
@zareifar Could you try again with version 2.7.8?  This should be fixed.    Sorry you wasted time on this.

**Comment by zareifar** [comment]
@jrobinso Works perfectly. Thanks Jim, you are a lifesaver!
