### ISSUE TITLE
support for gcloud requester-pays buckets

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1279]
Would it be possible to set a 'requester pays' project in the track config?

**Comment by jrobinso** [comment]
You can set that directly on the URL to the resource, no need for an additional config parameter.    e.g.  
```
https://foo.bar/my.bam?userProject=blahblah
```

**Comment by jrobinso** [comment]
@bw2 Did you try adding the parameter in the URL?

**Comment by bw2** [comment]
I didn't realize you could do this with the url. The issue resolved itself before I went to try it as some crams moved to a different bucket. I will try this next time I run into requester-pays buckets.
Thanks
