### ISSUE TITLE
Color items by pair orientation and  insert size. (was IGV desktop feature parity)

### ISSUE THREAD

**Issue by brainstorm** [igvteam/igv.js#1283]
At @UMCCR we are working in htsget integrations with our internal data portal and the curators have identified some mismatches on functionality between igv-desktop and igv-js, most notably the [**lack of htsget-variants support**](https://github.com/igvteam/igv.js/issues/1187) and some particular unsupported desktop view features that are missing on the JS version, namely from one of our curators, @JoepVissers:

1. Colour alignments by insert size and pair orientation' and 'group reads by chromosome of mate.
2. In IGV [desktop], if you zoom in enough, the reference at the bottom shows the amino acid sequence encoded by exons of respective genes. This is helpful when verifying the presence of SNVs and small indels. There is an option in IGV.js to show forward and reverse three-frame translation tracks, but this is less straightforward to interpret.

So we might be focusing a bit more on igv.js (rather than our work on AWS & igv-desktop) if we can patch those shortcomings in the midterm future, hopefully :)

@igvteam Is there some feature matrix documented somewhere that outlines the features and status supported on both sub-projects?

/cc @victorskl @ohofmann @JoepVissers

**Comment by jrobinso** [comment]
@brainstorm As I'm sure you have figured out I do virtually all the development for this as well as IGV desktop, plus a few other projects you aren't involved in like juicebox.js.   No I do not have a feature matrix, I've learned that would be pointless as external events will intervene.   Open separate issues for igv.js features, the more atomic the better, you would like to see and I will get to them.   I also accept PRs.     WRT usage igv.js is now on par with IGV desktop and I split my time more or less evenly,  unexpected crises notwithstanding.

AFAIK htsget-variants is not supported in any IGV.    I'm pretty sure I would have remembered adding that.   I did support the old GA4GH API, and there is code in there for that, but not the newer htsget.   However igv.js has generic webservice and custom reader hooks that can be used to support it.

**Comment by jrobinso** [comment]
I'm going to rename this to cover request (1).   Request 2 already has an open issue.

**Comment by mceike** [comment]
The option to "colour alignments by insert size _and_ pair orientation" in the desktop version (as opposed to the current IGV.js where you can only select one mode or the other) is very useful when looking at CNVs and would be highly appreciated by our variant interpreters at Oslo University Hospital. So consider this an upvote :)

**Comment by mceike** [comment]
Fantastic - thanks a lot!

**Comment by brainstorm** [comment]
Nice! Our team is eager to test this feature on the next release :)

**Comment by jrobinso** [comment]
This is released in 2.10.5

**Comment by mceike** [comment]
@jrobinso it appears that this wasn't entirely fixed. When choosing Color by: pair orientation & insert size, I would expect that pair orientation (green/turquoise) take precedence over insert size (red), like in desktop IGV. However, in current IGV.js it seems to be the other way around?

Example - IGV desktop: 

![image002](https://user-images.githubusercontent.com/2444948/161958875-c29c2a4a-2644-4cf3-8a72-20e7f5a8e97c.png)

Same CNV in IGV.js: 

![image003](https://user-images.githubusercontent.com/2444948/161958913-354179d8-0450-41d4-b9e4-b5c8519e38b8.png)

**Comment by jrobinso** [comment]
This will be fixed in the next point release which I am preparing for the end of the week.
