### ISSUE TITLE
New MUT functionality popup error

### ISSUE THREAD

**Issue by aram10** [igvteam/igv.js#1284]
Hello,

I really appreciate the work you've done so far with the MUT integration. I am having a small issue with a popup error for the track. So here is an image of the track on the webpage:

![muttrack](https://user-images.githubusercontent.com/59741191/110545177-b8784080-80fa-11eb-8a5a-aaa7b56b1153.PNG)

When I tried to click on one of the icons, nothing happened, so I checked the console and saw this error:

![muterror](https://user-images.githubusercontent.com/59741191/110545386-05f4ad80-80fb-11eb-99dc-213af0b1ac4f.PNG)

In an attempt to resolve this, I pulled and built the most recent versions of igv.js and igv-webapp. Both were built from source. I've also attached a screencap of the associated snippet in igvwebConfig.js

![igvwebconfig](https://user-images.githubusercontent.com/59741191/110546030-f5910280-80fb-11eb-9511-6b401951a9ac.PNG)

Also, is there a configuration option to have the y-axis correspond to different samples? Having all of the mutations together causes the most frequent mutations to bunch up and accumulate along the y-axis.

**Comment by jrobinso** [comment]
@aram10 I assume you are running from master as I haven't released anything yet.   I think the track type should be "mut", not "variant".    In another branch we are working on sample name display,  which will be to the right of the track, when that's done all will be merged and released.    In any event the intent is to dedicate a row to each sample.

So try. ```type:"mut"```. and see how that works.   BTW at the moment I'm working on an IGV desktop problem which has priority,  I will return to this soon.

**Comment by jrobinso** [comment]
I'm closing this because the error above is with the track type. ("variant" instead of "mut").   See "dev/issue_1256.html" for a full example config you can try with the latest in master.  substitute your own URLs where appropriate.

**Comment by jrobinso** [comment]
@aram10 BTW,  there are 2 extra tabs in the header (first line) of the mut file you supplied which mess up the popup text.  The first is between the "type" and "gene" headings,  then there is a tab after the last column.
