### ISSUE TITLE
issue with frequency track popup data

### ISSUE THREAD

**Issue by feedlord18** [igvteam/igv.js#1291]
Hi!

I am current facing an issue in the igv-webapp. When clicking on frequency bars, there is a high probability that I will get this error.
![image](https://user-images.githubusercontent.com/65100114/111419164-55b91300-86bf-11eb-93a4-ab1f2422dcac.png)

I tried fixing this by checking for null values with some if statements. However I've only done that in igv.min.js. I am having some trouble figuring out which file is the source code for this segment when building igv.js repository.

Current fix that I am using:
![image](https://user-images.githubusercontent.com/65100114/111419380-bf392180-86bf-11eb-9250-48afe8b046d8.png)

Some feedback would greatly appreciated!

Best!

**Comment by feedlord18** [comment]
issue is still there, but managed to fix it from wigTrack.js

**Comment by jrobinso** [comment]
@feedlord18 For the benefit of others could you describe the problem and fix?  What did you change in wigTrack.js?

**Comment by feedlord18** [comment]
Hi!

The problem was:
1. when I load up a frequency track, and I try to click on some of the features, it would give me an error saying that in function h(t, e, n), t.start was undefined.
2. That wouldn't cause the webapp to crash but will just give console errors and popup will show.

So I am not really sure if the changes I did really solved the problem or hid a deeper issue. But here are the changes to wigTrack.js
![image](https://user-images.githubusercontent.com/65100114/111421650-bba79980-86c3-11eb-9edf-4a7b457e3cb5.png)

This builds into function h(t, e, n) in igv.min.js.

Best!

**Comment by jrobinso** [comment]
Thanks.  I will look into this,   feature or position should never be null, null is an explicit value that would need to be set somewhere.    I can see that they might be undefined, but your test would fail if they were undefined.     I will investigate further.

**Comment by jrobinso** [comment]
@feedlord18 Correction -- your test will work for undefined as well,  !== will not.   A "truthy" test would be better for the feature,  i.e.   ```if(feature)```, but would not work for position as position == 0 is not "truthy".
