### ISSUE TITLE
SVG export after transformation applied to context?

### ISSUE THREAD

**Issue by AlanRace** [igvteam/igv.js#1292]
Firstly, thanks for the great tool - it really is easy to drop in and use. I am trying to do something that is perhaps not intended by the library, but I don't see why it wouldn't be theoretically possible. I am trying to export SVG with some transformation (e.g. rotation). I feel like this should be possible from the bits of code that I have read, but for some reason `renderSVGContext` seems to ignore any transformation. Do you know whether this should work?

```js
// Create a browser
var browser = ...

// Create SVG context
var svgContext = new C2S(
            {
                width: desiredWidth, 
                height: desiredHeight,
                backdropColor: 'white',

                multiLocusGap:  multiLocusGapWidth,               
                
                viewbox:
                {
                     x: 0,
                     y: 0,
                     width: desiredWidth,
                     height: desiredHeight
                }
            });

// Apply some transformation to SVG context, e.g. rotation by 90 degrees
svgContext.rotate(0.5 * Math.PI)

// Render all tracks
for (let trackView of browser.trackViews) {
     trackView.renderSVGContext(svgContext, { deltaX: currentX, deltaY: currentY })
}

```

The above renders the tracks fine, but always in the top left corner and without any rotation (or any other transformation for that matter.

**Comment by AlanRace** [comment]
Quick update to this. It seems to only be a problem if the C2S context is used to draw something else prior and/or after to the call to `renderSVGContext` which includes some (different) transformation.

After I realised that, I implemented a workaround, which involves generating two C2S contexts; one for igv.js browser and one for generating the main diagram. Then its possible to add the generated SVG from the browser to the main document after applying a transformation (as below).

```js
let browserSVG = browser.toSVG()

var parser = new DOMParser();
var browserSVGDocument = parser.parseFromString(browserSVG, "image/svg+xml");

let mainSVGDocument = ...// create document from main SVG diagram

// Get the root element from the browser SVG
let rootGroupElement = browserSVGDocument.getElementById('root-group');

// Set transformation as necessary
rootGroupElement.setAttribute('transform', 'rotate(90)')

// Add the igv.js browser to main SVG document with transformation
mainSVGDocument.documentElement.appendChild(rootGroupElement)
```

**Comment by turner** [comment]
Thanks for the update. Your use case sounds interesting, but not one we had anticipated. Your new implementation looks like the way to go. Glad it worked for you.
