### ISSUE TITLE
error making variant track : "TypeError: n is undefined"

### ISSUE THREAD

**Issue by kwon0299** [igvteam/igv.js#1295]
Hello, I'm a student who is trying to make a web database for our lab's research results.
Currently I succesfully made igv.js embedded with custom reference genome and custom tracks.
However, when I'm trying to add variant track with custom vcf file, the console log (also in website error message) sends me the error message like following:
![image](https://user-images.githubusercontent.com/34572783/112605826-10cd7300-8e5b-11eb-83e3-93184d94e376.png)

When I inspect the line 44 at 'vcfParser.js', it does not seems to be using any variables named 'n'.
Does this problem related with my custom vcf file's header?
Currently i'm inspecting on your example's vcf files.

My custom vcf file is here:
[wgs_test_sorted.vcf.gz](https://github.com/igvteam/igv.js/files/6210448/wgs_test_sorted.vcf.gz)

**Comment by jrobinso** [comment]
This file works fine for me (see screenshot).    What version of igv.js are you using?

**Comment by kwon0299** [comment]
currently using 2.7.6 by html <script scr>.

**Comment by jrobinso** [comment]
I need a reproducible test case, again the file you sent works fine for me.   Please zip up your html and attach it here, or just paste the contents of the file.

**Comment by kwon0299** [comment]
[upload.zip](https://github.com/igvteam/igv.js/files/6219101/upload.zip)
here's the aggregated essential html codes and custom bed file for custom tracks.
If you need .fa and .fai files for the refreence track, please refer to following link:

http://bidas.kaist.ac.kr/static/genome/reference.fa
http://bidas.kaist.ac.kr/static/genome/reference.fa.fai

Thanks.

**Comment by jrobinso** [comment]
I can't reference your fastas, your server is down, but the VCF loads fine.   Try switching to version 2.7.9, and give me any steps you can to reproduce the error.  For example what genomic location are you viewing?  

Your html looks o.k., but try adding a format specifier to your vcf track definition.  ```format: 'vcf',```

See the screenshot below from your VCF 

<img width="1401" alt="Screen Shot 2021-03-26 at 8 53 06 AM" src="https://user-images.githubusercontent.com/933148/112789963-1d94c700-9013-11eb-891c-9c842b514b76.png">

**Comment by kwon0299** [comment]
It seems like problem is related with my server. when i used the original vcf file, it kept throwing me errors. However, when i unzipped the vcf file and used it, it worked well. Thanks for the help! Closing this issue.
