### ISSUE TITLE
This cram file crashes igv.js

### ISSUE THREAD

**Issue by xzhub** [igvteam/igv.js#1297]
I've tried many different versions of igv.js, from 2.2.9/2.2.17/2.7.6 to 2.7.9, they all crash with this cram file. I think there might be something wrong with cram file, but I can't locate the issue.

Could you please take a look and see what is the cause? Thanks very much!

Error message:
![image](https://user-images.githubusercontent.com/3990687/112744149-008ad480-8fd0-11eb-99db-0c33b839b023.png)

html code:

```
<script src="https://igv.org/web/snapshot/dist/igv.min.js"></script>
<div id="igv-div" style="padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray"></div>

<script type="text/javascript">

    document.addEventListener("DOMContentLoaded", function () {

        var options =
        {
            genome: "hg19",
            locus: "chr2:49206890-49207049",
            tracks: [
                {
                    type: 'alignment',
                    format: 'cram',
                    url: 'L4-L9.sv_simple.normal.cram',
                    indexURL: 'L4-L9.sv_simple.normal.cram.crai',
                    samplingDepth: '2000',
                    alignmentRowHeight: 4,
                    colorBy: "strand",
                    name: 'TEST'
                }
            ]
        };

        var igvDiv = document.getElementById("igv-div");

        igv.createBrowser(igvDiv, options)
                .then(function (browser) {
                    console.log("Created IGV browser");
                })

    });

</script>
```

cram/crai file: 
[Archive.zip](https://github.com/igvteam/igv.js/files/6216928/Archive.zip)

**Comment by jrobinso** [comment]
This looks like it is a very sparse cram file, which in turn leads to large genomic regions being compressed into a single slice.  To decode these large slices correspondingly large reference sequence regions need to be loaded.   This is not possible in a web browser, you will run out of memory.   The workaround is to use "bam" files for such sparse files.    Alternatively you could setup an htsget server to decode the CRAM on a server.
