### ISSUE TITLE
DEL is always 0

### ISSUE THREAD

**Issue by xzhub** [igvteam/igv.js#1298]
Is this behavior normal? While clicking on the depth track, the popup window always shows "DEL 0", even there is a del.
![image](https://user-images.githubusercontent.com/3990687/112774149-4ea0e600-906b-11eb-9581-bbb81c88ed31.png)

Tested with the latest version.

**Comment by jrobinso** [comment]
That's not normal, and I can't reproduce it.

**Comment by xzhub** [comment]
Seems the latest version v2.7.9 has fixed this issue, but at least v2.3.0 is still vulnerable. Let me do more tests then get back here.

**Comment by xzhub** [comment]
I will simply switch to the latest version. Thanks!
