### ISSUE TITLE
Reference genome from local file

### ISSUE THREAD

**Issue by nlapalu** [igvteam/igv.js#1302]
Hello,

Is it possible to load a ref genome with the reference object from a local file without getting a CORS exception of the browser ? 
I would like to set up a browser in a html page to visualize results from an analysis without web server.
Thanks for your help.

nico

**Comment by jrobinso** [comment]
The only way to load local files is to use the "FileReader" object, which enables the user to select the file and returns an opaque "File" object.   CORS is not the issue,  javascript is not allowed to go fishing about your local file system.   igv.js accepts the "File" object in place of a URL, but it is up your containing application to present this to the user.   This is how igv-webapp works.    If you want to supply a path to the file you will have to run a web server.
