### ISSUE TITLE
Variant genotype not iterable

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#1303]
I'm getting the following error when trying to visualize a variant track that combines data from individual sources. Each of the three individual tracks will display just fine, but when loading the `combined.sorted.vcf` file, this is the console log:

```
featureFileReader.js:70 Warning: index file not specified.  The entire vcf file will be loaded.
Cc @ featureFileReader.js:70
variantTrack.js:222 Uncaught (in promise) TypeError: n.genotype is not iterable
    at Ed.draw (variantTrack.js:222)
    at sl.draw (viewport.js:325)
    at sl.repaint (viewport.js:310)
    at gl.updateViews (trackView.js:361)
variantTrack.js:222 Uncaught (in promise) TypeError: n.genotype is not iterable
    at Ed.draw (variantTrack.js:222)
    at sl.draw (viewport.js:325)
    at sl.repaint (viewport.js:310)
    at gl.repaintViews (trackView.js:298)
    at gl.setTrackHeight (trackView.js:264)
    at gl.adjustTrackHeight (trackView.js:415)
    at gl.updateViews (trackView.js:365)
```

I couldn't see anything relating to genotype that was different between the working tracks and combined, any thoughts?

[Combined VCFs.zip](https://github.com/igvteam/igv.js/files/6246750/Combined.VCFs.zip)

**Comment by jrobinso** [comment]
How were the VCFs combined?  You can't just concatenate VCFS, you need to use a tool to do that.

**Comment by jrobinso** [comment]
That's too many files for me to sort through.   A couple of things to check,  all vcfs will need to have the same number of genotypes, in the same order, and with the exact fields (again in the same order).   That's a minimum.   There are tools, I think, that will safely combined VCFs.    Also, there should be tools out there to validate a VCF.

**Comment by athomson-archerdx** [comment]
Thanks, I'll check with my team that does the combination to make sure that we're following those rules and get back to you if we have something more clear.

**Comment by jrobinso** [comment]
Look at section 1.6.2 here if you haven't before, its rather specific  https://samtools.github.io/hts-specs/VCFv4.3.pdf.     I will look at igv.js for possible bugs in the meantime.

**Comment by jrobinso** [comment]
@athomson-archerdx Actually I think I see it, its an igv.js bug.  The error isn't from combining, its present in the "lofreq.ann.vcf".   This vcf has a genotype column, but no genotype field (GT).   This is the first such VCF I have seen, , but from the spec it looks like it should be allowed.   The spec just says GT must be the first field if present, but no fields are required.   I should have a fix for this soon.

**Comment by jrobinso** [comment]
This should be fixed now in the master branch.

**Comment by athomson-archerdx** [comment]
Thanks! I appreciate the quick fix 😄
