### ISSUE TITLE
Issue displaying cram track

### ISSUE THREAD

**Issue by feifei9606** [igvteam/igv.js#1304]
Hello~ I encountered the unconsistant diplay of the cram and the bam file recently. The position of **3-bp insertion** does not same. The cram file was converted from bam using samtools-1.10. The lastest igv.js and igv web app were tried. The bug describled below,

![image](https://user-images.githubusercontent.com/24381328/113678373-23fd0000-96f1-11eb-8fb4-80a993e7fb37.png)

but, the IGV desktop app displayed correctly, there may be few bugs in parsing cram file.

![image](https://user-images.githubusercontent.com/24381328/113678508-4727af80-96f1-11eb-8a07-cbae3ac643a3.png)

bam/cram file for test, position: **chr7:39991399**
[cram.zip](https://github.com/igvteam/igv.js/files/6263093/cram.zip)

**Comment by jrobinso** [comment]
Thanks for the report.   When you say "the latest" for igv.js and igv-webapp are you referring to the latest code in the master branch, or to the latest release?

**Comment by jrobinso** [comment]
@feifei9606 Thanks for the report and the test data, this is fixed and will be released soon.

**Comment by feifei9606** [comment]
Thanks for the quick fix~
