### ISSUE TITLE
Genes track doesn't show specific genes

### ISSUE THREAD

**Issue by yaarau** [igvteam/igv.js#1305]
Hi, 
when using IGV javascript with refGene.sorted.txt.gz for the Genes track, we don't see specific genes in this track - e.g. POLG in locations 15:89,862,175-89,862,214 and HTRA2 in locations 2:74,757,174-74,757,212. While these genes are seen in the UCSC browser, they are not shown in the IGV jafascript page as well: https://igv.org/web/release/2.7.9/examples/functional-url.html.
We do manage to see other genes in this track (e.g. CSF1R in locations 5:149,433,578-149,433,616). We checked the refGene.sorted.txt.gz file we are using, and it contains the locations we don't see in the Genes track. We also looked at the code and we don't see any condition that indicates these genes cause problems.

Can you please help us with this?

Thank you,
Yaara Unger

**Comment by jrobinso** [comment]
I see that gene at the location specified (see screenshot) with https://igv.org/web/release/2.7.9/examples/functional-url.html..   Perhaps its scrolled out of view?  Try using the scrollbar or change the track height

<img width="1857" alt="Screen Shot 2021-04-06 at 9 22 14 AM" src="https://user-images.githubusercontent.com/933148/113744672-c39e9c00-96b9-11eb-9f37-169a3c7193cd.png">

**Comment by yaarau** [comment]
Hi,the screenshot you added shows the gene we manage to see. Please look at the ticket - examples for genes we don't see are POLG in location 15:89,862,175-89,862,214 and HTRA2 in location 2:74,757,174-74,757,212.
Can you please check these locations?
Thank you,Yaara
    On Tuesday, April 6, 2021, 07:24:35 PM GMT+3, Jim Robinson ***@***.***> wrote:  
 
 


I see that gene at the location specified (see screenshot) with https://igv.org/web/release/2.7.9/examples/functional-url.html.. Perhaps its scrolled out of view? Try using the scrollbar or change the track height

**Comment by helgathorv** [comment]
In  https://igv.org/web/release/2.7.9/examples/functional-url.html I do see POLG in location 15:89,862,175-89,862,214 and HTRA2 in location 2:74,757,174-74,757,212. But note the SCROLLBAR in the track -- you need to either scroll down or use the gear menu to make the track taller.

**Comment by yaarau** [comment]
OK, thank you.
Can you please tell me whether there's a way to show all the track, so that there's no need to scroll down in order to see the genes?

**Comment by jrobinso** [comment]
As a developer or an end user?

**Comment by yaarau** [comment]
as a developer

**Comment by jrobinso** [comment]
To control aspects of the annotation track you will need to use a "reference" object instead of just specifying the genome id with the "genome" property.   For hg19 you can use this for a start.   Then either set  a large initial height for the gene annotation, or use "COLLAPSED" for display mode.   See the documentation in the wiki or more details.

```
{
  "id": "hg19",
  "name": "Human (CRCh37/hg19)",
  "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta",
  "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta.fai",
  "cytobandURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/cytoBand.txt",
  "tracks": [
    {
      "name": "Refseq Genes",
      "format": "refgene",
      "url": "https://s3.amazonaws.com/igv.org.genomes/hg19/ncbiRefGene.txt.gz",
      "indexed": false,
      "visibilityWindow": -1,
      "removable": false,
      "order": 1000000,
    }
  ]
}
```
