### ISSUE TITLE
MUT file support not available from local file upload

### ISSUE THREAD

**Issue by feedlord18** [igvteam/igv.js#1306]

**Comment by jrobinso** [comment]
Please give a more complete description of the problem,  issues filed with no description will be closed.

**Comment by feedlord18** [comment]
When I upload a MUT file from the menu, it says, "Unable to load track file test.mut - unknown file format"

**Comment by jrobinso** [comment]
@feedlord18 What is confusing here is igv.js does not have a load menu.  What menu are you referring too?

**Comment by feedlord18** [comment]
oh wait, sorry about this. I was referring to the webapp. Posted issue in the wrong repo. :)

**Comment by feedlord18** [comment]
I'll close this issue and post in igv-webapp

**Comment by jrobinso** [comment]
@feedlord18 mut files are not supported yet in igv-webapp,  what led you to think they were?   In fact they are not released yet in igv.js.
