### ISSUE TITLE
[FEATURE REQUEST] - Have vertical line that goes across tissue tracks, gwas catalog track, and gene track

### ISSUE THREAD

**Issue by khadley** [igvteam/igv.js#131]
It would be helpful if a person moused over the genome browser and had a vertical line that was drawn across all of the tracks (tissue, gwas catalog, and gene) so that the user can see what lines up together.

The mouse hover to draw line functionality is similar to how it's drawn on this plot on tumor portal:

http://www.tumorportal.org/view?geneSymbol=TP53

**Comment by vingorius** [comment]
+1

**Comment by jrobinso** [comment]
I'll try to get to this soon.  Coincidentally I developed the tumor portal viz referenced above.   I never liked the "Straightedge cursor" label and checkbox,  any feedback or suggestions on how to enable / disable the line?

**Comment by vingorius** [comment]
how about "guide ruler" or "guide line" as label?

And  it has to be distinguished with 'center line' which was mentioned at #137 .
Color or style(dotted or line) may be good.

**Comment by nlwashington** [comment]
+1

**Comment by jrobinso** [comment]
This is partially implemented with #207.   What's missing is a button to toggle it dynamically.
