### ISSUE TITLE
Add "copy sequence" popup menu item.

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#1319]
When viewing the details of an annotation feature, it would be handy if the popup included the length and full sequence associated with that feature for easy copy+pasting.  Thoughts?

**Comment by jrobinso** [comment]
That's too much information, could be many megabases.  Some features span a chromosome.

**Comment by jrobinso** [comment]
Perhaps a "copy sequence" popup menu item as IGV desktop has,  this is active if the feature is < some maximum length.    I will rename this issue to that effect if its o.k. with you.

**Comment by athomson-archerdx** [comment]
That should work for me, thanks :+1:

**Comment by flowersjg** [comment]
Hey folks, just curious if this one is coming up on the roadmap anytime soon. Thanks, really enjoying igv.js so far!

**Comment by jrobinso** [comment]
Yes, this is planned for the next release, which will be 2.10.0

**Comment by flowersjg** [comment]
Wonderful! Do you have a rough idea of when that might be released?

**Comment by jrobinso** [comment]
By the end of the month

**Comment by flowersjg** [comment]
FYI, evidently `navigator.clipboard` only works with https enabled (or localhost). Not a huge deal, but wanted to let you know.

**Comment by jrobinso** [comment]
OK, thanks, I suppose if the page is http we will just remove that menu
item.

**Comment by flowersjg** [comment]
There are some workarounds to access the clipboard in other ways, I think. Your call, obviously! Thanks as always @jrobinso.

**Comment by jrobinso** [comment]
I've decided against workarounds, unless someone submits a low impact PR that has been tested on all major browsers.

**Comment by jrobinso** [comment]
The problem being the warning at MDN that these workarounds are not recommended and could be pulled at any time.
