### ISSUE TITLE
bigwig track only appears for one chromosome

### ISSUE THREAD

**Issue by thomasyu888** [igvteam/igv.js#132]
Thanks in advance for your time.  For some reason, my bigwig track only shows data for chromosome 1, and nothing else.  I am on the right reference genome and have re downloaded the data to double check.  Please kindly advise me what to do.

**Comment by jrobinso** [comment]
I'll need to see the bigwig, are you sure you have data on other 
chromosomes?   You can convert it to a wig and grep to be sure.

Also attaching a screenshot would be helpful.   And please always report 
the IGV version you are using by selecting "Help > About".

**Comment by thomasyu888** [comment]
Thank you for the quick response.  I am currently using igv-beta.js version and following the example in api.html.  I am certain that there is information on the other chromosomes, as I used the same data for biodalliance and jbrowse as well.  
![chr1](https://cloud.githubusercontent.com/assets/10556275/8605128/f2b7661e-2637-11e5-9892-af2e5972b9c2.png)
![chr22](https://cloud.githubusercontent.com/assets/10556275/8605132/f6c6d564-2637-11e5-9a6a-393289ed5877.png)

Furthermore, I was wondering if we stored our data in an S3 bucket and produced a link to that data, would we be able to use these links in the igv-web if we enabled CORS, or would other problems occur.

**Comment by jrobinso** [comment]
OK, apologies,  I thought this was an igv-desktop report.   I'll look 
into it.

CORS enabled files on amazon are no problem.

**Comment by jrobinso** [comment]
Hi,

So far I can't reproduce this problem using Encode bigwigs.   I've added 
an example bigwig to  http://igv.org/web/examples/api.html .  Its the 
last item in the menu ("Encode bigwig") and resolves to 
http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneGm12878H3k4me3StdSig.bigWig. 
Could you try that url in your instance and report if you see the problem?

Is it possible to share a bigwig that illustrates the problem, perhaps 
with example html?

Thanks

Jim

**Comment by thomasyu888** [comment]
Thank you for all your help.  Unfortunately I cannot share the data, however, I found that the bigwig file you used has a different format as the bigwig I have:
>hg19.bigwig
>#bedGraph section chr11:63534600-63568700
>#bedGraph section chr11:63568700-63604050

>my.bw
>#bedGraph section 11:63534600-63568700
>#bedGraph section 11:63534600-63568700

Could it be because of the lack of chr?

**Comment by jrobinso** [comment]
That shouldn't matter but I'll test it.  Could you just extract a few 
lines with a data point or two from different chromosomes, and share that?

I'm traveling now through Monday,  I'll look into this more when I return.

Jim

**Comment by thomasyu888** [comment]
Thank you for the quick response.  I just tested it on my computer, and when I added chr in front of all the chromosome numbers with a small dataset and transformed it to a bigwig, the data showed up.  I did this on a small subset of data.  
![chr1](https://cloud.githubusercontent.com/assets/10556275/8626588/435f0f0a-26fa-11e5-96df-192b8efb7481.png)
![chry](https://cloud.githubusercontent.com/assets/10556275/8626590/45ff590e-26fa-11e5-9ad0-0623787ddf46.png)

As I use wigToBigWig provided by UCSC, I do not know how to make bw files from wig files if they are not in this format.

>#bedGraph section chr11:63534600-63568700
>chr11:63534600-63534603

**Comment by jrobinso** [comment]
Hi,  I did the opposite test,  I downloaded an encode bigwig, converted it to bedgraph,  and removed all the "chr" prefixes from the chromosome names.   I then converted back to bigWig using bedgraphToBigWig and still could not reproduce the problem.    It might be a problem of data scale,  i.e. the autoscaling is setting a range too high for data on other chomosomes to be seen.

**Comment by thomasyu888** [comment]
Thank you for your help.  I saw that you have opened an issue to set min and max on the bigwig tracks.  Is there a way to add it into my html file? ie...
>{
>url:my.bigWig',
>name: 'example',
>max:30
>}

**Comment by jrobinso** [comment]
Yes, actually that is exactly how you do it.   Now that I know there is 
at least 1 user of this library besides myself I will try to up the 
priority on documentation.   In the meantime feel free to use the git 
issues to pose questions,  this will also serve to open documentation 
issues.

Jim

**Comment by thomasyu888** [comment]
Thank you for all your help. Unfortunately, adding a max didn't change anything. However, I did find
>bedGraph section ERCC-00003:0-1023
>ERCC-00003	0	996	0
>ERCC-00003	996	1022	1
>ERCC-00003	1022	1023	0

in our bigwig files. Could this be the cause?

**Comment by jrobinso** [comment]
Those won't show up anywhere, but should harm anything.   I will create 
a file with this in it and see if I can reproduce.

I understand you can't share data on a public forum but if you could 
share a bigwig privately that reproduces this I could probably fix it 
pretty quick.   If that's possible respond here and I'll give you an  
ftp upload url.   Possibly if you convert to bedgraph and just grep out 
a few lines for each of your chromosomes (including ERCC-00003) that 
would be enough to reproduce.

Jim

**Comment by thomasyu888** [comment]
Thank you for all your help.  I am definitely willing to send you the bigwig after I grep out a few lines for each chromosome.  I apologize about all the hassle.  It would be much easier if I could just send you the original file

Tom

**Comment by jrobinso** [comment]
OK,  you can upload it by ftp using the instructions below.  Reply here 
when its uploaded and I can fetch it with my private account. Before 
uploading verify that it reproduces the problem.

Thanks

Jim


Any individual that has an internet access can send files to the Broad 
"anonymously" via our external public FTP site. All that is needed is an 
FTP client.

Our external public ftp site address isftp.broadinstitute.org 
<ftp://ftp.broadinstitute.org/>. A user logs in with a username of 
anonymous and a password of their email address.

Once connected, the user can upload the data to the/incoming/directory 
(note "cd to incoming). This upload directory is a blind directory, i.e. 
after the upload is done, the file that was uploaded, or any file in the 
incoming directory, cannot be read.

**Comment by thomasyu888** [comment]
Dear Jim,

I apologize for the delay.  Thank you for all your help.  The file name is A2final.bw.  I hope I did it right.  I was able to reproduce the problem with it.  Please kindly let me know if you have any questions.

**Comment by jrobinso** [comment]
Hi Thomas,

I got the file, and I can reproduce the problem, so that's progress.   I 
will update when I find the problem.

Jim

**Comment by thomasyu888** [comment]
Dear Jim,

Thank you for the quick responses.  You have been very helpful.  Look forward to hearing from you about the problem.

Cheers,
Thomas

**Comment by jrobinso** [comment]
Thomas, was the original source of this file a bedgraph or wig file?  Are you able to convert this file to a bedgraph using bigWigToBedgraph?  I get a bus error

bigWigToBedGraph A2final.bw A2final.bedgraph
Bus error

**Comment by jrobinso** [comment]
Thanks for the test file, problem fixed.

**Comment by thomasyu888** [comment]
Dear Jim,

Thanks for fixing the problem! 

Cheers,
Tom
