### ISSUE TITLE
read count from cram popup is sometimes wrong

### ISSUE THREAD

**Issue by scalavision** [igvteam/igv.js#1323]
Sometimes the read count is a few counts off for cram files. It is shown in the image below, which is from HG002 sample in opened in https://allel.es/, updated with the newest version of igv, 2.8.1. It usually diverges between 1 and 5-6 counts, and it seems to consistently be increased. It might have improved a bit from 2.7.9 which we used when we first encountered this, but this is not confirmed in any way.

The bam file was converted to cram using samtools. When opening the tracks in java version of igv, the read count shows the same for both bam and cram, and it is equal to the bam count in igv.js.

I have extracted the example region from the original bam and cram in example01.tar.gz. It shows the same count error.

Let me know if you need more information to properly investigate this.

![read_count_wrong_igvjs](https://user-images.githubusercontent.com/3958212/117146077-20be6800-adb4-11eb-9f2d-44e780a93068.png)

[example01.tar.gz](https://github.com/igvteam/igv.js/files/6427315/example01.tar.gz)

**Comment by jrobinso** [comment]
Aplogoies for the delay looking into these.   I can't reproduce this with the example data you provided,  the config object for my test case is below.   If you can modify the config to reproduce the issue, or give me other instructions, I will investigate further.

```javascript
        {
            genome: "hg19",
            locus: "1:161,518,391-161,518,554",
            tracks:
                [{
                    type: 'alignment',
                    format: 'bam',
                    url: 'example01/example01.bam',
                    indexURL: 'example01/example01.bam.bai',
                    name: 'BAM',
                    height: 300
                },
                    {
                        type: 'alignment',
                        format: 'cram',
                        url: 'example01/example01.cram',
                        indexURL: 'example01/example01.cram.crai',
                        name: 'CRAM',
                        height: 300
                    }
                ]
        }
```

**Comment by scalavision** [comment]
Thanks for looking into this. I am on vacation but will look into it again when I am back, in a couple of weeks. You can close this if you want, and I can reopen it, if I still have problems.

**Comment by jrobinso** [comment]
@scalavision Actually on closer inspection I found the issue.   Alignments marked "duplicate" are being filtered from BAM sources, but not from CRAM sources.   I will correct this for the next release (they should be filtered from both).

**Comment by scalavision** [comment]
That is great! Looking forward to the fix :-)

**Comment by jrobinso** [comment]
This should be fixed now, igv.js version 2.9.3
