### ISSUE TITLE
IGV-Web and CRAM encoded with samtools "no_ref" option

### ISSUE THREAD

**Issue by bioinfo-chru-strasbourg** [igvteam/igv.js#1324]
Dear all,

I'm trying to deploy IGV-Web on a docker service. It mainly works, but I've some problem with CRAM decoding, especially with CRAM files encoded with "no_ref" option (infinite loading... no crash...). It works with a default encoded CRAM (version=3.0,level=5).

I see that it works on online IGV-Web app (https://igv.org/app/), and I suppose due to a specific configuration, i.e. mount of docker volumes for genomes, and MD5 REF_PATH. Is there specific configurations for CRAM and MD5 REF_PATH? 

IGV-Web app version 1.5.1
igv.js version 2.7.9
I mainly use a MacBook Pro with 8 CPU and 16Go memory (same on a CentOS server 32CPU 240Go memory). It works well on IGV Desktop. 

Thanks!!

**Comment by jrobinso** [comment]
There is no special configuration that I am aware of.  When you say it works at igv.org/app, what do you mean?   Do you have a URL to a no-ref CRAM that works at igv.org/app but does not work in your container?

The CRAM reader comes from the JBrowse project, @cmdcolin might have some insight.
