### ISSUE TITLE
fastaURL

### ISSUE THREAD

**Issue by namratasp20** [igvteam/igv.js#1329]
1) fastaURL accepts url only and not local files.
Thus, I wanted to understand if google drive/one drive link to fasta files can be used? If yes, how should it be configured?
(I tried making folder containing sequences as public and using the same link, which didn't yield results)

2) Currently if I provide ncbi ftp url, it is not working to display genome browser. I wanted to understand if the problem is that fasta is in zip format (.fna.gz) or some other issue?
eg. I want to display genome for bacteria Wolbachia. The sequences are available at ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/022/285/GCF_000022285.1_ASM2228v1/

I am providing the following urls in reference 
  reference:{
            "name": "Wolbachia",
            "fastaURL": "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/022/285/GCF_000022285.1_ASM2228v1/GCF_000022285.1_ASM2228v1_genomic.fna.gz",
            "tracks": [
              {
                "name": "Annotations",
                "url": "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/022/285/GCF_000022285.1_ASM2228v1/GCF_000022285.1_ASM2228v1_genomic.gff.gz",
                "displayMode": "COLLAPSED",
              }
            ]
          }

**This renders a empty genome browser**

**Comment by jrobinso** [comment]
ftp protocol is not supported, only http and https.   Also, fastaURL will accept a local File blob object, but cannot of course accept a local file path as this is javascropt.

**Comment by jrobinso** [comment]
Also, gzipped fastas are not supported.

**Comment by namratasp20** [comment]
Thanks for the response

Could you provide some more information regarding local File blob object, how to use it in place of fastaURL or any related helpful link? I haven't come across or used this concept before.

**Comment by jrobinso** [comment]
The File object is standard javascript,  there is lots of information.  Try a web search.   Ditto for your ftp question, mixed protocols are not allowed in javascript, as the page is loaded by http/https those are the only protocols you can use to load data.
