### ISSUE TITLE
svg of +/- bedgraph lacks the zero line (chrom, safari, firefox)

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1332]
Just upgraded to igv 2.8.2, running with igvR 1.13.1.

toSVG() returns a mostly faithful rendition of these data, but with the left-side vertical scale partly obscured.
```
  chrom    start      end value
1 chr18 58982201 58982241   0.5
2 chr18 58982251 58982261 -10.2
3 chr18 58983001 58983081  20.0
```
The svg file, when examined in a browser, does a good job with the vertical scale, but the zero line is missing.
igv.js via igvR in Chrome:
![Screen Shot 2021-05-20 at 11 08 59 AM](https://user-images.githubusercontent.com/2480712/119028014-d44e5d00-b95b-11eb-8480-4552f3ae440a.png)

svg file in Chrome: 

![Screen Shot 2021-05-20 at 11 10 39 AM](https://user-images.githubusercontent.com/2480712/119028489-5fc7ee00-b95c-11eb-9d7d-e23803d09c46.png)

**Comment by turner** [comment]
Closed with commit 10725d29
