### ISSUE TITLE
minor feature request: programmatic hide/show track labels

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1333]
Dear igv team,

I could not find this in the api - forgive me if I missed it.   

An igvR user asked for programmatic control, similar to that offered for the "Save SVG" button, for hiding and showing track labels.   If this makes sense to you, perhaps this low-key request could go on your to-do list?

 - Pa ul

**Comment by turner** [comment]
Paul,
If you want a button to show/hide at `showTrackLabelButton = true` to the browser config. 
If you want programmatic controls use the API: `browser.hideTrackLabels()` and `browser.showTrackLabels()`.

**Comment by paul-shannon** [comment]
My bad.  I overlooked browser.[hide|show]TrackLabels.

Thanks.
