### ISSUE TITLE
arriba

### ISSUE THREAD

**Issue by yingfeikeji** [igvteam/igv.js#1337]
hi:
  How to use Arriba data to render IGV?
  Thanks you!

**Comment by jrobinso** [comment]
What is "Arriba" data?

**Comment by yingfeikeji** [comment]
https://github.com/suhrig/arriba

**Comment by yingfeikeji** [comment]
This is the result file from Arriba
[http://www.lpf929.com/wp-content/uploads/2021/06/fusions.pdf](url)

**Comment by yingfeikeji** [comment]
This PDF is produced by Arriba's R script. Can it be converted to JSON and then used for IGV?

**Comment by jrobinso** [comment]
The short answer is no.  You can possibly write scripts to convert the tsv output to bedpe, which can be loaded into IGV, but I don't know what you would accomplish in doing that.  BTW you are posting to the igv.js javascript component forum, not IGV.
