### ISSUE TITLE
Allow fallback for fetching genomes.json e.g. if igv.org is unreachable

### ISSUE THREAD

**Issue by dnil** [igvteam/igv.js#1340]
Hi, I'm fairly sure it has not gone unnoticed, but just to get updates: the certificate on igv.org expired tonight, which is causing some issues downstream with automation (and possible concern for users visiting).

```
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “igv.org”, which could put your confidential information at risk. (genomes.json, line 0)
[Error] Unhandled Promise Rejection: Error accessing resource: https://igv.org/genomes/genomes.json?randomSeed=0.j3jilitafer&version=2.8.1 Status: 0
	(anonymous function) (igv.min.js:63:178047)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

**Comment by RoadRoller** [comment]
It's not certificate expiration, the error is ERR_CERT_COMMON_NAME_INVALID.

**Comment by dnil** [comment]
Right, the new certificate from tonight appears to be for data.igv.org. It may be very obvious, but a workaround for your users can be to point their browsers to https://igv.org and accept the situation for now.
We use the https://cdn.jsdelivr.net/ to mirror the code, but the app seems to request a few files from igv.org during runtime. Perhaps it would be a good idea to allow them to be mirrored as well, or at least add some error handling to them missing?

**Comment by dnil** [comment]
One might e.g. change 
https://github.com/igvteam/igv.js/blob/8dbe2cb7992e964de8436882604c49e2a4e5ee76/js/genome/genome.js#L66
to directly retrieve https://s3.amazonaws.com/igv.org.genomes/genomes.json or even a local version as a fallback if there are exceptions on that request.

**Comment by helios** [comment]
> One might e.g. change
> https://github.com/igvteam/igv.js/blob/8dbe2cb7992e964de8436882604c49e2a4e5ee76/js/genome/genome.js#L66
> 
> 
> to directly retrieve https://s3.amazonaws.com/igv.org.genomes/genomes.json or even a local version as a fallback if there are exceptions on that request.

There is also something I do not understand: I am using igv-webapp and in my setup igv-webapp loads first my custom reference `genomes.json` AND then there is second call to the outside pointing to https://igv.org/genomes/genomes.json. Why do you need this second call ? Shouldn't the first be enough ?

**Comment by jrobinso** [comment]
The certificate issue has been fixed.  @helios Yes there is some duplication, its on my list to fix.   The first call is from the webapp, the second call from igv.js.

**Comment by helios** [comment]
> @helios Yes there is some duplication, its on my list to fix. The first call is from the webapp, the second call from igv.js.
@jrobinso at the moment I fixed it replacing the remote call with a reference to a local resource. This, within my deployment stack to have minimum impact of the overall code base and build system (starting from your source).

**Comment by jrobinso** [comment]
@helios Looking at the code I think this is configurable without code changes. by (1) setting ```loadDefaultGenomes: false``` and (2) ```genomeList: urlToYourJson```,  or ```genomes: {genomeJson}```
