### ISSUE TITLE
Gene symbol placement

### ISSUE THREAD

**Issue by dnil** [igvteam/igv.js#1342]
Since v2.8.1, gene symbol placement appears to have some issues. Something with the calculation of center position placement has changed from previous versions and desktop version behaviour. Gene symbols (the name labels) are no longer centered on the gene in the view after load. On large zoom levels, with multiple genes in sight, it is possible to see them, and with detailed zooms and avid scrolling, one can glimpse them briefly before they are moved out of the view port on recalculation.

**Comment by jrobinso** [comment]
Thanks for the report.  Looking at the log there are some commits that might be implicated, but they would also have affected v2.8.0.     I can reproduce it, will investigate.

**Comment by jrobinso** [comment]
This should be fixed and released as 2.8.5.

**Comment by dnil** [comment]
Thank you kindly! Confirm solved with v2.8.5 on my end!
