### ISSUE TITLE
Is there a way to turn off the refgene track?

### ISSUE THREAD

**Issue by SimonLi5601** [igvteam/igv.js#1346]
I am debugging a loading issue, is there is a possible to turn off the refgene track? It seems a default track added by the IGV js.
It's referring to the file below. I didn't add it to my tracks, I already set showSequence: false.
https://s3.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz

**Comment by jrobinso** [comment]
See the section on defining the reference, nothing is loaded by default unless you use the shortcut "genome" property:  https://github.com/igvteam/igv.js/wiki/Reference-Genome

**Comment by SimonLi5601** [comment]
Got it! Thank you!

**Comment by SimonLi5601** [comment]
Hi Jim, sorry I have to reopen this ticket since I found the issue is related to the genome track. I am working with IgvJs in a React framework. However, I found it took a long time for IgvJs to load the genome track for either HG19 or HG38. I debugged and tracked down to the line of code  below to see why it takes quite a long time to load the tracks.  I am wondering what is this doing, it takes more than 15 seconds to go through this line, did I miss something to make it faster?
https://github.com/igvteam/igv.js/blob/df81773947f375150cc34a75c5a23696810ac032/js/feature/featureTrack.js#L132

My settings look like below,
igvOptions = {
     locus,
     tracks: [],
     genome: 'hg38',
     showKaryo: false,
     showIdeogram: false,
     showNavigation: false,
     showRuler: false,
     showCenterGuide: false,
     showCursorTrackingGuide: false,
     showCommandBar: false,
     showSequence: false,
   }

**Comment by jrobinso** [comment]
Hi, sorry I don't know anything about react, but that line of code loads in much less than a second for both hg19 and hg38 for me.   Can you confirm you are using the latest igv.js release, and reproduce the issue with a plain (non-react) html page?    If so zip and post the html page here.  

This doesn't appear to be related to the issue as originally posted, to turn the refGene track off you cannot use the "genome" property as described earlier.

I'm traveling, and responses might be delayed.

**Comment by SimonLi5601** [comment]
Hi Jim, thanks for you reply even you are in traveling. I can't reproduce the issue in a plain html page, and I guess the issue is only triggered in some circumstances with React.
Why I think it is related to the original post because I found the refgene track slow down the display at the beginning. I thought there is a way to turn it off, but as you figured out, the gene track is from the genome property and there is no way to turn off this track as I understand. I looked into further in the codes and I located the function that consumes most of the time. It seems it tried to read and parse all the genes features (56MB in size)?  I don't know if it is normal, any idea would be appreciated!

https://github.com/igvteam/igv.js/blob/df81773947f375150cc34a75c5a23696810ac032/js/feature/featureParser.js#L164-L196

<img width="645" alt="Screen Shot 2021-06-21 at 3 35 30 PM" src="https://user-images.githubusercontent.com/18488136/122817992-a0da5780-d2a6-11eb-9dd3-701270230fe9.png">

**Comment by jrobinso** [comment]
@SimonLi5601 actually what I said is you need to define your reference with the "reference" property, as I noted in the link, and do not use the "genome" property.  That is how you turn it off.  Is that clear?  If you continue to use the "genome" property it will continue to load the refGene track.

Yes it is normal to parse the features if the track is loaded.   Its not normal to take so long, but I cannot debug your environment.   The refgene track loads in a couple of seconds.   How long does this page take to load?  https://igv.org/app

**Comment by SimonLi5601** [comment]
Hi Jim. Thanks for your patience! It works! It's much faster if I takes off the default refgene  track from the reference genome and add another refgene track using "url": "https://s3.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz",
What's difference between refGene.sorted.txt.gz and ncbiRefGene.txt.gz?

reference = {
    "id": "hg38",
    "name": "Human (GRCh38/hg38)",
    "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa",
    "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa.fai",
    "cytobandURL": "https://s3.amazonaws.com/igv.org.genomes/hg38/annotations/cytoBandIdeo.txt.gz",
    "aliasURL": "https://s3.amazonaws.com/igv.org.genomes/hg38/hg38_alias.tab",
  },

**Comment by jrobinso** [comment]
There's no substantial difference between the 2 refGene tracks.   If you
are in a slow internet environment using an index for the gene track will
speed things up.   The index url. (property indexURL) for that track is.
https://s3.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz.tbi

**Comment by SimonLi5601** [comment]
Thanks for the help, Jim! I will close this. I think this might be helpful for other users are having the same issue. I don't think it is related to the slow network though, the memory usage in the application context might contribute to the issue.

**Comment by marhabaie** [comment]
I have experienced the same issue using it in React (it takes so long for it to load the genome) and when I used "reference" property instead of "genome" it loaded almost instantly! Thanks for your help!
