### ISSUE TITLE
Issue in loading tracks

### ISSUE THREAD

**Issue by namratasp20** [igvteam/igv.js#1347]
Hi Team,

I am currently using python - django to build a webpage and deploying it using heroku

I have loaded annotation tracks (.gff3 and .bed) using igv.js.
I am able to view these tracks on local server. However, the tracks are not being rendered upon deploying the webpage (only empty IGV browser is being displayed).

Are there any options which needs to be taken care of, so that tracks are rendered upon deploying webpage ?

**Comment by jrobinso** [comment]
I'm not sure I understand your question,  all options are described in the wiki page.   There are no special options other than what are described there.

Are you calling "createBrowser" before the page is rendered?  If so you will have to call

```
browser.visibilityChange()
```

after the div igv.js is placed in is visible, as documented here:  https://github.com/igvteam/igv.js/wiki/Browser-API-2.0#visibilitychange.    For an example of this use see [examples/tabs.html] (https://igv.org/web/release/2.8.6/examples/tabs.html)

**Comment by namratasp20** [comment]
I tried above , but issue is not resolved.

The tracks are visible when website is tested locally. On deploying over https, igv tracks are not rendered and only the logo appears

**Comment by jrobinso** [comment]
@namratasp20 I really can't help you debug your system without a reproducible test case.  One suggestion would be to examine the network traffic using a browser development tool to see requests and responses for the track data.  

I do not understand what you mean by "On deploying over https",  deploying what?
