### ISSUE TITLE
MUT popup rendering issues

### ISSUE THREAD

**Issue by feedlord18** [igvteam/igv.js#1349]
The popups for MUT file is not displaying Genes and Notes column. I have attached the file.

![image](https://user-images.githubusercontent.com/65100114/125007188-b46b1980-e02d-11eb-8dde-3ae8b037b66b.png)
[test_mut.txt](https://github.com/igvteam/igv.js/files/6787957/test_mut.txt)

**Comment by helgathorv** [comment]
The columns must be tab-separated, but there seem to be spaces in your file after the first 5 required columns. 
When I fixed that in your file, it displayed the Genes and Notes columns too.

Note however that there is something not quite right with the igv.js popup display in the whole-genome view, but when viewing individual chromosomes it works correctly when the file is tab-separated.
