### ISSUE TITLE
Slow performance when using contig-level reference even with disabling "showChromosomeWidget"

### ISSUE THREAD

**Issue by christianbioinf** [igvteam/igv.js#1352]
Hi all,
I am using igv.js with a custom reference sequence that consists of more than 100k contigs which are almost equally sized (hence reduction via option `showAllChromosomes` does not work well). For this, it was already recommended before that one should disable the whole genome view using the option `reference: wholeGenomeView: false` as well as disable the chromosome widget in the navigation bar using the option `showChromosomeWidget: false`. 

Disabling the whole genome view works nicely. However, I still noticed that most of the loading time (see performance infos below) that most of the loading time (i.e. more than 40s) are spent on the chromosome widget. Basically, the option `showChromosomeWidget` simply hides the div but the `<select>` entries are still build and contained in the DOM (which results in "Page Unresponsive" popups from Google Chrome after some time).

<img width="659" alt="Performance_before_fix" src="https://user-images.githubusercontent.com/10414269/125922686-82f5de89-317f-4c42-aa04-c78f301ccb36.png">

I will soon provide a small fix using a pull request based on the new version that significantly improves the performance (see performance after fix below) and I, (with my limited JS experience) do not see any drawbacks of it.

<img width="1066" alt="Performance_after_fix" src="https://user-images.githubusercontent.com/10414269/125922924-57f9b334-1bd7-4ddf-a20d-ba0bb59235a5.png">

Best,
Christian

**Comment by jrobinso** [comment]
Thanks for the report and the PR.   I found a simpler solution, namely don't create the widget if show == false.   This should fix the issue.
