### ISSUE TITLE
Switch scale of manhattan plots from log to linear

### ISSUE THREAD

**Issue by omarwagih** [igvteam/igv.js#1355]
Loading .gwas files in a locally run igv.js shows manhattan plots in linear scale and has an option to make it a log scale.
For igv.js, it seems it automatically applies a log scale with no way to make it linear.

Is there a way to do this that I'm not aware of?

Thanks

**Comment by jrobinso** [comment]
What type of values are your GWAS scores?  As documented here, by default pValues are assumed, but there is an option to indicate the values are probability (and thus use a linear scale):   https://github.com/igvteam/igv.js/wiki/GWAS.

**Comment by omarwagih** [comment]
I'm actually using it to, in a roundabout way, plot fold changes by converting my values into into p-values (10^-val) since the output is expected to be plotted as a -log10 (If there's a better way of doing this please let me know!). 

In the local browser I see what I expect, which is the -log10 p-value plotted in linear scale by default (attached screenshot).

![](https://i.ibb.co/qmj2BTM/Screen-Shot-2021-07-26-at-8-40-16-AM.png)

Not sure if I'm doing this right but for igv.js, I also tried added the track header as such 

> track type=gwas name=test_track posteriorProbability=true

which did not work for me (the local IGV also complained about having the header there).

Any advice would be greatly appreciated. Thanks!

**Comment by omarwagih** [comment]
I'm actually using it to, in a roundabout way, plot fold changes by converting my values into into p-values (10^-val) since the output is expected to be plotted as a -log10 (If there's a better way of doing this please let me know!).

In the local browser I see what I expect, which is the -log10 p-value plotted in linear scale by default (attached screenshot).

![](https://i.ibb.co/f97BPgv/Screen-Shot-2021-07-26-at-8-45-17-AM.png)

Not sure if I'm doing this right but for igv.js, I also tried added the track header as such

track type=gwas name=test_track posteriorProbability=true

which did not work for me (the local IGV also complained about having the header there).

Any advice would be greatly appreciated. Thanks!

**Comment by omarwagih** [comment]
I'm actually using it to, in a roundabout way, plot fold changes by converting my values into into p-values (10^-val) since the output is expected to be plotted as a -log10 (If there's a better way of doing this please let me know!).

I made a mistake. The values are showing up as expected in igv.js!

**Comment by omarwagih** [comment]
For the link you shared, are we able to add a track header as such?

`track type=gwas name=test_track posteriorProbability=true`

to gwas files?

**Comment by omarwagih** [comment]
Consider the simple example of:
```
chr	bp	p	snp
chr13	1000000	0.9999	a
chr13	1000000	0.00005	b
```

When visualized in igv.js, this is what I get 

![](https://i.ibb.co/m882Fkn/Screen-Shot-2021-07-26-at-10-09-28-AM.png)

The first example should give a -log10 pvalue very close to 0, yet on the scale it shows as ~2.

**Comment by jrobinso** [comment]
The settings are for the track configuration, not the header line.   I will add more options but that's what exists now.   These instructions are for igv.js (this project) screenshot you show, by the way, is for igv-webapp.

**Comment by jrobinso** [comment]
I will add some more options for the next release.

**Comment by omarwagih** [comment]
Thanks!

**Comment by jrobinso** [comment]
@omarwagih let's leave it open, otherwise I will not remember.
