### ISSUE TITLE
Error when loading bam file without index: this.parseAlignments is not a function

### ISSUE THREAD

**Issue by bartcharbon** [igvteam/igv.js#1359]
We are using igv to view small bam slices without a bai index file.

This worked fine for the previous version we used (3.8.6) of igv.js, but since updating to the 3.9.4 release an error occurs while loading the track:
"this.parseAlignments is not a function"

**Comment by jrobinso** [comment]
Could you post the track "config" you are using to load the bam?

**Comment by bartcharbon** [comment]
Sorry, I forgot to mention that we are using the "data urls"

Our code to create the track config looks like this:

```
tracks.push({
            order: 1,
            type: 'alignment',
            format: 'bam',
            name: `Alignment`,
            url: 'data:application/gzip;base64,' + [base64_String_here]
          });
```

**Comment by jrobinso** [comment]
Ah, important detail.   This is fixed in the master branch, and will be in the next release.
