### ISSUE TITLE
Lighter gray color for mapping quality 0 reads 

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#136]
Is there a way to make mapq=0 reads show up light gray like in IGV?

![image](https://cloud.githubusercontent.com/assets/6240170/9050599/5e04d390-3a1d-11e5-8c23-6b25bac877d0.png)

**Comment by jrobinso** [comment]
Will do

**Comment by bw2** [comment]
I was initially thinking this could be implemented here:
https://github.com/igvteam/igv.js/blob/425028b001b1a4da9390b915dda8612e08709474/js/bam/bamTrack.js#L68
but since the lighter color would be needed for any alignment shading scheme, I'm thinking a function like colorToLighterColor(colorString) could be created and called here:
https://github.com/igvteam/igv.js/blob/425028b001b1a4da9390b915dda8612e08709474/js/bam/bamTrack.js#L394

colorToLighterColor could then be implemented using the last answer here: 
http://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes

**Comment by jrobinso** [comment]
Thanks for the reminder and implementation pointers.   I've implemented the equivalent of the igv-desktop scheme, which is to apply and alpha of 0.15 to the color if mq == 0.   The implementation is not the most robjust, it assumes an "rgb()"  type input string,  but will do for now.   Please test and re-open if you find issues,  I tested against a GA4GH 1kg bam.

**Comment by brentp** [comment]
when using colorBy: strand, it's still nearly impossible to see which are mapping-quality 0 alignments.

![mq0](https://user-images.githubusercontent.com/1739/81856992-cf6ff580-951e-11ea-95a9-3f1794ee821b.png)

The read touching the top of the click box is mapping-quality 0 as are several others in the view.

Is there some config I can change to improve this?

**Comment by jrobinso** [comment]
There's no config for this, but also it looks like a bug.   I think its fairly easy to see in IGV desktop.  

I'll reopen this bug,  the original issue was not for color-by-strand but its close enough.

**Comment by oyvinev** [comment]
Should be fixed by resolving this TODO: https://github.com/igvteam/igv.js/blob/c67503bb2cc1af7d1b28ea5b3bfa963bb47e843e/js/igv-color.js#L229

Optional work-around is setting `negStrandColor` and `posStrandColor` as rgb-values (e.g. `"rgb(150, 150, 230)"`).

**Comment by jrobinso** [comment]
@oyvinev thanks for reviving this, and finding the problem
