### ISSUE TITLE
can we return custom components in the trackclick event?

### ISSUE THREAD

**Issue by algarsi3** [igvteam/igv.js#1363]
I have seen that we can [modify](https://igv.org/web/release/current/examples/custom-track-popover.html) what happens when the trackclick event is fired.

I tried to modify it so it returned a div component, which worked great (i.e., `"return <div>It works</div>"`). My doubt is if it is possible to return a React component like this one: `<CustomTable data={data} />`. If I return the component, it renders nothing and, if I return it as a String, it does not recognize the custom element.

My question is if there is a workaround to display custom components when the trackclick event fires (it would be great to display my own component).

**Comment by jrobinso** [comment]
I'm not sure what you mean precisely by "component", but certainly igv.js will not understand React, you need to return valid html if you want to use the igv.js popover window.

However you can do anything you like from the "trackclick" callback, including I suppose opening a React component,   then return "false" to prevent igv.js from opening the default popove window.   See examples/custom-track-click.html.

```
                    browser.on('trackclick', function (track, popoverData) {
                        var symbol = null;
                        popoverData.forEach(function (nameValue) {
                            if (nameValue.name && nameValue.name.toLowerCase() === 'name') {
                                symbol = nameValue.value;
                            }
                        });

                        if (symbol && !genesInList[symbol]) {
                            genesInList[symbol] = true;
                            $("#geneList").append('<li><a href="https://uswest.ensembl.org/Multi/Search/Results?q=' + symbol + '">' + symbol + '</a></li>');
                        }

                        // Prevent default pop-over behavior
                        return false;
                    });
```

**Comment by algarsi3** [comment]
Thank you @jrobinso, I managed to modify it so that a custom React Dialog opens when the `trackclick` event fires.
