### ISSUE TITLE
Support for encoded data of binary files

### ISSUE THREAD

**Issue by gaitat** [igvteam/igv.js#1366]
I would like to ask if there is support for base64 encoded data (i.e. data:application/octed-stream) of binary files. For example I have a case of bigbed and bigwig files that I need to encode before passing them to igv and they dont seem to work.
On the other hand I also tested base64 data encoded wig files and they worked fine.
For example this sequence works:
`const bwSource = new BWSource({url: require.resolve("./data/bb/myBigBed2.bb")});`
On the contrary this does not work:
`const bwSource = new BWSource({url: 'data:application/octet-stream;base64,6/KJhwQAAAADBAAAAAAAADMEAAAAAAAACBMB ...});` 

Thank you

**Comment by jrobinso** [comment]
data URIs (including gzipped data) should work for fasta, bam, and plain text formats (e.g. wig and bed),  but will not work for cram or "bb" formats (bigwig and bigbed).  If you need to do that I suggest first converting to bed or wig,   then gzip (optionall) and create the data URI.   For some examples see the files in. "dev/datauri".

**Comment by gaitat** [comment]
Is it a technical limitation?

**Comment by jrobinso** [comment]
I'm not sure what you mean, its not implemented, of course it could be done.

**Comment by jrobinso** [comment]
This should work now, but it has not been exhaustively tested.    See https://github.com/igvteam/igv.js/blob/master/dev/datauri/ucsc-interact3.html for an example

**Comment by gaitat** [comment]
Thank you, will do some testing.
