### ISSUE TITLE
Space between tracks too tight

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#1367]
The vertical space between tracks is too tight, 2 pixels I think, making it really hard to distinguish the boundaries for certain types of tracks such as seg and alignments.   Maybe 5 pixels is enough, really it probably should be configurable, but at a minimum let's try 5 pixels.  Prior to the dom refactor I think it was 4 pixels.

**Comment by turner** [comment]
Fixed with commit ab472a7a
