### ISSUE TITLE
Transparent background on track label mouseover

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#1368]
When mousing over the track label, the background becomes grey with transparency.  The grey is good, but not the transparency.  In some cases the label text becomes hard to read.

<img width="189" alt="Screen Shot 2021-08-27 at 11 48 35 AM" src="https://user-images.githubusercontent.com/933148/131175336-fa9e5ae0-874f-4c9e-9db7-47a886f4b74b.png">

**Comment by turner** [comment]
Fixed with commit ab472a7
