### ISSUE TITLE
Show vertical center line

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#137]
Would it be possible to show the center line to help line up variants with reads?

**Comment by jrobinso** [comment]
This is already an Alignments preference option (View > Preferences > 
Alignments).

**Comment by jrobinso** [comment]
Apologies I see this is an igv.js ticket,   not IGV.   Yes we will add 
this option.

THanks

**Comment by bw2** [comment]
Hi Jim, I'm now adding IGV.js to another portal and wanted to revisit this.
What do you think about an API for this being like:
`v1 = igv.browser.add_vertical_line("chr1:12345") `

and, possibly (though not as needed) a remove method like:
`igv.browser.remove_vertical_line("chr1:12345")` or  `igv.browser.remove_vertical_line(v1)`

The line would then appear across all tracks and scroll left-right with the other features.
Even better, these could be track-level functions, and could be called in a loop on each track when a global line is needed.

**Comment by subji** [comment]
+1

**Comment by vingorius** [comment]
+1

**Comment by bw2** [comment]
Hi Jim, if I have some time to work on this, would you be open to a PR on this?

**Comment by jrobinso** [comment]
Yes, for sure.   I will have time myself after Wednesday.  I've been 
traveling basically the whole month.

**Comment by jrobinso** [comment]
This one might be tricky, btw,  I'm not sure we have an element  to draw 
the line on.   Perhaps you should study it and propose something first,  
or just go for it and we'll iterate,  but I have a feeling this will 
take a few attempts.

**Comment by bw2** [comment]
Got it. Without looking into the details yet, I was thinking to draw it on the track(s) so the line would be fixed at a particular genomic coord and  scroll horizontally along with the feature it's marking.

**Comment by jrobinso** [comment]
Comment -- pull request #207 does not really address this case directly, it is more relevant to #131.

**Comment by turner** [comment]
Closed with commit de0b9e3a

**Comment by turner** [comment]
See `igv-dev.html `for configuration options:

To present fixed one-base wide guide pair:
`showCenterGuide: true`

To present cursor tracking guide:
`showCursorTrackingGuide: true`
