### ISSUE TITLE
Update already opened igv window

### ISSUE THREAD

**Issue by carolnaomivars** [igvteam/igv.js#1373]
Hello!

I would like to know if something like this would be possible:

If I open an IGV window in any position and then want to view another region, is it possible to automatically update the existing window? (without opening another window or browser)
I cannot think of any way to perform this "identification" that a window is already opened, but I would like to know if anyone has come across something like this.

Thanks in advance!!

**Comment by jrobinso** [comment]
Sorry I don't really understand your question.  Note this is the forum for the igv.js javascript component.

**Comment by carolnaomivars** [comment]
Sorry I will try to explain it better.
I am using igv.js in an application. Currently, when I want to look at a genomic region, a new window opens in this region of interest.
However, if I want to look at another region I need to open another new browser window that wiil direct me to this other region.
My question is if it would be possible to "detect" that an instance of igv.js ia already created and only change the locus search to a new position. (instead of always creating a new instance)

**Comment by carolnaomivars** [comment]
Oh yes, I meant programatically.
Thanks, I think you answers gave me some insight!
