### ISSUE TITLE
Feature suggestion - Native typing support

### ISSUE THREAD

**Issue by rootux** [igvteam/igv.js#1376]
Thank you for creating this library.

Having an IDE automatically understand typing, requires a `@typing/igv` library

[Here](https://github.com/datavisyn/igv_wrapper/blob/master/typings/index.d.ts) is a project that can be used as a base for typing (4 years old :sweat_smile: )

Would love to see this in this project

**Comment by jrobinso** [comment]
Its an interesting idea but I doubt I would have time to support this and keep it up to date.

**Comment by jrobinso** [comment]
I'm going to close this as we don't have any time to support it, and in general like non-typed programming anyway.  That's why we don't use type script.
