### ISSUE TITLE
Display insertions in bam reads

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#138]
As far as I can tell, insertions aren't currently displayed?
![image](https://cloud.githubusercontent.com/assets/6240170/9077636/62e9a084-3afe-11e5-881f-dfa3d89c5d27.png)

Is there some way to enable the purple bar or some other glyph to mark insertions?

Thanks
-Ben

**Comment by jrobinso** [comment]
You are correct, they are not.   Keep these coming,  I will be working through them.   This is "beta" software, not everything is implemented.

**Comment by bw2** [comment]
Will do.. thanks.

**Comment by bw2** [comment]
Hi Jim, have you had a chance to look at this? if not, would you be open to a pull request?
I'm guessing this would take another loop over the CIGAR (like https://github.com/igvteam/igv.js/blob/425028b001b1a4da9390b915dda8612e08709474/js/bam/bamTrack.js#L398) that would just render the insertion glyph(s) once the loop over alignment blocks is done (https://github.com/igvteam/igv.js/blob/425028b001b1a4da9390b915dda8612e08709474/js/bam/bamTrack.js#L415) so that the glyphs would be rendered on top.

**Comment by jrobinso** [comment]
Hi,

Not yet,  sorry for the delay.  I've been out of the office dealing with 
my move,  but will be in my new location next week and am planning to 
look through all open igv.js issues then.

I'm always open to a pull request.

Jim

**Comment by jrobinso** [comment]
Looking at this now while sitting in the airport.  I think the change 
required is pretty minor,  doesn't require a second loop through the 
cigar string.   If you want to help speed things up it would be helpful 
to have a small test file with a few insertions of varying length,  
perhaps using the example from the sam spec.    If you can help in this 
way  just check the bam and index into test/data/bam and do a pull request.
Thanks

**Comment by bw2** [comment]
Thanks Jim. I'll submit the example bam. 
For now I'm seeing the mapq=0 color fix but not the insertion fix when using 
http://igv.org/web/beta/igv-beta.min.js

![image](https://cloud.githubusercontent.com/assets/6240170/9483377/9b05b2d0-4b6d-11e5-8b09-423bc0779fb1.png)

**Comment by jrobinso** [comment]
Thanks for the test file.  Try again for the insertions, there was a bug.

**Comment by bw2** [comment]
Looks great.. thanks!
