### ISSUE TITLE
Add ability to mark ROI interactively

### ISSUE THREAD

**Issue by scalavision** [igvteam/igv.js#1380]
Our interpreters would really like to have the ability to mark a region on the RulerSweeper. In this way, they can scroll down the track list, but keep the overview of a variants position etc.

Is this something that could be added?

I could make an attempt on this, if you are considering such a feature but don't have time for adding it.

**Comment by jrobinso** [comment]
Could you describe in a little more detail how you envision this looking?    Would it be some sort of transparent overlay running over all the tracks after a sweep action?

**Comment by scalavision** [comment]
Sorry for my vague explanation @jrobinso , I was thinking the ability to mark the `ruler` like this:

![igv_marked_sweeper](https://user-images.githubusercontent.com/3958212/133835771-c726ea18-70a8-4bf2-8787-b2e9ea5d642e.png)

I see a couple of ways doing it:

* The user press CTRL key, while dragging the mouse on the ruler, and instead of  zooming in,
   the squared marked selection just sticks to the ruler.
* Add a knob on the IGV top bar, `mark ruler`, that switches this mode.

We have a lot of tracks, so by creating this marked selection on the ruler, it is possible to keep the position visible, while scrolling down in the igv.

**Comment by jrobinso** [comment]
Yes that makes sense,  we already have this ability but its not interactive with "regions of interest".   So this is defining a region-of-interest interactively.    See this for example, the blue regions are global (all tracks), green ones are track specific.

We do intend to remove the ugly gaps in the region overlays between tracks

https://igv.org/web/release/2.10.1/examples/roi.html

**Comment by scalavision** [comment]
Thanks @jrobinso , I think the ability to interactively select regions of interest would be highly appreciated from our interpreters. We will use the static roi for now.

**Comment by hmgill** [comment]
This would definitely be a very useful feature!

Apologies since this is likely a naive question and seems to be actively worked on:

Will the coordinates of the interactive ROI be represented as a feature array? Something I would be interested in would be extracting the ROI genomic coordinates. 

Thank you

**Comment by jrobinso** [comment]
@hmgill We will note that.   Apologies we haven't gotten to this yet.

**Comment by hmgill** [comment]
No trouble, thanks for looking into it

**Comment by Sammi-Smith** [comment]
My team would also find this feature extremely helpful for our use case.  We currently have a set of ROIs displayed using the [static ROI feature](https://github.com/igvteam/igv.js/wiki/Regions-of-Interest).  We would like for the user to be able to select additional ROIs of their choosing by selecting a section on the ruler.  As @hmgill suggested above, we'd then want to extract the ROI genomic coordinates of that selected region by adding those coordinates to another .bed or .gff3 file.

I envision something similar to what @scalavision suggested, where the user would select a knob/button on the IGV top bar, `mark ruler`, that switches to this mode.  Then they would highlight/select a region on the ruler.  The genomic coordinates of that region would be added to a .bed/.gff3 file and then displayed across all the tracks, perhaps in a different color than any ROIs specified using the static ROI feature.  The user would have the benefit of seeing their custom/selected ROIs displayed alongside the original ROIs (displayed using the static ROI feature) and we would have one file with the coordinates of the original ROIs and another with the coordinates of all the user-selected ROIs.

Thank you for all your team's work on igv.js, it's an amazing tool!  Feel free to comment/reply here if you have any questions about this use case or want to discuss options for how it might be implemented.

**Comment by helgathorv** [comment]
@Sammi-Smith Thanks for the reminder. We had to put this on the back burner for a while, but we are now looking at it again. I expect we'll have something you can try within in a couple of weeks.

**Comment by Sammi-Smith** [comment]
@helgathorv thanks so much for the response!  I'll try to keep an eye on this issue for any updates.

I'm using igv.js along with flask, so once there is something ready to test out, I can update my line of code that grabs igv.js to use the latest version with that interactive ROI feature implemented. This is what I'm using currently:

`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/igv@2.11.0/dist/igv.min.js"></script>`

**Comment by jrobinso** [comment]
Yes you can just update that script url when we have something ready.   This is a bit more complex, BTW, than just enabling adding the ROI.   Once you can add it there must be a means to remove or edit it.    Also they need to be stored in the session, and someone above asked for the ability to export them.   So its a package of features.   We might not roll them out all at once, first task is just being able to add them.

**Comment by Sammi-Smith** [comment]
Makes sense.  I understand that this will require adding a considerable amount of functionality to fully flesh out the way the user would interact with adding/removing/exporting ROIs.  An incremental rollout sounds like a great approach!
