### ISSUE TITLE
graphType in bedgraph or wiggle are ignored

### ISSUE THREAD

**Issue by dridk** [igvteam/igv.js#1381]
I didn't success to display a track with "point" instead of "bar" by specify the graph type in the file. 
Indeed, Bedgraph and wiggle format can specify the "graphType" from the header data. 

For instance, the following file display points in IGV Desktop Java but bars in IGV.js. 

```test.wig
track type=wiggle_0 graphType=points name="truc" description="une description" visibility=full color=50,150,255 yLineMark=11.76 yLineOnOff=on
variableStep chrom=chr1
[span=windowSize]
2488157 0.4818
2488159 0.4818
2491207 0.537
2494787 0.5251
6257857 0.488
7434547 0.4077
```

To display point, I should specify the "graph type" outside the file in the JS track option.

**Comment by jrobinso** [comment]
I'll look into it, I'm traveling until Tuesday.

**Comment by jrobinso** [comment]
BTW, what is this line supposed to do?

```
[span=windowSize]
```

**Comment by dridk** [comment]
A mistake, I guess... I copy paste from an example

**Comment by jrobinso** [comment]
This should be fixed now in the master branch.   It will be included in the next release.
