### ISSUE TITLE
Zoom slider not working on Firefox

### ISSUE THREAD

**Issue by GMignerot** [igvteam/igv.js#1382]
Hello,

It seems that the zoom widget's slider doesn't work in Firefox (but does in Chrome)
After messing around a bit, it turns out the `change` event is not triggered, and creating a browser makes other `range` inputs on the page unresponsive as well, even though they worked before.
This can be reproduced in the IGV webapp.

Thanks for your great work !

**Comment by jrobinso** [comment]
Fixed with commit https://github.com/igvteam/igv.js/commit/cd4f361f08d105c48c4d40762a31d281699f77ae
