### ISSUE TITLE
browser.toSVG() now returns promise

### ISSUE THREAD

**Issue by SchwarzMarek** [igvteam/igv.js#1388]
Hello,
the `browser.toSVG()` fucntionality now returns promise instead of rendered SVG. This is an undocumented change, which was introduced in https://github.com/igvteam/igv.js/commit/912a960843e31b96388e7092274e36f60fedd814. 
This functionality change is also not reflected in current documentation https://github.com/igvteam/igv.js/wiki/Browser-API-2.0#tosvg.

I expect, that there are some performance reasons for the change and I do not expect, that it's going to return to previous functionality, however, it broke part of my application as I didn't notice the change since it was not mentioned in change log.

Please add it to the changelog and update the documentation, write if PR is wanted.

**Comment by jrobinso** [comment]
Closed, rendering problem was unrelated (and resolved).
