### ISSUE TITLE
showCenterGuide doesn't work

### ISSUE THREAD

**Issue by thedam** [igvteam/igv.js#1397]
Hey, in my case `showCenterGuide: true `doesn't work; the line doesn't show up and the button "Center Line" is not clicked.

      let config = {
        queryParametersSupported: true,
        genome: "hg19",
        locus: locus,
        showCenterGuide: true,
        showCursorTrackingGuide: true,
        tracks: [...]

I use npm, the package.json contains entry:
`"igv": "^2.10.1"`

Cheers

**Comment by turner** [comment]
Fixed with commit 6639a9e2

**Comment by jrobinso** [comment]
@thedam Apologies, an inadvertent change on our part.  The fix will be rolled out in 2.10.2 early next week.
