### ISSUE TITLE
browser.zoomIn(), browser.zoomOut() gone?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1400]
I just installed https://cdn.jsdelivr.net/npm/igv@2.10.1/dist/igv.min.js in igvR, discovering (I believe)  that

```
browser.zoomIn()
browser.zoomOut()
```
are no longer defined, though they still appear in the 2.0 API:
https://github.com/igvteam/igv.js/wiki/Browser-API-2.0#zoomin

![image](https://user-images.githubusercontent.com/2480712/137552864-5e9e24cb-6b4e-497e-b037-e42176bff8cb.png)

where ```igvBrowser``` is my global variable, more typically named (as in the API example) ```browser```

Any suggestions?

**Comment by turner** [comment]
Fixed with commit b7a6285e
