### ISSUE TITLE
spliceJunction track - popup and appearance issues

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#1406]
In the current version, clicking on a splice junction shows an empty popup without any metadata fields:

![image](https://user-images.githubusercontent.com/6240170/138457547-82f51baf-2055-41e6-9432-aa3da68d9241.png)

Reverting to Aug. 23 (81ee2624f531c5ccc641439d2189d8fae2069cf0) fixes popups :

![image](https://user-images.githubusercontent.com/6240170/138457935-743cf501-9d05-4f31-8863-0bac3c0c9ae6.png)

Also, the current version has a worse font and splice junction curve appearance compared to the previous version in my opinion. 

This is the same junction in the new version:
![image](https://user-images.githubusercontent.com/6240170/138458253-fe527a47-67cc-4410-9f0a-a6978fecc1fd.png)

vs. the old version:

![image](https://user-images.githubusercontent.com/6240170/138458322-18876ad3-213b-4416-b526-bdbd16467585.png)

The new junction label is bold by default, and the junction curve is more pixelated.

**Comment by jrobinso** [comment]
Fix is released in 2.10.4
