### ISSUE TITLE
Highlight samples in gcnv bed on click instead of specifying in file

### ISSUE THREAD

**Issue by jethror1** [igvteam/igv.js#1411]
It would be great if when loading bed files of copy ratios from gcnv if the highlighting on samples could be done 'on click' instead of having to specify these either in loading config or written into the first line of the bed file.

At the moment I know it is possible to add the following:

`track  type=gcnv height=500 highlight=sample-X12345;red\n`

![image](https://user-images.githubusercontent.com/45037268/139098940-22224b06-ccfd-4fd9-8df9-0960579cc0ac.png)

But when wanting to load these bed files into any instance of igv.js/igv-webapp this isn't convenient as the sample(s) to highlight have to be determined when creating the bed file.

Also, would it be possible to get better docs on the use of gcnv, I only knew about this from my internship at the Broad and using tgg-viewer, and it would be really helpful for sharing this wider as it is very useful for cnv visualisation.

Thanks!

**Comment by jethror1** [comment]
@bw2 has any decision been made on this / rough idea when it would happen? No worries if not, just wanting to know if I should try implement something on our side in the mean time

**Comment by bw2** [comment]
@jethror1 I don't have the bandwidth to implement this, so defer to you and Jim on next steps.

**Comment by jethror1** [comment]
I'd be happy to work on implementing it if I can find the time and you're happy with others contributing?

If so @bw2 could you point me to gcnv related functions and what you'd like / suggest to do for it.

**Comment by jrobinso** [comment]
I'm happy to accept pull requests, but please keep them as focused as possible and change as little as possible, this includes things like file formatting,  to help with the code review.   Occasionally I get a PR that does something + lots of other things that seemed like improvements, these are impossible to accept.   However most PRs are accepted, the gCNV track itself is a contribution from @bw2.

**Comment by jethror1** [comment]
I've taken a look at adding to the gCNV track to add highlight on click. I've add an option to the track config to be named `clickToHighlight` that accepts either a colour or a keyword `any`. If set to `any`, a random colour will be chosen on each click for the line. If a line that has been coloured is clicked again it will remove the highlight colour.

With `clickToHighlight=red` set: 

![gcnv_igv_red](https://user-images.githubusercontent.com/45037268/142782979-80f6437c-a48a-435e-9a18-76170969ae13.gif)

With `clickToHighlight=any` set:

![gcnv_igv_random](https://user-images.githubusercontent.com/45037268/142782983-0ee45a7b-d5e1-434f-b3a4-c3c891200091.gif)

This has only added ~20 lines to the gCNV track, so hopefully not too much change.

The only thing I think could be better for this specific use case is having the labels appear on hover as oppose to click, so as to know what the sample line is below clicking and highlighting.

Is tooltip displaying on hover already implemented in igv.js, and would it be possible / appropriate to implement here?

Hope this seems okay with you both

**Comment by jrobinso** [comment]
Very nice!  I will defer to @bw2 for comment as he is really the creator and primary user, AFAIK, of this track.    Could you prepare a PR to review?

WRT hove we don't support it currently, it would mean (I think) tracking mouse movement continuously and updating the hover text associated with the DOM element.   If there is an option to catch an event just before the tooltip is raised that would make implementation easy, but I don't think there is.    In any case we don't support it now,  I don't really have time to look into it currently.

**Comment by bw2** [comment]
I agree, the demo looks great. I'm doubt hover could be implemented without bogging down the UI since 
https://github.com/igvteam/igv.js/blob/master/js/gcnv/gcnvTrack.js#L263-L279
would need to run every time the mouse moves.

**Comment by jethror1** [comment]
No worries, labels on hover is only a nice to have, might take a look at it at some point if I have the time / if it is requested.

I've now opened a PR for you to take a look
