### ISSUE TITLE
using browser.search() from an html button error

### ISSUE THREAD

**Issue by asthara10** [igvteam/igv.js#1418]
Hi all,

I am trying to link a table in html with the genome browser, so that a user can click on a button from a list of positions and the genome browser reloads to that position.

I am using the function browser.search() but an error appears:
```
VM14177 :89 Uncaught TypeError: Cannot read properties of undefined (reading 'search')
    at HTMLAnchorElement.onclick
```

My html code looks like this, I tried both with a link or a button, but I get the same error.
```
<a href='#' onclick='igv.browser.search("chr1:0-100");'>chr1:0-100</a>
<button class='editbtn' value='chr2:200-400' onclick='igv.browser.search(this.value);'>chr2:200-400</button>
<button class='editbtn' onclick='igv.browser.search("chr2:200-400");'>chr2:200-400</button>
```

Any help would be appreciated. Thank you!

Júlia

**Comment by asthara10** [comment]
I am using v.2.10.4
`<script src="https://cdn.jsdelivr.net/npm/igv@2.10.4/dist/igv.min.js"></script>`

Probably the problem is that I haven't set the "igv.browser". Could you show me how to do it?

I create the browser with the javascript genome-browser.js
```
var position = "3:0-100";

document.addEventListener("DOMContentLoaded", function() {
    var options =
        {
            reference:
                {
                    genome: "hg38",
                },
            locus: position,
            tracks:
                [
                    {
                        type: 'alignment',
                        format: 'bam',
                        url: 'Output/MAPPED/201212_subset_filtered.sorted.bam',
                        indexURL: 'Output/MAPPED/201212_subset_filtered.sorted.bam.bai',
                        name: 'chr12:24551636-24552559',
                        height: 600
                    }
                ]
        };

    var igvDiv = document.getElementById("igvDiv");

    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
            console.log("Created IGV browser");
        })
});
```
And inside the html:
```
//I add the div
<div id="igvDiv" style="padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray"></div>

// And call the js script
<script type"text/javascript" src="genome-browser.js"></script>
```

**Comment by jrobinso** [comment]
As I said before you are referencing the global "igv.browser" in your button action, but that global does not exist.  You must be copying some really old example,  it would be helpful if you could tell us where you got the reference to using the global "igv.browser" from, did you copy an example from somewhere?

Probably the best way to do this is attach your click handler function to "browser" from within the function passed to the "igv.createBrowser" promise, i.e. the function that logs "Created IGV browser".   An alternative would be to define the global from within that function, like this
```
    igv.browser = browser
```

**Comment by asthara10** [comment]
I tried to adapt it from the example [loadTrack](https://github.com/igvteam/igv.js/blob/master/examples/loadTracks.html).

**Comment by asthara10** [comment]
Now I see that they use the form that you suggested by defining the global "igv.browser".
Thank you!
