### ISSUE TITLE
Clicking outside track settings dialog doesn't close the dialog

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#142]
![image](https://cloud.githubusercontent.com/assets/6240170/9488360/802959a0-4ba7-11e5-9193-768ebdbcc166.png)

It would be great if clicking outside closed the dialog.

**Comment by jrobinso** [comment]
The behavior is the same for info dialogs and menus.  Clicking on another IGV component should dismiss both windows in the same manner.   Clicking outside an IGV component,  e.g. elsewhere on the web page does nothing.    This is maybe not idea, perhaps we could get those events.

On a related issue,  we pushed a fix for the "skinny menu" as shown in your screenshot,   the menu width should be wide enough for each item without wrapping.

**Comment by bw2** [comment]
Got it. One of the users of our alpha brought up dialog dismiss, but I don't think it's a major issue.  
I see the skinny menu fix - thanks!

**Comment by jrobinso** [comment]
I'll leave this open to see if we can catch mouse events for the whole document,  it will be hard and seem a little bit arbitrary for users to have to click within the invisible igv div.
