### ISSUE TITLE
Minor bug : Wrong last sequence in the overview

### ISSUE THREAD

**Issue by GMignerot** [igvteam/igv.js#1423]
Hello,
When clicking the last sequence displayed on the "all" overview, the last sequence in the genome is opened, that is often not the one that was displayed.
For example, with the hg18 genome, clicking on the Y chromosome opens the chrM sequence (that was not displayed, probably because of its small size), and the Y chromosome is not accessible from the overview
![image](https://user-images.githubusercontent.com/71443252/141796351-020032d5-672b-409e-b18f-ff792ed4f71c.png)
![image](https://user-images.githubusercontent.com/71443252/141796424-6c59a095-e247-4b98-8426-0fc5f09d0a21.png)
This can be reproduced in the IGV webapp.

Thanks a lot !

**Comment by jrobinso** [comment]
It certainly does, thanks for the report.

**Comment by turner** [comment]
Candidate for fix commit cc697c0
