### ISSUE TITLE
How to refresh the displays when the locus changed?

### ISSUE THREAD

**Issue by ShifaSZ** [igvteam/igv.js#1425]
We need to allow users to switch the displaying scope between variant wide and gene wide in the embedded IGV on [seqr](https://seqr.broadinstitute.org/). I can't find any [`Browser API`](https://github.com/igvteam/igv.js/wiki/Browser-API-2.0) which can refresh the displays after the locus parameter of the `igv.browser` is changed.

We could remove the old `igv.browser` and create a new one with the updated locus. I'm not sure if there is a better way to do that.

**Comment by jrobinso** [comment]
@ShifaSZ I'm having difficulty understanding you.    When the locus is changed the igv.js views automatically repaint.  Or perhaps you mean something else?  If you want a method to force igv.js repaints I can provide one but this shouldn't be necessary, so I want to understand first.

I also don't know that "variant wide" and "gene wide" means in this context, are these SEQR concepts?

**Comment by ShifaSZ** [comment]
Usually, a variant has a few base pairs while the gene has hundreds or thousands of them. The seqr users may want to see a view for either a variant or a gene. The start and end locations for the variant and the gene are different.

Maybe you are right, the views automatically repaint when the locus is changed. But I just don't know how to change the locus with the Browser API.

**Comment by jrobinso** [comment]
With the "search" function. https://github.com/igvteam/igv.js/wiki/Browser-API-2.0

**Comment by ShifaSZ** [comment]
The "search" works for me. Thanks, Jim.
