### ISSUE TITLE
Setting track height - is there a way to register a callback for when track(s) finish loading?

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#143]
I need to do some DOM manipulation after the initial set of tracks is done loading, and then once more after I add other tracks using loadTrack(..), but I can't figure out how to detect this.
Also, bam tracks currently resize to show all reads when loading is finished. I want to also use this callback to set bam track height to a fixed value (unless there's away to prevent the auto-height-adjustment in the 1st place).

**Comment by jrobinso** [comment]
You can set a maximum track height with  "maxHeight"  (see below).   Alternatively you can explicitly set a height and turn autoHeight off with this combo.  

height: 200,
 autoHeight: false,

{
                                sourceType: 'ga4gh',
                                type: 'bam',
                                url: 'https://www.googleapis.com/genomics/v1beta2',
                                readGroupSetIds: 'CMvnhpKTFhCjz9_25e_lCw',
                                maxHeight: 200,
                                name: 'Ga4gh alignments'}

 I will look into registering a callback.   However, indexed tracks are never "done loading",  loads can be triggered by zooming and panning.

**Comment by bw2** [comment]
Strangely, when I set either height + autoHeight,  or just the maxHeight, the track starts out the expected height and loads nicely, but as soon as I try to scroll it, the data disappears, and no scroll bar appears:
Before scroll:

![image](https://cloud.githubusercontent.com/assets/6240170/9539315/18a07ffc-4d1e-11e5-9416-2d72d06399ad.png)

after attempt to scroll:

![image](https://cloud.githubusercontent.com/assets/6240170/9539319/27c20a28-4d1e-11e5-8e20-70f46d9b6a46.png)

after switching to color by read strand, and only after trying to scroll again, the reads get displayed again:

![image](https://cloud.githubusercontent.com/assets/6240170/9539347/3e608d36-4d1e-11e5-93e7-471a4ea26d4a.png)

This all happens without javascript errors or any trips to the server.

**Comment by jrobinso** [comment]
Oh boy.   I'll look at it, might be this weekend before I get to it.   Looks like some image cache problem but I need to look.

**Comment by bw2** [comment]
thanks.. not sure if it's easy to reproduce.. let me know if I can test different scenarios.

**Comment by bw2** [comment]
Just realized this was related to #64, #66, #77
