### ISSUE TITLE
The search function doesn't render the same ending locus

### ISSUE THREAD

**Issue by SimonLi5601** [igvteam/igv.js#1437]
We use the search function to navigate the variant locus, however, it doesn't seems to return the exact same locus as we passed to it. For example, we have a variant ch17:42329643 (hg38) , we would like to display a region +- 100bp based on the variant, 201bp in total, which the range is ch17:42329543-42329743. We print out the locus right before we call the search API below. this.browser.search(locus)

However, after IGV is rendered, the end locus is shifted a little bit (+37bp) more than we want. Different variant seems to shift the same, but not always. It might not a very critical issue, but I was wondering is that expected? Also after we add more tracks, e.g RNA splice junction, it shifts the end locus to a different base bp. Do you see if anything might be wrong?

![Screen Shot 2021-12-08 at 1 26 42 PM](https://user-images.githubusercontent.com/18488136/145275528-fb200031-b20d-4679-b85d-56761f7f2a8b.png)

**Comment by jrobinso** [comment]
What version of igv.js are you using?

**Comment by SimonLi5601** [comment]
> 

I am using 2.10.1

**Comment by SimonLi5601** [comment]
Actually the issue happens in the browser creation. Please see my attached files for properties we passed and the browser returned. The locus has been changed
[properties.txt](https://github.com/igvteam/igv.js/files/7686383/properties.txt)
[Returned_browser.txt](https://github.com/igvteam/igv.js/files/7686384/Returned_browser.txt)

**Comment by jrobinso** [comment]
@SimonLi5601 that's an important detail because I could not reproduce it post creation.   You also mentioned it changed when you "added more tracks" but I can't reproduce that either.    I can see how there might be issues with the initial locus as the exact end size of the components might not be known when the locus is set.  That's still a bug, which we will address, but is a different bug than locus changing after the igv dom is created.

**Comment by SimonLi5601** [comment]
Hi there, thanks for you attention. Another feedback,  I realized when we resize the browser, the initial end locus will change as well. That could be the reason. Is there any option we can specify the static size of canvas or browser? I can't seem to track down how it resize after the browser is created.

**Comment by jrobinso** [comment]
@SimonLi5601 No there is no option to fix the size, if the user resizes the browser then locus can change.

**Comment by SimonLi5601** [comment]
We figured out the IGV container size is affected by a neighbor element which might cause the resize of the locus. We need to set a relative static width of container. Thanks for you attention.
