### ISSUE TITLE
Center line is not at the center anymore in v2.10

### ISSUE THREAD

**Issue by marhabaie** [igvteam/igv.js#1438]
I have been using IGV within another div which has a set width and it has offset from the left side. The center line was shown correctly in v2.9 but the in v2.10 it is way off to the right. It is most likely from miscalculating the ViewportWidth. I also noticed that the div with "igv-column-container" class is not bounded within the "igv-container" div which might be contributory.

**Comment by jrobinso** [comment]
Fixed with commit 27c56315c1b49635b88e05b5674525e23152e7f7

**Comment by marhabaie** [comment]
Hey Jim, thank you for fixing the bug. When do you plan to release v2.10.5?

**Comment by jrobinso** [comment]
@marhabaie Next week, maybe towards the end of the week.
