### ISSUE TITLE
support for different browsers (firefox, IE)?

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#144]
Does igv.js support Firefox and IE (latest versions)?
I have a prototype which loads all data as expected in Chrome, but not in Firefox, IE, or Safari. 
Specifically, in Firefox, IE and safari, the .bed tracks do load, but  the .bam tracks just show a spinner and then after some seconds the spinner goes away but the tracks remain blank:

![image](https://cloud.githubusercontent.com/assets/6240170/9953372/28d94bb0-5dae-11e5-988b-cc448a1d0460.png)

Firefox doesn't show any javascript errors in the console when this happens.

The code I'm using to init IGV is:

```

	  <!-- jQuery and jQuery UI -->
	  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	  <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css"/> <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

	  <!-- Google Fonts and Font awesome -->
	  <link rel="stylesheet" type="text/css" href='//fonts.googleapis.com/css?family=PT+Sans:400,700'> <link rel="stylesheet" type="text/css" href='//fonts.googleapis.com/css?family=Open+Sans'>
	  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

	  <!-- Bootstrap JS-->
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.22.2/js/jquery.tablesorter.js"></script>

	  <!-- igv.js -->
	  <link rel="stylesheet" type="text/css" href="http://igv.org/web/beta/igv-beta.css">
	  <script type="text/javascript" src="http://igv.org/web/beta/igv-beta.min.js"></script>

	  <script type="text/javascript">

            var tracks = [];
	    tracks.push({ url: '/static/read_viz/gencode.v19.sorted.bed', name: "gencode v19" });
	    tracks.push({ type: 'bam', indexed: true, url: '/static/read_viz/80/5880/chr22-46615880-T-C_het0.bam', name: 'het #1'});

            var locus = '22:46615730-46616030';
	    var options = {
               showCommandBar: true,
	       genome: 'hg19', 
               locus: locus,
    	       showKaryo: false,
	       tracks: tracks,
            };

            igv.createBrowser(  $("#igv-container")[0],  options);

```

**Comment by jrobinso** [comment]
Hi,

It should work on all up-to-date browsers, although we don't test on 
IE.  I will try to reproduce the problem.

Jim

**Comment by bw2** [comment]
Thanks Jim, I forgot to test out http://igv.org/web/examples/ga4gh.html 
When I look at that, it does work in Firefox and IE, so it's looking like some issue with my code snippet. I'll see if I can debug further.

**Comment by jrobinso** [comment]
It could also be something in your data that is triggering a bug we don't see otherwise.   If you can create a test case with small data files we can try that.  You can email them to my broad address, or point me to them.
