### ISSUE TITLE
Alignement strangely changing when scrolling horizontally

### ISSUE THREAD

**Issue by idecarva** [igvteam/igv.js#1440]
Hello,

I am encontering problems when I display alignments of a BAM file. When I scroll a bit horizontally, alignements are changing and I don't know if it's a normal behavior.

For example I can be at position chr1:36,931,684-36,931,765 and I scroll horizontally to the right to the position chr1:36,931,793-36,931,874 and the alignements displayed on the left are not the same that they were. Even if I scroll back to the left it doesn't display what I saw previously.

Thanks for the amazing tool!

**Comment by jrobinso** [comment]
If you scroll far enough for the alignments to redraw then it is normal for them to be rearranged vertically,  the placement of alignments on a "row" is arbitrary and will vary whenever it is redrawn.
