### ISSUE TITLE
Null pointer exception in CursorGuide

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#1446]
When the mouse is moved over the "Gear" icon, or probably anywhere out of the track view container, the following is printed to the console

<img width="957" alt="Screen Shot 2021-12-29 at 9 40 34 AM" src="https://user-images.githubusercontent.com/933148/147689280-672dec0b-a36f-4ca2-b6b0-a56b926d7bb6.png">

**Comment by turner** [comment]
I can't reproduce this one. Do you have a session I can try?

**Comment by jrobinso** [comment]
I can't either now, if I reproduce it I'll re-open.
