### ISSUE TITLE
Downsample whole genome features to a default max count

### ISSUE THREAD

**Issue by cheehongsg** [igvteam/igv.js#1448]
@jrobinso : Thanks for addressing the usability and resource requirement by performing reservoir sampling for whole genome feature set.

While reviewing the code for merging, I note the implicit uniform distribution assumption which works for features with equal probability.

For features that are weighted, e.g. interaction score, peak score, the weighted reservoir sampling will likely capture the trends that user most expect.

There is also another unexpected effect we observed. We no longer can assume that the highest arc in the whole genome view is the highest in the dataset.

My apology for these oversights.

**Comment by jrobinso** [comment]
RE the max, we can easily insure that the max (and min) scores are kept, when there are scores (this is not a required field).   RE weighting, its not clear to me how to weight features generally.    Scores in bedPE files are optional,  but when they are present do you have a suggestion for a general weighting function?

**Comment by jrobinso** [comment]
@cheehongsg OK I implemented code to keep the max score feature, but won't merge it until I've merged your PR.   I definitely see what you mean by uniform sampling, which I will record here with screenshots for future reference.  Unfortunately I am going to be away for a week starting Thursday and will have to pick this up when I return.   The screenshots are  (1) downsampling to 10,000,   (2) downsampling to 100,000,  and (3) no downsampling, ~1.2 million arcs, .  Ideally our downsampled picture should look closer to the non-downsample one.   While waiting for a fix you can turn off downsampling by setting. "wgMaxCount: Number.MAX_SAFE_INTEGER" in the configs.   Of course WG view will then be slow.

<img width="1708" alt="Screen Shot 2022-01-04 at 10 01 50 PM" src="https://user-images.githubusercontent.com/933148/148168443-1b054a14-4a61-44c8-8afc-b93cbf036f51.png">

<img width="1714" alt="Screen Shot 2022-01-04 at 10 01 08 PM" src="https://user-images.githubusercontent.com/933148/148168454-925a57dc-a10e-4171-95e0-89b4d6267dcb.png">

<img width="1708" alt="Screen Shot 2022-01-04 at 10 00 05 PM" src="https://user-images.githubusercontent.com/933148/148168464-b7cb25fa-d2a0-4335-80dd-81ec67eaac3d.png">

**Comment by jrobinso** [comment]
OK I experimented with a simple binning scheme, the idea being to divide the vertical axis into bins and keep a representative sample of arcs in each bin.   It seems to work well for this use case (see screenshot).   It needs more work, but I pushed it to a branch if you want to have a look. (branch binned_WG_sampling)

<img width="1700" alt="Screen Shot 2022-01-05 at 12 29 45 AM" src="https://user-images.githubusercontent.com/933148/148185431-8984594b-df49-4726-8c17-11675f659e1a.png">

**Comment by cheehongsg** [comment]
@jrobinso Wow! You are really quick!

The vertical axis binning is brilliant. It looks representative.
I will read the code later and also spin it on our datasets.

Thank you.

**Comment by jrobinso** [comment]
@cheehongsg I have merged this.  I am back now, after unexpected travel, and am concentrating on the IGV desktop release for circular view at the moment.   When that is done  I plan to return to igv.js / web-app for the first circular view enabled release.
