### ISSUE TITLE
For bam tracks, is there a way to only show one read group?

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#145]
I have .bams with multiple read groups, and need to display only one of the read groups in a given IGV.js track. 
Would it be possible to add "read group" as one of the options passed to igv bam track?

**Comment by bw2** [comment]
I was going to try to add this to https://github.com/igvteam/igv.js/blob/master/js/bam/bamTrack.js#L131
but am not seeing where bam tags / read groups are being parsed.

**Comment by jrobinso** [comment]
Yes, excellent idea.   Is it common that you would want to show multiple 
read groups, each in their own track?  We would need to do this 
intelligenly to avoid re-reading the bam for each track.

I'm traveling to ASHG this week,  there might be some delay before 
implementation.   Add another comment to this issue to ping me if its 
still open the end of next week.

Jim

**Comment by jrobinso** [comment]
Look at the function    igv.BamAlignment.prototype.tags   in 
bamAlignment.js.   The tags are lazily decoded,  but if you call this 
function on an alignment it should return an object representing the tags.

Jim

**Comment by bw2** [comment]
>  Is it common that you would want to show multiple read groups, each in their own track? 
For the project I'm working on now.. yes  (will send more details shortly). 

> The tags are lazily decoded
Oh thanks! I will take a look.

Even without explicit handling on the client-side, perhaps browser caching of the identical requests will make this work decently fast.

**Comment by jrobinso** [comment]
Possibly, although browser caching with range-byte requests does not 
always work  (e.g. it doesn't work at all on Safari).   In any event 
this is a detail we can return to if its a common use case.

**Comment by jrobinso** [comment]
Proposal:  add this to the "filter" object (see table 4b):  https://github.com/igvteam/igv.js/wiki/Tracks

**Comment by bw2** [comment]
The ExAC/gnomAD browser currently monkey-patches an older version of IGV.js to make it readgroup-aware. 

(https://github.com/macarthur-lab/gnomad_browser/blob/07d003bc8edf176e7bceea2ee66846070a9ccd11/templates/variant.html#L784)

We'd like to upgrade to the latest IGV.js, and it'd be great if this functionality existed natively in IGV.js.

**Comment by jrobinso** [comment]
I will make it so.     The latest version is http://igv.org/web/release/2.0.0-beta3/.    Note the updated doc for 2.0 in the wiki.   Specifically,  there is only a single javascript include now  (igv.js or igv.min.js),  no css,  no font-awesome,   just the single include.    There will be a beta4 next week and a 2.0 final release by the end of the month.

**Comment by jrobinso** [comment]
We discussed this earlier but it completely fell through the tracks.
 Let's start over, could you specify here all your use cases?   Filter all
but a specified read group,  a list of groups,  separate track for each
read group,  whatever....   Thanks.

**Comment by bw2** [comment]
`Fell through the tracks` 👍 

What we'd need is a new 'readgroup' config setting when creating bam tracks, so we could do:

```
tracks.push({
                                type: 'bam',
                                url: '/some/dir/file.bam',
                                readgroup: 'some-readgroup-string1',
                                name: 'track1',
                                indexed: true,
                                alignmentShading: 'strand',
                                height: 300,
                                minHeight: 300,
                                autoHeight: false,
});

tracks.push({
                                type: 'bam',
                                url: '/some/dir/file.bam',
                                readgroup: 'some-readgroup2',
                                name: 'track2',
                                indexed: true,
                                alignmentShading: 'strand',
});

```
where track1 would only show file.bam reads that have RG=='some-readgroup-string1' and track2 would only show reads (potentially from the same bam file) that have RG=='some-readgroup2'.

**Comment by bw2** [comment]
We're currently doing this via
https://github.com/macarthur-lab/gnomad_browser/blob/07d003bc8edf176e7bceea2ee66846070a9ccd11/templates/variant.html#L814

**Comment by jrobinso** [comment]
I can easily support this in a wasteful way,  where the same alignments are
read for each track.   I guess that's what you are doing now,  if it's
adequate we can go with that and optimize later.

**Comment by bw2** [comment]
awesome! That should be good enough - especially with various caches along the way.

**Comment by jrobinso** [comment]
OK,  I'll do it soon.   BTW,  I'll be in Cambridge most of June,  coming
into the Broad frequently.

**Comment by jrobinso** [comment]
Fixed.  There are 2 ways to set this (see below), the second method takes an array of readgroups.  The first added for convenience to match what you already have. 

You can test from this distribution:  http://igv.org/web/test/dist/.   Note you should only include the igv javascript file,  no css or any other dependency (i.e. there are no other dependencies).  

```javascript
readgroup: 'SRR360772',
```

```javascript
filter: {
   readgroups: ['SRR360772', 'SRR360760']
}
