### ISSUE TITLE
Uncaught TypeError for isPaired

### ISSUE THREAD

**Issue by mceike** [igvteam/igv.js#1450]
When viewing alignments with the "View as pairs" option selected, right-clicking in-between actual reads produces an error. This has no discernable functional effect, but in our embedded version the UI throws an error.  This is devtools for the [VCF/CRAM example](https://igv.org/web/release/2.10.5/examples/cram-vcf.html): 

![Uncaught_TypeError_isPaired](https://user-images.githubusercontent.com/2444948/150100847-fe6a392b-c3b7-47e7-99bc-e700568e3536.png)

**Comment by scalavision** [comment]
It seems related to this check returning `undefined`:

https://github.com/igvteam/igv.js/blob/73d88214b3f204e3c7b971ecb42386ce37120257/js/bam/pairedAlignment.js#L91

called from here:

https://github.com/igvteam/igv.js/blob/73d88214b3f204e3c7b971ecb42386ce37120257/js/bam/bamTrack.js#L1185

**Comment by jrobinso** [comment]
Thanks for the report,  this should be fixed in master and will be in the next release.
