### ISSUE TITLE
Colour different segments of a BED track

### ISSUE THREAD

**Issue by maltesemike** [igvteam/igv.js#1453]
I have a BED track loaded into IGV defining a series of chromatin states (1-12). Once loaded, IGV colours these with its own set palette. Is there a way for me to individually colour the different states as I see fit? Changing the track colour just changes all the segments to one colour...

**Comment by jrobinso** [comment]
@maltesemike If you are seeing different colors they are baked into the BED records, specifically column 9,  IGV does not assign colors to bed file features.
