### ISSUE TITLE
rejections when loading tracks: this.$spinner undefined / this.track undefined

### ISSUE THREAD

**Issue by f-krull** [igvteam/igv.js#1454]
When loading tracks, at least two rejections seem to be triggered from async code. 

Some extra checks as shown here seem to solve the problem:
https://github.com/igvteam/igv.js/compare/master...ousamg:spinner-undefined?expand=1

Can we fix this upstream? I'm happy to provide more info or create a PR.

**Comment by f-krull** [comment]
Without knowing the implementation details, maybe the `this.track` undefined problem can be solved by moving `if (this.disposed) return` further up? If that's a solution too it would be cleaner of course. 

https://github.com/igvteam/igv.js/blob/9de9415a32348d461aa5511e9514ddb153341f8d/js/trackView.js#L417

**Comment by jrobinso** [comment]
Could you create a pull request?  Also, a reproducible test case with some instructions would be helpful.

**Comment by jrobinso** [comment]
I implemented both fixes.  Do you see this error when removing tracks in that are in the process of loading data?

**Comment by f-krull** [comment]
Yes, you are right. I just checked. We are removing the default refgene track on startup. 

Here is a test setup
https://github.com/ousamg/igv.js/commit/254732b60475f2eca38a6670a3c69a7c99f4d563

It does not reproduce the exact same error though (maybe it's because of the nature of the async code).


![Selection_525](https://user-images.githubusercontent.com/11461352/151963705-125d1755-92f3-4847-babc-932e90c786ed.png)

**Comment by jrobinso** [comment]
Rather than remove the default track why not just define a reference object without it?

**Comment by f-krull** [comment]
Yes, it's a case of RTFM. I wasn't aware that "Ref Genes" was loaded as a default track until you asked: 

> Do you see this error when removing tracks in that are in the process of loading data?

I had some wrapper code around igv.js that keeps the tracks in the igvjs-brower in sync with an external list - and thus removes all tracks that are not part of that list. 

Thanks for your help!
