### ISSUE TITLE
Query regarding track labels

### ISSUE THREAD

**Issue by namratasp20** [igvteam/igv.js#1459]
Hi Team,

The track label name provided using "name : " appears on the track, i.e it overlaps with the track information. (even after zooming in, the content of track behind the label remains hidden).

Is there a way to display the labels above or below the track ? OR specify the co-ordinates where we would want the label to appear ?

Thanks,
Namrata

**Comment by jrobinso** [comment]
No, but you can toggle the labels off and on.
<img width="266" alt="Screen Shot 2022-02-12 at 8 12 51 AM" src="https://user-images.githubusercontent.com/933148/153719013-8f990012-c520-44cd-940b-2294e6b486da.png">
