### ISSUE TITLE
Color coding to flag anomalous insert sizes

### ISSUE THREAD

**Issue by SimonLi5601** [igvteam/igv.js#1462]
Hi Team, in the IGV desktop version, there is a feature to flag the insert size if it is larger than expected. Is this feature available in IGV JS version? I don't seem to find the exact same feature. But in the sample alignment panel, but I did find "color by insert size(TLEN)", but how to define what size of insert will be colored? Is this the same feature as desktop version?

https://software.broadinstitute.org/software/igv/interpreting_insert_size

Thanks!

**Comment by jrobinso** [comment]
It is the same feature as the desktop, the "expected" insert size is
determined from the loaded alignments.  This is the same behavior as the
default desktop implementation.    Its not possible for an end user to set
this length, but it can be set in the track configuration as filed
"maxFragmentLength", see
https://github.com/igvteam/igv.js/wiki/Alignment-Track.   Apologies for the
different nomenclature,  it has varied over time,  but insert size ==
template length == fragment length.

**Comment by SimonLi5601** [comment]
Thanks for your workaround, Jim!  I will keep it open.

**Comment by SimonLi5601** [comment]
@jrobinso  Hi Jim, can I ask you a follow up question? In the document, the default value is said to be Computed (mean fragment length + 3 * standard devation), , but how this actually calculated in a track?  Thanks!
BTW, I guess devation is a typo of derivation.

**Comment by jrobinso** [comment]
That's a misspelling, its "standard deviation", computed from insert sizes of the loaded alignments themselves.   This is how desktop does it also.  If you set an explicit value it will use that value and not compute it.

**Comment by jrobinso** [comment]
@SimonLi5601 Not het.  Did you try setting an explicit value?

**Comment by jrobinso** [comment]
@SimonLi5601 I am changing the calculation to use percentiles rather than median and standard deviation so it will better match IGV desktop.   Specifially 0.5 and 99.5 percentiles.   These will be user settable.   It will never match IGV desktop exactly as sampling is involved, and IGV desktop uses a much larger sample.   

I don't understand the comment "we don't know when the default value will be triggered".   I scrolled up through the discussion.  The calculation is always done, or if you set a fixed value it is always used.

**Comment by jrobinso** [comment]
@SimonLi5601 Also, what type of files are these alignments from?  CRAM, BAM, and are the tracks indexed or not?   It shouldn't matter but it might. 

Actually a test case I could run would be helpful.

**Comment by jrobinso** [comment]
I've pushed some changes that should align igv.js closer to igv desktop.
