### ISSUE TITLE
Request: allow "Cursor Guide" to be enabled in config

### ISSUE THREAD

**Issue by bartgrantham** [igvteam/igv.js#1464]
The mouse-tracking cursor guide ("Cursor Guide" button) is super helpful for tall views, I find myself toggling the button on on page load most of the time.  It'd be great if we could have a `showCursorGuide` option in the config.

**Comment by jrobinso** [comment]
@bartgrantham Sorry for the long delay,  I looked into this and its already there, but the property name is

```
showCursorTrackingGuide: true,
```

I like your name better as it matches the button name, will make it a synonym,  but the above should work.
