### ISSUE TITLE
URL pop-up is a string representation of the javascript code instead of execution result

### ISSUE THREAD

**Issue by creativeyann17** [igvteam/igv.js#1465]
Hello, 

**Steps to reproduce**
1- Go to official documentation: [functional-url]( https://igv.org/web/release/2.10.4/examples/functional-url.html)
2- Bottom of the page click on `CTCF function` (or anything but the string case) to display the pop-up

**Current result:** URL: function () { return "https://www.encodeproject.org/files/ENCFF563PAW/@@download/ENCFF563PAW.bigWig" }

**Expected result:** URL: https://www.encodeproject.org/files/ENCFF563PAW/@@download/ENCFF563PAW.bigWig

**Comment by jrobinso** [comment]
Hi, there is no bug here, and I'm not sure what you are expecting to see.   The popup text is merely explanatory telling you how the URL for the track is encoded, it is simply text manually inserted.   This is just an example, have a look at the source code.

**Comment by creativeyann17** [comment]
Thx for the reply. I still would like to point out what was the logic for me to open that issue.

According to the code itself from https://github.com/igvteam/igv-utils/blob/master/src/igvxhr.js url isn't just a string:

- `throw Error(`url must be either a 'File', 'string', 'function', or 'Promise'.  Actual type: ${urlType}`);` 
- and url is clearly invoked if function/promise by `url = await (typeof url === 'function' ? url() : url);` 

That's misleading because if you give a function/promise I would not expect to see source code of a my function displayed but the result.

Thx for your time,.

**Comment by jrobinso** [comment]
@creativeyann17  I'm not sure you understand the purpose of this demonstration file.   The purpose is to demonstrate how you can use a function or a promise for the "url" field in a bigwig track configuration.   In the most common case url is just a string, however functions and promises can be supplied.  The demonstration has nothing do to with popup text.   Also, you are not seeing source code,  again that is an explanatory note it is just text.

**Comment by jrobinso** [comment]
See the wiki documentation for wig tracks, that might make it clearer.
