### ISSUE TITLE
variant track, locally served (CORS + ranges supported):  "Error accessing resource"

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1468]
Jim and all,

This is likely to be a problem on my end.  I present some of the details here, hoping you can point me in the right direction.  vcf/tbi files from ```"https://s3.amazonaws.com/igv.org.demo``` load fine.   I am pretty sure my local (but publicly visible) vcf/tbi files used to load fine, but I have not run these tests in many months.

One perhaps significant clue is that when I read an indexed vcf file programmatically, from R, on my publicly visible flask/CORS/byte-range web server, the tbi file is always returned, HTTP status always 200.   

When I do this from within a simple igv.js app, modeled after examples/variant-color.html, the tbi gets HTTP status 304, not modified - at least sometimes.

The error messages I see are:

![image](https://user-images.githubusercontent.com/2480712/155615472-a0bfe013-17e1-4a41-862f-db1048216746.png)

igv.js version:  2.10.5
html example from ```examples/variant-colors.html```
```chr22.vcf.gz``` and ```chr22.vcf.gz``` fully readable (tested as a simple link in chrome, and by Bioconductor readVcf)
But failed to load properly , with this error message:
```
Error accessing resource: 
https://igv-data.systemsbiology.net/static/ampad/NIA-1898/chr22.vcf.gz?someRandomSeed=0.6wqm7vkas9w 
Status: 0
```
I have reliable remote, programmatic access to regions in this file, suggesting that the webserver is configured properly. 
You can also get an indication of the adequacy of the flask (CORS + ranges) webserver I use is to click on the above link in your browser, seeing that the download begins - but then you will probably want to cancel because the file is so large - 9G.

The 36k index file downloads quickly:
```
https://igv-data.systemsbiology.net/static/ampad/NIA-1898/chr22.vcf.gz.tbi?someRandomSeed=0.6wqm7vkas9w 
```
The track is configured this way:
```
 {url:     "https://igv-data.systemsbiology.net/static/ampad/NIA-1898/chr22.vcf.gz",
  indexURL: "https://igv-data.systemsbiology.net/static/ampad/NIA-1898/chr22.vcf.gz.tbi",
  name: "AMPAD",
  visibilityWindow: -1
  }
```

**Comment by jrobinso** [comment]
Downloading a file from the browser address bar doesn't tell you anything about CORS setup, CORS only applies to script (javascript) access.   CORS issues are very hard to debug because the browser does not let javascript or any tools even see the error.

Chrome network tools weren't helpful, however from Safari I see the following response headers.   The access-control-allow-origin header is set, but others are note.   Here's what I see

```
HTTP/1.1 206 PARTIAL CONTENT
Content-Type: text/vcard; charset=utf-8
Access-Control-Allow-Origin: http://localhost:63342
Last-Modified: Sat, 17 Jul 2021 01:19:35 GMT
Content-Disposition: inline; filename=chr22.vcf.gz
Content-Encoding: gzip
Cache-Control: no-cache
Date: Fri, 25 Feb 2022 08:24:47 GMT
Content-Length: 9348899
Connection: keep-alive
Accept-Ranges: bytes
Vary: Origin
Content-Range: bytes 0-9348898/9630339397
Server: nginx
```

From the [doc](https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements)  you also need to set several other headers.   This is likely the issue.   Here is how you might set them for an Apache server.

```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods: "GET,POST,PUT,OPTIONS"
    Header set Access-Control-Allow-Headers: "RANGE, Cache-control, If-None-Match, Content-Type"
    Header set Access-Control-Expose-Headers: "Content-Length, Content-Range, Content-Type"
</IfModule>
````

**Comment by jrobinso** [comment]
BTW by setting visibility window to -1 you are saying load data for entire chromosomes.   This could be quite a large amount of data to load at once.   That can also cause hard-to-debug issues if you stress the browser too much.

**Comment by paul-shannon** [comment]
Thanks, Jim.   My minimally configured flask webserver, with CORS and byte ranges, still serves vcf files fine to safari.   So I imagine that chrome has tightened its CORS requirements, maybe at the pre-flight stage.  

Your suggestions about other headers to set is very helpful.   I will figure out how to do that with flask and update this thread once I get it right.   (Maybe others will find flask useful for serving files to igv.js once the bugs are worked out.)

**Comment by jrobinso** [comment]
That's interesting about Safari,  but Safari was the only browser that would even show me the response headers for these requests.  Chrome would not, maybe because "Access-Control-Expose-Headers" is not set.   You can avoid CORS altogether if you can serve your igv.js page from the same Flask server you are serving the data from.

**Comment by paul-shannon** [comment]
Hi Jim,  After spending more than a few hours trying to get my flask webserver's CORS configuration to match the one you provided, so that I could serve genomes and tracks from a host my collaborators could use also, I ran into a puzzle.   Now, using igv 2.10.5, I get a CORS error on files YOU host.  That makes no sense - those files and their server always work.

I can only assume this problem is somehow my own, but if you could take a glance at this I'd be grateful.
```
chrome:  99.0.4844.51 (Official Build) (x86_64)
```
minimal igv.js html file:
```
<html>
<head>
    <title>minimal igv.js</title>
    <script src="https://cdn.jsdelivr.net/npm/igv@2.10.5/dist/igv.js"></script>
</head>

<body>

<div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>

<script type="module">
    var options = {
        genome: "hg38",
        locus: "chr7:127,250,755-127,695,107"
        };
    var igvDiv = document.getElementById("igvDiv");
    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
            console.log("Created IGV browser");
        })
</script>
</body>
</html>
```
error from the chrome javascript console:
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/2480712/157487425-771706fa-3ac1-457a-89c0-e70f1caede2a.png">

**Comment by paul-shannon** [comment]
Thanks, Jim.

This bizarre behavior continues, and though it is my problem to solve, I have been unable to.  So let's close this issue.  I will work around it by disabling CORS on some urls when I use chrome.

**Comment by jrobinso** [comment]
Did you try this outside your institution network (e.g. at home)?

**Comment by paul-shannon** [comment]
Hi Jim,  S

Since covid came I work full-time at home, without ready access to another network.  I tried a phone hotspot, but learned nothing.

It’s unsatisfying to leave this unsolved, so my new strategy is to use node.js to explore headers, requests, responses, maybe preflight.

I hope that with the right modules installed, I can see the fine-grained details of what’s broken.

If I figure anything out, I will let you know.  

 - Paul

**Comment by jrobinso** [comment]
Ah yes, as do we all.  I don't know why I imagine everyone else in the world is toiling away at their office.

**Comment by paul-shannon** [comment]
Hi Jim.  Success at last.  I replaced the python flask web server with nginx, configured it for CORS and byte ranges.  Now I can serve custom files to igv.js without trouble.     nginx runs out of a docker container - I'd be glad to provide the docker command and the nginx config file if you think others may be interested.

**Comment by JasonLing95** [comment]
> Hi Jim. Success at last. I replaced the python flask web server with nginx, configured it for CORS and byte ranges. Now I can serve custom files to igv.js without trouble. nginx runs out of a docker container - I'd be glad to provide the docker command and the nginx config file if you think others may be interested.

Hi could you provide the nginx config please, that will be helpful

**Comment by paul-shannon** [comment]
First the docker command, then the nginx configuration.
```
docker run -p 60050:80 \
      -v /data/dockerizedFlask/default.conf:/etc/nginx/conf.d/default.conf:ro \
      -v /data/dockerizedFlask/static/:/usr/share/nginx/html:ro \
      --restart always \
      -d nginx
```
default.conf
```
server {
    listen       80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;                                                                                                                                                              

    location / {
	root   /usr/share/nginx/html;
	index  index.html index.htm;
	# max requests per keepalive connection                                                                                                                                                                     
	keepalive_requests 55000;

	# awesome OPTIONS header                                                                                                                                                                                    
	if ($request_method = 'OPTIONS') {
		add_header "Access-Control-Allow-Origin" $http_origin;
		add_header "Vary" "Origin";
		add_header 'Access-Control-Allow-Credentials' 'true';
		add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,Range,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Acopenept-Ranges,Content-Encoding,Content-R$
		# Tell client that this pre-flight info is valid for 20 days                                                                                                                                        
		add_header 'Access-Control-Max-Age' 1728000;
		add_header 'Content-Type' 'text/plain charset=UTF-8';
		add_header 'Content-Length' 0;
		return 204;
	}
        if ($request_method = 'POST') {
		add_header 'Access-Control-Allow-Origin' '*';
		add_header 'Access-Control-Allow-Credentials' 'true';
		add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,Range,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Acopenept-Ranges,Content-Encoding,Content-R$
		add_header 'Access-Control-Expose-Headers' 'Accept-Ranges,Content-Encoding,Content-Length,Content-Range,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,Date';
	}
        if ($request_method = 'GET') {
		add_header "Access-Control-Allow-Origin" $http_origin;
		add_header "Vary" "Origin";
		add_header 'Access-Control-Allow-Credentials' 'true';
		add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		add_header 'Access-Control-Allow-Headers' 'DNT,Range,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Acopenept-Ranges,Content-Encoding, Content-$
		add_header 'Access-Control-Expose-Headers' 'Accept-Ranges,Content-Encoding,Content-Length,Content-Range,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,Date';
	}
    }

    # redirect server error pages to the static page /50x.html                                                                                                                                                      
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
	root   /usr/share/nginx/html;
    }
}
```
