### ISSUE TITLE
Bed file feature rendering bug for the left most feature that is partially in the viewport

### ISSUE THREAD

**Issue by cheehongsg** [igvteam/igv.js#1474]
content of hg38_bed_test.bed
```
chr1	121605200	124938900	High Signal Region
chr1	125067600	125086000	High Signal Region
chr1	125130200	143562200	High Signal Region
```

Load the bed file to https://igv.org/app/ (IGV-Web app version 1.9.0, igv.js version 2.11.0) on hg38 assembly, and navigate to chr1:124,410,585-125,635,544
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/8243109/158083550-4a3f9ebd-c5bc-45b4-8dee-a6ca919d9fcd.png">

The expected rendering is:
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/8243109/158083567-82a6c37f-be36-4a34-b828-6305d1a0a4e6.png">

Discrepancy stems from the use of Math.max instead of Math.min at
https://github.com/igvteam/igv.js/blob/eca9436ee955792b36d6d8ace6baaada492cfb9b/js/feature/render/renderFeature.js#L81

**Comment by jrobinso** [comment]
Thanks!  Actually I think it should just be ```const width = xRight - xLeft```
