### ISSUE TITLE
dm6 genome: search("chr2L:5,100,877-5,207,002") works, search("Msp300") fails

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1476]
This was first reported by an igvR user.  But since I can reproduce it in the Javascript console - with no R involved - perhaps this is a problem with gene lookup in the drosophila genome dm6?  Or in my understanding of how it should work?
```
igv.version() // '2.10.5'
p1 = igvBrowser.search("chr2L:5,100,877-5,207,002") // this works
p2 = igvBrowser.search("Msp300")  // this fails 
```
![image](https://user-images.githubusercontent.com/2480712/158481949-85fad146-1067-46fd-a51f-a2074c11a63b.png)

**Comment by paul-shannon** [comment]
Any chance this issue could get a little time?   Full apologies if the error is my own...

**Comment by jrobinso** [comment]
This should be fixed, there was an issue with the dm6.json config
