### ISSUE TITLE
Uncaught ReferenceError: longestChr is not defined

### ISSUE THREAD

**Issue by danvk** [igvteam/igv.js#148]
When I set `showKaryo: true`, I get this error:

```
Uncaught ReferenceError: longestChr is not defined
```

coming from this line: https://github.com/igvteam/igv.js/blob/9ecc2dea752f7fdd552a243ce9d31df1ae41f4e3/js/karyo/karyo.js#L183

**Comment by jrobinso** [comment]
Thanks for the report,  will look at it soon.
