### ISSUE TITLE
Option to show popup on hover instead of click

### ISSUE THREAD

**Issue by onursumer** [igvteam/igv.js#1486]
<img width="471" alt="track_popup" src="https://user-images.githubusercontent.com/3604198/162490813-d547bd51-0337-438f-b229-753edd3deeb5.png">

Seems like the only way of showing this popup is to click on a track. Would it be difficult to add an option/flag to show this content on hover instead?

**Comment by jrobinso** [comment]
Not easy, might be possible.  You are hovering over a canvas element, the features are not html elements.

**Comment by jrobinso** [comment]
@onursumer Sorry for the delay.   This looks like it should be possible, I've done a hacky test.  Is it still of interest?

**Comment by jrobinso** [comment]
On further review, we can do simple hover text but no formatting.   The hover text is an html attribute ("title"), and cannot contain any html itself, just an unformatted string.   There are complex solutions but we are not going to get into those, and hover text should probably be kept simple in any event.   So my thought is to have a simplified (optional) form of the popup text for hover display.    This will need defined for each data type,  I'm not sure what you have clicked on in your example.  For copy number we might just display something like. ```sample-name: value```.

**Comment by jrobinso** [comment]
I implemented some simple tooltip text, will be in the next release.   You can customize it to a degree, see https://github.com/igvteam/igv.js/wiki/Hover-text
