### ISSUE TITLE
How to show LOH events using seg-track?

### ISSUE THREAD

**Issue by arpanda** [igvteam/igv.js#1490]
I am trying to show Deletion, Duplication and Loss of heterozygosity(LOH) events for few samples using `seg-track`. But  I could not found any [documentation](https://github.com/igvteam/igv.js/wiki/Seg-Track) to show the LOH events. 

Therefore, is it possible to show LOH events using seg-track? if yes, could you please help. If not, is there any other way to show the events together?

Thanks
Arijit

**Comment by jrobinso** [comment]
I'm not sure I understand the question.  The seg-track will display red for amplification (duplication),  and blue for deletion.  There is no LOH display.   If you want to show events rather than quantitative values perhaps another format would be better.

**Comment by arpanda** [comment]
I woud like to show three events together  Deletion, Duplication and LOH. Looks like seg-track does not have option to show LOH events. As its copy number is 2. 

Could you please suggest a format that can be used to show all three events together.

**Comment by jrobinso** [comment]
No  I cannot, I do not know of any format that supports this.
