### ISSUE TITLE
How to enable Three-frame Translate by default?

### ISSUE THREAD

**Issue by minmarnoo** [igvteam/igv.js#1491]
![Screenshot 2022-04-14 at 3 04 37 PM](https://user-images.githubusercontent.com/86052341/163332119-e8729e79-256e-4f82-8791-bcb5cd1b48c9.png)

**Comment by helgathorv** [comment]
You can only enable it by selecting it from the gear menu.

**Comment by minmarnoo** [comment]
Understood. thanks!

**Comment by jrobinso** [comment]
This is possible now with the just released 2.12.3 version.   Documentation to follow, here is an example.   You need to include an explicit "sequence" track in the tracks collection of the config.   It will probably also work to include it in the tracks collection of the reference, if that is used, but I didn't test that.   The track record will look like this.   The "order" field, a large negative number, effectively pins the track to the top.  

```
                {
                    type: "sequence",
                    order: -9007199254740991,
                    frameTranslate: true
                },
```

Complete example



```
    const config =
        {
            reference: {
                fastaURL: '../../macFas5/macFas5.fa',
                indexURL: '../../macFas5/macFas5.fa.fai'
            },
            loadDefaultGenomes: false,
            locus: 'chr2:32,027,456-32,027,495',
            tracks: [
                {
                    type: "sequence",
                    order: -9007199254740991,
                    frameTranslate: true
                },
            ]
        }
```

**Comment by minmarnoo** [comment]
Thanks @jrobinso, could you explain more about `order` value?

**Comment by jrobinso** [comment]
Its the rank order of the track,  ascending, so a large negative number will pin the track to the top.   This is where we put the sequence by default.
