### ISSUE TITLE
Inaccurate three-frame translation track in recent updates

### ISSUE THREAD

**Issue by vkozareva** [igvteam/igv.js#1493]
I've noticed that since recent updates to the web app, the three-frame translation track appears to be inaccurate and inconsistent between sessions when looking at the same reference genome. 

Here are two screenshots from today (Apr. 13), looking at the SARS-CoV2 reference: 

<img width="1676" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/6119489/163201516-da467d7d-fbfa-48d7-ba39-faf5f35d63f8.png">

<img width="1657" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/6119489/163201646-106af19b-38cc-4f1d-859c-c61da73092b6.png">

These were both viewed in Chrome, and here is the corresponding IGV web app info: IGV-Web app version 1.10.2, igv.js version 2.12.2.

For comparison, this is a screenshot of the same reference from March 30th, again in Chrome: 

![image](https://user-images.githubusercontent.com/6119489/163201993-c01608d4-8dbe-48fe-84ba-6eb4cf13a3bc.png)

Unfortunately, I didn't record the web app version info at the time. The March 30th session shows the correct translation annotation (and matches my local IGV app). 

Not sure what is causing the inconsistency, but in some cases the codons don't even seem to line up with the nucleotides, so perhaps it's a display issue.

**Comment by jrobinso** [comment]
This should be fixed now with igv.js version 2.12.3, and also with the latest igv-webapp (1.10.4) and igv.org/app
