### ISSUE TITLE
Color variants by FILTER

### ISSUE THREAD

**Issue by alimanfoo** [igvteam/igv.js#1501]
I'd like to be able to color variants in a variant track according to the value of the FILTER column in a VCF. Specifically, I'd like to be able to set one color for PASS (e.g., green) and a different color for any kind of failure (e.g., red). 

From the igv.js docs and code I gather this cannot be done using the `colorBy` configuration attribute, because this is used to look up values from the INFO field only. It might be possible using the `color` configuration attribute and passing a javascript function. However, I couldn't see how it would be possible to provide a javascript function as a configuration value when using igv-notebook. 

Any help/suggestions greatly appreciated.

**Comment by jrobinso** [comment]
I transferred this as it was really an igv.js issue.  This is now support with igv.js release 2.12.5, and igv-notebook 0.2.3.  I added an example notebook as well.
