### ISSUE TITLE
how to use cache when loading custom reference?

### ISSUE THREAD

**Issue by DawnEve** [igvteam/igv.js#1508]
It will be very slow when using custom reference, and it will add someRandomSeed=xxx to force reload when refreshing the browser.

So, how to use cache when loading custom reference?

**Comment by DawnEve** [comment]
My code:
```
	var hg19_local={
			"id": "hg19",
			"name": "Human (GRCh37/hg19)",
			"fastaURL": "ref/hg19/hg19.fasta", //?someRandomSeed=0
			"indexURL": "ref/hg19/hg19.fasta.fai",
			"cytobandURL": "ref/hg19/cytoBand.txt",
			"aliasURL": "ref/hg19/hg19_alias.tab",
			"tracks": [
			  {
				"name": "Refseq Genes",
				"format": "refgene",
				"id": "hg19_genes",
				"url": "ref/hg19/ncbiRefSeq.sorted.txt.gz",
				"indexURL": "ref/hg19/ncbiRefSeq.sorted.txt.gz.tbi",
				"visibilityWindow": -1,
				"supportsWholeGenome": false,
				"removable": false,
				"order": 1000000,
				"infoURL": "https://www.ncbi.nlm.nih.gov/gene/?term=$$"
			  }
			],
			"chromosomeOrder": "chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY"
		  }

var options =
	{
...
reference: hg19_local,
...

```

**Comment by jrobinso** [comment]
It should not be slow, the fasta is indexed, if it is slow you have some issue with your server.   See [here](https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements) for server requirements, particularly support for "range" headers.  The seed is necessary for some browsers that do not consider the range header when caching.

**Comment by DawnEve** [comment]
Thanks for your advise. 
My fault to neglect this wiki page.

I used `python3 -m http.server 8888`, which seems not support this header, I may try flask latter.

**Comment by jrobinso** [comment]
This might also work, hasn't been updated since 2016 though. https://pypi.org/project/rangehttpserver/

**Comment by DawnEve** [comment]
This is a good option, though still need `a step modification` after pip installation, in order to support port parameter.

Now, my IGV.js works fine under this `rangehttpserver` , and the local fasta and bam files load in seconds, not minutes.

Thank you again.


---

Here is my note, in case anyone needs it:
```
$ pip3 install rangehttpserver
$ pip3 list | grep -i range
rangehttpserver                   1.2.0
$ python3 -m http.server 8890
# Error: OSError: [Errno 98] Address already in use
#Error, not support range header, can only use default 8000, but the latter is used 
```

Modify this file(whose path can be found among the Error message above) according to the current version on github:  https://github.com/danvk/RangeHTTPServer/blob/master/RangeHTTPServer/__main__.py
```
$ vim python3.7/site-packages/RangeHTTPServer/__main__.py
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('port', action='store',
                    default=8000, type=int,
                    nargs='?', help='Specify alternate port [default: 8000]')

args = parser.parse_args()
SimpleHTTPServer.test(HandlerClass=RangeRequestHandler, port=args.port)
```


Start server, supporting port and range header
```
$ python3 -m RangeHTTPServer 8890
Serving HTTP on 0.0.0.0 port 8890 (http://0.0.0.0:8890/) ...
```

**Comment by jrobinso** [comment]
Nice, thanks for sharing your setup.
