### ISSUE TITLE
Non Indexed file for fastaURL

### ISSUE THREAD

**Issue by asmariyaz23** [igvteam/igv.js#151]
As per current documentation only an indexed fasta file can be served with the fastaURL option, is there a possibility to serve a non-indexed fasta file as well with this configuration? When a bed/bam track is configured indexURL option can be turned off/on depending on the user, if something similar can be implemented for "fastaURL" as well it will be extremely helpful.

**Comment by jrobinso** [comment]
To use, set "indexed: false" for the reference sequence like this

 reference: {
                fastaURL: "http://dn7ywbm9isq8j.cloudfront.net/genomes/seq/ca21/C_albicans_SC5314_A21.fasta",
                indexed: false
            }
