### ISSUE TITLE
Minimum FASTA File Requirements for Visualization

### ISSUE THREAD

**Issue by shen-ui** [igvteam/igv.js#1514]
Hey all,

I've been wrestling with a problem for the last couple days that I can't seem to resolve alone.
There might be a trivial answer I'm not aware of . 

The main question I have is, what is the minimum requirements of a fasta/fai for IGV to create a visualization?
Is there a tag for the fasta contig headers that I'm missing?

What I have so far:
I'm trying to create a basic visualization with IGV and I'm using an API to get genomic data. 
To use IGV, I have parsed the api data to a fasta and fasta.fai both as File type blobs.
I've formed the content of these files just like any fasta file
i.g. (note: remove the .txt at the end of the extension)
[test.fasta.txt](https://github.com/igvteam/igv.js/files/8826207/test.fasta.txt) 
[test.fasta.fai.txt](https://github.com/igvteam/igv.js/files/8826208/test.fasta.fai.txt)

in code, I'm creating two blobs and then casting the blob to a File Type.

    let my_browser: any;
    let fasta = new Blob([fastaData], {type: "text/plain"});
    let fai = new Blob([indexData], {type: "text/plain"});

    // cast blob  to File pseudocode
    fasta = <File>fasta;
    fai = <FIle>fai;

    const options = {
     ...
      reference: {
        fastaURL: fasta,
        indexURL: fai,
      },
      locus: "contig1:10-499",
     ....
    };

    igv.createBrowser(canvas, options).then(function (browser) {
      my_browser = browser;
    });

Although the browser is able to get the blob file, the drop down next to the navigator does not show contigs.
![Screenshot 2022-06-02 134607](https://user-images.githubusercontent.com/47713674/171694264-57433a14-8bda-4b1b-857d-abeaf20c9734.png)
consistently, I run into the error: Cannot set initial Locus.

This leads me to believe I am malforming the fasta/fai for igv to create a visualization. Leading me to question, what are the minimum requirements for Fasta/index files so that igv can read them and create a visualization from them?

**Comment by jrobinso** [comment]
Did you look in the console for errors?  Also, be sure you are using the latest version.

**Comment by jrobinso** [comment]
BTW I don't understand the "cast" comment, javascript is typeless there are no casts.

**Comment by jrobinso** [comment]
If you can zip up a complete working example I will look into it.  Your fasta file looks fine.

**Comment by shen-ui** [comment]
> BTW I don't understand the "cast" comment, javascript is typeless there are no casts.

My mistake, for context I'm using typescript. 
Really what I'm doing is just telling the Blob it is a File. (IGV  says fastaURL and indexURL required the type File.)

**Comment by shen-ui** [comment]
> If you can zip up a complete working example I will look into it. Your fasta file looks fine.

Got it, I'll hack up a live version for you to look at. Really appreciate the help.

**Comment by jrobinso** [comment]
Actually also "name",  here is the actual isFile test

```
function isFile(object) {
    if(!object) {
        return false;
    }
    return typeof object !== 'function' &&
        (object instanceof File ||
            (object.hasOwnProperty("name") && typeof object.slice === 'function' && typeof object.arrayBuffer === 'function'))
}
```

**Comment by jrobinso** [comment]
Blob implements slice and arrayBuffer, so my suggestion would be to wrap a Blob in an object with a "name" property.

**Comment by shen-ui** [comment]
> Blob implements slice and arrayBuffer, so my suggestion would be to wrap a Blob in an object with a "name" property.

I think I may have done so. My example code was a bit sparse. Here what the object looks like on the console
![Screenshot 2022-06-02 141324](https://user-images.githubusercontent.com/47713674/171698566-3142afd2-a469-484e-be6e-a742f30c4674.png)
.

**Comment by jrobinso** [comment]
Actually I think the problem is with your data,  the fai file columns should be tab delimited.

**Comment by shen-ui** [comment]
> Actually I think the problem is with your data, the fai file columns should be tab delimited.

You're right! Thank you so much!

**Comment by jrobinso** [comment]
This works for me

```
    const igvDiv = document.getElementById("igv-div");

    class MockFile {
        constructor(str) {
            this.name = ""
            this.blob = new Blob([str])
        }

        slice(start, end) {
            return this.blob.slice(start, end)
        }

        arrayBuffer() {
            return this.blob.arrayBuffer()
        }
    }

    const fastaData = ">one\n" +
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
        "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
        ">two\n" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n" +
        ">one_seq1\n" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n" +
        ">one_seq2\n" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]n"

    const fastaIndex = "one\t120\t5\t30\t32\n" +
        "two30\t149\t30\t32\n" +
        "one_seq1\t30\t30\t30\t32\n" +
        "one_seq2 30\t90\t30\t32\n"

    const fastaBlob = new MockFile(fastaData)
    const indexBlob = new MockFile(fastaIndex)


    const options =
        {
            reference: {
                fastaURL: fastaBlob,
                indexURL: indexBlob
            }
        }

    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
            console.log("Created IGV browser");
        })

```

**Comment by jrobinso** [comment]
BTW, you don't need an index here, just set indexed: false
```
            reference: {
                fastaURL: fastaBlob,
                indexed: false
            }
```
