### ISSUE TITLE
gwas config example, file not found

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1515]
In the [GWAS Track wiki docs](https://github.com/igvteam/igv.js/wiki/GWAS), as best I can tell, the example's url is no longer working.   I also looked for a working example (type=format="gwas") in ```examples/test/tracks-hg38.html``` but had no luck there either.    If my failure to find a working example is not just my own mistake, could you provide one?

Thank you.
```
{
   type: "gwas",
   format: "gwas",
   name: "GWAS sample",
   url: "https://www.dropbox.com/s/7ex70zwt1o4n8d8/gwas_sample.tsv.gz?dl=0",
   indexed: false,
   columns: {
      chromosome: 12,
      position: 13,
      value: 28
   }
}
```

**Comment by jrobinso** [comment]
Paul try this. https://s3.amazonaws.com/igv.org.demo/gwas_sample.tsv.gz

**Comment by paul-shannon** [comment]
Thanks, Jim.   Having that valid file helped me to establish that there is a small typo to be fixed in the parseFeatures function of the ```GWASParser``` class, version 2.12.6 of igv.js.

I believe  ```this.valueCol``` should be ```this.pvalueCol```:

```
          if (tokens.length === this.columns.length) {
            const chr = tokens[this.chrCol];
            const start = parseInt(tokens[this.posCol]) - 1;
            const end = start + 1;
            const value = Number(tokens[this.valueCol]);  // this.pvalueCol
```

**Comment by jrobinso** [comment]
@paul-shannon Could you elaborate?   I think the typo is might be in the constructor that sets defaults (pvalueCol should be valueCol).   The values might be pValues, or might be something else.   I agree something is wrong somewhere.   The example file (such as the one I pointed you to) display correctly in my eyes.

**Comment by jrobinso** [comment]
OK, yes you are correct there was a typo.  The example files worked unless you tried to explicitly set the columns.   Thanks for the debugging.
