### ISSUE TITLE
Getting errors loading any BAM files

### ISSUE THREAD

**Issue by jorvis** [igvteam/igv.js#1517]
My configuration for a BAM track looks like this:

```
{
                        type: "alignment",
                        format: "bam",
                        name: "A1 IL100038432",
                        url: "./annotation-data/bams/A1.IL100038432.sorted.bam",
                        indexURL: "./annotation-data/bams/A1.IL100038432.sorted.bam.bai"
}
```

And I've verified that the relative paths are correct (they're working with the GFF tracks).  In the apache log I just see a lot of these messages:

```
gzip: stdout: Broken pipe
gzip: stdout: Broken pipe
```

On the front end it's this:

```
trackViewport.js:184 Error accessing resource: ./annotation-data/bams/A1.IL100038432.sorted.bam?someRandomSeed=0.p6g1awg2wbm Status: 0

GET http://myserver/annotation-data/bams/A1.IL100038432.sorted.bam?someRandomSeed=0.p6g1awg2wbm net::ERR_CONTENT_DECODING_FAILED
```

Has anyone seen this?

**Comment by jrobinso** [comment]
See the [data server requirements](https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements), particularly the note on BAM mime types at the bottom.   This is sometimes a problem with apache servers.
