### ISSUE TITLE
Displaying Refseq Genes track at the top on browser creation

### ISSUE THREAD

**Issue by olingerc** [igvteam/igv.js#1518]
How would I have the Genes track be above all other tracks that I load on browser object creation?

**Comment by olingerc** [comment]
Hi @jrobinso . Thanks for the answer. The following worked successfully. The key was the `order` value and separating the refgene track from the reference object.:

```javascript
const options = {
   reference: {
      "id": "hg19",
      "name": "Human (GRCh37/hg19)",
      "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta",
      "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/hg19.fasta.fai",
      "cytobandURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/cytoBand.txt"
   },
   tracks: [
      {
            "name": "Refseq Genes",
            "format": "refgene",
            "url": "https://s3.amazonaws.com/igv.org.genomes/hg19/refGene.txt.gz",
            "indexed": false,
            "removable": false,
            "order": 0
      },
      <restOfMyTracks>
   ]
};
```

**Comment by jrobinso** [comment]
It shouldn't matter if the refgene track is in the "reference" or not, if you found it did that would be something for me to look into.   Order is optional, and if not specified will be in the order listed.   If you want to pin it to the top I would suggest a large negative number.

**Comment by olingerc** [comment]
Indeed, putting the RefSeq track with the reference tracks did the trick as well. Nice :-) I updated my initial answer to reflect this.
