### ISSUE TITLE
Refseq gene names not displayed at all zoom levels

### ISSUE THREAD

**Issue by olingerc** [igvteam/igv.js#1519]
Gene names on the refseq track are only displayed when zooming out, irrespective of track height. Looking at the [draw code](https://github.com/igvteam/igv.js/blob/7bb68de2c7369705cdaa8e7dff3856bc0252ab2a/js/feature/render/renderFeature.js) I tried setting `labelAllFeatures` but I think it is not meant for this purpose.

![image](https://user-images.githubusercontent.com/5046645/173007927-2d9b281a-608f-4df6-955e-733e29c76ced.png)
vs
![image](https://user-images.githubusercontent.com/5046645/173007989-344403d0-ba12-4018-86bd-d630dd5f53ef.png)
for reference in IGV Desktop
![image](https://user-images.githubusercontent.com/5046645/173008278-10a9badd-739f-496b-9950-6c13b1904959.png)

**Comment by bs-shubham-gupta** [comment]
same issue has reappeared in [2.15.12](https://github.com/igvteam/igv.js/releases/tag/v2.15.12) 
and is reproducible in  [3.0.1](https://github.com/igvteam/igv.js/releases/tag/v3.0.1)

**Comment by jrobinso** [comment]
@bs-shubham-gupta I'm not able to reproduce it, can you give me some exact steps?

**Comment by bs-shubham-gupta** [comment]
@jrobinso  I have added a comparison between these versions and IGV Desktop.

IGV 2.15.11 (Gene name reappears when i scroll or change locus)

https://github.com/user-attachments/assets/646575ef-a699-4220-9947-38666b254b35



IGV 3.0.1 (Gene name remains fixed at one postion)

https://github.com/user-attachments/assets/ea8793e1-57f3-4ecc-aec8-fc744ede66e8




IGV Desktop Linux 2.18.2 (Gene name moves with scroll )

https://github.com/user-attachments/assets/9747af82-a659-433c-94a3-bbcb2a49ab5f

**Comment by jrobinso** [comment]
Apologies I interpreted this as a desktop IGV issue although clearly its posted in igv.js.     Thanks for the report.

**Comment by jrobinso** [comment]
This is fixed with v 3.0.4
