### ISSUE TITLE
loadTrack promise returns before track load completes

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1528]
Attached is a gzip file containing only one file, a very small modification of ```dev/wig/groupAutoscale.html```.
All I have added is a button "Load Tracks" which calls a function to load the 3 histone bigwig tracks which, in the original, are loaded at igv browser creation time.  

(This html file reproduces the problem I see in igvShiny.R, where R and htmlwidget code can obscure the debugging process.  I hope that this file - most of it written by the igv team, and with only a few lines of html and javascript - reproduces my problem in a familiar, small context.)
  
When a button click runs this function,  using the latest igv-2.12.6.js, the ```then``` function executes immediately: 
```
  function loadTracks(){
      igv.browser.loadTrack(histone_tracks[0])
          .then(function(newTrack){console.log("Track loaded: " + newTrack.name);});
     }
```
```Track loaded: GM12878 H3K4me3``` appears in the console, and the track does not load.  If I resize chrome manually with my mouse, the track load completes.  Otherwise, no track appears.   This reproduces what I see in igvShiny.R.

Any suggestions? 

[groupAutoscale-button.html.gz](https://github.com/igvteam/igv.js/files/8932770/groupAutoscale-button.html.gz)

**Comment by jrobinso** [comment]
This is a bug, autoscaleGroup tracks do not trigger an update/paint in the loadTracks() function,  updating is delayed until other potential tracks in a list are updated.   When using the loadTracks function directly this never happens.    This bug will be addressed in the next release, in the meantime you can use the following as a workaround.

```browser.loadTrackList([histone_tracks[0]])```

or if you want to load them all

```browser.loadTrackList(histone_tracks)```

**Comment by jrobinso** [comment]
A related problem, if you load a track that is part of an autoscale group, then later load another track that is part of that group, the autoscale won't sync immediately.   That's because the first track you load does not have knowledge of the second load until it is forced to update.   This will be fixed as well, the workaround is to call ```browser.updateViews()``` after every track load that involves an autoscale group.   This will also allow using loadTrack instead of loadTrackList.

**Comment by jrobinso** [comment]
Edit:  the above will work to load the track, but group autoscale still doesn't work until something else forces an update.  Group autoscale was apparently never tested for dynamic track loading (i.e. by calling loadTrack).    So at this point it won't work,  you will need to wait until the next release,  probably by the end of the month or first week of July.

**Comment by jrobinso** [comment]
@paul-shannon I think this is fixed, will be released by the end of next week, maybe earlier.   If you want to try a preview use an igv distribution from this url:  https://igv.org/web/snapshot/dist/
