### ISSUE TITLE
Request: Add feature to igv search input allow tab(\t) delimitated chromosome and loci 

### ISSUE THREAD

**Issue by hotsoupisgood** [igvteam/igv.js#1533]
Hi, I would like to add a feature that would allow for a search to be formatted like so: `chr7\t6010535\t6013193` (normally it just accepts formatting like so: `chr7:6010535-6013193`). 
What do you think?

**Comment by jrobinso** [comment]
You didn't describe a use case for this, I assume its to copy/paste from other programs such as spreadsheets.   This is now supported,  however note you cannot manually enter a tab delimited search string in the search box widget as the tab will submit the string.   That will not be changed.
