### ISSUE TITLE
Add INS/DEL base counts to coverage track popup

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#154]
The coverage track popup currently shows ACGTN counts:

![image](https://cloud.githubusercontent.com/assets/6240170/11173109/dd588d12-8bdf-11e5-932a-ee7e5e6287e1.png)

It would be great to also have INS/DEL counts like in IGV desktop:

![image](https://cloud.githubusercontent.com/assets/6240170/11173096/b9adbfae-8bdf-11e5-940d-1bb388b9b737.png)

I started looking into adding this in coverageMap.js, but handling gapType == 'D' coords is proving to be tricky.

**Comment by sveint** [comment]
This one is in high demand with our users. Are there any plans by you guys to tackle this soon, or do you have any pointers for where I can look for implementing this?

Thanks a lot!

**Comment by jrobinso** [comment]
Thanks for the reminder,  I'll look at it now.
