### ISSUE TITLE
Track height popup appears out of view

### ISSUE THREAD

**Issue by rsmeral** [igvteam/igv.js#1542]
When the track height is set to a sufficiently high number, the next time you open the Track Height popup, it appears out of view, making it impossible to set the track height again. See attached video.

## Steps to reproduce
1. Click **Set track height** on a track
2. In the popup, set a large number (e.g. 5000) and confirm
3. Click **Set track height** again on the same track

## Actual results

The popup doesn't appear. Even if I scroll all the way to the bottom of the track, the popup is is not visible anywhere.

## Expected results
The popup should appear again, letting me set a different track height.

## Demo
https://user-images.githubusercontent.com/1309590/188664723-09e4fc69-4050-4abf-82a5-7e7f47fd5b81.mov

**Comment by turner** [comment]
I cannot reproduce this bug using the published app. Here is the URL I have tested with:
https://tinyurl.com/2glxc4h8

**Comment by jrobinso** [comment]
@rsmeral We can't reproduce this behavior.  Could you confirm that you are using the latest igv.js version?

**Comment by rsmeral** [comment]
Sorry to have dropped this for so long – competing priorities.
I've got a reproducer now: https://codesandbox.io/s/igv-in-modal-tqbfb6

It seems to happen whenever the IGV Browser is lower in the page, not the first thing at the top.

The `present` and `clampLocation` of `InputDialog` calculate the dialog position relative to the page: https://github.com/igvteam/igv-ui/blob/master/src/components/inputDialog.js#L83-L105

Not sure why exactly this breaks in some cases. But, for example, calculating relative to the viewport fixes it: https://github.com/igvteam/igv-ui/compare/master...rsmeral:igv-ui:patch-1

WDYT?

**Comment by jrobinso** [comment]
@rsmeral Thanks for the analysis, I think your fix is the correct one.  Do you want to submit a PR?
