### ISSUE TITLE
Sorting reads by read name in IGV.js visualization appears to sort randomly

### ISSUE THREAD

**Issue by firstcloudconsulting** [igvteam/igv.js#1546]
When using the the alignments visualization in IGV.js, and right-clicking in the coverage to select "sort by read name", there doesn't appear to be any logical sort order (certainly not by "read name". The sort order changes depending where you right-click in the coverage.

Examine the read order and note that it is not sorted.

**Comment by jrobinso** [comment]
Sorting occurs at the location you click, so it is not surprising it changes depending on location.   The reads in the pileup at the click location, that is that instersect that location,  should be sorted. If not we will need a test case to reproduce what you are seeing.

**Comment by firstcloudconsulting** [comment]
I’ve attached a `.bam`, `.bai`, and `.fasta` reference that show the problem for us in our implementation of `igv.js`; I’ve pulled out just a single candidate from the visualization files for one of the demo datasets, this is a Quiver detection of an EGFR rearrangement with ~5000 reads of coverage.

[Q52.zip](https://github.com/igvteam/igv.js/files/9611425/Q52.zip)

**Comment by jrobinso** [comment]
@firstcloudconsulting Could you be more specific on what you want me to do verify?   From your initial report I think you are misunderstanding what sorting actually does.

**Comment by jrobinso** [comment]
@firstcloudconsulting  thanks for the data, that was helpful.  I think I might see the confusion here.   Sorting of readnames is not lexicographical, in fact it sorts on the hashcode of the string.  This arises from the use case for which this sort option arose, the purpose is to bring paired or split alignments that might overlap in adjacent rows.  Such alignments have identical readnames.   

Your readnames are a bit unusual, looking a bit like a sequence, and perhaps you are looking for a lexicographical sort?  That is a reasonable request, but thats not what it currently does.     Leave this open for now, a lexicographical sort would be more intuitive and still work for the original use case.

Having said that, I'm still not sure it will do what you are expecting as I don't know what your use case is.  If you could elaborate on that here that would be helpful.

**Comment by firstcloudconsulting** [comment]
I don't know that there is a specific use-case - more of an observation amongst multiple colleagues that "something doesn't seem right". I think any "sort by name" is inherently expected to be lexicographical, so it is confusing, but thank you for the explanation. I'll leave it open in case this is a small change if others might agree.

**Comment by jrobinso** [comment]
Its a small change, and I agree that would be the expected behavior.
