### ISSUE TITLE
igv.js downsample reads

### ISSUE THREAD

**Issue by arthurchipdean** [igvteam/igv.js#1547]
Does igv.js downsample reads? Some of our users are reporting that there seems to be more reads visible depending on the zoom level.

**Comment by jrobinso** [comment]
It does, see https://github.com/igvteam/igv.js/wiki/Alignment-Track.

However, downsampling should not be dependent on zoom level.  I would need to see a test case to comment further.

**Comment by arthurchipdean** [comment]
Is it possible this could mean that it downsamples when the bases in the visible window is less than 100? I found another case where I see the same thing. Not all the reads are present (but there are more than 100), but when I zoom out to more than 100 bp window, more reads get added?

**Comment by jrobinso** [comment]
It creates a series of contiguous buckets of the width specified, 100bp being the default.   Zooming out could change the starting position of the first bucket which would shift the region of all the buckets.   

Membership in a bucket is based on the alignment start position,  so you can get > 100X coverage from alignments overhanging from adjacent buckets. Another thing that could affect the total number is paired alignments.   If one end of a pair is kept in its downsampled bucket its mate is not subject to downsampling.

When downsampled the precise total number of reads kept is not considered important.    No downsampling should occur until a bucket reaches the specified count, but you can have > the specified amount from paired reads and overhanging alignments.    You can always turn it off by setting the max number to Number.MAX_SAFE_INTEGER, although you then risk hanging the browser in areas of deep coverage.

**Comment by jrobinso** [comment]
I think the question is answered above, if not please re-open with more details.
