### ISSUE TITLE
scrollbars don't adjust position when 3-frame translation opens

### ISSUE THREAD

**Issue by jvolkening** [igvteam/igv.js#1553]
Thanks for the great piece of software -- just what we were looking for to use in a publication instead of asking readers to fiddle with their IGV server preferences.

I notice that in recent versions, expanding the three-frame translation view throws off positioning of the scrollbars for tracks below -- they appear not to adjust downward along with their associated tracks. Based on testing, this behavior appeared between releases 2.9.4 and 2.10.0. I've experienced it in both Firefox and Chrome on Linux. Attached are two screenshots showing the behavior in 2.9.4 (correct) and 2.10.0 (wrong positioning).

I can provide a MWE if needed, but it seems to happen with any of the pages in the examples folder of the repo.

Thanks,
Jeremy

Release 2.9.4:

![image](https://user-images.githubusercontent.com/11667655/197369701-427b59a8-ad95-4c14-ade5-48499e27c5d9.png)

Release 2.10.0:

![image](https://user-images.githubusercontent.com/11667655/197369711-144a2997-d45e-4d7d-aa82-a6bad0ebbda6.png)

**Comment by jrobinso** [comment]
OK I'll investigate.

**Comment by jrobinso** [comment]
This is fixed in release 2.13.4
