### ISSUE TITLE
IGV requests the entire bam file at once in certain cases.

### ISSUE THREAD

**Issue by IbrahimTanyalcin** [igvteam/igv.js#1561]
There are certain situations where IGV.js will require the entire bam file even if you scroll slightly to left/right of the viewport.

Normally, I have a reference (2.23GB) and a .bam file around 262Mb, when I zoom in/out or scroll left/right, a sample IGV request header looks like:

```
Range: bytes=1969716952-1969767576
```
My server responds as expected:
```
Content-Range: bytes 1969716952-1969767576/2396323876
Content-Type: application/octet-stream
```
Resulting payload is around 12-50kB generally. Which is the expected behavior.

Recently I received a small reference file (around 4kb), and a small bam file (around 7.3Mb) and a big bam file (around 700Mb) with respective .bai indexes and even with the small .bam file and `visibility Window` set to 50bp, whether you zoom in/out or scroll, IGV always makes the following request (basically entire bam file):

```
Range: bytes=270-7327614
```

And my server responds:

```
Content-Length: 7327345
Content-Range: bytes 270-7327614/7612045
Content-Type: application/octet-stream
```

Since the sequences are confidential, I am not able to share files. However what might be the reason for IGV requesting the entire file for particular bam/bai pairs all the time? Since I did not generate these files I am guessing the bam files might be unsorted (not sure whether that can affect things). Are there any other reasons why this might arise?

**Comment by jrobinso** [comment]
This would probably indicate some problem with the index, or some edge-case bug in igv.js parsing of the index.  Without a test file to reproduce the issue here I can't really say.   

If the bam files are not position sorted they could not be indexed.   If you tried to index a non-sorted file hopefully you would get an error, if not an error the index would be corrupt.   You might try sorting and then re-indexing the bam file

**Comment by IbrahimTanyalcin** [comment]
@jrobinso , ty for the swift response.
Looking at [this](https://www.biostars.org/p/5256/#5263) post at Biostars, it say samtools might generate a faulty .bai file from an unsorted bam and silently exit. I went and checked the size of the example that works:

262Mb bam file / 2.7 Mb bai file

The example that made igv request the entire bam is:

718Mb bam file / 96B (byte!) bai file
Smaller one:
9.9Mb bam file / 96B (byte!) bai file

How is a 96 byte bai file possible?

**Comment by jrobinso** [comment]
That doesn't seem possible (96 bytes),  if you could share the bai file, which has no sensitive information,  I could look at it.  Could you try sorting and indexing the bam file with samtools?

**Comment by IbrahimTanyalcin** [comment]
@jrobinso I will do as you suggest and re-sort and re-index with samtools and report back, thank you so much for your insight. Great tool.

**Comment by IbrahimTanyalcin** [comment]
Hi @jrobinso, I apologize for keeping this issue unresolved for so long and thank you for the patience. I posted the question on 

biostars  --> [here](https://www.biostars.org/p/9546642/#9547086)

It turns out, for Oxford Nanopore, it is normal to have 1 packet, therefore 96bytes of a bai file. 😢

**Comment by IbrahimTanyalcin** [comment]
Np, I guess there is no workaround. If only "vertical slicing" was possible, like not just start-end of the genomic region but also what is visible on the y-axis. But the bam format does not have that info even if that would be implemented in IGV. :( Anyway, I am closing the issue as this turned out to not have anything to do with IGV. Once again, thanks a lot!

**Comment by jrobinso** [comment]
And even if all that were true there's not much to be gained by manually inspecting many millions of reads.  

There's not much information after a certain coverage depth,  unless you are looking for the rarest of the rare variants.   Even then you are likely to miss it visually.    I think the best solution here is to downsample, as suggested in the biostars thread, to a reasonable sample depth.   Samtools is good for this.

**Comment by IbrahimTanyalcin** [comment]
This brings me to the last part, on the biostars thread, they wrote:

>You can split the bam easily after alignment (sort by read name, chop it up, sort by position).
You can post the issue in the appropriate IGV repository: https://github.com/igvteam and be sure to specify that your issue is a side-case where the reference length is smaller than the .bai interval size. My guess is that there may be an edge case when, if there is only one "interval" in the index, then even if all the reads are held in memory, any kind of scrolling re-triggers a request when it otherwise wouldn't.

Indeed, above is what was happening, even if the bam file was 10Mb, probably all data was held in memory. But if the user scrolls a little bit left or right, the same file would be requested over and over again. Is it possible to prevent this from happening?

**Comment by jrobinso** [comment]
@IbrahimTanyalcin Possibly but I would need a test case.

**Comment by jrobinso** [comment]
I can't reproduce what you describe, but that might be in the definition of "a little bit".    IGV will do a query for what's in view +/- one visible screen to left and right.   You can scroll left and right within that window without further loading of data.   If you leave that interval a new query will be generated.     That's how it works.   This has nothing to do with the size of the reference.

I'm not sure how you conclude that "probably all data is held in memory".    Its possible all data had to be read in the query,  but data not queried for (the window in view +/- a screen width). will be discarded.
