### ISSUE TITLE
High egress?

### ISSUE THREAD

**Issue by robertaboukhalil** [igvteam/igv.js#1562]
Hi Jim,

Random thought: Does IGV incur a lot of S3 egress charges from users downloading reference genome assets? Or are you part of an AWS opendata program?

I ask because I've been exploring a new cloud storage (Cloudflare R2) that has 0 egress fees and thought IGV might be able to benefit from it. I wrote about my experience with it so far here in case you're interested: https://robaboukhalil.medium.com/youre-paying-too-much-for-egress-b1fe20274a6b 🙂

**Comment by jrobinso** [comment]
Thanks, we'll keep an eye on it.
