### ISSUE TITLE
While I'm testing my project failed to export igv

### ISSUE THREAD

**Issue by nocey** [igvteam/igv.js#1563]
While testing, I get an error like the following. 

```
FAIL  src/theme/__test__/index.spec.js
    ●  Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/naci/Desktop/Web/frontend/node_modules/igv/dist/igv.esm.js:54087
    export { index as default };
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React, { useState, useEffect } from "react";
    > 2 | import igv from "igv";
        | ^
      3 | import clsx from "clsx";
      4 | import {
      5 |   Box,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/components/pages/reports/igvBrowser.js:2:1)
```
I tried adding libraries such as "EcmaScript, babel" and removing the standards, but I couldn't find a solution.

I know this is not an igv.js issue and it works fine outside the react app, but I have been trying to figure this out for days and haven't got a solution yet. Any suggestions are appreciated.

**Comment by jrobinso** [comment]
I don't have any experience with raw imports like

```
import igv from "igv"
```

This is not standard Browser javascript,  I wish it were.   Have you tried importing in the usual way, for example

```
/Users/naci/Desktop/Web/frontend/node_modules/igv/dist/igv.esm.js
```

Also, many projects use igv.js with react, and there are example projects out there.   A web search will turn them up.   I don't think we've done anything to break react compatibility.

Despite what the error message says igv.js uses 100% standard javascript syntax,  its a specific goal of this project that all files run in a browser without any transforms or packaging whatsoever.   That's how we develop.    We do package for distribution and babel transform for use on old browsers (although we might cease that soon),  however the igv.esm.js should not have any transforming its just a straight rollup (i.e. concatenation) of the code.

**Comment by nocey** [comment]
I know you are using JS syntax but this export is not standard for this reason jest it gives an error and wants to me use babel. I added to jest config this :

```
 "transform": {
    "transformIgnorePatterns": [
      "node_modules/(?!(react-flag-icon-css|flag-icon-css|igv))/"
    ]
```

this code igv and react-flag-icon-css libraries do not transform to babel (ECMAScript) and the test does not fail.

**Comment by jrobinso** [comment]
The line you reference is standard javascript syntax.   See https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

```
export { name1 as default /*, … */ };
```

**Comment by nocey** [comment]
I know is right but the jest error says to not standard JS export. That's why I wrote to let you know.

**Comment by jrobinso** [comment]
Thanks, you might want to report this to the jest project if that's where the error is coming from.
