### ISSUE TITLE
 How do I get the bam byte stream from "Range: bytes=1279-1304" to return to igv.html

### ISSUE THREAD

**Issue by xuefei6600** [igvteam/igv.js#1567]
Recently I have been using **django** to develop some visual pages， Some problems have been bothering me for a long time。
 I don't know much about front ends, so forgive me if I don't have a clear description。

I'll tell you a little bit about my front and back ends：

My viewpage：

```html
<DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IGV_browser</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="{% static 'igv/igv.min.js' %}" charset="utf-8"></script>
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
</head>
<body>
<div class="layui-row layui-col-space15">
    <div class="layui-col-md12">
        <div class="layui-panel">
            <div style="padding: 30px;">
                <div id="igv-div"></div>
            </div>
        </div>
    </div>
</div>
</body>
<script src="{% static 'igv/igv.js' %}" charset="utf-8"></script>
<script>
    var igvDiv = document.getElementById("igv-div");
    var options = {
        showNavigation: true,
        showRuler: true,
        genome: "hg19",
        locus: "chr2:209,111,864-209,114,359",
        tracks: [
            {
                name: "AGU138DZ.sorted.bam",
                type: "alignment",
                format: "bam",
                url: "http://123.57.32.214:8889/down/AGU138DZ.sorted.bam",
                indexURL: "http://123.57.32.214:8889/static/AGU138DZ.sorted.bam.bai"
            },
        ]
    };
    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
            console.log("Created IGV browser");
        })
</script>
</html>
```

the django back-end for resolution the bam url:

```python
def get_igv_url(request, *args):
    path = '/root/test/AGU138DZ.sorted.bam'
    range_header = request.META['HTTP_RANGE']
    content_type, encoding = mimetypes.guess_type(path)
    content_type = content_type or 'application/octet-stream'
    m = re.search('(\d+)-(\d*)', range_header)
    if not m:
        return "Error: unexpected range header syntax: {}".format(range_header)
    offset = int(m.group(1))
    size = os.path.getsize(path)
    length = int(m.group(2) or size) - offset + 1
    with open(path, 'rb') as f:
        f.seek(offset)
        data = f.read(length)
    response = StreamingHttpResponse(data)
    response['Content-Type'] = content_type
    response['Content-Range'] = 'bytes {0}-{1}/{2}'.format(offset, offset + length - 1, size)
    response['Content-Length'] = length
    response['status'] = 206
    response['Accept-Ranges'] = 'bytes'
    return response
```

The problem I encountered is described below：

![1image](https://user-images.githubusercontent.com/41353934/204237405-48a59ed2-c9d3-4ed7-8b30-43e8098be2fb.png)

![2image](https://user-images.githubusercontent.com/41353934/204237478-4190b0b0-2b7f-4d44-9eff-0ff9a0c95dd0.png)

I clearly know that for a large bam file, I need to get the byte stream of windows information according to the Range information. I think I may have handled the parsing of bam url incorrectly. **If you have any tips or suggestions that would be helpful, I would really appreciate it~**

**Comment by xuefei6600** [comment]
im sorry for my images up failed ,you can look at  http://123.57.32.214:8889/igv2/

**Comment by jrobinso** [comment]
@xuefei6600 I don't really understand your question.   If you are implementing a server yourself, which you appear to be doing, you need to respect the range-byte header and any other headers for that matter.   You'll also need to implement CORS.  But these aren't really igv.js questions,  I don't know anything about django, but it looks like you are doing the correct thing WRT byte range, but I don't see any CORS headers.   This could cause an issue.

The screenshots aren't really helpful, what are you trying to show?

**Comment by jrobinso** [comment]
Some information on CORS for igv.js here: https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements.   Also just do a websearch for "javascript CORS".
