### ISSUE TITLE
disable cytoband view

### ISSUE THREAD

**Issue by lpryszcz** [igvteam/igv.js#1568]
Hi, first of all, jgv.js is fantastic! 

Would it be possible to disable cytoband view automatically if cytobandURL isn't provided? 
Alternatively, could you add an option to disable it in [Browser-Creation config](https://github.com/igvteam/igv.js/wiki/Browser-Creation#browser-configuration-options)?

**Comment by jrobinso** [comment]
Hi, sorry for the delay.   There is already an option for this, although its not documented (I will correct that).   To disable the cytoband use the following in the browser configuration object

```
showIdeogram: false
```

**Comment by lpryszcz** [comment]
thanks a lot, most helpful!
