### ISSUE TITLE
Add arbitrary text to navigation bar

### ISSUE THREAD

**Issue by lpryszcz** [igvteam/igv.js#1569]
Hi, would it be possible to add arbitrary text to navigation bar ie brief experiment/session description? 
For now it's mostly empty and this info has to be specified somewhere in the page taking space...

![image](https://user-images.githubusercontent.com/988152/206722900-abc63969-ef83-4f46-b417-803410756107.png)

**Comment by jrobinso** [comment]
This depends on the width of your browser window, obviously you have a very wide one.     In general there is not a lot of extra space
