### ISSUE TITLE
allow bamReader block size to be adjusted

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#157]
The bam block size is set to 65kb in several places (eg. https://github.com/igvteam/igv.js/blob/d9a46bf5a7325bc2cd10a938b87dee80aca34097/js/bam/bamReader.js#L80). On some bams (particularly RNA-seq bams - because of splicing and/or read-depth) this triggers over 20 http GET requests to load 1 viewport. Could the 65kb constant be globally settable so that it's easy to adjust for particular datasets?

**Comment by jrobinso** [comment]
That parameter in bamReader has no effect on the # of get requests.   The # of get requests will be controlled by the # of "chunks" from the bam index for the region requested.   An attempt is made to merge adjacent chunks in bamIndex around line 229.    This is where you would adjust the 65k parameter to something else.   However, before doing this could you try changing that manually in the code and see if it makes any difference?

**Comment by jrobinso** [comment]
I'm going to close this in the absence of evidence that increasing the "chunk merge" parameter will have a positive impact on performance.   I think it is much more likely to have a negative one.
