### ISSUE TITLE
Default hg38 genome loading blocked by CORS

### ISSUE THREAD

**Issue by kalon33** [igvteam/igv.js#1570]
When using igv.js I got `Error accessing resource: https://igv.genepattern.org/genomes/seq/hg38/hg38.fa Status: 0`. Opening webbrowser console, it seems linked to a CORS problem.
   
Could you have a look for a fix?
   
Thanks for your help.

**Comment by kalon33** [comment]
It seems to affect https://igv.org/app/ too.

**Comment by nvnieuwk** [comment]
Happens to me too. It seems to be `firefox` only though. Apparently Firefox blocks API calls that do not contain the `Access-Control-Allow-Origin` in their header (which `https://igv.genepattern.org/genomes/seq/hg38/hg38.fa` is missing). This is new in the last update I think.

**Comment by jrobinso** [comment]
I can reproduce the error on Firefox,  the header is there for the GET method but is missing for OPTIONS.   Apparently Chrome does not care.

@liefeld

**Comment by jrobinso** [comment]
I've reverted the fasta URLs back to the old location until we can fix this.   I had to clear my Firefox cache, then restart it, to force it to update, it was very stubborn.  

We are in the process of moving our hosted files, thanks for the report.

**Comment by jrobinso** [comment]
This should be working now, re-open if not.

**Comment by nvnieuwk** [comment]
It works again for me!

**Comment by kalon33** [comment]
Works again for me too, thanks!
