### ISSUE TITLE
Multiple Pop-ups 

### ISSUE THREAD

**Issue by DustBytes** [igvteam/igv.js#1571]
Thank you for making an awesome tool.

One feature we need is to have multiple pop-ups when clicking on reads/coverage. This way we can compare different reads from same or different tracks. Can see coverage info from different reads etc.

If it's already possible please link. I couldn't t find it.

Thank You

**Comment by DustBytes** [comment]
@turner any updates on this please.

**Comment by turner** [comment]
Not yet. Other tasks currently take precedence.

**Comment by turner** [comment]
Implemented with PR 1571
https://github.com/igvteam/igv.js/pull/1745
