### ISSUE TITLE
Split View Depth

### ISSUE THREAD

**Issue by DustBytes** [igvteam/igv.js#1578]
Hi,

When we view multiple locations as split view like this https://igv.org/web/release/2.13.9/examples/multi-locus.html
The depth is only shown for one of them (seems like the last location).
This is uninformative. For comparison we need to know the depth of both.

Can we please have depth for all the split views.

Regards,

**Comment by jrobinso** [comment]
The depth is shown for both views, as you can see in the example you referenced.   So I'm really not sure what you are referring too.   If you don't see depth on both views I will need a reproducible test case.   Verify you are using the latest igv.js release first.

<img width="1523" alt="Screen Shot 2023-01-19 at 10 46 38 PM" src="https://user-images.githubusercontent.com/933148/213634425-9ad490a7-96e1-4436-8bb8-f56699d02305.png">

**Comment by DustBytes** [comment]
I am using latest from https://igv.org/web/release/  , 2.13.10

I think I am mistaken with what this value is:

The red highlight.
![igv_depth](https://user-images.githubusercontent.com/9694405/213637283-1ccc0a9e-6a8a-449a-9a51-89b18af1dfc7.png)

**Comment by jrobinso** [comment]
That is the data scale, it applies to all views.

**Comment by DustBytes** [comment]
Shouldn't this range be different for each location?

This number gets adjusted to the second/last split. 
I am loading the viewer as single location, then adding another location with  space in the top left search.


If second view coverage is of lower height than the first, the first view coverage gets trimmed.

Names are long for my data, which covers the custom tracks and coverage graph also.

Different scale will help to compare if these regions are equally/comparatively covered or not.

![Screenshot_20230120_141237](https://user-images.githubusercontent.com/9694405/213653055-ce2dff3d-fd9a-4010-8b5b-6db088fa9ba8.png)

**Comment by jrobinso** [comment]
Also, you can toggle name labels off.   The solution for it is to use shorter names.

**Comment by DustBytes** [comment]
> Also, you can toggle name labels off. The solution for it is to use shorter names.

Can we change font/location of names?
We are adding lots of tracks so names are needed.

**Comment by DustBytes** [comment]
> 

Different coverage view for each split?
Is it worth or good idea?

Right now this data scale is matching to last split which is creating confusion to know which coverage scale we are looking at.

**Comment by DustBytes** [comment]
> You can make an argument for either, if one region has much lower coverage than another you would want to see that. If all regions had different scales you wouldn't be able to compare coverage. That is how IGV works anyway.
> 
> I don't understand your comment about different scales helping to compare, it would seem to do the opposite. At any rate that is what igv.js (and IGV) do, we could consider an option to allow different scales.

Different coverage view for each split? Is it worth or good idea?

Right now this data scale is matching to last split which is creating confusion to know which coverage scale we are looking at.

**Comment by DustBytes** [comment]
> You can make an argument for either, if one region has much lower coverage than another you would want to see that. If all regions had different scales you wouldn't be able to compare coverage. That is how IGV works anyway.
> 
> I don't understand your comment about different scales helping to compare, it would seem to do the opposite. At any rate that is what igv.js (and IGV) do, we could consider an option to allow different scales.

Right now this data scale is matching to last split which is creating confusion to know which coverage scale we are looking at.


On desktop IGV we can see data scale for each location.


![coverage_data](https://user-images.githubusercontent.com/9694405/213666025-eda1c27b-91fa-4174-bf66-02d7b254f981.png)

**Comment by jrobinso** [comment]
I'm not sure I'm understanding you, but the data scale is not associated with any specific panel.    The scale is the same for all panels.    Its shown once on the left in igv.js but it is not in any specific panel.

RE names,  the user can toggle them on or off but you cannot move them.   If you want to request the ability to set the font open an issue for that.   Its best to open specific issues for specific requests, otherwise they get lost and forgotten.

**Comment by DustBytes** [comment]
[0-161] is on both the locations./splits.
It should change in second location , don;t know why it's common in both.

**Comment by jrobinso** [comment]
Are you referring to igv desktop now?  I'm getting very confused trying to follow your reasoning I don't think you understand the data scale.   Why do you think its the scale of just the right one?

**Comment by DustBytes** [comment]
Sorry for the confusion.
I am comparing the igv.js with desktop igv to talk about data scale.

I think it's the second one because when I scroll the position in the second one the scale changes but not while scrolling first position.

**Comment by jrobinso** [comment]
The scale is the autoscale of all the data in view (in all views), assuming you have autoscale turned on,  which panel you are scrolling is not relevant.
