### ISSUE TITLE
is it possible to downsample bam tracks?

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#158]
It would be great if I could set a max depth so that regions with excessive read depth don't overload the browser (ideally the extra reads wouldn't even be requested).

**Comment by jrobinso** [comment]
Starting work on this now.  There is no way to not request "extra reads",  you don't know where they are until you've read them (thus don't know they are extra).

BTW,  you can set a maximum # of rows of alignments to show,  config param maxRows.   However,  I'm not sure this frees up any memory.

**Comment by jrobinso** [comment]
Ben, this and many other features have been implemented in a branch called "Promises".   It will be merged into main later this weekend.  You can test the branch from igv.org/web/test

**Comment by benralexander** [comment]
Will test.  Thanks.

**Comment by jrobinso** [comment]
Downsampling can be configured as follows.  It works by limiting the number of alignments in each sampling window to the specified depth.    The defaults are window size = 100bp, depth = 100

{
                                type: 'bam',
                                url: '../test/data/bam/gstt1_sample.bam',
                                name: 'Ion BAM',
                                samplingWindowSize: 100,
                                samplingDepth: 5}
