### ISSUE TITLE
Unknown file type with files in the same location as .html

### ISSUE THREAD

**Issue by mirpedrol** [igvteam/igv.js#1583]
Hello,

I am trying to implement a genome browser with a bam file. 
I locate the file in the same folder together with my html. 
When I try to open the browser, I see a pop-up with the message "Unknown file type: test.paired_end.sorted.bam".

I have tried to serve this files with the command `npx http-server -a localhost /var/folders/lt/b3cs9y610fg_13q14dckwcvm0000gn/T/tmp0qednhq2/igv/` and teh error persists.

I have also checked that the links from where I obtained those files (s3 bucket) work, and I can read the files with `samtools` so they are readable.

Is there anything I am doing wrong? How could I solve this? 
Thank you!

<details>
<summary>My html looks like this</summary>

```
<html>
    <head>
        <script src="https://cdn.jsdelivr.net/npm/igv@2.10.5/dist/igv.min.js"></script> <!-- https://github.com/igvteam/igv.js/ -->
    </head>
    <body>

    <div id="igv-div"></div>
    <script>
        var igvDiv = document.getElementById("igv-div");
        var options =
        {
            genome: "hg38",
            locus: "chr22:4,514-4,554",
            tracks: [
                {
                    "name": "test",
                    "url": "test.paired_end.sorted.bam",
                    "indexURL": "test.paired_end.sorted.bam.bai",
                    "format": "bam",
                    "type": "alignement"
                }
            ]
        };
        igv.removeAllBrowsers();
        igv.createBrowser(igvDiv, options)
            .then(function(browser){
                igv.browser = browser;
            })
    </script>

    </body>
</html>
```
</details>

I have also created a `httpd.conf` file in the same directory containing `AddType application/octet-stream .bam`

**Comment by jrobinso** [comment]
It looks almost perfect,  but the type ("alignment") is mis-spelled.   That's an older version of igv.js, the latest version (2.13.9) gives a slightly more helpful error message.

**Comment by mirpedrol** [comment]
This solved the error, thank you very much for your help! My apologies for the silly oversight 😅
