### ISSUE TITLE
[Docs] Best practices for viewing alignments

### ISSUE THREAD

**Issue by jamestwebber** [igvteam/igv.js#1587]
I've been exploring `igv.js` along with [igv-notebook](https://github.com/igvteam/igv-notebook) as a tool to explore our data. It seems like it could be a great option for interactive analysis that we can also share with collaborators.

As I get started, I wanted to check that I'm doing everything I can to make it responsive. I'd like to build a tool for exploring an aligned dataset and visualizing the evidence for different isoforms, etc. If there are particular ways to prepare my BAM file to make `igv.js` work better, that'd be great to know.

I was looking at the [documentation for alignments](https://github.com/igvteam/igv.js/wiki/Alignment-Track#b-sort-option) and saw the section on sorting, but I wasn't clear on what it did. Is that config for re-sorting the track for display, or is it a hint about how the BAM is sorted, or something else? Does it make a difference to performance?

I'm focused on viewing BAMs that are on the local machine, via a jupyter notebook. I was considering whether there's anything I could do on the "server" side to make loading data faster. i.e. perhaps I could pre-filter the BAM file to a certain region based on the user's analysis, before passing that to the viewer. I would want to avoid writing that to disk, though, so it would require some way to pass an in-memory object to the viewer.

**Comment by jrobinso** [comment]
@jamestwebber I found the bottleneck, it is not loading or rendering, rather the "packing" of alignments into rows.   The characteristics of long-read transcriptome data has exposed some slowness of the algorithm.    I will solve this, thanks for the data,  whatever the issue is does not arrive in short or long read genome data.

**Comment by jamestwebber** [comment]
That's great! Happy to test things out if that helps.

**Comment by jrobinso** [comment]
I pushed a fix for the slow packing, in your test case it is reduced to ~200 ms from almost 2 seconds.    The no-packing idea (1 alignment per row) is interesting but a much bigger task and should have its own git issue, if you are interested in pursing that.

This will be in the next igv.js release by the end of the month, and igv-notebook soon after.

**Comment by jrobinso** [comment]
I just pushed support for a new "FULL" display mode, which layouts a single alignment per row.
