### ISSUE TITLE
Allow orderly disposal of igv.browser object, and re-creation

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#159]
From igv-help forum.

This is a developer question related to IGV.js (the embeddable Javascript library, NOT the standalone application, IGV):

I was able to follow the demonstration page and embed igv.js functionality in my web page.  It works great.  Very impressive work.  

My only issue is that it seems intended for single-launch use - i.e. if you twice invoke the "igv.createBrowser(...)" call, you get the error "Attempt to create 2 browsers".  But I am attempting to embed the viewer within some modal popups that users can open/close at their convenience (and thus the DOM element into which IGV was initiated goes away at close). 

I got around this issue (sort of) by explicitly destroying the IGV object when the modal popup closes, via:  
delete igv['browser'];

And this seems to do the trick - now the modal popups can be opened/closed without problems.  But this is no doubt not a recommended method (okay, okay... it's 'criminal') for accomplishing this goal.  One tipoff - after doing the above forced destruction, there are console messages like this: 

Uncaught TypeError: Cannot read property 'referenceFrame' of undefined
  (anonymous function)	
  igv.throttle	
  m.event.dispatch	
  m.event.add.r.handle

so perhaps some IGV event queue still contained messages when I unceremoniously unplugged things.  

Is there a recommended orderly way to close down an IGV.js instance so that it can be cleanly started from scratch again?

**Comment by MatthewMaher** [comment]
Just to elaborate on the use case for the question just copied here from igv-help forum:

I am _not_ looking to have two active IGVs simultaneously, just one at a time.   

The app allows users to pull up lists of variant calls for a given sample (~ BAM) for searching, sorting, etc. and the GUI has a general paradigm of popups to supply functionality specific to a variant - and popping open IGV to see the reads supporting a particular variant call is a tremendous feature. But the users could quickly want to close that view and then view a different variant or possibly from a completely different sample/BAM.  And the user would be doing this opening/closing of IGV or other tools, all without leaving the page/app (based on Angular) so there's no full reload of the page that would recreate a blank slate.

**Comment by jrobinso** [comment]
OK, thanks for elaborating.   I'm working on igv.js this week and will look to add a clean shutdown/dispose.  In the meantime there are api calls to add/remove tracks, and jump to other locations.  If you need help finding or using those just continue the conversation here.

**Comment by jrobinso** [comment]
A fix has been committed to the Promises branch.   Now calling createBrowser will first cleanup/remove existing igv objects, if any,  effectively doing a reset.   This branch will be merged to main in the next few days.
