### ISSUE TITLE
igv.js breaks CI test by appending style when included

### ISSUE THREAD

**Issue by holtgrewe** [igvteam/igv.js#1590]
When run in my CI tests (with vitest), I get the following error:

```
TypeError: Failed to execute 'insertBefore' on 'Node': 2 arguments required, but only 1 present.
 ❯ HTMLElement.insertBefore node_modules/happy-dom/lib/nodes/node/Node.js:330:19
 ❯ HTMLElement.insertBefore node_modules/happy-dom/lib/nodes/element/Element.js:353:35
 ❯ embedCSS$2 node_modules/igv/dist/igv.esm.js:20591:19
    20589| /*# sourceMappingURL=igv-ui-1_3_0.css.map */
    20590| `;
    20591|     document.head.insertBefore(style, document.head.childNodes[ document.head.childNodes.length - 1 ]);
       |                   ^
    20592| }
    20593| 
 ❯ node_modules/igv/dist/igv.esm.js:20597:9
 ❯ async /home/holtgrem_c/Development/varfish/varfish-server/varfish/vueapp/src/svs/components/GenomeBrowser.vue:3:31
 ❯ async /home/holtgrem_c/Development/varfish/varfish-server/varfish/vueapp/src/cases/components/CaseDetailContent.vue:22:32
 ❯ async /home/holtgrem_c/Development/varfish/varfish-server/varfish/vueapp/src/cases/components/CaseDetail.vue:23:32
 ❯ async /home/holtgrem_c/Development/varfish/varfish-server/varfish/vueapp/tests/cases/unit/cases/CaseDetail.spec.js:9:31
```

I can work around this by putting the following on top of my `.spec.js` file:

```
// Work around issue with igv.js accessing document.head.children when included.
document.head.appendChild(document.createElement('title'))
```

It would be nice if one could prevent this, e.g., by checking whether the environment variable `NODE_ENV` is `test`.

**Comment by jrobinso** [comment]
@holtgrewe I have a couple of questions,  what is "vitest", and what is ".spec.js".   I assume the test is running in a Node environment,  no 3rd party library or tool should be needed.    

Also, could you elaborate a little bit on your NODE_ENV suggestion?

**Comment by holtgrewe** [comment]
[vitest](https://vitest.dev/) is a unit testing framework for Javascript (the recommended one for Vue apps). A `.spec.js` file is a unit test file. When tests are run, the environment variable `NODE_ENV` is set to `test` to indicate to the code under test that it is tested.

**What is the problem?**
When the `igv.js` file is included, it tries to execute the `document.head.insertBefore(...)` without any function being called. This causes trouble if the `document.head` is empty, as is the case when running unit tests. My unit testing environment uses [happy-dom](https://github.com/capricorn86/happy-dom) to provide a DOM in plain node and the head tag is empty.

**What does my workaround do?**
The workaround adds a `<title>` element into the global `document.head`. The `igv.js` code can thus run.

**What is the NODE_ENV suggestion?**
I would suggest to wrap the `documet.head.insertBefore()` code as follows:

```javascript
if (process?.env?.NODE_ENV !== "test") {
    // document.head.insertBefore(...)
}
```

This means that this is not executed when tests are being run.

It would be even better if this code was not called implicitly when the IGV JS file is imported. Rather, the browser creation function could check whether it can find the code that is injected in the `document.head` already and only inject it if it has not been added before.

**Comment by jrobinso** [comment]
I can look into these suggestions.   However there might be other issues, your stack trace references "igv.esm.js".    The tests do not run on the distributed package "igv.esm.js",  they run on the source code in "js".

**Comment by jrobinso** [comment]
The igv.js unit tests uses its own mock DOM as well,  I don't know how that interacts with happy-dom.     In short you might be using the tests in ways that they are not designed for.     I will look into not injecting the CSS if its already there, because that is a good suggestion in its own right.

**Comment by holtgrewe** [comment]
@jrobinso Maybe there is a misunderstanding. I'm referring to the tests of my app varfish-server and their failing tests.

https://github.com/bihealth/varfish-server/actions/runs/4133109190/jobs/7142618887#step:5:111

**Comment by jrobinso** [comment]
@holtgrewe Ahh, yes,  I misunderstood.   I did not understand how igv.js tests worked at all.

**Comment by jrobinso** [comment]
@holtgrewe I don't understand how this suggestion helps you, unless your tests never call createBrowser

> It would be even better if this code was not called implicitly when the IGV JS file is imported. Rather, the browser creation function could check whether it can find the code that is injected in the document.head already and only inject it if it has not been added before.

**Comment by jrobinso** [comment]
Also, so I'm clear on the problem,  I infer your DOM has no nodes under "head", so ```document.head.childNodes[ document.head.childNodes.length - 1 ]``` is not defined, correct?

**Comment by holtgrewe** [comment]
> Also, so I'm clear on the problem, I infer your DOM has no nodes under "head", so `document.head.childNodes[ document.head.childNodes.length - 1 ]` is not defined, correct?

Yes, this is the problem. At the beginning of the test, the DOM is pretty minimal.

**Comment by jrobinso** [comment]
That's a bug in itself, assuming there are nodes,  I think fixing that should solve this.   I'm testing just using "append" instead of insertBefore.

**Comment by holtgrewe** [comment]
@jrobinso Wonderful, thanks for your support!

**Comment by jrobinso** [comment]
@holtgrewe I lost track of this but I think it should be fixed,  I'm closing but reopen if I've missed something.
