### ISSUE TITLE
change in format of genomes.json?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1592]
igvR and igvShiny both query 

   ```https://s3.amazonaws.com/igv.org.genomes/genomes.json```

It looks like the format just changed.  Possibly so?   Easy to accommodate, but wanted to be sure my problem does not lie elsewhere.

**Comment by jrobinso** [comment]
In what way?  Nothing has changed to my knowledge.

**Comment by paul-shannon** [comment]
Hi Jim,   My parsing broke, so blamed it on you :) .   Unfairly...
With my parsing code now a bit more pessimistic, everything works again.    What changed, and where, in the libraries I use, I'll probably never know.
