### ISSUE TITLE
Read alignments from hstget format specifications

### ISSUE THREAD

**Issue by alberto1189** [igvteam/igv.js#1605]
Hello

We would like to visualize alignments data in htsget format: 

`{"htsget":{"format":"BAM","urls":[{"url":"data:base64,H4sIBAAAAAAA/wYAQkMCA .....`}}]}

We would send this json file from server to the igv.js. How should we decode the "url" string in order to visualize the data?
Does the new version supports this json specification of htsget?

We are trying this at the moment, without success:

`for url in  response["htsget"]["urls"]:
    data = url["url"]
    data = data[data.find(',')+1:]
    htsget_data = htsget_data + data

t = htsget_data.encode("ascii")
decoded = base64.decodebytes(t)`

But the alignment is not visualized and no extra information is given.

![empty_igv](https://user-images.githubusercontent.com/5526881/224736802-ee5e025b-e477-40fa-8d16-cc5087886183.JPG)

Many thanks
Alberto

**Comment by jrobinso** [comment]
Hi,

Could you post your igv.js track configuration?    There is an example htsget configuration in the documentation here:  https://github.com/igvteam/igv.js/wiki/Alignment-Track.   Scroll to the bottom.

```
{
   type: 'alignment',
   sourceType: 'htsget',
   format: 'bam',
   url: 'https://htsget.ga4gh.org/reads/giab.NA12878.NIST7086.1',
   name: 'NA12878'
}
```

This should still work.   Unfortunately the htsget public enpoint  ```https://htsget.ga4gh.org/``` stopped working over a year ago and I have no way to test htsget anymore.

I'm sorry I don't understand the rest of your post, in particular this.   Where are you doing this?  

> We are trying this at the moment, without success:
> 
> `for url in response["htsget"]["urls"]:
> data = url["url"]
> data = data[data.find(',')+1:]
> htsget_data = htsget_data + data
> 
> t = htsget_data.encode("ascii")
> decoded = base64.decodebytes(t)`

**Comment by alberto1189** [comment]
thank you Jim,


We are using the following 

`
   
       let track = [
            {
                type: 'alignment',
                sourceType: 'htsget',
                url: bam_url,
                endpoint: server_url,
                id: experimentName,
                name: experimentName,
                oauthToken: token
            }
        ];

    
`

The code above is a python script block in our flask server, from where we serve the alignments data to the client that includes the igv.js. We stream the data from the server, after decoding. What is the input data type expected by the igv.js for rendering for the htsget use case?

Many thanks
Alberto

**Comment by jrobinso** [comment]
The configuration I gave you is for igv.js,  you don't need to do any
decoding in python its done in igv.js.   See the documentation I pointed
to.   If that doesn't work zip and post your html page that contains the
igv.js configuration here.

Below is a complete example.  Again it doesn't work because the server it
is referencing stopped working, but this is how you configure igv.js.

```

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,
initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon"
href="https://igv.org/web/https://igv.org/web/img/favicon.ico">

    <title>igv.js</title>

</head>

<body>

<h1>htsget server example</h1>

<div id="myDiv" style="padding-top: 50px;padding-bottom: 20px; height:
auto"></div>

<script type="module">

    import igv from "../dist/igv.esm.js";

    var div = document.getElementById("myDiv");
    var options = {
        genome: "hg19",
        locus: "chr8:128,734,098-128,763,217",
        tracks: [
            {
               type: 'variant',
               name: 'giab.NA12878',
               sourceType: 'htsget',
               format: "VCF",
                url: 'htsget://htsget.ga4gh.org/variants/giab.NA12878'
            },
            {
               type: 'alignment',
               name: 'giab.NA12878.NIST7086.1',
               sourceType: 'htsget',
               format: 'bam',
                url: 'htsget://htsget.ga4gh.org/reads/giab.NA12878.NIST7086.1'
            }
        ]
    };

    igv.createBrowser(div, options)

        .then(function (browser) {
            console.log("Created IGV browser");
        })


</script>

</body>

</html>

```

**Comment by alberto1189** [comment]
Thanks very much Jim for your quick replies.

We are indeed using the same configuration. I realized yesterday that the decoding of hstget data URIs is done already in the IGV.js in the "readAlignments" function. It seems like the data was corrupted or not formatted correctly which gives the empty image that I attached earlier. No error is thrown, but only a no rendering. Do you have any suggestion to verify the integrity of the data?

Thanks
A

**Comment by jrobinso** [comment]
You might try reading with this python client to see if the problem is with your server or igv.js.   https://github.com/ga4gh/htsget

Again I cannot test htsget anymore because the only public endpoint I know about is no longer maintained.    So until that is fixed or an alternative appears I cannot really support it.

**Comment by brainstorm** [comment]
GA4GH htsget-rs public endpoint is now available, here are some instructions: https://umccr.org/blog/htsget-rs-crypt4gh/
