### ISSUE TITLE
wigTrack.js  "lastNegValue is not defined"

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#1607]
In trying to track down a just-appeared failure in latest igv.js to display format bedGraph tracks from igvR, I found this related, and maybe explanatory error message in the js console.  I could not reproduce my problem in minimal html, but maybe this error will be of interest?  (And might even fix my own odd failure in igvR, in which the second of two bedGraph tracks fails to display).

Looking at the latest source for wigTrack.js, I see that ```lastNegValue``` appears only once in the file.

![image](https://user-images.githubusercontent.com/2480712/224827131-423dc5ae-9b4b-4970-bb10-e2272eafb242.png)

**Comment by paul-shannon** [comment]
I just  rebuilt igvR with  ``` https://cdn.jsdelivr.net/npm/igv@2.13.9/dist/igv.js```:
  - my igvR bedGraph track problem went away
  - I may see the line that went missing:
```
bash>  grep -i lastNegValue igv-2.13.9.js
    let lastNegValue = 1;
          if (pixelEnd > lastPixelEnd || f.value >= 0 && f.value > lastValue || f.value < 0 && f.value < lastNegValue) {
```

**Comment by jrobinso** [comment]
Thanks. Fixed.
