### ISSUE TITLE
For htsget variants source and visibilityWindow = -1 IGV get data only for one chromosome

### ISSUE THREAD

**Issue by RoadRoller** [igvteam/igv.js#1609]
igv.js version: 2.13.11

Steps to reproduce:
1. configure variants track with htsget source and visibilityWindow = -1

```
{
        name: 'My variants',
        url: <URL_TO_HTSGET_SERVER>,
        type: "variant",
        format: "vcf",
        sourceType: 'htsget',
        visibilityWindow: -1,
      }
```
2. Open IGV with track and select some chromosome - variants displayed as expected
3. Switch to another chromosome - results are empty, expected variants for selected chromosome

**Comment by jrobinso** [comment]
Unfortunately I do not have access to an htsget server anymore,  the public endpoint from GA4GH has been broken for over a year.   So I'm not able to support htsget at this time.
