### ISSUE TITLE
igv-jupyter notebook extension breaking on igv.js

### ISSUE THREAD

**Issue by kkapuria3** [igvteam/igv.js#1612]
I am using igv-jupyter notebook extension to use IGV inside our notebooks. Yesterday (03/20), we started noticing that the igv app was no longer loading in our notebook and was prompting following error.

![image](https://user-images.githubusercontent.com/25559534/226743050-3116a4e3-814e-4018-8fad-d3134976561b.png)

Further looking in browser's console logs, we see this error

![image](https://user-images.githubusercontent.com/25559534/226742492-1ed9b383-1e00-4e44-8ad0-02217a2b4d20.png)

Please let us know if this error means something and can help.

**Comment by jrobinso** [comment]
Hi,  igv-jupyter is no longer supported by us (the "igv" team).   We now support igv-notebook, which wraps igv.js in a python module for notebooks, no extension required.      https://github.com/igvteam/igv-notebook

If you wish help with igv-jupyter it is now supported by the "genepattern" team,  the repository is here:  https://github.com/g2nb/igv-jupyter.
