### ISSUE TITLE
https://igv.org/genomes/genomes.json does not return json  

### ISSUE THREAD

**Issue by mmanokhov** [igvteam/igv.js#1614]
Hello everyone,
   
We have faced with the following problem recently:

By default igv.js lib uses https://igv.org/genomes/genomes.json resource to initialize genomes references. Now it returns an empty body in a response although json is expected according to the lib code.
Now genome.js throws the following exception:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/2229434/226993342-87c27087-c1e7-4209-9ad8-9b773e87ff00.png">
We use igv.js version 2.7.4

The similar problem may be found in official IGV Web client by https://igv.org/app

Thanks.

**Comment by mmanokhov** [comment]
Hello everyone,
   
We have faced with the following problem recently:

By default igv.js lib uses `https://igv.org/genomes/genomes.json` resource to initialize genomes references. Now it returns an empty body in a response although json is expected according to the lib code. 
Now genome.js throws the following exception: 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/2229434/226991801-9c7c4820-f31e-452e-b9d9-5dd55e220008.png">
We use igv.js version 2.7.3

The similar problem may be found in official IGV Web client by https://igv.org/app

Thanks.

**Comment by jrobinso** [comment]
Thanks for the report,  I will look into it.   If this server fails a
backup store should be used automatically (in an S3 bucket).   Is the
backup store working for you?

**Comment by jrobinso** [comment]
This should be fixed, reopen if not.
