### ISSUE TITLE
Invisible bigwig track on reverse strand

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#1615]
From IGV-help [question]( https://groups.google.com/d/msgid/igv-help/3c966854-40f0-4043-a719-7378bb4eddf0n%40googlegroups.com?utm_medium=email&utm_source=footer)

I use the web browser (IGV-Web app version 1.12.9 igv.js version 2.13.11) and I load 8 bigwig tracks where 4 are forward strand and 4 are reverse strand. None of the reverse strand tracks are visible, I can set the track height, change the data range, but nothing shows up. Data values for the reverse strands are negative numbers and vice versa for the forward. 
When I use the desktop version, the all track show up. I want to use the web version because of the sharing ability.

Here is the link to the viewer for reference: https://tinyurl.com/2hwmu4be

**Comment by helgathorv** [comment]
Here's one of the files that isn't displayed https://www.dropbox.com/s/xacdr2ds50vz4en/MEF_CF_2_rev.bw?dl=0

From the console log: Uncaught (in promise) ReferenceError: lastNegValue is not defined

**Comment by paul-shannon** [comment]
I think this was fixed in response to https://github.com/igvteam/igv.js/issues/1607

**Comment by turner** [comment]
Yes,
This was fixed with this commit:
https://github.com/igvteam/igv.js/commit/33eddee942da5694a85a6d7e658f42c9e1676e15
