### ISSUE TITLE
URL-encoded spaces (and other chars) in BED name field not decoded in igv.js

### ISSUE THREAD

**Issue by jvolkening** [igvteam/igv.js#1621]
@jrobinso mentioned in a separate issue that spaces in BED fields are technically not correct, because BED files can be whitespace-delimited. After URL-encoding spaces as suggested in the [IGV docs](https://software.broadinstitute.org/software/igv/BED), it seems igv.js is not displaying them correctly when used with `#gffTags`, e.g.:

![Screenshot_2023-03-28_04-28-06](https://user-images.githubusercontent.com/11667655/228194861-63fa5fbb-f54d-40de-a557-2271c7280fb6.png)

I see in the code for `decodeGFFAttribute()` that only a small subset of encodings are supported. A code comment says "GFF3 attributes have specific percent encoding rules, the list below are required, all others are forbidden." Spaces are not included in the list of encodings, which seems to differ from the behavior of standalone IGV. In fact, IGV also properly decodes the "plus" sign which I had encoded in these as well. Here is a (different) feature from the same file and track in standalone IGV:

![Screenshot_2023-03-28_04-52-14](https://user-images.githubusercontent.com/11667655/228199543-88545ca8-615e-4672-ae8b-b1ead58c06e8.png)

Which behavior is "correct?"

**Comment by jrobinso** [comment]
I will look into it.

**Comment by jvolkening** [comment]
Following up... as far as I can tell, the IGV app just passes encoded GFF attributes to a generic URL-decoding function (in the `decodeURL()` method in `src/main/java/org/broad/igv/util/StringUtils.java`), without setting any limit on what characters can be encoded.

I imagine this might be a thorny issue, because a specification (GFF3) which is *always* tab-delimited and specifies that spaces *cannot* be encoded is being fitted into another format (BED) which allows space-delimited fields. Since these are BED files after all and are only using the GFF3 tag format to display metadata in IGV, it would seem to make sense to enforce the actual BED spec (allow whitespace delimiting) and relax the GFF3 tag spec (allow for URL-encoding any characters) in parsing BED only.

**Comment by jrobinso** [comment]
@jvolkening I just came on to say essentially the same thing.   The semicolon and = delimiters should of course not be encoded.   Leave this open until I can get to this, but the plan is to just URL decode the attribute values.

**Comment by jvolkening** [comment]
Fixed by #1622
