### ISSUE TITLE
quotes should not be stripped from GFF3 attribute values

### ISSUE THREAD

**Issue by jvolkening** [igvteam/igv.js#1623]
The GFF3 spec states:

>  Attribute values do not need to be and should not be quoted. The quotes should be included as part of the value by parsers and not stripped.

Currently, the igv.js code strips surrounding quotes from all flavors of GFF/GTF-like attributes. This should probably be modified to retain the quotes in the case of GFF3.

**Comment by jrobinso** [comment]
Done.  Early versions of GFF required quotes around column 9 attribute values.

**Comment by jvolkening** [comment]
Thanks!
