### ISSUE TITLE
Wiki references nonexistent showCursorTrackGuide option

### ISSUE THREAD

**Issue by jvolkening** [igvteam/igv.js#1624]
The wiki section for API 2.0 Browser Creation references an option called `showCursorTrackGuide`. It looks like the code recognizes either `showCursorGuide` or `showCursorTrackingGuide`.

**Comment by jrobinso** [comment]
Also, BTW, the .genome format was deprecated and replaced with "json" as of release 2.11.    .genome files are still supported for backward compatibility.

https://github.com/igvteam/igv/wiki/JSON-Genome-Format
