### ISSUE TITLE
search webservice unavailable

### ISSUE THREAD

**Issue by jessakay** [igvteam/igv.js#1625]
Hello, it seems that searching by gene symbol is unavailable today due to the webservice being down (as attached) 
<img width="547" alt="Screen Shot 2023-03-31 at 3 14 21 PM" src="https://user-images.githubusercontent.com/59965498/229242383-29999826-22a6-40d8-a19a-85a7732994ab.png">
Could you please help me understand if it's an issue on my end or is the server generally down for maintenance?

**Comment by jrobinso** [comment]
There was a server problem this is fixed now.
