### ISSUE TITLE
Feature request | Enable custom bed/file formats

### ISSUE THREAD

**Issue by NizanHellman** [igvteam/igv.js#1626]
We would like to be able to support other custom bed formats. (For example[ Illumina's Dragen ROH bed](https://support-docs.illumina.com/SW/DRAGEN_v40/Content/SW/ROHCaller.htm))

We would like to extend the FileFormats available [here](https://github.com/igvteam/igv.js/blob/master/js/util/fileFormats.js) without changing igv.js. Is it possible to export it to the TrackUtils object.

Example of a Illumina's Dragen ROH bed:
`Chromosome Start End Score #Homozygous #Heterozygous`

This can be easily implemented by exporting FileFormats in TrackUtils. I think a PR should add example/docs for using it.
I would submit a PR if you agree with the approach.

**Comment by jrobinso** [comment]
Yes in principle, that would be helpful.   Thanks.

**Comment by NizanHellman** [comment]
@jrobinso 
Can you please upload this file to this location and share the link?
Please change the file extension to be .bed (Example.dragen.roh.bed)
I want to use this file for an example and a test.

location: https://s3.amazonaws.com/igv.org.demo
[Example.dragen.roh.txt](https://github.com/igvteam/igv.js/files/11415519/Example.dragen.roh.txt)

**Comment by jrobinso** [comment]
@NizanHellman This all looks good but I'm traveling this week,  I'll get to the PR asap.   The only change I might make is to add a method on igv, maybe "igv.registerFileFormat",  to avoid exposing TrackUtils.   Yes I know its exposed already but not part of the published API.

**Comment by NizanHellman** [comment]
Hi @jrobinso, Hope you are having fun on your travelling.
I updated the PR according to your recommendation.

**Comment by NizanHellman** [comment]
Hi @jrobinso 
Any update on this?

**Comment by jrobinso** [comment]
Sorry not yet, its on my list,  I should get to it by the end of the week.

**Comment by NizanHellman** [comment]
Closing as the PR was merged 

Example: https://github.com/igvteam/igv.js/blob/master/examples/custom-file-format.html
