### ISSUE TITLE
Gaps in RNA-Seq coverage tracks

### ISSUE THREAD

**Issue by cmcninch** [igvteam/igv.js#1627]
Hello,

I have a set of RNA-Seq bigWig files that display with gaps in their coverages but display without these gaps on desktop IGV using default settings. Any thoughts on why the coverage gaps exist?

**example of coverage gaps**
<img width="508" alt="image" src="https://user-images.githubusercontent.com/10406011/230956771-03ba1dbc-2e3f-4791-9d15-329df039a6fa.png">

**desktop igv view without coverage gaps**
<img width="485" alt="image" src="https://user-images.githubusercontent.com/10406011/230956807-20b5104f-ea3f-4167-ac4d-f23f7f8b355b.png">

**Comment by jrobinso** [comment]
The top and bottom pictures aren't comparable, try comparing for the same region.

**Comment by jrobinso** [comment]
Hi, I'm not sure what the question is.   Are you suggesting IGV desktop and igv.js are displaying the same bigwig file, with the same settings (in particular data range),  differently?   That would be surprising.    If so could you narrow your screenshots down to that, or point out what track you are asking about and verify its the same?  Also check the display settings.

**Comment by jrobinso** [comment]
Making a leap here, and guessing you are comparing the bottom bigwig track from igv.js with the top track in igv desktop.  I note the data range (scale) in igv.js is something like 0 - 86 million.   The I can't read it, but the scale in igv desktp is something like 0-168.    Set them to the same value and I think you'll see the same thing.   Do you have autoscale on in igv-desktop?

**Comment by cmcninch** [comment]
Hello,

My apologies for not effectively describing what I shared in the last set of screenshots or the main question.

The top track from igv.js is using the same input bigWig file as the track shown in igv desktop. The bottom track from igv.js is a bigWig file created from the aggregate counts of a cohort of 100s of GTEx muscle samples. The top track from igv.js is a bigWig file created by taking the counts in the aggregate bigWig file in the bottom track and dividing by the number of samples in the cohort, generating an averaged bigWig file.

The question is two-fold:

1) Why is the top track from igv.js discontinuous (has gaps / is striped / not solidly filled in), whereas the bottom track from igv.js is solidly filled in, though these files are seemingly in the same format and perfectly correlated? (Though the only difference we are aware of is the averaged file is composed of decimal, rather than whole, numbers.)

2) Why is the top track from igv.js discontinuous (has gaps / is striped / not solidly filled in), whereas the track in IGV desktop is solidly filled in, though these files are the same?

**Comment by jrobinso** [comment]
1.  RE the fill color (the stripes),   I'm not sure, if you could share that track and its specific settings I will investigate.   These are different programs with completely different code bases (obviously),  colors and track styles can differ.
2.  This is an easy one, as I pointed out in the top tracks you have a data scale that span millions,  in the bottom track the data scale is 0-168.    Again,  set the data scales to the same values to compare.     A value of, for example, 30 becomes zero when scaled for display if the max value is a million,  but is very visible if the max value is 168.

**Comment by cmcninch** [comment]
Hello,

For both questions, when I referred to gaps I had intended to mean the striping within exon boundaries. So, 1 & 2 are indeed related to the same problem. Essentially, striping occurs only in igv.js and not desktop IGV for that Averaged (float value containing) bigWig.

For sharing the igv.js track, I was hoping I could pass along the configuration settings for the coverage track and the 2 bigWigs from that last igv.js screenshot (Aggregated counts & Averaged counts). Would that be helpful/sufficient?

The coverage track settings were:

export const COVERAGE_TRACK_OPTIONS = {
  format: 'bigwig',
  height: 170,
}

Thanks for your help!

**Comment by jrobinso** [comment]
I would need the file itself, there is something particular about this file since we don't see that striped pattern generally.

I still don't see what you are trying to distinguish in the repeated question (2), but maybe that's not important.

Also, you didn't specify but I am assuming you are using the latest igv.js release.

**Comment by cmcninch** [comment]
Here is a link to download the bigWig for the file giving the problems.

https://drive.google.com/file/d/1GBZNwWGGfgi4NUFxYyx-dNy8OHzk3QIu/view?usp=sharing

I'm using igv.js v2.13.6

**Comment by jrobinso** [comment]
I don't see this behavior with the latest release (2.15.3).    Screenshot below, also a URL to an igv-webapp session

https://tinyurl.com/2bbgcyla

<img width="1674" alt="Screen Shot 2023-04-12 at 2 41 29 PM" src="https://user-images.githubusercontent.com/933148/231592718-ac8adad6-f8c6-4a2d-803f-b27d9df267d5.png">

**Comment by cmcninch** [comment]
When I zoom in further on a GAPDH exon using the igv-webapp session you shared, it looks like the striping is present.
![Screen Shot 2023-04-13 at 8 18 00 AM](https://user-images.githubusercontent.com/10406011/231771046-752147bd-74a8-4b1d-b4b8-4b5a220fda69.png)

**Comment by jrobinso** [comment]
OK zooming in was the key.   There was a bug parsing fixed step bigwig data.   With span=1,  the width of the bar was zero basepairs, resulting in 1 pixel max width on the screen.  When zoomed out this isn't noticeable.  Zooming into you start to see aliasing then actual gaps.    This will be fixed in the next release,  in the next few days.

**Comment by cmcninch** [comment]
Thanks for your efforts on this issue and creating and maintaining such a useful tool!

**Comment by jrobinso** [comment]
I'm glad we got to the bottom of this.   I will update here when the fix is released.

**Comment by jrobinso** [comment]
This is now fixed in igv.js release 2.15.4
