### ISSUE TITLE
npm install failing due to invalid repository name

### ISSUE THREAD

**Issue by cchu70** [igvteam/igv.js#1629]
`npm install` failed and printed the following error.
```
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com//jrobinso/hdf5-indexed-reader.git
npm ERR! Warning: Permanently added the ECDSA host key for IP address '140.82.113.3' to the list of known hosts.
npm ERR! fatal: remote error: 
npm ERR!   /jrobinso/hdf5-indexed-reader is not a valid repository name
npm ERR!   Visit https://support.github.com/ for help
```

My local fix was to update this line in the `package.json` file by removing the leading `/`: https://github.com/igvteam/igv.js/blob/e2b289d82a5119427012acda5136444ca64fb8ff/package.json#L54

My git version is 2.30.2 and npm version is 7.5.2. The igv.js version I am using was 2.15.3, and the current commit I am using is  9f26b5c7f07d7b9e4b112e36b91c652af786eb53 "testing"

**Comment by jrobinso** [comment]
That's a rather old version of NPM, I am not able to reproduce the error with 9.5.1.    Nevertheless the leading slash is not needed, and looks like a mistake, so I will remove it.
