### ISSUE TITLE
Precomputing (and displaying) the alignment coverage track

### ISSUE THREAD

**Issue by SchwarzMarek** [igvteam/igv.js#1632]
Hello,

I have a question on how to precompute and show the coverage track (with proportion occurrence of particular base at each position) that can be shown when displaying alignments track. I apologize if this is described somewhere, I've only found issue #1006 which somewhat touches on this.

Based on it, I've used the (AFAIK undocumented) support for `.tdf` format prepared with `igvtools count` and tried to use it to display the data. In the attached image four tracks and annotation are visible.

- `tdf` produced by `igvtools count -w 1`
- `tdf_bases` produced by `igvtools count -w 1 --bases`
- `mapping` computed by `igv.js` from `.bam` file
- `variants` track with called variants

![image](https://user-images.githubusercontent.com/25510773/234597580-94ffa9d0-744c-4a2e-9ccd-eb44d2ffa0f9.png)

Is there a way how to precompute and show enhanced "coverage" track similar (what I really care about is showing support for the called variants, without loading the BAM by default) to how the igv.js does it (showing the blue strip in the coverage track)? If this is available through other formats I'm happy to use them.

igv.js version used is 2.15.4 (latest)

If this is documented somewhere, I haven't found it and I apologize for raising the issue.
Thanks
Best regards

**Comment by SchwarzMarek** [comment]
Thank you for the fast response. I assumed that it would be possible to precompute and show the mismatches, since the igv.js can display them from the `bam`. 

Feel free to close this issue, if you don't plan to support this functionality in the near future :). 

Thanks for the igv.js

**Comment by jrobinso** [comment]
This would be quite difficult in practice.
