### ISSUE TITLE
Allow comment in fasta header?

### ISSUE THREAD

**Issue by hiroshisuga** [igvteam/igv.js#1634]
Sometimes we write a Fasta header line with comment like:
`>Chromosome_1 (this is the first chromosome)`
, expecting the text after the first space will be ignored. 

However, the current implementation of igv does not allow it; the "(this is the first chromosome)" text is added to the sequence, instead of simply being ignored.

Is it an intended design?
(I'm using 2.15.1)

**Comment by jrobinso** [comment]
That shouldn't happen, in fact many of our fastas have comments separated by whitespace.   Could you share a small example fasta causing this problem.  You can zip it up and attach it here.

The chromosome is parsed from lines starting with ">" as follows

```
nextLine.substring(1).split("\\s+")[0];
```

**Comment by hiroshisuga** [comment]
Thanks for the comment, which hits me what was actually the problem.

I need to remove the fai file in the same directory. 

The fai is automatically generated by igv and I do not sometimes remember that I have to remove it when I change the fasta header. 
Would it be an option to check the timestamp of fasta file and fai file and automatically remove (or re-generate) fai file when its timestamp is older than fasta file?

**Comment by hiroshisuga** [comment]
However, it does not really make sense to me why leaving the old fai file leads to the mis-addition of the comment to the sequence...
In my IGV the sequence was like:
(this is chromosome 1) ATGCATGC.....
so all the coordinates of gtf annotations slipped off..

**Comment by jrobinso** [comment]
An fai file could cause this problem as the file position of the start of the sequence could differ 

We will not be removing a file on the users computer based on a timestamp.     Its uncommon to rely on IGV to generate an .fai file, this is not a common use case.  Indexes are more commonly created by other tools such as samtools.
