### ISSUE TITLE
HEAD requests for content length?

### ISSUE THREAD

**Issue by dnil** [igvteam/igv.js#1640]
Hi! As usual, thanks a bunch for the fantastic resource!

We ran into an issue with the 2.15.5 update, that I think is related to the igv-utils versions bump to 1.4.5. 

We use igv.js embedded in a Flask app, and serve alignment tracks via GET header Range requests to IGV.js using a different endpoint in the same app, with everything working nominally up to version 2.15.4. We now start seeing HEAD requests for content length, presumably from around here https://github.com/igvteam/igv-utils/blob/2e36e1e0ed15fed5b7ee439333cd94cb04d6ea23/src/igvxhr.js#LL122C4-L122C4, and I note an exception to a couple of signed URLs.

```
2023-05-03 08:52:11 macbook-pro-3.gaia.sll.se werkzeug[77061] INFO 127.0.0.1 - - [03/May/2023 08:52:11] "HEAD /remote/static?file=%2FUsers%2Fdannil%2Fsandbox%2Fscout%2Fscout%2Fdemo%2Freduced_mt.bam HTTP/1.1" 500 -
```
![Screenshot 2023-05-03 at 08 54 45](https://user-images.githubusercontent.com/758570/235849618-9cb1cd8a-962d-442f-81e4-329c2a018f31.png)
![Screenshot 2023-05-03 at 08 52 59](https://user-images.githubusercontent.com/758570/235849641-b72c25bf-9239-4111-84af-3519416d4e8e.png)

I would be grateful for some info here! Is the signed feature something we could introduce to our file "server" part, or should we implement a `HEAD` endpoint? Is the intention is to return just exactly the header that we would for the corresponding `GET` request?  If not, is it documented somewhere so we can read up? Thanks again!

**Comment by jrobinso** [comment]
Hmm, this is an unintended consequence of a fix for another issue. I will need to rethink that, or perhaps make this optional behavior.   I should have a fix soon,  in the meantime I suggest you stick with v2.15.4.

The problem this addresses is making range requests that extend beyond content length,  that is that overlap the end position of the file.  Well behaving servers should return only the portion of the request that should be filled.   However some important endpoints either (1) fail, or (2) return the entire file.    This is primarily a problem with bigwig and BAM files near the end of the file.

**Comment by jrobinso** [comment]
Hi all,  I rolled back this ill-advised solution in igv-utils,  the corresponding igv.js release is 2.15.6.   I'll be implementing a more targeted solution for the original problem,  not involving HEAD requests for the next igv.js release.

So to be clear igv.js 2.15.6 does not use HEAD requests.
