### ISSUE TITLE
It takes forever to load interaction track

### ISSUE THREAD

**Issue by YOUZhen93** [igvteam/igv.js#1642]
Hi,

I am using igvapp to visualize ChIA-PET data, but it takes roughly 20 seconds to load a 2 million lines bedpe file (primary assembly of hg38, ~100 Mb in file size). I've tried both plain bedpe and bgzip compressed bedpe, but they consumed the same time. With bgzip compression and tabix indexing, it only takes a few seconds to load the interactions, but the Achilles' heel of this way is that you need to zoom in to a small region to see the arcs. However, sometimes we would like to visualize the interactions in a over 1 million bp window. Are there any tricks to improve the performance of loading interactions? 

Best,
ZY

**Comment by jrobinso** [comment]
First, when you say you are using the "igvapp" are you refererring to https://igv.org/app, or github project igv-webapp?  If so I'll transfer this issue.

Try bgzip  + tabix with a large visibility window.  in fact a visibility window big enough for the entire chromosome will probably work fine.   A shortcut is to set visibility window to -1,  which is interepreted to load entire chromosomes.   Loading without an index loads the entire file.

**Comment by jrobinso** [comment]
@YOUZhen93 did you try my suggestion?
