### ISSUE TITLE
Exons of Transcript with no CDS are displayed as non-UTR exons

### ISSUE THREAD

**Issue by KleinSamuel** [igvteam/igv.js#1647]
Hello,

when loading a FeatureTrack from GTF, all exons of a transcript that has no CDS are displayed as non-UTR exons (meaning they have the full height such as protein coding exons).

I am not sure if this is a bug or intended but for me it was irritating that exons of a non-protein coding transcript are displayed the same way as protein coding exons are.

In the finish() function (GFFTranscript class), all exons that are not within the CDS region are tagged as UTR.
But this happens only if the "cdStart" attribute of the transcript is set, which is obviously not true for non-coding transcripts.
A possible fix could therefore be to automatically add the "exon.utr = true" attribute to all exons in such cases.

I will open a PR after you confirmed that this is indeed a bug.

**Comment by jrobinso** [comment]
This is not a bug, it is the IGV (and I think UCSC) display convention that features are drawn as blocks.   There are 2 exceptions,  introns are drawn as thin lines and UTRs of coding genes are drawn as 1/2 height blocks.

**Comment by KleinSamuel** [comment]
I figured that I missed some details, thanks for the information.
