### ISSUE TITLE
can't open an example of igv.js

### ISSUE THREAD

**Issue by hurchu** [igvteam/igv.js#166]
Hi,

This morning, I can't view any examples listed in igv.js. Does anybody know what's going on? Last Friday, everything is OK. But this morning, I can't view my own bam, neither igv example.

The following two links just display empty.
http://igv.org/web/demo/ga4gh-demo.html
http://igv.org/web/examples/bam.html

Thanks!

**Comment by jrobinso** [comment]
Apologies,  thanks for the report.  I'll look into it.

Jim

**Comment by jrobinso** [comment]
Hi, this is mostly fixed.  The ga4gh is not returning any samples,  I'm not sure if its a server-side problem or not.

**Comment by hurchu** [comment]
Hi Jim,

Thank you very much!

Can I view this example now?
http://igv.org/web/examples/bam.html

On Mon, Mar 28, 2016 at 10:27 AM, Jim Robinson <notifications@github.com>
wrote:

> Hi, this is mostly fixed. The ga4gh is not returning any samples, I'm not
> sure if its a server-side problem or not.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/igvteam/igv.js/issues/166#issuecomment-202472193>
>



-- 
Junfei Zhu

**Comment by jrobinso** [comment]
It works for me

**Comment by hurchu** [comment]
Thanks, Jim!
