### ISSUE TITLE
Does 'igv' support typescript?

### ISSUE THREAD

**Issue by lk101** [igvteam/igv.js#1663]
Does IGV already support or have plans to support typescript 5?

![image](https://github.com/igvteam/igv.js/assets/26990911/2e979d60-6c5e-4ffe-af90-198e71f27641)

**Comment by jrobinso** [comment]
Hi, no it doesn't, it is plain javascript, specifically client (web browser) javascript.  Raw imports such as 

```
import igv from 'igv'
```

are not supported in browsers at this time, unfortunately.      I do not know what you mean by "support typescript".

**Comment by hongiiv** [comment]
<img width="1074" alt="image" src="https://github.com/igvteam/igv.js/assets/502944/04014a2c-b76e-408b-9b80-87a70c35df60">

I have a same message in vscode editor (it's only vscode message). but typescript code is working good.

**Comment by holtgrewe** [comment]
I'm using it like this:

```typescript
// @ts-nocheck
import igv from 'igv'
```
