### ISSUE TITLE
Wiki formatting issue with `$` (accidental mathjax)

### ISSUE THREAD

**Issue by bartgrantham** [igvteam/igv.js#1667]
The description of the `url` parameter in the search object details on this page has a formatting issue where the unescaped dollar signs are being interpreted by github as mathjax: https://github.com/igvteam/igv.js/wiki/Browser-Creation#search-object-details.

Example: $FEATURE$ instead of `$FEATURE$`

Besides github rendering the text oddly, because there's no example of what the query looks like I couldn't tell what was wrong with my search object until I looked at the source.  If this is a common idiom in igv.js this documentation bug may be in other places, too.

**Comment by helgathorv** [comment]
Thanks for letting us know. The Browser-Creation page has been corrected.
