### ISSUE TITLE
Issue with dynamic features colors

### ISSUE THREAD

**Issue by mcjmigdal** [igvteam/igv.js#1669]
Hi, first of all thanks for this fantastic project!

In the app I am developing I am using the following code to allow coloring GFF features by their attributes values. This had been working well, but stopped recently. However I do not see any relevant changes on my side. Is there anything that could have changed on your side or maybe you have some ideas how I could get to the bottom of this?

```
export function setIGVColorBy(trackName, featureName) {
  const track = igv.browser.findTracks("name", trackName)[0];
  if (featureName) {
    track.color = function (feature) {
      const attr = feature.getAttributeValue(featureName);
      const color = stringToColor(attr);
      return color
    };
  } else {
    track.color = undefined;
  };
  track.trackView.repaintViews();
};
```

In the console I am getting

```
Uncaught TypeError: feature.getAttributeValue is not a function
```

I am using `https://cdn.jsdelivr.net/npm/igv@2.15.8/dist/igv.min.js`

**Comment by jrobinso** [comment]
Do you know at what igv.js version this stopped working?

**Comment by jrobinso** [comment]
If you could post a full test case I will look at it, but looking at your code its possible a non-gff track is being found.    The "getAttributeValue" function is only defined on GFF features.  You could protect for this by testing for the function

``` typeof feature.getAttributeValue === 'function'```

**Comment by jrobinso** [comment]
OK I was able to reproduce this in "whole genome view".  The features in whole genome view are actually wrappers, and the wrapper is getting passed to the color function.   I will fix this in the next release, but in the meantime you can fix it in your function by unwrapping as follows.   Of course this might not be your issue.

```
track.color = function (f) {
    const feature = f._f || f 
```

**Comment by mcjmigdal** [comment]
Thank you for looking into this! I missed your last comment and was about to get back with reproducible example. 

You are right, this is what is happening for me. I did not realized it, but I actually started to use "whole genome view" for testing recently :)
Thanks a lot! I guess the issue can be closed.
