### ISSUE TITLE
can not my own data

### ISSUE THREAD

**Issue by patidarr** [igvteam/igv.js#167]
Hi,

I copied over the bam.html from the igv.org and saved it to server, and when I tried it in browser I can see the reads from the BodyMap data, but when I copied over the bam to my local server and added it as extra track I am getting 
`
invalid literal/length code
2igv-beta.js:1090 # chunks = 7
`

I know you wont be able to see my server but I just added following 4 lines to the bam.html
`
                        {
                            url: 'https://fr-s-bsg-onc-d.ncifcrf.gov/onco.sandbox2/public/data/annotations/hg19/accepted_hits.bam',
                            name: 'Frederick'
                        },
`
Thanks,

**Comment by jrobinso** [comment]
Hi,

Are you sure the bam file is valid?   It might not have gotten copied 
completely.   Also, that is a large bam and probably shouldn't be copied 
in total.  There are some small example bams in the igv.js repostitory 
test directory.

If you verify the bam is ok,  vould you use Chrome's developer tools to 
get more details on the errors?  Use the network tab,  and look at the 
request and response.

Jim

**Comment by patidarr** [comment]
Hi Jim,

The bam file is ok, I also tried my own bam files (which works on desktop IGV) they are not working in this application, hence I copied this bam from broad. 

here is the request header.
`
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,hi;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Cookie:cartalyst_sentry=eyJpdiI6IlhDaGN6QzlZck1lQ3ZXdFQxWXEwQ2c9PSIsInZhbHVlIjoic3Fsa0J1dlBQQ09iQnRaY1hSM0dVZjNLMnRFQTZUcUUzYjBpWDdnMTBqY2YzYVRTZ0M3Z3NjeFRUb2xwZm1CZ3ZhcElkRVB4eEV2R1Rha2xoVGJIK2pMenVLRHN2U3h6aDVWcXphTDNHNmFGTXhvbE5BajRzUWF0cGxWK0JuYzgiLCJtYWMiOiIwYjA2YTI3YTRiODRiMTFkZGJhNGU4N2JmMThiMjQ5Y2ZhODZhMjEwYjRjZmZhZTBkOGVlZDJlOGNkOWFkZTNhIn0%3D; _ga=GA1.2.190198909.1402677796; laravel_session=eyJpdiI6IjJZbzBmN1ZGMXV1MnpreWVVTmtBZkE9PSIsInZhbHVlIjoiWWpJNkQ1K2VmaDcyYjNpNmNmbTNCb3FkN2VtdzhcL290dnFGYmVpZlF0WXQ0bllrXC9GUU1uVEVBNVNPb3hCeWI2ZmZtcmRJS2REODJuTko1ZVlzSHhaZz09IiwibWFjIjoiNjlhMjJiNzg2MjAyNTY4OTRiYjRjODFkODliZDZkMjc5MGRhMTJhY2UxYzYwMjU4NTEyZmYzOGFkNTAwODQ3YSJ9; d6e0b9b9aae687f02377dac471b021f01193eaf1=eyJpdiI6InQxQkRHNEdyUXhXUzI4WGhCS2JXRWc9PSIsInZhbHVlIjoicEVYWHRkOEhHeGZDTFpzVkF1TUJhUlhXN0V6TlpWXC9iWTZiWmRod2tTN1lJbkNZd084Q2FLTGZ4ZWdGSm9pbzBQdFo3RVRmeFlPSmlkamxxMkYybnFMXC9VWWlhYnFzYWhSNDBUREpicE1VRkFxU0NEZHFVemhpcUFMVjY3UTg3aThOUFViVmcrTXB5N0h3VmN1VndoalVhYndsRkhRQ2QrSUYxeGNjQ0xwMkpwbTh6bmVlbjVoME9zMFhBUWVsU2R2VzhoOEY3ZHUyRFYxZmxUemhWZnRqbTYyd2RYcnZjUHJYdzBoSENYVHZTN244SlwvVW9PZFF3QjV4SVVFNlwvZ2ErNFBjREVPRjEzYzNmT01ueU5yakU0ck8rK0p6QlFhWitZM1BRaWduUjFKaGFJYUZIVWRqQ0dFRjJxUU8wT3Z4d1M0Y1FmNnBLUGNBVWhBcTBvaWFYVVRTcGU2MXpjWkhpSkpBQUJOUHVvXC91cHFPRlFQK0hBc1krdm9uZ3hVNlwvd1pKR1lwcEtFR1pIMFVwblp0TzZCVVZCYTZUdGt5aG5BRlhaNHFrSTBpUXpNdWdaWHFHenRwR2o0N3hcL1dNNmVjcGxMdkhHRkxrZmpjVFwvM3NrZUFkZz09IiwibWFjIjoiMGM5ZTE4MGU2YjViODA0YTYwMzQ3NjUxYzE1MTdlODg4MWJjN2FkNzAxOTA3MGEzZjRhM2EzNDY1ZDE2ZTA4OSJ9
Host:fr-s-bsg-onc-d.ncifcrf.gov
Pragma:no-cache
Range:bytes=0-66400
Referer:https://fr-s-bsg-onc-d.ncifcrf.gov/onco.sandbox2/public/bam.html
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
`
 and few lines from response.
BAMi@HD	VN:1.0	SO:sorted
@SQ	SN:chr1	LN:249250621
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr2	LN:243199373
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chr3	LN:198022430
@SQ	SN:chr4	LN:191154276
@SQ	SN:chr5	LN:180915260
@SQ	SN:chr6	LN:171115067
@SQ	SN:chr7	LN:159138663
@SQ	SN:chr8	LN:146364022
@SQ	SN:chr9	LN:141213431
@SQ	SN:chrM	LN:16571
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@PG	ID:TopHat	VN:1.1.4	CL:/home/radon00/cole/bin/tophat -p 4 -a 5 -F 0.0 -r 100 --tmp-dir=/broad/shptmp/nmcabili/rnaseq/human/HBM_hg19/Alignments/brain_50 -o /seq/rinnlab/Moran/HBM_hg19/Alignments/brain_50 --no-novel-juncs -j /seq/rinnlab/Moran/HBM_hg19/Junctions/HBM+GencodeV4+RinnNov10.juncs /seq/rinnscratch/cole/bowtie_indexes/hg19/hg19-male /broad/shptmp/nmcabili/rnaseq/human/HBM/50bp/FCB/s_3_1_sequence.txt /broad/shptmp/nmcabili/rnaseq/human/HBM/50bp/FCB/s_3_2_sequence.txt
chr1=CÛchr10chr114	chr12÷júchr13VZÝchr14$fchr15@chr16A´bchr17ÊðÖchr18@]§chr19<chr2í~chr20p±Áchr21ggÞchr22vØchr3Íchr4dÈdchr5<È
chr6;3
chr7gC|	chr8vV¹chr9÷¾jchrM»@chrX =A	chrYþ÷ÿBC§@Ý½}%KvØoÞÌÀ.xU¾àfÖöô½®îºÕÕUùy«Á3ÝÕJzFìúEkëuq-id
Ùf1þgñ|lYÙÉØÈxæ=!³ÆvÖ6ÀØÐ÷ÞÈ{3«"»_Ýª¬öøóñ;'Î9ñ±ÍsqöàÁã¯¿òàûxí»¯=k>o>üúøøüzþÏßè8Øgðº±ë2Â¾ÆyðèÕN.oÄlÆù±-bq+äz¹\ÈÕÐ£~ã&y¨¯õ/>ðuÕ+¸©^ùû--.ÐòDÑ÷Úß?¿hAú<S8±KóÀ¿ùîÈ»×kýúQÝQÁ¨ÔÏõjèþbã]ÈÆ_mÙH5ß©ùOüõw
/3%±Ë¨CãÈ
ô:ËÙÑÉ\Ü,''7âööDÞ®×K.g{(YÙ7¡[ç{ÞÈÁ7h/&ËÁa-½õ³ZvtÔ×ûn¾O¶´|øè{é{]ÑwP|\C
r@<Ïmé{ñðf9ãÅòæn¹8>­ï/ïÖüîn>?==}Ï)Í2I|æ{vß]Uÿëÿûp½Õ×¿þàÿ|åÁ§
zO§ÐK=XÊÁx-Åó!ã'iYËº®*!eçyVURHµ¸\dKÁá(DÑQüÀFq·Âß¢Wø¹Ï^ì/&.¡±ç1/hé½¹;¾»ïîÄüfy4ë#±Xs~·¢%@µ«?×Uýºî$À¤7@zÿöüÊ÷~Ò ­¡kz¿e*½wÏînçK¾~x·^r!×w\>äKÇ«ªÆKIæÍ°=æ4Éëz"a$	m%vÞo4èý#@ï¤÷{5½¿÷j½4ö]×Asié]®7s±¼»½[/·w·ë»ùzýünmQ! vëEk¤¹¾ï1éý'êéEÚz?¤éE&ÑËÅñßÈÙÝÝb
r gåÙlýÁýÚ%õÃËàêôììlÞ®ï½ïz?×ÒöçÈÇ¯Nð4}J££­£Ïæâèxv»¯åíÃÅân¾\Ís¹I±Xñ£2å)/Dæ¢®¯Á²U°¤Iî1F<÷ê"gI1	VD&(ðÂën+®Í]xÉÕ_úº¯|oç8Ò9?¢wá7È]ðÂ8dè=B/
ÂÎqåÝ¬ëÅòf¹x¾XÏÐïçËÓÊÙuºØêeUËXCQëIð+/G`(Ãà2-a}¹¨ª¢lé[«ôg±Aà[&J.pº¾+èD­`8|=_Þ¬ÁÞÎKe!ò$²"\£©DÅ+ø
Úªâê¢Ê3B÷$Ã'&yUUüÉë¬¶	Æ¿ü_ùÞkÙúYÒ9ìâaÆQä§ÃEÇÇ9ÀHÏO±l6èìÍüHÌwùÂr:­rAñ¼cð§y\<½8?¿¼<
ð99yüäñã'O´ÛÔðîgÉDxJë4òc×§$ÀÆº´:M9Þ2ó¸B7 À|z°O$Iò$
&lâ®üÙwÁd-=ë;	,Ü®g¥\sy{4[/ïdÛ'·{õ+»ÞÀm-$°PÐéie¤¨+´#Rük+M;oó~çÍû8äÝÁ¼£4ô[úÇóÅóÛãwËùÜäúv½ßÜÍ
8´rÊöõX¹¥ïUSý>ûû¿ò½Uù% ÷É+$ÖaÄGßíW¤³üv)Ï//À¨ÜÜÞÎác½}p[ÿ^æ±ÁÖÿ±W|Î`ëñ¶(`*uÒ÷gWüQãl*cý«­ýÀ½ªcÈþÙ -rõIC®úànp-~ßð#_Ô,à`®|¿4X>¹PfC¸p}ª¥í»N¸z¨ø!ºO[AQ!v`ðãuÑØ<ºCä»¼ß.aíFærùü¢î8L¢$N¬ l/"A$~Yq@lÁùk{ìÅèDì"0Ï½uAúR?¿^ÎnoîÏøíb¾àpÄìÇÝÍÅ°I-VÜ¨XR½ØVëÎ2µ-HÂ½þÅëý6à7ÛÐ#àïÞg¬ÛððîÏJBpq<@k)ë[áyâCDÈ\ç	O,®âóÁ²ÈakècòØ;'¶	îÒÃ~0E{Á°÷*G¤Ý>¿½[/æÇÇïnÄ¨~ø\.sÄv³ÙñÕ#ÔÎHÖhÔ[-Ü;OïÃêF§>Àýl!{¥¾Oÿè+ÞnÙ
Ã.àÜ0$QÈíPÂâäÿn&nogó5ÚÝsÎå
G»»»ÉKÑ2Q+á¯'D%Oã²-Pþ/Î²(,KÉU3[ûÿÞôZóU¬3K#ùòýØ'ÔYèNk^Ï  z¸¸{~wt$ÁCCT¸ßÜÂ~'×1Þ½9- ñÙ5Qa¼Æ»
ãõ¯_+F7 ~çBÄ(®ºSñÁZ´Ö·ã)kP<rézÍß#Wúj¶æü
Ûc`¯eDÐjÏçîvy÷ðùÑlaÃÍÝÂË»H\	Â%I'ü)O(0Q]ð\ðsY% dáM'@G(qU@0Làbvg¬çóÍßHµ®ðt¼ÏL
¿Z?x³~¸¾¹'wwà íðßa_ÀBïÈ?hÀå3âã$Éý?X¼m05É4y°à ò÷Ý`2_ÍÓó¥t9fIÂYæù*}H%YMQbä«CL'lbººqD¢ ¼ ºtëKnÅdëéi1Ãh± ÙàL#U¡%rh£÷ËSz2Õèx¸A!eÑ¤·ÝåÝr)_ëWËA./\E7^îá]xu«_7vátê.ty¡ãÄ.Þ!+>á,É#÷=zØvá¸éÒûdRÞ]/`häÃO}þ¬Að4VÝ¸=x§^êöv-g¥Zl4IÈ$³lË3£ì_~azf`êÝÛL}Á°I§Sm=ÐcS
ÀÏ×Íì5,z¾b$UD»eå«ópç÷³û<ÇâÐñQ(#]c©ðsØåµÏ¶~¦	ìÃ¶/î#¤ßQzÄïôuÐõÿMïÆûðAeGàÇO!0ÀcT®ÓÇÁÃôa¥AÂV¥BY+!g@ÅÓ´ÂüP$©?¼ý~}óDKm	üÒà>?9991ü§V¹8Î(ÍL($ÇÙ·Ã{	ÐsAÝ(báÁ.DN$
ò¢UDI¥@F-rgX<Bá«\Ê¼,áo´ìV>bÐ Ç,pÈºp?'x$K@ß¢ÖªQoéHÐµPÚ¬V	Ê«, Y+Y·lü3\|Ó+îÍFQ®÷²u³\Þ´lÚ$ôÌµ©HEN2¢Cßêú[÷³ÃÖÇ[¶´ÔSäÝQðÔpÓå¹ÊIZäÂ®2ì´{SÒ
#Ì9ïz(,Û¬²¾bUg*+ÙZ÷mæ
Â>d3<8]x×sCôm,N#îµm!û7}]!+ø`

Thanks,
Rajesh

**Comment by patidarr** [comment]
apparently I am having this issue with bam file only, bed and my own vcf works fine.

**Comment by jrobinso** [comment]
What browser are you using?

I would suggest that you check that all your CORS headers are correct, 
but as you are getting a response that looks like a bam that isn't the 
issue.

Are you running from the "beta" js, or a pull from the repository. What 
url are you using to include the igv javascript?

Jim

**Comment by jrobinso** [comment]
Ahh, here's something to check,  are you sure you server supports 
range-byte requests?  I'm guessing it doesn't.  You should be getting 
206 responses for the bam requests, if you are getting 200 it's not 
going to work.   This is something igv.js should check, but doesn't,  to 
give a good error message.   Almost all production servers should 
support range-byte requests,  but some development servers don't.

**Comment by patidarr** [comment]
I am using the igv-beta.js
here is my head section:
`
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css"/>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://igv.org/web/beta/igv-beta.css">
    <link rel="stylesheet" type="text/css" href="css/bam.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://igv.org/web/beta/igv-beta.js"></script>
`
I am confused about the rage byte request.
when I checked the general headers for igv.org bam.html I see following.
`
Request URL:https://data.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam
Request Method:OPTIONS
Status Code:200 OK
Remote Address:69.173.92.29:443
`
for my bam I see 
`
Request URL:https://fr-s-bsg-onc-d.ncifcrf.gov/onco.sandbox2/public/data/annotations/hg19/accepted_hits.bam
Request Method:GET
Status Code:206 Partial Content
Remote Address:129.43.165.68:443
`

**Comment by jrobinso** [comment]
The OPTIONS command will return 200,  GET for a bam should return 206.  
So that looks correct.

**Comment by patidarr** [comment]
But I dont see OPTIONS while loading my bam file. only 2 GET
![image](https://cloud.githubusercontent.com/assets/4172322/14086255/367a23d0-f4f2-11e5-99cc-d53c4fe54326.png)

**Comment by patidarr** [comment]
is https://igv.org/web/beta/igv-beta.js most stable and recent version or I should clone one from github ?

**Comment by jrobinso** [comment]
The most (and only) stable version is here: 
http://igv.org/web/release/0.9.3/.   The beta version is in a lot of 
flux right now but should be stable by the end of this week. Generally 
speaking it is stable but there was a major merge recently.

Re your issue,  I'm not sure it is a version problem as bams load fine 
for me,  and I think you indicated you can load the bodymap from our 
server.

You will only see the OPTIONS request if CORS is involved,  that is if 
your data and webpage are served from different hosts.

I don't have any further ideas at the moment.  A number of people are 
serving BAMs,  its the main use case so far.   I'm traveling and will be 
back in the office on Wednesday,  if its not resolved by then we can 
perhaps add more logging to see what the issue might be.

Jim

**Comment by patidarr** [comment]
I also don't think it has something to do with version but wanted to use a stable version so that all the merges does not cause more errors while I am trying to test this on my server. 

Thanks for the help so far, I will also try to talk to the IT dept here at NCI to see if can give me some insight, 

Regards,
Rajesh

**Comment by jrobinso** [comment]
I suggest the 0.93 release version,  or alternatively make a local copy 
of igv-beta.js so that it's not changing on you.

You might try reading the same bam with the same URL from IGV desktop to 
see if that works.

**Comment by patidarr** [comment]
Now I changed the version to 0.93

I am getting following error while loading the bam to desktop IGV
![image](https://cloud.githubusercontent.com/assets/4172322/14087068/3e6af3cc-f4f6-11e5-92e2-b95d40acc5c5.png)

at the same time I can download the bam file from browser. any reason you think of?

**Comment by jrobinso** [comment]
That would indicate the server is returning a 403.  The igv.log file (in 
the igv folder) might have more details.

Is it possible your browser is setup to use a proxy server?

**Comment by patidarr** [comment]
No my browser is not setup to use a proxy server.

does attached file help in resolving the issue?
[igv.log.txt](https://github.com/igvteam/igv.js/files/192388/igv.log.txt)

**Comment by jrobinso** [comment]
It looks like the 403 error is on the index (.bai) file, not the BAM itself.

On Monday, March 28, 2016, Rajesh Patidar <notifications@github.com> wrote:

> No my browser is not setup to use a proxy server.
>
> does attached file help in resolving the issue?
> igv.log.txt <https://github.com/igvteam/igv.js/files/192388/igv.log.txt>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/igvteam/igv.js/issues/167#issuecomment-202557601>
>


-- 
Sent from Gmail Mobile

**Comment by patidarr** [comment]
Hi Jim,

I asked the IT team and they dont see any error message on server side, does IGV uses a different port? what settings I should ask them to check to make IGV work?

Thanks

**Comment by jrobinso** [comment]
Did you fix the permissions problem with the index file?  IGV does not ouse
any apecial ports..

On Tuesday, March 29, 2016, Rajesh Patidar <notifications@github.com> wrote:

> Hi Jim,
>
> I asked the IT team and they dont see any error message on server side,
> does IGV uses a different port? what settings I should ask them to check to
> make IGV work?
>
> Thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/igvteam/igv.js/issues/167#issuecomment-203068213>
>


-- 
Sent from Gmail Mobile

**Comment by jrobinso** [comment]
I assume you have an index file for the bam.  If you don't that would also
be a problem

On Tuesday, March 29, 2016, James Robinson <jrobinso@broadinstitute.org>
wrote:

> Did you fix the permissions problem with the index file?  IGV does not
> ouse any apecial ports..
>
> On Tuesday, March 29, 2016, Rajesh Patidar <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Hi Jim,
>>
>> I asked the IT team and they dont see any error message on server side,
>> does IGV uses a different port? what settings I should ask them to check to
>> make IGV work?
>>
>> Thanks
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/igvteam/igv.js/issues/167#issuecomment-203068213>
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Comment by patidarr** [comment]
I have index and bam in the same folder and permissions look good to me. i.e. I can wget both of them as well as download using browser, still somehow they can not be loaded in igv desktop app or web app. I copied the bams to another server (not http**s**) and webapp as well as desktop app worked, so some permissions  or port issue I think.

**Comment by jrobinso** [comment]
This doesn’t appear to be an issue with IGV or igv.js, but with that particular server.   IGV does not use any special ports, it makes straightforward http & https requests using the built-in Java and javascript libraries.   In both cases range-byte requests are used.   The one log you sent indicated a permissions problem with the .bai file,  I didn’t see any other errors of note.

BTW 2 conventions are used for index files,  in one they end .bam.bai,  in the other just .bai.   Since IGV can’t know which is used it tries both.   This results in a not-found error for one.   You can eliminate this distracting error by making a copy of your index file and name it with the other convention, they are small.    With igv.js you can explicitly set the indexURL so this step is not needed.

Jim

**Comment by patidarr** [comment]
Yes it is a problem with the server. 

Thanks a lot for looking into this.

Regards,
Rajesh
