### ISSUE TITLE
Warning: Range header ignored for URL: http://localhost:PORT/static/path/*.fasta.  This can have severe performance impacts.

### ISSUE THREAD

**Issue by cryanezMeristem** [igvteam/igv.js#1673]
I'm running IGV.js from my personal Django application in my html and I get the error "Warning: Range header ignored for URL: http://localhost:PORT/static/path/*.fasta.  This can have severe performance impacts." The error occurs when loading the Fastas of the genes of interest that I need to visualize. The error is a JavaScript alert-type message, but I have to accept it every time I load the page in order to view the fasta sequence. Additionally, for some reason, the message appears twice and loads the fasta sequence twice. When loading the respective GFF and VCF files, I don't have any issues. Can someone please help me with this warning so that the message no longer appears? It's worth noting that I encounter this message when running the application with Nginx using Gunicorn as well as with "python manage.py runserver". I will attach the IGV.js JavaScript code as well as the Nginx configuration for reference:

*IGV.js Javascript code:

    <script src="https://cdn.jsdelivr.net/npm/igv@2.15.5/dist/igv.min.js"></script>
    {{gene.gene_id}}
    {{gene.organism.abbr_1}}
    <div id="igv-div"></div>
    <script>
        // Configura y crea el visor IGV.js
        var abbr_1 = "{{gene.organism.abbr_1}}";
        var gid = "{{gene.gene_id}}";
        var fastaPath = "http://localhost:8021/static/genomes/"+ abbr_1 +"_genes_seq.fasta";
        var fastaPathFai = "http://localhost:8021/static/genomes/"+ abbr_1 +"_genes_seq.fasta.fai";
        var vcfPath = "http://localhost:8021/static/genomes/"+ abbr_1 +"_genes_final.vcf";
        var gffPath = "http://localhost:8021/static/genomes/"+ abbr_1 +"_GFFmodified.gff";

        var igvDiv = document.getElementById("igv-div");

        var reference = {
            "id": "Ath",
            "name": gid,
            "fastaURL": fastaPath,
            "indexURL": fastaPathFai,
            "byteRange": true,
            "tracks": [
            {
                "name": "Genome Sequence", 
                "type": "sequence", 
                "format": "fasta", 
                "sourceType": "url", 
                "url": fastaPath, 
                "indexed": true
            }]
        };

        // Configuration for the VCF track
        var vcfTrack = {
            "name": "Alleles Data",
            "type": "variant",
            "format": "vcf",
            "sourceType": "url",
            "url": vcfPath,
        };

        var gffTrack_introns = {
            "type": "annotation",
            "name": "GFF Annotations",
            "url": gffPath,
            "format": "gff3",
            "sourceType": "url",
            "displayMode": "expanded",
             "height": 130,
        };

        var options =
        {
            genome: reference,
            locus: gid,
            tracks: [vcfTrack, gffTrack_introns]
        };

        igv.createBrowser(igvDiv, options)
            .then(function (browser) {
                console.log("Created IGV browser");
            })
    </script>

* Nginx configuration
server {
    listen 8020;  # Puerto que deseas utilizar
    server_name localhost;  # Usamos "localhost" como el servidor

    location / {
        proxy_pass http://127.0.0.1:8021;  # Puerto en el que Gunicorn estará escuchando
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       # proxy_force_ranges on;  # Agregamos esta directiva
       # max_ranges 100;
    }

    location /static/genomes/ {
        alias /home/cyanez/GREGOR/static/genomes/;
        sendfile on;
        expires max;
        add_header Cache-Control "public, max-age=31536000";
        add_header Accept-Ranges bytes;
    }
}

Grateful for your help, Cristian Yáñez

**Comment by jrobinso** [comment]
Actually, if your fasta files are small I think you can work around this by not indexing them.   For the reference try

```
            reference: {
                fastaURL: fastaPath,
                indexed: false
            }
```

For the track try

```
 {
            "name": "Genome Sequence", 
            "type": "sequence", 
            "format": "fasta", 
            "url": fastaPath, 
            "indexed": false
        }]

```


BTW `byteRange` is not an igv.js configuration parameter, and setting `indexed: true` is not a valid, or at least useful, option.   The purpose of the `indexed` property is to tell igv.js that the resource is not indexed, if it is indexed the index url should be provided.   Similarly,  `sourceType: url` is not a valid property.

Let me know if this works.     One theory is your fasta files are so small the server is choosing to ignore the Range header and return the entire file with a 200 status code.   That is not a condition we expected, but it is possible I think.
