### ISSUE TITLE
About [Color By Allele Frequency] 

### ISSUE THREAD

**Issue by zlxd76** [igvteam/igv.js#1674]
Hi, I need to use igv.js to create the same graphics as the IGV APP.
How should I configure it, such as [Color By Allele Frequency] in IGV APP.

**Comment by zlxd76** [comment]
![igv-new](https://github.com/igvteam/igv.js/assets/104063031/33a1cc3d-12b0-4935-81dc-d357cbf53e40)

**Comment by jrobinso** [comment]
That option is not supported in igv.js.

**Comment by zlxd76** [comment]
OK.thanks.
So do you plan to support this option?

**Comment by jrobinso** [comment]
Not at this time.   There are a number of higher priorities.   You can leave this open as a request.
