### ISSUE TITLE
Unwanted request to igv.org for genomes.json despite local genome reference

### ISSUE THREAD

**Issue by zongzi111** [igvteam/igv.js#1678]
I have configured a local genome reference using the following settings:
```
reference: {
    id: "hg19",
    name: "Human (GRCh37/hg19)",
    fastaURL: "http://192.168.11.46:8080/GRCh37.fa",
    indexURL: "http://192.168.11.46:8080/GRCh37.fa.fai",
}
```
However, despite configuring this local reference, there is still a request being made to igv.org for genomes.json. This behavior is unexpected and unwanted. I would like to know how I can prevent this request from being made to igv.org while using the local genome reference.

Please assist me in resolving this issue. Thank you!

**Comment by jrobinso** [comment]
You need to set `genomeList` property as described here:  https://github.com/igvteam/igv.js/wiki/Browser-Creation

I think but am not sure you can provide an empty list (empty array),  if not download  [https://igv.org/genomes/genomes.json](https://igv.org/genomes/genomes.json) and edit out all but one.   I'm not sure we've tested an empty list.

**Comment by jrobinso** [comment]
Actually the doc says an inline array can be used, so this might work

```genomeList: []```

**Comment by jrobinso** [comment]
Apologies, wrong information.  The "genomeList" property to is append to the default list.   To prevent loading the default genome list set

```loadDefaultGenomes: false```

If that doesn't work re-open this issue,  I don't think anyone has asked this before and am not sure its been tested, but from code inspection that should do it.
