### ISSUE TITLE
gene track bed file for hg38?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#168]
In ga4gh-demo.html I see:

 `{url: "//dn7ywbm9isq8j.cloudfront.net/annotations/hg19/genes/gencode.v18.collapsed.bed",`

But no amount of looking and experimenting has led me to hg38 v24 gencode gene annotations.

I'll be grateful for a tip!

 - Paul

**Comment by jrobinso** [comment]
Paul,  are you looking for a url to use with igv.js?   I don't have one
yet, gencode is released as GTF and GFF files and igv.js does not yet
support gene models in those formats.   The v18 bed file was created by
someone at the Broad for another project and I'm just using it.   For IGV
desktop use the URL is.

https://s3.amazonaws.com/igv.broadinstitute.org/data/hg38/gencode.v24.annotation.sorted.gtf.gz

Open an issue on github in the igv.js project for this annotation, if that
is indeed what you are looking for.

Jim

**Comment by paul-shannon** [comment]
Hi Jim,

Belatedly:  I am looking for a gene model track, saw that hg19 collapsed bed, thought it might be just one of many such tracks.  Is there a better approach to creating a build-specific gene track in igv.js?

Thanks!
  
 - Paul

**Comment by jrobinso** [comment]
I'm working on gencode gtf support now, when its ready it will be just a matter of downloading and indexing.  Until then the only option is to find or create a "bed" file.

**Comment by jrobinso** [comment]
Hi, gtf (and gff3) are supported now,  the URL above should work.  These are big files,  I suggest you put a limited on window size (visibilityWindow) such as the example below (set to 10MB).  Also set the indexURL

{
            url: 'https://s3.amazonaws.com/igv.broadinstitute.org/data/hg38/gencode.v24.annotation.sorted.gtf.gz',
            indexURL: 'https://s3.amazonaws.com/igv.broadinstitute.org/data/hg38/gencode.v24.annotation.sorted.gtf.gz.tbi',
            name: 'Gencode v24',
            format: 'gtf',
            visibilityWindow: 10000000
        }

**Comment by paul-shannon** [comment]
Thanks, Jim.  The gtf support works beautifully. 
Two tiny followup questions:

-  I parsed the xml at https://s3.amazonaws.com/igv.broadinstitute.org  to see what else is available, and found lots of repeat masker files.  Will other reference data appear here?  Are there better places to look, some sort of a CDN for genomic data?
-  The gtf track, as best I can tell, does not display gene symbols.  Will that be possible?

Thanks -

 - Paul

**Comment by jrobinso** [comment]
Hi Paul,  a CDN is a good idea,  OTOH our grant pays for access and its really not our mission to provide a database (not budgeted).   So your XML parsing strategy is a good one for now, whatever you find you're welcome to reference.   RE gene symbol,  I assume you mean the common gene name?   Yes I need to do that, slipped my mind,  I'll reopen this for that purpose.   Unfortunately there is no standard for this, but I can copy the byzantine desktop strategy for finding a name as it works most of the time.

**Comment by jrobinso** [comment]
The gff/gtf parser now searches for a name (label) field in column 9 in this order, by default ["Name", "gene_name", "gene", "gene_id", "alias", "locus"].   You can specify a specific field to use for the label in the track configuration, as shown in this example

 {
            url: '../test/data/gff/wustl.gtf',
            name: 'WUSTL gtf',
            format: 'gtf',
            nameField: 'gene_id',
            indexed: false
        }

**Comment by colinhercus** [comment]
I'm looking for a hg38 gtf file that includes genes on the alt_scaffolds. The one from Broad mentioned above only has the main chromosomes.

**Comment by jrobinso** [comment]
Have you tried Gencode?

**Comment by colinhercus** [comment]
Thanks. I hadn't and I just found it there.

It does have different sequence names for the alt_scaffolds then my GRCh38
from

ftp://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/analysisSet

>*chr19_KI270938v1_alt*  AC:KI270938.1  gi:568335998  LN:1066800 *
rg:chr19:54025634-55084318  rl:alt-scaffold*  AS:GRCh38

*KI270938.1*      HAVANA  transcript      15200   38320   .       -
.       gene_id "ENSG00000275962.4";

so looks like I have to change reference fasta as well.

But closer exam shows gencode fasta doesn't have rl: & rg: tags on the
alt_scaffold sequences!

>KI270938.1 HSCHR19_4_CTG3_1

I could write a script to patch this but it would be nice to find a source
for fasta file & gtf file that have consistent sequence names and the rl/rg
tags.

Any ideas on that?

Thanks, Colin

**Comment by jrobinso** [comment]
I haven't done a search, and have a few other things on my plate,  but will
do so.   If you find a consistent fasta / gtf set and send me links I'll
index and upload them with url links to use.

Also, please excuse me I have my head in a lot of different things right
now,  but what are "rl" and "rg" tags?

**Comment by colinhercus** [comment]
Hi Jim,

The rl/rg tags on the alt_scaffold fasta headers give the primary reference
chromosome coordinates that the alt_scaffold is an alternate for.

>chr19_KI270938v1_alt  AC:KI270938.1 gi:568335998 LN:1066800 *
rg:chr19:54025634-55084318 rl:alt-scaffold* AS:GRCh38

So rl tag identifies that the fasta sequence is an alternative scaffold and
the rg tag the region on the main chromosome that it is an alternative for.
Aligners need this information when calculating MAPQ.

I've found another strange difference between Gencode GRCH38 and GoldenPath
GRCH38. Gencode looks like they are using the reverse comlements of the
alt_scaffolds so Gencode >KI270936.1 is the reverse complement of
GoldenPath >chr3_KI270936v1_alt and Gencode gtf coordinates are all
reversed compared to my WES tracks in IGV.

This is evident in UCSC Genome Browser
<https://genome-asia.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr3_KI270936v1_alt%3A1%2D164170&hgsid=471538578_MOOhcyBk8LehrzwnPNZihJehAhdU>
where the Gencode and Refseq tracks are in opposite directions. Look at
MUC4 and MUC20 positions for the two.

Ensemble gtf files also have different sequence names and coordinates for
the genes.

I'll keep digging.

Thanks, Colin

**Comment by colinhercus** [comment]
Hi Jim,

The rl/rg tags on the alt_scaffold fasta headers give the primary reference
chromosome coordinates that the alt_scaffold is an alternate for.

>chr19_KI270938v1_alt  AC:KI270938.1 gi:568335998 LN:1066800 *
rg:chr19:54025634-55084318 rl:alt-scaffold* AS:GRCh38

So rl tag identifies that the fasta sequence is an alternative scaffold and
the rg tag the region on the main chromosome that it is an alternative for.
Aligners need this information when calculating MAPQ.

I've found another strange difference between Gencode GRCH38 and GoldenPath
GRCH38. Gencode looks like they are using the reverse comlements of the
alt_scaffolds so Gencode >KI270936.1 is the reverse complement of
GoldenPath >chr3_KI270936v1_alt and Gencode gtf coordinates are all
reversed compared to my WES tracks in IGV.

This is evident in UCSC Genome Browser
<https://genome-asia.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr3_KI270936v1_alt%3A1%2D164170&hgsid=471538578_MOOhcyBk8LehrzwnPNZihJehAhdU>
where the Gencode and Refseq tracks are in opposite directions. Look at
MUC4 and MUC20 positions for the two.

Ensemble gtf files also have different sequence names and coordinates for
the genes.

I'll keep digging.

Thanks, Colin
