### ISSUE TITLE
Alignment and splice Junctions

### ISSUE THREAD

**Issue by akhilvelluva** [igvteam/igv.js#1681]
Hi,
To display bam and splice junctions in a single window I used the following code 

            const options = {
            locus: locus,
            genome: 'hg38',
            tracks: [
                {
                   type: 'merged',
                    name: sampleid,
                    height: 150,
                    tracks: [
                  {
                   type: 'alignment',
                  format: 'bam',
                  url: bamUrl,
                  indexURL:bamUrlindex
                   },
                      
           
                        {
                            type: 'spliceJunctions',
                            format: 'bed',
                            url:bedUrl,
                            indexURL:bedIndexUrl,
                            displayMode: 'COLLAPSED',
                            // other configuration options
                             minUniquelyMappedReads: 1,
                      minTotalReads: 1,
                      maxFractionMultiMappedReads: 1,
                      minSplicedAlignmentOverhang: 0,
                      thicknessBasedOn: 'numUniqueReads', //options: numUniqueReads (default), numReads, isAnnotatedJunction
                      bounceHeightBasedOn: 'random', //options: random (default), distance, thickness
                      colorBy: 'isAnnotatedJunction', //options: numUniqueReads (default), numReads, isAnnotatedJunction, strand, motif
                      labelUniqueReadCount: true,
                      labelMultiMappedReadCount: true,
                      labelTotalReadCount: false,
                      labelMotif: false,
                      labelIsAnnotatedJunction: " [A]",
                      hideAnnotatedJunctions: false,
                      hideUnannotatedJunctions: false,
                      hideMotifs: ['GT/AT', 'non-canonical'], //options: 'GT/AG', 'CT/AC', 'GC/AG', 'CT/GC', 'AT/AC', 'GT/AT', 'non-canonical'
                        }
                    ]
                }
            ]
        };

I am getting an error "error loading data", but it is working with bigwig format.

Any suggestion?

Thank you

**Comment by jrobinso** [comment]
There's not enough information there to help,  what messages do you see in the console?  Also, can you load the tracks individual (i.e. not as a merged file)?  In particular can you load the bam file individually?

The "merged" track is not designed for use with bam files and even if you get it to load its not going to work visually.   I suggest you not merge these tracks.

**Comment by akhilvelluva** [comment]
Thanks. I loaded tracks individually and it worked
