### ISSUE TITLE
Can not read ".gvcf.gz" extension

### ISSUE THREAD

**Issue by biorococo** [igvteam/igv.js#1683]
Hi! Thanks for developing such a great tool!

It would be useful to allow IGV to read extension "input.gvcf.gz" currently it only accepts "input.g.vcf.gz"

Thanks!

**Comment by jrobinso** [comment]
What exactly is a "gvcf" file?

**Comment by jrobinso** [comment]
Also, are you configuring this track with igv.js?   If so you can explicitly specify the track type, you don't have to rely on an extension.
