### ISSUE TITLE
 Discrepancy in Total Counts Displayed at the Same Position in IGV and IGV.js for the Same BAM File

### ISSUE THREAD

**Issue by zongzi111** [igvteam/igv.js#1685]
![image](https://github.com/igvteam/igv.js/assets/48515774/8d177bb1-2c6a-4911-a1e3-3933bb85dfb0)
I have encountered a discrepancy in the total counts displayed for the same genomic position in both the desktop version of IGV and IGV.js when working with the same BAM file.

**Comment by jrobinso** [comment]
I haven't been able to reproduce this.  Can you share a small test case?

**Comment by jrobinso** [comment]
Is it possible you have disabled filters in igv-desktop, such as "vendor failed" or "duplicates"?

**Comment by zongzi111** [comment]
It's possible that I may have disabled some filters in IGV-desktop, but please note that the settings in IGV-desktop are at their default values. I'm interested in ensuring that the results in IGV.js match those of the desktop version consistently. Below is a specific case to illustrate the issue:

https://drive.google.com/drive/folders/16tbMR_aDmfV29azhhQm2032tlTTyjzI_?usp=sharing
locus：chr7:140,739,907-140,739,947

If there are specific steps or configurations I need to follow in IGV.js to achieve results consistent with IGV-desktop, please let me know. I would appreciate any guidance or recommendations to address this inconsistency.

**Comment by jrobinso** [comment]
How have you confirmed that the settings in IGV-desktop are at their default values?  I get exactly the same counts between IGV desktop & igv.js, see the screenshot.   To insure you are at default values first shutdown IGV, then delete or rename prefs.properties in the `igv` folder,  then restart.   Also, you didn't say what version of IGV or igv.js you are using, I am assuming recent versions of each.

<img width="445" alt="Screen Shot 2023-09-11 at 7 13 30 PM" src="https://github.com/igvteam/igv.js/assets/933148/021f1c0b-b41b-4d28-99f8-a099b997377f">

**Comment by zongzi111** [comment]
![110758537cb1cdd6eb115fafd4882a2d](https://github.com/igvteam/igv.js/assets/48515774/5715f68b-1cac-4b73-a116-156141241aa3)
![image](https://github.com/igvteam/igv.js/assets/48515774/684c3389-56be-4f51-9d9a-f32ad084c76f)

Filter duplicate reads affect this value, I was wondering how to turn off this filter in igv.js.

**Comment by zongzi111** [comment]
"I have found how to disable this filter by adding filter: {duplicates: false} in the track configuration. Thank you."
