### ISSUE TITLE
Possible bug on Exon/Intron render

### ISSUE THREAD

**Issue by antonioaltamura** [igvteam/igv.js#1688]
Hello,
I'm reporting a possible bug in the rendering of this track.

According to the first render, the position 7,371,015-7,377,019 is a CAMTA1 exon area.
When you zoom out and then zoom in again, the area is being rendered as an intron.

https://jsfiddle.net/alfredopacino/7cgLkpxd/1/

See recordings https://github.com/igvteam/igv.js/assets/6325475/205d3593-99d0-40a4-90d1-6f23b721d969

**Comment by jrobinso** [comment]
Yes there is something wrong here.  As a work-around for now set the visibilityWindow for that track to -1.  This loads all the features for a chromosome.   I suspect what's happening is its not loading all the features belonging to that transcript on the initial view and the model is not constructed correctly.   When you zoom out the other features (CDS, exon, etc) are loaded and the model is fixed.

**Comment by jrobinso** [comment]
This is fixed for next release.  Thanks for the JSFiddle, makes things easier.

**Comment by antonioaltamura** [comment]
Thanks! When will the next release come out?

**Comment by jrobinso** [comment]
Its a big one,  probably mid October.  In the meantime you can use
`visibilityWindow:  -1`, or use the development build at
https://igv.org/web/snapshot/dist/.
