### ISSUE TITLE
when load 1000 Genomes Project vcf file, the web is killed

### ISSUE THREAD

**Issue by hurchu** [igvteam/igv.js#169]
Hi Jim,

I tried to load ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz to igv.js. But the page was killed. Is it because of the vcf is too big? Is there some limition of the vcf file's size to load?

![image](https://cloud.githubusercontent.com/assets/13222564/14214387/07352bdc-f7fa-11e5-9836-b8b95cfa3401.png)

Thank you very much! 

Best,

**Comment by jrobinso** [comment]
You need to use http protocol and an index,  the index file will not 
work with ftp protocol.   In general ftp protocol should not be used 
with igv.js,  I will add some code to throw an error.

You could load this from the 1KG Amazon S3 store as http and it should 
work,  I don't have the URL for this particular file but perhaps the 
project page does.

**Comment by hurchu** [comment]
Hi Jim,

Thank you very much for the quick response.

I download the vcf and index file into my s3 and load them for there.

 {
    name: "1000 Genomes Project",
    url: "https://s3.amazonaws.com/tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz",
    indexURL: "https://s3.amazonaws.com/tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi",
  }
, but still have the problem.

**Comment by jrobinso** [comment]
I tried loading those but can't (403 forbidden).   In general there is 
no size limit on tabix-indexed VCF files.   If you can make these 
public, and insure the CORS headers are set,  I will look into it.

> {
> name: "1000 Genomes Project",
> url: 
> "https://s3.amazonaws.com/tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz",
> indexURL: 
> "https://s3.amazonaws.com/tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi",
> }

**Comment by hurchu** [comment]
Hi Jim,

Here are links. They are public. Thanks!

https://s3.amazonaws.com/igv-optional-tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz
https://s3.amazonaws.com/igv-optional-tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi

**Comment by jrobinso** [comment]
OK, I can reproduce the problem, not sure of the cause but I'm looking into it.

**Comment by hurchu** [comment]
Thanks, Jim!

**Comment by jrobinso** [comment]
This is fixed, had nothing to do with the size of the VCF

**Comment by hurchu** [comment]
Hi Jim,

Thank you very much!

Could you please see the following link? In this html, I added several tracks, and when I zoom in several times, the page will be killed.

http://54.173.80.110/igv.js/dev/test.html

Have a good weekend!

**Comment by jrobinso** [comment]
Are the large annotation tracks indexed?  I don't see indexURL for 
dbSnp, for example.

**Comment by hurchu** [comment]
Yes, all are indexed. I didn't specify the indexed url in the html. But all files are public, including the index. Should I add the indeURL?

**Comment by jrobinso** [comment]
Its good practice, makes it clear.   I might require it before 
releasing, haven't decided.

I haven't been able to freeze it but will keep trying.    Could you open 
a new issue,  as this is a new issue?   Replys to closed issues are 
likely to get lost and forgotten.

**Comment by hurchu** [comment]
Created. Thanks, Jim!
