### ISSUE TITLE
Adding support for bedmethyl files

### ISSUE THREAD

**Issue by Ge0rges** [igvteam/igv.js#1696]
Bedmethyl files containing DNA methylation information are a [defined standard](https://www.encodeproject.org/data-standards/wgbs/) that are becoming more widely used. Nanopore's cheap sequencing technology is making methylation data more accessible every year, and significant resources have been spent producing quality tools to interpret that data. The standard nanopore tool [modkit](https://github.com/nanoporetech/modkit) has embraced the bedmethyl standard (and so have many other tools). 

It would be nice if IGV supported bedmethyl files out of the box.

**Comment by jrobinso** [comment]
BTW these files work if you fix the tabs.    This from the data you posted in the other issue.

https://tinyurl.com/254u2vb7

**Comment by Ge0rges** [comment]
Sounds like you support bedmethyl files when they are in TSV format (which we argue [here](https://github.com/nanoporetech/modkit/issues/43) should be the default). If that's the case I consider this issue closed. I leave it to you to determine if added compatibility is required. 

Please let me know if I can be of any help, looks like you have example data from the previous issue. Happy to provide any more needed.

**Comment by jrobinso** [comment]
I'm going to reopen as a reminder to myself to add the extension

**Comment by jrobinso** [comment]
The extension has been added, so igv will know what to do with ".bedmeythl" files.  ".bed" will still work, but you won't get the last 2 columns in popup text.   This will be part of the next release, which will be sometime in October.
