### ISSUE TITLE
failed when try to load some big vcf files at the same time

### ISSUE THREAD

**Issue by hurchu** [igvteam/igv.js#170]
Hi Jim,

I downloaded several public vcf files and bed files (1000 Genomes Project, ExAC, dbSNP, etc.) I saved all these files including indexes into my s3 bucket and make them public.
I want to load them to igv.js to view. But when I try to zoom in, most of the times, the page will be killed. Maybe 1/10  chances I can success.
Here is the link, thanks.
http://54.173.80.110/igv.js/dev/test.html
Best,

**Comment by jrobinso** [comment]
I've been trying but can't "kill the page",   I'm something like 10/10 success.   Be sure you have cleared your browser cache,  you could have an old version of the js file in the cache.

**Comment by jrobinso** [comment]
BTW,  set the visibilityWindow on your tracks to something reasonable, they defaults are not always the best.  This is the genomic window size at which features are loaded.  Setting it smaller will increase performance,  e.g.  visibilityWindow: 100000  for 100kb, etc.

**Comment by hurchu** [comment]
Hi Jim,

Thanks for your suggestion. I have added visibilityWindow.

Have you tried to zoom in 8 times? Because when I tried to zoom in 8 times, the page will be killed.

Best,

**Comment by jrobinso** [comment]
Yes,  I’ve tried all the way to base level, no problems.   Please give us exact steps to reproduce.    Also your environment (OS, browser),  and insure you are using the beta urls.

**Comment by hurchu** [comment]
Hi Jim,

OS: Windows 8.1 enterprise
Browser: chrome

I load http://54.173.80.110/igv.js/dev/test.html, and zoom in 8 times to chr1: 111,514,240-112,388,860
Every track is loaded successfully, but dbsnp keeps loading and then failed. Sometimes, it can be loaded successfully, but most of the times, it failed. Thanks!

I used //igv.org/web/beta/igv-beta.js

**Comment by jrobinso** [comment]
Still works for me (see screenshot),  I don't have a windows machine to test on.   However, that is a lot to try to load and you are not setting the visibility window on any of the tracks.   This needs set on a per track basis.    Try the settings below,  I can't test them immediately as the jquery server seems to be down.  

  $(document).ready(function () {

        var div = $("#igvDiv")[0],
                options = {
                    showNavigation: true,
                    genome: "hg19",
                    tracks: [
                        {
                            name: "Gencode Genes (v18)",
                            url: "https://s3.amazonaws.com/igv-optional-tracks/gencode.v18.collapsed.bed.gz",
                            indexURL: "https://s3.amazonaws.com/igv-optional-tracks/gencode.v18.collapsed.bed.gz.tbi"
                        },
                        {
                            name: "1000 Genomes Project",
                            url: "https://s3.amazonaws.com/igv-optional-tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz",
                            indexURL: "https://s3.amazonaws.com/igv-optional-tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi",
                            visibilityWindow: "300000"                        },
                        {
                            name: "OMIM Genes",
                            url: "https://s3.amazonaws.com/igv-optional-tracks/hg19_omim_genes.sorted.bed.gz",
                            indexURL: "https://s3.amazonaws.com/igv-optional-tracks/hg19_omim_genes.sorted.bed.gz.tbi"
                        },
                        {
                            name: "Ensemble",
                            url: "https://s3.amazonaws.com/igv-optional-tracks/EnsemblGenes.ensGene.sorted.bed.gz",
                            indexURL: "https://s3.amazonaws.com/igv-optional-tracks/EnsemblGenes.ensGene.sorted.bed.gz.tbi"

                        },
                        {
                            name: "ClinVar",
                            url: "https://s3.amazonaws.com/igv-optional-tracks/clinvar.vcf.gz",
                            indexURL: "https://s3.amazonaws.com/igv-optional-tracks/clinvar.vcf.gz.tbi",
                            visibilityWindow: "300000"
                        },
                        {
                            name: "dbSNP 146",
                            url: "https://s3.amazonaws.com/igv-optional-tracks/00-All.vcf.gz",
                            indexURL: "https://s3.amazonaws.com/igv-optional-tracks/00-All.vcf.gz.tbi",
                            visibilityWindow: "300000"

                        },
                        {
                            name: "ExAC",
                            url: "https://s3.amazonaws.com/igv-optional-tracks/ExAC.r0.3.1.sites.vep.vcf.gz",
                            indexURL: "https://s3.amazonaws.com/igv-optional-tracks/ExAC.r0.3.1.sites.vep.vcf.gz.tbi",
                            visibilityWindow: "300000"
                        }
                    ]
                };

        igv.createBrowser(div, options);

    });
![screen shot 2016-04-04 at 2 31 02 pm](https://cloud.githubusercontent.com/assets/933148/14264150/67886906-fa73-11e5-9ee3-2f572cd0cb8b.png)

**Comment by hurchu** [comment]
Hi Jim,

It works for me right now. Thank you very much!

Best,


On Mon, Apr 4, 2016 at 3:42 PM, Jim Robinson <notifications@github.com>
wrote:

> Still works for me (see screenshot), I don't have a windows machine to
> test on. However, that is a lot to try to load and you are not setting the
> visibility window on any of the tracks. This needs set on a per track
> basis. Try the settings below, I can't test them immediately as the jquery
> server seems to be down.
>
> $(document).ready(function () {
>
>     var div = $("#igvDiv")[0],
>             options = {
>                 showNavigation: true,
>                 genome: "hg19",
>                 tracks: [
>                     {
>                         name: "Gencode Genes (v18)",
>                         url: "https://s3.amazonaws.com/igv-optional-tracks/gencode.v18.collapsed.bed.gz",
>                         indexURL: "https://s3.amazonaws.com/igv-optional-tracks/gencode.v18.collapsed.bed.gz.tbi"
>                     },
>                     {
>                         name: "1000 Genomes Project",
>                         url: "https://s3.amazonaws.com/igv-optional-tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz",
>                         indexURL: "https://s3.amazonaws.com/igv-optional-tracks/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi",
>                         visibilityWindow: "300000"                        },
>                     {
>                         name: "OMIM Genes",
>                         url: "https://s3.amazonaws.com/igv-optional-tracks/hg19_omim_genes.sorted.bed.gz",
>                         indexURL: "https://s3.amazonaws.com/igv-optional-tracks/hg19_omim_genes.sorted.bed.gz.tbi"
>                     },
>                     {
>                         name: "Ensemble",
>                         url: "https://s3.amazonaws.com/igv-optional-tracks/EnsemblGenes.ensGene.sorted.bed.gz",
>                         indexURL: "https://s3.amazonaws.com/igv-optional-tracks/EnsemblGenes.ensGene.sorted.bed.gz.tbi"
>
>                     },
>                     {
>                         name: "ClinVar",
>                         url: "https://s3.amazonaws.com/igv-optional-tracks/clinvar.vcf.gz",
>                         indexURL: "https://s3.amazonaws.com/igv-optional-tracks/clinvar.vcf.gz.tbi",
>                         visibilityWindow: "300000"
>                     },
>                     {
>                         name: "dbSNP 146",
>                         url: "https://s3.amazonaws.com/igv-optional-tracks/00-All.vcf.gz",
>                         indexURL: "https://s3.amazonaws.com/igv-optional-tracks/00-All.vcf.gz.tbi",
>                         visibilityWindow: "300000"
>
>                     },
>                     {
>                         name: "ExAC",
>                         url: "https://s3.amazonaws.com/igv-optional-tracks/ExAC.r0.3.1.sites.vep.vcf.gz",
>                         indexURL: "https://s3.amazonaws.com/igv-optional-tracks/ExAC.r0.3.1.sites.vep.vcf.gz.tbi",
>                         visibilityWindow: "300000"
>                     }
>                 ]
>             };
>
>     igv.createBrowser(div, options);
>
> });
>
> [image: screen shot 2016-04-04 at 2 31 02 pm]
> <https://cloud.githubusercontent.com/assets/933148/14264150/67886906-fa73-11e5-9ee3-2f572cd0cb8b.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/igvteam/igv.js/issues/170#issuecomment-205510199>
>



-- 
Junfei Zhu

**Comment by jrobinso** [comment]
Thanks for all your reports, its very helpful.
