### ISSUE TITLE
Features visible when zoomed out past visibility window

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#171]
If you zoom in on tracks with a "visibility window",  then zoom out past the threshold,  features are still visible (but greyed out a bit).    The background needs to be white, no features,  when zoomed out.
<img width="1442" alt="screen shot 2016-04-01 at 4 13 32 pm" src="https://cloud.githubusercontent.com/assets/933148/14222410/4da01818-f825-11e5-9b5b-61f240e924ca.png">

**Comment by helgathorv** [comment]
Jim,
Did you confirm that it's the features that show up when they shouldn't, 
as opposed to the "zoom in to see features" label not behaving correctly?

Helga

**Comment by jrobinso** [comment]
Its not the label,  actually I fixed this.
