### ISSUE TITLE
Adding rhesus macaque genome reference

### ISSUE THREAD

**Issue by fe4960** [igvteam/igv.js#1713]
Hello,

Thanks a lot for developing this software. It is very helpful. We are currently working on the rhesus macaque genome data, Rhesus (Mmul_10/rheMac10). Rhesus macaque is the most commonly utilized non-human primate species. I am wondering if you can help add this genome to your reference genome list. Thanks very much.

**Comment by jrobinso** [comment]
Consider it added to my to-do list.  I am currently working on a release that will make it possible to add any genome by referencing its UCSC "hub" url,  for example as follows

https://igv.org/app-test/?hubURL=https://hgdownload.soe.ucsc.edu/hubs/GCF/003/339/765/GCF_003339765.1/hub.txt

This is not ready for release, ETA is end of November,  at which time adding to our list will be largely irrelevant.

**Comment by fe4960** [comment]
That is great. Looking forwards to the new release. Thanks a lot!
