### ISSUE TITLE
Insertions are collapsed with variants at neighboring positions even when track is expanded

### ISSUE THREAD

**Issue by ajw725** [igvteam/igv.js#1714]
This is a little hard to describe, so I'll try to include a couple of screenshots. We've noticed that, if we load a VCF with an insertion at one position and, say, a SNP at the next position in a chromosome, the two variants show up as a single horizontal bar on the same row in the track, which makes it very difficult to 1) see that there are two variants, and 2) click on the insertion. In cases where there are neighboring variants on both sides, it seems like the insertion is maybe even completely hidden by the other two variants. This happens even if the track is set to "Expand." Desktop IGV, by contrast, puts each variant on a separate row.

Here is an example from IGV.js. There is an insertion at chr5:170837543 and a SNP at chr5:170837544 (the next position). Clicking on _most_ of the bar gives only the SNP details; to get the insertion details, you have to click very precisely on the left edge of the bar.

Here is the SNP, with the corner of the modal exactly where I clicked on the bar:
![image](https://github.com/igvteam/igv.js/assets/2425541/d88ad5f3-1c01-47eb-92e6-b2ad7e0824e6)

And here is the insertion (note that the position still shows 544, even though the insertion is reported at 543):
![image](https://github.com/igvteam/igv.js/assets/2425541/b3dff771-9e21-4e1b-8c2c-51ad71bd44ec)

Interestingly, clicking slightly _off_ the left edge of the bar, at the actual position of the insertion, still brings up the modal:
![image](https://github.com/igvteam/igv.js/assets/2425541/51b27e02-de2b-4d70-8ca3-00b449ad71d6)

Here is the same region of the track from the desktop IGV application. Note that the insertion (the narrow bar just to the right of the ruler line) and the SNP (above that, just to the right) show up in different rows here, which makes it easy to see that there are multiple variants.
![image](https://github.com/igvteam/igv.js/assets/2425541/ae442352-2304-464f-be14-5c0cf73d1e9a)

Is there some way to force these variants to display on different rows of the track, either through a setting we haven't found or through a code change at some point in the future?

**Comment by ajw725** [comment]
Here is an example of a region with four distinct variants, as displayed in IGV.js:
![image](https://github.com/igvteam/igv.js/assets/2425541/388af941-1068-45a5-8341-f6f92ff2ff79)

And with the same track loaded into desktop IGV:
![image](https://github.com/igvteam/igv.js/assets/2425541/13c59f73-31a5-4411-81ff-c1c8facd0fe0)

In this case, no matter what I do, I can't manage to click on the insertion. I suspect it's hidden behind the two variants making up the top bar in IGV.js.

**Comment by jrobinso** [comment]
It seems like there are 2 issues here, difficulty on clicking insertions, and possibly some variants not shown in igv.js that are in IGV desktop.  I've noticed the first myself and it is (I think) improved in the not-released main branch.   For the second, that would be a bug but I would need some test data to reproduce it.  If you can provide a small test VCF I will look into it.  You can zip and attach here.

If you can pull and build from  source, or alternatively install from here:  https://igv.org/web/snapshot/dist/,  and see if the behavior is improved, the same, or worse that would also be helpful.

**Comment by ajw725** [comment]
Hi @jrobinso - thanks for the quick response.

I remembered that I'm a software engineer, so I opened up that example in my last comment (the one with four variants at chr10:89692940) and threw in a breakpoint in variantTrack.js right around [here](https://github.com/igvteam/igv.js/blob/2a96b2fa515fdbda3d9064183b2720beb6e117ec/js/variant/variantTrack.js#L298), where it looks like it sets up the rectangles. It does indeed hit that breakpoint for all four variants at that position:
1. A SNP, C>G, with row = 0 and rectangle `{"x": 1693, "y": 10, "w": 55, "h": 10}`
2. Another SNP, C>T, with row = 1 and rectangle `{"x": 1693, "y": 22, "w": 55, "h": 10}`
3. Type "Other," with row = 0 and rectangle `{"x": 1748, "y": 10, "w": 3, "h": 10}`
4. Another of type "Other," with row = 0 and rectangle `{"x": 1750, "y": 10, "w": 56, "h": 10}`

So it _is_ rendering all four variants, but it's almost entirely obscuring that insertion - presumably variant 3, with a width of 3 - behind variants 1 and 4 in row 0. Variant 1 covers (1693, 10) to (1748, 20), and variant 4 covers (1750, 10) to (1806, 20). Variant 3 appears to sit right in between (and probably slightly behind variant 4), in that tiny two-unit (pixel?) gap. If I click long enough, maybe I'll get it, but it hasn't worked yet.

I'll try to find a few minutes early next week to try the newer version and also get you some test data. Thanks!

**Comment by jrobinso** [comment]
OK, thanks for the diagnostics. I'm covered up right now but will look into this when I can and mark it for the next release.

**Comment by jrobinso** [comment]
@ajw725  Did you ever find time to create a test dataset?

**Comment by ajw725** [comment]
@jrobinso sorry, i had forgotten about that. just spent a little time with this. here are some stripped-down config files that reproduce what we were seeing.

Track config: [igv_config.json](https://github.com/igvteam/igv.js/files/15136212/igv_config.json)
The referenced VCF (Github won't let me attach a VCF, so I added `.txt`): [targeted_variants.vcf.txt](https://github.com/igvteam/igv.js/files/15136216/targeted_variants.vcf.txt)

We're hosting a copy of hg19 ourselves, so you'd have to point the reference fasta URL at your own location. This should produce a track like this:

![image](https://github.com/igvteam/igv.js/assets/2425541/2efed639-2e42-438f-a22e-8b437ebcb66b)

The location of the four mutations in the VCF have been modified from our actual data, but the configuration is the same: four variants called at the same position, with two SNVs, one insertion, and one deletion. Interestingly, the order seems to impact how they are displayed; if I put one of the SNVs first, I end up with three rows in the expanded track, whereas with insertion/SNV/deletion/SNV, I only get two rows, which is what we were seeing.

I did just notice that, if I click roughly on the position of the insertion, IGV.js does give me a scroll bar within the little popup window, and I can scroll down to see multiple variants at a single position:

![image](https://github.com/igvteam/igv.js/assets/2425541/b11451ac-9b43-4656-8766-37686f215b3f)

I hadn't noticed this before, because the scroll bar wasn't showing up until I attempted to scroll (which I know is just an OS setting). We haven't updated our version of IGV.js in a while, so I suspect we just didn't notice the scroll content when we were looking at this back in October. I'll check with a colleague on Monday to confirm this.

I still wonder whether IGV.js could/should completely expand the track to show one variant per row like desktop IGV, but it does seem like the information for all four variants is available in IGV.js if you scroll in the modal. It's just hard to see in the track that there are four distinct things, and it's hard to know what you're clicking on.

**Comment by jrobinso** [comment]
Sorry for the delay, this should be fixed and included in the upcoming release in early June.  The issue turned out to be in the packing of features into rows, specifically the insertion was treated as if it took no space and placed on the first row, between two adjacent variants, so visually it looked like a single feature.   This is fixed now.  Also I changed the rendering of insertion variants to be wider, and easier to see,  they should be the same width as snps now but still drawn between bases at the insertion point.

**Comment by ajw725** [comment]
> specifically the insertion was treated as if it took no space and placed on the first row, between two adjacent variants, so visually it looked like a single feature.

yep, this sounds exactly like what we were seeing. thanks! we'll test out the fix as soon as we have a chance, either from master or the release depending on timing.

**Comment by ajw725** [comment]
@jrobinso sorry it took a while for me to get back to this. just tested on 3.0.2 and it's looking good - thanks!
