### ISSUE TITLE
IGV web not searching gff file

### ISSUE THREAD

**Issue by H1889** [igvteam/igv.js#1716]
Hi. When I upload my own genome and gff annotation file cant search any gene, an error is shown "Unrecognized locus: AN5788"
The urls where I uploaded my files are:
genome:
https://data.cyverse.org/dav-anon/iplant/home/ggpozo/ANTONIO2023/asp.fasta
https://data.cyverse.org/dav-anon/iplant/home/ggpozo/ANTONIO2023/asp.fasta.fai

annotation:
https://data.cyverse.org/dav-anon/iplant/home/ggpozo/ANTONIO2023/asp.gff

thank you

**Comment by H1889** [comment]
Thanks again.
This gff file is searchable (but I have not added the field "searchable"):
NC_026501.1	RefSeq	gene	1151	2878	.	-	.	ID= ;db_xref=GeneID:5847003;gbkey=Gene;gene_biotype=protein_coding;gene_id=NCU10129;locus_tag=NCU10129
NC_026501.1	RefSeq	mRNA	1151	2878	.	-	.	ID=XM_001727924.2;Parent= ;db_xref=GeneID:5847003;gbkey=Gene;gene_biotype=protein_coding;gene_id=NCU10129;locus_tag=NCU10129
NC_026501.1	RefSeq	exon	1151	1449	.	-	.	ID=nbis-exon-2;Parent=XM_001727924.2;db_xref=GeneID:5847003;exon_number=2;gbkey=mRNA;gene_id=NCU10129;locus_tag=NCU10129;orig_protein_id=gnl|WGS:AABX|NCU10129|gb|EDO64885;orig_transcript_id=gnl|WGS:AABX|mrna_NCU10129T0;product=hypothetical protein;transcript_id=XM_001727924.2
NC_026501.1	RefSeq	exon	1528	2878	.	-	.	ID=nbis-exon-1;Parent=XM_001727924.2;db_xref=GeneID:5847003;exon_number=1;gbkey=mRNA;gene_id=NCU10129;locus_tag=NCU10129;orig_protein_id=gnl|WGS:AABX|NCU10129|gb|EDO64885;orig_transcript_id=gnl|WGS:AABX|mrna_NCU10129T0;product=hypothetical protein;transcript_id=XM_001727924.2
NC_026501.1	RefSeq	CDS	1436	1449	.	-	2	ID=nbis-cds-2;Parent=XM_001727924.2;db_xref=GeneID:5847003;exon_number=2;gbkey=CDS;gene_id=NCU10129;locus_tag=NCU10129;orig_transcript_id=gnl|WGS:AABX|mrna_NCU10129T0;product=hypothetical protein;protein_id=XP_001727976.1;transcript_id=XM_001727924.2
NC_026501.1	RefSeq	CDS	1528	1990	.	-	0	ID=nbis-cds-1;Parent=XM_001727924.2;db_xref=GeneID:5847003;exon_number=1;gbkey=CDS;gene_id=NCU10129;locus_tag=NCU10129;orig_transcript_id=gnl|WGS:AABX|mrna_NCU10129T0;product=hypothetical protein;protein_id=XP_001727976.1;transcript_id=XM_001727924.2

etc...

However this one is not searchable despite I have added the field "searchable" to the json file:
HF679023	VEuPathDB	protein_coding_gene	7187	8012	.	-	.	ID=FFUJ_02088;description=uncharacterized protein;ebi_biotype=protein_coding
HF679023	VEuPathDB	mRNA	7187	8012	.	-	.	ID=FFUJ_02088;Parent=FFUJ_02088;description=uncharacterized protein;gene_ebi_biotype=protein_coding
HF679023	VEuPathDB	exon	7187	7395	.	-	.	ID=exon_FFUJ_02088-E2;Parent=FFUJ_02088;gene_id=FFUJ_02088
HF679023	VEuPathDB	exon	7454	8012	.	-	.	ID=exon_FFUJ_02088-E1;Parent=FFUJ_02088;gene_id=FFUJ_02088
HF679023	VEuPathDB	CDS	7187	7395	.	-	2	ID=FFUJ_02088-p1-CDS2;Parent=FFUJ_02088;gene_id=FFUJ_02088;protein_source_id=FFUJ_02088-p1
HF679023	VEuPathDB	CDS	7454	8012	.	-	0	ID=FFUJ_02088-p1-CDS1;Parent=FFUJ_02088;gene_id=FFUJ_02088;protein_source_id=FFUJ_02088-p1
HF679023	VEuPathDB	protein_coding_gene	9590	14170	.	-	.	ID=FFUJ_02087;description=related to multidrug resistance protein;ebi_biotype=protein_coding
HF679023	VEuPathDB	mRNA	9590	14170	.	-	.	ID=FFUJ_02087;Parent=FFUJ_02087;description=related to multidrug resistance protein;gene_ebi_biotype=protein_coding
HF679023	VEuPathDB	exon	9590	10217	.	-	.	ID=exon_FFUJ_02087-E5;Parent=FFUJ_02087;gene_id=FFUJ_02087

**Comment by jrobinso** [comment]
Which field in column 9 are you trying to search for?

**Comment by H1889** [comment]
Hi again, I search any of them, when I load any GFF file on the local version of IGV I can search any of the 9th column fields.
Thanks for the help.

**Comment by jrobinso** [comment]
Sorry for the delay on this, if its still an issue can you zip and attach working and non-working gff3 files, or paste the contents quoted as code so the tabs don't get lost?  If you can do that I will investigate further.

**Comment by H1889** [comment]
Thanks for your help, but I resolved it reformating the gff file to gtf with bioconvert : https://bioconvert.pasteur.cloud/
I deleted not working files and used the new ones, so I can not send you one not searchable. If I have again the same problem vith a new one I will send it to you.
Anyway, thanks for everything
