### ISSUE TITLE
Support broadPeak and gappedPeak.    Renamed - was "Error creating track. Could not determine track type for file: [object File]"

### ISSUE THREAD

**Issue by akhst7** [igvteam/igv.js#1717]
HI, 

I have a gappedPeak bed file (BED 12+3) created by MACS3 hammratac, and tried to view it by IGV-web app.   When I upload it through a Track tab, I get a following error;
`Error creating track. Could not determine track type for file: [object File]`

I've tried other gappedPeak bed files [https://personal.broadinstitute.org/anshul/projects/encode/rawdata/peaks_histone/mar2012/broad/combrep_and_ppr/](url)
but IGV-webapp failed to load these files as well.  

Are there any workarounds for this ? 

Thanks.

**Comment by jrobinso** [comment]
Apologies for the delay.   I've looked into this,  did the files have an appropriate extension (".broadPeak", ".narrowPeak", ".gappedPeak"?   If so broadPeak and narrowPeak should have worked, I was incorrect on that.   I am adding gappedPeak now.     If you are still having problems with igv-web reopen this issue with test data, the link above does not have any data.
