### ISSUE TITLE
is:issue is:open Visualization of gene fusion from vcf file and RNA seq data 

### ISSUE THREAD

**Issue by Rahel14350** [igvteam/igv.js#1719]
Hi,
I would like to visualize EML4-ALK fusion on IGV (Version 2.16). 'Show soft clip' is active and when I go to the ALK breakpoint location, I can not find Blat-Soft-Clip option on IGV and I only have BLAT-read-sequence.
After blatting the sequence and finding the location that goes to both genes (ALK and EML4), I tried to visualize both of them with 'View mate region in split screen', but it shows the same gene and not the mate. Would you please let me know how I can solve this  problem.
I also would like to know for fusion visualisation, is it correct to group alignments by "Supplementary flag" and sort them by "base" and colour them by "Tag" such as 'MD'.
Many thanks in advance,
Rahel

**Comment by jrobinso** [comment]
IGV does not have a fusion visualization per se, could you be more specific on what you are trying to do?

The minimum blat sequence length is 20 bases, if your soft clip is less than that you will not see a blat option for it.

RE "view mate region in split screen", this will view the genomic region of the read pair mate in a separate panel.  If you find it is not doing this I would need to see the read details,  check where the mate is aligned in the popup text for the alignment you clicked over.

**Comment by Rahel14350** [comment]
Many thanks for your prompt reply. I have these fusion from VCF file:
```
chr2	29446394	FC_52	A	A]2:42522654]	.	.	FUSION_SUPPORTING_READS_DEDUP=381;GENE2_REF_READS=123881;GENE1_REF_READS=94960;FUSION_SUPPORTING_READS=2202;FUSION_DIRECTIONALITY_KNOWN=True;ALT_PAIR_DEDUP=121;ALT_SPLIT_DEDUP=260;REF_B_DEDUP=418;REF_A_DEDUP=262;BREAKPOINTS=chr2:42522654_chr2:29446394;KEEP_FUSION=True;CONTIG_ALIGN2=168;CONTIG_ALIGN1=70;CONTIG=CTCAGCTTGTACTCAGGGCTCTGCAGCTCCATCTGCATGGCTTGCAGCTCCTGGTGCTTCCGGCGGTACA**CT**TTAGGTCCTTTCCCAGGTGTGGGCTCTACAGTAGTTTTGCTCCATATAAGCATGACTCCACCTGAGTCTCCAGTAAGAACATCTCCATTCCCCAAGAATGCTAAACACTGCACAAATTTTGGCTTTTCATATTTCCCAAAAATTCCCTGTTTTCTTGTTAGTGAAT;ALT_PAIR=430;ALT_SPLIT=1772;REF_B_PAIR=107712;REF_B_SPLIT=16169;REF_A_PAIR=90935;REF_A_SPLIT=4025;PRECISE=Precise;FILTER=PASS;SCORE=0.981;CALLER=RnaFusionFilter;SVTYPE=BND;ROWID=bnd_2;MATEID=bnd_1;EVENT=FC_52;VARTYPE=fusion	.	.
chr2	42522654	FC_52	A	A]2:29446394]	.	.	FUSION_SUPPORTING_READS_DEDUP=381;GENE2_REF_READS=123881;GENE1_REF_READS=94960;FUSION_SUPPORTING_READS=2202;FUSION_DIRECTIONALITY_KNOWN=True;ALT_PAIR_DEDUP=121;ALT_SPLIT_DEDUP=260;REF_B_DEDUP=418;REF_A_DEDUP=262;BREAKPOINTS=chr2:42522654_chr2:29446394;KEEP_FUSION=True;CONTIG_ALIGN2=168;CONTIG_ALIGN1=70;CONTIG=CTCAGCTTGTACTCAGGGCTCTGCAGCTCCATCTGCATGGCTTGCAGCTCCTGGTGCTTCCGGCGGTACA**CT**TTAGGTCCTTTCCCAGGTGTGGGCTCTACAGTAGTTTTGCTCCATATAAGCATGACTCCACCTGAGTCTCCAGTAAGAACATCTCCATTCCCCAAGAATGCTAAACACTGCACAAATTTTGGCTTTTCATATTTCCCAAAAATTCCCTGTTTTCTTGTTAGTGAAT;ALT_PAIR=430;ALT_SPLIT=1772;REF_B_PAIR=107712;REF_B_SPLIT=16169;REF_A_PAIR=90935;REF_A_SPLIT=4025;PRECISE=Precise;FILTER=PASS;SCORE=0.981;CALLER=RnaFusionFilter;SVTYPE=BND;ROWID=bnd_1;MATEID=bnd_2;EVENT=FC_52;VARTYPE=fusion	.	.
```
When I blat them on UCSC, I can see that the contig goes to both genes and the "CT" is shared in both alignments. This is known as a region of microhomology. I grouped and sorted alignments as mentioned above and when I look for a read with more mismatches and BLAT them, I can find reads mapped to ALK and also EML4. Then with right click on the read with mismatched, and select 'view mate region in split screen' I still see ALK gene and not the EML4. Therefore, I am not able to read the sequence till the breckpoints in ALK (CT) and continue reading it in EML4 gene sequence and actually see the fusion region. I hope I made it more clear now.
Kind Regards,
Rahel

**Comment by jrobinso** [comment]
I'm still a bit confused, "view mate region" has nothing to do with the VCF file, or the blat,  it is the read mate of the alignment you clicked over.   I assume this is paired-end sequencing or you wouldn't see that menu option.

If you know the 2 regions you want to view you can manually type them in separated by spaces in the locus box near the top.

**Comment by Rahel14350** [comment]
From VCF file, I just get the cotig information and breakpoints but yes, The alignments coming from RNAseq paired-end sequencing BAM file.
Yes, Manually, I could see both genes breackpoints side by side and I was trying to visualise them with 'view mate region in split screen' option.
Many thanks.

**Comment by jrobinso** [comment]
Apologies for the delay.  "View mate region" is going to show you the region the mate of the alignment you click over is in.   Does this address your question?
