### ISSUE TITLE
mapping quality filtering

### ISSUE THREAD

**Issue by lpryszcz** [igvteam/igv.js#1727]
Hi, could you please add mapping quality filter to Alignment track similar to vanilla IGV?
![image](https://github.com/igvteam/igv.js/assets/988152/042dda02-c822-4a54-af04-b14c996c9d4d)

**Comment by jrobinso** [comment]
Agree we should implement and document this. In the meantime, from inspecting the code I think it might work to set the following in the track configuration

```
filter: {mqThreshold: 20}
```

**Comment by jrobinso** [comment]
This is implemented, It will be in the upcoming release.  The example below filters alignment with mapping quality < 30.   

```
  {
                    "type": "alignment",
                    "url": "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam",
                    "indexURL": "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam.bai",
                    "name": "NA12878",
                    "format": "bam",
                    filter: {mq: 30}
 }
```
