### ISSUE TITLE
Track scroll not working in splitted regions view

### ISSUE THREAD

**Issue by RoadRoller** [igvteam/igv.js#1730]
Issue reproduced on demo link, steps to reproduce:
1. Open IGV by link https://igv.org/web/release/2.15.5/examples/cram-vcf.html
2. Set alignments track height to 300
3. Set location to two regions, i.e. "1:10,000-19,922 1:14,771,706-14,781,628"
4. Not all alignments fit into track windown, but there is no way to scroll down, see screenshot below:

![image](https://github.com/igvteam/igv.js/assets/740624/20a24448-5dac-4ca6-81ad-b70af6b9b8be)

**Comment by RoadRoller** [comment]
@jrobinso, @turner, Hello!

I looked at this with a debugger locally and think that I found the problem: https://github.com/igvteam/igv.js/pull/1731
Please take a look.

**Comment by turner** [comment]
@jrobinso I think @RoadRoller fix is correct.

**Comment by turner** [comment]
closed with commit b714ae04
