### ISSUE TITLE
The error for URL

### ISSUE THREAD

**Issue by zhaosq2022** [igvteam/igv.js#1739]
Hi，
When I upload genome files using a URL, it always displays "Error accessing resource". But I can open this file in the browser through this link.
Do you know what the reason is?

Thank you very much.

shiqi

**Comment by zhaosq2022** [comment]
https://genome.cpolar.cn/hg19.fasta
https://genome.cpolar.cn/hg19.fasta.fai

**Comment by jrobinso** [comment]
You need to look in the console to see the specific error, but most likely the server is not including CORS headers.   See https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements
