### ISSUE TITLE
igv.js security concern related to s3 bucket names with '.' and cors

### ISSUE THREAD

**Issue by cariaso** [igvteam/igv.js#1740]
igv.js loads several resources from amazon hosted s3 buckets.
Buckets with a '.' in their name, such as 'igv.org.genomes' necessitate dangerous security practices.

Here are 3 such url that I see as loading when viewed from "Firefox->Developer Tools->Network"

https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg38/hg38.fa.fai
https://s3.amazonaws.com/igv.org.genomes/hg38/hg38_alias.tab
https://s3.amazonaws.com/igv.org.genomes/hg38/annotations/cytoBandIdeo.txt.gz

Those correspond to these urls in the aws console

https://s3.console.aws.amazon.com/s3/object/igv-genepattern-org?region=us-east-1&prefix=genomes/seq/hg38/hg38.fa.fai
https://s3.console.aws.amazon.com/s3/object/igv.org.genomes?region=us-east-1&prefix=hg38/hg38_alias.tab
https://s3.console.aws.amazon.com/s3/object/igv.org.genomes?region=us-east-1&prefix=hg38/annotations/cytoBandIdeo.txt.gz

On each of those pages there is a suggested Object URL of

https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg38/hg38.fa.fai
https://s3.amazonaws.com/igv.org.genomes/hg38/hg38_alias.tab
https://s3.amazonaws.com/igv.org.genomes/hg38/annotations/cytoBandIdeo.txt.gz

The first case uses virtual-hosted-style-access, where the bucket name is a url subdomain
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access

The two latter cases use path-style-access, where the domain is all of s3, and the bucket name is part of the url subdirectory.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access

however this path-style-access has been deprecated
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/
in part because the the virtual-hosted-style-access allows improved CORS security.

The deprecated path-style-access remains necessary for bucket names
that include a "." so 'igv-genepattern-org' is a good bucket name, and
'igv.org.genomes' is a deprecated bucket name.

Please consider taking these steps:

1. copying 's3://igv.org.genomes' to 's3://igv-org-genomes'

2. global search and replace across https://github.com/search?q=org%3Aigvteam+igv.org.genomes&type=code

Doing so would allow your users to have webservers configured with the far more secure
`content-security-policy connect-src https://igv-genepattern-org.s3.amazonaws.com https://igv-org-genomes.s3.amazonaws.com` 

instead of necessitating the terrifyingly permissive
`content-security-policy connect-src https://igv-genepattern-org.s3.amazonaws.com https://s3.amazonaws.com`

**Comment by jrobinso** [comment]
Thanks, I'll look into it., I was not aware of this issue.   I would point out that using our hosted data is not required, it is there for convenience, you are free to use other sources of data.    You can copy anything you need to your own server and use the `genomeList` parameter to repoint igv.js to that server.  See https://github.com/igvteam/igv.js/wiki/Browser-Creation.

**Comment by jrobinso** [comment]
Copying all of our files is not feasible, however I have moved the hg38 files listed above.  New files are already going to igv-genepattern-org.
