### ISSUE TITLE
Sort samples shown in vcf variant track by genotype

### ISSUE THREAD

**Issue by UndressK** [igvteam/igv.js#1743]
Hello!
I created a test vcf file (attached) that is displaying the genotype info for 8 samples for those 5 variants. Is it possible to sort them by genotype (GT) instead of by the order in which they appear on the VCF? so that for instance the samples with HET (1|0) or HOM (1|1) show up always on top by default? (and samples with 0|0 or no GT are displayed always below)
Thanks!

[vars.vcf.gz](https://github.com/igvteam/igv.js/files/13683677/vars.vcf.gz)

<img width="1205" alt="image" src="https://github.com/igvteam/igv.js/assets/32929741/1e1c732a-99e8-408d-9be9-7bcf66ef1fd9">

**Comment by jrobinso** [comment]
Hi, currently there is not an option to sort by genotype in igv.js.    Leave this issue open, we will treat it as a feature request.

**Comment by UndressK** [comment]
Thank you Jim!

**Comment by jrobinso** [comment]
I'm looking at this now.  Its somewhat complicated as a sample can have multiple genotypes,  if there are multiple variants at a site.   This is pretty common in the 1KG dataset for example.    I'm sure something reasonable can be done just noting this complication.

**Comment by jrobinso** [comment]
This is implemented and will be in the upcoming release (early June).  The configuration looks like this

```
                {
                    name: "VCF",
                    type: "variant",
                    format: "vcf",
                    url: "../../test/data/vcf/vars.vcf",
                    indexed: false,
                    sort: {
                        direction: "DESC",
                        option: "genotype",
                        chr: "chr4",
                        position: 102596193
                    },
                    height: 200
                }
```

**Comment by UndressK** [comment]
That's great news, thanks for implementing that, it will surely be useful!
