### ISSUE TITLE
In the GENE Track, The Exon should be -1 position but it looks like -2.

### ISSUE THREAD

**Issue by TamarOr** [igvteam/igv.js#1746]
Dear IGV Team,
I wanted to bring to your attention an observation I made within the "GENE Track" while using the 2.15.11 version of the IGV tool.
Upon inspecting the track, I noticed that the first exon position in the "GENE Track" is consistently presented at -2 position, whereas it should be at the starting position -1. For clarification, I have attached a figure of this issue.
![image](https://github.com/igvteam/igv.js/assets/156075036/92a2ec92-72c5-43c8-a28f-187c19809aa3)
In our specific case, the NF2 gene transcript (chr22:30032739) begins at -2 position of this variant . 
Your insights on this matter would be highly appreciated.
I look forward to receiving your input.
Thank you in advance,

**Comment by jrobinso** [comment]
What is the source of the "Genes" track?   In IGV default annotation track it is correctly positioned (see screenshot):

<img width="1262" alt="Screen Shot 2024-01-09 at 8 35 32 AM" src="https://github.com/igvteam/igv.js/assets/933148/9d4a03aa-633c-4bbe-8923-2fed7507551c">

**Comment by jrobinso** [comment]
<img width="1262" alt="Screen Shot 2024-01-09 at 8 35 32 AM" src="https://github.com/igvteam/igv.js/assets/933148/1944dd7d-d4ad-463d-b0f0-75572637b52d">

**Comment by jrobinso** [comment]
<img width="1114" alt="Screen Shot 2024-01-09 at 12 39 34 PM" src="https://github.com/igvteam/igv.js/assets/933148/bf032f77-437b-44f0-941b-fbcfee35ca35">

**Comment by TamarOr** [comment]
On the desktop, it works properly but when integrating with the web component it does not work properly.

**Comment by jrobinso** [comment]
The screenshot I provided above is the web component, as you can see its correct.   Again my question is, what is the source of the "GENES" track in your screenshot,  the problem is with the data file for that track.

**Comment by jrobinso** [comment]
I'm closing this due to a lack of response.   If you can provide a test file (the source of the "GENES" tracsk) I will look at it, but its almost certain the coordinates for that gene are off by 1 in the file.   Keep in mind "BED" and related UCSC formats use zero-based coordinates, GFF and other formats use 1-based.

**Comment by TamarOr** [comment]
sorry for the delay in our response:(
we are prepared to communicate with you.
any information you need!!

We use these 4 files.
b37_cytoband.txt
cytoBandIdeo.txt
human_g1k_v37_decoy.fasta
human_g1k_v37_decoy.fasta.fai
In the code, we saw that start is correct but start+1 is displayed in the UI.

**Comment by jrobinso** [comment]
In the original screenshot you have more files than that, there is a file for GENES and an alignment file. The problem is with the file you are using for the GENES track, its coordinates are off by 1. this is not an igv.js issue, it is a problem with your file.

**Comment by TamarOr** [comment]
Thank you:)
I will check our files as you said.
And I will use them in the desktop application and see what the results will be.
