### ISSUE TITLE
Aliases not iterable

### ISSUE THREAD

**Issue by JoukjeKloosterman** [igvteam/igv.js#1747]
Hello all,

I am currently using the embedded genome browser.
I have cloned the code from github, and build it, i have integrated this in a different pipeline. 

However it was working normally when I used the relase 2.15.11, but now working with the unreleased code I get the following error when loading a track with the cram format:

![image](https://github.com/igvteam/igv.js/assets/144109774/f0fac9fe-1f1d-4b77-b095-1486e2f59251)

I am using this unreleased version of igv because there are some features that i want to implement and test.
I hope you can help me, and maybe you can tell me how to fix it. 

Below is a screenshot on how i load the track:

![image](https://github.com/igvteam/igv.js/assets/144109774/2d824462-11d0-4c0a-bf07-125b8e029840)

**Comment by JoukjeKloosterman** [comment]
I have a similar issue when opening the cram_vcf.html in the directory examples from igv.js 

![image](https://github.com/igvteam/igv.js/assets/144109774/cc7bb713-1372-469d-b089-d5bf7d89b0d1)

**Comment by JoukjeKloosterman** [comment]
Maybe good to know that i am also loading a VCF file in the tracks, maybe that causes the issue?

**Comment by jrobinso** [comment]
Looks like a bug, I will look into it.
