### ISSUE TITLE
Problems when quickly clicking the zoom button

### ISSUE THREAD

**Issue by guohuayu** [igvteam/igv.js#1748]
When quickly clicking the zoom button, igv.js will still load the previous data until rendering is complete, resulting in a bug where "Zoom in ti see features" and the previous data appear simultaneously

**Comment by jrobinso** [comment]
There's not a lot we can do about this, once an http request has been made its difficult to cancel it cleanly, an in any event would require a large code redesign with unknown side effects.  If you want to zoom multiple levels I suggest you use the slider.
