### ISSUE TITLE
A bug when using CSI index for BAM alignments

### ISSUE THREAD

**Issue by beaulian** [igvteam/igv.js#1749]
Hi, I think there is a bug when searching alignments using CSI index, here `overlappingBins[0]` is a tuple and in the top level, causing `lowestOffset` to be undefined, maybe it should be `ba.loffset[overlappingBins[this.depth][0]]`?

https://github.com/igvteam/igv.js/blob/77d88fac63564111462b010f739ce691ac44c321/js/bam/csiIndex.js#L155

**Comment by jrobinso** [comment]
Yes something is wrong here.  I think this was ported from C code, makes my head spin a bit but I will get to the bottom of it.  Thanks for the report.

**Comment by jrobinso** [comment]
OK I no longer understand `loffset`, if I ever did.   According to the spec here, https://samtools.github.io/hts-specs/CSIv1.pdf, `loffset` is 

"(Virtual) file offset of the first overlapping record".   

"record" is not defined anywhere,  but I assume it is an alignment or feature.     So if loffset is the virtual position of the first alignment/feature,  why would there be any chunks in this bin with vpointers < loff?  

The bug you have found is effectively turning off the `loffset` optimization.  I don't want to guess at how it should be fixed until I understand it.  At the moment it is a harmless bug,  efficiency aside.

**Comment by jrobinso** [comment]
OK this incorrect "optimization" is removed.

**Comment by beaulian** [comment]
Hi, @jrobinso 

Thanks for your reply. The bug is significant when using CSI index. Without the `loffset` to reduce the search space, CSI index needs to access large bins, causing a big performance loss.

I find a similar code in htsjdk
https://github.com/samtools/htsjdk/blob/b16416c078e2df3e3a21486207d0c0c31b293cb9/src/main/java/htsjdk/samtools/CSIIndex.java#L172

they say
> Compute 'minimumOffset' by searching the lowest level bin containing 'startPos'.

So I think `lowestOffset` should be `ba.loffset[overlappingBins[this.depth][0]]`. I would greatly appreciate it if you can fix this bug. Thanks.

**Comment by jrobinso** [comment]
I would consider a PR for this if it included a unit test,  since you seem to understand how loffset should be used.   I personally do not understand it, and can't find any clear description of what it actually is.

**Comment by beaulian** [comment]
Hi, @jrobinso 

Thanks for your reply. I can't find a clear description either. I try my best to give my own explanation and then submit a PR.

I think `loffset` comes from BAI's linear index. The linear index has a clear description that it record the smallest file offset of the alignments that overlap with the window. So the "record" you mentioned should be the "alignment".

Since CSI index support variable interval size, when the interval size is too small, CSI index will be too large. As a result,  CSI index records the chunk start offset of the parent bin (the `loffset`) for a bin, corresponding the linear index is changed to tree index.

In the implementation of htsjdk, there exists a additional piece of code to check if the computed bin is not in the index, I think there is no need to check `overlappingBins[this.depth][0]` in the implementation of igv.js. Therefore, the `lowestOffset` is the `loffset` of the bottom-left bin.
