### ISSUE TITLE
Provided http headers missing on some request step when loading 'wig' track

### ISSUE THREAD

**Issue by yfedyai** [igvteam/igv.js#1757]
Hi Igv team
Ver 2.15.2

I tried to update igv from older verson (2.12) to newest and faced with issue loading 'wig' track.
bam/cram/refseq/vcf is fine
In my application we are using special auth header to interact with backend

After investigation i compare my requests loading any succes track and failed one i've noticed that request header is missing on next sequence file request. 
The idea is that i do request to BE and BE redirects me to corresponding bucket in aws and as i understand loading happens partially by sequence 

**SUCCES FLOW**

- first request in sequence 

<img width="1301" alt="image" src="https://github.com/igvteam/igv.js/assets/33098616/5c4c1cf4-b05b-4d39-849e-6a269cc83739">

- second request in sequence
<img width="1306" alt="image" src="https://github.com/igvteam/igv.js/assets/33098616/e1d76f14-2c38-4b98-8ae3-054706a12b35">

-------------------------------
***FAILED FLOW***

- first request in sequence
<img width="1314" alt="image" src="https://github.com/igvteam/igv.js/assets/33098616/5a39d6d2-e366-43c4-9d7e-db52c3949407">

- second request in sequence
<img width="1308" alt="image" src="https://github.com/igvteam/igv.js/assets/33098616/ef911e49-e9e5-4ebe-a3e5-f3fb02699706">

- third request ( BE resposne 401 due missing auth header)
<img width="1310" alt="image" src="https://github.com/igvteam/igv.js/assets/33098616/831dc006-246c-4e16-924d-728be0cd4d2b">

$~$

Please advice
If any extra details needed please let me know

**Comment by yfedyai** [comment]
Hi @jrobinso
headers for all track types set as a `headers` key of track config object

**Comment by jrobinso** [comment]
Sorry for the delay.   I see the issue, working on a solution.

**Comment by jrobinso** [comment]
Actually I can't reproduce your issue in 2.15.2, which is not the latest release that is 2.15.11.   I do see an issue with the latest unreleased code and will be addressing that.  Can you verify the version of IGV you are using?  If there is a reproducible bug in 2.15.11, the latest release, I will address it.

**Comment by yfedyai** [comment]
sorry, it was my bad.. on initial message i mentioned wrong version. issue was on 2.15.11

need some extra time to check after your commit, i will inform you later

**Comment by jrobinso** [comment]
I can't reproduce the issue on 2.15.11 either.

**Comment by yfedyai** [comment]
lets close for now, still no longer actual and now don't have an opportunity to check
