### ISSUE TITLE
Authentication Issue with JWT Tokens in Cross-Application Setup (Django-Generated, Flask-Validated) for igv.js Requests

### ISSUE THREAD

**Issue by gezthxbio** [igvteam/igv.js#1762]
I'am encountering an issue with igv.js where OAuth2 bearer tokens (JWT tokens), generated by a Django application and validated in a Flask application, are not consistently included in the Authorization header for requests made to Flask-served endpoints (serve_file and serve_reference). This inconsistency leads to authentication failures and prevents the loading of genomic data files.

**Setup Details:**

**JWT Token Generation:** Performed by a Django application.
**Token Validation:** Conducted by a Flask application, configured with the same secret_key as Django to ensure consistent token validation.
**Data Serving:** Flask application serves genomic data (CRAM, SNV, CNV, STR, SV files) through protected endpoints requiring OAuth2 bearer tokens for access.
**Client:** igv.js configured to visualize genomic data, with OAuth token provided for accessing protected resources.

**Expected Behavior:**
igv.js should send the OAuth2 bearer token in the Authorization header for each request to the Flask-served endpoints, facilitating successful authentication and data retrieval.

**Actual Behavior:**
Requests made by igv.js to some endpoints do not include the OAuth2 bearer token in the Authorization header, leading to authentication errors and failed data loading attempts.

**Configuration Example:**

```
var options = {
    locus: "chr1:155,000-156,000",
    reference: {
        oauthToken: "{{ jwt_token }}",
        id: "hg38",
        fastaURL: "http://127.0.0.1:5002/serve_reference/hg38.fa",
        indexURL: "http://127.0.0.1:5002/serve_reference/hg38.fa.fai",
    },
    tracks: [
        {
            oauthToken: "{{ jwt_token }}",
            name: "Sample CRAM - SampleID",
            url: "http://127.0.0.1:5002/serve_file/SampleCRAM.cram",
            indexURL: "http://127.0.0.1:5002/serve_file/SampleCRAM.cram.crai",
            format: "cram",
            type: "alignment"
        },
    ]
};
```
**Troubleshooting Attempts:**

Verified direct access to the Flask endpoints using curl with the Authorization header succeeds.
Ensured that JWT tokens are valid and correctly configured in both Django and Flask applications.

**Inquiry:**

Are there known issues or limitations with igv.js handling OAuth2 bearer tokens, especially in a setup involving cross-application token generation and validation (Django and Flask)?
Could there be specific configurations or practices recommended to ensure consistent inclusion of JWT tokens in requests made by client-side libraries like igv.js in such scenarios?
I would appreciate any guidance or insights into resolving this authentication issue to ensure seamless access to protected genomic data through igv.js.

**Comment by jrobinso** [comment]
Thanks for the report.   What version of IGV are you using?   

You say "Requests made by igv.js to some endpoints...".   Does this mean it works for other endpoints?   Does it fail immediately or after some number of requests?  Is there anything repeatable?  The first step on my end would be to reproduce the problem, any details you can provide will help.     The sequence of network request / responses for a test case would be helpful.

**Comment by gezthxbio** [comment]
Thank you for looking into this.
IGV.js version : 2.15.5
 I've confirmed that the Flask app correctly handles authenticated requests with a JWT token when tested using curl. Additionally, IGV.js functions as expected when JWT authentication is disabled on the server side. This issue seems specific to how IGV.js handles the Authorization header for HTTP Range requests.

Please find the attached screenshot demonstrating the network activity and the missing Authorization header in Range requests made by IGV.js: [link to screenshot].

This scenario leads me to believe there might be an issue with how authentication headers are managed for certain types of requests in IGV.js
<img width="2549" alt="Screenshot 2024-02-06 at 8 15 10 PM" src="https://github.com/igvteam/igv.js/assets/29910603/bcb9acbb-b926-46c9-8a36-d8ebe376ab63">
<img width="2257" alt="Screenshot 2024-02-06 at 8 22 23 PM" src="https://github.com/igvteam/igv.js/assets/29910603/d64277d2-c3fd-4bf1-aca8-630df15e980c">
<img width="2549" alt="Screenshot 2024-02-06 at 8 22 32 PM" src="https://github.com/igvteam/igv.js/assets/29910603/5110abac-9e09-4173-9f44-209dbed1e262">
<img width="1797" alt="Screenshot 2024-02-06 at 8 29 33 PM" src="https://github.com/igvteam/igv.js/assets/29910603/71359a0d-ced7-4df7-a652-7f77db983845">

Any insights or suggestions you have would be greatly appreciated.

**Comment by jrobinso** [comment]
I just noticed something else, which might be the issue for the particular failure in the screenshot.   The byte range igv.js is requesting on the fasta file looks wrong, and could cause the 500 error.   This is not related in any obvious way to the authorization token.  I will need to try to reproduce this.    Do you see this error immediately after startup with the configuration posted?  

Also, any fixes to igv.js will be for the next release.  It would be helpful if you could try the development build, which will form the basis of this release.  You can install this from https://igv.org/web/snapshot/dist/.    Its possible you won't see the issue there as a lot has changed since 2.15.5.

<img width="351" alt="Screen Shot 2024-02-06 at 9 31 58 AM" src="https://github.com/igvteam/igv.js/assets/933148/f53d3f2c-84b4-4ab9-b162-bb1870233e67">

**Comment by gezthxbio** [comment]
I have additional screenshots that highlight the issue more clearly:

The hg38.fa.fai file request successfully includes the Bearer token in the Authorization header.
The initial request for hg38.fa does not include the Bearer token in the Authorization header.
Subsequently, a byte range request for hg38.fa that includes the Bearer token results in a 500 INTERNAL SERVER ERROR from the server. I will surely look into this 500 internal server error.
![Screenshot 2024-02-06 at 9 54 21 PM](https://github.com/igvteam/igv.js/assets/29910603/d1f545b9-bd7b-47e1-9dd9-7c458cc03e7e)
![Screenshot 2024-02-06 at 9 54 17 PM](https://github.com/igvteam/igv.js/assets/29910603/675f2b91-0e0a-4186-8fa8-39f31bcdae14)
![Screenshot 2024-02-06 at 9 54 10 PM](https://github.com/igvteam/igv.js/assets/29910603/05fa94df-a302-4b88-9757-47f5030bbc60)

**Comment by jrobinso** [comment]
What type of request is the first one (the one that does not include the token)?   If its a pre-flight OPTIONS request the token should not be required.   If the server is returning a 401 for the OPTIONS request that could be a problem.

**Comment by jrobinso** [comment]
Oh sorry, I see it is a HEAD request.  

To repeat what I said above, any fixes will be for the next release.  So we need to see if this problem exists in the development build.   Could you try it?  You can install this from https://igv.org/web/snapshot/dist/.

**Comment by gezthxbio** [comment]
You are right, IGV.js requests a valid byte range (bytes 94923195-94973694/3249912778) without the JWT token but requests an invalid range (bytes=94923195-43) with the JWT token enabled.
this is for hg38.fa.fai
![Screenshot 2024-02-06 at 10 34 13 PM](https://github.com/igvteam/igv.js/assets/29910603/12dd0d6a-b194-45c1-a0a1-71da563e3673)
and for hg38.fa
![Screenshot 2024-02-06 at 10 34 19 PM](https://github.com/igvteam/igv.js/assets/29910603/93dbbdd1-72b8-432a-aec5-135a79857e79)

**Comment by gezthxbio** [comment]
@jrobinso 
Thank you for your insights regarding the potential cause of the byte range request issue. After further testing, I can confirm that the issue does not occur with this snapshot version [igv.min.js](https://igv.org/web/snapshot/dist/igv.min.js)
Thank you once again for your support and assistance in troubleshooting this issue.
