### ISSUE TITLE
text has no color and error：circular-view.css.map Not found

### ISSUE THREAD

**Issue by jianqi-chen** [igvteam/igv.js#1768]
The clicked content is all white, and the background error is "GET/circular view. css. map" Error (404): "Not found"
![image](https://github.com/igvteam/igv.js/assets/26400047/0d9299ec-e3c5-41d1-928f-2c1fe6f85f7c)

![image](https://github.com/igvteam/igv.js/assets/26400047/535bfef6-e439-4fd3-a5b8-aa4976e3cbff)

**Comment by jrobinso** [comment]
What version of igv.js are you using?

**Comment by jrobinso** [comment]
Well there's not enough information here to help you.   The warnings are normal and not related to the error.    I will need a reproducible test case to investigate further, this is not reproducible with any data I have.

**Comment by jianqi-chen** [comment]
That's it, I'll pack a Docker container. Do you think it's feasible

**Comment by jianqi-chen** [comment]
I'll give you this Docker container. Can you help me check if there's any problem

**Comment by jrobinso** [comment]
Sorry I don't use Docker.  Can you just zip up an example?  I need the html, and the data your are referencing.

**Comment by jianqi-chen** [comment]
ok，thank you，this ‘test’ folder is too big，can I del it？

**Comment by jrobinso** [comment]
I'm not sure what you mean "del" it.   If you send email to igv-team@broadinstitute.org I can send you a dropbox link you can upload to.   Or alternatively you can make a smaller test case,  just slice the region of the bam file that is causing issue using samtools.

**Comment by jianqi-chen** [comment]
I have already sent an email, please check it carefully

**Comment by jrobinso** [comment]
Sorry this is too complex.  I don't have time to debug your program,  I need a simple reproducible test case with data.   See the snippet below,  you may edit this for your local paths and substitute a reference to your own data.   I can fix the URL to the data (that is the BAM file)  for my local server, but be sure to include it.

```
<!DOCTYPE html>
<html lang="en">
<head>
</head>

<body>

<div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>

<script type="module">

    import igv from "dist/igv.esm.js"
    const config =
        {
            "genome": "hg38",
            "locus": "chr8:<put your coordinates here>",
            "tracks": [
                {
                    "type": "alignment",
                    "url": "<your bam file>",
                    "indexURL": "<your bam index file>",
                    "format": "bam"
                }
            ]
        }

    igv.createBrowser(document.getElementById('igvDiv'), config)
        .then(browser => {
            console.log("IGV created")
        })


</script>
</body>
</html>
```

**Comment by jianqi-chen** [comment]
ok

**Comment by jrobinso** [comment]
Also, BTW, in your html I see this

```<script src="https://cdn.jsdelivr.net/npm/igv@2.15.5/dist/igv.min.js"></script>```

I don't think you are actually using anything from the igv.js github repo.

**Comment by jianqi-chen** [comment]
There is no dist folder in this GitHub, nor are there files such as igv. esm. js and igv. min. js
![image](https://github.com/igvteam/igv.js/assets/26400047/bef78eb5-5bfd-4690-b714-cbbdd92b7329)

**Comment by jianqi-chen** [comment]
When debugging with the demo you provided, the results were normal. I think it's a problem with my HTML script. Next, I will debug myself. Thank you for your patient answer.

**Comment by jrobinso** [comment]
If you are working from the github repo you need to read the documentation (README).
