### ISSUE TITLE
Failed to use search from gtex portal

### ISSUE THREAD

**Issue by ericjason11111** [igvteam/igv.js#1771]
It does not work using the code below:

        search: {
            url: 'https://gtexportal.org/rest/v1/reference/features/$FEATURE$',
            resultsField: 'features',
            geneField: 'geneSymbol',
            snpField: 'snpId'
        },

**Comment by ericjason11111** [comment]
The code is from dev/eqtl/gtex.html

**Comment by jrobinso** [comment]
Oops, closed accidentally.  Leave open until I remove this dev code.

**Comment by ericjason11111** [comment]
How can I have the same function as this? Many thanks!

**Comment by jrobinso** [comment]
I don't know, what exactly do you want?   This is probably a question for the gtex project.

**Comment by jrobinso** [comment]
Also, have you read the igv.js documentation?
