### ISSUE TITLE
Represent filter

### ISSUE THREAD

**Issue by Andy-B-123** [igvteam/igv.js#1773]
Hi, thank you for your work on this! I'm looking to use igv-reports to highlight certain variants of interest from a background set of variants. 

I use the "FILTER" column in the VCF for this and in the desktop version of IGV the variants are greyed out as shown:
![image](https://github.com/igvteam/igv-reports/assets/35752341/9fb6bd9d-0fc4-460b-ade4-d8628fd73764)

However with igv-report the filter information doesn't seem to be visually displayed (although it is still there if manually inspecting the variant):
![image](https://github.com/igvteam/igv-reports/assets/35752341/a4e2776e-9eaa-4fa9-b390-55ad7b432a25)

Would there be a way of having the FILTER column be able to be used to adjust opacity/colour? Or should I look to have that information as part of the INFO column? If so, any quick advice for colouring things by the INFO column? 

Thank you!

**Comment by jrobinso** [comment]
This is implemented in igv.js,  post release we will update igv-reports.   If you want to test it beforehand edit your report and change the igv.js script import near the top of the page to this

```
<script src="https://igv.org/web/snapshot/dist/igv.min.js"></script>
```
