### ISSUE TITLE
RangeError when loading a specific region on any chromosome in WGS analysis

### ISSUE THREAD

**Issue by lionncle** [igvteam/igv.js#1777]
Hi Igv team
From version 2.15.8

I'am encountering an issue with igv.js when I want to load a specific region (66,994,190-66,994,230) on any chromosome for WGS analysis with an average coverage at 30x.  
The problem with these positions is that the chunks generated are too big ~1.33GB instead of the usual 20MB and crash the browser. 
With a colleague, we first checked our bam files and the corresponding indexes, which were all ok. We then tested these positions with an older version of IGV.js (v2.8.1) and no problem. We then compared the index loading code of these two versions and identified a difference in the canMerge function of file [js/bam/indexUtils.sj](https://github.com/igvteam/igv.js/blob/master/js/bam/indexUtils.js):
- v2.8.1 (in file [js/bam/bamIndex.js](https://github.com/igvteam/igv.js/blob/v2.8.1/js/bam/bamIndex.js))
```javascript
function canMerge(chunk1, chunk2) {
    return (chunk2.minv.block - chunk1.maxv.block) < 65000 &&
        (chunk2.maxv.block - chunk1.minv.block) < 5000000;
    // lastChunk.minv.block === lastChunk.maxv.block &&
    // lastChunk.maxv.block === chunk.minv.block &&
    // chunk.minv.block === chunk.maxv.block

}
```
- v2.15.8
```javascript
function canMerge(chunk1, chunk2) {
    const gap = chunk2.minv.block - chunk1.maxv.block
    const sizeEstimate = chunk1.maxv.block - chunk1.minv.block
    return sizeEstimate < 5000000
}
```

So we propose to fix this issue by modifying the canMerge function as follows:
```javascript
function canMerge(chunk1, chunk2) {
    const gap = chunk2.minv.block - chunk1.maxv.block
    const sizeEstimate = chunk2.maxv.block - chunk1.minv.block
    return sizeEstimate < 5000000 && gap < 65000
}
```

We tested version 2.15.8 with the above proposed modification to the positions of interest and the problem was solved. 

Does our solution suit you?

Thank you

**Comment by jrobinso** [comment]
Hi, thanks for the detective work!

I think the bug is here, it should be "chunk1.maxv.block"

```
const sizeEstimate = chunk1.maxv.block - chunk1.minv.block
```

As coded in 2.15.8 I would expect canMerge to always return true.    I.E. always return true.   

You solution is fine,  I will apply it now.   We are close to releasing 2.16.0

**Comment by lionncle** [comment]
Thank you for your quick response

**Comment by lionncle** [comment]
attention, the correction applied is not correct :
```javascript
function canMerge(chunk1, chunk2) {
    function canMerge(chunk1, chunk2) {
        const gap = chunk2.minv.block - chunk1.maxv.block
        const sizeEstimate = chunk2.maxv.block - chunk1.minv.block
        return sizeEstimate < 5000000 && gap < 65000
    }
}
```

**Comment by jrobinso** [comment]
@lionncle Yea I caught that, thanks.
