### ISSUE TITLE
Unhandled Error in TrackViewport when scrolling

### ISSUE THREAD

**Issue by shortercode** [igvteam/igv.js#1779]
We're experiencing an error thrown by IGV when interacting with a view that is showing "Zoom in to see features". It probably wouldn't be a major issue but in our dev environment any thrown error causes a "application crashed" style overlay.

I tracked back through the code and I think it's caused by the canvas reference being cleared, or not being set. Then the scroller trying to update it's position.

![image](https://github.com/igvteam/igv.js/assets/9051865/74e6a41d-a236-4569-9314-6742c9190516)
![image](https://github.com/igvteam/igv.js/assets/9051865/70e021dc-89ea-4aba-9f9d-dfc124770991)

Checking the local state `canvas` is undefined, as is `featureCache` which means repaint bails early instead of recreating the canvas.

I can trigger the error by doing a vertical click drag on the viewer.

This is the "latest" version on npm.

**Comment by jrobinso** [comment]
Thanks for the report.   I can also reproduce this with a vertical drag.   It will get fixed in the next release, not ETA ye but we are working on finalizing it now.

**Comment by shortercode** [comment]
Thanks @jrobinso for the speedy fix!
