### ISSUE TITLE
Getting 416 Unsatisfiable Range upon zooming in

### ISSUE THREAD

**Issue by colossalpat** [igvteam/igv.js#1785]
IGV Version: https://github.com/igvteam/igv.js/releases/tag/v2.15.11

Hi,

Loaded a BAM file in igv and we're seeing "416 Unsatisfiable Range" errors upon zooming in on the gene. Also doesn't display the nucleotides of the reference genome.

Example:
<img width="323" alt="Screen Shot 2024-03-19 at 1 35 43 PM" src="https://github.com/igvteam/igv.js/assets/107420042/0fd80fbe-1007-48ee-b1ca-273928f0a8df">

Tested out the same BAM file on IGV Desktop, it doesn't seem to be an issue there.

I also tried building off latest `master` in case this was fixed, but that doesn't seem to be the case.

Any help would be appreciated, thank you.

**Comment by jrobinso** [comment]
I will probably need a test case to reproduce this.  I am not seeing this error on any files that I have.    Seeing the request/response details from the developer network tab would also be helpful.  

What server are you using for the BAM file?

Would you be able to share a bam and test case reproducing this problem?

**Comment by colossalpat** [comment]
@jrobinso, we were able to figure out the issue! Turns out we were gzipping some of the reference genomes and required us to pass in `compressedIndexURL` (as seen in this PR https://github.com/igvteam/igv.js/pull/1452).

Thank you for reaching out so quickly and for maintaining this package!
