### ISSUE TITLE
igv.js styling breaks inside shadow DOM

### ISSUE THREAD

**Issue by twrightsman** [igvteam/igv.js#1795]
Embedding igv.js inside of a shadow DOM breaks the UI since the CSS is [manually applied](https://github.com/igvteam/igv.js/blob/c8410100067cd94220cba5ac93734997e6f58701/scripts/embedCssTemplate.js#L1-L9) to the document root and cannot style elements inside of the shadow DOM.

See https://github.com/marimo-team/marimo/issues/1165 for an example.

**Comment by jrobinso** [comment]
That's not a use case we support,  if you have suggestions please leave them here.

**Comment by twrightsman** [comment]
I appreciate your response @jrobinso. I understand if you're unwilling to support Marimo specifically, but shouldn't an app such as igv.js that is expected to be embedded support being inside of a shadow DOM?

If I do come up with a patch that solves the situation for both cases, I'll open a PR if that's something the team is open to.

**Comment by jrobinso** [comment]
@twrightsman This is the first times its been requested, and I have never heard the term "shadow DOM" until now.   One possibility might be to optional pass in the node onto which the style element is attached, with the default node being `document.head`,  so replace `document.head` with the supplied node.  This might require some minor refactoring of the startup sequence.   Would that solve your issue?  

```
    document.head.append(style)
```

**Comment by twrightsman** [comment]
Yeah, the shadow DOM was new to me as well. I'm not much of a web developer, but I looked into the APIs for this and I think I have the beginning of something that will work on modern browsers.

The CSS attachment would need to be refactored to occur at browser creation, by [appending](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets#append_a_new_stylesheet) a `CSSStyleSheet` to the `element.getRootNode().adoptedStyleSheets`, where `element` is the element that is passed to `igv.createBrowser`. A check would be needed to see if the style sheet is already present in the root, so the same style sheet doesn't keep getting added with each new browser created.

`element.getRootNode()` would be `document` in the normal case and `ShadowRoot` if inside a shadow DOM, so this shouldn't break anything or change any behavior, except IGV within a shadow DOM will now style itself properly.

I can try my hand at web development and make a patch for this, if you'd prefer.

**Comment by jrobinso** [comment]
This looks promising.   I will experiment with it when I can find some time,  it might not be today.   Ping this issue again if too much time passes.   I would like to find an alternative to injecting a <style> tag and this looks like it could work.

**Comment by jrobinso** [comment]
The shadow dom approach works, and solves some other problems, thanks for the pointer.    The root igv.js node now attaches itself as a shadow node to the container element provided on startup.   If you could test this in your application that would be helpful, you can access a test build from

https://igv.org/web/snapshot/dist/

**Comment by twrightsman** [comment]
@jrobinso I really appreciate you looking in to this! It seems to work well on my end (besides the dark mode coloring, but separate issue!).

![igv](https://github.com/igvteam/igv.js/assets/6300973/853092e9-27ee-4680-b039-0f55dc4992f2)

**Comment by jrobinso** [comment]
Hmm, that looks like it mostly works, but the track label boxes are empty.    If you can put this on a public site I can poke around with web inspector.

**Comment by twrightsman** [comment]
I'm having trouble getting it statically hosted, but if you're inclined to do a few steps, you can get it running by going to [marimo.app](https://marimo.app), going to Tutorial > New notebook, and pasting the following four code blocks into their own cells:

```python
import asyncio
import micropip
task_install = asyncio.create_task(micropip.install(['sqlite3', 'anywidget']))
```

```python
while not task_install.done():
    pass

import anywidget
import marimo as mo
```

```python
class IGVWidget(anywidget.AnyWidget):
    _esm = """
    import igv from "https://igv.org/web/snapshot/dist/igv.esm.min.js"

    function render({ model, el }) {
      var options = {
        genome: "hg38",
        locus: "chr8:127,736,588-127,739,371",
        tracks: [{
          "name": "HG00103",
          "url": "https://s3.amazonaws.com/1000genomes/data/HG00103/alignment/HG00103.alt_bwamem_GRCh38DH.20150718.GBR.low_coverage.cram",
          "indexURL": "https://s3.amazonaws.com/1000genomes/data/HG00103/alignment/HG00103.alt_bwamem_GRCh38DH.20150718.GBR.low_coverage.cram.crai",
          "format": "cram"
        }]};

        igv.createBrowser(el, options)
    }
    export default { render };
  """
```

```python
IGVWidget()
```

**Comment by twrightsman** [comment]
I see the track levels are not quite invisible, just very light; adding `el.style['background-color'] = 'white'` after `igv.createBrowser` works around the dark mode coloring issues.

**Comment by twrightsman** [comment]
![igv](https://github.com/igvteam/igv.js/assets/6300973/13e8a1cb-74f6-42fd-b15e-51c35dd62de0)

**Comment by jrobinso** [comment]
OK,  I was just about to respond that everything looks normal in "light" mode.    What element are you adding the background color to?

**Comment by twrightsman** [comment]
The same element passed in to `igv.createBrowser`. I think we can close issue thanks to your shadow DOM work. Would it be possible to tag a new release with the shadow DOM fixes? Thanks again!

**Comment by anderspitman** [comment]
This is really cool, but just wanted to point out (as @twrightsman mentioned above) that some of these APIs will only work in most browsers since early 2023.

**Comment by jrobinso** [comment]
@anderspitman thanks for note.  I assume, but haven't tested, that babel takes care of that for non-esm users.   If not a polyfill might be possible, but I'll wait until someone reports an actual issue.

**Comment by anderspitman** [comment]
I think it's less of a secure these days with evergreen browsers.

**Comment by jrobinso** [comment]
@anderspitman Yes that's true, but thanks for pointing this out.
