### ISSUE TITLE
Bigwig rendering difference in igv vs igv.js

### ISSUE THREAD

**Issue by mbeer3** [igvteam/igv.js#1802]
Hi--  Thanks for this tool.  I'm seeing bigwig rendering differences between igv and igv.js.  igv.js is filling in 1's were there should be 0's).  The igv plot below is correct.  Is there a parameter to control this, or maybe something missing in my bigwigs (generated from bedGraphToBigWig)?
http://beerlab.org/gkmpwm/CTCF_hg38_avg.bigwig
http://beerlab.org/gkmpwm/CTCF_hg38_avg1.bigwig
http://beerlab.org/gkmpwm/browser6.html
![image](https://github.com/igvteam/igv.js/assets/13926343/2f910b5f-32d7-4b2b-953a-b632fde570ab)
![image](https://github.com/igvteam/igv.js/assets/13926343/bde0a438-0f3a-487f-b5e9-9cb4dd98adbe)

Thanks,
Mike Beer

**Comment by mbeer3** [comment]
I pasted the wrong figure, this is what IGV produces:
![image](https://github.com/igvteam/igv.js/assets/13926343/b4d72af4-7761-469a-a4b9-c0be50e4c4c7)

**Comment by jrobinso** [comment]
Thanks for the report.  This looks like a bug in the latest (unreleased)
code.   I do not see this error in the latest release (igv.js 2.15.11).

**Comment by jrobinso** [comment]
This should be fixed, will be in the 3.0 release.
