### ISSUE TITLE
The bedgraph file in line plot doesn't work the same as the IGV desktop

### ISSUE THREAD

**Issue by KingZop959** [igvteam/igv.js#1808]
Why does viewing my bedGraph file with line plot in the desktop version of igv not work the same as when I view it with igv.js?line plot looks too tight in IGV.js in the same locus.I don't know if configuration is wrong or something else, can anyone help me?
![8$C$1 $0AN)9UEM 5VL`EHM](https://github.com/igvteam/igv.js/assets/84114601/349d9273-c620-4999-9176-5bed9504d8e8)
![FU{}D OE ZL I%BJ3Y80(U9](https://github.com/igvteam/igv.js/assets/84114601/e6df53b1-b51d-4412-ba46-c3bfaf2902e3)

**Comment by jrobinso** [comment]
This might be a result of summarization.  IGV desktop computes an average value for all data occupying a single pixel on the genomic axis before drawing.  The release version of igv.js does not do this for bedgraph.   However the development version does, you might try it by building from source yourself or using the distribution at https://igv.org/web/snapshot/dist/.   You can also test the file at https://igv.org/app-test.    If you want to zip and post your bedgraph here I will test it.

**Comment by KingZop959** [comment]
Thank you, I solved it after using the development version.
![92c0b91503d70637c6984f551bedf3e](https://github.com/igvteam/igv.js/assets/84114601/33d4a111-da82-4192-a53f-c202c01acab9)
