### ISSUE TITLE
Docs: Add `compressedIndexURL` and clarify `indexURL` behavior

### ISSUE THREAD

**Issue by fiskus** [igvteam/igv.js#1812]
Hi!

First off, thanks for the awesome work on IGV.js! It's a fantastic tool for genome visualization.

I wanted to point out a couple of things in the documentation that could use some improvement:

1. **`compressedIndexURL`**  
   There's no mention of the `compressedIndexURL` property. It would be great to include info on this to help users who need to work with compressed index files. ~~From the names `compressedIndexURL` and `indexURL`, it looks like they serve the same purpose and are interchangeable, but from the code, they appear to do different jobs. Currently, you have to provide both files; you can't just use `compressedIndexURL`. It would be great if we could use only one.~~ Could you consider updating the documentation to clarify the distinct roles of `indexURL` and `compressedIndexURL`? This would help prevent confusion for other users like myself.  For context, `compressedIndexURL` was introduced https://github.com/igvteam/igv.js/pull/1452.

2. **`indexURL`**  
   The docs say `indexURL` is optional, but IGV.js tries to guess this URL (by appending ".fai" to the `fastaURL`) if it's not provided, which crashes IGV.js if the file doesn't exist. This happens unless the `indexed` property is explicitly set to `false`. Clarifying this behavior would really help prevent configuration errors and crashes. See the docs for `indexURL` https://github.com/igvteam/igv.js/wiki/Reference-Genome.

Despite these small issues, IGV.js is an amazing tool. Improving these parts of the documentation will make it even better. I'd be happy to help with the code if you can provide some guidance.

Thanks for considering these suggestions!

**Comment by jrobinso** [comment]
Yes, leave this open till we add these items to the doc.   Also, I'm considering changing this behavior of trying to guess the index, its a carryover from IGV desktop.

**Comment by jrobinso** [comment]
@fiskus I'm just getting around to lookint at this.   I don't understand how the compressed index can work without the normal index, the .gzi index it is not a replacement for the .fai index, it is an additional index to the compressed blocks.    So I don't understand what you mean by "they are interchangeable"?

I am going to remove all guessing for the index files,   which will make the "indexed" property unneeded.   It is not much burden to add the explicity index URLs, and we already require this in the web app.

**Comment by fiskus** [comment]
Thank you for the clarification. I initially thought the `compressedIndexURL` property served the same functionality as `indexURL`, pointing to a compressed version of the index file that would normally be set by `indexURL`. So, my thoughts were, if we have two files, one ungzipped and the second the same but gzipped, why do we need to provide both? My confusion stemmed from the naming, as I'm not deeply familiar with the underlying mechanics. I appreciate your explanation and understand the distinction now.

**Comment by jrobinso** [comment]
The "fai" index maps chunks of sequence to file positions.  When the file is bgzipped these positions are no longer valid, but are interpreted as virtual file positions.   The gzi index maps these virtual file positions to actual positions of gzipped blocks in the file.

**Comment by jrobinso** [comment]
OK I've removed the guessing code, which was also causing issues with signed URLs and hashed filename schemes such as used with Google Drive and Dropbox.
