### ISSUE TITLE
copy sequence from selected region as in IGV desktop

### ISSUE THREAD

**Issue by MiqG** [igvteam/igv.js#1814]
Hi,

thanks for developing and maintaining such a great genome visualizer. Is it possible to copy the sequence from a selected region in IGV web app as it can be done in IGV desktop?

thanks very much in advance, best,

Miquel

**Comment by jrobinso** [comment]
I've implemented a copy sequence item to the ROI menu if the region length is < 100 kb.   We can't have an unlimited string length here, if 100kb is not sufficient we can probably increase it.

As I was looking to implement this and discovered it is already possible from the sequence track.   Apologies for not realizing this sooner.  You simply zoom in to the region of interest, right click on the sequence track, and select copy sequence.
