### ISSUE TITLE
Possible to add a peptide track?

### ISSUE THREAD

**Issue by spieden** [igvteam/igv.js#182]
We have a peptide sequence data file in refseq .txt format that we extracted from what the desktop IGV uses. Is there any way to display this information in igv.js?

Thanks!

**Comment by jrobinso** [comment]
Sorry I don't know precisely what you are referring to,  could you attach a sample of the "refseq.txt" file, and also a screenshot of what it looks like in IGV desktop?

**Comment by spieden** [comment]
Here's the file in question -- I believe it was extracted from a ".genome" file:

https://www.amazon.com/clouddrive/share/0PnrJUSDi5NXhElvtx38w5ydvhEixktNlLW0p8HrQPK

I asked another member of my team to paste a desktop IGV screenshot.

**Comment by cjhseq** [comment]
Hi, we're just looking to replicate the ability to see amino acid sequence within an open reading frame as seen here. Our assumption is that this information was being derived from the refGene.txt file that IGV loads as a "geneFile". Is this something that we can pull off with igv.js?

![igv_snapshot](https://cloud.githubusercontent.com/assets/12943565/14570473/43dd4844-02f9-11e6-9be0-2a5c77a05853.png)

**Comment by jrobinso** [comment]
Ahh, o.k.,  I though you were asking about a custom format.    Yes we 
plan to do that, but its not ready yet.  The peptides are not part of 
the file,  they are computed from the sequence and frameshift 
information in the gene annotations.    Now that you've registered 
interest via the git issue we will put it on the schedule.

Jim

**Comment by cjhseq** [comment]
Great, thanks!

**Comment by lmtani** [comment]
+1

**Comment by patidarr** [comment]
HI Jim,

Any update on this issue?

**Comment by lhelseth** [comment]
Jim,
Any progress on adding an amino acid translation track corresponding to the nucleotide sequence?  IGV Desktop is useless in our institution since the Broad moved reference files to AWS (blocked by our IT department) so I'm trying to implement IGV.js with locally hosted reference files for our pathologists to review their sequencing results.  Let me know if I can help with testing.  Thanks.

**Comment by jrobinso** [comment]
It would probably be easier to just setup local reference genomes for IGV
desktop, many people do this.    There's a long list of igv.js items,  as
well as IGV desktop items,  on my plate so I can't give you an eta on this.

**Comment by lhelseth** [comment]
Okay, thanks.

**Comment by amberlin** [comment]
Is there any work around for this until it is implemented?

**Comment by tiffanydai** [comment]
Hi @jrobinso, 

Is the 3-frame translation track that IGV desktop has, on the near-term roadmap for igv.js? I think this is the correct open issue to ask about the plan for this feature, but apologies if it isn't! 

![image](https://user-images.githubusercontent.com/35508772/62093304-a26f8200-b22d-11e9-8b6c-6024e38410fb.png)

**Comment by jrobinso** [comment]
Update on what issue, unfortunately there are a lot of topics touched on in this thread.  3-frame translation has been in igv.js for a long time.

**Comment by tiffanydai** [comment]
Oh! I must have overlooked it in the documentation. Thanks @jrobinso :)

**Comment by oootif** [comment]
Hi, i still don't see the amino acid coding on igv.js like the desktop version has. Is there a work around recommended? I just need the hg19 AA sequenc to pair up with the RefSeq DNA sequence. Thanks

**Comment by jrobinso** [comment]
Do you mean the 3 frame translation?  Did you try the menu for the sequence
track (gear icon)?

**Comment by oootif** [comment]
Not the 3-frame translation. I’m talking about the Amino acid coding, which
is only 1-frame, like how the IGV desktop displays the AA coding at the
RefSeq track.

**Comment by jrobinso** [comment]
That's not implemented in igv.js.    Looking  back through this thread at some point it got confused with the 3-frame translation and closed.  I will reopen it.  No ETA though.

**Comment by oootif** [comment]
No problem. Can I add a separate track for hg19 amino acid sequence that
matches the DNA seq that igv uses? Do you have a recommended one that I can
use?

**Comment by jrobinso** [comment]
@oootif I don't understand how that would work, the AA sequence needs to be computed from fields in the annotation file, specifically the frame shift taking account the strand combined of course with the nucleotide sequence.  I don't know of any format to do this.   I would welcome a pull request if you are able to implement it, but there is not off-the-shelf file for this that I am aware of.
