### ISSUE TITLE
Inquiry About Highlighting SNPs in IGV.js

### ISSUE THREAD

**Issue by yrjia1015** [igvteam/igv.js#1833]
Dear IGV.js Development Team,

I hope this message finds you well. I am currently utilizing the IGV.js tool and am particularly interested in replicating a feature similar to what is observed in the GTEx IGV, where specific SNPs influencing a gene are highlighted in red upon searching for that gene.

![IGV](https://github.com/igvteam/igv.js/assets/104757328/b429480f-b56d-4251-8030-f80ceceaac9f)

Could you kindly guide me on how to implement this functionality in IGV.js? Are there any tutorials, documentation, or code samples available that could assist in achieving this feature? My goal is to enhance the visual representation of gene-SNP relationships directly within the IGV.js viewer.

Thank you for any help or direction you can provide. I look forward to your valuable guidance.

**Comment by jrobinso** [comment]
GTEx uses igv.js, so this should be possible.   The documentation is the code,  my suggestion would be to start with the EQTL track and search for the string "gtex" throughout the code base.   The functionality you mention is specific to gtex.

Leave the issue open, when I can find time I will look at generalizing this functionality.   I have other priorities at the moment.

**Comment by yrjia1015** [comment]
Thank you for your previous response and guidance regarding the use of igv.js for GTEx. I have been exploring the EQTL track functionality as you suggested but have encountered some challenges. Specifically, after changing the track type to "eqtl," the data does not display correctly.
Unfortunately, I was unable to find relevant tutorials or documentation for the eQTL track in the official igv.js resources. Could you kindly provide an example or further guidance on how to properly utilize the eQTL track? This would be incredibly helpful for our implementation.

**Comment by jrobinso** [comment]
Sorry I'm not able to do that,  but if you would like to open an issue as a feature request for this functionality please feel free to do so.  I would need a good description of what you are trying to achieve, as well as a test data case.

**Comment by yrjia1015** [comment]
Thank you for your response. We appreciate your suggestion to open an issue as a feature request. We have already sent test data and a detailed description of our needs via email to igv-team@broadinstitute.org. If possible, please consider this feature request for future updates. Thank you!

**Comment by jrobinso** [comment]
From private email

> Request: Would it be possible to create an xQTL track based on the GWAS track format that includes five columns: CHR, SNP, BP, Phenotype, and P? This track should allow searching and highlighting data points where the Phenotype column matches specified values. We believe this functionality would greatly enhance our ability to analyze various xQTLs directly within IGV.

**Comment by yrjia1015** [comment]
Thank you for considering our request.

**Comment by jrobinso** [comment]
Hi, I'm working on this now.  Is this format a recognized standard in the field for xQTL data?

```
CHR	SNP	BP	P	Phenotype
10	rs146165798	50023438	0.000106	A1CF
10	rs1937725	51879303	0.000485	A1CF
```

**Comment by jrobinso** [comment]
Also, I don't understand the naming of the "Phenotype" column, these appear to be gene names.  Can the values be something else?

**Comment by jrobinso** [comment]
The "Phenotype" field is problematic.  If you want to associate an eQTL with a gene I think the column needs to be more explicit, ie. be named "Gene" or similar.  Otherwise there is no way to determine that the column contains genes.  In the hQTL file, for example, it contains the following

```
H3K27ac(chr10:100005048-100011461)
```

I am guessing this means that this feature is associated with H3K27ac at the location in the parentheses,  but there really isn't much igv.js can do with this information.    What were you hoping to implement here?

**Comment by yrjia1015** [comment]
Thank you very much for considering this request. Your understanding is correct: in eQTL data, the "Phenotype" typically correlates with specific genes, akin to what you do with the gtex project. However, for other types of xQTL data such as mQTL and hQTL, the "Phenotype" might refer to specific molecular phenotypes affected by SNPs, not just gene names. For instance, mQTLs often relate to changes in DNA methylation patterns, while hQTLs involve specific histone modifications like the H3K27ac mentioned in the file.

In this context, I am hoping to implement a feature in IGV that allows users to search for a specific phenotype (e.g., "H3K27ac(chr10:100005048-100011461)") to highlight and navigate to the corresponding genomic region. This would greatly enhance IGV’s capability, especially in handling and displaying complex xQTL data, providing more direct and detailed biological insights.

Therefore, I would like to inquire if it's possible to add support for the "Phenotype" field in IGV's search functionality, allowing matches based on the values in the Phenotype column to be highlighted. This way, users could quickly locate relevant genomic areas directly through phenotype information.

**Comment by jrobinso** [comment]
I think it would be more feasible if you separated the region from the phenotype.  H3K27ac is not a useful search term, but chr10:100005048-100011461 is.   

I still don't understand quite how this would work,  BTW,  do you envision a user literally typing "H3K27ac(chr10:100005048-100011461)" into the search box?   How would they know to do this?  

BTW, when you specify genomic coordinates in any form you are committed to a specific genome reference assembly.   An EQTL association to a gene by name is not.   But there is nothing we can probably do about that.

**Comment by jrobinso** [comment]
I think however we approach this we will need to create a track for the phenotypes,  unlike genes there is no automatic track for features like "H3K27ac(chr10:100005048-100011461)".    Even if you loaded H3K27ac as a signal or peak track it is highly unlikely anything in it would correspond to the region stated exactly.    So I suggest explicit columns be added for the phenotype,  perhaps "PCHR, PSTART, PEND".    The phenotype name can remain as it is, but coordinates would come from the new columns.   

Unless of course there is already a widely used convention of encoding the coordinates in the name, but so far my searching on xQTL data formats has not discovered such a convention, or any conventions really.

**Comment by jrobinso** [comment]
For this to work we are going to need a track for the "phenotype", when it is not a gene.  We already have a track for genes.  So, for example,  you might load a BED file track for the histone modifications with entries like this

```
chr10 100005047 100011461 H3K27ac(chr10:100005048-100011461)
```

This would enable users to search by the phenotype name.   We could generalize the GTEX portal behavior to highlight the phenotype feature and associated xQTLs as GTEX does for genes.

**Comment by yrjia1015** [comment]
Thank you very much for considering this request. I will create several sample xQTL test files and then send them to igv-team@broadinstitute.org

**Comment by jrobinso** [comment]
@yrjia1015 I am making progress on this, I don't need any additional data at this time.

**Comment by jrobinso** [comment]
Hi,

Is the data you have shared with us sensitive (B.cell_eQTL,tsv and
Monocyte_hQTL.tsv)?  I would like to create some public examples when I
release this.

**Comment by yrjia1015** [comment]
Hi,

Thank you for reaching out.
The data we have shared with you (B.cell_eQTL.tsv and Monocyte_hQTL.tsv) is not considered sensitive. We appreciate your efforts in creating public examples for this feature.

**Comment by jrobinso** [comment]
This is now supported,  I used the files you provided.  There is an example [here](https://igv.org/web/snapshot/examples/xqtl.html)

Also from the igv.org test app. https://tinyurl.com/22t9mzrp

To highlight eqtls or phenotypes you search from the track gear menu, rather than the top level locus/search box as you do at GTEx.   Also, it is assumed you are zoomed into the general region of interest.   To see how it works try searching for the following from the "Search for..." menu item from the B Cell eqtl track

* rs5751764
* SMARCB1

You can also right-click on an eqtl and select "highlight associated features".    If any tracks are loaded containing the phenotype features they will be highlighted.  For an eQTL this is often the gene track.  For other types you will need to load a track with the phenotypes if you want to see them.   I created a track for the histone peaks from your file to illustrate.

More info will follow on the file format but the files you used will work.   You can tabix-index them if you wish, as I did for the examples.

```
            {
                type: "qtl",
                format: "qtl",
                name: "B cell eQTL",
                url: "https://igv-genepattern-org.s3.amazonaws.com/test/qtl/B.cell_eQTL.tsv.gz",
                indexURL: "https://igv-genepattern-org.s3.amazonaws.com/test/qtl/B.cell_eQTL.tsv.gz.tbi",
                visibilityWindow: 4000000
            }
```

**Comment by yrjia1015** [comment]
Thank you for the detailed instructions and the example on the igv.org test app. The new search and highlight features are particularly useful.
Thank you again for your support and the valuable enhancements you've implemented.
