### ISSUE TITLE
trouble with loading bedgraph tracks

### ISSUE THREAD

**Issue by nlwashington** [igvteam/igv.js#184]
i've been able to successfully set up tracks using both plain bed and bigwig files.  however, i am unable to get it to display bedgraphs.

a bit of investigative work has tracked down that it might not be getting the proper decoder at the time of rendering, treating it as a standard bed.  the values from col 4 are then in a "name" field, instead of a "value" field.

furthermore, i am able to supply an index to the file, but it is not calling the loadFeaturesWithIndex with that file.

this is where my javascript capabilities end. any suggestions/fixes?
(i grunted to make igv.js on master after most recent commit https://github.com/igvteam/igv.js/commit/f8b73afaa0cafbdc0efc0d545318f3b3701ba070)

**Comment by jrobinso** [comment]
Does the filename end in ".bedgraph"?  If not you need to specify the 
format as "bedgraph" explicitly.   Also, indexes do not work with an 
wig-type file including bedgraph,  if the file is large convert it to 
"bigwig".

If you post your track configuration object I can suggest changes.

**Comment by nlwashington** [comment]
thanks @jrobinso.  sorry if i missed the documentation, but that wasn't clear to me...  my bedgraph was explicitly listed as ```format: "bedgraph"```, but i had it bgzipped with a gz extension, together with a tbi supplied in the indexURL.  

i've tried making changes as follows.  i've bgunzipped the file, and made sure the file name ends in ```.bedgraph```, and made the relevant changes.  here's part of my new config:
<pre>
                tracks.push({
                    url:  '/track_data/gencode_v23.hg38.bed',
                    name: "genes",
                    displayMode: "SQUISHED",
                    indexed: false
                },
                {
                    //testing loading this as a bed, to see where the regions should show up
                    url:  "/track_data/chunk.chr3.am.test.bedgraph",
                    name: "chunk.chr3.am as bed",
                    format: "bed",
                    indexed: false,
                    height: 30
                },
                {
                    url:  "/track_data/chunk.chr3.am.test.bedgraph",
                    name: "chunk.chr3.am.bedgraph",
                    format: "bedgraph",
                    height: 30
                }
                );
</pre>

here's a snippet of the bedgraph file:
<pre>
chr3    12022884        12022885        78
chr3    12022885        12022886        80
chr3    12022886        12022887        79
chr3    12022887        12022888        83
chr3    12022888        12022890        86
chr3    12022890        12022892        89
chr3    12022892        12022893        99
</pre>

and a screenshot:
<img width="908" alt="screen shot 2016-04-22 at 5 47 29 pm" src="https://cloud.githubusercontent.com/assets/5124411/14758255/5b660136-08b2-11e6-8e1f-4d342f337b22.png">

fyi, i tried loading the same file as either a bed or a bedgraph...the former just to visualize where we should see peaks.  
the data scale comes up as NaN, so i also tried manually resetting the data scale, but that didn't fix it either.

**Comment by jrobinso** [comment]
Could you make your whole file available?  This is what I see with the snippet, using the track config you provided

<img width="1363" alt="screen shot 2016-04-22 at 7 06 42 pm" src="https://cloud.githubusercontent.com/assets/933148/14758687/8348d628-08bd-11e6-8e8d-0520c258f8d1.png">

**Comment by jrobinso** [comment]
RE tabix, its not supported by IGV (or UCSC for that matter) for numeric "wig" type tracks such as bedgraph.   The "bigwig" format was created for that.  Bigwig files have aggregated data for all zoom levels, so you can support zooming out and in effeciently.    It would be possible to support tabix, but you would not see any data if you zoomed out too far (you would see the "zoom in to see features" message).

**Comment by nlwashington** [comment]
the same happens even with just that chunk as i pasted.

[chunktest2.bedgraph.txt](https://github.com/igvteam/igv.js/files/234966/chunktest2.bedgraph.txt)

**Comment by nlwashington** [comment]
FYI, I tested this with a locally grunted igv.js, and a remotely hosted (beta and rc1.0) igv.js.  (Apologies if it's something very strange on my end.)

**Comment by jrobinso** [comment]
Hi,  as I said above I can't reproduce the problem with that chunk (see screenshot above).   Could you send me your entire html file?  Remove all tracks except the bedgraph,  I will just change the URL to the bedgraph to my local copy.

**Comment by nlwashington** [comment]
I was able to successfully get a different bedgraph file to run just fine with rc1.0.  i'm going to close this ticket because it's a difficult to reproduce problem.
