### ISSUE TITLE
loadTracks example not working

### ISSUE THREAD

**Issue by mukamel-lab** [igvteam/igv.js#1841]
Thanks for the great software!

When I tried running the loadTracks example and select a track from the dropdown, I get an error:

`ReferenceError: igv is not defined
    at HTMLAnchorElement.onclick (loadTracks.html:70:37)`

I believe this can be solved by loading igv directly (not as a module):

```
  <script src="../dist/igv.min.js" type="text/javascript"> </script>
  <script>
  <!-- <script type="module"> -->

    <!-- import igv from "../dist/igv.esm.min.js" -->

    const options =
    {
      locus: "chr1:155,160,475-155,184,282",
      genome: "hg19"
    }
```

**Comment by jrobinso** [comment]
OK, thanks for the report, I see it as well.

**Comment by jrobinso** [comment]
Your fix will work, but I updated the example to a bit more modern javascript.   But either method is o.k.
