### ISSUE TITLE
Sequence Track not using nucleotideColors creation option

### ISSUE THREAD

**Issue by eternal-flame-AD** [igvteam/igv.js#1849]
Hi, this happened when I was validating function signature for the ts definitions, the sequence track does not use the `nucleotideColors` creation option. I git blamed to this commit:
https://github.com/igvteam/igv.js/commit/92c1ab93a3c444f5f328476fd319fc3ffe6e095d

I was confused, why take away an option that otherwise don't change anything? The commit message just says "Changes to support juicebox.js." I traced the linked PR and the issue board I don't find anything explaining this change. so i'm not sure.. 

If this is intended and there is a valid reason for that, I think it should be reflected on the API docs.

**Comment by jrobinso** [comment]
So is the report that the nucelotideColors option described here is ignored?  https://github.com/igvteam/igv.js/wiki/Browser-Creation

**Comment by eternal-flame-AD** [comment]
Yes
