### ISSUE TITLE
Gene symbol not visible when zoomed in

### ISSUE THREAD

**Issue by keithcallenberg** [igvteam/igv.js#185]
Currently the gene symbol is only being drawn in the center of the gene. If you zoom in to a region within the gene away from the center, the gene symbol is no longer visible. In desktop IGV, the gene symbol is always visible in the gene track, no matter the zoom level. Could we similarly have this in igv.js?

**Comment by jrobinso** [comment]
Yes, I can see the need for that, it is more difficult in igv.js but 
clearly we need some solution.  Its probably not possible to be sure the 
gene symbol is centered, but we should be able to insure it is visible 
at all zoom levels.

In the meantime you can click on the gene to discover its name.

**Comment by jrobinso** [comment]
Fixed by @skushch (#200)
