### ISSUE TITLE
Uncaught (in promise) RangeError: Invalid array length

### ISSUE THREAD

**Issue by nlwashington** [igvteam/igv.js#186]
Using [igv-1.0.0-rc1.js](https://igv.org/web/release/1.0.0-rc1/igv-1.0.0-rc1.js), I get the following error in my console:
```
Uncaught (in promise) RangeError: Invalid array length(…)
   (anonymous function) @ igv-1.0.0-rc1.js:3550
```
This seems to happen with a somewhat sizeable bigwig file, 58M, representing only chr22.

The file itself was created from a bedgraph --> bigwig using the UCSC bedGraphToBigWig conversion utility.  A smaller file (1.6M) converted from a subset of the same bedgraph data works just fine.

Is there a size limit we should be aware of?

**Comment by nlwashington** [comment]
Also, a 6.7M file is also fine.

**Comment by jrobinso** [comment]
Hi, there is no size limit, and we have loaded 3+GB bigwigs.  Is it possible to place the problematic bigwig in some location I can grab it?

**Comment by nlwashington** [comment]
I figured (hoped) that there wouldn't be a size limit (it didn't really make sense).  I've reproduced this with several files of various sizes.  

I've stuck a file in dropbox with some testing files:  
https://www.dropbox.com/s/srbiv8sbeszk3ap/igvtestfiles.tgz?dl=0

In the tgz, I have the original bedGraph file, together with it's bigwig version.  In addition, I have taken ```head -n 1000```, and made a bigwig of that.  The little file loads just fine into the igv.js browser.

I have a sneaky suspicion there might be an issue with the bedGraphToBigWig conversion utility.  I used the [pre-compiled version for mac os](http://hgdownload.cse.ucsc.edu/admin/exe/macOSX.x86_64/bedGraphToBigWig) dated 8-Mar-2016.  Just in case it was something funny with my computer, I tried recompiling it from source, but I've been unable to (I will try to troubleshoot that separately with the UCSC team-perhaps this is the root of the issue).  The next step would be to run the same utility on linux instead to see if it clears up the problem...if so, it's definitely something wrong with the binary.  I will investigate that tomorrow.

**Comment by jrobinso** [comment]
OK, so once I again I can load the file without issue.  I am suspecting something is not right with your web server (the server serving the bigwig file).   Specifically, that it does not support range-byte requests.  Nearly all servers do.   Could you confirm that it does, or does not?   

Here's what I see on chr22 for the large bw

<img width="1406" alt="screen shot 2016-04-26 at 8 02 19 pm" src="https://cloud.githubusercontent.com/assets/933148/14840559/346bb590-0bea-11e6-849e-d860c6e0d63a.png">

**Comment by jrobinso** [comment]
Now I'm fairly certain that is the issue.  I serverd your file from a development server that ignores range byte requests and got the same error.   Range-byte support is required for any indexed file.    Nearly all servers accept range-byte headers, what sort of server are you using?

RangeError: Invalid array length
    at http://localhost:63342/igv-web/js/bigwig/bwRPTree.js:88:33


I'm attempting to add an explicit error message for this condition.

**Comment by nlwashington** [comment]
Ok, I've been trying to track this down for the better part of the day.  I'm running a flask app, and now am setting my own content headers like:

```
@app.route('/track_data/<path>')
def track_data_files(path):
    full_path = os.path.join(os.path.dirname(__file__), TRACK_FILES_DIR, path)
    # TODO security check - only files under TRACK_FILES_DIR should be accessible

    headers = Headers()
    headers.add('Content-Disposition', 'attachment', filename=path)
    headers.add('Content-Transfer-Encoding', 'binary')

    status = 200
    size = os.path.getsize(full_path)
    begin = 0
    end = size-1

    if request.headers.has_key('Range'):
        status = 206
        headers.add('Accept-Ranges', 'bytes')
        ranges = re.findall(r"\d+", request.headers["Range"])
        begin  = int( ranges[0] )
        if len(ranges)>1:
            end = int( ranges[1] )
        headers.add('Content-Range','bytes %s-%s/%s' % (str(begin),str(end),str(end-begin)) )

    headers.add('Content-Length', str((end-begin)+1))

    response = Response(file(full_path), status=status, mimetype="application/octet-stream", headers=headers, direct_passthrough=True)

    return response
```

Now, I get past the error dealing with range queries specifically.  BUT, I now get that pesky array error again.  It seems it is tracked down to near line 3551 in igv.js code:
```
bufferedReader.dataViewForRange({start: filePosition, size: 4}, false).then(function (dataView) {
    var binaryParser = new igv.BinaryParser(dataView, self.littleEndian);

    var type = binaryParser.getByte();
    var isLeaf = (type === 1) ? true : false;
    var reserved = binaryParser.getByte();
    var count = binaryParser.getShort();
```
where it seems ```count=-30577```.
FWIW, I am running on MacOS 10.11.4, Chrome browser.

**Comment by nlwashington** [comment]
btw, what kind of server were you successful serving it from?

**Comment by jrobinso** [comment]
Hi,  this probably means you aren't actually returning the bytes requested, but something else.    Are you returning the entire file?  That's what it looks like.   Its not enough just to set the headers,  you have to return the bytes requested.  We are running Apache.

**Comment by jrobinso** [comment]
Implementing a production web server is not a trivial task,  I don't know much about Flask but if you have to code support for this yourself its surprising.   If you serve your files from any host other than the host serving the web page you'll also have to deal with CORS and preflight requests.

**Comment by nlwashington** [comment]
thanks @jrobinso.  still very pre-production, only on my laptop to try some things out.  i'll make sure i'm returning the right bytes.

**Comment by jrobinso** [comment]
If you're on a Mac you can use Apache, that's what I do, its already installed.   You can google on how to start it up.   It supports byte-range and all the neccessary CORs stuff out-of-the box.

**Comment by nlwashington** [comment]
Great, thanks.  
FYI, I was able to fix my code above, by refactoring the return:
```
    def generate(path, begin, end):
        with open(path, 'rb') as f:
            f.seek(begin)
            yield f.read(end-begin+1)

    response = Response(generate(full_path, begin, end), status=status, mimetype="application/octet-stream", headers=headers, direct_passthrough=True)

    return response
```

I will be looking at apache too as i move toward production.  Thank you so much for your help!

**Comment by jrobinso** [comment]
There are some notes in the “doc” folder of the git repo on setting up apache for development on the Mac.  It might be a little out of date and varies a little by Mac OS,  but its basically correct.

**Comment by nlwashington** [comment]
Thanks so much!

**Comment by blajoie** [comment]
I too am running into the same issue  (also using flask)  - could this somehow be related to large bigWig files (>4GB) causing some sort of overflow?  

My flask + igv.js is working AOK for all bigWig (except > ~8GB) ones.  No errors.  This error happens when serving up the large bigWig(s) from either a local proxy or through s3 links (which are not routed through my flask server)... 

With a large bigWig (10GB) igv.js is requesting negative byte ranges, and ends up making thousands of range requests (searching for tree leafs?) and ultimately crashes.

The large 10GB bigwig loads in AOK to the desktop IGV, suggesting the bigwig is intact.

Happy to share a large 10GB bigwig if it helps.

**Comment by jrobinso** [comment]
Perhaps the file offsets are so large they are overflowing the maxmium size
of an integer resulting in negative numbers.

Could you point me to a bigwig in s3 that exhibits this problem, and also a
query region to trigger the error?

This is not the same issue as originally reported, BTW.

**Comment by blajoie** [comment]
Fair point :)

I will open a new issue and provide an s3 file.  We too are fairly certain this has something to do the file_offsets overflowing.  Mind you this is an extreme case, this bedgraph->bigwig has a value at every genomic position.  Moving forward this can be condensed.
