### ISSUE TITLE
Alignment coverage track base mismatch depth indicator missing

### ISSUE THREAD

**Issue by dnil** [igvteam/igv.js#1860]
The coloured boxes representing base mismatches on the alignment coverage track appear to be missing on v3?
![Screenshot 2024-08-05 at 08 36 11](https://github.com/user-attachments/assets/2036332d-6c76-42f2-8019-f487deb598fb)

Compare (another variant) in 2.15.11:
![Screenshot 2024-08-05 at 08 42 59](https://github.com/user-attachments/assets/78b75545-7b6e-4ade-9996-8c31b0c01042)

Is there a config option? It appears the intention is still to have it when the (very cool) basemod track is switched off [here](https://github.com/igvteam/igv.js/blob/e199a169d3178b8cf5a0c267f5f00ef85f6b2cd4/js/bam/coverageTrack.js#L115)?

**Comment by jrobinso** [comment]
That certainly was not intentional,  we will fix it.  Thanks for the report.

**Comment by jrobinso** [comment]
This is fixed in v 3.0.1.

**Comment by dnil** [comment]
Thank you!
