### ISSUE TITLE
ERROR: Cannot read properties of undefined (reading 'table')

### ISSUE THREAD

**Issue by nictru** [igvteam/igv.js#1865]
Receied this error when loading a bigbed file. Surprises me as I was already able to load some other bigbed files.

Stacktrace says:
```
TypeError: Cannot read properties of undefined (reading 'table')
    at getDecoder (igv_dist_igv__esm__js.js?v=874868be:20757:112)
    at BWReader.getBedDataDecoder (igv_dist_igv__esm__js.js?v=874868be:21466:19)
    at BWReader.<anonymous> (igv_dist_igv__esm__js.js?v=874868be:21025:44)
```

When looking at the location in the source code, I assume the problem occurs in [this line](https://github.com/igvteam/igv.js/blob/c8fdb0e0e278d37f596f49087dce107d19a3a796/js/bigwig/bbDecoders.js#L5). Is it possible that `autoSql.table` is undefined?

**Comment by jrobinso** [comment]
Well apparently it is possible.   Is autoSql itself undefined?   I will add a check.

**Comment by nictru** [comment]
You are right; `autoSql` has to be undefined for this to occur - thanks in advance for adding the check!

**Comment by jrobinso** [comment]
Hmm, there's already a check in the line you reference.  What version are you using?

```
    if ("biginteract" === format || (autoSql && ('chromatinInteract' === autoSql.table) || 'interact' === autoSql.table)) {
```

**Comment by nictru** [comment]
I used 2.15 when the error first occurred, upgraded to 3.0.1 afterwards.

When looking at the check:
`(autoSql && ('chromatinInteract' === autoSql.table) || 'interact' === autoSql.table)`

Let`s say `autoSql` is undefined, then we get:
`(FALSE && ('chromatinInteract' === autoSql.table) || 'interact' === autoSql.table)`

which leads to
`(FALSE || 'interact' === autoSql.table)`

and then
`('interact' === autoSql.table)`

So yes there is a check, but the way the brackets are arranged it is not effective.
But should be an easy fix:

`if ("biginteract" === format || (autoSql && (('chromatinInteract' === autoSql.table) || ('interact' === autoSql.table)))) {`

**Comment by jrobinso** [comment]
Ahh yes, I see now, the parens are out of place, thanks.   That is a bug, will fix it.
