### ISSUE TITLE
BAM - Sort by base (alt-click) doesn't work for Capture Panels

### ISSUE THREAD

**Issue by david-ma** [igvteam/igv.js#187]
Is this a known issue? Sorting by base doesn't seem to work for Capture Panels.

(It worked ok for Amplicon Panels)

**Comment by jrobinso** [comment]
I'm not sure what a "capture panel" is,  or an "Amplicon panel" for that 
matter.

**Comment by david-ma** [comment]
Amplicon Panels have many reads with the exact same start/finish, so the BAM looks like a bunch of blocks in IGV
Reads from Capture Panels are staggered, so the reads look like waves in IGV

Do you have a different name for these panels? Like, targeted panels vs whole genome panels?

**Comment by jrobinso** [comment]
Sorry, I thought you were referring to some UI element ("Panel"). 
Sorting works fine for me,  could you give me a case I can reproduce.   
Specifically a small test bam where it doesn't work, and the steps you 
are taking to trigger the sort (e.g. by alt-clicking, or through some 
javascript code).

**Comment by david-ma** [comment]
Ok I'll prepare a small test bam that I can send out of the institute and get back to you.

**Comment by david-ma** [comment]
Oh! I updated to the latest IGV.js and it seems to work now. I'm not sure exactly how old the other IGV.js I was using was, between 1-2 months I think.

Here's the [example bam.zip](https://github.com/igvteam/igv.js/files/251595/example.bam.zip) anyway. It might be useful in future.
The locus is: 18:19750692-19752307
