### ISSUE TITLE
Htsget Bam support broken since v2.9.0

### ISSUE THREAD

**Issue by jmgenomics** [igvteam/igv.js#1870]
Following on from my colleague's [issue](https://github.com/igvteam/igv.js/issues/1691) a while back, I have been investigating why newer versions of IGV.js are no longer compatible with our Htsget server at Genomics England.  The last working version was v2.8.6.

My investigations have uncovered that the breakage occurred when code around Htsget support was refactored in commit [bcd4720](https://github.com/igvteam/igv.js/commit/bcd4720e880ef9f5a436bc16032f11a6a8e06c6c).

I have been able to determine the exact cause of the problem and have managed to fix it locally.

In `js/htsget/htsgetBamReader.js::readAlignments()` there are 2 problems:

1.  (minor issue) - `this.header.chrAliasTable` is undefined at runtime - I'm not sure of the purpose of the code and removed it.
2.  (major issue) - the call to `BamUtils.decodeBamHeader()` is happening too early, before the data has been loaded.  This has the effect that the `header.size` value passed into `BamUtils.decodeBamRecords()` is wrong.  Moving the header decoding call to after the data has been loaded and decompressed (`BGZip.unbgzf()`), fixed the issue.  

I have attached the fixed code and a visual diff for your perusal.  I'm happy to be added as a maintainer and push my branch too.

![IGV-screenshot](https://github.com/user-attachments/assets/bfd47a72-4201-4d34-aab1-654c58e4d3a5)
[htsgetBamReader.txt](https://github.com/user-attachments/files/16550007/htsgetBamReader.txt)

**Comment by jrobinso** [comment]
Unfortunately we can no longer support htsget as there are no reference test servers available, and the project itself does not seem to be active.   For example this ticket has been open for more almost 3 years, in fact there are no project updates in three years: https://github.com/ga4gh/htsget-refserver/issues/33.   

That said, your change should not affect any other code negatively so I would accept is as a PR.   I'm in general hesitant to accept PRs that I cannot personally test, but will make an exception in this special case.

**Comment by jmgenomics** [comment]
Thanks @jrobinso, happy to raise a PR for this.  I'm ready to push my branch - can you add me as a collaborator to the repo please?

**Comment by jrobinso** [comment]
@jmgenomics  You don't need to be a collaborator to submit a PR.

**Comment by jrobinso** [comment]
BTW the chr alias table is important and should not be removed.  Without it files aligned to a reference with UCSC naming conventions ("chr1", etc) cannot be read if the loaded reference uses the other convention ("1", etc).  

This is also the reason the header is read first.     It allows the chr alias table to be built.   Without this the query for alignments will fail if there is a mismatch in the chr naming convention. 

I don't understand why the code as is fails unless the server has not implemented the "class=header" query, in which case the server is non-conforming.    What is your server returning for the "readHeader" method, implementation below.

```
    async readHeaderData() {
        const url = `${getUrl(this.config)}?class=header&format=${this.format}`
        const ticket = await igvxhr.loadJson(url, buildOptions(this.config))
        return await this.loadUrls(ticket.htsget.urls)
    }
```

**Comment by jmgenomics** [comment]
Our Htsget server does support header queries and the data returned appears to be ok.

I think the issue with `header.chrAliasTable` being undefined may be due to `bamUtil.js::decodeBamHeader()`.  It [declares](https://github.com/igvteam/igv.js/blob/25c83c2404e05f5924fcff7839629644daa945aa/js/bam/bamUtils.js#L44) `chrAliasTable` but never assigns to  it after that?

**Comment by jmgenomics** [comment]
I looked back into the code history and found statements from the last working version that had been removed wrt population of `chrAliasTable`.

I have raised a [PR](https://github.com/igvteam/igv.js/pull/1872) for your consideration.

**Comment by jrobinso** [comment]
Thanks.  I see the issue but this is not the place to fix it.    That
unused chrAliasTable code in. BamUtils should have been removed.   I will
attempt another fix in a branch, and alert you so you can test it.   As
mentioned previously we have no server to test against.

**Comment by brainstorm** [comment]
> (...) we have no server to test against.

Yes, there is, see https://github.com/igvteam/igv.js/pull/1909#issuecomment-2502493072 and https://github.com/ga4gh/htsget-refserver/issues/33#issuecomment-3153155293
