### ISSUE TITLE
Track gene name for v2.15.13

### ISSUE THREAD

**Issue by ozlem-sevri** [igvteam/igv.js#1878]
Hello IGV team,

In the version 2.15.11 , I can track the name of gene without making any zoom out. But with the version 2.15.13 it does not work . I have to make zoom out to see gene name. Why it is changed? Can you make it also works v2.15.13 properly?

**v2.15.11**
![igv before](https://github.com/user-attachments/assets/8bfe82b3-8bbf-42a3-970f-83e5a5500536)

**v2.15.13**
![image (1)](https://github.com/user-attachments/assets/0b6c77cd-1b88-4f80-b49d-2e23e84b8f26)

![igv](https://github.com/user-attachments/assets/3cad9dc4-bf32-4014-8367-38dddfaf8ec9)

**Comment by jrobinso** [comment]
This is fixed in the latest version (3.0.4).
