### ISSUE TITLE
contrib: devcontainer config 

### ISSUE THREAD

**Issue by PeterKnealeCMRI** [igvteam/igv.js#1881]
I'd like to add a devcontainer config file to make it easier to run this project locally and contribute. I've included an example of one below. After cloning the repository and opening it in VSCode the user will be asked if they with to spin up a docker container and develop within that. This means the tooling and environment used to write the application can be made consistant and reliable. You can also spin up codespaces within github and develop using an 'on demand' instance when circumstances require it.  

> What are Development Containers?
A development container (or dev container for short) allows you to use a container as a full-featured development environment. It can be used to run an application, to separate tools, libraries, or runtimes needed for working with a codebase, and to aid in continuous integration and testing. Dev containers can be run locally or remotely, in a private or public cloud, in a variety of [supporting tools and editors](https://containers.dev/supporting).

Further info: https://code.visualstudio.com/docs/devcontainers/containers

```js
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/javascript-node
{
	"name": "Node.js",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm",
	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "npm install && npm install --global http-server",
	"portsAttributes": {
		"8080": {
			"label": "http-server"
		}
	}
	// Configure tool-specific properties.
	// "customizations": {},
	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

**Comment by PeterKnealeCMRI** [comment]
Further to this, when setting this project up locally I noticed that the [github action](https://github.com/igvteam/igv.js/blob/master/.github/workflows/ci_build.yml#L15) is using `node-version: '19.x'`

I'm not hugely familiar with the node / js ecosystem but I think its generally considered more reliable to stick to the even numbered releases. If using the above dev container it also means you can pin the same version in both your github action and devcontainer ensuring releases are built the same locally and within the CI process.
https://nodejs.org/en/about/previous-releases#release-schedule

**Comment by jrobinso** [comment]
I am not sure I understand the proposal,  do you want to add this file to the repository?   WRT node, there is nothing particularly special about even numbered releases.

**Comment by PeterKnealeCMRI** [comment]
Yes, I'd like to add a devcontainer file, I'll open a PR just to show you the file which might be simpler.

WRT node: the even numbered releases should be used for builds / releases.

https://nodejs.org/en/about/previous-releases#release-schedule
> Major Node.js versions enter Current release status for six months, which gives library authors time to add support for them. After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use. LTS release status is "long-term support", which typically guarantees that critical bugs will be fixed for a total of 30 months. Production applications should only use Active LTS or Maintenance LTS releases.

**Comment by jrobinso** [comment]
Thanks, I wasn't aware of this node number scheme.  However we aren't distributing a node app or imposing any particular version on developers.    Still good to know.

**Comment by PeterKnealeCMRI** [comment]
All good, I would still recommend updating this though...
```
- name: Use Node.js
  uses: actions/setup-node@v1
  with:
    node-version: '19.x' <-- 20.x
```
cheers
