### ISSUE TITLE
Loading from dropbx url is slow

### ISSUE THREAD

**Issue by aardes** [igvteam/igv.js#1883]
Since the latest release and update, loading data from Dropbox files or URLs become too slow on IGV online for the CRAM files. 

We tested the same URLs with the standalone IGV, and it works perfectly, but the online IGV does not. 

There is an issue with loading one of the files, there might be related to this issue.

<img width="1651" alt="Screenshot 2024-09-03 at 14 13 45" src="https://github.com/user-attachments/assets/9d31a9fb-adc7-46d2-8ef3-22bfc69efc9b">

I tried the older version by downloading the code and running it locally and it works fine.

**Comment by aardes** [comment]
Hi Jim,

I should have add this issue the igv-webapp. Am I correct?

**Comment by jrobinso** [comment]
I don't know where it belongs yet as I haven't had time to look into it.  Leave it here for now.

**Comment by jrobinso** [comment]
I think I can reproduce this issue but want to confirm.  Is the slowness with the initial load?  With my test file the initial load of the Cram is very slow.   After that, loading alignments as I jump to loci is fast.   Is this what you see?

**Comment by jrobinso** [comment]
Thanks for the report, I think this is fixed now with igv.js release 3.0.5 / igv-webapp release 2.0.4

**Comment by aardes** [comment]
Appreciate it, I've just checked and there is no issue anymore.
