### ISSUE TITLE
Save Image does not work when an Alignment track is grouped

### ISSUE THREAD

**Issue by milandomazet** [igvteam/igv.js#1886]
Hello,

it seems there is an error with saving the SVG/PNG image when an alignment track has been grouped. The problem is with the small roundRect that holds the group name.

<img width="712" alt="Screenshot 2024-09-04 at 17 00 00" src="https://github.com/user-attachments/assets/34f14f7f-767e-4d6d-a478-50e449140067">

Thanks!

Edit: I would be glad to help with this one but the whole SVG thing is a bit over my head and I hope it is a small/quick fix if one is familiar with it. :)

**Comment by milandomazet** [comment]
As far as I can see a quick fix is to just use rect instead of roundRect (it is not that much of a visual change and rect is already covered in the image generation class). The issue is that `pixelShift` which is used for the x coordinate is not present in the context when an image is being saved so it throws an error and the x coordinate is way off from what is seen on the screen (as it is Nan).

**Comment by turner** [comment]
@milandomazet can you copy/paste a session file for this error? thx.

**Comment by jrobinso** [comment]
@turner You can reproduce the error by loading any bam file and grouping, then saving an svg.  For example, run "dev/alignments/bamCSI.html".   Group by read strand (from the gear menu),  then save svg.  You'll see the error.  Apparently our svg ctx does not support roundRect.     Using a rect as suggested is probably fine.

```
Uncaught TypeError: ctx.roundRect is not a function
    at AlignmentTrack.draw (alignmentTrack.js:318:25)
    at BAMTrack.draw (bamTrack.js:206:33)
    at TrackViewport.draw (trackViewport.js:363:34)
    at TrackViewport.renderSVGContext (trackViewport.js:498:18)
    at TrackView.renderSVGContext (trackView.js:189:22)
    at Browser.toSVG (browser.js:439:23)
    at Browser.saveSVGtoFile (browser.js:453:30)
    at Object.click (saveImageControl.js:58:38)
    at HTMLDivElement.handleClick (popover.js:202:26)
```

**Comment by milandomazet** [comment]
> @turner You can reproduce the error by loading any bam file and grouping, then saving an svg. For example, run "dev/alignments/bamCSI.html". Group by read strand (from the gear menu), then save svg. You'll see the error. Apparently our svg ctx does not support roundRect. Using a rect as suggested is probably fine.
> 
> ```
> Uncaught TypeError: ctx.roundRect is not a function
>     at AlignmentTrack.draw (alignmentTrack.js:318:25)
>     at BAMTrack.draw (bamTrack.js:206:33)
>     at TrackViewport.draw (trackViewport.js:363:34)
>     at TrackViewport.renderSVGContext (trackViewport.js:498:18)
>     at TrackView.renderSVGContext (trackView.js:189:22)
>     at Browser.toSVG (browser.js:439:23)
>     at Browser.saveSVGtoFile (browser.js:453:30)
>     at Object.click (saveImageControl.js:58:38)
>     at HTMLDivElement.handleClick (popover.js:202:26)
> ```

Thanks @jrobinso! Just be mindful about the x coordinate and the pixelShift even with using `rect`
alignmentTrack.js:310
`const x = -options.pixelShift + options.viewportWidth - w - 10`

**Comment by turner** [comment]
@milandomazet we could fix this issue with the IGV library function:
`IGVGraphics.roundRect(ctx, x, baselineY - textMetrics.actualBoundingBoxAscent - 5, w, h, 2)`
This function implements roundRect with lower level constituent functions all of which are implemented in the - ancient - third party library `canvas2svg.js` that we use.

However, there is an canvas2svg.js` error we have to look into that is independent of this rect/roundRect issue.

Jim and I can take it from here. Cheers.

**Comment by jrobinso** [comment]
@milandomazet @turner Has this been fixed, tested?  I see a merged PR.

**Comment by turner** [comment]
@jrobinso checking now ...

**Comment by turner** [comment]
@jrobinso I see the PR but it was never merged. I'll double check and merge if needed.

**Comment by milandomazet** [comment]
Thanks a lot @turner @jrobinso!
