### ISSUE TITLE
Shift of -1bp in insertions displayed on igv.js

### ISSUE THREAD

**Issue by gemmabv** [igvteam/igv.js#1889]
Hi,
The position of a particular variant changes when displaying it on igv.js 

- Position of the variant in the gVCF and the CRAM file visualized at desktop IGV: 15-57232290-G-GA
- Position of the variant at igv.js: 15-57232289-A-AA

Is there any explanation and solution for that? The consequences of both variants are very different which can lead to a wrong interpretation.

Thanks

**Comment by jrobinso** [comment]
Could you provide an example file or VCF record?  Also, where do the position strings come from, particularly the GA vs AA?  Is that in the popup text?

**Comment by jrobinso** [comment]
Also,  what versions of igv.js and IGV are you using?

**Comment by gemmabv** [comment]
Hi,
In the gVCF the only variant in this region is this one:
chr15 57232290    .     G     GA,<NON_REF>      557.60      .     BaseQRankSum=-2.005;DP=38;ExcessHet=3.0103;MLEAC=1,0;MLEAF=0.500,0.00;MQRankSum=0.000;RAW_MQandDP=136800,38;ReadPosRankSum=0.182    GT:AD:DP:GQ:PL:SB 0/1:18,18,1:37:99:565,0,561,619,616,1235:6,12,7,12

Igv.js version is 2.6.1
Local IGV: Version 2.16.0 01/25/2023 01:50 PM

**Comment by jrobinso** [comment]
The current version of igv.js is 3.0.5.   Version 2.6.1 is over 4 years old.

This record indicates an insertion of a single base A just after the G at position 57232290.   In other words between reference location 57232290 and 57232291.   igv.js displays insertions where they occur, that is between reference locations

<img width="141" alt="Screenshot 2024-09-10 at 9 16 28 AM" src="https://github.com/user-attachments/assets/a6559041-65bb-453e-9738-8c769ff3603c">

IGV desktop uses a different convention, displaying insertions at the genomic location just before

<img width="143" alt="Screenshot 2024-09-10 at 9 20 53 AM" src="https://github.com/user-attachments/assets/dd460299-32dc-4abd-b7ed-15823b59bbb7">

I can't speak to the convention used in 2.6.1 (either base before or base after),  drawing the insertion between flanking bases eliminates the ambiguity.
