### ISSUE TITLE
Searching the region by gene name is not working

### ISSUE THREAD

**Issue by gunho-park** [igvteam/igv.js#189]
Hello, Mr. Robinson.

First of all, I deeply thank for making us use igv.js.

Unfortunately, it seems searching the region by gene name is currently not working.

Could you check this issue?

Cheers.

**Comment by jrobinso** [comment]
You'll have to be more specific about the problem.   At the moment Broad servers are down,  so that could be the cause.

**Comment by gunho-park** [comment]
Right, that would be the cause.

I'll wait till the server is fine.

Thanks.

**Comment by jrobinso** [comment]
Apologies, this is a rare occurence.
