### ISSUE TITLE
IGV gene locus not updated with new gene's name (GBA1 vs. GBA)

### ISSUE THREAD

**Issue by yaarau** [igvteam/igv.js#1891]
Using IGV.js, when looking for GBA1 using the IGV “search through position”, I get an "Unrecognized Locus: GBA1" message.
The URL used for this search: https://igv.org/genomes/locus.php?genome=hg38&name=GBA1
gives an empty result.
However, when searching for GBA (the old name of GBA1):
https://igv.org/genomes/locus.php?genome=hg38&name=GBA
I get a result: GBA chr1:155234451-155244627 s3 hg38

Since GBA1 is the updated name of the gene, it appears the "search through position" option is not updated with current gene names according to HGNC (at least for this gene).

**Comment by jrobinso** [comment]
This is fixed
