### ISSUE TITLE
`flanking` argument isn't applied to the locus when `search` parameter is also supplied

### ISSUE THREAD

**Issue by audsc** [igvteam/igv.js#1892]
It appears that the `flanking` configuration option is not picked up if a `search` parameter is included in the igv configuration option that uses the `processSearchResult` method. Our team is going to use the `coords` argument to pad the front of the search, however it would be ideal to be able to use the flanking option as it is documented + would pad the start and end from my understanding. This is the processSearchResult function:

`function processSearchResult(browser, result, searchConfig) {

    let results

    if ('plain' === searchConfig.type) {
        results = parseSearchResults(browser, result)
    } else {
        results = JSON.parse(result)
    }

    if (searchConfig.resultsField) {
        results = results[searchConfig.resultsField]
    }

    if (!results || 0 === results.length) {
        return undefined

    } else {

        const chromosomeField = searchConfig.chromosomeField || "chromosome"
        const startField = searchConfig.startField || "start"
        const endField = searchConfig.endField || "end"
        const coords = searchConfig.coords || 1

        let result
        if (Array.isArray(results)) {
            // Ignoring all but first result for now
            // TODO -- present all and let user select if results.length > 1
            result = results[0]
        } else {
            // When processing search results from Ensembl REST API
            // Example: https://rest.ensembl.org/lookup/symbol/macaca_fascicularis/BRCA2?content-type=application/json
            result = results
        }

        if (!(result.hasOwnProperty(chromosomeField) && (result.hasOwnProperty(startField)))) {
            console.error("Search service results must include chromosome and start fields: " + result)
        }

        const chr = result[chromosomeField]
        let start = result[startField] - coords
        let end = result[endField]
        if (undefined === end) {
            end = start + 1
        }

        const locusObject = {chr, start, end}

        // Some GTEX hacks
        const type = result.type ? result.type : "gene"
        if (searchConfig.geneField && searchConfig.snpField) {
            const name = result[searchConfig.geneField] || result[searchConfig.snpField]  // Should never have both
            if (name) locusObject.name = name.toUpperCase()
        }

        return locusObject
    }
}`

**Comment by jrobinso** [comment]
OK thanks for the report.  I'm transferring this to igv.js

**Comment by jrobinso** [comment]
Flanking is applied downstream of the search.  It is only applied to searches by feature name, flanking is not applied to a "search" with explicit coordinates (e.g. chr1:100-200).   The test is to look for a "name" field in the returned search result

```
        // If a flanking region is defined, and the search object is a feature (has a name) type, adjust start and end
        if (browserFlanking && locus.name) {
            locus.start = Math.max(0, locus.start - browserFlanking)
            locus.end += browserFlanking
        }
```

In looking into this I discovered the  documentation for custom search is incomplete. You should include the string searched for as a "name" field to invoke flanking.   So the result from the documentation example should be

```
[{"chromosome": "chr17", "start":7572927, "end":7579912, "name": "TP53"}]
```

**Comment by audsc** [comment]
Hello @jrobinso ! Do you think we are using flanking incorrectly? We are seeing it append to the locus like so `14:24,304,186-243,114,301,000` (where the locus is `14:24,304,186-243,114,30`).

Here is how we are passing it to the browser configuration options:
```
     const options = {
        reference: genome reference object with our urls,
        search: {
          url: url to our http web service,
          chromosomeField: 'chr',
          name: 'symbol',
        },
        flanking: 1000,
      };
```
      
 In the current version, the search service only works when we set flanking to null explicitly. Thank you in advance!

**Comment by jrobinso** [comment]
Sorry I don't understand the question.   Flanking will only be applied if the objects returned by the search service include a "name" property.  The configuration looks correct, but what does your custom search service return?

**Comment by audsc** [comment]
Hi @jrobinso ! I could be mistaken but I believe we are currently hitting the flanking code -- 
```function createReferenceFrameList(loci, genome, browserFlanking, minimumBases, viewportWidth, isSoftclipped) {

    return loci.map(l => {

        const locus = Object.assign({}, l)  // Copy as we might mutate this object

        // If a flanking region is defined, and the search object is a feature (has a name) type, adjust start and end
        if (browserFlanking && locus.name) {
            locus.start = Math.max(0, locus.start - browserFlanking)
            locus.end += browserFlanking
        }

        // Validate the range.  This potentionally modifies start & end of locus.
        if (!isSoftclipped) {
            const chromosome = genome.getChromosome(locus.chr)
            validateGenomicExtent(chromosome.bpLength, locus, minimumBases)
        }

        const referenceFrame = new ReferenceFrame(
            genome,
            locus.chr,
            locus.start,
            locus.end,
            (locus.end - locus.start) / viewportWidth
        )

        return referenceFrame
    })
}```

That is the only explanation I can see for why 1000 is being appended to the end of the range unless we explicitly set flanking to null like this:

```      const options = {
        reference: genomeReference,
        search: {
          url: `${environment.trackGeneratorBaseUrl}/symbol-locus?symbol=$FEATURE$&genome=${this.genomeCombined}`,
          chromosomeField: 'chr',
          displayName: 'symbol',
        },
        flanking: null,
      };
      ```
      
 If we don't include a flanking parameter of null , it defaults to `1,000` and tries to append that to the end of the returned range.
 
 Our search service returns these fields for reference.
 
 [{"chr":"...","start":"...","end":"...","symbol":"..."}]
 
Thank you in advance!

**Comment by jrobinso** [comment]
As I indicated above, your service must return the "name" property if you want flanking applied.    Did you see that?  I'll repeat it here



`
You should include the string searched for as a "name" field to invoke flanking.   So the result from the documentation example should be
`
```
[{"chromosome": "chr17", "start":7572927, "end":7579912, "name": "TP53"}]
```

**Comment by audsc** [comment]
Hi @jrobinso I did see that thank you! We are looking into adding that to our webservice. I am confused however why 1000 is being appended to the end of our range (and 1000 is being correctly subtracted), unless we explicitly set flanking to null. Can you help me with that?

**Comment by audsc** [comment]
Additionally, I can't find anywhere in the igv code where the webservice search is grabbing a `searchConfig.name` parameter. Can you help me understand what I am missing?

```
function processSearchResult(browser, result, searchConfig) {

    let results

    if ('plain' === searchConfig.type) {
        results = parseSearchResults(browser, result)
    } else {
        results = JSON.parse(result)
    }

    if (searchConfig.resultsField) {
        results = results[searchConfig.resultsField]
    }

    if (!results || 0 === results.length) {
        return undefined

    } else {

        const chromosomeField = searchConfig.chromosomeField || "chromosome"
        const startField = searchConfig.startField || "start"
        const endField = searchConfig.endField || "end"
        const coords = searchConfig.coords || 1


        let result
        if (Array.isArray(results)) {
            // Ignoring all but first result for now
            // TODO -- present all and let user select if results.length > 1
            result = results[0]
        } else {
            // When processing search results from Ensembl REST API
            // Example: https://rest.ensembl.org/lookup/symbol/macaca_fascicularis/BRCA2?content-type=application/json
            result = results
        }

        if (!(result.hasOwnProperty(chromosomeField) && (result.hasOwnProperty(startField)))) {
            console.error("Search service results must include chromosome and start fields: " + result)
        }

        const chr = result[chromosomeField]
        let start = result[startField] - coords
        let end = result[endField]
        if (undefined === end) {
            end = start + 1
        }

        const locusObject = {chr, start, end}

        // Some GTEX hacks
        const type = result.type ? result.type : "gene"
        if (searchConfig.geneField && searchConfig.snpField) {
            const name = result[searchConfig.geneField] || result[searchConfig.snpField]  // Should never have both
            if (name) locusObject.name = name.toUpperCase()
        }

        return locusObject
    }
}
```

I do see this, but I don't know how it would hit that && based on the comment. Thank you so much in advance!!!
```
 if (searchConfig.geneField && searchConfig.snpField) {
            const name = result[searchConfig.geneField] || result[searchConfig.snpField]  // Should never have both
            if (name) locusObject.name = name.toUpperCase()
        }

```

**Comment by audsc** [comment]
I believe we need:
```        if (browserFlanking && locus.name) {
            locus.start = Math.max(0, locus.start - browserFlanking)
            locus.end = Number(locus.end) + browserFlanking
        }
```

instead of 
```        if (browserFlanking && locus.name) {
            locus.start = Math.max(0, locus.start - browserFlanking)
            locus.end += browserFlanking
        }
```

But you would know the implications of this better. Thank you in advance.

**Comment by jrobinso** [comment]
Sorry I don't have time to revisit this, but if you include the "name" field in your search results flanking will be applied.   Try this.

**Comment by jrobinso** [comment]
One other thing, and this might be part of your issue,  you should return integers for  start and end, not strings.
