### ISSUE TITLE
Issue in RefSeq reference

### ISSUE THREAD

**Issue by aardes** [igvteam/igv.js#1893]
Hi,

I noticed some issues with the latest IGV online regarding the RefSeq track. Apparently in the newest version you used the wrong RefSeq.

Please take a look at this image:

<img width="1908" alt="Screenshot 2024-09-16 at 10 35 20" src="https://github.com/user-attachments/assets/037aa522-2579-4fe2-bc2d-743114949a44">

The image is an old version of IGV.js which shows the RefSeq tracks for a gene named: PKD1, if you search for the same gene in the latest version ( lower image) you see that the track does not show the gene. 

I tried it for both GRCh37 and 38 and both are the same. 

Regards
Amin

**Comment by aardes** [comment]
@jrobinso sorry that I have to tag you, could you please let me know what do you think?

**Comment by jrobinso** [comment]
Refseq is updated regularly,  I can't comment on specific genes but igv is using the "correct" files, specifically

hg38: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz

hg19: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz

Note the scrollbar on the gene track, you aren't seeing everything.    Try scrolling or setting the track height to a larger value, like 500.  Here's what I see for hg19

<img width="1681" alt="Screenshot 2024-09-26 at 2 14 04 PM" src="https://github.com/user-attachments/assets/91b06136-0386-47cd-bf4c-c4cdd151d862">

**Comment by aardes** [comment]
Indeed I tried the scrollbar but nothing was there and interestingly I can see it now, it might becouse of my network or something temporary, thanks a lot.
