### ISSUE TITLE
Can't see any alignments on "M" chromosome when using chromosome alias tab files

### ISSUE THREAD

**Issue by northwestwitch** [igvteam/igv.js#1896]
Hello, our mitochondrial variants contain chromosome "M", both on VCF files and bam alignments. When trying to create the igv display object, the alignments fail to show up. We believe it's because chromosome "M" is not recognised in the chromosome alias file used by our browser (`https://s3.amazonaws.com/igv.org.genomes/hg38/hg38_alias.tab`)

Here is the line in the alias file:

<img width="454" alt="image" src="https://github.com/user-attachments/assets/c63ec969-84cb-402a-8c7b-71bf005a60fb">

Would it be possible to add the "M" chromosome as an alias to the tab files? Both the one I mentioned above and the one for genome build hg19 (`https://s3.amazonaws.com/igv.org.genomes/hg19/hg19_alias.tab`) ?

Many thanks! Chiara

**Comment by jrobinso** [comment]
Done, but please update your alias URLs to 

```
https://igv.org/genomes/data/hg38/hg38_alias.tab
https://igv.org/genomes/data/hg19/hg19_alias.tab
```

The most recent versions of hg19.json and hg38.json use these.

Also, just a note.  Previous versions of IGV have incorrectly aliased chrM and MT for hg19.  These are actually different sequences.

**Comment by northwestwitch** [comment]
Thank you! @jrobinso! 🙏🏻
