### ISSUE TITLE
turning autoHeight = true requires users to set the track height twice using the gear icon

### ISSUE THREAD

**Issue by edlynhaynes** [igvteam/igv.js#1897]
We're currently making use of the autoHeight property in our code. If it's currently set to true, then we try to manually set the track height using the gear icon, nothing happens at first. We'd have to click the gear icon again then set the track height. We noticed that autoHeight is getting set to false in the callback function below, but wanted to see if it can be done before setting the minHeight and maxHeight?

                // Explicitly setting track height turns off autoHeight
                trackView.track.autoHeight = false;

function trackHeightMenuItem(trackView) {

    const click = e => {

        const callback = () => {

            const number = Number(trackView.browser.inputDialog.value, 10);

            if (undefined !== number) {

                // If explicitly setting the height adust min or max, if neccessary.
                if (trackView.track.minHeight !== undefined && trackView.track.minHeight > number) {
                    trackView.track.minHeight = number;
                }
                if (trackView.track.maxHeight !== undefined && trackView.track.maxHeight < number) {
                    trackView.track.minHeight = number;
                }
                trackView.setTrackHeight(number, true);

                trackView.checkContentHeight();
                trackView.repaintViews();

                // Explicitly setting track height turns off autoHeight
                trackView.track.autoHeight = false;
            }

        };

        const config =
            {
                label: 'Track Height',
                value: trackView.track.height,
                callback
            };

        trackView.browser.inputDialog.present(config, e);

    };

    const object = $$1('<div>');
    object.text('Set track height');
    return {object, click}

}

**Comment by jrobinso** [comment]
Yes, good catch.
