### ISSUE TITLE
Hub missing cytoband

### ISSUE THREAD

**Issue by Kahl84** [igvteam/igv.js#1900]
I am trying to create a react component that integrates IGV for ROS_Cfam_1.0 but I get a console error Error loading IGV: TypeError: Cannot read properties of undefined (reading 'cytobandURL') below the code. What I am missing?

const chromosome = geneData?.chromosomes?.[0] || "1"; // Ensure we get chromosome from geneData
      const start =
        geneData?.annotations?.[0]?.genomic_locations?.[0]?.genomic_range
          ?.begin || 100000;
      const end =
        geneData?.annotations?.[0]?.genomic_locations?.[0]?.genomic_range
          ?.end || 200000;

      // IGV options using the UCSC hub URL for ROS_Cfam_1.0
      const igvOptions = {
        locus: `${chromosome}:${start}-${end}`, // Set locus dynamically from geneData
        genome: "GCF_014441545.1", // genome ID, but will be fetched from the hub
        tracks: [
          {
            name: "Gene Annotations",
            type: "annotation",
            url: "https://genark.s3.amazonaws.com/dog_genome.gff3", // Update with real track URL
          },
        ],
        // Add the UCSC Genome Browser Hub URL
        hubUrl:
          "https://hgdownload.soe.ucsc.edu/hubs/GCF/014/441/545/GCF_014441545.1/hub.txt",
      };

**Comment by jrobinso** [comment]
Have you checked the igv.js documentation?

**Comment by Kahl84** [comment]
I did but I couldn't find how that could help me? maybe if you have more specific pointers I would appreciated it. Thank you!

**Comment by Kahl84** [comment]
I tried a super simple implementation using the documentation here: here: https://igv.org/doc/igvjs/#Reference-Genome/ and test UCSC GenArk assembly GCA_000002305.1 with the following code (tracks removed to avoid complexity)
```

import React, { createRef, Component } from "react";

const igvStyle = {
  fontFamily:
    "open sans,helveticaneue,helvetica neue,Helvetica,Arial,sans-serif",
  paddingTop: "60px",
  margin: "5px",
};

class IGVViewer extends Component {
  constructor(props) {
    super(props);
    this.container = createRef(null);
  }

  componentDidMount() {
    // Load igv.js dynamically from a CDN
    const script = document.createElement("script");
    script.src = "https://cdn.jsdelivr.net/npm/igv@2.9.4/dist/igv.min.js";
    script.async = true;
    script.onload = () => {
      const { geneData } = this.props;

      // Extract chromosome, start, and end from geneData
      let chromosome = geneData?.chromosomes?.[0] || "NC_051843.1"; // Default chromosome for testing
      const start =
        geneData?.annotations?.[0]?.genomic_locations?.[0]?.genomic_range
          ?.begin || 100000;
      const end =
        geneData?.annotations?.[0]?.genomic_locations?.[0]?.genomic_range
          ?.end || 200000;

      // IGV Options, using GenArk genome reference
      const igvOptions = {
        genome: "GCA_000002305.1", // Replace with any valid GenArk genome ID
        locus: `${chromosome}:${start}-${end}`, // Set locus dynamically from geneData
        tracks: [], // No tracks for now, can add later
      };

      // Log the full IGV options object to verify URLs and locus
      console.log("IGV Options:", igvOptions);

      // Initialize IGV browser
      window.igv
        .createBrowser(this.container.current, igvOptions)
        .then((browser) => {
          console.log("IGV Viewer successfully loaded.");
          // Log the initialized IGV browser to verify further
          console.log(browser);
        })
        .catch((error) => {
          console.error("Error loading IGV:", error);
        });
    };
    document.body.appendChild(script);
  }

  render() {
    return <div id="igv-div" ref={this.container} style={igvStyle}></div>;
  }
}

export default IGVViewer;
```
but I get Unknown genome id: GCA_000002305.1 and I am not sure why.

**Comment by jrobinso** [comment]
What version of igv.js are you using?  This is important.

**Comment by jrobinso** [comment]
Here's a complete working example

```html
<html>

<body>

<div id="igvDiv"></div>

<script type="module">

    import igv from "https://cdn.jsdelivr.net/npm/igv@3.0.7/dist/igv.esm.min.js"

   igv.createBrowser(document.getElementById('igvDiv'), {genome: "GCA_000002305.1"})

</script>

</body>

</html>
```

**Comment by Kahl84** [comment]
I am using the latest version of IGV.js. Your solution actually made it work, now moving to tracks creation. Sharing the code here just for reference for other people

`import React, { createRef, Component } from "react";

const igvStyle = {
  fontFamily: "open sans, Helvetica, Arial, sans-serif",
  paddingTop: "60px",
  margin: "5px",
};

class IGVViewer extends Component {
  constructor(props) {
    super(props);
    this.container = createRef(null);
  }

  componentDidMount() {
    // Dynamically load IGV.js from a CDN
    const script = document.createElement("script");
    script.src = "https://cdn.jsdelivr.net/npm/igv@3.0.7/dist/igv.min.js";
    script.async = true;

    script.onload = () => {
      const { geneData, type, variants } = this.props;

      // Extract chromosome, start, and end from geneData
      const chromosome = geneData?.chromosomes?.[0] || "NC_051843.1"; // Default chromosome
      const start =
        geneData?.annotations?.[0]?.genomic_locations?.[0]?.genomic_range
          ?.begin || 100000;
      const end =
        geneData?.annotations?.[0]?.genomic_locations?.[0]?.genomic_range
          ?.end || 200000;

      // Log values to verify correctness
      console.log("Chromosome:", chromosome);
      console.log("Start:", start);
      console.log("End:", end);

      // Ensure locus string matches IGV format: "chromosome:start-end"
      const locus = `${chromosome}:${start}-${end}`;
      console.log("Locus being set:", locus); // Log the formatted locus

      let genomeID = "GCA_000002305.1"; // Default Genome ID
      if (type === "ROS_Cfam_1.0") {
        genomeID = "GCA_000002305.1"; // Genome ID for ROS_Cfam_1.0
      } else if (type === "CanFam3.1") {
        genomeID = "GCA_placeholder1"; // Genome ID for CanFam3.1
      } else if (type === "BROADD2") {
        genomeID = "GCA_placeholder2"; // Genome ID for BROADD2
      } else if (type === "Felis_catus_9.0") {
        genomeID = "GCA_placeholder3"; // Genome ID for Felis_catus_9.0
      } else if (type === "Felis_catus_6.2") {
        genomeID = "GCA_placeholder4"; // Genome ID for Felis_catus_6.2
      } else if (type === "EquCab3.0") {
        genomeID = "GCA_placeholder5"; // Genome ID for EquCab3.0
      } else if (type === "EquCab2") {
        genomeID = "GCA_placeholder6"; // Genome ID for EquCab2
      }

      // Prepare the variant track data, limiting to the first 10 variants
      const limitedVariants = variants.slice(0, 10);

      const variantTrack = {
        name: "Custom", // Track label
        type: "annotation",
        displayMode: "EXPANDED",
        color: "blue", // Set variant color
        height: 100, // Track height
        labels: true, // Show variant labels
        features: limitedVariants.map((variant, index) => ({
          chr: variant.seq_region_name,
          start: variant.start,
          end: variant.end,
          name: variant.id,
          alleles: variant.alleles.join("/"),
          row: index, // Assign row for layout in the track
        })),
      };

      // Log the variant track data to see what we are passing to IGV
      console.log("Variant Track Data:", variantTrack);

      // IGV options, using GenArk genome reference and default locus
      const igvOptions = {
        genome: genomeID, // Use GenArk genome ID
        locus: locus, // Use dynamic locus
        tracks: [variantTrack], // Add the variant track
      };

      // Log the full IGV options object to verify everything being passed
      console.log("IGV Options:", igvOptions);

      // Initialize IGV browser
      window.igv
        .createBrowser(this.container.current, igvOptions)
        .then((browser) => {
          console.log("IGV Viewer successfully loaded.", browser);

          // Explicitly set the locus after the browser is initialized
          browser
            .search(locus)
            .then(() => {
              console.log("Locus set successfully:", locus);
            })
            .catch((error) => {
              console.error("Error setting locus:", error);
            });
        })
        .catch((error) => {
          console.error("Error loading IGV:", error);
        });
    };

    document.body.appendChild(script);
  }

  render() {
    return <div id="igv-div" ref={this.container} style={igvStyle}></div>;
  }
}

export default IGVViewer;
`

**Comment by jrobinso** [comment]
@Kahl84 As I pointed out to you earlier you can use igv.org/app and export a session, and then customized it as you wish (for example removing tracks).  WRT VCF see its documentation, you might find some online tutorials on VCFs.
