### ISSUE TITLE
Locus search is case-sensitive in 3.0

### ISSUE THREAD

**Issue by ajw725** [igvteam/igv.js#1904]
I'm not sure if this was an intentional change, but I figured I'd ask. We have some sequence names in our fasta files with letters in them, e.g. "Q123." These names are capitalized in the fasta we're loading as a reference, but our application provides them to IGV.js as lower-case when we initialize the browser or search for a locus, e.g. "q123." This worked fine in version 2.x, apparently because the alias names [were all lower-cased](https://github.com/igvteam/igv.js/blob/079641a71a01d02e4a858a7bbab3bd2efc1340be/js/genome/genome.js#L178), but it doesn't work in 3.x, because the names are both stored and looked up exactly as provided. We now get this error:
```
browser.js:777 Uncaught (in promise) Error: Cannot set initial locus q123
    at fA.loadReference (browser.js:777:19)
    at async fA.loadSessionObject (browser.js:631:9)
    at async Object.createBrowser (igv-create.js:78:18)
```

Example track config, with files attached (had to add `.txt` to upload them):
```json
{
  "reference": {
    "id": "Custom",
    "name": "Custom Reference",
    "fastaURL": "example.fasta",
    "displayMode": "EXPANDED",
    "order": 1,
    "indexURL": "example.fasta.fai"
  },
  "tracks": []
}
```
[example.fasta.txt](https://github.com/user-attachments/files/17469639/example.fasta.txt)
[example.fasta.fai.txt](https://github.com/user-attachments/files/17469638/example.fasta.fai.txt)

This doesn't seem like a completely unreasonable change, and I think the real fix for us is to provide the value with the same casing in both places, but was it an expected change from v2 to v3?

**Comment by jrobinso** [comment]
This was not intentional,  I will look into it.   Consider this a bug.
