### ISSUE TITLE
No data for chrX and chrY for GRCh37

### ISSUE THREAD

**Issue by 1pratham** [igvteam/igv.js#1912]
Issue on: igv.js v3.0.0 and up
Track data missing for almost all track types in chrX and chrY only for GRCh37 reference. Tracks works fine for GRCh38 reference

![image](https://github.com/user-attachments/assets/cb233536-8d9e-4ddc-ba43-850fad22bba6)

Working fine for v2.15.13
![image](https://github.com/user-attachments/assets/bd7d3ced-6ee1-41dc-b543-efd7f492e69e)

I tried to compare both versions but can't find the cause. If someone can point me in the right direction, I am willing to do a PR fix.

Thank you

**Comment by jrobinso** [comment]
How are the X & Y chromosomes named in your data files?

**Comment by 1pratham** [comment]
1, 2, ..., X, Y format without 'chr'

**Comment by jrobinso** [comment]
Can you load this data at igv.org/app?

**Comment by jrobinso** [comment]
BTW there is no code involved here, aliasing is configured in  the genome definition.   The current definition for hg19 is below.  The aliases are defined in https://igv.org/genomes/data/hg19/hg19_alias.tab

```
  {
    "id": "hg19",
    "name": "Human (GRCh37/hg19)",
    "fastaURL": "https://igv.org/genomes/data/hg19/hg19.fasta",
    "indexURL": "https://igv.org/genomes/data/hg19/hg19.fasta.fai",
    "cytobandURL": "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/cytoBand.txt.gz",
    "aliasURL": "https://igv.org/genomes/data/hg19/hg19_alias.tab",
    "twoBitURL": "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.2bit",
    "chromSizesURL": "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes",
    "tracks": [
      {
        "name": "Refseq Curated",
        "format": "refgene",
        "url": "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeqCurated.txt.gz",
        "indexed": false,
        "order": 1000000,
        "infoURL": "https://www.ncbi.nlm.nih.gov/gene/?term=$$"
      }
    ],
    "chromosomeOrder": "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY"
  },
```

**Comment by 1pratham** [comment]
I converted bigwig to bedgraph and added chr to each line
For v3.0.0, the bedgraph without chr has issue and one with chr is working fine
![image](https://github.com/user-attachments/assets/b4945895-2c04-4064-9b64-fe5bde8a7c09)

For v2.15.13 both with and without chr works
![image](https://github.com/user-attachments/assets/56125405-ac93-4970-8b93-eb9329637f2c)


I added the two files in igv.org/app (I am not sure how to change the track type) but both of them show data 
![image](https://github.com/user-attachments/assets/49978f53-4282-4536-8c11-0a93b8665fa5)

I think the issue is for bam and wig track types. Anyway I added manually the aliasUrl in genome definition and it worked even in v3.0.0. However, it works by default (without aliasUrl) in v2.15.13. So something is amiss.

**Comment by jrobinso** [comment]
The alias file is necessary with igv.js 3.0, if you don't explicitly alias X and chrX you will not see data.    I don't understand how VCF tracks would work without an alias definition.

**Comment by 1pratham** [comment]
Well, will close the issue if alias file is required.

Just a quick question before though, does it need to be a file url or are
there other options for aliasing like directly defining it in code? If yes,
can you point me to an example?

Thank you

**Comment by jrobinso** [comment]
You need to supply an alias file,  otherwise you get the defaults.   I don't have time to look into this now but if you want to try to add chrX -> X to the defaults the file is "js/genome/chromAliasDefaults.js".

**Comment by jrobinso** [comment]
I've added X and Y to the defaults.  If you want to pull and build from source to test please update here with the results.

**Comment by 1pratham** [comment]
It works.. Thank you for the quick fix. Any ETA on a new release?
