### ISSUE TITLE
How do I add a gene track for hg19? 

### ISSUE THREAD

**Issue by dexon9109** [igvteam/igv.js#1921]
I see that the `RefGene` file of **hg38** is provided in the example, but I failed to download the `Refgene` file of **hg19**. Could you please help me? Thank you.

**Comment by jrobinso** [comment]
I'm not sure what you are trying to do, but you can download the refgene track file here:  https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz
