### ISSUE TITLE
VCFs with tab at the end of line not loading data

### ISSUE THREAD

**Issue by pratham-emedgene** [igvteam/igv.js#1922]
I tried to load a vcf to [igv.org/app ](https://igv.org/app/) and it didn't show any variants. On checking the vcf, I noticed there were tabs at the end of each line. So I removed the tabs from some lines and then the corresponding data showed up. 
![image](https://github.com/user-attachments/assets/71357500-7892-44ec-a0f3-7f9fd748dde0)
![image](https://github.com/user-attachments/assets/9e75e12c-779e-481f-aed7-7344ae6a35d2)

Attaching the file itself for reference.
[tab_test.vcf.gz](https://github.com/user-attachments/files/18094179/tab_test.vcf.gz)

Unfortunately, we have lots of such files and hoping something could be fixed at igv.js side.

I am happy to work on it if someone can point me to the relevant code. 
Thank you

**Comment by jrobinso** [comment]
There are other whitespace problems with this file, I tried to validate it with the htsjdk and ran into this right away, although igv.js lets it slide.  

```
The VCF specification does not allow for whitespace in the INFO field. Offending field value was "AN=6;AC=4;Het=0;Hom=2;AF=0.6667;TEN=case2HOM,case3HOM ", for input source: /Users/jrobinso/Downloads/tab_test.vcf.gz
```

You can probably fix this in the file js/variant/vcfParser around line 142 by trimming the line before splitting.   However I suggest you also fix whatever is producing these files as they aren't going to work in other tools, certainly tools that use the htsjdk (such as IGV desktop, and the GATK tools).

**Comment by pratham-emedgene** [comment]
@jrobinso Thank you and would also fix the source of files on our side.

**Comment by jrobinso** [comment]
I added a trim() to the string before parsing,  which should take care of it but I haven't tested it.
