### ISSUE TITLE
Unable to Use  igv-1.0.0-rc1.js as a react component

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#195]
We have created react component by using igv-1.0.0-rc1.js but we face below issue(s)
in igv-1.0.0-rc1.js for below line no we are facing issue,
> 19973	-	this.popover.draggable();
	igv-1.0.0-rc1.js:19973 Uncaught TypeError: this.popover.draggable is not a function

> 19937	-	this.$popoverContent.kinetic({});
	igv-1.0.0-rc1.js:19937 Uncaught TypeError: this.$popoverContent.kinetic is not a function

> 18983	-	this.$container.draggable();
	igv-1.0.0-rc1.js:18983 Uncaught TypeError: this.$container.draggable is not a function

> 19674	-   dialog.$container.draggable();
	igv-1.0.0-rc1.js:19674 Uncaught TypeError: dialog.$container.draggable is not a function

> 19397	-  this.container.draggable();
	igv-1.0.0-rc1.js:19397 Uncaught TypeError: this.container.draggable is not a function

By commenting above lines it's working with some issues. Can u please help me out to resolve above issues.
PFA React component created using igv-1.0.0-rc1.js

[igv-react-comp.zip](https://github.com/igvteam/igv.js/files/278773/igv-react-comp.zip)

**Comment by amolpshinde07** [comment]
We are also facing few other issues like unable to release scrollbar of bam/track once we clicked on the same and #191

**Comment by jrobinso** [comment]
Hi, I have no idea what a react component is.  Can you provide me with a test html file that I can reproduce the issues with?

**Comment by amolpshinde07** [comment]
Hi @jrobinso ,
Thanks for quick response. We fixed the issue with the help of [http://stackoverflow.com/questions/29910823/popover-is-not-a-function](url).
Issue is occurring due to multiple instances of Jquery in application.

Once again Thanks!
You can close this issue.
