### ISSUE TITLE
Feature search "in browser" does not work for loaded feature files

### ISSUE THREAD

**Issue by drpowell** [igvteam/igv.js#196]
I believe the problem is the change to Promise code.  A JS promise only takes 1 argument, but the following line has then() attempt to take 2 arguments.  The second of which will always undefined according to spec:

    ./feature/featureSource.js:76:                    self.reader.readHeader().then(function (header, features) {

**Comment by jrobinso** [comment]
Actually "then"  can take 2 arguments, a success and fail function.    However the line cited takes a single argument, the success function.  Could you please elaborate on what is failing, with a test case or at least config object for the track in question.

**Comment by drpowell** [comment]
Sorry, I wasn't clear.  then() can take 2 arguments, both callbacks.  The first of those callbacks for "success" is can only take 1 argument.  In the line of code I quoted the callback takes 2 arguments, "header" and "features" - in which case the "features" argument will always be undefined.

The failure I noticed is loading an unindexed BED file "should" allow searching be feature name without the use of an external web service.  I say "should" since I take that from the reading of the code.

**Comment by jrobinso** [comment]
Hi,  actually there is no limit to the number of arguments the success function can take, that is under your control.    To enable searching for a non-indexed bed file you need to set the "searchable=true" parameter in the config.    See https://github.com/igvteam/igv.js/wiki/Tracks  for details.  If that doesn't work please provide a complete track config object as a test case,  preferably with a small test file.

**Comment by drpowell** [comment]
That's not my understanding of the native JS implementation.  See the test code below:

    new Promise(function(resolve, reject) { resolve(1,2,3); }).then(function(a,b,c) { console.log("a=",a,"b=",b,"c=",c); })
    a= 1 b= undefined c= undefined

**Comment by jrobinso** [comment]
Hmm, yes, you are correct.  This is not intuitive.  The bug will be easy to fix.  Thanks for your persistence and patience.
