### ISSUE TITLE
Unable to render 2 igv instances on single page

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#197]
Hi ,
I am trying to create 2 different object of IGV web and adding them in 2 different div but its unable to show both. Sometime it display only last one instance and sometime nothing but if i put only one instance then it shows it correctly.
Can you please help me out.

**Comment by jrobinso** [comment]
Hi, that is not supported in this version.

**Comment by amolpshinde07** [comment]
![igv multiple instance issue](https://cloud.githubusercontent.com/assets/17845118/15529121/5858e5ec-2268-11e6-954a-65798b1e74b2.png)
PFA expected layout using IGV.
@jrobinso  there any alternative to achieve this?

**Comment by jrobinso** [comment]
Sorry what is PFA?  I don't know what you are referring to.  I think the answer is no, there is no way to achieve that with igv.js.

**Comment by amolpshinde07** [comment]
ok. can we expect it in feature release?

**Comment by jrobinso** [comment]
There are no plans to support this at this time.

**Comment by skushch** [comment]
@amolpshinde07 - you could wrap each of the two viewers in an iframe and put them on the same page. You will still be able to interact with them but it will be more work.
