### ISSUE TITLE
Error reading BAM file: "invalid stored block lengths"

### ISSUE THREAD

**Issue by benjamin-cogne** [igvteam/igv.js#199]
Dear all,

when i try igv javascript with web url of a BAM, as in your exemples, it's working very well.
But when i try to run it on a local file via apache server i have an error saying "invalid stored block lengths". They are BAM files produces by GATK's pipeline, i can't figure out what's going on. 

If you have any ideas (apache configuration, ... ?), it would be great !

Thanks

Benjamin

**Comment by benjamin-cogne** [comment]
Hi Jim, thanks for your response

i'm using version 1.0
I'm able to view the files in IGV desktop
Here are a zip with the html file and an extracted bam region:
[IGV_test.zip](https://github.com/igvteam/igv.js/files/295992/IGV_test.zip)

I don't know how to check if the Apache server is configured to allow range-byte requests...i'm a biologist and those things are quite hard for me to understand^^

Thanks for your help!
Benjamin

**Comment by jrobinso** [comment]
Hi Benjamin,  your test files are loading fine for me. 

What do you know about the configuration of this server? Apache supports range-byte requests out of the box, you have to do some configuration to turn it off.  

If you can send me the contents of the javascript console it might have some hints.

**Comment by jrobinso** [comment]
Update,  I doubt the range-byte header is the problem.  You will get a more specific error if it is (see below).    So I don't know what this is, or how to solve it, but more information on your server might be helpful  
![screen shot 2016-06-09 at 2 49 08 pm](https://cloud.githubusercontent.com/assets/933148/15947652/8ae86164-2e51-11e6-8c42-004b88c0f901.png)

**Comment by benjamin-cogne** [comment]
Hi Jim,

sorry for late reply but i gave up a bit to make it work. But as it would be so helpful for me, i retried and now, i do not have the error message anymore. Could it be thanks to the igv update to 1.0.1 ?

As it'd be too easy, i have now another message: "Error accessing resource; test.bam.bai Status 0". 

If you have any idea...

Thanks so much for your help

Benjamin

**Comment by benjamin-cogne** [comment]
Update, it was just a problem of my server not reading double extendion .bam.bai don't know why..
After, i'm still having the invalid stored block lenghts error...

**Comment by benjamin-cogne** [comment]
Finally, i got it to work... by trying with firefox. It seems to be an error with Chrome only.

Also i had issues reading .bam files with red hat: i added :  "AddType application/octet-stream .bam " in the httpd.conf file and i can read it now.

Seems like i can begin to enjoy your great javascript igv !

Thanks

Benjamin

**Comment by jrobinso** [comment]
The invalid blocks length error usually indicates a problem with a bam index file, or that the server is not responding properly to byte-range requests  (i.e. returning bytes from position 0 irrespective of what is requested).   If you can make a test bam available on a public server I will look into it.
