### ISSUE TITLE
Render track using data in the form of Array/List

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#203]
Hi @jrobinso ,
I want to pass array of variants to render them as a track instead of path of track.
is there any way to do it? can you please provide some help?

**Comment by jrobinso** [comment]
Hi, there is no way to do that.   You could probably implement this by creating a custom FeatureSource (featureSource property of FeatureTrack).    If you do please send a pull request and I will try to integrate it.

**Comment by amolpshinde07** [comment]
I will try to create Custom FeatureSource. If anybody can do please help.

**Comment by jrobinso** [comment]
I did a quick code review and I think it would be simpler to implement a custom FeatureReader and use the existing FeatureSource.   You're reader wouldn't actually read anything but that's o.k.   See gtexReader.js for an example,  you can copy that then supply an implementation for readFeatures.  In your case the features could be stored in the config object.   The final step is to set the sourceType in the config to something new,  for example "array",  then use this in the FeatureSource constructor to create your custom reader.
