### ISSUE TITLE
Google authentication to access bam files in buckets

### ISSUE THREAD

**Issue by lmtani** [igvteam/igv.js#204]
Hi,

Is it possible to authenticate and use igv.js as in IGV ? I have some private bams in my google storage, and it works fine with IGV, but when I try to authenticate and access the files from javascript I have the error 401 - login required.

I followed the [steps here](https://developers.google.com/api-client-library/javascript/start/start-js#how-it-looks-in-javascript
) to perform the authentication.

After, by clicking in the following div I would expect my alignment track, but it is not happening.
```
    <div onclick="igv.browser.loadTrack({
                                  sourceType: 'gcs',
                                  type: 'bam',
                                  height: 200,
                                  autoHeight: false,
                                  url: 'gs://mybucket/test/OUT1.bam',
                                  indexPath: 'gs://mybucket/test/OUT1.bam.bai',
                                  name: 'My_private_bam')">
                                          Google Cloud Storage - PRIVATE
     </div>
```

**Comment by jrobinso** [comment]
Apologies that I missed this issue, I was traveling last week.    The answer is yes, you have to set the google access token explicitly,  specifically set the global

oauth.google.access_token

This is not documented, that was an oversight,  I will update the doc.   If I can ask did you discover this on your own, and thus close?

**Comment by lmtani** [comment]
Hi,

Yes, but I decided to generate a [signed url ](https://cloud.google.com/storage/docs/access-control/create-signed-urls-program) using python (for allowed users) and then pass the signed bam and bai links to igv.js.

Everything working well now, thank you for the code.

**Comment by jrobinso** [comment]
OK, but for the future be aware that you can explicitly set the access token.  We have several portals that use oAuth in this way.   I'm creating a git issue to try to dig the token out of gapi if its defined,  that wasn't done originally because we don't require you use gapi.
