### ISSUE TITLE
Splitpane in Each Track

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#205]
is there any way to add Splitpane in every track like in igv desktop?

**Comment by jrobinso** [comment]
Not currently.  Its a long term goal.

**Comment by amolpshinde07** [comment]
Approximately when we can expect it?

**Comment by jrobinso** [comment]
No estimate, there are other higher priority features for us. Perhaps in 
the 4th quarter.

**Comment by jrobinso** [comment]
BTW, could you elaborate on what you mean by "Splitpane"?   I am referring to viewing multiple loci,  I actually am not sure what you are referring to.

**Comment by amolpshinde07** [comment]
"Splitpane" means every track should be resizable vertically like it is in IGV desktop.

**Comment by jrobinso** [comment]
Oh sorry, I misunderstood.  We have no plans to add that.
