### ISSUE TITLE
Error reading bam file

### ISSUE THREAD

**Issue by ashy143** [igvteam/igv.js#206]
For some of the files I get this error
Chunk size requested is: 62126867. Max supported is 52428800
Is this a known issue?

I feel like this fails inside loadNextChunk().
How are these values calculated ?

var c = chunks[chunkNumber],
fetchMin = c.minv.block,
fetchMax = c.maxv.block + 65000,   // Make sure we get the whole block.
range = (bam.contentLength > 0 && fetchMax > bam.contentLength) ?
                                {start: fetchMin} :
                                {start: fetchMin, size: fetchMax - fetchMin + 1};

**Comment by jrobinso** [comment]
I think you might have pinpointed the problem.  Are you able to load these bams in other tools (e.g. IGV desktop or samtools view)?

**Comment by ashy143** [comment]
Yes I am able to load these bams using IGV desktop and samtools.

**Comment by jrobinso** [comment]
OK, thanks.   Without access to these files it is not easy to reproduce the error,  is it possible to make one available?  Otherwise I will have to ask you to test possible fixes.

**Comment by jrobinso** [comment]
Where does this error message come from (file and line number if possible)?   Could you paste the contents of the javascript console.  I can't find that error in the igv.js source code.

**Comment by ashy143** [comment]
![screen shot 2016-06-20 at 4 22 49 pm](https://cloud.githubusercontent.com/assets/3258388/16213308/478a9c60-3703-11e6-864b-31619da47e7b.png)

Line #104 in bamreader.js where it call igvxhr.load()

**Comment by jrobinso** [comment]
You have a 404 error for that bam (file not found).  I don't see the 
error originally posted.

**Comment by ashy143** [comment]
![screen shot 2016-06-20 at 4 27 27 pm](https://cloud.githubusercontent.com/assets/3258388/16213422/0976524c-3704-11e6-8729-ff6ef0a0d250.png)

Values before the GET request is failed. It fails with 404 error and the the returns the error message that I  mentioned.
![screen shot 2016-06-20 at 4 30 08 pm](https://cloud.githubusercontent.com/assets/3258388/16213453/654a78a0-3704-11e6-80c0-178c670f4f02.png)

**Comment by jrobinso** [comment]
Where is the "Chunk size requested" message coming from?  I think this 
is a server-side problem, but I can't tell from your screenshot what the 
"preview" is showing.

**Comment by jrobinso** [comment]
In case I wasn't clear, the "chunk size" message is coming from the server, and doesn't correspond to any limit in the bam or bgzf spec that I'm aware of.   So my guess is you have a problem with the webservice (I assume its a webservice) serving these files.   Try loading the same bam by an http url,  with no intermediate webservice.

**Comment by ashy143** [comment]
@jrobinso  I found the root cause. This issue is from our server where we restrict the range size. You can close this issue. Thank you.
