### ISSUE TITLE
Last read skipped by BamReader 

### ISSUE THREAD

**Issue by skushch** [igvteam/igv.js#208]
I think decodeBamRecords() fails to include the last read.

The attached sample contains two bam files with 3 and 4 reads (Human-81). The 3-read file produces 2 reads while the 4-read file produces 3. In both cases the Java version of the viewer renders correctly.

[bam-samples.zip](https://github.com/igvteam/igv.js/files/324380/bam-samples.zip)

**Comment by jrobinso** [comment]
Thanks for the test data.  Just pushed a fix.

**Comment by skushch** [comment]
Thanks for the really quick fix!

**Comment by jrobinso** [comment]
It was easy to fix because you provided a detailed description, and test 
data.
