### ISSUE TITLE
Data is displayed differently.

### ISSUE THREAD

**Issue by subji** [igvteam/igv.js#210]
i'm use igv.js v 1.0.1

but when i called to continue to refresh bam and bai data that different show every time.

only same data, same chr, same location

so igv.js showing data compared with igv desktop application 

but that is different to displaying data between igv.js viewer and igv desktop app viewer.

i need help 

below result pictures

-- igv desktop app
![1](https://cloud.githubusercontent.com/assets/8937254/16290135/da23da62-3935-11e6-8e28-360e3a5fd02c.PNG)

-- igv.js

![3](https://cloud.githubusercontent.com/assets/8937254/16290151/fbdc0a44-3935-11e6-9598-bf1414a1d8a8.PNG)

**Comment by jrobinso** [comment]
It looks the same to me,  it won't be exactly the same of course because 
alignments can get packed differently,  and the region with the snp has 
been downsampled.   Also theses are different products.

**Comment by subji** [comment]
thanks. 

one more question.

i pushed refresh every time

data show to different every time 

below pictures that using same data, location, chr

![4](https://cloud.githubusercontent.com/assets/8937254/16292075/da794408-3948-11e6-8112-fc45605dec87.PNG)


![5](https://cloud.githubusercontent.com/assets/8937254/16292076/dd508ac4-3948-11e6-80fb-bd7dec6c7af3.PNG)


![6](https://cloud.githubusercontent.com/assets/8937254/16292077/df3f5afe-3948-11e6-8c6a-3e36c032318a.PNG)


![7](https://cloud.githubusercontent.com/assets/8937254/16292082/e10fac08-3948-11e6-81d0-33f5d821898f.PNG)

**Comment by skushch** [comment]
Hi @subji - this was also initially confusing for me. As Jim mentioned above, the alignments get downsampled (you can tell because you get a black bar above the alignments). The downsampling is random which means that the actual depiction will vary as you refresh the page.

In our app we disabled the downsampling for _some_ tracks to avoid the situation that you describe. The [Track wiki page](https://github.com/igvteam/igv.js/wiki/Tracks) does a good job of giving an overview of the options available when configuring your tracks.

`samplingDepth: Number.MAX_VALUE`

Note that the docs caution against using this setting.

**Comment by jrobinso** [comment]
Again,  I don't see any real differences.  Alignments can be packed and downsampled differently every time you refresh.   See the samplingDepth parameter for the alignment track (https://github.com/igvteam/igv.js/wiki/Tracks) , set to a very large # to turn it off.  Even with no downsampling alignments can be packed differently (i.e. appear in different rows).

**Comment by skushch** [comment]
My bad, didn't realize the packing order could vary with downsampling disabled. I guess it happened to be the same for a few examples I tried initially.

**Comment by jrobinso** [comment]
If downsampling is disabled, and you jump to exactly the same locus,  then
packing should be deterministic.

On Friday, June 24, 2016, skushch <notifications@github.com> wrote:

> My bad, didn't realize the packing order could vary with downsampling
> disabled. I guess it happened to be the same for a few examples I tried
> initially.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/igvteam/igv.js/issues/210#issuecomment-228396960>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA49HEYbe8fSiD1OXM9VAkz8Wptzz2z3ks5qPAkbgaJpZM4I8Zg3>
> .
>


-- 
Sent from Gmail Mobile

**Comment by subji** [comment]
really thank you jim, skushch i can understand it
