### ISSUE TITLE
Do not rely on default protocol for external links

### ISSUE THREAD

**Issue by jdelafon** [igvteam/igv.js#211]
The first time you try igv.js, you probably create an emtpy html page and [copy-and-paste the package](https://github.com/igvteam/igv.js/wiki/Dependencies#the-complete-package-copy-and-paste). Or copy one of the examples. Then you open it in a web browser and it works.

But there are hard-coded URLs in the code (e.g. `reference.fastaURL`, or the css imports) that are not prefixed with the protocol name, so that opening an html page calling `igv.createBrowser` directly in the browser says "Error accessing resource: //s3.amazonaws.com/...", while accessing it through a web server works. (What is appended instead of "html:" is "file:").

Can I suggest to just add the "http"/"https" where needed, instead of requiring to copy the single-file app to /www ? I can easily edit the CSS imports, but not the source JS.

Edit: if it is not a bad idea, I could submit a pull request of course.

**Comment by jrobinso** [comment]
In the past this has been considered best practice to avoid mixed-protocol errors.    However,  I don't see any harm in setting an https:// protocol for those resources that support it.  An https:// resource can be accessed from an http:// page, but not the other way.

file:// protocol is really not supported.  Most resources accessed require range-byte support.   What is your use-case for using file://?

**Comment by jdelafon** [comment]
Thanks.
There is no use-case for file://, only the browser setting this by default when it sees nothing (firefox, chrome).

**Comment by jrobinso** [comment]
That's not how it works.  The browser sets this to the protocol used for 
the page itself, that's why you use protocol-less URLs,  so there are no 
mixed protocol errors.

**Comment by jdelafon** [comment]
Ah I see, so opening the .html file directly in the browser uses file:// , and the same protocol is used to fetch these urls. But now it works in all cases.
