### ISSUE TITLE
Bug in alignment coverage track with low height

### ISSUE THREAD

**Issue by jdelafon** [igvteam/igv.js#216]
Setting the alignement coverage track's height to a small value superposes the coverage on top of the reads (cf screenshot). Moreover, it is sometimes unnecessary (e.g. for spotting SNPs), so an option to not display it would be welcome.

![coverage](https://cloud.githubusercontent.com/assets/12040845/16588706/5b4f5be0-42d0-11e6-935c-a54ed383fb23.png)

**Comment by jrobinso** [comment]
OK, noted.  Its helpful to have 1 git issue per request (there are 2 here) as they won't necessarily be added at the same time.

**Comment by jdelafon** [comment]
Right, I should be more disciplined. I moved the second one to #217 .
