### ISSUE TITLE
Allow to remove the mini-chromosome view

### ISSUE THREAD

**Issue by jdelafon** [igvteam/igv.js#217]
In most(?) cases, the mini-chromosome view is not useful. Strangely, setting "div.igv-ideogram-content-div" to display:none, or even setting its height to fewer px in CSS breaks the whole layout. The canvas itself can be made invisible but will still take vertical space.

If we could have an option to remove it, like we have for the karyotype and navigation, it would save 32px of very precious vertical space.

**Comment by turner** [comment]
Closed with commit e5d81bd6
