### ISSUE TITLE
Error: Range-Byte Header Ignored When Loading Local File

### ISSUE THREAD

**Issue by chgibb** [igvteam/igv.js#218]
I'm attempting to embed IGV.js into an Electron application. When pointing file urls to local files, status code 200 is always returned along with the entire file. IGV is expecting status code 206 with only the portion of the file it is trying to read. Could this be an Electron bug? Is there any work around to get IGV to maybe cache the file in case of a 200 response and then selectively seek from the cached version?

**Comment by jrobinso** [comment]
I'm not sure what "Electron" is but support for range-byte headers is 
required of data file servers.   I don't understand your suggestion,  
cache it where?  On the client browser?  That would never work except 
for very small files.

**Comment by chgibb** [comment]
http://electron.atom.io/
I'm going to attempt to patch IGV's file loading code to be compatible with Electron. Am I right to assume that all file loading flows through igvxhr.loadArrayBuffer?

**Comment by chgibb** [comment]
I apologize for my lack of explanation earlier. Electron essentially allows the running of HTML5 applications as desktop applications. Therefore, file system access is possible. I was mostly successful in patching IGV's xhr.load method to turn to the local file system when it detects it is running in Electron and the user has specified 'file://' at the beginning of their URL. However, zlib's jszlib_inflate_buffer function is throwing an "invalid stored block length" error. I am not very familiar with zlib. Would you kindly be able to advise? The following is my patch, inserted immediately prior to the setting of xhr call backs in igvxhr.load.

```javascript
//trying to load local file
			if (url.match(new RegExp("(file:\/\/)","g")) && range) {
				//Running inside Electron
				if (window.require && window.process) {
					var fs = require('fs');
					//trim protocal from file url
					var fsURL = url.substr(7,url.length-1);
					//spoof return status
					xhr.status = 206;
					//read the entire file into memory and then extract range specified.
                    //should be changed to stream.
					var buffer = fs.readFileSync(fsURL);
					var fsResponse = new ArrayBuffer(range.size);
					//extract only the range requested from the file
					for (var i in buffer) {
					 	if (i >= range.start && i < rangeEnd) {
						 	fsResponse[i] = buffer[i];
			   			}
					}
				}
				fulfill(fsResponse,xhr);
				return;
			}
```

**Comment by jrobinso** [comment]
Hi, this is going to be difficult to do, and I don't have the expertise to advise.  We will eventually support local files, but not through the use of file:// urls.   If you get this to work and want to submit a pull request I'm happy to review it.   For desktop use we offer have IGV,  which is much more full featured, so this is not a priority for us.

**Comment by chgibb** [comment]
Thanks for taking the time to respond. I have been unable to solve the issue with zlib unfortunately and will likely end up rolling my own solution. Thanks for making such a great tool like IGVjs open in the first place. All the best.
