### ISSUE TITLE
Citing igv js

### ISSUE THREAD

**Issue by danielecook** [igvteam/igv.js#219]
Is a publication for igv js in the works or is there a preferred method of citation? We are already using it, and it is working quite well (-:

https://elegansvariation.org/data/browser

**Comment by jrobinso** [comment]
Thanks for asking!  Also for the link, its helpful to know how its being 
used.  A publication will come, but if you publish before we have it 
please cite the website, if that is allowed by your publisher.   We will 
update this ticket when we have something better to cite.

**Comment by gaitat** [comment]
Which website would you like us to reference? igv.org or github?

**Comment by helgathorv** [comment]
Preferably www.igv.org
