### ISSUE TITLE
Version Number Variable

### ISSUE THREAD

**Issue by david-ma** [igvteam/igv.js#220]
Hey people :)

Is there a way to tell what version of IGV you're using?
E.g. if you type in "d3.version" into the console, it'll spit out the version number for d3.js
Or "$.fn.jquery" for jQuery.

I've been inserting a string whenever I build a new igv.js.min, so that typing "igv.version" gives me "David's build 11-July-2016, igv.js v1.0.1" so I know which version I'm using and how out-of-date I am haha

**Comment by jrobinso** [comment]
I'm not sure I understand the question.  When we release a version it gets its own url, with the version # in the url.   Are you looking for something like the git commit ID?   It would be a neat trick to insert that into some javascript during the grunt build.  We don't do it, but if you find a grunt task or some other way to make that work please give us a pull request.

**Comment by david-ma** [comment]
Sorry I'm not sure how to explain it differently. Here's a screenshot that illustrates what I mean?
<img width="456" alt="screen shot 2016-07-25 at 5 12 26 pm" src="https://cloud.githubusercontent.com/assets/3320713/17093181/05d7ad14-528b-11e6-805c-6d801c9dd38d.png">

This isn't an important feature request, so feel free to close this issue as a "won't do".

**Comment by jrobinso** [comment]
Cool, I didn't know you could run code in the developer tools console.  
It would have to access a constant or function defined in the source, so 
I don't think your example would work unless that information is 
injected during the grunt "build" process.

**Comment by jrobinso** [comment]
@david-ma is this revolved now?

**Comment by david-ma** [comment]
Yes we can close this issue now.
