### ISSUE TITLE
programmatic and interactive item (e.g. SNP) selection

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#221]
Can a segment displayed on a track (a SNP, for instance) acquire a "selected" status, after which   its rendering is modified appropriately?  I have use cases for which I wish to do interactive and programmatic selection.

If these capabilities already exist (which seems likely) where may I read about them?

Thanks -

**Comment by jrobinso** [comment]
Hi @paul-shannon I have 93 open issues so I'm trolling through them.  This one's still open.  Would this still be useful?  And if so what would you want to do next with the "selected" item?
