### ISSUE TITLE
igv.js and  Jupyter notebooks?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#222]
Has anyone wrapped up igv.js as an ipython widget, for use in Jupyter notebooks?

**Comment by jrobinso** [comment]
Not to my knowledge.  Will keep this open and take it as a request.   Happy to entertain a  pull request.

**Comment by jrobinso** [comment]
Resolved,  see https://github.com/igvteam/igv.js-jupyter

**Comment by jrobinso** [comment]
@paul-shannon Old thread, but are you using igv.js in a Jupyter workbook?   I don't think it works any longer.   I've been trying to learn enough to bring it up to date but I can't even get the official widget cookie-cutter code to work.   So I'm not optimistic.

**Comment by jrobinso** [comment]
Don't spend any time on it but the code might be instructive, doesn't have to work.   I actually did get our project working,  I had configuration problems.

**Comment by paul-shannon** [comment]
Here’s what worked last February:   https://github.com/paul-shannon/ipyTrenaViz

There’s a makefile in the root directory that includes this build target:


buildWidget:
	(cd ./js; npm update)
	(cd ./js; webpack --config webpack.config.js)
	pip install -e .
	jupyter nbextension install --user --py ipyTrenaViz
	jupyter nbextension enable --user --py --sys-prefix ipyTrenaViz


A complicated procedure, for sure.   The net result is notebook widget with multiple jQuery tabs, one of which embeds igv.js

 - Paul

**Comment by jrobinso** [comment]
Thanks.   Complicated procedures seem to be the bread and butter of Jupyter
nbextension development.   To do it well one needs to be an expert in
python, conda and pip,  modern javascript,  backbone.js, node, NPM, and
webpack.

My goals are modest,  to update to the latest IGV release,  clean up and
"pythonify" the code, and add some documentation.   I probably don't have
time to learn backbone and make a proper widget, and I don't think its
needed as igv.js does not need to control the backend python.

**Comment by paul-shannon** [comment]
Maybe I misunderstand “does not need to control the backend python”?  

For what may be a tiny counter-example - or maybe it just illustrates my confusion :} - I find it useful to be able to query igv.js, from python but now especially in R shiny apps, for the current region.  Or to ask, from python or R, for igv to display a region, add or remove a track.   So back-and-forth communication between the python or R, and igv.js has been very helpful.

However, I suspect I misunderstand!

**Comment by jrobinso** [comment]
Hi Paul,  our current extension, as you know, supports python -> igv.js communication,  but not the other way.   How do you query igv.js  for the current region in trenaviz?

**Comment by paul-shannon** [comment]
When I worked this out for i[gvShiny](https://github.com/paul-shannon/igvShiny) there was not yet a javascript API in igv.js to query the current region.  So (maybe even with advice from you) I did it this way:
````
igvWidget.on('locuschange', function (referenceFrame, chromLocString){
    Shiny.setInputValue("currentGenomicRegion", chromLocString, {priority: "event"});
    });
````
This then shows up in R as ````input$currentGenomicRegion```` upon which reactive code can be written.  I did something similar in python with the backbone protocol.

**Comment by jrobinso** [comment]
I see.  I need something simple to build and maintain and am trying to avoid backbone and importing ipywidgets, partly because I have too many projects to learning and then supporting that.  However, I just discovered a simple way to do this with just javascript and core jupyter, this works beautifully from a cell,  so its promising.

```
%%javascript
 igv.browser.on('locuschange', function (referenceFrame, label) {
                 var str = "locus=\"" + label + "\""
                 console.log(str)
                        IPython.notebook.kernel.execute(str)
                    });
```

**Comment by paul-shannon** [comment]
Nice solution!

**Comment by jrobinso** [comment]
This also looks promising, maybe a little less of a hack:  https://jupyter-notebook.readthedocs.io/en/stable/comms.html
