### ISSUE TITLE
Toggle Karyotype

### ISSUE THREAD

**Issue by david-ma** [igvteam/igv.js#223]
I'd like to be able to toggle the Karyotype Panel.

Current behaviour:
- If showKaryo evaluates to "true", igv.js will draw the Karyotype Panel, and if a div #igvKaryoDiv exists, it will be used to draw the panel.

Proposed behaviour:
- If showKaryo evaluates to "true", igv.js will draw the Karyotype Panel, and if a div #igvKaryoDiv exists, it will be used to draw the panel.
- A toggle button, similar to "hide labels/show labels" will be used to hide/show the Karyotype Panel.
- If showKaryo === "hide" then draw the Karyotype Panel and button, but hide the panel by default (instead of showing it).

Anyway it's probably easier if you just take a look at my pull request :)

I've hidden the panel using some css to set height:0 and overflow:hidden, because using "display:none" seems to mess with canvas and prevent the Karyotype Panel being drawn at all.

**Comment by jrobinso** [comment]
I think this is resolved, reopen of not.
