### ISSUE TITLE
Make an API to sort segmented CN in igv.js

### ISSUE THREAD

**Issue by linghong** [igvteam/igv.js#225]
Hi, Jim,

In your desktop igv, the segmented CN can be sorted. Could you also make an API that can be used to sort the segmented CN graph in igv.js? 

Thank you!

linghong

**Comment by jrobinso** [comment]
Yes, are you asking for a dynamic API (function call) or a track config parameter?

The user can trigger this now by holding the alt key down and clicking.

**Comment by linghong** [comment]
Jim, 

I think an API maybe give us more flexibility. We want to make the following thing happen: we want to draw another table or graph that was drawn using same tissue order as the segmented CN but drawn for different data parameters.  When sorting  the segmented CN, that table or graph will be  sorted accordingly. Hence, if your API will also give a way for us easily get the segmented CN tissue sample names, so we can call a redrawing function to redraw our table/graph according to the segmented CN samples order, that will be highly appreciate.

By the way, what is the best way to get  those segmented CN tissue  names from your current igv.js code that we can use them to fetch data in our database to draw an initial table /or graph? 

Thank you!

Linghong

**Comment by jrobinso** [comment]
@linghong -- another point of clarification.   Do you want to address specific track(s) with the API,  or just a function to sort all loaded CN tracks?

**Comment by linghong** [comment]
@Jim,
We want to sort all CN segments in the CN track, a similar way in the desktop version. Thanks.

**Comment by jrobinso** [comment]
Hi,  there is now an API to sort seg (CN) tracks, actually 2 apis.  One to select seg tracks (issue #264) and another to sort them once selected (issue #265).  Example usage is below.   

```
        var tracks = igv.browser.findTracks("type", "seg");
        tracks.forEach(function (track) {
            track.sortSamples("8", 124512906, 124512945, "DESC");
        })
```

However, based on your description you might also need a means to be notified when the user sorts the track,  e.g. by an "alt-click", and also fetch the sample names from the track in the current order.   Is that correct?    If so, please open a new git issue, we will probably support that with an event you can register for.

**Comment by linghong** [comment]
Hi, Jim,

Thank you so much for the new API. I think for sorting segment samples, the current API can do the work.

Linghong

**Comment by JiaoJiao123** [comment]
@jrobinso It is very helpful! Thanks for letting us know
