### ISSUE TITLE
Document how to serve BAM files

### ISSUE THREAD

**Issue by jdelafon** [igvteam/igv.js#227]
The examples all use URLs pointing to public BAM files. That does simply not exist as soon as the genomes are human, or while research is ongoing. Instead, one can write a BAM server that returns some content when given a login and an identifier for the file.

After examining the requests I finally understood that I had to return headers such as "Accept-Ranges", "Content-Range" etc., and a 206 status. And how to set CORS accordingly. But at first it is not trivial at all how to make that work.

It should be documented what is the expected API to communicate with IGV.js.

**Comment by jrobinso** [comment]
OK, we'll write something up, probably very brief with a pointer to CORS 
documentation.   This is not special to IGV,  CORS must be dealt with 
for any web app.

Most web serves should return range headers in response to range 
requests,  in fact I've never had to do anything special there. What 
server are you using?

Jim

**Comment by jdelafon** [comment]
Apache does indeed. I wrote my app using [Scala Play](https://www.playframework.com/), which uses the [Netty](http://netty.io/) server and does not [(yet)](https://github.com/playframework/playframework/pull/5961) do it automatically. I am rather inexperienced with this, so it was not easy to figure out how to do it manually.

Also, although it makes perfect sense, it wasn't immediate for me for instance that when I give IGV.js a URI, the first thing it does is appending ".bai" to it to fetch the index (some people use "filename.bam" + "filename.bai". By "some people" I mean our whole sequencing facility).

**Comment by jrobinso** [comment]
You can explicitly specify the index, and that is recommended. If you 
don't it will try to guess, as you've observed.  Track configuration 
options are here: https://github.com/igvteam/igv.js/wiki/Tracks,  see 
indexURL.

Writing your own webserver that conforms to the spec is not a trivial 
task,  it is spelled out here: 
https://www.w3.org/Protocols/rfc2616/rfc2616.txt.   The igv.js client 
assumes a well behaved server is on the other end, and checks specific 
error codes and header values in various places.

**Comment by jdelafon** [comment]
Oh, I missed that. Thanks. 
I managed to have everything working - the server just needed an extension -, but it was not trivial indeed! That's how you realize the work people have done before we arrive.

Maybe there is not much to write then, assuming people are using well-behaved servers.
Just a note about adding Range to the CORS still could be helpful.

**Comment by jdelafon** [comment]
I see it has been done here: https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements, so it can be closed.

One thing that could be added though is how to verify that the user querying the BAM has the right to do so. Since the request is a GET, one must pass a token in the URL, so it has to be short-lived and one-time-only.
