### ISSUE TITLE
How to use credential for loading tracks from server ?

### ISSUE THREAD

**Issue by deepaksibar** [igvteam/igv.js#228]
Hi,

We are using other server which hold all track (BAM, Gene, VCF etc). But server requires authentication for accessing these data. So can you plz let me know, how to get tracks for igv.js from server using credentials?

Thanks,
Deepak

**Comment by jrobinso** [comment]
What type of authentication scheme are you using?

**Comment by deepaksibar** [comment]
We are using token based authentication(x-auth) in a single page application(SPA).

**Comment by jrobinso** [comment]
I'm closing this as I can't do much without details.
