### ISSUE TITLE
Demos are broken

### ISSUE THREAD

**Issue by DimitryDushkin** [igvteam/igv.js#230]
http://igv.org/web/igv-api.html
http://igv.org/web/examples/ga4gh.html
http://igv.org/web/examples/copyNumber.html
http://igv.org/web/demo/ga4gh-demo.html

Could you please fix them.

**Comment by helgathorv** [comment]
Thanks for letting us know. We're looking into it.

BTW, two of the links you reported are incorrect. The first and fourth should be:
http://igv.org/web/examples/api.html
http://igv.org/web/examples/google-demo.html
Did you find the incorrect links in our current doc? If so, where? We'd like to fix them.

**Comment by DimitryDushkin** [comment]
I've found them here http://igv.org/web/doc/

**Comment by jrobinso** [comment]
OK, thanks, that page is orphaned and not referenced form anywhere.  Did you find it by googling?

**Comment by DimitryDushkin** [comment]
Yes, I did.
