### ISSUE TITLE
visualize TDF files

### ISSUE THREAD

**Issue by patidarr** [igvteam/igv.js#232]
Hi, 

Currently I don't see the capability to visualize TDF files, will it come in near future?

Thanks,
Rajesh

**Comment by jrobinso** [comment]
It will come, but no estimate on the time right now.   In the meantime,  I suggest using BigWig.

**Comment by patidarr** [comment]
Thanks.

**Comment by jrobinso** [comment]
I'm reopening, this is the first request for this so I'll keep it open.

**Comment by scottx611x** [comment]
@jrobinso We have just incorporated IGV.js within https://github.com/parklab/refinery-platform and are also interested in the ability to visualize `.tdf` files

**Comment by jrobinso** [comment]
@scottx611x  OK, noted.

**Comment by jrobinso** [comment]
TDF is now supported in the latest code.  It will be released by the end of the month, meanwhile you can trying it by pulling the latest or using https://igv.org/web/beta/

**Comment by jrobinso** [comment]
I should add a caveat -- current support is for "single track" TDF,  the most common type.  Coverage files or files computed from wig or bedgraph are single-track.   The rarely used multi-track TDF file is not supported yet.

**Comment by gilhornung** [comment]
Hi,

The option of using TDF is not documented in the Wiki:
https://github.com/igvteam/igv.js/wiki/Tracks

I wwasn't able to make it work for me.

All the best,

Gil
