### ISSUE TITLE
Show Transcripts in gene track

### ISSUE THREAD

**Issue by patidarr** [igvteam/igv.js#233]
Hi,

I notices that even in the Expand Mode gene track does not show individual transcripts, would it be possible to add this feature? 

Thanks,
Rajesh

**Comment by patidarr** [comment]
I am using //s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed
is there a bed file with transcript info on broad server?

Also Is it possible to show amino acids as in desktop version when you zoom in ?

**Comment by jrobinso** [comment]
Try the following

url:"https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.annotation.sorted.gtf.gz",
indexURL:"https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.annotation.sorted.gtf.gz.tbi"

Amino acid translations are not done yet,  there is another open issue for that.

**Comment by jrobinso** [comment]
Actually don't try those URLs yet, there's a problem with that file.  Will update here when fixed.

**Comment by patidarr** [comment]
Thanks. Will wait

**Comment by jrobinso** [comment]
OK, try this.  

        {
            url: 'https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v24lift37.annotation.sorted.gtf.gz',
            indexURL: 'https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v24lift37.annotation.sorted.gtf.gz.tbi',
            name: 'Gencode v24',
            format: 'gtf',
            visibilityWindow: 10000000
        }

**Comment by patidarr** [comment]
Works awesome!!
Any chance this is available for RefSeq only transcripts?

**Comment by jrobinso** [comment]
I don't have such a file ready, but the process would be to obtain a 
bed, gtf, or gff file with those transcripts then index it.

**Comment by patidarr** [comment]
Thanks!!

**Comment by patidarr** [comment]
Any update on when will be amino acid sequence visualization?

**Comment by jrobinso** [comment]
No update yet, we know its important.  That issue is #182 .  Closing this one as I think it is resolved.
