### ISSUE TITLE
CORS error on portals.broadinstitute.org/webservices/igv/locus

### ISSUE THREAD

**Issue by david-ma** [igvteam/igv.js#237]
Searching for a feature, e.g. TP53 relies on this code:

`            this.searchConfig = {`
`                // Legacy support -- deprecated`
`                type: "plain",`
`                url: "https://portals.broadinstitute.org/webservices/igv/locus?genome=" + genomeId + "&name=$FEATURE$",`
`                coords: 0,`
`                chromosomeField: "chromosome",`
`                startField: "start",`
`                endField: "end"`
`            }`

Unfortunately it is giving a CORS error right now.

**Comment by jrobinso** [comment]
Thanks for the report, looks like a server-side error.  Do you know when this began happening?

**Comment by david-ma** [comment]
We only noticed it yesterday, but it may have started earlier.

**Comment by jrobinso** [comment]
Actually I don't get the error,  you'll have to provide more details.  Try our examples at igv.org,  or just enter this in a browser with developer tools on.   You'll see the CORS headers in the response.    https://portals.broadinstitute.org/webservices/igv/locus?genome=hg19&name=egfr
Can you give me something, e.g. a web page, that reproduces the error you are seeing?

**Comment by jrobinso** [comment]
Capturing the response with developer tools from your app might be enough.

**Comment by david-ma** [comment]
Ok I figured it out, I had an old version of igv.js (built on the 25th of July, 2016) which was using this:

url: "//www.broadinstitute.org/webservices/igv/locus?genome=" + genomeId + "&name=$FEATURE$"

Turns out it wasn't happy with the redirect. Updating the url fixes this problem.

**Comment by david-ma** [comment]
I've also noticed that I can pass in my own search url in the igvOptions

search: { url: "/PathOS/Transcript/locusJSON?name=$FEATURE$" }

Is this documented anywhere?

It seems to require a JSON that looks something like this:

`[{`
`"chromosome":"chr17",`
`"start":"7572927",`
`"end":"7579912",`
`"type":"refseq"`
`}]`

However, this doesn't work because in "handleSearchResult", when it is applying flanking, it treats "igv.browser.flanking" as a string and then concatenates the string it to the result, rather adding it.

I'll fix this and submit a pull request.

**Comment by jrobinso** [comment]
Yes, its documented here:  https://github.com/igvteam/igv.js/wiki/Browser,  scroll down to the bottom.  Not many have used this,  so the documentation hasn't been vetted thoroughly.  Report any discrepancies.    I'll look for the pull request for the fix.

**Comment by david-ma** [comment]
Oh oops!!! I should have looked at the wiki for that! 😅
