### ISSUE TITLE
ReferenceError: SEQUENCE_DICTIONARY_FLAG

### ISSUE THREAD

**Issue by jdelafon** [igvteam/igv.js#239]
I passed a valid BAM file with header as `url`, and a valid index that I just created from the former as `indexURL`, and checked with a `diff` that what I get with CURL are the correct files. Still I am getting this error:

    ReferenceError: SEQUENCE_DICTIONARY_FLAG is not defined
        at readHeader

I suppose that it is coming from there:
https://github.com/igvteam/igv.js/blob/3d837e451adb1d55ce914d0a09886107b754ad43/js/feature/tribble.js#L88
(and I cannot see where this constant is defined. Moreover, this code does nothing as the condition block is empty)

Can you tell me what is happening ?

**Comment by jdelafon** [comment]
Ah, it happens if the file has no extension and you forget to add 'format' parameter. 

But should that check be cleaned out, and "Tribble" really be the default format ? Probably better throw an error if no format is given and no extension is found.

**Comment by jrobinso** [comment]
I just pushed a change that should catch this.  Could you try again leaving out for format parameter to confirm?
