### ISSUE TITLE
PR for helper script to download / index / unzip reference files?

### ISSUE THREAD

**Issue by mccalluc** [igvteam/igv.js#240]
For our work it made sense to wrap the download-from-ucsc-unzip-index-and-upload process in a script: https://github.com/parklab/refinery-platform/blob/mccalluc/igvjs-visualization/deployment/genome-to-s3.sh

This isn't a core concern of your project, and it's pretty trivial, but at the same time other folks might find it useful: Would you like a PR? No worries if not. Thanks!

**Comment by jrobinso** [comment]
Thanks!  This looks really useful,  I've probably done 30+ of these myself the hard way.    It would also be useful for IGV desktop.
If you wish to contribute this yes we would host it,  send a PR.  However, if you are going to maintain the script we could reference your repository instead, perhaps from the documentation.

**Comment by mccalluc** [comment]
The script has gotten more complicated, so it now has its own repo, and tests: https://github.com/refinery-platform/get-reference-genomes

Perhaps the best course is for you to confirm that the script works for folks in the broader world, and when you're comfortable, perhaps reference it near the top of https://github.com/igvteam/igv.js/wiki/Tracks?

(Sorry to let this drop.)

**Comment by jrobinso** [comment]
Hi @mccalluc ,  I haven't had an occasion to use this yet but I have added a pointer to your repo here:  https://github.com/igvteam/igv.js/wiki/Reference-Genome-2.0
