### ISSUE TITLE
Differences in BAM compatibility between IGV and IGV.js

### ISSUE THREAD

**Issue by andrewhill10X** [igvteam/igv.js#242]
IGV.js is excellent, thank you very much for making it available!

I recently ran into an issue where certain BAMs will not load into IGV.js but will load into IGV without a problem. I was also able to get these to work with pileup.js, although I would prefer to use IGV.js for a number of reasons.

A few things I have ruled out (I think):
- Server compatibility -- have ruled this out by downloading an example BAM from IGV.js docs to our server and confirming I can display it correctly in my IGV.js setup (see below for which BAM this was).
- Header size -- our BAM files have a lot of contigs in them as they are not aligned to a genome but a custom reference with several thousand contigs using bowtie2. I have since confirmed that this is not the issue (at least not the only issue) by taking only a very small subset of these contigs and their respective reads and confirming that this does not work either.
- Contig names -- our contig names are non-standard, containing '-' and '_' characters. I generated sets with generic contig names: seq1, seq2, etc. and this did not solve the problem.
- Samtools version -- we were using quite an old version of samtools to generate and index the BAM and fasta files. Upgrading did not seem to solve the problem. Although there did seem to be a few test cases where switching to the newer version seemed to change behavior, it has not allowed me to display our files.

I am a little stuck at this point and am wondering if there are any known issues with BAM file compatibility or if someone would mind taking a quick look at small example files (see below). Note I have also changed the sequence entries for all reads and contigs to be made up of As but maintained the other information in the SAM/BAM for sharing here (this maintains same phenotype regardless of seq).

Here are the example BAM and sam files + indices (I have also included the plain text SAM formatted file there as well):
https://www.dropbox.com/sh/qmtfsbiv3oatemh/AABOabgJrxg2xqAMYVLIXW-va?dl=0

These were generated by taking a plain text SAM format file that is a subset of my full files, converting to BAM with `samtools view -bhS file.sam > file.bam`, `samtools sort file.bam -o file.sorted.bam`; `mv file.sorted.bam file.bam`; `samtools index file.bam`. Fasta index was generated with `samtools faidx fasta.fa` with samtools 1.3.1 (have also tried with 0.1.19).

Here is an image of the files loaded into IGV.js (all of seq4):
![image](https://cloud.githubusercontent.com/assets/19783927/17834393/5dbfaed8-66f3-11e6-9727-87a2c8ed154b.png)

Here are the same files loaded into IGV (all of seq4):
![image](https://cloud.githubusercontent.com/assets/19783927/17834498/9c3621de-66f7-11e6-941e-5172d979d5e2.png)

Note this is not specific to seq4, it happens with all the seqs in this file and many others I have tried.

An example BAM I downloaded from `https://data.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam` works both on our server and on the original hosted URL from the example in my IGV.js setup.

These are the options I am using with IGV.js:
```
    var options = {
        showNavigation: true,
        showRuler: true,

        reference: {
            id: "partial_sub",
            fastaURL: <url_to_fasta>,
        },
        tracks: [
                        {
                url: <url_to_reads>,
                name: 'reads',
            }
        ]
    };
```

If you need anything else please let me know and thank you in advance for your help with this!

**Comment by jrobinso** [comment]
Thanks for the detailed report and the test files!   It makes finding problems so much easier.

**Comment by jrobinso** [comment]
This should be fixed now.  I don't actually know why your files were different,  but we were trying to be entirely too clever in guessing the bam header size to save a few bytes transferred.   I simplified this code and it fixed your case.   Please reopen if this occurs again, and thanks again for such a detailed report.

**Comment by jrobinso** [comment]
The fixes have been pushed to the beta build

    <link rel="stylesheet" type="text/css" href="https://igv.org/web/beta/igv-beta.css">
    <script type="text/javascript" src="https://igv.org/web/beta/igv-beta.min.js"></script>

**Comment by andrewhill10X** [comment]
Awesome, thank you very much for all your help! This does indeed seem to fix the test case. There still seems to be a problem loading our full-size files and I think I have a better idea of where things are going wrong. I changed the requested size like so:

```
var len = index.headerSize + MAX_GZIP_BLOCK_SIZE + 1000000 // rather than 10000
```

and rebuilt the module. This allowed our full size files to display without a problem. It looks like you are already trying to calculate the size of the header here, so I was a bit confused why this did not scale appropriately.

The underlying issue appears to be that index.headerSize is always calculated as zero for our files, so the request is always constant: `MAX_GZIP_BLOCK_SIZE + 10000`. Looking through the code briefly, it is not entirely clear to me why this is the case for our files in particular, but this does appear to be happening for both the full size files and the test files that I sent you.

**Comment by jrobinso** [comment]
OK,  thanks for the update.   I'll try to determine why size is 
calculated as zero, rather than just add a large number.

**Comment by jrobinso** [comment]
Hi,  I think I've got this worked out but for testing purposes could you supply the header of one of your full-size files,  or better the header with 1 or 2 alignment records,  but just the header would be enough.  I want to be sure we can read it.   Thanks.

**Comment by andrewhill10X** [comment]
Thanks again for all your help, this seems to work great. I rebuilt with
your most recent commits and it reads from our full size files without
modification. If you would still like the header, I can provide it, but it
would be later tonight (the files I sent are linked on my personal dropbox
which I don't have easy access to on work comp).

**Comment by jrobinso** [comment]
As you've verified it I don't need the header, unless it recurs.

Here's a brief explanation.   The code uses the bam index to get the 
start of the bgzipped "block" that contains the first alignment record, 
which marks the end of the header section.  It finds this block by 
looking at the "v pointers" for each bin as defined in the bam spec.   I 
had not noticed this before, but there is an optional "psuedo" bin in 
the index which does not contain pointers to bam records.  It is 
recognized by looking at the bin number,  which is (I'm not making this 
up) 37450.   Your index files have this psuedo bin,  and the code was 
incorrectly treating it as a valid bin.

**Comment by andrewhill10X** [comment]
Oh wow, I had no idea that was in the BAM spec... Thanks a bunch for helping to track this down, everything seems to be working so far!
