### ISSUE TITLE
'Height' in track's option doesn't work

### ISSUE THREAD

**Issue by desnar** [igvteam/igv.js#243]
Hi,
    The height property doesn't work. I need to change the height by set the 'set track height' after opening.

**Comment by jrobinso** [comment]
Hi,  could you elaborate on what doesn't work,  with some example code?  What exactly are you trying to do?  There is no "set track height" API function.

**Comment by turner** [comment]
I am looking at this now. I tested with a BAM track and it works fine. What track type are you working with?

**Comment by desnar** [comment]
For the options controlling the igv in html's javascript, the height property in a track can't work, though I set autoheight to false. The only way for me to set the height of a track is using the button on the right of the track after displaying in the browser.
Thanks.

**Comment by jrobinso** [comment]
Could you post your html,  or just the configuration options object,  so we can reproduce the problem?

**Comment by jrobinso** [comment]
Also are you pulling code from git, or using a released or beta version?  If so which version?  In general please be more descriptive of issues when you post them.  Including example code or html illustrating what is failing is helpful.  We can't act on "doesn't work".

**Comment by desnar** [comment]
I'm sorry to post the example so late...
I see track info in 'https://github.com/igvteam/igv.js/wiki/Tracks, 1) Options for all track types' and I set this property in bam.html (https://github.com/igvteam/igv.js/blob/master/examples/bam.html)
![image](https://cloud.githubusercontent.com/assets/7296885/17917112/e033fd42-69eb-11e6-8955-8ff92ac310a7.png)
When I run this html in my apache server, it's still the default height.
![image](https://cloud.githubusercontent.com/assets/7296885/17917145/3e6b8182-69ec-11e6-86dd-7ae676404740.png)
The right button on the bam track can work when i use 'set track height' to 200
![image](https://cloud.githubusercontent.com/assets/7296885/17917166/77b8535c-69ec-11e6-8beb-b0017f24b5b5.png)

**Comment by jrobinso** [comment]
I just checked in a change to turn autoHeight off if height is set.   This will be in the nightly "beta" url build, or you can pull from source.  

However this also works with the current release.  Note autoHeight is case sensitive.  This is an error in our documentation.
{
                            url: 'https://data.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam',
                            name: 'Brain (BodyMap)',
                            height: 200,
                            autoHeight: false
                        }

**Comment by desnar** [comment]
It seems work for bam but not for wig-bedgraph format?
![image](https://cloud.githubusercontent.com/assets/7296885/17919823/c37a9ab4-6a02-11e6-9f65-f77c6b1110c6.png)
![image](https://cloud.githubusercontent.com/assets/7296885/17919830/d16827f4-6a02-11e6-970c-ad54f79f73e3.png)

**Comment by jrobinso** [comment]
This should be fixed now for bed and wig.  Apologies for that.

**Comment by skycolloredo** [comment]
Hi Jim, 
I am having a similar issue with seg files. When I set the height in the track configuration in the way demonstrated above, it the heatmap track height remains very short. Is there a way to adjust the height of heatmap tracks?
Thanks!
Sky

**Comment by skycolloredo** [comment]
Hi Turner, 
My problem was I was using height when the relevant property was expandedRowHeight. Adjusting that fixed things. 
Thanks!
Sky
