### ISSUE TITLE
how to set up 'showGuideLine' option.

### ISSUE THREAD

**Issue by subji** [igvteam/igv.js#244]
i don't know where is 'showGuideLine' option.

i'm use to igv.js v1.0.1

i figure out that option on wike and igv.org 

but there are nothing any explain about 'showGuideLine' 

so how to set up that option ?

**Comment by jrobinso** [comment]
Could you please tell us what exactly you want to do?

**Comment by subji** [comment]
at #207 

vertical line configuration is 'showGuideLine'.

how to set up configuration of 'showGuideLine'

**Comment by jrobinso** [comment]
Yes, I know what you are referring too,  but what do you want to do?  That option has not been released, when it is it will be described in the documentation.   In the meantime if you can describe what you want to see I might be able to point you to code that would be helpful.

**Comment by subji** [comment]
That options has not been released..? 

sorry, I knew it was already released.

**Comment by subji** [comment]
ok, i want to draw vertical line.

![image](https://cloud.githubusercontent.com/assets/8937254/17881651/15b172b0-6942-11e6-9069-f55d9917c5b6.png)

like above picture.

so i saw this post in looking for the wiki #207 

In the last article above 'show GuideLine' option I thought the picture would be implementing the same functionality.

However, that option was not anywhere.

So would you want to know how to set the options.

**Comment by jrobinso** [comment]
That hasn't been implemented yet.

**Comment by subji** [comment]
ok, thank you
