### ISSUE TITLE
Difference in transcript/exon rendering between IGV and IGV.js

### ISSUE THREAD

**Issue by MichielVanBel** [igvteam/igv.js#246]
Example GFF3: http://www.psb.ugent.be/~mibel/zma.v3.exon.gff3

In the standalone version of IGV, the exons are rendered as part of the transcripts (using parental relationships as defined in the GFF3 file), while using the 'expanded' view. See  example here: http://www.psb.ugent.be/~mibel/IGV_gff3_example.png  

In IGV.js when using the same GFF3 file and using the 'expanded' view, the exons are rendered on different lines as the transcripts. See example here: http://www.psb.ugent.be/~mibel/IGV_js_gff3_example.png

I've searched for multiple ways (options for IGV.js, adapting the GFF3 file) in order to get the same kind of rendering in the annotation track as with the standalone IGV version, but no luck so far.

**Comment by jrobinso** [comment]
Hi, this should work,  what version of igv.js are you using?

**Comment by jrobinso** [comment]
I figured out the problem.   Combining GFF features was only enabled for indexed files.   As we generally index all files this wasn't noticed.   I just pushed a fix.    If you need this before the next release you could index your gff3 files, using tabix or igvtools.   Indexing is important for igv.js if its a large file,  you can overwhelm the browser memory otherwise.

**Comment by MichielVanBel** [comment]
Hi, we didn't use indexing of the GFF3 files, because we need the search option to work for gene-identifiers (and as explained here https://github.com/igvteam/igv.js/wiki/Tracks the searchable option doesnt work for indexed gff3 files). I try to minimize the size of the GFF3/BED files by removing any unwanted features, which should help reduce the memory footprint as well.

**Comment by jrobinso** [comment]
OK.  Are you using a release URL, or pulling from git?  The problem is fixed in code, but not in any packaged release.  

Another way to support search is to provide your own webservice.
