### ISSUE TITLE
Support for CRAM files in IGV.js

### ISSUE THREAD

**Issue by MichielVanBel** [igvteam/igv.js#247]
CRAM file support in IGV.js would be a great way to reduce the disk space usage necessary for the BAM files. 

Are there any plans to include CRAM support in IGV.js?

**Comment by jrobinso** [comment]
Hi, CRAM is an enormously complex format and will not be supported in igv.js until a javascript reader is available.    The likelihood of that in the near future is low.

**Comment by matthdsm** [comment]
Hi,
Are there any evolutions regarding this issue?

Thanks
M

**Comment by jrobinso** [comment]
No, its unlikely we will be able to support this anytime soon.   It's a
very complex format and there are no javascript libraries to read it that I
am aware of.   If you are aware of one please let me know.

**Comment by jrobinso** [comment]
This could be supported with some server-side code, not too difficult if
you have the ability to do that.  If interested reply and we can discuss
further.

**Comment by matthdsm** [comment]
Hi, 
Thanks for the reply. I'd be very interested to hear your proposition. For the moment, the bam files in our app are read from local storage, so there isn't much server to begin with.
We are planning however to move our data storage to a dedicated server in the middle term.
All help is welcome!

Cheers
M

**Comment by jrobinso** [comment]
Its more of an idea than a proposition.    The idea is to write a
webservice to query the cram file on the server, and return the results as
SAM, BAM, or GA4GH records in the response.   The webservice could use
samtools or the htsjdk to do the query, perhaps there is a python library
that could be used as well.   I would be interested in collaborating on
such a project, but don't have the cycles to take the lead on it.

**Comment by bw2** [comment]
Hi Jim, 

It would be great to collaborate on this.  pysam can read cram files and I've written python code before to proxy igv.js range requests to backend http servers. One thing I'm stuck on is what igv.js track type is best to use - as I'm not sure how to convert crai <=> bai indexes.

**Comment by jrobinso** [comment]
Hi,

Actually, we've already done this using flask & pysam, but it's not quite
finished.   See the igv.js-flask project and this page in particular:
https://github.com/igvteam/igv.js-flask/wiki/Alignment-service.  These
instructions might change slightly.    I still need to write the reader for
this in igv.js and we'll be ready,   I'll try to do that next week.

**Comment by bw2** [comment]
great! looking forward to using this.

**Comment by jrobinso** [comment]
Instructions to come shortly, but look at dev/cram.html in conjunction with the igv.js-flask project.  You must enable CORS on the flask server, unless it also serves your html server.  To do this add the following to _config.py:  ENABLE_CORS_REQUESTS = True

**Comment by bw2** [comment]
Thanks Jim. 
We're now able to use igv.js to view crams that are stored in google buckets 
by using https://github.com/igvteam/igv.js-flask & gcsfuse mounts.

**Comment by mbookman** [comment]
Hi Jim.

I was wondering if you had any intent of extending the [htsget](https://github.com/igvteam/igv.js/wiki/htsget) support in igv.js to support CRAMs. Or is server-side conversion the expected solution for the foreseeable future?

Thanks.

**Comment by jrobinso** [comment]
There is no javascript decoder for CRAM, so yes that needs to be converted
on the server.    if you know of any efforts to support CRAM decoding in
javascript let me know.

We have a flask server that reads and converts CRAM files on the server to
stream to igv.js.

I don't check for CRAM in the htsget reading code so that will likely fail
if tried.   It would be a nice addition to be able to tell the server what
format the client supports.

**Comment by jrobinso** [comment]
Yes I'm aware of that, thanks, and talked to the author of that module,
Robert Buel, recently.   I plan to incorporate it into igv.js in the next
couple of months.

BTW are you using the Flask solution?

**Comment by bw2** [comment]
Wow that's great. 
Yes, we're using the Flask solution to serve cram files to seqr.

**Comment by anderspitman** [comment]
Hey @jrobinso, is CRAM now implemented? I see #813 but not sure if it's ready to be tried or not.

**Comment by jrobinso** [comment]
@anderspitman Yes, it should be ready.

**Comment by anderspitman** [comment]
Awesome, the timing couldn't be better! We'll try it out

**Comment by jrobinso** [comment]
This is not released to NPM yet,  it will be soon (within a week).   To
test now you'll need to pull from github.

**Comment by jrobinso** [comment]
Or use this distribution  http://igv.org/web/snapshot/dist/

**Comment by anderspitman** [comment]
Oh nice that snapshot will be helpful. I was having some issues getting master to work. I think something to do with esm modules. Getting a build from you will at least remove me building it wrong as a variable.

**Comment by jrobinso** [comment]
@anderspitman If your having problems building open a git issue,  it should just work.  You might have to do npm install first.   The "esm" bundle is for use as an ES6 style module  (import),  otherwise ignore it.
