### ISSUE TITLE
What is the max number of reads before IGV.js crashes?

### ISSUE THREAD

**Issue by david-ma** [igvteam/igv.js#249]
I had someone load a BAM file with 500,000+ reads and the browser crashed.

I'm going to put in a little warning that detects if the BAM is too big that directs them to open the file in Desktop IGV instead of in-browser IGV.

Is there a known limit to the number of reads that IGV.js can handle? Or does this depend too much on the browser/machine you're using?

**Comment by jrobinso** [comment]
There's no way to know that, but igv never loads the whole bam file, the 
total size is really not relevant.  Some of the example files are 300+ 
GB in size.  Were the default settings for visibility window and 
down-sampling changed?   Its possible if this is excessively deep 
coverage that the visibilityWindow for the track should be reduced from 
the default value of 30000. Coverage depth is more important than total 
size.

It would be interesting to open developer tools and see if there are any 
errors in the console.

I would need access to the file to assist further.

**Comment by david-ma** [comment]
Downsampling was turned off, and the read depth at that location was 500,000

I've set a friendly message that warns the user if the read depth at that locus is more than 10k, but they can very easily click "continue" to dismiss the warning for the rest of the session.

**Comment by jrobinso** [comment]
Downsampling should never be turned off,  you are guaranteed to freeze 
the browser if you do.   Every bam file has regions of crazy deep 
coverage, regions of low complexity that everything maps to.    There is 
really no legitimate reason to turn it off altogether,  I might remove 
that as an option.

**Comment by david-ma** [comment]
Maybe our use case is different, I'm navigating the users to specific locations using the igv.browser.search() function, users don't usually scroll through regions of low complexity.

I've been setting `downsample` to false [here](https://github.com/igvteam/igv.js/blob/82903d8a8eb7ab15791388d8a21738405e58ac20/js/bam/alignmentContainer.js#L29), which results in `samplingDepth` being set to Number.MAX_VALUE [here](https://github.com/igvteam/igv.js/blob/82903d8a8eb7ab15791388d8a21738405e58ac20/js/bam/alignmentContainer.js#L52).

If I set `downsample` to true, and then set samplingDepth to 10,000 then that should allow other files to be browsed normally (with no down sampling) and only larger files will be down sampled. Correct?

Is there a visual cue to show that an area is being downsampled? I believe there is a black bar visible in Desktop IGV that tells the user whether or not downsampling is on/off.

**Comment by jrobinso** [comment]
I've just pushed a change.  You can no longer set downsampling to false, and the maximum sampling depth is 2500.   This is already more than can be displayed in the browser due to canvas size issues.   I'm not sure you are interpreting downsampling correctly,  this means that there are up to 2500 alignment records in every 100 bp window.   It is not some total number of alignments viewable.  

All alignments are loaded and counted for coverage, and a representative sampling is kept for display.   

Yes there is a visual cue, the same black bar as in igv desktop.

The total size of the file is not relevant here, as I said before.

**Comment by david-ma** [comment]
I think I'm going to have to read a bit more and talk to the users more to understand the issue here.

From my current understanding, 25% of the variants that the users are looking at have a read depth of greater than 2500 (I.e. there are more than 2500 alignment records within 100bp of that location).

If these variants are not being displayed correctly due to canvas size issues, then this will need to be addressed.

**Comment by jrobinso** [comment]
David, I'm having a hard time parsing your statement,  but you don't need to see every individual alignment to see the variant.   If they want to see every individual alignment in a deep coverage situation, then neither IGV desktop nor igv.js is the tool.  Do your users really scroll through 1000s of alignments examining each one individually?  A truly random downsampling, such as IGV does,  handles this situation very well.  In fact even variant callers such as the GATK do this.  If you have a specific case where this fails we can discuss that.

**Comment by david-ma** [comment]
Yes they really do open the whole thing, sort by base, and then scroll down through 1000s of alignments before they are satisfied that the reads are correct.

Some users have even asked for BAMs to have an squished and expanded view.

**Comment by jrobinso** [comment]
Yes, we will add a squished view.  You've seen what will happen if you try to keep all those alignments in memory, you freeze the browser.   Its just not possible.   Reservoir downsampling is the best solution I know,  if 2% of the alignments support the variant 2% of what you see will support it.   In any event we can't support loading an indeterminate # of alignments, there are limits.   They can still scroll through 1000s (2500 is the limit I have set now),  just not 10s of 1000s or 100s of 1000s.

If you have a better solution please propose it.    The limit could be > 2500,  maybe 10,000 when we have a "squished" mode,  but infinite is not supportable.

**Comment by david-ma** [comment]
Ok I've spoken to a user and I think I understand this better now. Downsampling is fine in most cases but in certain use cases they need to see particular reads. E.g. When sequencing to detect Minimal Residual Disease. In this use case, there are 500k+ reads and ~10 variants. The reads with variants need to be inspected for sequencing artefacts and other things.

The users did not seriously expect the 500k+ one to load, they just wanted to see what would happen.
The users often browse panels where read depth is up to 15k, downsampling is 

My solution:
I will load IGV.js as normal if there are less than 2500 reads at a locus.

If there are more than 2500 reads, I will display the text "There are #### reads at this locus. It is recommended that you downsample to 2500 reads or the visualisation may be unreliable and your browser may freeze. Please use Desktop IGV if you need to see all your reads accurately."
And then give them three buttons: [ Downsample to 2500 reads and load using Browser IGV | Load all #### reads using Browser IGV | Load all #### reads using Desktop IGV ]

**Comment by jrobinso** [comment]
That sounds reasonable, and I was thinking along those lines myself.   However, note the following.  The maximum height of an html canvas is ~32,000 pixels.  It varies a bit by browser type (IE is less), but that is close.  So you will have to work out the alignment row height to fit within that constraint.   Also, note there is a "maxRows" setting.

I was confused by your use of the word "variant",  but I understand now.  I interpret the term variant to refer to  a called event at a location,  you are referring to individual base mismatches.   Another solution would be to have a popup view that displays all alignments that have a mismatch at a specific location.

**Comment by jrobinso** [comment]
One thing that does confuse me,  how do you know there are 500k reads at a particular location before coverage is calculated?   Have you computed this offline?   The size of the bam file is not important, there are typically millions of reads in a WGS bam file.

**Comment by jrobinso** [comment]
David, another possibility is to make the downsample bar (the black bar) a little more prominent, and clickable.  Clicking might give you an option to see, for example,  all alignments that have mismatches at that location in a popup window.

**Comment by david-ma** [comment]
Hey Jim! Sorry for the slow reply, some other stuff needed my attention.

> Another solution would be to have a popup view that displays all alignments that have a mismatch at a specific location.

Yes that would be a good way to show certain users what they want need to see.

> How do you know there are 500k reads at a particular location

We use the variant caller's read depth output for the given variant, this is stored when the pipeline is run, and this is how the users decide which locus to navigate to.

> make the downsample bar (the black bar) a little more prominent

It turns out that I had previously set "config.coverageTrackHeight = 30", which was messing up the display of coverage/downsample bar/alignments. They were overlapping in inconsistent ways, but I have fixed this by removing that config and so it just defaults to 50.

---

This is my warning when IGV.js opens now (no warning shows if it is under 2500 reads/alignments/counts)

<img width="862" alt="screen shot 2016-08-31 at 11 05 24 am" src="https://cloud.githubusercontent.com/assets/3320713/18112867/8ab3ef0c-6f6e-11e6-8c9e-763b13fd275f.png">

**Comment by david-ma** [comment]
I'm getting some weird things happening when files are downsampled.


This part is expected. The count is 2655, and I've downsampled the reads to 2500.

IGV.js is correctly displaying a black bar, and says that 155 samples have been downsampled.

<img width="449" alt="screen shot 2016-08-31 at 11 53 15 am" src="https://cloud.githubusercontent.com/assets/3320713/18113264/a41d1088-6f71-11e6-910f-469e253e2b9f.png">

---

However... right next to it, you can see in the coverage that there s a region with **more** counts.

There are 3949 counts here, and there is no black downsampling bar. Should I open this as a separate issue? I think the original issue of #249 has been solved with your commit and clarification.

<img width="508" alt="screen shot 2016-08-31 at 11 52 50 am" src="https://cloud.githubusercontent.com/assets/3320713/18113305/e7f598e8-6f71-11e6-8c04-8c12a2e4580a.png">

**Comment by jrobinso** [comment]
Hi,

Yes you can open a ticket, but if at all possible include sample data.  
I realize this might not be possible.  Downsampling is in windows, you 
set the size, not a sliding window.  Also,  an alignment is full in a 
bucket, or not, if the start position is in the bucket.  Read coverage 
is actual coverage of a base.  So it is entirely possible to have a 
region with high coverage and no downsampling, while the region just to 
the left is downsampled because more alignments start there.

**Comment by jrobinso** [comment]
The warning looks good,  but you can increase the 2500 number for these 
situations by reducing the alignmentRowHeight.   The real limit is 
32,000 pixels / alignmentRowHeight.   Also note the maxRows setting,  
which would need to be increased as well.
