### ISSUE TITLE
User interface for sorting

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#250]
Currently you can sort alignment and copy # tracks by "alt-clicking".   Obviously this is not all that intuitive,  although it is convenient.   Can we think of a better user interaction?   This issue is for discussion of the issue.

**Comment by bw2** [comment]
It seems to me that putting it in track settings would be intuitive

![image](https://cloud.githubusercontent.com/assets/6240170/18039019/bf1b3c36-6d6c-11e6-9710-9d47926f7e19.png)

**Comment by jrobinso** [comment]
Thats one possibility, Ben, but then sort at what locus?   In IGV desktop the sort is always based on the base location at the center of the view, which is framed by guidelines.   Perhaps this is the right way to do it.  You have to (possibly) drag to get the desired location centered, then sort.   The current "alt-click" is a one click operation.    The 2 are not mutually exclusive.

**Comment by turner** [comment]
This is closed with commit 94eba273

A sort item has been added to BAM track menu. Click the item to sort alignments based on genomic location within the centered guide.
