### ISSUE TITLE
Hitting return should close dialogs

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#252]
For the track menu items that bring up a dialog (e.g. set track height, or set track name) - the OK button is highlighted to indicate it's the default action. And indeed, if you enter a value and hit return the new value takes effect, but the dialog doesn't close. So the Cancel button is still there, but it's too late to Cancel. The dialog should have closed when the value takes effect.

**Comment by turner** [comment]
Closed with commit f976226f
