### ISSUE TITLE
Multiple genes view for copy number segment

### ISSUE THREAD

**Issue by JiaoJiao123** [igvteam/igv.js#257]
In the current version of igv.js, we can only use single gene as locus in the options setting. If we could visualize multiple genes at the same time like IGV desktop version, that would be great.

@jrobinso 
hey Jim, this is Jiaojiao Wang from Sloan Kettering Cancer Center. We are trying to replace current IGV tab (which is using IGV desktop) with igv.js. A summer student worked on this earlier and had some conversations with you and JJ through email. I will continue to work on this.  

Do you have any update on this issue?

**Comment by jrobinso** [comment]
We've had some design discussion but haven't implemented this yet.  If you
are ready to use it we will prioritize it.   Have you been able to get
igv.js integrated for a single gene view?

**Comment by JiaoJiao123** [comment]
@jrobinso 
Yes, we are definitely ready to use it. We would appreciate it if you could prioritize it.

I tried to use igv.js for single gene view but I got two problems. 
1) Currently we passed in copy number segment file through url under options and tracks setting. But we don't think it is a good approach to store copy number segment data in a file in cBioPortal. Firstly, it is not secure. Secondly, we can't customize the data returned. Thus we developed new API to fetch copy number segment data based on hugo symbol, cancer study id and sample ids. But the result is returned in JSON format. Could you add the option to accept JSON format data source as input? 

2)Say we have two genes from user input: BRCA1 and BRCA2. We could create single gene view but can't have them on the page the same time. I looked into igv.createBrowser and saw it only allow one browser.  
if (igv.browser) {
            //console.log("Attempt to create 2 browsers.");
            igv.removeBrowser();
}
If that's true, we have to wait till the multi genes view get done, because we can't add single gene view for all genes on the condition that each single gene need a igv browser to hold it but only one browser is allowed.

**Comment by jjgao** [comment]
@jrobinso Thanks for the quick response!

For @JiaoJiao123's first point, is it possible to pass in data (instead of url) for initialization? In any case, this is not high priority since we can also change our web api to return segment format.

For the second point, is there a way to create multiple igv instance on the same page?

Thanks again!

**Comment by jrobinso** [comment]
Hi, no you can't have multiple igv instances.  I wasn't suggesting the single gene view as a solution, just wanted to know what progress you have made.   As a test its a good first step.

Instead of passing in data could igv.js query a webservice you provide to fetch the segments as json objects (i.e. your web API)?  We do support webservices in other contexts that return objects in a json format.   We just need to agree on an API and json spec.  At a high level your webservice should accept a genomic range (chr, start, end, and perhaps assembly ID),  and it should return a collection of copy # segments.    Ideally the json objects representing segments should have (at a minimum) these fields

sample
chr
start
end
value

It can have additional fields, which would be used for popup text, but those are the minimum required to display the segment.

**Comment by jjgao** [comment]
Hi @jim, I just discussed with @jiaojiao, we are going to do the following the solve the problem.

1) we are going to return segment file format from our web api for igv.js.
2) we are going to use iframe to support multiple instances of igv.js before you implement the multi-gene view.

One last feature request: is there any method to sort samples based on copy number values of a gene or region?

Thanks!

**Comment by jrobinso** [comment]
OK re (1),  but supporting a webservice would be very easy, we already do
it for multiple projects.

re (2),  there's not a public API yet,  there is a function to do it
(igv.SegTrack.prototype.sortSamples) that is triggered by an alt-click.
We will provide an API.

**Comment by JiaoJiao123** [comment]
@jrobinso 
If support web service would be very easy, could you please add support for JSON format? I would like to use that once it is ready. Feel like it is the proper way. 
Below is an example for the JSON result returned from our API
[{"sample_stable_id":"TCGA-AF-5654-01","chromosome":"7","start":"132672067","end":"158385118","num_probes":"13493","segment_mean":"0.3068"},{},{}...]

**Comment by jrobinso** [comment]
Could you provide instructions for querying the webservice, and an example
query I can use to test with?

**Comment by JiaoJiao123** [comment]
@jrobinso This is the document for the API https://docs.google.com/document/d/1mqqnyDeaWN0uTDuBU2bzUBFwetUWHX_PtHstCeCpnLk/edit
I will build a war file for you and send you the link

**Comment by JiaoJiao123** [comment]
@jrobinso actually war file isn't going to work since it has to be inside of mskcc network. I made a screenshot of how I access the api and let me know what else you need.
![screen shot 2016-09-09 at 11 00 21 am](https://cloud.githubusercontent.com/assets/13951023/18391734/f460aac0-767c-11e6-92f2-cb1d72a8e2bd.png)

**Comment by jrobinso** [comment]
I can't really develop against a screenshot.    Is there any possibility of deploying a public test webservice?    

If you can do that can you copy the url text,  and capture the json returned into a file?  You can use postman to do this, probably other tools,  or using "file save" from the browser would probably work.   Also, is this a "get" api?  If its a post I will need the body.

I do see one problem with the screenshot.  You are passing a gene symbol to the webservice,  IGV will be passing a genomic range.   Is the database queryable by range?

**Comment by JiaoJiao123** [comment]
@jrobinso I am sorry about the oversight. Attached are two files. 
reuslt1.txt is for http://localhost:8080/cbioportal/api/cnaSegmentService?cancerStudyId=coadread_tcga&hugoSymbols=BRAF,EGFR
result2.txt is for http://localhost:8080/cbioportal/api/cnaSegmentService?cancerStudyId=coadread_tcga&hugoSymbols=BRAF,EGFR&sampleIds=TCGA-AF-5654-01,TCGA-AG-3732-01
[result1.txt](https://github.com/igvteam/igv.js/files/464368/result1.txt)
[result2.txt](https://github.com/igvteam/igv.js/files/464369/result2.txt)

It is a GET api. Yeah we are querying copy number data based on gene. And chromosome, start and end position are in the returned result, which should be good as the IGV data input.

**Comment by jrobinso** [comment]
Query by gene is not going to work for IGV,  we need to query by genomic
start and end.  Otherwise when the user pans there will be nothing.   Could
you add this as an option to your webservice?

**Comment by JiaoJiao123** [comment]
@jrobinso sorry but I don't see how the API from igv.js user case could affect its implementation. I thought as long as the data returned from API has start and end position, it should be enough to visualize IGV viewer. Please correct me if anything wrong.

**Comment by jrobinso** [comment]
IGV queries files and webservices by genomic position,  where would the
gene parameter come from?  There could be many genes in view,  or none at
all,  and the user is free to move wherever they want irrespective of where
you start them.     We  could make a special exception for your case,  but
that is how it works.

Are you unable to support a query by genomic range?   The segments are
normally described by a range, not a gene.

**Comment by JiaoJiao123** [comment]
@jrobinso oh ok, I see what you mean. This is the query part I should have let you know: we return copy number segment data for the whole chromosome that gene is located, not just for that gene. 

Say user input BRAF, and we will return all copy number data in chromosome 7, that way the user is able to move anywhere in chromosome 7.

**Comment by jrobinso** [comment]
Hi,  I don't think I"m communicating properly.  IGV is a general genome
browser, we aren't creating a special tool for gene-based analysis.    The
multi-locus view enables IGV to display multiple genomic regions
simultaneously, but each view is still a genome browser, may or may not
contain annotation such as genes.   The bottom line is we can support
queries by genomic coordinates,  or files.

We could also probably support a webservice that returns all copy #
segments for the entire genome,  basically like a non-indexed file.   This
would be new but not a big change.

So your choices are (1) .seg files,  (2) a webservice that takes genomic
coordinates and returns seg json objects, or (3) a webservice that returns
all copy # segments for the dataset.

Jim

**Comment by JiaoJiao123** [comment]
@jrobinso ok get it. Then we will change our API to return seg file as JJ said earlier. Thank you.
