### ISSUE TITLE
bam/bai net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#258]
Looks like a similar issue to (https://github.com/igvteam/igv.js/issues/254) is happening with BAM files.  Issue resides within bamReader.js

I was loading in a small BAM for testing, and noticed CLM errors.
e.g. to re-create, simply make a bam with a single paired read.

This is again related to the lines where 65000/MAX_GZIP_BLOCK_SIZE is added to the range request length.  This has the potential to request more bytes than the file contains and result in a CLM.

Fix is here.  Happy to PR.  Though it may be useful to run this through some additional tests.
https://github.com/blajoie/igv.js/commit/6a8de944084e831fa3974b5cfc94cb949e641520

**Comment by jrobinso** [comment]
I can't reproduce this error.  Furthermore I don't really understand where its coming from.   It should be no problem according to the http spec to request a range of bytes that extends beyond the end of the file.  In that case the server should return the bytes available.  The response header tells you what was actually returned.   For example, in my test case (the YC tags bam in igv-dev.html) the following is requested 
 
Range:bytes=143-65467

This is more bytes than are available in the file, the file is 467 bytes total.   The server responds with a 206 code, no errors, and the following header

Content-Range:bytes 143-466/467

The alignments display as expected.   So if you have a bam file and html to reproduce this I would like to see it.  Perhaps it is browser dependent?

**Comment by jrobinso** [comment]
Also, what server is this?   It could be the server is not returning the correct content-length in the response header.   I can see how this could cause an error in the browser.   If there is a commonly used out-of-spec server in use we'll have to work around it, but I'd like to understand the issue first.

**Comment by blajoie** [comment]
Hmm, let me take a look at my server spec and see if that could be the culprit.
I am using a FLASK server on my end , very similar implementation to the way the exac_browser is set up and similar range_request logic as in lines 876-910.
https://github.com/konradjk/exac_browser/blob/master/exac.py

Using chrome as my browser - have not yet tested using other browser, but will do so and then report back.

**Comment by jrobinso** [comment]
This looks like a server error.   See the http spec for range-byte requests, particularly section 4 here https://tools.ietf.org/html/rfc7233#section-2.1.     Having said that, if FLASK is out-of-spec in some way and can't be fixed we'll have to try to work around it in the client.

**Comment by blajoie** [comment]
You absolutely correct Jim - thanks for directing me to the server code.

It looks like I now have things working again (after rolling-back my JS code) and fixing the range_request in my flask app.  Testing things now.

Appreciate it!

**Comment by jrobinso** [comment]
I'm not familiar with flask, it sounds like it doesn't really work out of the box for range requests.    How much manual setup is required?  Is there flask documentation to help?  I think this is/will be a popular server perhaps we need to add something to the igv.js wiki for flask.

**Comment by blajoie** [comment]
Yes - flask does not seem to work with CORS/range_requests right out of the box.   Some simple setup is required to properly configure all routes.   Once I do a bit more testing, I would be happy to share some flask boiler plate code with range_request + CORS support to future users/questions.

**Comment by jrobinso** [comment]
I'm sure that would be much appreciated.  Flask is a very popular server in the community.

**Comment by blajoie** [comment]
Just to follow up re. the request/response of yc_bam

```
-jrobinso
Range:bytes=143-65467
Content-Range:bytes 143-466/467
```

I produce the following request/response.

```
-request-
Content-Length:
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Connection: keep-alive
Range: bytes=143-65467
Dnt: 1
Accept: */*
Accept-Language: en-US,en;q=0.8
Content-Type:
Accept-Encoding: gzip, deflate, sdch

-response-
Content-Disposition: attachment; filename="/igv/test/yc_tags.bam"
Content-Transfer-Encoding: binary
Accept-Ranges: bytes
Content-Range: bytes 143-466/467
Content-Length: 324
```

All bam files seem to be working for me now, only still having issue with the small bed(s).
