### ISSUE TITLE
featureFileReader.js - slice offset + missing features

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#262]
Starting this as a seperate issue - from (https://github.com/igvteam/igv.js/issues/254) 

I am using the below (Broad-supplied) file, both as a non-indexed BED and as tabix + bgzip bed

```
https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed
bgzip gencode.v18.collapsed.bed
tabix -p bed gencode.v18.collapsed.bed.gz
```

Top track is gencodev18 bedgz+tbi, bottom is raw unindexed gencodev18 bed.
If you zoom to the beginning of chr1, some bytes/lines of data are missing on my end?  Can you replicate?
![bedgz-vs-bed-bug](https://cloud.githubusercontent.com/assets/8889420/18395159/2e9fd8ce-7672-11e6-8667-77f4ee7040c2.png)

I've tracked this down to line 174 of featureFileReader.js
slicedData = startOffset ? inflated.slice(startOffset) : inflated;

I've modified as such:

```
// bug ?
//slicedData = startOffset ? inflated.slice(startOffset) : inflated;
slicedData = inflated;
```

Slicing by the startOffset seems to put us ahead of where would like to be in the bytearray?
Perhaps the startOffset is incorrect here?
Removing the slice, fixes the issue, and now both the bed and bed.gz+tbi show correctly.
![bedgz-vs-bed-fixed](https://cloud.githubusercontent.com/assets/8889420/18395161/30a12128-7672-11e6-8e98-779d1abb12c2.png)

**Comment by jrobinso** [comment]
I can't reproduce this,  I followed your steps and put the tabix indexed file on Amazon.  Can you see if you can reproduce it using this URL?   

https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed.gz

Also, the startOffset for this chunk of features is zero.

If you can reproduce it with the above file can you elaborate on exact steps, i.e. how did you get to that genomic position?    Another thing to check is the tabix version.

**Comment by blajoie** [comment]
Strange, I was not getting a startOffset of 0 for this file, 0 is what I would expect for the above genomic position.

Will check via your file and then respond with a bit more detail on this tomorrow (or at the latest, monday morning)!

Thanks Jim!

**Comment by jrobinso** [comment]
OK,  your change will work but I wan't to understand the cause first.   You might know this, but a tabix index is basically a bam index with a little extra information in the header.   The index works off a "virtual pointer", consisting of 2 parts,  the first is byte position in the file to the start of a compressed block.   The second is a byte offset for the uncompressed block pointed to by the first.   This should be the position at which the queried features start.  Actually it might be before that as features are chunked, not every individual feature is indexed.   So....  ignoring the offset would mean decoding the entire block of features.

**Comment by blajoie** [comment]
Agreed, my change is not ideal as it will cause the entire block to always be decoded, this was meant to be only temporary.   I did check my bed file via IGV-desktop and a normal tabix query, both returned the correct set of features when queried by the above genomic position.  So this suggests that my tabix index is correct/intact.  Strange that you see a offset of 0 using the above query/position.  I will try again using a few pull of the current master (my code does include a few other changes).

**Comment by blajoie** [comment]
This looks to be completely resolved now.

Perhaps it was a creature of to the server mis-config and/or index issue.
In any event, all is now well.
