### ISSUE TITLE
"sweep zoom" bug

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#263]
On chr1 I tried zooming the first 10mb by sweeping from ~ the 10mb ruler mark to the chromosome origin.  I got the error attached.   This might be a regression caused by recent "zoom" changes, I'm not sure.  

![screen shot 2016-09-10 at 8 21 59 pm](https://cloud.githubusercontent.com/assets/933148/18414403/8845eb16-7794-11e6-860e-434fd30f68af.png)

**Comment by turner** [comment]
Bug fix with commit cff63116.

**Comment by jrobinso** [comment]
Still getting this.  Go to all - chromosome view  (e.g. type "1" and go).   Then sweep from anywhere past left edge.   I think you just need to limit the lower number to a minimum of "1"  
![screen shot 2016-09-11 at 11 16 07 pm](https://cloud.githubusercontent.com/assets/933148/18423772/00328300-7876-11e6-94d0-6f8139c4b555.png)

**Comment by turner** [comment]
I have entered "1", "2", etc. Tried all manner of loci. Repeatedly sweeping past left the origin. As far as I can tell the bug is squashed.
