### ISSUE TITLE
BUG: regions in CURSOR not displayed correctly

### ISSUE THREAD

**Issue by noamshoresh** [igvteam/igv.js#270]
Hi,
Elements of main track are not plotted correctly in surrounding regions.
Example shown: two bed files each with a single element, the elements are non overlapping, yet their drawn parts do.
![image](https://cloud.githubusercontent.com/assets/4535755/18757660/e19a59f4-80c2-11e6-849c-0f870714d164.png)

**Comment by jrobinso** [comment]
Closing this issue here,  and opening one in the cursor project.
