### ISSUE TITLE
Exception while search chrx, chry or chrm locus.

### ISSUE THREAD

**Issue by deepaksibar** [igvteam/igv.js#279]
Hi,
Igv.js throws "Unrecognized feature or locus: chrx:100-200" error. As i observed if we pass chromosome names like chrx, chry or chrm instead of chrX, chrY or chrM (here x, y and m are in uppercase), then this error thrown. 

For same locus chrX:100-200 but with X in upper case data is rendered.

-Deepak

**Comment by jrobinso** [comment]
This is not an error, chromosome names are case sensitive.
