### ISSUE TITLE
support all chromosomes view

### ISSUE THREAD

**Issue by JiaoJiao123** [igvteam/igv.js#282]
@jrobinso  In [cBioPortal patient view Genomics Overview](http://www.cbioportal.org/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC), we have static data display for single sample. We would like to replace it with igv.js version if it could support all chromosomes display. Currently, we can only load one chromosome at a time.

**Comment by jrobinso** [comment]
Got it.  We'll do in time for next release.  Do you have a time frame for
that?

**Comment by JiaoJiao123** [comment]
@jmanning2k We will have next major feature release in around two month. If this feature could be done before that, I can work on the integration to cBioPortal and release next time.

**Comment by jrobinso** [comment]
@JiaoJiao123  -- I see you already have a nice display for a single sample,  what do you need igv.js to do?

**Comment by JiaoJiao123** [comment]
@jrobinso In the current static display, we can only see the overall distribution. we want to be able to zoom in and out to view a more specific genomic range.

**Comment by jrobinso** [comment]
But still for a single sample, correct?

**Comment by JiaoJiao123** [comment]
@jrobinso If a patient only has one sample, then yes. In some cases not. Say If a patient has four samples, then there will be four samples in that genomic overview.

**Comment by jrobinso** [comment]
So your webservice will take an argument identifying a patient, and return all segments for that patient?

**Comment by JiaoJiao123** [comment]
@jrobinso I think so. We will be able to fetch segment data by patient ID.

**Comment by jrobinso** [comment]
Hi, I'm back form ASHG and working on this now.  Could you give me an example query for fetching all data for a specific patient?  What is the parameter name?  I tried  "caseID" but that didn't work.

**Comment by blajoie** [comment]
Looking forward to this feature.
Our need is for only a single sample view.

Ideally this would be a user-toggled panel similar to the karyotype panel - a quick visual overview of the individual genome, which can be configured with any number of simple BED tracks.

Or - have you thought about adding the ability to plot directly on the karyotype panel itself?
e.g. some simple BED tracks on the side of each chromosome icon?

Or ideally the ability to visualize via bed12 (breakpoints, inversions, translocations etc etc) as lines connecting various genomic segments (same chromosome, or different chromosomes)

**Comment by jrobinso** [comment]
Hi Brian,  to be clear the view under discussion here is just the "whole
genome" view from IGV desktop.  Its not really a special view, just treat
the entire genome as another chromosome or contig.      The last bit is
related to work on IGV desktop itself,  when I can get away from this to
work on it.  This type of view would be developed in desktop first before
igv.js.

I have not considered anything additional for the karyotype view.   If you
would like to open another git issue for it,  with examples,  we can
discuss it there.  The contributor of that feature is no longer active,  it
doesn't have an owner at the moment.

**Comment by JiaoJiao123** [comment]
hi @jrobinso very sorry about my late response.

The sample Ids for a patient got fetched before genomic overview got constructed. And we get patient's segment data from its sample Ids. 
Here is the [segment api link](http://www.cbioportal.org/api-legacy/swagger-ui.html#!/cn-segment-controller/getCNSegment)
Let me know if this answer your question or not.

**Comment by jrobinso** [comment]
Got it, thanks this is what I was looking for.   The whole genome view is almost ready,  here's what it looks like for those 2 samples 
![screen shot 2016-12-01 at 11 05 54 am](https://cloud.githubusercontent.com/assets/933148/20808111/40343dc0-b7b6-11e6-9d1f-d9716ad0be0f.png)

**Comment by JiaoJiao123** [comment]
@jrobinso It looks great! I just checked it together with JJ and he likes it very much as well. Thank you!

Just one thing to double check with you, are we able to click on a chromosome number and zoom in to that specific chromosome?

Another thing is about the mutation data. As you can see, we also have [mutation track](http://www.cbioportal.org/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC) in the Genomic Overview besides CNA. Just wondering how are we handling high level mutation data like VCF in IGV currently? And is there any example page for mutation data you can point me to?

**Comment by jrobinso** [comment]
Hi,

You cannot click n a chromosome number at this time.  You can type the
chromosome number in the "Search" box.   Perhaps we will support clicking
before release.

Variants are supported from VCF files or webservices implementing the GA4GH
variant spec.   We could also support a custom webservice as we do for the
seg,  but that would require a small bit of development.   You can see how
it looks at this demo:  http://igv.org/web/examples/ga4gh.html.      Also,
if you have a VCF file that is tabix indexed (bgzipped)  you can load it by
url as with any other track.    VCF as you know supports both variant calls
and sample genotypes, the latter being optional.   The example above has 20
or so samples.

**Comment by JiaoJiao123** [comment]
@jrobinso Yeah it would be great if you could support clicking chromosome number later.

Thank you for the info about variant track. JJ said he need to discuss with Niki to decide how will we handle that, since there are some discrepancy between mutation data we have and what the variants track requires. I will keep you updated on how it goes.

**Comment by renyaoxiang** [comment]
Dear @jrobinso 
This is a grate idea, I am hopping to make it work and pull a request. Do you have some suggestion?
