### ISSUE TITLE
phantomjs + igv web link - ReferenceError/TypeError

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#283]
Hi,

I was hoping to get use phantomjs to perform a simple/headless screen capture of igv.js remotely.
http://phantomjs.org/

It looks like there may be some issues with Set.js and igv-create.js?
e.g.

example.js

```
var page = require('webpage').create();
page.open('http://igv.org/web/examples/bam.html', function() {
  page.render('nussetti.png');
  phantom.exit();
});
```

Run as:

```
$ phantomjs example.js

ReferenceError: Can't find variable: Set

  https://igv.org/web/release/1.0.5/igv-1.0.5.js:4370
TypeError: undefined is not a function (evaluating 'igv.createBrowser(div, options)')

  http://igv.org/web/examples/bam.html:83
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2 in j
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2 in fireWith
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2 in ready
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:2 in J
```

phantomjs does indeed work with other browsers (e.g. ucsc)
example.js

```
var page = require('webpage').create();
page.open('http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chr7%3A31204545-36262301', function() {
  page.render('nussetti.png');
  phantom.exit();
});
```

```
$ phantomjs example.js
```

Which yields the following PNG.
![ucsc](https://cloud.githubusercontent.com/assets/8889420/19206553/86cb356a-8c9e-11e6-8d92-36653e2a186f.png)

**Comment by jrobinso** [comment]
Set is definitely defined.  Sorry I don't know much about phantom.js.

**Comment by jrobinso** [comment]
We're working on this, we get the same error when trying to automate unit tests.

**Comment by blajoie** [comment]
Fantastic, thanks Jim.

**Comment by MarWoes** [comment]
This issue seems to occur in every browser that lacks ES6 support (where Set is defined). Including an ES6 shim should add the missing features. See related [github](https://github.com/paulmillr/es6-shim) or serve directly using a [cdn](https://cdnjs.com/libraries/es6-shim).

**Comment by jrobinso** [comment]
@MarWoes  Thanks for the pointer.   I feel this is best included by the pages using igv.js,  we are distributing a library (js file), not a website.     The library requires ES6.   So I think this needs better documented, perhaps with a pointer to the shim.

**Comment by sgratzl** [comment]
you should consider using a [headless chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) instead. Latest web browser technologies.

**Comment by sgratzl** [comment]
you should consider using a [headless chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) instead. Latest web browser technologies.
