### ISSUE TITLE
S3: No 'Access-Control-Allow-Origin' header is present on the requested resource in Chrome 54.0.2840.71

### ISSUE THREAD

**Issue by tweep** [igvteam/igv.js#286]
Hell IGVers, 

I'm trying to access http://igv.org/web/examples/bam.html - however i get this error in Chrome Version 54.0.2840.71 (64-bit) on Mac OS X 10.11.6. 

It worked on previous versions of Chrome. Here's the console error I see: 

XMLHttpRequest cannot load https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/cytoBand.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://igv.org' is therefore not allowed access.
bam.html:1 Uncaught (in promise) Error accessing resource: https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg19/cytoBand.txt Status: 0

Looks like it's related to the S3 config. 

Jan

![screen shot 2016-10-24 at 1 31 18 pm](https://cloud.githubusercontent.com/assets/5687381/19656575/95837fd8-99ee-11e6-92ea-c9412c822e57.jpg)

**Comment by jrobinso** [comment]
Thanks for the report.  The request to s3 is timing out on me.   I suspect
this is some network problem, possibly another attack.   Could you use
developer tools to catch the response?

**Comment by tweep** [comment]
Hi Jim, 

http://igv.org/web/examples/bam.html <http://igv.org/web/examples/bam.html> now works for me without error in Chrome Version 54.0.2840.71 (64-bit)

Thanks for fixing. 

  Jan

**Comment by jrobinso** [comment]
Actually I didn't do anything,  I think it was an intermittent S3 glitch.
These happen from time to time at random.
