### ISSUE TITLE
No datarange show for bedgraph

### ISSUE THREAD

**Issue by desnar** [igvteam/igv.js#291]
Hi,
   The DataRange Lable is not shown for bedgraph after a update recently. 

![datarange](https://cloud.githubusercontent.com/assets/7296885/20088346/7125ce34-a5ba-11e6-8a6b-6f9b529a406c.png)
    The upside of the picture is before and the underside is the newer version igv.js, how could I show the label again?

Thanks.

**Comment by turner** [comment]
Closed with commit: 22efb4c

**Comment by jrobinso** [comment]
This should be fixed now.
