### ISSUE TITLE
Can't select popup data

### ISSUE THREAD

**Issue by desnar** [igvteam/igv.js#292]
Hi,
  I see that #288, but the popup data is still not selectable. The popup header is draggable to move and popup data is to show more info when dragged.
![drag](https://cloud.githubusercontent.com/assets/7296885/20125934/28366334-a66c-11e6-8e8a-27722c5f8bb8.png)
   Moreover, the read info is truncated with ... if its content is too long, Could it be disappeared completely?
Thanks.

**Comment by turner** [comment]
Issue close with commit that allows menu items to be selected - copy/paste'ed.
