### ISSUE TITLE
Exon number shows error

### ISSUE THREAD

**Issue by desnar** [igvteam/igv.js#295]
Hi,
    I grep all exon feature from gencode gtf annotation file to show exon number. But It seems that gtf file only read the first one info, and can't show the correct exon number info when I click to one.

![alk1](https://cloud.githubusercontent.com/assets/7296885/20456529/41216d54-aeb3-11e6-999c-678be9fe4912.png)
![alk2](https://cloud.githubusercontent.com/assets/7296885/20456530/4147db1a-aeb3-11e6-9032-b91438abfeac.png)

**Comment by akikuno** [comment]
Hello,
I am now using the igv.js ver 2.2.2, but the above issue is still happening so I can not get correct exon numbers. Could you tell me how to solve it?
I look forward to hearing from you.

**Comment by jrobinso** [comment]
You could send me a pull request.  When this is prioritized I'll update this issue.

**Comment by jrobinso** [comment]
I can't reproduce this issue, it behaves properly with gtfs I've tested (gencodev24).  If its still an issue please attach a zipped example gtf to reproduce.
