### ISSUE TITLE
Creating a new track

### ISSUE THREAD

**Issue by WesleyvanLee** [igvteam/igv.js#297]
Hello,

I want to create a new track on the IGV that shows ORF's from a fasta file. Is there an easy way create whole new tracks in the viewer? 

Thanks in advance.

**Comment by jrobinso** [comment]
Do you want to develop a custom track, or would one of the current tracks
(e.g. features or wig tracks) suffice with support for a new file format?
Perhaps if you mock up a figure illustrating what you want to see that
would help.

Would the track work directly from a fasta file,  or by loading another
containing "orf" features?

**Comment by WesleyvanLee** [comment]
I want to develop a custom track supporting a different kind of file format. This file contains positions of the ORF features that should be visualized on the current sequence view. The track should directly work from this fasta file.

What i want to see in the viewer is something like this:
![screenshot from 2016-12-22 09-14-51](https://cloud.githubusercontent.com/assets/11502661/21419878/95e5b148-c82a-11e6-9fb4-6207335df0ad.png)




**Example**
ORF number 3 in reading frame 1 on strand foward extends from base 3334 to base 3453.
ATGGTGAACCAGATGATCGGCGGGGTCGGAAACTTTATCCAGGCGATACGATTGAAGTTG
AAGACAACGGGTCATTTTTTATTCGCTCAAATCAAGAAACGACTGATTAGATGTACTTAG

ORF number 4 in reading frame 1 on strand foward extends from base 4117 to base 4233.
ATGTCACTCAAGTGCCAACTGCCGACCAGACGTCGGTCGATCACATTTATCAAACGCTAC
AGGCCTTATATCAGCAACAACAAGCCAAAGAAATTTTTCAAGGGACGACTTTATTAG

ORF number 5 in reading frame 1 on strand foward extends from base 4246 to base 4350.
ATGATTTACAATTTGGTGTTAACGGCAAAAATGTGCAGACTTTTGGCTCCCAAGGCCAAC
AGCGTACAACTGCTTTGTCCGTTAAGCTTGCTGAAATTGATCTGA

**Comment by jrobinso** [comment]
Hi,  I'm not sure I phrased my question correctly.   By "directly from the
fasta" I mean are the orfs being discovered in real time as you view from
the fasta file,  or are you loading a separate file which defines the orfs?
  If the latter why not use a "bed" format and "annotation" track?

**Comment by WesleyvanLee** [comment]
The bed format for the annotation track is a good solution for me, my only question is why am i required to add an index file along with my .bed or .gff file?

**Comment by jrobinso** [comment]
You are not required to index the file, it is optional.  If the file is
very large you might run out of memory or suffer poor performance without
an index.

What led you to think an index is required?

**Comment by WesleyvanLee** [comment]
I tried to load an file via URL in the browser (.bed), but apparently these require an index file. When i looked through older issues and researched the code i figured that you don't need the index file if you load a local file. 

Thanks a lot for you time!

**Comment by jrobinso** [comment]
Hi, just for clarification bed files do not require an index file, ever, whether local or remote.   All files are loaded by URL,  we do not have "local file" support yet.   A url such as  "foo.bed" is still a URL, it is just relative to the page that loaded.  

See the documentation for more detaills on track configuration.
