### ISSUE TITLE
Browser freezes while loading coverage from a bam file

### ISSUE THREAD

**Issue by cromozome** [igvteam/igv.js#298]
Hello!

i am newbie to igv js
I am trying to load coverage across regions in a kb range genome using a bam/bai file
here is my track configuration
-------------------------------------------------------------------------

    var div = document.getElementById('igvDiv');
    var options = {

        reference: {
            id: "Polio",
            fastaURL: "polio-genome-reference.fasta"
            
        },
        tracks: [
            {
                name: "Polio genome coverage",
                type: "alignment",
                sourceType: "file",
                url: "polio-sample-sorted.bam",
                samplingWindowSize: 100,
                samplingDepth: 50,
                indexURL:  "polio-sample-sorted.bam.bai",
            }
        ]

    };
    var browser = igv.createBrowser(div, options);

-------------------------------------------------------------------------

when i try to load the above page, the page loads the reference genome but crashes after 30 secs, trying to load the coverage. Any pointers on what I might be missing or what could be going wrong ?

**Comment by jrobinso** [comment]
Hi,  I don't see anything obviously wrong.  Are there any messages in the
console (use developer tools to see console)?   Could you make the bam and
fasta available to us for testing?

BTW you aren't loading coverage here but the alignments.  If you're only
interested in coverage a "wig" or "bigWig" file would be more efficient.

**Comment by cromozome** [comment]
Thanks for the prompt response!
I am looking for the alignments, worded it incorrectly.
A vcf track generated from the same dataset loads up beautifully.
i am using apache tomcat as the webserver and currently testing this at localhost:8080
I have uploaded the fasta and bam to:
https://www.dropbox.com/s/8gy8qq7mjppio6e/TestigvFiles.gz?dl=0

**Comment by jrobinso** [comment]
Does Tomcat support Range-byte requests?   I'm not sure it does,  maybe
there is a configuration switch.  Look at the console for error messages.
Server requirements are documented here, you can ignore the "CORS' sections
if your web page and data are served from the same host:
https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements

I will check the bam later but I suspect it is the lack of support for
range-byte headers.  The console should have error messages to this effect.

**Comment by cromozome** [comment]
Thanks, I will check if my tomcat is supporting the range-byte requests. (if this was an issue, I am suspecting I should have problem with the vcf too..which I did not).
The console does not show any error, and the in-progress circle/hourglass keeps going till the page crashes.

**Comment by jrobinso** [comment]
OK,  Tomcat should support this unless its an old version.  I'll try to recreate the error hear, might be this evening before I get to it.

**Comment by jrobinso** [comment]
RE VCF, is it indexed (either .idx or tabix)?  If its not,  igv.js will load the entire file and range headers are not involved.

**Comment by jrobinso** [comment]
Hi, I can reproduce this problem with an Apache (not tomcat) server so its
not a server problem.   Still looking into it.  On IGV desktop this data
looks like this,  note all the mismatched bases (bases with color).  Is
this the sort of picture you expect, when its working properly that is?


​

**Comment by jrobinso** [comment]
I've isolated the problem somewhat.  It is the depth that is causing
issues,  possibly memory but I haven't confirmed that definitively.
Downsampling should protect from memory problems, but perhaps there is a
leak.   I was able to load portions of the file by restricting the window
to 1kb  (visibilityWindow: 1000).    So bottom line,  this will take some
time to track down,  and my holiday starts soon,  but it is high priority
and will get fixed.

On Wed, Dec 21, 2016 at 9:56 PM, James Robinson <jrobinso@broadinstitute.org

**Comment by jrobinso** [comment]
Bingo,  forget all previous theories I espoused.  It was simple.  We were not treating unmapped bam records properly,  this was causing an infinite loop.   Unmapped records are at the end of the file.  Your file is small,  so there is only a single indexed chunk which includes the unmapped records.   The problem hasn't arisen before because we don't typically query for a chunk at the end, although this could happen with any bam file.   I just pushed the fix.   Are you pulling from git or running from one of our releases?

**Comment by cromozome** [comment]
Thanks Jim for looking into this and for the fix!
I was running from your latest release, but this is not super urgent and I am just testing things around for project, I can use from git as well for now.

**Comment by jrobinso** [comment]
The fix should be in the beta build (its built nightly),  and I am going to
do a point release for this (1.0.6) because its a rather serious bug when
you hit it.

**Comment by jrobinso** [comment]
This is now fixed in 1.0.6  https://igv.org/web/release/1.0.6

**Comment by cromozome** [comment]
Thanks! its loading beautifully now!
