### ISSUE TITLE
b37 genome wrongly display MT sequence

### ISSUE THREAD

**Issue by reshetovdenis** [igvteam/igv.js#299]
I'm trying to display a genome data aligned to 1kg reference (b37), but IGV displays it as hg19 - with hg19 MT sequence that is not applicable to b37. Is it option to fix it? Also what is the best gene track for b37 like refGene.hg19.bed.gz? Thank you in advance.
Here is my code:
function showAlignment() {
        var div = $("#igvDiv")[0],
                options = {
                    showNavigation: true,
                    showRuler: true,
                    genome: "b37",
                    locus: "chr8:128,747,267-128,754,546",
                    tracks: [
                        {
                            name: "Genes",
                            type: "annotation",
                            format: "bed",
                            sourceType: "file",
                            url: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz",
                            indexURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz.tbi",
                            order: Number.MAX_VALUE,
                            visibilityWindow: 300000000,
                            displayMode: "EXPANDED"
                        }
                    ]
                };
        igv.createBrowser(div, options);
    };

**Comment by reshetovdenis** [comment]
![2016-12-29_13-42-37](https://cloud.githubusercontent.com/assets/24824905/21542131/b558f330-cdcc-11e6-822a-582b0294fadc.png)

**Comment by jrobinso** [comment]
For the human genome "hg19" is a synonym for the b37 sequence.   The
mitochondria, as you know, is a separate organelle, and there are several
sequences available for it.  To use a specific sequence you could host your
own fasta as described in the documentation, rather than use ours with the
"b37" shortcut.

What is the length of the mt sequence you aligned this bam file to?

WRT the gene annotation the file you reference is fine.

**Comment by reshetovdenis** [comment]
Jim, thank you for fast response. I used to think that hg19 and b37 refers to set of fasta sequences including mitochondria. hg19 traces to UCSC and b37 (= grch37) to Ensembl.
IGV standalone version displays b37 as it should be with MT from Ensembl. The problem is withing IGV.js. b37 could not be used as complete synonym of hg19. As well as gene sets for MT should be different. Please help, I would not like to host my own version of genome and annotation for such task.

**Comment by jrobinso** [comment]
OK,  I will see what IGV does and make igv.js do the same.  It might take a
week, I am traveling.  WRT gene sets you can load those as tracks,  or
point me to the best gene set for Enesmble /MT.

**Comment by reshetovdenis** [comment]
Jim, thank you so much. It would be great if igv.js could load the same gene track as IGV for b37. Nice trip!

**Comment by jrobinso** [comment]
For the b37 reference try the following reference object, do not use the
"genomeID" shortcut.   This is the 1KG project b37 reference.

reference: {
    id: "b37",
    fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/1kg_v37/human_g1k_v37_decoy.fasta",
    cytobandURL:
"https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/b37/b37_cytoband.txt"
}

The gene track used in IGV is the same one you referenced earlier (copied
below),  the UCSC refGene track.  If you have another annotation file you
prefer send me a pointer to it, in bed or gff format,  and I will put it on
our server and send you the URL.


{
name: "Genes",
type: "annotation",
format: "bed",
sourceType: "file",
url: "https://s3.amazonaws.com/igv.broadinstitute.org/
annotations/hg19/genes/refGene.hg19.bed.gz",
indexURL: "https://s3.amazonaws.com/igv.broadinstitute.org/
annotations/hg19/genes/refGene.hg19.bed.gz.tbi",
order: Number.MAX_VALUE,
visibilityWindow: 300000000,
displayMode: "EXPANDED"
}
