### ISSUE TITLE
igv.js in a simple require.js app

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#300]
In preparation for writing Jupyter notebook "multi-widget", in which cytoscape.js, igv.js, a heatmap and a data table each appear in  separate jQuery tabs in a single (combined) notebook extension, I am learning the ropes by creating minimal index.html/app.js files for each of the contained widgets.  cytoscape.js works fine with require.js, but I have some trouble with igv.js.   It seems to be similar to the problem reported in [this issue from May 24th 2016](https://github.com/igvteam/igv.js/issues/195), which turned out to be caused by loading multiple versions of jQuery.  

require.js seems to be quite fussy about jQuery.  Before I dig into that I thought perchance the igv team has already encountered (and solved) this.   Perhaps so?  I would be glad to submit a minimal pair of files to demonstrate the problem.

**Comment by jrobinso** [comment]
Hi Paul,

We haven't solve this, but would like to work nice with require.js.
JQuery versions are a pain.   If you could submit a minimal test case to
illustrate the problem that would be helpful.

**Comment by paul-shannon** [comment]
Hi Jim,

In the zip file: two small files (index.html and app.js) to demonstrate the problem, plus the latest minified require.js and an idiosyncratic (it seems) version of jquery which require.js needs.

Many thanks!

[igv-require-demo.zip](https://github.com/igvteam/igv.js/files/684898/igv-require-demo.zip)
![screenshot](https://cloud.githubusercontent.com/assets/2480712/21645877/b3eac93a-d248-11e6-8d58-63099b22c948.png)

**Comment by turner** [comment]
Paul,
I have a working version based on your starting point. The solution was to tweek the require config object:
[dat-igv-require-demo.zip](https://github.com/igvteam/igv.js/files/687804/dat-igv-require-demo.zip)

**Comment by paul-shannon** [comment]
Hi Douglass,

I never ceased to be amazed at how helpful you and your team are.  Thank you!

Your modifications to my little demo work perfectly.  The shim configure option now makes sense to me.

Maybe you will have some quick advice on the odd (and somewhat familiar - I think I have seen this before) half-way rendering I get when I move the new code to my multi-widget devel notebook.  Perhaps the NaN in the genome region end position reveals to you what might have gone awry?  (Note, however, that the same code works great in the the shimmed demo you sent this morning).

Thanks again!

 - Paul

**Comment by paul-shannon** [comment]
In case it is helpful, and if you have the time, here is the all-in-one jupyter notebook I use to explore jQuery tabs, cytoscape and igv.  It produces the genome end position NaN problem I mentioned last night.  It should run without any additional setup.

 - Paul

**Comment by paul-shannon** [comment]
Admitting the obvious:  the code in the all-in-one jupyter notebook is a dreadful hack, hastily assembled.  As I get the pieces working in some minimal fashion, I will refactor that notebook, then create a proper nbextension - to include interoperable tabs for  cyjs, igv, an interactive heat map (maybe clustergrammer), and some d3 and three.js visualizations.   Please pardon the dreadful hack which the code is now!

 - Paul

**Comment by turner** [comment]
Paul,
I don't see the code. Did you forget to attach it to your issue?

**Comment by paul-shannon** [comment]
Here it is, zipped up.  I think github did not recognize the file type.  

[notebook.zip](https://github.com/igvteam/igv.js/files/690552/notebook.zip)

**Comment by turner** [comment]
Paul,
I am running the notebook. I don't see the multiple tabs. How do I make that happen.

**Comment by paul-shannon** [comment]
Hi Douglass,

Executing the cells one at a time, reaching this point, the display(app) function call ought to do it.

But I imagine you already tried that.  Does the javascript console show anything?

 - Paul

**Comment by turner** [comment]
All I am seeing is each cell executing. I see a cell with the tab markup. Is it supposed to present the tabs?

**Comment by paul-shannon** [comment]
This block, at the end of the render function, makes the jQuery tabs function call, and the jQuery css magic creates the tabs according to the divs added, at the start of the render function, by the call to this.createMasterTabsDiv();

            setTimeout(function(){
               console.log("about to call tabs()");
               $("#masterTabsDiv").tabs();
               $("#cyDiv").cytoscape({elements:{nodes:[{data:{id:'a'}}], edges:[{data:{source:'a', target:'a'}}]}});
               window.browser = igv.createBrowser($("#igvDiv"), igvOptions);
               }, 0);
            },

Do you see “about to call tabs()” in the console?  This works in both chrome and firefox for me. 

You are very generous with your time.  I feel badly that I am using so much of it.   I will use any strategy you suggest to make my code easy|possible for you to run.

Perhaps you could seen me a screenshot of the tab markup you see?

 - Paul

**Comment by paul-shannon** [comment]
One minor long-shot possibility - which you almost certainly would have caught, but sometimes surprises me - is that a random cell will intermittently change its status from “code” to “markdown”, requiring me to manually make it right.

**Comment by paul-shannon** [comment]
Here is a minimal notebook using jQuery tabs in a jupyter widget which might be helpful if, as you wrote yesterday, the jQuery tabs() function is not working in the cytoscape/igv notebook.  Thanks again for all of your help as I try to get the multi-widget working.

[tab-minimal-demo-notebook.zip](https://github.com/igvteam/igv.js/files/691597/tab-minimal-demo-notebook.zip)

**Comment by turner** [comment]
Paul,

Here is a igv running in tabs: [dugla-tabs.ipynb.zip](https://github.com/igvteam/igv.js/files/697182/dugla-tabs.ipynb.zip)

I had to remove the cytoscape tab and functionality make it kinda worked. I then added the igv.css to make it work properly.

Not sure what is up with cytoscape but that is where the issue lies.

**Comment by paul-shannon** [comment]
Douglass,

Your notebook works perfectly.  Thank you for finding the time, for figuring it out.
I may have additional related questions for you, but let's close this issue for now.
I am, in tiny incremental steps, creating tabbed (single tab) requirejs apps out of igv, cytoscape, leaflet and Three.js.  Once I get all those and their shims working separately, I will experiment with two-tab apps and their shims.  All of this is, at first,  just plain javascript running in the browser.    

I hope that once the pure no-notebook versions of these multi-tab widgets work that then there will not be too many surprises as I put them into a notebook, and then into an nbextension.

Thanks again for your skillful and patient help.

 - Paul

**Comment by paul-shannon** [comment]
Hi Douglass,

I may have a bug (or feature request) for you.   I made a tiny change to your notebook, placing igv in the second tab rather than the first.  No cytoscape involved.  The original problem (NaN, no loading of tracks) surfaces, as seen here:

![screen shot 2017-01-12 at 4 35 13 pm](https://cloud.githubusercontent.com/assets/2480712/21913997/25e4d646-d8e5-11e6-8298-19560a145fee.png)

I see the same general phenomenon with cytoscape (I will test three.js and leaflet next), and it seems to be related to this stackoverflow [discussion](http://stackoverflow.com/questions/25916735/using-cytoscape-rendering-inside-twitter-boostrap-tabs).  A simple `cy.resize()` on the tab activate event solves the problem for cytoscape.  The hidden tab div in which the cy or igv widget renders seems to be the problem.

Here is the slightly modified notebook, along with a pure js/html two-file version, which might be easier to work with:
[dugla-tabs-igvInTab3.zip](https://github.com/igvteam/igv.js/files/703287/dugla-tabs-igvInTab3.zip)

I will, as always, be grateful for any help you can supply.

Cheers!

 - Paul

**Comment by turner** [comment]
I am looking at this now.

**Comment by turner** [comment]
Paul,

I looked into this issue and here's what I suspect is happening: When you create the TabsView object you create a set of functions initialize, render, etc. and I think its launching the igv app (which programmatically constructs DOM elements and objects) before the parent DOM container is fully in place. Perhaps there something you can do in the initialization code to prevent igv from being launched too early?

**Comment by paul-shannon** [comment]
Hi Douglass,

If I setTimeout(function(){ <initialize tabs here>}, 5000) igv is able to render itself into a regular (non-tabs) div, and then remains intact after the tabs are created.  That is adequate, but somewhat ad hoc since the time to load, configure and display igv depends on many somewhat unpredictable factors.

A little more reliable would be (forgive me if this is greedy, or wrong-headed) if igv.js had a ready event or function call in which I could place the tabs() call.  FWIW, cytoscape.js has such a [capability](http://js.cytoscape.org/#cy.ready), providing clients with a place to call post-network-rendering code.

 - Paul

**Comment by jrobinso** [comment]
Paul,  I'm a bit confused,  igv.js is ready immediately,  its the div it is
being inserted into that is not ready.   Maybe I'm missing something, could
you show us some code or psuedo code as to how it would be used?   I agree
we need a better solution but I don't see how a "ready" function helps.

**Comment by paul-shannon** [comment]
Hi Jim,

I think (and may be wrong) that the div igv.js is inserted into -is- ready, but hidden.

jQuery-ui tabs() hides all divs but the first one.   If igv.js is in the top div, then igv remains visible (as the default currently selected tab), and nicely continues to fetch data and render itself, often for 10 or more seconds, and then remains intact through any subsequent tab raising, tab lowering.  

I feel some trepidation here - that I have been unclear, wooden-headed, worn out my welcome, or worse :}

For what it’s worth, I have experimented with cytoscape.js, leaflet.js and three.js.  They all work fine when rendering into hidden tabbed divs.  In some circumstances, in the past (earlier versions of cy.js) we needed to trigger a redraw when raising the cyjs tab to the front.  But it (and the others) complete their rendering  to a hidden div.  igv.js seems to hang when hidden.

I tried to boil this down to the simplest non-notebook form, in dugla-tabs-igvInTab3.zip, from 9 days ago.  There is a minimal igv.html file (using requirejs) with some simple javascript in igvTab.js.

I would be glad to simplify that further, removing requirejs, sending just on html file.

Thanks to both you and Douglass for your patience!

 - Paul

**Comment by paul-shannon** [comment]
Here - if you have time for it - is a minimal single html file combining igv.js with jQuery tabs.
All of the javascript runs in the document ready function, so the page DOM is ostensibly complete.
The final three lines are currently:

        browser = igv.createBrowser(igvDiv, options);
        //$("#tabs").tabs();       
        //setTimeout(function() {$("#tabs").tabs()}, 1000);

*  In this code fragment, and in the attached index.html, two ways to call the tabs function are disabled,  no tabs are used, and igv renders fine.
*  enable the first form of the tabs() call, and if the igvDiv is the <b>front</b> div, then igv renders fine.
* If the igvDiv is the <b>second</b> div, then igv renders incompletely, reports a failure.
*  If the setTimeout line is enabled, and if the igvDiv is first or second (visible or hidden) then igv has the chance to render <b>before</b> the tabs function is called, and everything works fine.  From this I conclude that igv is not happy rendering to a hidden div...

Because all of the javascript runs in the document ready function, and because of that quirky NaN that appears in case 3, for the terminal position of the locus - and maybe because of wishful thinking on my part - I think that perhaps this is aspect of igv which could maybe be remedied.


[igvInJQueryTabs.zip](https://github.com/igvteam/igv.js/files/724670/igvInJQueryTabs.zip)

**Comment by turner** [comment]
Paul,

This is an example of igv.js working in a hidden tab:
[dugla-tabs-bug-fix.ipynb.zip](https://github.com/igvteam/igv.js/files/727770/dugla-tabs-bug-fix.ipynb.zip)

jQuery tabs have a configuration object that includes a callback for when a tab becomes active. I use this callback to delay creation of igv.js until the parent tab is active.

**Comment by paul-shannon** [comment]
Nice solution, Douglass.  Thanks!

  - Paul

**Comment by turner** [comment]
Great. I will go ahead and close this thread
