### ISSUE TITLE
hg19 and hg38 versions produce similar visuals

### ISSUE THREAD

**Issue by gaitat** [igvteam/igv.js#301]
I am using the following two reference objects in two separate html files.

`	reference: {
		cytobandURL: "annotations/hg19/cytobands/cytoBand_processed.txt"
	},`

head of hg19 cytobands file: 
`1       0       2300000 p36.33  gneg`
`1       2300000 5400000 p36.32  gpos25`
`1       5400000 7200000 p36.31  gneg`
`1       7200000 9200000 p36.23  gpos25`
`1       9200000 12700000        p36.22  gneg`
`1       12700000        16200000        p36.21  gpos50`
`1       16200000        20400000        p36.13  gneg`
`1       20400000        23900000        p36.12  gpos25`
`1       23900000        28000000        p36.11  gneg`
`1       28000000        30200000        p35.3   gpos25`

and

`	reference: {
		cytobandURL: "annotations/hg38/cytobands/cytoBand_processed.txt"
	},`

head of hg38 cytobands file: 
`1       0       2300000 p36.33  gneg`
`1       2300000 5300000 p36.32  gpos25`
`1       5300000 7100000 p36.31  gneg`
`1       7100000 9100000 p36.23  gpos25`
`1       9100000 12500000        p36.22  gneg`
`1       12500000        15900000        p36.21  gpos50`
`1       15900000        20100000        p36.13  gneg`
`1       20100000        23600000        p36.12  gpos25`
`1       23600000        27600000        p36.11  gneg`
`1       27600000        29900000        p35.3   gpos25`

I am not specifying any other keys to the reference object because it does not seem to make a difference.
The two cytoband files are different yet the visual result that I get when I call `igv.createBrowser()` is the same.
What am I doing wrong?

**Comment by gaitat** [comment]
Thank you for the quick response. I was doing that and had also used `showKaryo: true` and for the human cytobands I was expecting to see some differences at least some popping of the cytoband colors but I could not spot any. Maybe the differences are smaller than the pixel resolution used but what other way could I use to verify that the files are actually being used? So now I went in the hg38 cytobands file and totally mutilated the cytobands of the Y chrom leaving only the first and the last cytobands like so:
`Y   0   300000  p11.32  gneg`
`Y   300000  57227415    q12 gvar`
Still, there was no change in the visual. I can still see the bands on Y.
![y](https://cloud.githubusercontent.com/assets/3304370/21707495/4ab741ac-d395-11e6-96dd-74a970928345.PNG)
The only difference I could see was that in your cytobands file the chroms are listed in numerical ascending order (i.e. 1, 2, 3, ..., 10, 11, 12, ..., 19, 20, 21, 22) while in mine they are listed sorted lexicographically (i.e. 1, 10, 11, 12, ..., 19, 2, 20, 21, 22). Could that be an issue?

**Comment by jrobinso** [comment]
Please post your complete config object.

**Comment by gaitat** [comment]
```
var options = {
	showNavigation: true,
	showRuler: true,
	showKaryo: true,
	genome: "hg38",
	locus: "chr1",
	reference: {
		fastaURL: "data/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa",
		indexURL: "data/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa.fai",
		cytobandURL: "annotations/hg38/cytobands/cytoBand_processed.txt"
	}
};
```

**Comment by jrobinso** [comment]
You can't specify both "genome" and "reference", they are mutually
exclusive.  Actually "genome" is deprecated, the proper way to do this is
to set the id field in the reference.  So delete "genome" .   You don't
actually have to specify the id as you are providing a URL to the fasta.

I assume you've seen the doc,  https://github.com/igvteam/igv.js/wiki/  its
best to stick with the options enumerated there.
