### ISSUE TITLE
"chr" prefix on reference files

### ISSUE THREAD

**Issue by gaitat** [igvteam/igv.js#302]
I have noticed that all of the reference files do not contain the "chr" prefix in the chromosome column, both in the `cytobandURL` and the `fastaURL`. Is there an option for this or do we have to convert all of our files to this scheme? 
In addition bed files and bam files that contain the "chr" prefix work fine.

**Comment by jrobinso** [comment]
There is no required chromosome naming convention,  you can use 1 or chr1
or anything else.   I guess I don't understand the question or issue.

**Comment by gaitat** [comment]
Let me use an example for cytobands which is easier.
I am using this object:
```
var options = {
	showNavigation: true,
	showRuler: true,
	showKaryo: true,
	locus: "chr8:128,750,000-128,755,000",
	reference: {
		id: "hg19",
		fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/1kg_v37/human_g1k_v37_decoy.fasta",
		cytobandURL: "annotations/hg19/cytobands/cytoBand_processed.txt",
	},
};
```
and when `cytoBand_processed.txt` contains data of the format:
```
1       0       2300000 p36.33  gneg
1       2300000 5400000 p36.32  gpos25
1       5400000 7200000 p36.31  gneg
1       7200000 9200000 p36.23  gpos25
1       9200000 12700000        p36.22  gneg
1       12700000        16200000        p36.21  gpos50
1       16200000        20400000        p36.13  gneg
1       20400000        23900000        p36.12  gpos25
1       23900000        28000000        p36.11  gneg
1       28000000        30200000        p35.3   gpos25
```
everything works fine. But if I swap that out with a cytobands file of the format"
```
chr1    0       2300000 p36.33  gneg
chr1    2300000 5400000 p36.32  gpos25
chr1    5400000 7200000 p36.31  gneg
chr1    7200000 9200000 p36.23  gpos25
chr1    9200000 12700000        p36.22  gneg
chr1    12700000        16200000        p36.21  gpos50
chr1    16200000        20400000        p36.13  gneg
chr1    20400000        23900000        p36.12  gpos25
chr1    23900000        28000000        p36.11  gneg
chr1    28000000        30200000        p35.3   gpos25
```
then I get "TypeError: Cannot read property "length" of undefined" as a popup dialog and on the Chrome debugger I get:
```
TypeError: Cannot read property 'length' of undefined
    at igv.KaryoPanel.repaint (igv.js:16530)
    at igv.KaryoPanel.resize (igv.js:16490)
    at igv.js:14467
```
where line 16530 is
```
        var maxLen = cytobands[cytobands.length - 1].end;
```

**Comment by jrobinso** [comment]
The names of chromosomes should match between the cytoband and fasta file.
  I'm not sure if that's the problem here but it likely is.   I will look
into it.

**Comment by gaitat** [comment]
That was one combination of files that I did not try. Thank you.

**Comment by jrobinso** [comment]
In general you can use chr1 and 1 interchangeably in track files,  but the
internal reference is defined by the fasta.   I suspect the chr1 - 1
aliasing is not working for the cytoband.  Just a theory at this point.

What are you trying to achieve?

**Comment by gaitat** [comment]
At this point I am just trying to verify that our data goes into igv and that igv does not have any default settings that would override my files. As I was not seeing differences (as I mentioned yesterday) I got concerned but both posts cleared things up for me. Thank you for your quick response.

**Comment by jrobinso** [comment]
The only default settings are for the (deprecated) genome attribute.   This
attribute let you supply one of a few recognized UCSC genome IDs,  and the
fasta & cytoband (if any) would be loaded from our server.   That has been
replaced with the "reference" object.   You can still use our defaults by
supplying only an "id" parameter in the reference object.

The other built-in default is an alias table between "chr1" and "1" naming
conventions.   This is to allow annotation and track files to use both
conventions.   However this alias is apparently not working for the
cytoband file, per your report.

I will search for use of "genome" in our example files and remove it match
our documentation.
