### ISSUE TITLE
Reads displayed in bam track are random

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#306]
Hi,
currently if we load same bam twice in igv js then it shows different reads at same location.
whats the impact of setting 'samplingWindowSize'=0 ?

**Comment by amolpshinde07** [comment]
@jrobinso Can you please help me out?

**Comment by jrobinso** [comment]
I don't understand what you are saying, maybe a screenshot would help.   The vertical location of a specific alignment is not guaranteed,  it can vary based on how the alignments are packed.   Further, if coverage is very deep alignments can be downsampled.    I don't know what the effect of setting sampling window size to zero is,  if you want to  minimize sampling set the samplingDepth to max number.  Beware this might cause the browser to freeze.

Could you attach a screenshot illustrating your problem?
