### ISSUE TITLE
Track viewDisplayMode options no longer in gear-menuitems

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#308]
It looks like a simple bug.

Line 280 of featureTrack.js
`menuItems.concat(mapped);`

should instead be
`menuItems=menuItems.concat(mapped);`

Loving all of the new updates - looking forward to using the genome-wide view for moderately-sized BED files.

**Comment by turner** [comment]
Good catch Bryan. Closed with commit e8d65295
