### ISSUE TITLE
spilt view in igv js as in IGV desktop

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#309]
How to use split view to view multiple position in same view as implemented in IGV desktop?

**Comment by amolpshinde07** [comment]
@jrobinso Can you please help me out?

**Comment by jrobinso** [comment]
Could you please describe in more detail what it is exactly you want to do?
  This makes it easier for us to help you.   Not all features in desktop
are supported in igv.js

**Comment by amolpshinde07** [comment]
@jrobinso  please check attached screenshot from igv desktop
![Split View](https://cloud.githubusercontent.com/assets/17845118/22823453/baad1d62-efa9-11e6-8a8a-36456b806d72.png)

**Comment by jrobinso** [comment]
This feature is not released yet,  but if you are building from source you
can do this by specfiying multiple loci in the configuration like this

locus: [ '8:124,512,907-124,512,945', '8:60,512,907-60,512,945' ]

You can also type multiple loci in the search box separated by a space

**Comment by amolpshinde07** [comment]
@jrobinso  Thanks for help.
When will be next release of igv.js?
