### ISSUE TITLE
Support reading local files

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#311]
Add support for reading non-indexed local files.

**Comment by xtmgah** [comment]
I am asking the same question.how do i include the "BAM file path" in the html  file?

**Comment by turner** [comment]
I am looking at this now.

**Comment by jrobinso** [comment]
I think @xtmgah was asking how to include a path in the configuration object.  This is not possible of course and not something that can be supported on a web page.

**Comment by matthdsm** [comment]
Seconded, I'd like to be able to add a path on the server instead of an URL as file location for BAM files.
Is that a possibility?

**Comment by jrobinso** [comment]
No, its not possible,  browser security rules would not allow it.   You can use a relative URL  (i.e. like  "../datafolder/file.bam"  if your data is hosted no the same server as your web page, but that is still a URL.     This ticket is about using a "Load" button from the web page for a user to browse to a file,  not using paths in configuration objects.

**Comment by turner** [comment]
Closed with commit dd0e7a24. Implemented drag & drop widget to support local file  loading and URL loading.

**Comment by keqiang** [comment]
@turner Hi, I'm reading your last comment and wondering how to enable the drag & drop. Any example? Thanks!

**Comment by turner** [comment]
Hi @keqiang i'll put together a screen shot. hang on.

**Comment by turner** [comment]
@keqiang in the config add this option `showLoadFileWidget: true`

Here is a screencast of how to use it:
https://drive.google.com/open?id=1aCUPXx0Dwg0A38_xe-pRZJ0U6oBS7Jqz

**Comment by keqiang** [comment]
@turner Thanks! I will give it a go!

**Comment by keqiang** [comment]
Hi @turner , I managed to make the 'Load Track' button show using the dev version. However, the files I used didn't work(the page just freeze or break). Two questions: Is there a file size limit? What file format should I use? I saw you used .bed file. I also tried uploading bam and bai. If I drag only one file each time, the UI says it needs the other file. When I drag both at the same time, it does nothing. I've rather large bam files(> 1G) together with bai, is it still possible for me to use it?

Appreciate your help.

**Comment by turner** [comment]
@keqiang I fixed a bug that occurred when loading local indexed files  - so, bed and bam. Do a pull.

Loading a local file that is indexed requires you to select and drag/drop both the file and its index.

For a remote (URL) file the interfaces walks you through loading the file then the index.

Let me know if this works.

**Comment by keqiang** [comment]
@turner I'm sorry I have a silly question... How can I get igv.js from source? I'm currently using the nightly build which is dated back in Jan.

**Comment by jrobinso** [comment]
@keqiang I would point you to our github repository but you are posting on it.   Just clone the repository.

**Comment by keqiang** [comment]
@jrobinso I have searched in the repo and found no igv.js or any compiled igv js library. Even the examples don't include the igv.js in the header and if I save the examples locally they would not run.

**Comment by jrobinso** [comment]
You asked about the source,  the distributions are available here:
http://igv.org/web/release/   and here:  http://igv.org/web/beta/.      If
you want the absolute latest you will need to pull and build with grunt.

This directory is built nightly, sometimes more frequently:
http://igv.org/web/test/dist/.

**Comment by keqiang** [comment]
@jrobinso Yes, exactly. I think it would be better if your repo contains instruction on how to build from source. And the link to the wiki saying Night build is actually the beta version, maybe you want to change that to avoid misleading as well.

**Comment by jrobinso** [comment]
Good points, most people just pull and build with grunt,  this is the first
request but it is a fair point.    Will add a "readme" to the repo and
update the wiki.

**Comment by matthdsm** [comment]
Hi @turner, @jrobinso 

Nice addition! Seems to work beautifully. Some further questions on this:
* Can the same result be achieved using some sort of API call? I'm building a web page using IGV.js, and I've already got several UI elements calling the API.
* On the same note, is it possible to remove the button from the browser itself? Ideally, I'd like to move as much of the buttons in the top bar to other UI elements

**Comment by jrobinso** [comment]
>
>
>
>    - Can the same result be achieved using some sort of API call? I'm
>    building a web page using IGV.js, and I've already got several UI elements
>    calling the API.
>
> Not currently.  The API call would have to take a Blob as input,  you
cannot use or even know the actual file paths.


>
>    - On the same note, is it possible to remove the button from the
>    browser itself? Ideally, I'd like to move as much of the buttons in the top
>    bar to other UI elements
>
>
That could be supported when the API call is there.    Could you open a new
git issue for "API to load local files"?


>
>
>
>
