### ISSUE TITLE
only hosted genomes consulted when searching gene name from search box?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#312]
It appears (browser.js, line 129) that a search from the IGV search box results in a mostly hard-coded query back to 

    https://portals.broadinstitute.org/webservices/igv/locus?genome=" + genomeId + "&name=$FEATURE$",

The wiki [suggests](https://github.com/igvteam/igv.js/wiki/Browser) that only hg18 and hg19 are supported.  We use hg38 in our analyses.  Is there a way I can configure my own locus search, in another genome or annotation file?    

 - Palu

**Comment by jrobinso** [comment]
There are 2 ways you can support this.

(1) load a non-indexed annotation track (e.g. bed) and set the "searchable"
parameter to true (see https://github.com/igvteam/igv.js/wiki/Tracks)

(2) provide your own search webservice.   This is more complex,  see
"search object details" here:
https://github.com/igvteam/igv.js/wiki/Browser

You could also open a ticket for hg38 search support,  we should support
this but I can't promised when I would get to it.

**Comment by paul-shannon** [comment]
Strategy #1 worked great.  Thanks!  igv.js is a delight.
