### ISSUE TITLE
label individual isoforms

### ISSUE THREAD

**Issue by lfrohman** [igvteam/igv.js#313]
When a gene is displayed, the default label is "Gene" for the entire track. Is there a way to label the individual isoforms?

**Comment by jrobinso** [comment]
I'm not sure I understand the question.  Gene is the track name, but the
individual features are labeled.   To see all isoforms use the "gear" menu
to expand the track.   Or perhaps I'm not understanding the question,
could you post a screenshot?

**Comment by lfrohman** [comment]
something like:

![image](https://cloud.githubusercontent.com/assets/1037104/22224553/e51243be-e173-11e6-904e-aa6df8b07ea2.png)

**Comment by jrobinso** [comment]
Those isoform names should be under the isoforms (where ADAR is now).   Did
you get this with our default annotation?   We can't put them on the left
as you have them,  there's not limit no how many genes can be in view
horizontally.

**Comment by lfrohman** [comment]
I used the defaults for this, when I click expand on the gear, only the gene symbol shows underneath
the feature, not the isoform. I did not see anything in the documentation about that.

**Comment by jrobinso** [comment]
I'll look at the annotations.  There are no standards for labels in
annotation formats,   but I will see what can be done here.

**Comment by lfrohman** [comment]
Thanks, but please don't spend time on this, since our users may require the isoforms on the left
instead of below. Does the canvas that holds the features have any kind of callback where we could
get the y value of each feature?

**Comment by jrobinso** [comment]
No there is not, and that would be complex.  I suggest you nail down
requirements with your users then open a request, or update this one with
specifics.   As I pointed out earlier there is no control on the number of
features in view on a single horizontal row,  to which would a label apply?
  You probably want something like UCSC's "full" mode.   That we could add,
 have a look at it.

Also, there is no internal concept either in the code or annotation file
formats of an "isoform".   I know what you are referring to but to
implement something we will have to be more precise,  making reference to
fields in the various formats.   This will probably require some
configuration options on the track object.
