### ISSUE TITLE
Reading files hosted on same server

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#315]
Hi, 
I'm trying to read a bam file hosted on the same server as IGV.js, but I'm getting the following error:

```
ERROR: range-byte header was ignored for url: ../test.bam
```
Any idea what could be wrong? 
My track config looks as follows:
```
                    tracks: [
                      {
                        type: 'alignment',
                        sourceType: 'file',
                        indexURL: '../test.bam',
                        url: '../test.bam',
                        name: 'test'
                      }
                    ]
```

Thanks for the help!
M

**Comment by VivekTodur** [comment]
Hi,

Try adding this to  "AddType application/octet-stream .bam " in the httpd.conf file. Refer the issue #199 for more information.

**Comment by jrobinso** [comment]
Does your server support Range request headers?  That's a requirement.

**Comment by matthdsm** [comment]
Hi all, thanks for the replies!
I've added the "AddType application/octet-stream .bam" to my apache config, and the error message has gone away. However, there still aren't any reads shown. Any more ideas?
Thanks
M

**Comment by jrobinso** [comment]
Can you extract a small slice of you bam for us to test with?

**Comment by matthdsm** [comment]
another small oversight. Does igv.js support hg38? Since all the examples refer to hg19 and surrounding files.

**Comment by matthdsm** [comment]
My debug screen tells me there's a resource missing on igv.org
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (promise-7.0.4.js.map, line 0)
```

Could this cause the issue? I got it to succesfully load a vcf file+index, and the hg38 genome, but still no bam file.

M

**Comment by matthdsm** [comment]
Allrighty! I got it to work, turns out I just wasn't zoomed in enough.
Thanks for all the help!
M
