### ISSUE TITLE
String.prototype.contains() and String.prototype.splitLines() are enumerable

### ISSUE THREAD

**Issue by zarsky-broad** [igvteam/igv.js#316]
In `igv-exts.js`, there are a number of polyfills, but the only ones that take effect in a modern browser environment are `String.prototype.contains()` ([removed from the spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#String.prototype.contains)) and `String.prototype.splitLines()` (non-standard). When these are monkeypatched, they are added as enumerable properties of every `String`. This causes issues, as they appear with `for…in`, used for example in `jQuery.parse()`.

Two proposed solutions:
1. Remove these two shims. One isn't needed, and the other is a non-standard feature, and so shouldn't be modifying the prototype. (See warning [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf), but generally custom functions should either be on a new object type, or should be a function called on an object. The easiest solution might be to replace instances of `string.splitLines()` with `string.split(lineBreaks)`, with `lineBreaks` defined as `/\r\n|\n|\r/gm` in the app's global scope.)
2. Mark the properties as non-enumerable, like so:
    ```js
    if (typeof String.prototype.splitLines === "undefined") {
        Object.defineProperty(String.prototype, 'splitLines', {value: function() {
            return this.split(/\r\n|\n|\r/gm);
        }, enumerable: false, configurable: false})
    }
    ```

Thanks!

**Comment by jrobinso** [comment]
Thanks for the feedback.   I'm a bit of a javascript noob but learning.
I'll look into this and likely follow your first suggestion.  Extending
prototypes with non-standard features is a bad idea in any language.

I'm open to all such criticisms, btw, its very helpful.

**Comment by jrobinso** [comment]
All polyfills are gone
