### ISSUE TITLE
Large (10GB) bigwig + RangeError: Invalid array length (overlow?)

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#317]
Opening this as it's own ticket (coming from https://github.com/igvteam/igv.js/issues/186)

We are experiencing an issue with large bigwigs causing negative byte range requests (and ultimately throwing a RangeError: Invalid array length)

Flask + igv.js is working AOK for all other (small) bigWigs (mostly < 1GB).

When using large bigwigs, this error happens when serving the files through either the local flask proxy or through local-s3-compatible links... (Will try aws s3 next)

With a large bigWig (10GB) igv.js is requesting negative byte ranges, and ends up making thousands of range requests (searching for overlapping tree leafs?) and ultimately crashes.

The large 10GB bigwig loads in AOK to the desktop IGV, suggesting the bigwig is intact.

Here is a large bigwig to test with (via s3)
https://s3-us-west-2.amazonaws.com/ilmn.igv-test/test.bigWig

This should basically hang using any genomic interval (e.g. 19:49,284,301-49,322,005)
If you open the dev console you can see thousands of requests being made (ultimately a RangeError will be thrown).

**Comment by jrobinso** [comment]
Got it, thanks.  I suspect its an overflow on the index offsets, currently they are parsed as 32 bit ints because that's all javascript's DataView supports.   Will investigate but it might be a couple of days.

**Comment by jrobinso** [comment]
I just pushed a fix that works for your big bigwig.  Parsing longs in javascript is tricky, and it could still fail if the value is > 2^53-1.   However that's a very large number, and unlikely to be seen in any genomics file.  I'm not even sure a file of that size could exist on a physical file system.

There could still be downstream issues with numbers > a 32 bit integer being used where an integer is expected,  but I don't anticipate any issues with using these large numbers as file offsets.

**Comment by blajoie** [comment]
Great stuff Jim - Thanks.
Will test in the morning!

**Comment by jrobinso** [comment]
I didn't do thorough testing for sure.

**Comment by blajoie** [comment]
9 of the 11 tracks I was testing with now work.  The remaining 3 still throw an error.

Here is another bigWig that replicates the issue
https://s3-us-west-2.amazonaws.com/ilmn.igv-test/test2.bigWig

Zooming here should replicate the issue:
19:49,284,301-49,322,005

Note: This track does not load into igv desktop, but it query-able via bigWigSummary
(IGV ERROR : Error loading Y:\test2.bedgraph.bigWig: null)

bigWigSummary test2.bedgraph.bigWig chr19 49284301 49322005 1000

**Comment by jrobinso** [comment]
I fixed the issue with test2.bigWig, in both IGV and igv.js.   It was a similar issue,  in this case unsigned shorts were being parsed as shorts, and they were > the limit for a signed short so were overflowing.   They are now parsed as unsigned, and the types in Java changed to "int" to hold the large values.

**Comment by blajoie** [comment]
Everything seems to be working great now - thanks for the quick fix!

**Comment by jrobinso** [comment]
You've got some big files there.  One of the overflows was an item count in the leaf nodes,  normally a few hundred to few thousand but in your case enough to overflow a short.   Thanks for the test data,  nice to catch these edge cases.

**Comment by jrobinso** [comment]
@blajoie Could you send me any pointers on how you got igv.js Flask working, specifically content-range header support?   Thanks
