### ISSUE TITLE
ga4gh API versions

### ISSUE THREAD

**Issue by idelvall** [igvteam/igv.js#318]
Hello, 
what is latest version of the ga4gh API (https://github.com/ga4gh/schemas) supported by the viewer?

Thanks!

**Comment by jrobinso** [comment]
Should be "v1",  the endpoint used is https://genomics.googleapis.com/v1

**Comment by jrobinso** [comment]
I should add only variants and alignments are supported.    Other entities
will be supported if there is any demand.

**Comment by idelvall** [comment]
Thanks for the the response. 
It seems that the google "v1" adheres to the ga4gh API "v0.5.1" 
https://cloud.google.com/genomics/reference

**Comment by jrobinso** [comment]
Closing this as the GA4GH API has been deprecated.   pity.
