### ISSUE TITLE
add ability to highlight ROI (across all tracks)

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#319]
Before one of the fairly recent refactors, I had a simple working example where a user could supply a genomic interval and the browser would highlight said region across all tracks.
e.g.
[https://s3-us-west-2.amazonaws.com/ilmn.igv-test/highlight-igv.png](https://s3-us-west-2.amazonaws.com/ilmn.igv-test/highlight-igv.png)

Following the refactor, the existing highlight logic no longer transfers to the new code..

Any chance such a feature can be added?  Or is this already something on the backlog?

Thanks!

**Comment by jrobinso** [comment]
Hi, that's cool,  I assume you were overlaying this (i.e it wasn't internal
to IGV)?

Could you describe to us how you were doing this before?   I am guessing
the multi-locus implementation broke it, but am not sure.    Also, as an
igv.js feature how would you envision it working?

**Comment by blajoie** [comment]
Yes, it was a very simple css overlay.
Similar logic to how the sweeper (click-and-drag to zoom) worked, only extended through all vertical space.

This looks to be the old (initial) commit.
https://github.com/blajoie/igv.js/commit/479e4cfb7df9284dde8816bae2d5fdcb64c9714f

Ideally there would be a highlight search box (besides the main search box) where users can enter in either a gene or coordinate.  igv.js would then highlight the ROI across all tracks  (simple css overlay should suffice).  A (clear/reset) button could reside next to the highlight text box to clear/hide the highlight css.  Also - adding this as a browser level param, similar to locus, with listeners to repaint if the values ever change.
  
e.g.
    var options = {
                        locus: locus,
                        highlightLocus: highlightLocus: {
                        ....
                        },
               
It would also be useful if one could not only highlight a single ROI, but instead highlight a set of ROIs (configurable by either a provided list of genes/coordinates or a separate ROI bed track).  Though this could come later.

For the time being, our use-case is to highlight a ROI (variant) of interest and then center the browser around said variant for interpretation.

**Comment by jrobinso** [comment]
Hi, for the time being could this be a configuration or API option,  rather
than a user option with a UI for the region?   Features involving UI
widgets take much longer to design.

**Comment by blajoie** [comment]
config/api option would be AOK!

**Comment by oleraj** [comment]
We would be interested in this feature through a config/API option as well.  Is there any update/progress on this feature?  

Thanks!

**Comment by jrobinso** [comment]
Sorry no progress yet, but thanks for the reminder

**Comment by jrobinso** [comment]
To be clear we're talking about adding a list of ROIs, probably as a bed file,  and having them highlighted as in Bryan's original figure:  https://s3-us-west-2.amazonaws.com/ilmn.igv-test/highlight-igv.png.   I ask because this is somewhat different than IGV desktop's ROI.

**Comment by oleraj** [comment]
Thanks for clarifying.  The way you described it is just what we need.

**Comment by jrobinso** [comment]
Check out the latest commit, in particular the dev/roi.html example file.    You can use any supported feature file type to define the regions of interest

**Comment by turner** [comment]
Closed with commit d0bd4362

**Comment by jrobinso** [comment]
Yes,  there is no documentation but there isn't much to document either.  See http://igv.org/web/test/examples/roi.html.

I will reopen this issue until its documented.  Here is the important bit from the example

```
            // Define 2 "region of interest" sets
            roi: [
                {
                    name: 'ROI set 1',
                    url: '../test/data/bed/roi_bed_1.bed',
                    indexed: false,
                    color: "rgba(68, 134, 247, 0.25)"
                },
                {
                    name: 'ROI set 2',
                    url: '../test/data/bed/roi_bed_2.bed',
                    indexed: false,
                    color: "rgba(0, 150, 50, 0.25)"
                }
```

**Comment by yarongolan** [comment]
On v2.0.1 I'm getting "ERROR DRAWING REGIONS OF INTEREST" (roi.draw is not a function)

**Comment by jrobinso** [comment]
This looks like a regression.   Looking into it.

**Comment by fany3** [comment]
This ROI is across all tracks. Could you highlight ROI across one single track associated with it? 
Thanks!

**Comment by jrobinso** [comment]
@fany3 this issue did not get updated, but yes you can highlight ROI across a single track.  Just embed it in the track config.
