### ISSUE TITLE
bed-like track for displaying SNPs, 5 categories, 5 colors?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#326]
Can you suggest an igv.js track which permits coloring of each block (each a 1-base SNP) by category?   I use FIMO from the MEME suite to predict TF-binding motif changes:

  * gain of motif
  * loss
  * lossAndGain
  * noChange
  * noMotif

Colors might be green, red, magenta, grey, black

Thanks!

**Comment by jrobinso** [comment]
Well, you can use a bed track and explicitly set the color,  or gff (set it
with an attribute in column 9).   However there is no built-in color scale
for this.

It might be useful to create such a capability.   What format is this data
in,  and can you share an example file?

**Comment by paul-shannon** [comment]
The simplest form:

chr5 88469841 88469841     noMotif
chr5 88689478 88689478        loss
chr5 88697548 88697548        gain
chr5 88701462 88701462    noChange
chr5 88704819 88704819 lossAndGain

somewhat richer:

chr5 88469841 88469841 rs9293499 1.757459     noMotif
chr5 88689478 88689478   rs26579 1.853562        loss
chr5 88697548 88697548   rs34338 1.873869        gain
chr5 88701462 88701462   rs27721 1.589391    noChange
chr5 88704819 88704819  rs254781 1.538501 lossAndGain

I may be missing some obvious solutions.

Thanks, Jim.

 - Paul

**Comment by jrobinso** [comment]
I assume you got the examples directly from a tool?   It would be really
great if tool developers could use standard formats when possible,  the
first is almost but not quite a "bed" file.   It uses '1" based coordinates
so is not legal bed.

To avoid proliferation of formats and file extensions  I started a
custom-format capability in igv.js. It's not quite ready but I will take
these examples into account.   In the meantime your only option really
would be to write a script to coerce these formats to bed and explicitly
add the color column.

**Comment by paul-shannon** [comment]
Hi Jim,

The little tables I sent are just ad hoc subsets of an R data frame.   I can just easily create any other format, and will be glad to.  Can you point me to something to read so that I can create tables which follow accepted standards?

 - Paul

**Comment by jrobinso** [comment]
Oh sorry,  no offense intended.

If you need this right away I suggest the bed format,  which will suffice
for your first example.  The format is described here:
https://genome.ucsc.edu/FAQ/FAQformat#format1

You will need to supply up to column 9 (itemRGB) to do the color,
unfortunately.    This will be addressed in the "custom format" capability
I mentioned earlier, but I don't have an ETA on that.   An important point
-- bed is "zero" based coordinates,  so subtract 1 from your start
position.  End position is unchanged.   So the first base in chr1 is
represented as

chr1 <tab> 0 <tab> 1

If you create the bed and color doesn't work file a bug report with an
example bed and we'll fix it, but it should work.

**Comment by paul-shannon** [comment]
No offense taken!  Many thanks for the tip about the 9-column bed format, and the 0-based coordinates.   Just the help I was hoping to get.  

Thank you!

 - Paul
