### ISSUE TITLE
Issues accessing certain features on firefox

### ISSUE THREAD

**Issue by cganote** [igvteam/igv.js#327]
Hi,

I've noticed that our Galaxy server (https://galaxy.ncgas-trinity.indiana.edu - which connects to igv services) isn't behaving the same way in FF as it does in Chrome. I get an error from FF straight away:
<img width="843" alt="image" src="https://cloud.githubusercontent.com/assets/5487606/23080664/9c74f970-f51f-11e6-85c5-08d4ead6aabc.png">
And then it seems unable to load up the chromosome map:
<img width="1100" alt="image" src="https://cloud.githubusercontent.com/assets/5487606/23080745/01ce736e-f520-11e6-84c3-05a93f0eb4dc.png">

I get no error in Chrome and the chrom map loads just fine:
<img width="846" alt="image" src="https://cloud.githubusercontent.com/assets/5487606/23080823/4be8e7fe-f520-11e6-8dba-54a039906699.png">

Is this a known issue?

**Comment by jrobinso** [comment]
Hi,

What version of igv.js is this page using?

Jim

**Comment by cganote** [comment]
How can I find out? I pulled down a copy of igv-all.js and saved it locally.
-Carrie

**Comment by jrobinso** [comment]
Hi, pulled down from where?  It sounds like you have a very old copy,
probably pre-release,  since it should have a release number on it.   For
example this is the current release

https://igv.org/web/release/1.0.6/igv-1.0.6.min.js
