### ISSUE TITLE
Access permissions

### ISSUE THREAD

**Issue by olegs** [igvteam/igv.js#330]
Once I navigate to the URL: https://github.com/igvteam/igv.js/wiki
I click on link Integrative Genomics Viewer (IGV) https://github.com/igvteam/igv.js/wiki/www.broadinstitute.org I am able to create new page, looks like a security problem.
<img width="1024" alt="igv" src="https://cloud.githubusercontent.com/assets/75644/23579519/4564b89a-0100-11e7-8edf-cf3b7ace1f6a.png">

**Comment by jrobinso** [comment]
Thanks for the report.  Surprisingly this is the default github setting.    I was not aware of that,  page creation is now restricted.
