### ISSUE TITLE
How to display multiple sequences alignment file

### ISSUE THREAD

**Issue by newuser1971** [igvteam/igv.js#331]
I just know that igv.js is not supporting the psl file format. I want to know what kind of multiple sequences alignment file format it supports.

**Comment by jrobinso** [comment]
It doesn't support multiple sequence alignments,  and psl is not a multiple
sequence alignment format (.maf is).     You can find a list of file
formats currently supported here:
https://github.com/igvteam/igv.js/wiki/Tracks

**Comment by newuser1971** [comment]
My purpose is to display reads mapping file (indexed sorted bam). Then extract consensus sequences from this bam file and map to reference sequence. What tool should I use to do the consensus mapping and display in igv.js track.

Thank you very much!

Haibin

Haibin Wang

GRVLB, DVD, NCIRD
Centers for Disease Control and Prevention
Atlanta, GA 30333
Mail Stop: G18
(404) 639-1205 (Office)
(404) 639-4005 (Fax)
ytm4@cdc.gov<mailto:ytm4@cdc.gov>

**Comment by jrobinso** [comment]
Hi,  you'll need to look elsewhere for advice on bioinformatics analysis,
 we do visualization.     For the last part of your question,  displaying
tracks,  see the supported file formats link I posted earlier.
