### ISSUE TITLE
Use SASS for CSS Generation

### ISSUE THREAD

**Issue by turner** [igvteam/igv.js#333]
Use SASS for CSS Generation.

**Comment by david-ma** [comment]
Hi Douglass!

Sorry to be nosey, but I see you're refactoring the CSS using SASS?

But I don't see grunt-contrib-sass added to the package.json or to the gruntfile. Are you using something else to compile the SASS?

**Comment by jrobinso** [comment]
Good point, we probably should,  for now we are generating it and keeping
the css in the repo (in addition to the sass).   This will be less
disruptive.    However, having it generated during the grunt build and
copied to dist should also be done.

**Comment by turner** [comment]
Now using SASS for CSS creation.
