### ISSUE TITLE
Large BAM file cannot be loaded in 32 bit Chrome in Windows 10, while the same one can be loaded in 64 bit Chrome in MacOS 

### ISSUE THREAD

**Issue by jinyichao** [igvteam/igv.js#335]
I tried to load the same BAM file (~500 MB) with igv.js. 

The problem is when I am using 64 bit Chrome in MacOS, everything works fine. However, when I open the same page using 32 bit Chrome in Windows 10, an error message popped up, indicating "RangeError: invalid array length". 

Is anyone here met the same issue? Is it related to [#317](https://github.com/igvteam/igv.js/issues/317)?

**Comment by jrobinso** [comment]
What version of igv.js are you using  (what is the URL to the igv.js)?

**Comment by jinyichao** [comment]
I used igv-1.0.6.js downloaded from https://igv.org/web/release/. My code at the front-end is basically the same as [igv.js/examples/bam.html](https://github.com/igvteam/igv.js/blob/master/examples/bam.html)

**Comment by jrobinso** [comment]
Get the latest,  1.0.7,   that should address it.
