### ISSUE TITLE
Feature request: simple HTTP authentication

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#336]
Hi,

Would it be possible to add support for simple http authentication?
e.g. `http://user:pswd@dataserver/path/to/file.vcf.gz`

Thanks
M

**Comment by jrobinso** [comment]
Sorry I missed this @matthdsm,   I've tagged it for the next release.   Is it still of interest?   I assume the server in this example implements "Basic Authentication".

**Comment by matthdsm** [comment]
Hi Jim,

I totally forgot about this too. Should be something that's programmed in from the users end.
closing, thanks anyway!

M
