### ISSUE TITLE
Igv J's takes more time to load bam track

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#338]
Hi,
How to make igv.js to load bamtrack faster?
Many times it takes approximately 1 min. For every igv.browse.search call.

**Comment by amolpshinde07** [comment]
@jrobinso please help me out

**Comment by jrobinso** [comment]
You need to profile your web page and determine what is taking time.   I can't help you out with such a vague request.

**Comment by amolpshinde07** [comment]
i checked by debugging igv.js and found that it request 3-15 MB data for every request which causes more time to download the response.

**Comment by jrobinso** [comment]
That is the data needed for display,  its not an igv.js issue.   What do you expect will happen without the data?   If its taking your application minutes to load 3-15 MB of data you have an issue with your webserver,  in any event nothing can be done in the client.

**Comment by amolpshinde07** [comment]
@jrobinso Thanks
