### ISSUE TITLE
Tribble index - can only read full chromosome

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#339]
Coming from the tail end of https://github.com/igvteam/igv.js/issues/320, creating a new ticket to maintain visibility into this.

"The "tribble" index isn't fully implemented and can only read a whole chromosome"

Leaving out a 'visibilityWindow' param on a bgzip+tabix bedgraph file causes the entire chromosome to be loaded.  Setting a visibility window of NNN allows only that slice to be loaded.

**Comment by jrobinso** [comment]
I think this was fixed long ago,  if not re-open.
