### ISSUE TITLE
IGV Spinner is not getting displayed while bam track rendering

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#341]
@jrobinso  igv-spinner is not displayed when bam track is rendering.

**Comment by amolpshinde07** [comment]
@jrobinso is there any fix for this? or anything else?

**Comment by jrobinso** [comment]
I can't reproduce the problem,  can you provide more details and a
step-by-step to reproduce?   Also identify the browser version you are
using,  as well as the igv version if you are not using the lastest code in
master.
