### ISSUE TITLE
Create a bower igv.js package

### ISSUE THREAD

**Issue by vrockai** [igvteam/igv.js#342]
Having a [bower](https://bower.io/) igv.js package would make it much more convenient to use and it will resolve the bundled dependency issue. Right now the project dependencies are bundled in the same file as the igv.js itself. This can create conflicts in practice (i.e. including into a project that uses [lodash](https://lodash.com/docs/4.17.4)). Even if you don't agree on creating a bower package out of this project I would suggest excluding the dependencies from the igv.js dist file.

I can work on this feature.

**Comment by jdelafon** [comment]
That - or npm - would be really useful!

**Comment by jrobinso** [comment]
I agree this would be a good thing,  I don't have cycles to work on it.
The issue you are having is not with the igv object itself, but rather the
singleton design of the igv.Browser object.  That is something we are going
to change irrespective of packaging (remove the singleton dependency).

WRT module systems,  I would welcome a pull request if it does not require
the module system  (i.e. use or Bower, require, or anything else is
optional).    It should not break existing user's pages, or if it does the
fix should be trivial and not require additional includes.

WRT dependencies are you referring to the third party packages such as
underscore (as opposed to inter-project file dependencies)?   I agree with
that in principle,  but could you elaborate on the "lodash"  comment?
What is the specific conflict you are referring to?

**Comment by vrockai** [comment]
This issue is outside our troubles with the singleton design, it's just a matter of the IGV library consumer comfort.

1. Registering a bower package doesn't need to change anything at all. Basically, on minimal level, it would just require adding _dist_ files into the repository + one additional bower annotation json file. Another level would be to maintain a bower package, which in practice means to run a shell command after each release.

2. I'm referring to [these 3rd party packages](https://github.com/igvteam/igv.js/blob/master/Gruntfile.js#L21-L27). We're using [lodash](https://lodash.com/) extensively in our project. _Lodash_ puts the `_` object into the global/window scope. IGV.js does the same thing with _underscore_, which overwrites our _lodash_. What I did as a workaround is a custom build of IGV [commenting out the underscore dependency](https://github.com/igvteam/igv.js/blob/master/Gruntfile.js#L27). Of course, I had to check all the usages of the `_` in the IGV code, to make sure all used _underscore_ functions are still supported in the _lodash_ version we use (because this way, _lodash_ is used instead of _underscore_ in the IGV code).

Since a workaround exists for us, this isn't a high priority item for me and I haven't started inspecting it deeper. But just by quick googling, [this seem to be quick&easy approach](http://stackoverflow.com/a/12907774) to fix the dependency-pollution issue.

**Comment by jrobinso** [comment]
I will move the 3rd party includes out, at least those that are still
maintained (not sure about inflate.js).

RE underscore and lodash,   I can move it out but you would still need to
check all the usages.   If both packages define the same object ("_") in
the global scope I don't know what else you can do.   Perhaps you are
saying Bower handles that?

**Comment by vrockai** [comment]
Checkout the link from the last paragraph in my previous comment. I think it might be possible to encapsulate the IGV with all its dependencies in a separate anonymous `function` scope and only propagate the igv itself to the global one.

**Comment by jrobinso** [comment]
Could be, my head isn't in igv.js at the moment I'm covered up with IGV
desktop.   Will study it when I have time.   Thanks for the tip.

**Comment by jrobinso** [comment]
If I understand your comment correctly would it be advantageous to wrap all
dependencies in this manner, including jQuery?

**Comment by sgratzl** [comment]
re npm compatible: https://github.com/datavisyn/igv_wrapper

**Comment by vrockai** [comment]
will need to check how it deals with dependencies, especially the `lodash`.

**Comment by sgratzl** [comment]
what do you mean, as far as I can see igv.js has no dependency on lodash. With a quick search I can't find any `_.*` calls in igv-1.0.9.js

**Comment by vrockai** [comment]
Hm, strange. I was referring to the source code, stuff like this:
https://github.com/igvteam/igv.js/blob/master/js/browser.js#L155

When I build the current `master` branch, my `dist/igv.js` file is full of lodash references. However, when I download the `1.0.9` release zip and build it, I don't see any lodash references in the dist file.

Since I remember having troubles with lodash before and I was always using locally built `master` branch, I must be missing some steps from the release process.

**Comment by sgratzl** [comment]
as far as I understood, the master is going through a lot of refactorings. One of them is incorporating underscore. That's why it is listed as beta dependency only.

**Comment by jrobinso** [comment]
@vrockai That's because we did not user underscore fo version 1.0.9 (or any 1.0.x).  That was introduced in the master branch,  which will be the basis for release 1.1 by the end of the year.

Originally we packaged underscore with our igv.js file,  but that caused issues for you because you were using lodash which also defines the global "_".   So we removed it from igv.js and now list it as a dependency.

**Comment by jrobinso** [comment]
As a first step towards minimizing dependency clashes (e.g. underscore and lodash) I am going to investigate wrapping all dependencies used by igv.js inside a function, and exposing only the "igv" object.  I think @vrockai suggested this approach above.    I think @sgratzl has posted an NPM solution for version 1.0.9.

**Comment by jrobinso** [comment]
I _think_ that with the latest commit "igv.js" will be AMD and CommonJS compatible.  Thanks to @sgratzl  and @vrockai for showing the way.   This does not address the OP request to make a Bower package, but perhpas it makes that easier.   Could those of you with interest in this give it a try and provide comments?   See wrapper/header.js and wrapper/footer.js.

I'll turn my attention to the underscore problem next.   I'm going to try to encapsulate it within igv.js without exposing the global "_" variable.   This will require modfiying underscore.js to avoid creating the global, but I think it can be done.

**Comment by jrobinso** [comment]
@vrockai Underscore is now encapsulated in igv.js,  the "_" function should not appear in global scope.

**Comment by vrockai** [comment]
Thanks @jrobinso, I'll check the solution tomorrow and share my experience when I was trying (and failed) to accomplish the same goal.

**Comment by jrobinso** [comment]
@vrockai Thanks, that would be really helpful.   I think I've followed the encapsulation rules but don't have anything setup to test it.  I had to modify underscore slightly to prevent it from defining a global and registering itself as a module.   AFAIK "igv" is the only global now.

**Comment by vrockai** [comment]
I have compiled current `master` with `$ grunt` and I must confirm that the `dist/igv.js` now doesn't clash with our internal lodash instance and works like a charm OOTB! Great job and big thanks @jrobinso! No more changes in the igv.js code for us to use it within our platform.

When I had been working on it, I was trying to come up with a solution without modifying the existing `underscore.js` file. I wasn't able to find a satisfactory solution within a reasonable time-frame and then my priorities switched and I forgot about this issue. Such approach was a mistake on my side, because the wrapper solution is good enough and solves the problem.

I've got several ideas in this area:

Another way would be to not include the underscore in the `igv.js` dist file at all. It could be stated as a dependency in the package.json (and/or bower.json) and referred in grunt or html files directly: `node_modules/underscore/underscore.js` instead of `vendor/underscore.js`. In this case no wrapping would be needed and developers using the bower package would have some options how to deal with using lodash instead of underscore:
* http://underscorejs.org/#noConflict
* Overriding the igv.js bower dependencies inside their project

This would need to be tested though. 

Another way would be to go for lodash.js instead of underscore. Igv.js uses only a few functions from underscore. In lodash, those function could be imported one-by-one and thus save space.

One way or another, this is a great step towards igv.js bower package. @sgratzl would it make sense to transfer your packaging related work inside this repository?

**Comment by jrobinso** [comment]
Thanks for the testing and suggestions @vrockai.   I agree a solution that does not involve modifying underscore would be better,  for now, we will stick with this one for underscore since we know it works.  As you note we don't use much of underscore, just a few of the collections functions.

Are there any other artifacts we should distribute to make igv.js friendlier to bower users?

**Comment by renyaoxiang** [comment]
I prefer npm package than bower package.
And a suggestion, the gulp or webpack is better than grunt to build a new igv version.

**Comment by jrobinso** [comment]
If you want to make an NPM package you should be able to with the current
igv.js or igv.min.js.

**Comment by jrobinso** [comment]
igv is now published to NPM.   If a Bower package is still needed please re-open this,  but also be prepared to help test it.
