### ISSUE TITLE
Canvas error in the Firefox browser

### ISSUE THREAD

**Issue by vrockai** [igvteam/igv.js#344]
When trying the examples, I see the error `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`:
![image](https://cloud.githubusercontent.com/assets/1726340/24651353/c4a2dc78-192d-11e7-968f-0cb70f226950.png)

Commenting [this line in karyo.js](https://github.com/igvteam/igv.js/blob/master/js/karyo/karyo.js#L233) in the code solves the issue:
```js
            drawImage.call(this);
        }

        // Comment here to prevent the FF issue:
        // this.ctx.drawImage(image, 0, 0);

        // Draw red box
        this.ctx.save();

        // Translate chr to official name
        var chr = referenceFrame.chrName;
```

**Comment by vrockai** [comment]
Any idea why this is happening, @jrobinso? It makes the browser unusable on recent versions of Firefox, that's a pity.

**Comment by jrobinso** [comment]
Apologies for the delay,  I just checked in a fix.
