### ISSUE TITLE
igv.js Run with own data sets

### ISSUE THREAD

**Issue by deshmukhpankaj30** [igvteam/igv.js#346]
I want to integrate this igv.js own html project.
I want to run browser with own data set.
can you help me to integrate this plug in.

**Comment by helgathorv** [comment]
Please see the documentation in our GitHub [wiki](https://github.com/igvteam/igv.js/wiki). It also has links to some example webpages that embed igv.js.

**Comment by deshmukhpankaj30** [comment]
Thanks for help...
but sir want to load my own .fa file.

**Comment by jrobinso** [comment]
Did you see the section on "reference" here:  https://github.com/igvteam/igv.js/wiki/Browser

igv.js is an embeddable javascript object for use by web developers, it is not an end-user application.   For that purpose I suggest you use IGV desktop.

**Comment by deshmukhpankaj30** [comment]
thanks for suggestion but i have use igv.js plug not desktop version.
Suppose at set my own data set paths where they are given fasta file path and cytoband.txt. file path.
It will take my data set as input. Suppose not, where should modify code after it will work.

**Comment by jrobinso** [comment]
Sorry but I don't understand your question at all.   You know where the source code is, and we have pointed you to the documentation.   Local file paths are not supported at all,  this is a web client.   I am closing this as there is no specific issue here.
