### ISSUE TITLE
configure zoom in threshold?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#347]
Hi Jim,

We sometimes wish to display only a very few bases in igv.js.  One place this comes up is when examining a transcription factor binding motif, which might for example be only 8 bases long.

It appears that there is a 39-base minimum.  Can this be configured to something smaller, say, 5 bases?

As always, we find igv.js incredibly useful.

 - Paul

**Comment by jrobinso** [comment]
Sure 

@turner  Could you find this setting and make it a config parameter?  Its probably hard-coded to "40" somewhere.

**Comment by turner** [comment]
Hi Paul,
There is now a config parameter called `minimumBases ` that sets the zoom-in limit.
Closed with commit 611da968

**Comment by paul-shannon** [comment]
Thanks, Doug.  Looks like just what we need.

Are there build notes somewhere?  Looking through the directories, I did not find anything I recognize for that.

 - Paul

**Comment by turner** [comment]
Paul, here is an example of setting the zoom-in threshold to 6 bases via the `minimumBases` parameter:

![screen shot 2017-04-11 at 10 05 08 am](https://cloud.githubusercontent.com/assets/87169/24913223/7a49dd9a-1e9e-11e7-8be8-4d69bb812eb2.png)

**Comment by paul-shannon** [comment]
Thanks, Douglas.

Sorry that I was unclear.  I meant to ask: how to I build igv.js from source, so that I can use the feature you just added?   Or perhaps the feature in already included in the latest 1.0.7 build?

 - Paul

**Comment by turner** [comment]
Run grunt.

**Comment by turner** [comment]
Sorry Paul, my head is buried in some code. You can find the update in the nightly build here: https://igv.org/web/beta

**Comment by paul-shannon** [comment]
Thanks, Doug.  Both of your answers are helpful.  Thanks for finding time to add this new feature!

 - Paul

**Comment by turner** [comment]
You bet.
