### ISSUE TITLE
How to load big bam file

### ISSUE THREAD

**Issue by cangfengzhe** [igvteam/igv.js#351]
I have a big bam file about 20Gb . when  loading the bam  , Chrome are down or not responding. Can you develop a back-end server(like php、java、python） to  load bam file and display in browser?

**Comment by jrobinso** [comment]
The size of the bam is irrelevant,  the index file is used to load only what's needed.  The bam for this example is approximately 80 GB:  http://igv.org/web/examples/bam.html

We have no plans to develop a back-end server.

**Comment by jrobinso** [comment]
Does the server hosting the bam file support range requests?  This is a requirement.   See https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements
