### ISSUE TITLE
way to set default "Color by" { 'track color', 'read strand', 'tag'} track options

### ISSUE THREAD

**Issue by cristynkells** [igvteam/igv.js#354]
Currently I don't see an easy way to set a default "Color by" { 'track color', 'read strand', 'tag'} for a track within the track options.  Would it be possible to add this to a future release?

**Comment by jrobinso** [comment]
Did you see the colorBy options described here (in alignment track
section)?  https://github.com/igvteam/igv.js/wiki/Tracks

**Comment by cristynkells** [comment]
Thank you! I do now.  Thank you thank you!
