### ISSUE TITLE
Extending references

### ISSUE THREAD

**Issue by vrockai** [igvteam/igv.js#363]
While the `hg18` and `hg19` references are supported by default, is there any plan to support more references? I'm interested in `grch38/hg20` in particular.

The desktop IGV browser can accept a `.genome` file, like:
http://s3.amazonaws.com/igv.broadinstitute.org/genomes/hg38.genome

Is this file type somehow supported in IGV.js, too? What are my options if I want to use `hg20` with IGV.js?

**Comment by ttriche** [comment]
hg20 doesn't exist... the hg38 genome file you pointed at is the one you
would want for the-assembly-that-followed-hg19.  In other words, hg38 is a
0-indexed version of GRCh38, but the sequences on each chromosome are
(should be) the same.

I can't find a live demo using the hg38 reference but this problem was
referred to and (apparently) solved in #315.



--t

**Comment by jrobinso** [comment]
Hi,
Yes I do plan to support all IGV hosted genomes, however not via the
.genome file.   The plan is support a json representation that is common to
IGV and igv.js.   That is not developed yet in IGV.

In the meantime you can use the "reference" object to specify paths to
fasta, index, and cytoband ideogram (optional).    I don't recognize hg20,
 I think you mean hg38.   You can use the following paths for that assembly

https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa
https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa.fai


cytoband
https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/cytoBandIdeo.txt

for an annotation track you can use

https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz
https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz.tbi
  (index)

**Comment by vrockai** [comment]
Thanks a lot! Sorry about the confusion. As you have correctly assumed, I had `hg38` in mind. However, the https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/cytoBandIdeo.txt file doesn't seem to render the cytoband correctly:
![image](https://cloud.githubusercontent.com/assets/1726340/25757878/9bfd27bc-31cc-11e7-8dc9-425b0a931ebb.png)

By any chance, do you host an annotation track for `hg18` somewhere, too? Or this SNP file used in examples for `hg18` and `hg38`:
https://github.com/igvteam/igv.js/blob/master/examples/beta.html#L83

Is there a list of hosted files by _igv.broadinstitute.org_ somewhere?

**Comment by jrobinso** [comment]
There is not a list per se,  but its easily discoverable.   First step is  the "data server registry" file for the genome, a flat list of xml files.  For genomes of interest

http://data.broadinstitute.org/igvdata/hg18_dataServerRegistry.txt
http://data.broadinstitute.org/igvdata/hg19_dataServerRegistry.txt
http://data.broadinstitute.org/igvdata/hg38_dataServerRegistry.txt

Then look through the XMLs listed.  For your purposes the "annotation" xml is probably the most interesting, for example

http://www.broadinstitute.org/igvdata/annotations/hg18/hg18_annotations.xml

Its might also be helpful to run IGV desktop,  select a genome,  then select "File > Load from server" to see what is there.

**Comment by jrobinso** [comment]
Modifying this to "add more references"

**Comment by jrobinso** [comment]
The list is longer now, and growing, current list is at https://s3.amazonaws.com/igv.org.genomes/genomes.json.   The cytoband rendering bug for some assemblies is noted in another issue.

**Comment by adebali** [comment]
How about bacterial genomes, like `E coli`? If not, how can I build custom reference genomes? Is there any documentation on this? @jrobinso

**Comment by jrobinso** [comment]
https://github.com/igvteam/igv.js/wiki/Reference-Genome-2.0
