### ISSUE TITLE
Can't use the locus option inside bootstrap tab

### ISSUE THREAD

**Issue by vrockai** [igvteam/igv.js#364]
If I use the IGV browser inside a bootstrap tab, there are some unexpected troubles with setting the locus. If the tab with IGV is not initially rendered (i.e. it's in the 2nd tab), the locus end position is changed to NaN. This is because [the IGV width is somehow used to compute the end position](https://github.com/igvteam/igv.js/blob/e04779cd65b840d758ba552ffe069c45e5bee6dc/js/browser.js#L526) despite the fact it was explicitly provided in the `options.locus`.

I've prepared a live example for this issue. While I set the locus to be `"chr1:1,000,105-1,000,204"`, it's changed to `1:1,000,106-NaN` after clicking on the _IGV_ tab:
https://jsbin.com/fejivomufa/edit?html,output

**Comment by jrobinso** [comment]
Thanks for the report, and example.  Will look into it.

**Comment by turner** [comment]
Viliam,
I have a fix for you. See this gist 
https://gist.github.com/turner/568bc67f5f2cda81c97fcc0cb19f9b69

The idea is to lazy load the IGV browser in a tabbed scenario.

**Comment by jrobinso** [comment]
Lets leave this open as a proxy for the more general problem,  that IGV can't be initialized in an "unopened" element.   The fix above is a good workaround but we should make it not necessary.  @vrockai the position in the locus box is live,  updated constantly as you move around or change the size of the window (and hence vieport).   That's the root of the problem.   Until we have a fix for this initialization problem try Doug's workaround.

**Comment by Parul-Kudtarkar** [comment]
Any permanent resolution to this?

**Comment by Parul-Kudtarkar** [comment]
NVM react-bootstarp has  unmountOnExit option, that Unmount tabs (remove it from the DOM) when it is no longer visible - https://react-bootstrap.github.io/components/tabs/

**Comment by valleema** [comment]
@Parul-Kudtarkar can you show a code snippet how to use it?

**Comment by jrobinso** [comment]
Hi all, the original problem was fixed long ago.   There is an example with a tab here  https://igv.org/web/release/2.5.2/examples/tabs.html

**Comment by jrobinso** [comment]
When a tab is made visibile you need to inform igv by calling
```
 igv.visibilityChange()
```

**Comment by valleema** [comment]
Thanks @jrobinso, I will try it!
