### ISSUE TITLE
Re-initializing and reusing the igv.js browser

### ISSUE THREAD

**Issue by vrockai** [igvteam/igv.js#366]
In our use-case we use the igv browser at several places in the app. We show different files at different places. Usually we create a new browser on each page, but all of them are using the same global `igv` object. But we often get intermittent errors like:
![image](https://cloud.githubusercontent.com/assets/1726340/25859323/783dc470-34de-11e7-874b-8925c4a25b54.png)

I was trying to find the root, but it's not trivial (there are no errors in the console). I believe It has something to do with reusing the global `igv` object. 

The question is whether the igv.js in its current state is suitable for such use-case. I've tried to re-initialize the browser in the examples just by duplicating the line :
```js
    igv.createBrowser(div, options);
    igv.createBrowser(div, options);
```

but that gives me duplicated browser:
![image](https://cloud.githubusercontent.com/assets/1726340/25859528/2603c956-34df-11e7-8ef5-574473c6cff2.png)

What is the right way to re-use the `igv` object on several pages with different datasets?

**Comment by jrobinso** [comment]
Hi,

The current igv.js implementation is limited to a single instance per page.
  I'm not sure what you mean by reuse the igv object on several pages,  how
are you doing that?   I can't see how that is possible as each page should
have its own javascript context.

Could you share some html that illustrates how you are doing this?

We plan to support multiple instances per page by removing the dependency
on the global igv.Browser object,   but I'm not sure it will address you
use case of "multiple pages".

**Comment by vrockai** [comment]
Thanks for the info. We use the IGV in an angularJS (single-page-application) app. While our platform is "multi-page" from user perspective, it's just a single page from javascript perspective and we don't have the liberty of reseting the global scope thus we have to reuse the global `igv` object in many places. 

If this doesn't answer your question, I can sketch an example of such application.

**Comment by jrobinso** [comment]
No that answers it.   Unfortunately the current implementation is limited
to a single igv.Browser object per page.     It is a restriction we will
relax.   I will keep this issue open until that is fixed.

**Comment by jrobinso** [comment]
This is fixed,  you can create many browsers, and destroy them as well.
