### ISSUE TITLE
Can i run this igv.js browser with my own data sets

### ISSUE THREAD

**Issue by deshmukhpankaj30** [igvteam/igv.js#367]
I have the browser with my own data sets, can run, if possible can help to where modify the code.

**Comment by jrobinso** [comment]
You must host your datasets and server them over http or https.  See
https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements  for data
server requirements.

**Comment by deshmukhpankaj30** [comment]
Thank you sir for your reply.
I host my dataset on server and run the browser it gives error : **Error accessing resource:**.
How to solve this problem.

**Comment by jrobinso** [comment]
Did you check your server settings carefully against the requirements listed above?

**Comment by deshmukhpankaj30** [comment]
Thank you so much sir..
It is work properly.
