### ISSUE TITLE
No alignments shown due to downsampling of a high-coverage region next to it

### ISSUE THREAD

**Issue by christianbioinf** [igvteam/igv.js#371]
I am using IGV.js for visualizing high-coverage amplicon variant data and it works very nice (even by displaying thousands of alignments).

![igvjs_downsampling_issue](https://user-images.githubusercontent.com/10414269/27171624-77197fda-51b2-11e7-81d9-f93bf30d4466.png)
Unfortunately, I have now come across an issue or maybe a bug where the downsampling prevents the display of a found variant due to a high coverage region on the left side. I have tried scrolling to the right but it does not help very much in this case since there is also a high coverage region.

I thought that downsampling would lead to alignments in the high coverage region to be downsampled and alignments in the lower coverage region in the middle (the one with the variant and the one I am interested in) to be shown completely (or at least to the samplingDepth I am specifying). However, I do not see *any* alignments in the middle and hence the variant cannot be inspected.

I have tried out different values for `minimumBases`, `samplingDepth`, and `samplingWindowSize` (even set it to 1) but it did not work. The currently shown options are set as follows.
```
var options = {
    'genome': 'hg19',
    'minimumBases': 10,
    'showNavigation': 'true', 
    'showRuler': 'true',
    'trackDefaults': {
        'alignment': {
            'samplingDepth': 1000,
            'alignmentRowHeight': 8,
            'samplingWindowSize': 10
        }
    }
};
```

**Comment by jrobinso** [comment]
Hi,  alignments are downsampled in bins according to their start position.
Its impossible to tell from the picture where the alignments covering the
variant start,  but its likely they start well to the left in the deep
coverage region.  If that's the case I dont' see any solution other than
turning downsampling off by setting samplingDepth to NUMBER.MAX_VALUE.

If you can share a small slice of this bam I'm happy to look further.

**Comment by christianbioinf** [comment]
Hi, I get that when I have thousands of alignments with the same start position, some covering the variant and some not, the downsampling may not select those that do not cover the position. But this is not the case here.

This is primer clipped amplicon data where there is actually even a gap between the blocks of alignments (left and center ones). Also, display of the alignments and the variant in IGV works perfectly fine with settings "Downsample Reads: Max read count: 1000 per window size (bases): 50" (see screenshot with squished reads).

<img width="621" alt="igv_downsampling" src="https://user-images.githubusercontent.com/10414269/27215692-d1fae93c-5272-11e7-98a0-ae3cadef6b5f.png">

For testing I have extracted the region as [test.bam](https://www.dropbox.com/s/bwqd5wuqybxrs3l/test.bam?dl=0). Please tell me if you need anything else to reconstruct the issue.

**Comment by jrobinso** [comment]
OK, will look at the test bam.   When thinking about downsampling consider
the alignments single base "points",  because that's how they are treated.

**Comment by jrobinso** [comment]
Sorry for not responding, this one got lost.  
Downsampling is no longer required, so this issue is mute when turned off by entering a large max depth.  For example

```
                {
                    type: 'alignment',
                    format: 'bam',
                    url: '../test.bam',
                    indexURL: '../test.bam.bai',
                    name: 'test',
                    samplingDepth: 10000000,
                    alignmentRowHeight: 1
                }

```
