### ISSUE TITLE
Regarding the declaration for igv variable

### ISSUE THREAD

**Issue by shivangsoni** [igvteam/igv.js#372]
Hey!  I am being tracing this IGV.js code from many days can anyone please let me know where igv variable is declared. It's very hard to understand the actual flow of the code without it.

**Comment by jrobinso** [comment]
Look at any of the source files,  its declared as an argument to the
self-evaluating function wrapping all source files.

**Comment by shivangsoni** [comment]
Thanks a lot for the answer. One more thing is where is igv object instantiated can you please let me know the file for it and also line no or so. This is because I am new to javascript and bit confused in this. It would be great if you help me with this.

**Comment by jrobinso** [comment]
I think you need to study javascript a bit more,  this is not a forum for
javascript tutorials.    The object is instantiated as an argument in the
self-evaluating function wrapping the code in each individual file,  as you
can clearly see

var igv = (function (igv) {
...
}) (igv | {})

If igv already exists nothing happens here, if it doesn't its instantiated.
  So the first function evaluated will instantiate the object.  It is a
technique for encapsulating the enclosed code.    For further help please
read some javascript primers.
