### ISSUE TITLE
add an option for specify delimiter for decodebed function

### ISSUE THREAD

**Issue by lidaof** [igvteam/igv.js#376]
Hi Jim,

Is it possible to add an option to specify delimiter for `decodebed` function? say I only want use `\t` as delimiter.

Thanks.

**Comment by jrobinso** [comment]
Yes, that could be added.   But that would not be a legal bed,  bed files
are delimited by whitespace.    What is your use-case for this?

**Comment by lidaof** [comment]
Yes, it's a bed variant and we call it hammock :)
Please see this link at
http://wiki.wubrowse.org/Hammock#desc, the desc attribute might contain space for gene description.

**Comment by jrobinso** [comment]
OK,  its possible to define a custom format,  that is probably the way to
go.   I'm not sure this is documented but I will do so.   Not tonight
though.  If you don't hear anything back in a day or 2 ping this issue
again.

**Comment by lidaof** [comment]
sure, thank you @jrobinso .

**Comment by jrobinso** [comment]
On reflection, a custom format is overkill, particularly since the bed format is not really specified precisely anywhere.   You can now set the delimiter in the config object,  this applies only to "bed" format.
