### ISSUE TITLE
Annotation Track Feature Labeling Feature Request

### ISSUE THREAD

**Issue by skushch** [igvteam/igv.js#385]
Hi,

I'd like to propose an enhancement to how annotation track features are labeled. The current approach appears to be one where labels are always drawn under the feature as long as the width of the label is less than the width of the feature. We use IGV js to display various assets against the genome and in many cases these features are very short compared to the size of the gene. As a result, none of the features get labeled until you zoom in a lot. Unfortunately, once zoomed-in to a level where labels appear you lose the big picture of things.

It would be nice to have an option to draw labels to the right or left of the feature. This would solve the resolution problem for short features and also help pack features denser vertically. Tighter vertical packing would be nice since most people's screens are wider than they are tall. In comparing different viewers we see that many choose left/right labeling over the vertical configuration (for example UCSC or NCBI).

I don't fully appreciate the level of effort involved in this change but I imagine that the feature tiling logic would have to change to accommodate the varied width labels.

Thanks,
Sergey

**Comment by jrobinso** [comment]
Its actually quite complex.  Labels are not fixed length in base-pair
units, which is how features are packed.  I see the problem and it needs a
solution,  but it is a bit more complex than it would seem.   I think UCSC
supports what you are suggesting in one mode,  but they display exactly 1
feature per row.

If igv.js is following the logic you outline for labels that is a bug.   It
should display labels if there is room irrespective of the feature size.
I will look into that.

**Comment by dicara** [comment]
We're dealing with a similar issue. We want to display user generated annotation labels that are often quite verbose. Even if a user clicks on the annotation, the name is abbreviated in the pop-up. As opposed to left/right labeling, I was wondering if hover could be implemented. In other words, if a label doesn't fit under the annotation track, add as much of the label as will fit and suffix the label with an ellipsis to indicate it has been abbreviated. When a user hovers over the track, then the entire annotation label would appear. Is this a more feasible/simpler solution to implement?

**Comment by dicara** [comment]
In addition, spaces in annotation names are not respected. We're providing a tab delimited BED file. Therefore, if an annotation name contains a space, I would expect the whole name to appear. Instead, only that portion of the name prior to the space is displayed. Is this a bug or is this by design?

**Comment by jrobinso** [comment]
@dicara these are separate issues,  at least the space one is,  open new issues (1 for hover, if you want it, and 1 for the space-not-respected bug).   Thanks.

**Comment by dicara** [comment]
Will do. Thanks for the quick response!

**Comment by jrobinso** [comment]
I've changed the feature label heuristic, with an option to force labeling all features.  Feature label is now drawn if either of the following are true:

* track option  "labelAllFeatures=true"
* feature density is < 0.1  (10 pixels per feature) AND feature label does not overlap last feature label drawn.
