### ISSUE TITLE
how to run igv.js

### ISSUE THREAD

**Issue by shibuvp** [igvteam/igv.js#386]
hi, i'm fresher in igv. what is the running command of igv?
i have reference genome, bam file and vcf file. how to put this resources into igv?

**Comment by jrobinso** [comment]
Have you looked at the documentation and example files?

**Comment by shibuvp** [comment]
oke i will

**Comment by shibuvp** [comment]
@jrobinso hi sir, can i get exact command to run the igv using bam and vcf?
