### ISSUE TITLE
Ability to import generic track with JSON data object

### ISSUE THREAD

**Issue by sreisman12** [igvteam/igv.js#391]
Hi,
I am interested to find out if it is possible to load a track as a JSON object rather than a link to a file.  In particular I would like to build a backend API to generate the necessary data to load variant and annotation tracks in IGV by creating a JSON object from information stored in a database.  

From looking at the examples and documentation it seems that the only way to load such information is by providing a link to some file (in my case either a VCF or BED file):

{
      name: "Genes",
      type: "annotation",
      format: "bed",
      sourceType: "file",
      url: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed",
      indexURL: "//igv.broadinstitute.org/annotations/hg19/genes/gencode.v18.collapsed.bed.idx",
      displayMode: "EXPANDED"
   }

But would it be possible to instead build my own custom track information in a JSON object the looked more like this (just as an example):

{
  "name": "COSMIC Annoations",
  "type": "annotation",
  "format": "customFormat",
  "sourceType": "JSON",
  "dataPoints": [
    {
      "displayName": "variant1",
      "cosmicId": "32535353359",
      "location": "chr3:10,183,780-10,183,825"
    },
    {
      "displayName": "variant2",
      "cosmicId": "53439535",
      "location": "chr3:93,187,026-107,567,739"
    },
    {
      "displayName": "variant3",
      "cosmicId": "3534343553",
      "location": "chr7:23,343,029-203,897,989"
    }
  ]
}

This way, I would be able to dynamically build my tracks from information that has already been parsed from BED and VCF files?

Hopefully this is clear, and thank you very much for your time and help!

Regards,
Steven

**Comment by jrobinso** [comment]
Hi Steven, its still not clear what you want to do.    Where would these json object come from?  Are you going to provide a webservice?

**Comment by sreisman12** [comment]
Hi Jim, Yes, I would build my own webservice to create these JSON objects.  I have a database of variants, and I would like to pull the relevant fields from that database and construct some object which can be loaded as a track in IGV.  As an example, a field in my database for a variant is pasted below.  The only solution I can think of would be to take the variants which should be used from the db and construct a new VCF file which can be passed to IGV, but I think this is a bit cumbersome.  So I am asking if there is a possibility of passing  in the track in a more generic manner, such as a JSON object which contains the location, name, and some metadata which can be displayed when mousing over?

```
{
    "id": "f54c7113-013f-46f5-96ef-a8f446904f69",
    "adp": 1068,
    "alt": "C",
    "pos": 7579472,
    "ref": "G",
    "gene": "TP53",
    "meta": {
        "versionId": "f54c7113-013f-46f5-96ef-a8f446904f69",
        "lastUpdated": "2017-08-09T11:39:13.566992+03:00"
    },
    "qual": ".",
    "chrom": "chr17",
    "filter": "PASS",
    "strand": "-",
    "ExAC_AF": "65.8600%",
    "chunkNo": 0,
    "context": [
        {
            "reference": "2dcdede6-7cde-11e7-a5ee-000c29e38654",
            "resourceType": "Mutation"
        },
        {
            "reference": "dd6ca91e-7cdd-11e7-96ef-000c29e38654",
            "resourceType": "WorkflowRevision"
        }
    ],
    "location": "exonic",
    "tumor_dp": 1068,
    "COSMIC ID": "COSM250061",
    "HGNC_gene": "TP53",
    "normal_dp": 0,
    "variation": ".",
    "1000Gp3_AF": "54.2931%",
    "HGNC_genes": "TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53,TP53",
    "coordinate": "chr17:7579472",
    "mutationId": "2dcdede6-7cde-11e7-a5ee-000c29e38654",
    "tumor_freq": "99.81%",
    "HGVS_coding": "ENST00000269305.4:c.215C>G,ENST00000359597.4:c.215C>G,ENST00000413465.2:c.215C>G,ENST00000420246.2:c.215C>G,ENST00000445888.2:c.215C>G,ENST00000455263.2:c.215C>G,ENST00000503591.1:c.215C>G,promoter,promoter,ENST00000505014.1:n.471C>G,ENST00000508793.1:c.215C>G,ENST00000509690.1:c.-21-918C>G,promoter,ENST00000514944.1:c.96+228C>G,ENST00000604348.1:c.215C>G,NM_000546.5:c.215C>G,NM_001126112.2:c.215C>G,NM_001126113.2:c.215C>G,NM_001126114.2:c.215C>G,promoter,c.-939C>G,promoter,NM_001126118.1:c.98C>G,NM_001276695.1:c.98C>G,NM_001276696.1:c.98C>G,c.-1020C>G,c.-1020C>G,c.-1020C>G,NM_001276760.1:c.98C>G,NM_001276761.1:c.98C>G,XM_005256778.1:c.176-21C>G,XR_243565.1:n.354C>G,XR_243566.1:n.354C>G",
    "normal_freq": "0%",
    "rs_dbSNP146": "rs1042522",
    "variantType": "SNV",
    "HGVS_genomic": "17:g.7579472G>C",
    "HGVS_protein": "ENSP00000269305.4:p.Pro72Arg,ENSP00000352610.4:p.Pro72Arg,ENSP00000410739.2:p.Pro72Arg,ENSP00000391127.2:p.Pro72Arg,ENSP00000391478.2:p.Pro72Arg,ENSP00000398846.2:p.Pro72Arg,ENSP00000426252.1:p.Pro72Arg,promoter,promoter,-,ENSP00000424104.1:p.Pro72Arg,intron -21-918C>G,promoter,intron 96+228C>G,ENSP00000473895.1:p.Pro72Arg,NP_000537.3:p.Pro72Arg,NP_001119584.1:p.Pro72Arg,NP_001119585.1:p.Pro72Arg,NP_001119586.1:p.Pro72Arg,promoter,promoter c.-939C>G,promoter,NP_001119590.1:p.Pro33Arg,NP_001263624.1:p.Pro33Arg,NP_001263625.1:p.Pro33Arg,promoter c.-1020C>G,promoter c.-1020C>G,promoter c.-1020C>G,NP_001263689.1:p.Pro33Arg,NP_001263690.1:p.Pro33Arg,intron 176-21C>G,-,-",
    "RCVaccession": "RCV000013144;RCV000034639;RCV000079202;RCV000132165;RCV000144668;RCV000211157;RCV000211212;RCV000211311;RCV000211338;RCV000211395",
    "resourceType": "Aberration",
    "SomaticStatus": "Unknown",
    "authorization": [
        {
            "reference": "2b2c5cca-f5d1-11e5-bef2-000c29c80ba6",
            "resourceType": "Organization"
        }
    ],
    "AberrationType": "Nonsynonymous SNV",
    "COSMIC_summary": "Same amino acid change",
    "alt_strand_adj": "G",
    "ref_strand_adj": "C",
    "AberrationClass": "SNV",
    "AminoAcidChange": "P72R;P33R",
    "ClinVar_presence": true,
    "dbSNPID_presence": true,
    "ApprovedTherapies": false,
    "COSMICID_presence": true,
    "LRT_pred_combined": "Unknown",
    "ResistantToTherapies": false,
    "THERAPY_AVAILABILITY": true,
    "ExperimentalTherapies": false,
    "Canonical_HGVS_Protein": "p.Pro72Arg",
    "SIFT_pred_adj_combined": "Tolerated",
    "ClinicalSignificance_adj": "drug response",
    "FATHMM_pred_adj_combined": "Damaging",
    "MutationTaster_pred_combined": "Polymorphism Automatic",
    "MutationAssessor_pred_combined": "Low",
    "Polyphen2_HDIV_pred_adj_combined": "Possibly Damaging",
    "Polyphen2_HVAR_pred_adj_combined": "Benign",
    "10b1142b-529d-4e14-bcfe-5055f32c3bf": "TP53"
}
```

**Comment by jrobinso** [comment]
Hi, sorry for the delay, its very busy in IGV land this month but I am interested in this topic.   The answer is yes, it should be possible with minimal work, and I am interested in pursuing it. 

Minimally IGV just needs a location to draw a generic feature as a box.    One approach would be to allow you to specify the required fields in the track configuration, much as custom file formats are defined.   So for the above example

{ 
   .... 
   format: {
       "chrField" : "chrom",
       "startField" : "pos"
   }
}
        
A slightly more general approach, which would work for records in which there are not separate chromosome and position fields would be to let you specify a function to parse the required fields from the record,  so

{
     format:  function (record) {
           return {chr: record["chrom"],  start: record["pos"],  end: record["pos"]
     }
}

Both forms can be supported,  does this make sense?

As for specifying the webservice,  the basic requirement is a service that optional takes a genomic range and returns features overlapping that range.   If no range is provided it would return all features.    The range could be provided as parameters or in the body of a post.

It would be helpful if you had a public webservice I could experiment with a little,  if not I know of others.    But does this general  direction make sense?

**Comment by sreisman12** [comment]
No problem at all! Thanks so much for your response, it does make a lot of sense.  I currently do not have such a webservice built for you to experiment with but if I were to design the API it would do just as you have said,

 `GET /aberrationTrack?start=123&end=246` 

which would return a list of aberration features that can be displayed in IGV.  Since at a minimum IGV would need the chromosome position of each feature, this would always be in the response.  

However, I would ideally like to use this functionality for both an aberration track and annotation tracks.  So if you can imagine I would also have another API

 `GET \annotationTrack?type=cosmic&start=123&end=123` 

which would return a list of annotation features.  Each of these features would also of course have the chromosome position, but may have some additional metadata which would be nice to have displayed in the box when mousing over them.  So perhaps your idea of a function to parse the responses from the webservice would be the best approach?

**Comment by jrobinso** [comment]
OK I think we're converging on a solution.   I'll tackle this early September.

**Comment by sreisman12** [comment]
Great to hear! Please let me know if you think of any questions or if I can somehow be of assistance.

**Comment by josephhalstead** [comment]
Hi,

This would be a really useful feature? Do you know if it is likely to be implemented soon?

Thanks,

**Comment by jrobinso** [comment]
Actually, this is implemented,  just not documented and there is only one example.   See dev/cBio.html and js/feature/customServiceReader.

If you have a webservice ready  I can provide an example config for it and we can move this closer to release.   The basic requirement is the service accept a query for features as either a get or post,  and returns a list of feature objects.    The details of the objects depends on the type of track you are creating.    This all needs documented, obviously, but rather than leaving you hanging there until I am able to do that I pass this limited information.   If you have a service that is public and ready to test we can get it working in the meantime.

**Comment by josephhalstead** [comment]
Thanks for the speedy reply! Great I will take a look.

I am developing an internal tool so it does not have an external webservice at the moment. However, I will be able to deploy a dummy version of one when I get back to work in a few weeks. 

Essentially the API looks like:

Example Input:

A chromosome number, start and end position e.g.

api/variants/?chr=chr1&start=69000&end=70000

Example Output:

```
{
   "variants":[
      {
         "id":"id1",
         "chrom":"1",
         "pos":"69232",
         "ref":"C",
         "alt":"A",
         "lab_class":"Pathogenic",
         "lab_freq":"0.01"
      },
      {
         "id":"id2",
         "chrom":"1",
         "pos":"69252",
         "ref":"C",
         "alt":"A",
         "lab_class":"Benign",
         "lab_freq":"0.43"
      }
   ]
}

```
Thanks again for your help,

Joseph

**Comment by josephhalstead** [comment]
Hi,

I have had a go at configuring IGV for my webservice, but don't seem to be able to get it to work for a variant track.

I have an example of the API below. The API takes a get request with the following parameters: chr, start and end.

http://samwonderfall.pythonanywhere.com/api/variants/?chr=chr11&start=1&end=1000000000

Would you be able to direct me as to how I write a config file. I can easily change the API to fit the IGV structure if necessary. 

Thanks so much for the help,

Joseph

**Comment by jrobinso** [comment]
Hi, try this
```
{
    name: "Sample Variants",
    sourceType: "custom",
    type: "annotation",
    source : {
         url: "http://samwonderfall.pythonanywhere.com/api/variants/?chr=$CHR&start=$START&end=$END"
    }
}
```

**Comment by josephhalstead** [comment]
Great thanks!

**Comment by kzoabi** [comment]
Hi @jrobinso,
Thanks for this feature! And Happy New year
I understand that this feature will be on 1.1 release, any estimations when it will be officially released?

Regards,
Khaled

**Comment by slevkor** [comment]
Hi @josephhalstead 
maybe you me with same problem you had? 
showing variant track from webservice

**Comment by josephhalstead** [comment]
Hi @slevkor,

The config file that worked for me looked like:

      {  
    name: "Lab Variants",
    sourceType: "custom",
    type: "annotation",

    source : {
         url: "/api/variants/?chr=$CHR&start=$START&end=$END&format=json",
         method: "GET",
         contentType: "application/x-www-form-urlencoded",
         parser: JSON.parse


    }
    } 

My API returned something like this:

```
[{"position":111111,"ref":"A","alt":"C","worst_consequence":"missense_variant","chr":"chr9","start":111111,"end":111112}]

```

Hope that works for you.

Joseph

**Comment by slevkor** [comment]
Thanks @josephhalstead !!

**Comment by jrobinso** [comment]
Very long thread, but inputting json objects directly is now supported, as are custom webservices.
