### ISSUE TITLE
reference tracks: only hg18 & hg19 provided

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#395]
https://github.com/igvteam/igv.js/blob/73abf3854b533a6a32950c53dab92bddfa5ecaee/js/igv-create.js#L380

https://github.com/igvteam/igv.js/wiki/Browser suggests that 

````Hosted genomes. FASTA, index, and cytoband URLs can be omitted for genomes in this list.````

- id = "hg38"
- id = "hg19"
- id = "hg18"
- id = "mm10"

However the code chunk pointed to above, and my experiments with 1.0.9, suggest that only hg18 and hg19 (the default) - their fasta and cytoband reference tracks - are provided.    It would be helpful to have mm10 and hg38 also.

**Comment by paul-shannon** [comment]
mm10 is working fine now - thanks.   hg38 gene symbol searchstill appears to be broken; hg19 coordinates for AQP4, for example, seem to be returned by igvBrowser.search:

     chr18:24,430,007-24,447,716

rather than hg38's:

     chr18:26,850,038-26,867,818

If I supply my own searchable gene symbol track, I can override this on subsequent search function calls, from the search box or the console - but on igv load, with

      options.locus: "AQP4",
      reference: {id: "hg38"}

I initially get a display of the hg19 coordinates.   

Maybe the geneSymbol search for the hg38 reference you provide has the hg19 gene coordinates by mistake?

 - Paul

**Comment by paul-shannon** [comment]
I just discovered that if I expand ````options.reference```` as shown below, then the hg38 search function works as expected.   I guess over-interpreted the power of simply assigning ````id: "hg38"````, without also specifying ````fastaURL```` or ````cytobandURL````.
````
 reference: {
    id: "hg38",
    fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa",
    cytobandURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/cytoBandIdeo.txt"
    },
````

**Comment by jrobinso** [comment]
That's a bug, setting the ID should be enough.

**Comment by jrobinso** [comment]
Search is confirmed to work for hg38, hg19, and mm10
