### ISSUE TITLE
using parts of igv.js

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#397]
Hi,

I'm looking for a js module that can read and query compressed and indexed vcf files from a remote location (e.g. S3-buckets). Since igv.js is able to do all of that, I was wondering if it would be possible to use routines from igv.js to get raw vcf records (or a json representation) from a given region for further processing and visualisation?

Thanks a lot
M

**Comment by jrobinso** [comment]
Hi,  there's no API or support per se to do that yet.  Could you elaborate
on what you are trying to do?    Will the region you want to extract be
loaded into igv.js already, or do you want to go directly to the file?

**Comment by matthdsm** [comment]
Hi Jim, 

We're starting with predefined regions, and we'd like to get the vcf records from the remote files.
Essentialy what we're trying to do is get the required records from a vcf file, filter them based on quality, annotations etc. and then visualise those records in a tabular format, with a link to the visualisation. So what we actually would want is access to the querying modules, so we can parse the vcf records.

the flow would look somewhat like this
```
  1) select file, set filtering params, set regions of interest
  2) get table of filtered variants
  3) view select variants in IGV for further inspection
```

Hope this clarifies my question a bit.

Thanks
M

**Comment by jrobinso** [comment]
Got it.   There's no API to do that now,  but I could add one easily enough.   I'm traveling now,  will look at it next week.   Ping this issue again if it goes silent for too long.

**Comment by matthdsm** [comment]
Allright, that would be awesome!

Thanks a lot and happy travels!
M

**Comment by hakanEdico** [comment]
Hey @jrobinso, I would love this feature as well. I implemented the BAM viewer, but what we really want is to be able to have a table of some sort of VCF records, which I can click and it will take me to that position in the BAM file. Would be great to be able to use a tabix file along with the VCF, as well as be able to sort by qual/contig/etc.

**Comment by jrobinso** [comment]
This needs speced out very carefully,  there are 3 of us in this conversation potentially (probably) talking about 3 different things.   My focus is on the igv browser.   What exactly are you requesting?  There is already an IGV API to take you to a genomic position.

**Comment by hakanEdico** [comment]
So I want a table, just picture an HTML table with rows of VCF records. I would like to see parts or all of the VCF file in this sortable, searchable table. Then, when I click on one of the individual records, it takes me to that position the browser. I don't need the VCF track in the browser necessarily, just a way to link variant positions when clicked to the browser, to see the pileup at that position. 

I have been looking at VCF parsers to create my own table, and send requests to IGV browser, but parsing a VCF takes a long time. If it was integrated into IGV that would be super helpful as you already handle big files well.

**Comment by hakanEdico** [comment]
Actually I guess you already have the API to do what I want. You don't need to make an HTML table or anything, I would just need to know how to use the API to be able to extract records using a tabix file, or for a given range, etc. Not sure what kind of object that returns but if it were a list for example of rows from a specified region, that would be enough for me, then I can build my own HTML table and go from there.

**Comment by jrobinso** [comment]
You could create an igv.FeatureSource object for your vcf file.   See  feature/featureSource.   This object takes the same config that you use for a track.    Then use the "getFeatures" method to retrieve features for a genomic range.   The last argument ("bpPerPixel") is ignored.   This works for any feature file,  but if it is a VCF record you will get igv.Variant records back.  

See also the unit test test/testTabix.js,  in particular the "Washu query" test.   Although this test is on a bed file,  the same pattern applies for a vcf file.

**Comment by jrobinso** [comment]
This could be made part of the public API,  but you can use it as if it were,  its very stable.   If its useful I might add an API function to return the feature source,  rather than using "new igv.FeatureSource",  I think that's what I had in mind wrt my September 2017 comment.

**Comment by matthdsm** [comment]
Hi @jrobinso,

This had been a bit on the backburner for me lately. Are the any updates regarding my initial question?

Thanks
M

**Comment by jrobinso** [comment]
I think I provide it above,  use igv.FeatureSource (file  feature/featureSource.js).   It does exactly what you asked for.

**Comment by matthdsm** [comment]
Oh, great, thanks a lot!
I'll close this issue then.

Thanks again
Cheers
M
