### ISSUE TITLE
IGV.js with Angular CLI

### ISSUE THREAD

**Issue by sreisman12** [igvteam/igv.js#398]
Has anybody successfully loaded IGV.js into an Angluar CLI app?  It seems that there is an issue with dependencies, and JQuery in particular.  I have looked at the issue noted here: https://github.com/igvteam/igv.js/issues/300 which seems to show a similar problem, but I am wondering if anybody has successfully integrated with an Angular 4 app?

Thanks,
Steven

**Comment by jrobinso** [comment]
Hi, hopefully someone with Angular experience will chime in,  but could you
describe in more detail the issue?  Does Angular require a specific jQuery
version?

Jim

**Comment by sreisman12** [comment]
Hi, I am using Angular CLI to inject the dependencies which I have managed with npm.  Currently, the scripts I am importing are as follows:

`"scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/jquery-ui/ui/core.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "./assets/scripts/igv-1.0.1.js"
      ],`

I am seeing a very similar issue to the issue #300 

![image](https://user-images.githubusercontent.com/30884053/29894328-f842147e-8da2-11e7-844c-5b9078e465e5.png)

I believe it may have to do with the version of JQuery, or something not being compatible with Angular.  Does anybody have any suggestions?

Thanks,
Steven

**Comment by jrobinso** [comment]
That's quite an old version of igv,  I would first suggest trying the
latest version.  Will look into the specific error,

**Comment by sreisman12** [comment]
I have updated to use the version 1.0.9 and have found the culprit line in the debugger which may be helpful:

`igv.popover = new igv.Popover($(contentDiv),"igv-popover"),`

![image](https://user-images.githubusercontent.com/30884053/29931122-53c42882-8e3e-11e7-98b0-81878c2b7e43.png)

**Comment by turner** [comment]
Are you including jquery-ui.css and jquery-ui.js? That is where the draggable functionality is hosted.

See https://api.jqueryui.com/category/interactions

**Comment by sreisman12** [comment]
I made sure to add `jquery-ui.css` and `jquery-ui.js`

My angular-cli.json file contains the following imports now:

`   "styles": [
        "./assets/styles/jquery-ui.theme.min.css",
        "./assets/styles/jquery-ui.min.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "./assets/scripts/jquery-ui.min.js",
        "./IGV/igv-1.0.9.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
      ],`

But I am still seeing the same error message.  I believe it may be an issue with the order in which the scripts are loaded, but can't seem to get it working.

**Comment by jrobinso** [comment]
When is the call to igv.createBrowser being made?  Is  it withing a $(document).ready() function, or equivalent?  Also,  does Angular load scripts asynchronously?

**Comment by jrobinso** [comment]
Update on this.  In the master branch / latest beta there are no external dependencies on jquery or jquery-ui.    So this issue should be resolved.

**Comment by jrobinso** [comment]
Final update,  igv.js has no javascript dependencies now (latest master branch).    Also, its available as an NPM module under the package name "igv".    So this issue should be solved with the latest code, re-open with details if not.
