### ISSUE TITLE
bigWig Track Minimum

### ISSUE THREAD

**Issue by datbdude** [igvteam/igv.js#399]
bigWig track min option does not actually set the minimum when using loadTrack.

**Comment by jrobinso** [comment]
Could you elaborate?  It seems to be working properly.

**Comment by datbdude** [comment]
```
igv.browser.loadTrack({
          type: "wig",
          url: "bigwig/MONOCYTES.bigWig",
          name: 'Monocytes',
          color: "#ffcc00",
          min: 1
        });

```

This is an example of how I am loading the bigWig tracks. The resulting track still shows a minimum of 0. Am I misunderstanding the function of this option?

**Comment by jrobinso** [comment]
Ah,  you're setting min but not max.  That had not been tested before.   You want to set min but let max autoscale?

**Comment by datbdude** [comment]
Exactly. The maximum per viewing frame can change as the position changes. The behavior of this should continue to autoscale. However, there can be reads considered insignificant. A minimum can be used to hide these values. This would be nice to have.

**Comment by jrobinso** [comment]
I just pushed a change that should do what you want.   If min is set but not max autoscale will be used to set max.   If max is < min after autoscale nothing will be drawn for that region.

**Comment by datbdude** [comment]
Awesome, thanks! Will this show up in the nightly build or is there another way to build it?

**Comment by jrobinso** [comment]
It should be automatically updated with the "beta" url,  its triggered on a commit.

**Comment by datbdude** [comment]
Hi Jim,

Autoscale does not seem to behave correctly now. Is it defaulted to false? When I set the min to 1, the track does not load with the minimum unless autoscale is explicitly set (true or false). 

I am loading with the same code as before:
```
 igv.browser.loadTrack({
          type: "wig",
          url: "bigwig/MONOCYTES.bigWig",
          name: 'Monocytes',
          color: "#ffcc00",
          min: 1
        });
```

The maximum for the frame shows up as 1.7 instead of 1000. The peaks are being cut off even though max is not set.

**Comment by jrobinso** [comment]
This is my test track,  which is working.    Does your track work as expected if autoscale is explicitly set to true.

{
                            url: 'https://s3-us-west-2.amazonaws.com/ilmn.igv-test/test2.bigWig',
                            min: 1,
                            name: 'Big BigWig'
                        }

Any chance you can share your bigWig?

**Comment by datbdude** [comment]
Unfortunately, I cannot share my bigWig at this time. 

The track seems to work as expected when I query for a locus or gene, but when I drag the frame out so that it loads the next range, the maximum remains the same. This happens even when the maximum is dragged out of frame. Querying again using the search bar will reset the range to the correct values.

This leads me to wonder if the initial locus query is throwing off the min max calculations. I am initializing the browser using the option:

```
locus: "chr15:45,002,685-45,011,357"
```

I have been using the previous stable version: 1.0.9 and the tracks load correctly. However, the tracks are not loading on page load with the beta version. I have to explicitly click the magnifying glass for the tracks to refresh and load. When the tracks do load, tracks that do not have "autoscale" set do not display correctly.

I have tried with your test track and get the following results:

![image](https://user-images.githubusercontent.com/1900546/30140138-4715fab4-9327-11e7-92e4-f18d35b10b49.png)

The first track on the page explicitly has autoscale set to false. The second is set to true. The others, including your test track, are not set at all (default).

The following is from v1.09 for reference:

![image](https://user-images.githubusercontent.com/1900546/30140196-ade01b4e-9327-11e7-81ad-b071fdc7462c.png)

**Comment by datbdude** [comment]
For now I can say that my bigWig files are generated from bedGraph files using UCSC tools. For some reason the min is set properly using your track on default autoscale, but the max does not seem to be set correctly?

**Comment by jrobinso** [comment]
OK, that's useful info.
