### ISSUE TITLE
Ruler bar needs work for multilocus view

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#403]
Shrinking the height of the rule bar has squashed labels & ruler ticks in multi-locus view.  Secondly,  the ruler just looks bad in this example.   Loci tested are  "egfr myc pten"

![screen shot 2017-09-06 at 1 03 10 pm](https://user-images.githubusercontent.com/933148/30132107-1974345e-9304-11e7-9f3c-881c5e229fd5.png)

**Comment by turner** [comment]
Fixed with commit 200d9ce020adcefd9e12c4841e8d869b2f724762
