### ISSUE TITLE
Can I embed igv.js into Shiny apps?

### ISSUE THREAD

**Issue by keqiang** [igvteam/igv.js#404]
I found [this](https://github.com/dnieuw/IGVshiny) repo but it doesn't work as the author pointed out. 

I also tried using javascript directly in Shiny but it looks like the jQuery libraries got messed up since Shiny includes jQuery already. 

I think it would be pretty useful if the user can upload bam files(or using files on the server) to Shiny and dynamically add tracks and send genes to igv.

**Comment by jrobinso** [comment]
Sorry, but what is "Shiny"?

**Comment by keqiang** [comment]
@jrobinso I'm sorry that I didn't explain it. [Shiny](https://shiny.rstudio.com/) is a web framework in R, in which you can write a web application purely in R. The reactive programming concepts it's using is very convenient for programmers to write interactive web applications. A lot of js libraries have their own widgets available in Shiny framework such as [plotly](https://plot.ly/r/).

[This repo](https://github.com/dnieuw/IGVshiny) is trying to convert igv.js to a Shiny widget but the author stopped his work since the incompatibility.

**Comment by jrobinso** [comment]
OK, thanks for the clarification.   Obviously, we don't have a widget,  but would be open to a pull request.    From the comment, it looks like the author was unable to implement support for the Range header.

**Comment by sgratzl** [comment]
one question is how to deal with data for the tracks. IGV.js can download data from a remote server but it is possible to locally provide the data?

**Comment by keqiang** [comment]
@sgratzl For a lot of Shiny element, there is a server side render function, such as datatable, so it will be able to use the data reside on your own server(locally). I feel it's more useful if the IGV.js can be controlled by the server side code, including loading data that's on the server. However, I'm not very familiar how to implement these functions, I will check out datatable or plotly to see how these logics are implemented.

**Comment by sgratzl** [comment]
loading and converting the data is quite easy. I also did in e.g., https://github.com/Caleydo/lineup_htmlwidget . My question was more how to put data that is stored in the R workspace as tracks in IGV.js? taking a look at the configuration, you can only link to external sites. see also #391

**Comment by jrobinso** [comment]
What do you mean by "local"?

**Comment by jrobinso** [comment]
You need a URL but it doesn't need to be remote,  it can be local to your
webserver.

**Comment by keqiang** [comment]
@jrobinso I think he is talking about loading the real data directly into the IGV because the data is already loaded into R session(running on the server). Like what he did for lineup, the data mtcars are converted to a data format that can be directly used for the htmlwidget. 

If we just specify an URL, it might not work because the data might not be accessible by the client using an URL, say, it might be in a user's home folder. Another thing is event the data is accessible, the server is not necessary to support range request.

**Comment by jrobinso** [comment]
@keqiang I'm not following you, but that's not surprising as I'm not familiar with the tools you are referencing.    When you say "loading .... directly" do you mean as an encoded blob in the page itself?     @sgratzl Where is R running,  on a server or on the client?   Do you want to generate a webpage with the data statically defined, for example as json objects?  #391 is really not about loading directly, it is about defining a webservice API at runtime with a json object.

**Comment by jrobinso** [comment]
Closing due to lack of response
