### ISSUE TITLE
Bug: Range Increments on query

### ISSUE THREAD

**Issue by datbdude** [igvteam/igv.js#405]
![image](https://user-images.githubusercontent.com/1900546/30189630-0a395da2-93ea-11e7-8a31-c3f1862f886b.png)

The start of the range increments by 1 each time the question mark is clicked. This issue is showing up on the beta version and not 1.09

**Comment by turner** [comment]
I think you are referring to the magnifying glass icon. Yes?

**Comment by turner** [comment]
Fixed.
