### ISSUE TITLE
disable call home feature

### ISSUE THREAD

**Issue by sgratzl** [igvteam/igv.js#409]
why does igv.js automatically makes the following AJAX call?

https://data.broadinstitute.org/igv/projects/current/counter_igvjs.php?version=beta

**Comment by jrobinso** [comment]
That's an anonymous usage count.  Without it, and without healthy numbers,  no funding and no igv.js.

**Comment by jrobinso** [comment]
You can of course comment it out,  but please don't without a good reason.
