### ISSUE TITLE
Dropdown list of chromosomes

### ISSUE THREAD

**Issue by MichielVanBel** [igvteam/igv.js#426]
Maybe I've totally missed it, but I really don't see in the documentation (https://github.com/igvteam/igv.js/wiki/Browser) how you can get a drop-down list for the available chromosomes in the reference genome (as is available in IGV).

One would expect that this is a configuration option set either globally (such as the showRuler and showNavigation) or as an option for the reference genome. 

I searched a bit in the examples, but also here I don't see anything that could indicate how to achieve this. 

So - if I am right and this option is not available right now - is this something that could be added in the future?

**Comment by jrobinso** [comment]
Could you describe your use case a little more?  igv.js is not itself a
full browser application, it is a component designed to be embedded in
pages for displaying user-hosted data.

**Comment by MichielVanBel** [comment]
we have a set of expression files (e.g. BAM files) that we offer to the end-user for Arabidopsis thaliana. Users can end-up directly at the correct position (because the correct location is given), or through the search-option. 

But some users rather just want to browse the data apparently, and as such they want to switch between chromosomes. The issue here is that chromosome naming is non-standard between species ("Chr1" vs "1" vs "Chromosome1"). And thus if they just type in Chromosome1 in the navigation-textfield, it doesn't work. And this also assumes they know how many chromosomes there are etc...

All in all, it seems to me that, since the reference genome is loaded through an indexed fasta file, it would be pretty straightforward to generate a drop-down menu for the chromosomes in the reference genome, no?

**Comment by jrobinso** [comment]
Ahh, yes, understood.  Yes, we can add that.   To be honest I misread the first time as "list of available genomes".

**Comment by jrobinso** [comment]
Note:  This should be an optional widget,  default off, and probably to the left of the locus box.  The names come from genome.chromosomeNames.

**Comment by turner** [comment]
got it

**Comment by jrobinso** [comment]
This is available now in igv-beta.   To enable it set  
"showChromosomeWidget: true"
in the browser config.   See dev/igv-dev.html
