### ISSUE TITLE
igv.js beta (upcoming 1.0.10?) and region selection via mouse-drag

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#428]
Lots to like about the UI in the current beta.  Thanks for all the improvements.

One difficulty I am having:  mouse-dragging a region  in the chromosomal location bar (just below the cytoband) does not always work for me.   Sometimes my mouse-clicks, used to initiate the drag, do not register.  Other times, the selection shading appears later in the dragging process: that initial mouse-down event did in fact register, but the selection shading appears only on mouse up.

I convinced myself for a while that only the lower half of the chromosomal location bar was sensitive to clicks, but that does not seem to be consistently true.

I am using
````
  <script  src='https://igv.org/web/beta/igv-beta.js'></script>
  <link rel="stylesheet" type="text/css" href="https://igv.org/web/beta/igv-beta.css">
````

**Comment by jrobinso** [comment]
Thanks, we'll look into it.

**Comment by turner** [comment]
This should be fixed with commit 5eee529ca7464e25edcc75e3f3e2fa0be6edd44c

**Comment by jrobinso** [comment]
@paul-shannon  -- Could you verify that this is fixed,  and close the issue if it is?  Thanks

**Comment by paul-shannon** [comment]
works great!

**Comment by paul-shannon** [comment]
I spoke a bit too soon, sorry.
The ruler sweeper, perhaps 10% of the time, possibly only on smaller regions, hangs for 15-30 seconds, eventually responds, but then remains barely responsive to (for example) clicks on the "-" icon, zoom out.

**Comment by turner** [comment]
Paul, I pushed a change that should fix the bug. Commit 9410a0d7

**Comment by turner** [comment]
Paul, can we close this issue?

**Comment by paul-shannon** [comment]
yes, and thanks!
