### ISSUE TITLE
removeTracksByName: cannot read property "apply" of undefined

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#432]
![image](https://user-images.githubusercontent.com/2480712/31259940-7c83994c-a9ff-11e7-9940-a14fbac950b9.png)

I see this error intermittently in the javascript console.  The request is actually from R, and works most of the time:
````
      if(track.name %in% getTrackNames(trenaViz))
         removeTracksByName(trenaViz, track.name)
````
If this is not enough information to be helpful, just let me know.  I can always to recreate it the problem with a bit of javascript pasted into the js console.

**Comment by turner** [comment]
Paul,

I've run some tests and I do not see a problem with `removeTrackByName(name)`. I implemented the above `R` code in `JS` and it works fine.

Are you still seeing this?

**Comment by paul-shannon** [comment]
Thanks for looking at this -  I still see it, though only intermittently.   It's on me to track down the details.  I'll try to do so over the next week.

**Comment by jrobinso** [comment]
Might be triggered by whitespace or other special characters in the name?
Just a guess.

**Comment by turner** [comment]
I test for white space. Can we go ahead and close this issue?

**Comment by paul-shannon** [comment]
Sure, please close.   If I come up with a reproducible javascript-only example I will (if I may) reopen.

 - Paul
