### ISSUE TITLE
Support CSI index for BAM and bgzip (tabix) files

### ISSUE THREAD

**Issue by brentp** [igvteam/igv.js#435]
as far as I can tell bgzip + tabix (.tbi) index is supported. It would be nice if CSI was supported as well.

**Comment by jrobinso** [comment]
That's probably not too difficult,  I know every little about CSI.   Care to contribute some test files?

**Comment by brentp** [comment]
Happy to.
You can get them e.g. with a recentish htslib tabix from the root of this repo with:
```
tabix --csi ./test/data/tabix/TSVC.vcf.gz
tabix --csi ./test/data/bed/badbed/badbed.bed.gz
tabix --csi ./test/data/bed/brokenbed/broken_bed.bed.gz
```
I also attached an example VCF with csi index (in .zip) and a gzipped version of the TSCV one as well.
[csi-test.zip](https://github.com/igvteam/igv.js/files/1369676/csi-test.zip)

thanks!

[TSVC.vcf.gz.csi.gz](https://github.com/igvteam/igv.js/files/1369671/TSVC.vcf.gz.csi.gz)

**Comment by renyaoxiang** [comment]
I add a track in igv and errors occurred, the track options is following.
Does igv not support the gz file?
```

				{
					name: "vcf.gz",
					type: "annotation",
					format: "vcf",
					sourceType: "file",
					indexed: true,
					url: 'igv_file/DRH-M_recal.vcf.gz',
					indexURL: 'igv_file/DRH-M_recal.vcf.gz.tbi',
					displayMode: "EXPANDED"
				}
```

**Comment by jrobinso** [comment]
Yes it does.

**Comment by jrobinso** [comment]
Does your server support Range-byte requests?

**Comment by jrobinso** [comment]
Also, please open a new git issue for a new problem,  with as much details
as you can.   At a minimum this includes the igv version number,  and any
output in the javascript console.

**Comment by renyaoxiang** [comment]
Dear @jrobinso 
Thank you!

**Comment by brentp** [comment]
bump. would be great if this was supported. It ends up being similar to tabix. There's a nice reference implementation in golang here: https://github.com/biogo/hts/tree/master/csi

**Comment by jrobinso** [comment]
Yes, bumps are helpful,  a pull request would be even better.    Keep
bumping periodically,  it will happen.

**Comment by juancrescente** [comment]
I want this feature as well

**Comment by jrobinso** [comment]
@juancrescente what is your use case for the CSI index?  It shouldn't be hard to implement but it is hard to prioritize,  I would welcome a pull request for this.   Probably just requires some modifications to bamIndex.js,  both bam and tabix use the same code for this.

**Comment by juancrescente** [comment]
@jrobinso I can only index bam files from wheat genome using CSI indexes. That's why I cannot use igv with wheat data

**Comment by jrobinso** [comment]
Just pushed CSI support for tabix.   BAM support is slightly different, that will follow soon.

**Comment by juancrescente** [comment]
Nice, waiting for bam support!

**Comment by jrobinso** [comment]
CSI v1 is supported.  I can't find documentation for CSI v2.

**Comment by lpryszcz** [comment]
hi, do you need to provide .csi index? when specifying just BAM url, it fails to find it (just looking for .bai I guess)

**Comment by jrobinso** [comment]
You need to provide the indexURL in the "indexURL" field.

**Comment by jrobinso** [comment]
In general indexURLs should always be provided for all file types.   It might occasionally guess correctly but that is legacy code and not supported.   indexURLs cannot always be guessed, and it generates needless network requests in the best case.

**Comment by lpryszcz** [comment]
thank you for the clarification @jrobinso .  :)
