### ISSUE TITLE
 is there any way to show names of variants?

### ISSUE THREAD

**Issue by liub1993** [igvteam/igv.js#445]
Hi, is there any way to show names of variants? Like the features in annotation track.

Thanks for any suggestions.

**Comment by jrobinso** [comment]
Variants don't have a specific name field.  You can click on them to see the attributes available from the VCF file.

**Comment by liub1993** [comment]
OK, thanks! 

By the way, the gene name look up service is not working now...
https://portals.broadinstitute.org/webservices/igv/locus?genome=hg19&name=egfr

**Comment by jrobinso** [comment]
Thanks for the report -- service re-started
