### ISSUE TITLE
Support UCSC track hub syntax

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#46]
Track hubs are important for Encode,  and by extension Cursor

Guide to basics:  https://genome.ucsc.edu/goldenPath/help/hubQuickStart.html

Really important for understanding structure of file: https://genome.ucsc.edu/goldenPath/help/trackDb/trackDbHub.html

Example trackDB.txt file: https://www.encodeproject.org/batch_hub/searchTerm=bernstein+k562,,type=experiment/hg19/trackDb.txt

The excellent Dalliance parser by Thomas Down: https://github.com/dasmoth/dalliance/blob/master/js/thub.js

**Comment by swingingsimian** [comment]
Hi, 
Has this dropped from the development path completely? Trackhub support in IGV would be great, especially if it supported authentication for private hubs.

**Comment by jrobinso** [comment]
Nothing that is still open has been dropped completely.   I am not an
expert on track hubs,  do you know how authentication is done?

**Comment by swingingsimian** [comment]
At present I believe it is basic url user/pw auth, e.g.:
    https://user:password@site.com/file 

Not well documented, but mentioned here:
   https://groups.google.com/a/soe.ucsc.edu/forum/#!topic/genome/GrXgW24IDMA

**Comment by Parul-Kudtarkar** [comment]
Hi any updates to support data hubs 
i.e.
https://igv.org/web/test/examples/igvjs.html?genome=hg19&hub=https://www.t2depigenome.org/browser_hub/type,,Experiment|assay_title=ATAC-seq/GRCh37/trackDb.json

Thanks!

**Comment by jrobinso** [comment]
No but periodic pinging is the secret.   Thanks for the example, what would
you expect should happen with such a url?

**Comment by jrobinso** [comment]
Let me expand on my question,  do you expect all the tracks in the json to
be loaded,  or for a selection menu of some type to be created from the
tracks?

**Comment by Parul-Kudtarkar** [comment]
@jrobinso I would set a limit for example view up to 50 tracks, based on selection menu.  the classic example is UCSC genome browser track hubs - http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&hubUrl=https://vizhub.wustl.edu/VizHub/RoadmapRelease3.txt 

I am hoping for something on similar lines with embed-able browser

**Comment by jrobinso** [comment]
Right, but I think the right thing to do is create a selection menu as UCSC
does.    In this view the right place for track hubs is igv-webapp,  not
igv.js.    igv.js is just the visualization component,  it does not supply
load menus, etc.   Its a component for building web apps, its not a webapp
by itself.   Most if not all of the track in your example have
"showOnHubLoad" set to false.

So I think trackhubs should be supported by the containing app, not the viz
component.   The UCSC page you reference is analogous to igv-webapp,  the
top half === igv.js,  the track selection stuff is === igv-webapps track
load menus.
