### ISSUE TITLE
Color wig track by value

### ISSUE THREAD

**Issue by jimhavrilla** [igvteam/igv.js#464]
Hey,

I looked through the documentation and the issues for this and it seems there is no way to color a wig track by value.  Would this be simple to implement?  It would be a useful feature for my purposes.  Also, if I'm wrong and it's already implemented somewhere I'm unaware of, please set me straight.

Regards,
Jim

**Comment by jrobinso** [comment]
I'm not sure I understand the request, could you elaborate?

**Comment by jimhavrilla** [comment]
Sure. Thanks for answering so quickly.  I have a bigwig track of values ranging from 0 to 100. Say I want to color 0-90 blue, 90-95 orange, 95-99 red, and 99-100 dark red. Is there already a way to do so for a wig track automatically (that is being generated in an html file) or is it a simple task to add this feature?

**Comment by jrobinso** [comment]
Well no there isn't, and I don't know how difficult it would be.  I've never seen a wig track treated this way,  the height of the bar codes for value,  and I'm not sure it would be widely used.  

Perhaps the wig track color field could optionally be a function that you supply that would take the value and return a color.   I would have to test the impact on performance, if any,  for the 99% of users that would not use this.

**Comment by jrobinso** [comment]
I've made a note to self to investigate supporting color as a function.   Would that work for you?  You would set the color parameter to something like

color: function(wigFeature() {var value = wigFeature.value;  if(value < 90 return "blue") else.... etc

**Comment by jimhavrilla** [comment]
Yeah that sounds pretty much like what I need. My track is basically under the IgvDiv like
{
                            url: 'File.bw',
                            name: 'Name',
                            type: "wig",
                            visibilityWindow: 500000
                        }

**Comment by jrobinso** [comment]
OK,  I can't get to this right away,  but if too much time passes ping this thread again.

**Comment by jimhavrilla** [comment]
Sure thanks for giving it a look
-- 
Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jrobinso** [comment]
Example usage:  

```
                {
                    url: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneGm12878H3k4me3StdSig.bigWig',
                    name: 'ENCODE - BigWig',
                    color: function (value) {
                        var red = Math.min(255, Math.max(100, Math.round(value / 2))),
                                blue = 255 - red;
                        return "rgb(" + red + "," + blue + ",0)"
                    }
                }
```

**Comment by jrobinso** [comment]
BTW it's not necessary to provide a visibilityWindow for bigwig tracks,  they are efficient at all zoom levels.

**Comment by jimhavrilla** [comment]
thanks for implementing this btw
