### ISSUE TITLE
igv.js as NPM module (and ready to be used with webpack)

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#470]
@jrobinso The steps to take in order to build and publicly provide igv.js as a node module are all laid out (I think) in the README of 

   https://github.com/paul-shannon/igv.js.npm

When you have time, you could try that out and I could respond to your questions and suggestions for making it more clear.

Then later this week I will add (in an example/ directory) a full  working sample webapp showing how to use this igv.js npm  module with npm and webpack - both popular tools these days.

**Comment by paul-shannon** [comment]
@jrobinso  I have added a minimal  webapp to the "igv.js.npm" repo

     https://github.com/paul-shannon/igv.js.npm/tree/master/examples/simpleApp

to illustrate the use of npm and webpack with igv.js.npm.  Follow these steps:

    git clone https://github.com/paul-shannon/igv.js.npm.git
    cd igv.js.npm/examples/simpleApp
    npm init
    npm install
    webpack
     
Then open ````simpleApp.html```` in your web browser.  webpack combines and "tree shakes" the javascript needed by ````src/main.js````, creating ````dist/bundle.js```` which is the only file loaded by ````simpleApp.html````

**Comment by jrobinso** [comment]
Thanks @paul-shannon
