### ISSUE TITLE
ReferenceError: Zlib is not defined

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#471]
![image](https://user-images.githubusercontent.com/2480712/32524850-864ed888-c3d6-11e7-8349-c2f2b166c8a9.png)

@jrobinso I get this error -- today, but not yesterday -- out of the code I build from a fresh pull of ````igv.js```` followed by grunt.

I have not yet found a mistake on my end (which I expect is the problem).  Have you seen this error on your end?   It occurs when igv is attempting to load the gtf gzipped file specified in this track:

````
tracks: [
     {name: 'Gencode v24',
      url: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz",
      indexURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz.tbi",
      format: 'gtf',
      visibilityWindow: 2000000,
      displayMode: 'EXPANDED'
    }]
````

- Paul

**Comment by jrobinso** [comment]
Hi Paul,  I haven't been able to reproduce it, but did re-order some includes in the grunt file.  Could you pull and try again?   I hope to get my own NPM set-up soon for testing and maybe then can catch these before you do.

**Comment by paul-shannon** [comment]
Hi Jim,

Thanks for getting to this.   Unfortunately the Zlib error persists.  

If it’s of interest, cloning my repo (only for the minimal npm/webpack simpleApp it contains) should reproduce the error quickly:

  git clone https://github.com/paul-shannon/igv.js.npm.git 
  cd igv.js.npm/examples/simpleApp
  npm update
  webpack
  open simpleApp.html 

(I still would not be surprised if the error turns out to be my own.)

 - Paul

**Comment by jrobinso** [comment]
Thanks,  I can reproduce it now with your repo, which is most of the battle.

**Comment by jrobinso** [comment]
I'm puzzling over something.   I'm trying to update the igv.js that gets bundled,  and replaced the copy in the project route.  But webpack from the "simpleApp" directory is getting a copy from somewhere else,  specifically and older copy.

**Comment by jrobinso** [comment]
OK,  I'm stumped.   I forked your repository and renamed it slightly to avoid confusion (igv.js-npm).  I pulled and updated references to your repository -> ours.  Then I update igv.js and tried to build and run the example.   I get the error below.  It doesn't surprise me it can't find these modules,  I'm obviously missing some step.  Could you pull https://github.com/igvteam/igv.js-npm and see what I'm doing wrong?   When I can update igv.js successfully I can fix the original problem.

 webpack 3.8.1
Time: 303ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  272 kB       0  [emitted]  [big]  main
   [0] ./src/main.js 1.36 kB {0} [built]
    + 1 hidden module

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'igv.js-npm' in '/Users/jrobinso/Google Drive/projects/igv.js-npm/examples/simpleApp/src'
 @ ./src/main.js 1:10-31

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'igv.js-npm/igv.css' in '/Users/jrobinso/Google Drive/projects/igv.js-npm/examples/simpleApp/src'
 @ ./src/main.js 2:0-29

Thanks

**Comment by jrobinso** [comment]
OK,  I think I'm missing a publishing step.  Its not enough to just update igv.js in the repo and commit, correct?    I think the best course is for me to publish igv.js as an npm package,  will let you know when that's ready.

**Comment by jrobinso** [comment]
Maybe some progress, on the npm side.   Could you try using this npm package?

npm install git://github.com/igvteam/igv.js-npm.git

**Comment by jrobinso** [comment]
WRT to the "ZLib" error,  if I manually replace the igv.js contents in "bundle.js" with the latest igv.js the error goes away and it works.   So there is some problem still with the webpack creation of bundle.js, in my setup anyway.   If you are able to modify your test to use the npm install from our repo above that error should go away,  I haven't got that far in my webpack understanding.

**Comment by jrobinso** [comment]
Before publishing to NPM I suppose I should substitute the minified version of igv.js,  using the full one is useful for debugging but its big.

**Comment by jrobinso** [comment]
OK, got it.  Phew.   I've got your "simpleApp" working by using git://github.com/igvteam/igv.js-npm.git  (see package.json below).   The package is installed as module  "igv.js".    So in main.js  var igv = require('igv.js')
require('igv.js/igv.css')

package.json for simpleApp

{
  "name": "simpleapp",
  "version": "0.1.0",
  "description": "demonstrate use igv.js.npm in a minimal webapp",
  "author": "Paul Shannon",
  "main": "lib/main.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/igvteam/igv.js-npm.git"
  },
  "keywords": [
    "igv.js",
    "webpack",
    "npm"
  ],
  "files": [
    "lib/**/*.js",
    "dist/*.js"
  ],
  "scripts": {
    "clean": "rimraf dist/",
    "prepublish": "webpack",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "css-loader": "^0.28.7",
    "rimraf": "^2.6.1",
    "style-loader": "^0.19.0",
    "svg-inline-loader": "^0.8.0",
    "svg-loader": "0.0.2",
    "webpack": "^3.5.5"
  },
  "dependencies": {
      "igv.js.npm": "github:igvteam/igv.js-npm",
      "jquery": "^3.2.1"
  },
  "bugs": {
    "url": "https://github.com/paul-shannon/igv.js.npm/issues"
  },
  "homepage": "https://github.com/paul-shannon/igv.js.npm#readme",
  "license": "ISC"
}

**Comment by paul-shannon** [comment]
Looks great, Jim!  Thanks for all the extra effort you expended in getting this to work.

 - Paul

**Comment by jrobinso** [comment]
I will keep this repo (igv.js-npm) up to date,  so install from there for a
stable module.  By up-to-date I mean periodically, not on every commit.
 Also very soon I'll publish this at NPM but that will be updated only on
numbered releases.

**Comment by jrobinso** [comment]
Paul, one last change and I'll close this issue.   I changed the module package name to "igv",  rather than "igv.js".    So its require('igv') and required('igv/igv.css').   Also, its at NPM so you can install from there or our git repo.     npm install igv

**Comment by paul-shannon** [comment]
Wonderful!   Thanks, Jim.

 - Paul
