### ISSUE TITLE
Additional "color-by" options for alignment track (igv.js)

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#475]
The alignment track is missing some important color-by options,  e.g. pair orienation and insert size.  Also,  color by  "track color"  is hard to interpret,  what does that mean?  I don't think its going to mean anything to a user,  we need a better name for that.

<img width="147" alt="screen shot 2017-11-10 at 9 20 46 pm" src="https://user-images.githubusercontent.com/933148/32686621-5bcfcade-c65d-11e7-9796-4d33897c4890.png">

**Comment by Erin1147** [comment]
In your picture,there's a function ,'Sort by base'. Can I  Sort by mapping quality?

**Comment by jrobinso** [comment]
No you can't.   Even if you could,  it only sorts the alignments
intersecting a line over the click point.  This is probably not what you
want.

**Comment by Erin1147** [comment]
Ok,thank you!

**Comment by jrobinso** [comment]
Done
