### ISSUE TITLE
What the specification of index is?

### ISSUE THREAD

**Issue by renyaoxiang** [igvteam/igv.js#479]
Now, I could have the gtf, gff files shown in the igv, and still I would like to use the index of gtf, gff or bed . 
How could I get the file format of the index files ? or how could I get the index files?

**Comment by jrobinso** [comment]
Do you mean ".idx" files?  Its an htsjdk format,  but I don't think its documented.   You can browse the source code here https://github.com/samtools/htsjdk/tree/master/src/main/java/htsjdk/tribble/index.

In general I don't recommend this type of index,  bgzip + tabix is more effecient.

**Comment by renyaoxiang** [comment]
get it, thank you!
