### ISSUE TITLE
browser.loadTrack  (bed file) drops final line in version > 1.0.9

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#482]
All lines are picked up and displayed in 1.0.9, but not in the current github, npm or web/test versions.

In these later versions, the last line of the bed file appears to be dropped, and the corresponding region is not displayed.

This one should be easy to reproduce!

**Comment by jrobinso** [comment]
Does this occur with all bed files?  We might need a sample but I'll try to reproduce first.

**Comment by paul-shannon** [comment]
@jrobinso   I discovered that, if the bed file (my test file has only 4 lines) is served up by apache, all lines are rendered by igv.   If I use the webserver either in the jupyter nbserver, or (in R) the webserver provided by the httpuv package, then the last line of any bed file is dropped.

These are specialized use cases, probably quite distant from your main concerns.  But they are important to me, and since it used to work (igv.js 1.0.9), maybe I can get some advice from you on where in the igv.js source to start exploring? Could you point me to the igv.js function/s which do an http get on the bed file, and translate each line/region into rectangles on the screen?

**Comment by jrobinso** [comment]
Sure.   looks at js/feature/FeatureFileReader.  The function loadFeaturesNoIndex() (line~155) reads the contents, which are then passed to FeatureParser.parseFeatures.   The problem though is probably with the class StringDataWrapper (line 846 of featureParsers).   I will look at it when I have time, but it would be helpful if you zip and attach a problematic bed file (you have to zip it or github won't let you load it).

Do these files have a line feed after the last line?

**Comment by paul-shannon** [comment]
Thank you, Jim.

I see the problem with ALL bed files; they all include a trailing newline.  Here’s a 5 row example:




which unzips to this:

18	26860695	26860701	A	-0.131537643261254
18	26860937	26860941	B	-0.995450963731855
18	26860788	26860792	C	0.669384277425706
18	26860880	26860887	D	0.660165932495147
18	26860770	26860774	E	0.913935635704547

**Comment by jrobinso** [comment]
Well it loads fine for me,  not surprising as my server is apache.

Do this, which will help.   Load in chrome with "developer tools" on.   Click the network tab.   You'll find the http get for the bed file.   Then click on "response" to see what the server is actually sending.    I still suspect a missing line feed at the end,  but maybe not in the file itself.

**Comment by jrobinso** [comment]
I see the flaw in the logic here,  the last line won't be returned if not terminated with a line feed.  I suspect the servers that aren't working aren't returning the trailing line feed,  however you could easily verify that with chrome developer tools.    I will fix this logic when I can get to it (soon).

    StringDataWrapper.prototype.nextLine = function () {
        //return this.split(/\r\n|\n|\r/gm);
        var start = this.ptr,
            idx = this.data.indexOf('\n', start);
        this.ptr = idx + 1;
        return idx < 0 || idx === start ? undefined : this.data.substring(start, idx);
    }

**Comment by jrobinso** [comment]
Fixed in master.  Do you need me to update NPM or the npm github?

**Comment by paul-shannon** [comment]
Thanks, Jim.   I could do a fresh pull, grunt and build my own npm (“igv.js.npm”) from your github repo, and then use your npm repo when it is updated.  Both are fine by me!

 - Paul
