### ISSUE TITLE
How to build a server supporting ga4gh data for igv.js?

### ISSUE THREAD

**Issue by renyaoxiang** [igvteam/igv.js#483]
We are using igv.js to build a genome browser. How could we use a ga4gh data source? If there is some open source to build a server and support the ga4gh data? 
We use the java language, so we would like it to be written by java.  I found the opencb in github looks like a very reliable originzation and support the ga4gh schema data server. Could you supply some infos about it if you are familiar with it?

**Comment by jrobinso** [comment]
Hi,  we support the ga4gh protocol but don't supply a server so I have no information for you that you can't easily find by a web search.

**Comment by renyaoxiang** [comment]
thank you。
