### ISSUE TITLE
What file types of ga4gh schema does the igv support ?

### ISSUE THREAD

**Issue by renyaoxiang** [igvteam/igv.js#485]
I read some issue of igv.js and It seems that igv.js only support alignment and variant files if we use ga4gh schema. So does it means only the bam or vcf files is valid?
As several months pasted after that issue. What types of ga4gh schema does the igv support?

**Comment by jrobinso** [comment]
IGV supports alignments (bam) and variants (vcf) in the ga4gh scehma.

**Comment by renyaoxiang** [comment]
Dear @jrobinso 
Thank you!
