### ISSUE TITLE
Read track fails to load when changing chromosome (sharded BAMs)

### ISSUE THREAD

**Issue by mbookman** [igvteam/igv.js#490]
For a given genomic sample, we have aligned reads sharded by chromosome, such that BAM files are named `recalibrated.<chr>.bam`. We load samples from Google Cloud Storage with track information like:

      sourceType: 'gcs',
      type: 'bam',
      url: "gs://<path>/<sample-id>/recalibrated.<chr>.bam
      indexPath: "gs://<path>/<sample-id>/recalibrated.<chr>.bam.bai",
      label: 'Reads',
      visibilityWindow: 100000,
      order: 9997

If the user changes the region in the `igv-search-container` text box, everything works fine so long as the new region is on the same chromosome. If they change chromosome, then IGV doesn't display the read track.

We need some way for to either get an "on change" notification so that we can reload the page with new track information, or we need a way to provide a mapping of chromosomes to BAM files.

Thanks!

**Comment by jrobinso** [comment]
I can think of a few ugly quick solutions.   How urgent is this (timeline)?

**Comment by jrobinso** [comment]
Example use
```
{
    name: "Sharded Bam",
    type: "alignment",
    sourceType: "shardedBam",
    sources: {
        sequences: ["21", "22"],
        url: "gs://igv-bam-test/mock/recalibrated.$CHR.bam"
    }
}
```

**Comment by mbookman** [comment]
What is the correct syntax for indicating that your `shardedBam` is indexed?
Are BAI files assumed to be at the `<url>.bai`?
For example: `gs://igv-bam-test/mock/recalibrated.21.bam.bai`?

**Comment by jrobinso** [comment]
@mbookman Good question.  If you follow the <url>.bai convention you don't need to specify anything.   I just pushed an update that lets you specify the indexURL pattern if not.   I updated example  (see dev/shardedBam.html) to specify the index, even though in this case its not neccessary.  

```
                {
                    name: "Sharded Bam",
                    type: "alignment",
                    sourceType: "shardedBam",
                    sources: {
                        sequences: ["21", "22"],
                        url: "gs://igv-bam-test/mock/recalibrated.$CHR.bam",
                        indexURL: "gs://igv-bam-test/mock/recalibrated.$CHR.bam.bai"
                    }
                }
```

**Comment by mbookman** [comment]
Thanks!

**Comment by mbookman** [comment]
Hi Jim - just wanted to mention that we have tested this change and everything looks good.

Thanks again!

**Comment by jrobinso** [comment]
Great.   I also restored the right-click context menu.
