### ISSUE TITLE
Browser's "Save Image As" no longer available on BAM tracks.

### ISSUE THREAD

**Issue by mbookman** [igvteam/igv.js#491]
In the version of IGV.js that we have been testing for the next release of MSSNG, we find that we can no longer "right-click" on the BAM tracks and "Save Image". Instead of the browser's pop-up, we now get a pop-up menu that says "Sort by base".

Saving the pileup image was really useful. Is there a way to restore this functionality? I'm wondering if an explicit "Save Image" option can be added to the `igv.BAMTrack.prototype.popupMenuItemList`.

**Comment by jrobinso** [comment]
We need to have another trigger for our context-specific menu and leave the right-click menu to the browser.  This will resolve the issue.
