### ISSUE TITLE
This wiki page does not work 'Genomic State Object'

### ISSUE THREAD

**Issue by renyaoxiang** [igvteam/igv.js#492]
I would like to use a latest version.
And I did the following config, it does not work. there is something wrong I think.
https://github.com/igvteam/igv.js/wiki/Genomic-State-Object

**Comment by jrobinso** [comment]
Hi @renyaoxiang .    Thank you for your reports,  but if you want help you are going to have to provide complete details of what you did and what went wrong.   An example test case is also helpful.

**Comment by jrobinso** [comment]
Also,  the page referenced is documentation of code,  its not an API so there is no way really that it "does not work".   If you want to reopen this please provide detailed specifics.

**Comment by renyaoxiang** [comment]
Dear @jrobinso
Thanks, It did make no error or warning.
Now I have suspend the work and would like to have a try some day.
