### ISSUE TITLE
Display bigwig value on hover

### ISSUE THREAD

**Issue by arq5x** [igvteam/igv.js#495]
Hi Jim and team,

Would it be possible to make igv.js display the value for a BW or BEDGRAPH interval when one hovers over a particular interval? This would be very useful for the constrained coding interval (CCR) browser we have developed using this awesome framework.

https://s3.us-east-2.amazonaws.com/ccrs/ccr.html

Aaron

**Comment by jrobinso** [comment]
Hi Aaron,

Yes, but we need to find a good hover library.   Our attention is focused
on some other things now but ping this ticket if it lingers too long.

Hover text is useful for some tracks,  and really annoying for others (e.g.
bams).   We have been implementing "click popup" for many tracks,  but not
wig type tracks are not supported yet.   Would that be useful as an interim
solution (click to see value)?

Thanks for the pointer to the CCR browser, it looks really nice.

Jim

**Comment by arq5x** [comment]
Click pop up would actually be preferred over hover in my opinion!
