### ISSUE TITLE
vcf track: "data.split" is not a function

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#498]
Using igv.js built from a Dec 8th pull, and using this track 

                {name: "chr7 sub variants",
                  format: "vcf",
                  url: "http://trena.systemsbiology.net/misc/chr7-sub.vcf.gz",
                  indexURL:  "http://trena.systemsbiology.net/misc/chr7-sub.vcf.gz.tbi",
                  type: "variant"
                  },

![image](https://user-images.githubusercontent.com/2480712/33839977-7e84110e-de48-11e7-86a2-c625e5de1e8f.png)
No diagnostics appear in the console.
Any ideas?

**Comment by jimhavrilla** [comment]
Also getting this error, even in version 1.0.9.
I am identifying the track like so:
{
                            name: "ClinVar functional pathogenics",
                            type: "variant",
                            url: "https://s3.us-east-2.amazonaws.com/ccrs/tracks/clinvar-functional-pathogenics.vcf.gz",
                            indexURL: "https://s3.us-east-2.amazonaws.com/ccrs/tracks/clinvar-functional-pathogenics.vcf.gz.tbi",
                            order: 4,
                            visibilityWindow: 500000
                        }
I have also tried adding file: "vcf", removing file and type, and even trying the 1KG example in your dev-html file did not work for me either.

**Comment by jrobinso** [comment]
Jim, are CORS headers enabled on those s3 buckets?

**Comment by jrobinso** [comment]
@jimhavrilla See the CORS section here:  https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements.   There is an example S3 rule set (the one we use).

**Comment by jimhavrilla** [comment]
Is this necessary for all tracks or just VCF?  Because without me setting up CORS header configuration, literally all other tracks render just fine.

**Comment by paul-shannon** [comment]
CORS headers seem to be shipshape at trena.systemsbiology.org, leading me to suspect that they are not the cause of the vcf track problem.

 - Paul

**Comment by jimhavrilla** [comment]
I would have to agree.

**Comment by jrobinso** [comment]
CORS headers always necessary for any trackf your page is on a different host than the data.   Where is the page hosted?   I tried testing your track and it failed because the CORS headers weren't present.   Could you post a track config from the same server that is working?   @paul-shannon I'm not sure this is the same problem as yours.

**Comment by jimhavrilla** [comment]
I'm pretty sure it's the same issue.  Trust me that it renders fine: https://s3.us-east-2.amazonaws.com/ccrs/ccr.html

**Comment by jimhavrilla** [comment]
That's with the VCF error.  If I remove the VCF track it works just fine.  You probably aren't able to read the S3 file the way you need to on your end but the HTML is also run in the S3 bucket, and I have had no issues with any track but the VCF track.

**Comment by jimhavrilla** [comment]
@jrobinso Can you see that all other tracks are rendering fine?  Since the page is on the same host as the data, CORS headers are not an issue.

**Comment by jrobinso** [comment]
If you see this issue in 1.0.9 it is definitely not the same.   I'm am
working on a fix for Paul's issue, then I'll turn my attention to yours.
 Its a little harder for me to test without the CORS headers but I'll try
debugging from your page.

**Comment by jimhavrilla** [comment]
Well if you fix Paul's issue I have a pretty strong feeling you'll fix mine.  So I am happy to wait for that.

**Comment by jrobinso** [comment]
OK, the bug affecting Paul was introduced a few weeks ago in master.   I
will have a push within a few hours.

**Comment by jimhavrilla** [comment]
Cool will this fix also be here: https://igv.org/web/test/dist/igv.js

**Comment by jrobinso** [comment]
Yes, that automatically builds from commits to master.

**Comment by jimhavrilla** [comment]
Great, I figured as much, but good to be sure.

**Comment by jimhavrilla** [comment]
So, I checked my S3 bucket and my CORS configuration looks like your example.  I made it exactly the same just to be sure, and no difference for me.  Did this commit fix your issue @paul-shannon?
![image](https://user-images.githubusercontent.com/6568964/33856648-0360ef5e-de86-11e7-9bee-320e22cbc5e6.png)

**Comment by jrobinso** [comment]
@jimhavrilla I'm looking at your problem now, its unrelated to Paul's.  I think you said this was also a problem with 1.0.9, correct?  There's something different about the call sets (genotypes) in these VCFs,  stay tuned.

**Comment by jimhavrilla** [comment]
I don't have genotype data in the file if that's what you mean.  And on going back, I made a mistake about 1.0.9.  It works there, I just forgot to use the 1.0.9 css when I threw in the 1.0.9 js.  My mistake entirely.  Still does not work in the test dist though.

**Comment by paul-shannon** [comment]
The fix works for me, pulled fresh from https://github.com/igvteam/igv.js followed by grunt.

Thanks, Jim!

**Comment by jrobinso** [comment]
@jimhavrilla Should be fixed now.  There was a bug introduced that affected VCFs without genotypes.  I had forgotten that was possible,  I've added one now to my test files (vcf with no genotypes).

**Comment by jimhavrilla** [comment]
Ok, it works now.  Thanks.  That explains why the data.split error kept popping up

**Comment by hakanEdico** [comment]
Is there a stable build with this fix? I have been using the beta build because 1.0.9 does not work for me. However, the beta build has this issue.

**Comment by MariaNattestad** [comment]
I'm using the npm version and getting the same "TypeError: data.split is not a function" error, also just for VCF files while all other tracks work fine. Has the fix made its way to the version available in NPM? (I believe that's also the beta version)

**Comment by jrobinso** [comment]
The latest beta version is not available yet in NPM.   Is there a reason
you need to use NPM?  The latest version can be included with a single
javascript file,  no other dependencies,  just this

<script src="https://igv.org/web/release/2.0.0-beta3/dist/igv.min.js
"></script>

**Comment by MariaNattestad** [comment]
I was getting other errors from doing that, perhaps because it's all within a larger React/Redux/Webpack/Babel etc. codebase, so there is a certain amount of compilation and processes that just make it much more palatable to use npm.

**Comment by MariaNattestad** [comment]
Within my node_modules directory, if I replace the npm igv.min.js file with the dist file you just linked to, it works perfectly. That's not a solution for our automated build process of course, but a quick replacement in this repo https://github.com/igvteam/igv.js-npm, would do the trick. Should I submit a pull request?

**Comment by jrobinso** [comment]
Yes, you can submit a pull request.   I will look at it as soon as
possible,  I'm traveling now.
