### ISSUE TITLE
With latest test dist, cannot search with Gene Symbol (no trouble with 1.0.9)

### ISSUE THREAD

**Issue by jimhavrilla** [igvteam/igv.js#501]
<img width="1179" alt="screen shot 2017-12-14 at 3 34 38 am" src="https://user-images.githubusercontent.com/6568964/33987902-c6741516-e07f-11e7-8166-86afa70b641a.png">
<img width="1179" alt="screen shot 2017-12-14 at 3 34 38 am" src="https://user-images.githubusercontent.com/6568964/33987930-d9c312b6-e07f-11e7-9b4f-f6435f11f6e6.png">
Note how this works in 1.0.9 above.
If I use the latest dist:
<img width="1179" alt="screen shot 2017-12-14 at 3 34 38 am" src="https://user-images.githubusercontent.com/6568964/33988095-744b3228-e080-11e7-88f7-cd7f7dc42773.png">

That is the error message I get when doing a gene symbol search.

**Comment by turner** [comment]
i am looking at this now

**Comment by turner** [comment]
Search is back. Fixed with commit a89738963dacf9e468ca78556395c37ec6d307a1

**Comment by jimhavrilla** [comment]
Thanks
