### ISSUE TITLE
Ability to grab locus coordinates from igvDiv object

### ISSUE THREAD

**Issue by jimhavrilla** [igvteam/igv.js#502]
It seems like the igvDiv object doesn't store the locus information (Jim has already told me it does not) but it is surprising there is no way to get it because the information has to be sent somewhere to perform a search.  If there is a way that I can get that information I can solve another issue we have which is updating the URL to reflect a new search.  I know this may not be a priority for you but it is something I would personally appreciate.

**Comment by jrobinso** [comment]
So to be clear you only want notified when the user types a symbol or
chr:start-end location in the search box?    What if they pan,  or zoom,
or use the ideogram to jump somewhere else?

Another consideration,  you can type multiple gene names into the search
box separated by spaces.

**Comment by jimhavrilla** [comment]
All of those, actually.  If there is a way I can grab the locus attribute of the igvDiv object as it updates, then I have access to all of that information, right?  
For example the way I set it up now you can type a chr:start-end or gene symbol after the hash like so: https://s3.us-east-2.amazonaws.com/ccrs/ccr.html#ACTN1 and it will parse after the hash and put it into the locus attribute when it creates the igvDiv object.  However, as I know you're aware I don't think there is a way for me to grab that attribute as it changes from that object.  That should solve my problems.  As an example, the class igv-windowsizepanel-content-div 

    <div class="igv-windowsizepanel-content-div">107 kb</div>
updates the window size in realtime and I can access _that_ variable as I zoom in or out or change the search coordinates.  If I could do the same and have access to what is written in the search bar in real time that would be great.

**Comment by jimhavrilla** [comment]
By the way, that is really cool about putting multiple gene names in the search box.  How does that get formatted when it is stored in the locus attribute?  Maybe I can also make that parsable from the URL.

**Comment by jrobinso** [comment]
RE the locus attributes,  percent-encoding should work.

**Comment by jimhavrilla** [comment]
I think I may not be explaining what I meant very well.  When I create an igvDiv object like so:

    <script type="text/javascript">
    $(document).ready(function () {

        var div = $("#igvDiv")[0],
                options = {
                    showNavigation: true,
                    showIdeogram: true,
                    showRuler: true,
                    reference: {
                        id: "hg19"
                    },
                    genome: "hg19",
                    locus: locus,
I can pass a variable to the locus attribute in the form "chr20:123-456789" or "KCNQ2".  I was wondering how it would be formatted in this case to allow two genes by default.

**Comment by jrobinso** [comment]
Did you try 'chr20:123-456789 KCNQ2'?   Separated by space?

**Comment by jimhavrilla** [comment]
Yes, it does not work I get an error reading it as one string saying locus unrecognized.  However when I try that in the search bar it works just fine as you can see:
![screen shot 2017-12-15 at 2 29 17 pm](https://user-images.githubusercontent.com/6568964/34061207-6693b7f2-e1a4-11e7-8dda-bc5f32dc27f3.png)

**Comment by jrobinso** [comment]
Sorry, I was mistaken.  Use an array, example

locus: ['egfr', 'myc', 'pten']

**Comment by jimhavrilla** [comment]
Thanks. I think I can find a workaround to allow that through the URL
automatically
-- 
Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jimhavrilla** [comment]
By the way, now if I use more than one locus in an array as the default locus attribute, the initial loading works but as it looks the other tracks the title for the second locus seems to disappear for some reason.  If I type two in after, even the same two, it works just fine.  Not a huge bug I would imagine, and I probably won't default to that anyway, just thought you should know.

**Comment by jimhavrilla** [comment]
Test dist gene search is broken again.  Any chance we can put out a stable release after the fix?

**Comment by jrobinso** [comment]
I'll look into it,  but test is just that.   If you want a stable release
use "beta".

**Comment by jimhavrilla** [comment]
Seems like it was fixed. And thanks.
-- 
Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jrobinso** [comment]
I'm not sure what problem you were having.    The whole-genome view is work
in progress,  I removed the initial setting of "all" in the test.html locus
property.

The multi-locus view is also a work in progress, not all track types are
done yet.  I can't reproduce the bug you reported though.    If it
continues to occur open a new ticket, if the report is buried in this one
it will be forgotten.
