### ISSUE TITLE
How to hide some aberrations from Pileup?

### ISSUE THREAD

**Issue by kzoabi** [igvteam/igv.js#509]
Hi,
I will give IGV.js a filtered variants as a result it will **show part of the variants** on the browser viewer.
How can I use browser viewer to show only relevant aberrations on the BAM alignments (Pileup), I mean aberrations that specific to the variants I would like to show, and hide or remove the irrelevant?
![image](https://user-images.githubusercontent.com/3586425/34467409-a6f2506c-eef9-11e7-9d99-1d3073721b6e.png)

Thanks,
Khaled

**Comment by jrobinso** [comment]
Hi,  you can't.

**Comment by jrobinso** [comment]
I've opened a related issue,  which you can follow here #513
