### ISSUE TITLE
Support IGV desktop style url links and session files

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#511]
This will ease the migration path for website developers.

**Comment by ausinha** [comment]
How do you plan to support saving a session?

Will it be similar to XML file of the Desktop version? Since web applications may have their own way of saving users' stuff, there could be an API call to save session, which will generate a json object, which can be used to regenerate the browser stat.

**Comment by jrobinso** [comment]
It will be json,  and in fact the desktop will be moving to json.    The
json will be close to or identical in form to the initial config object.

**Comment by jrobinso** [comment]
A sessionURL=<igv session.xml> parameter in the URL works now if queryParameters=true is set in the browser config.   There is an api to load and save sessions,  it is the responsibility of the enclosing page to provide a UI for this.   See igv.org/web/app  for an example.    I'm leaving this open until all options are supported,  and documented.

**Comment by serverhorror** [comment]
We're very much interested in [Load Files with HTML Links (IGV Desktop Documentation)](https://software.broadinstitute.org/software/igv/ControlIGV#node-68) as well.

There are quite a few integrations that use this pattern at our place and we can't quite find a way to do this. I guess this ticket describes what we would like to achieve.

**Comment by jrobinso** [comment]
@serverhorror All or nearly all links that work with the desktop will work with igv.js.   If I have missed any I will add them.   Have a look at  https://igv.org/web/release/2.5.2/examples/igv-links.html.   These use the embedded igv.js here:  https://github.com/igvteam/igv.js/blob/master/examples/igvjs.html.   Note "queryParametersSupported: true" in the config object.

**Comment by serverhorror** [comment]
Would "I love you!" be too much?
How did I miss that?

Sorry for the noise. Thank you so much!

**Comment by jrobinso** [comment]
Ha!  Well I don't think many people know this actually, we are not the best at getting the word out sometimes.   Open tickets if you run into issues.
