### ISSUE TITLE
igv.alert is undefined 

### ISSUE THREAD

**Issue by hakanEdico** [igvteam/igv.js#514]
IGV.js version 1.09 

Error: igv.alert is undefined
igv.presentAlert igv-1.0.9.js:15155:9

I have included all of the dependencies listed here: https://github.com/igvteam/igv.js/wiki/Dependencies

Code to reproduce (I pass in a local path to a bam/bai file): 
Sorry for formatting, don't know how to fix. 

`function createIgvBrowser(bam, bamIndex) {
    var igvContainer = $('#igv-container');
    var options = {
        showNavigation: true,
        showRuler: true,
        tracks: [ 
            { 
                name: 'Genes',
                type: 'annotation',
                format: 'bed', 
                sourceType: 'file', 
                url: 'https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz',
                indexURL: 'https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz.tbi',
                order: Number.MAX_VALUE,
                visibilityWindow: 300000000,
                contentType: 'text/plain',
                displayMode: 'EXPANDED'                                
            },
            {
                url: bam, 
                indexURL: bamIndex
            }
        ]
    };
    igv.createBrowser(igvContainer, options)
}
`

**Comment by jrobinso** [comment]
The presentAlert message should be fixed in snapshot and beta builds, as
well as the master branch.

You cannot use local file paths,  is that what you mean by "local path"?

**Comment by hakanEdico** [comment]
No sorry that wasn't clear, they are URLs. 

So I should use a beta build? Any stable one you recommend?

**Comment by jrobinso** [comment]
The beta build is stable,  the snapshot build is the most up-to-date

**Comment by hakanEdico** [comment]
@jrobinso thank you!
