### ISSUE TITLE
When is the next formal version will be released?

### ISSUE THREAD

**Issue by slevkor** [igvteam/igv.js#517]
Hi @jrobinso
the feature im using was solved here: igvteam/igv.js#391
currently i downloaded and compiled the git repository because the formal release version is older.
do you know when will the next formal version will be released and will it contain the change?

Thanks
Lev

**Comment by jrobinso** [comment]
No ETA,  but within the next 2 months.  You can use the beta in the
meantime, it is stable (not automatically built).
