### ISSUE TITLE
showing 'variant' track from JSON 

### ISSUE THREAD

**Issue by slevkor** [igvteam/igv.js#518]
Hello @jrobinso 
Im using your feature of getting track from api - with json response , it looks like that:
    {
        name: 'UrlTry',
        type: 'seg',
        sourceType: 'custom',
        displayMode: 'EXPANDED',
        source: {
          url: '/genomeViewer/getJson/?chr=$CHR&start=$START&end=$END',
          method: 'GET',
          parser : JSON.parse
         }
    }
and the JSON data format that returns is 
    [
       {
      "sample": "TCGA-OR-A5J1-01",
      "chr": "1",
      "start": 3218610,
      "end": 8644007,
      "numProbes": 3279,
      "value": 0.0315
    },
........
   ]
and it works well :)
(suggest adding this to the wiki - i can help if needed)

now what im trying to achieve is showing a 'variant' track,
i tried switching type:'seg' to type:'variant' and returning this format: 
[
    {
      "id":"id1",
      "chrom":"1",
      "pos":"69232",
      "ref":"C",
      "alt":"A",
      "lab_class":"Pathogenic",
      "lab_freq":"0.01"
    }, ...
]

found in [#391](https://github.com/igvteam/igv.js/issues/391)
but it doesn't work. 
do you know how can i solve this?

**Comment by jrobinso** [comment]
Sorry for the delayed response, this fell through a crack.  The variant track type is specifically for VCF files,  you would have to implement a VCF record (complex).     There is no track type that can display the record you show as is.   The closest would be track type 'annotation',  but you would need to make some changes

"chrom" -> "chr",
"pos" -> "start"

Also, the "start" value should be an integer, not a string, and it is "zero" based.   So the value for the example record would be  69231.  You might keep the "pos" column for popup text and add a new "start" property.

I am working on support for generic formats,  but its not quite ready.   I'm targetting 2.1 for that.
