### ISSUE TITLE
Problem using WigTrack

### ISSUE THREAD

**Issue by xirect** [igvteam/igv.js#519]
Whenever I try to make a new track with wig-format using variableStep and display it, it says TypeError: wig is undefined. Been searching for a while, can't seem to find a fix. Anybody got a clue?

**Comment by xirect** [comment]
I tried to change the format to a .bigwig format, which now gives an RangeError...
RangeError: argument 1 accesses an index that is out of range.

**Comment by xirect** [comment]
Going back to using the wig format and reducing the filesize, it somehow started to work, how big can the .wig files be? The full file still gives the errors...

**Comment by jrobinso** [comment]
Where do you see the errors,  in the wigToBigWig conversion or after
creating the bigwig?  Can you use the bigwig with with UCSC command line
tools?

There is no maximum size for a wig file,  but the entire file has to be
loaded into memory so things will get very slow if its very large and you
do not convert it to bigwig.
