### ISSUE TITLE
igv-beta.js - typing any chrX locus into the search bar results in "Unrecognized locus" error 

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#522]
This occurs on hg19 and hg38 

![image](https://user-images.githubusercontent.com/6240170/36177306-3e4022cc-10e3-11e8-8e01-f2b0fa63991c.png)

**Comment by paul-shannon** [comment]
Perhaps related?  https://github.com/igvteam/igv.js/issues/507

If so, this is fixed in the latest code from the github repo.
