### ISSUE TITLE
Maybe reference event callbacks in the Wiki?

### ISSUE THREAD

**Issue by andreyto** [igvteam/igv.js#526]
Their very existence can currently only be discovered by browsing the examples directory and the doc directory in the repo, although they already work in the current release (1.0.9). The HTML file from the doc directory is not linked from Wiki or README.

**Comment by slevkor** [comment]
I also suggest adding more events:
currently there are - 'trackremoved' / 'locuschange' / 'trackdrag' / 'trackdragend' / 'trackclick'
maybe also adding 'trackloaded' (when spinner ends)

**Comment by jrobinso** [comment]
Yes, we agree these should be documented.  They were contributed and have been considered experimental.   WRT "trackloaded",  that is tricky,  adding a track and loading data are separate operations.  In particular loading (spinny) is asynchronous and can happen multiple times as needed in the case of indexed files.  If a visibility window is set its possible to add a track and never load data.   "trackadded" could be useful.

**Comment by ausinha** [comment]
@slevkor Could you please share how you use trackdragend or locuschange?

**Comment by jrobinso** [comment]
added to wiki
