### ISSUE TITLE
Is there a way to use this on mobile devices? (Scrolling)

### ISSUE THREAD

**Issue by vyx-rohan-jyoti** [igvteam/igv.js#528]
In laptop/desktop browsers, moving the position is done by using cursor clicking and dragging left and right.

However, this doesnt work on touch interfaces. For example, I tried using on my iPad Pro, and could not move the reads left or right. Is there a way to accomplish this?

**Comment by jrobinso** [comment]
I am working on touch support.

**Comment by jrobinso** [comment]
Some touch support is implemented.  You can scroll and pan by touch-dragging.  Taps and double taps work.   Pinch zoom is not implemented, and probably won't be,  as it gets complex to infer what the user wants to do.
