### ISSUE TITLE
bed tracks confused after zooming out

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#530]
Using a build based on github pull just yesterday, I see that two easily distinguished tracks become two identical tracks after zooming out.  Note also that zooming out changes the order of the two green tracks.

I think this is a new problem, appearing in the last week or so.

  - Paul

![image](https://user-images.githubusercontent.com/2480712/36571418-683eaa62-17eb-11e8-9a0a-cd86671c9f6c.png)

after zooming

![image](https://user-images.githubusercontent.com/2480712/36571435-76c90f78-17eb-11e8-941e-4d535f5175c1.png)

**Comment by jrobinso** [comment]
Could you zip up a test case, or at least the 2 bed tracks?  Thanks.

**Comment by paul-shannon** [comment]
Jim,

You're right - no change of order.

Here's a tar.gz file containing two short bed files.  Or I should say, "bed" files.  I send these from R and have found (until possibly today) that igv.js makes good tracks out of even 3-column data.frames.  

[bed.tar.gz](https://github.com/igvteam/igv.js/files/1750051/bed.tar.gz)

**Comment by jrobinso** [comment]
I can't seem to reproduce it with those files.    I loaded them then jumped directly to  3:2,569,257-2,572,495.   Then I zoomed out with the "-" button a number of clicks.    Did you reproduce it with those files exactly?   Can you give me any more hints or instructions?

**Comment by paul-shannon** [comment]
Those are the exact files - temporary files written in R, their names then sent to javascript, read and displayed by this js function, using the http server builtin to the websocket library I use, httpuv.
Is there any chance that the track I create is reloaded on a zoom out?  I lazily use the same name "tmp.bed" - though I will experiment now, using a randomized temporary bed file name.


````
function addBedTrackFromDataFrame(msg)
{
   var self = this;
   checkSignature(self, "addBedTrackFromDataFrame")

   var trackName = msg.payload.name;
   var bedFileName = msg.payload.bedFileName;
   var displayMode = msg.payload.displayMode;
   var color = msg.payload.color;
   var trackHeight = msg.payload.trackHeight;

   var url = window.location.href + "?" + bedFileName;

   var config = {format: "bed",
                 name: trackName,
                 url: url,
                 indexed:false,
                 displayMode: displayMode,
                 sourceType: "file",
                 color: color,
		 height: trackHeight,
                 type: "annotation"};

   console.log(JSON.stringify(config));
   self.igvBrowser.loadTrack(config);

   self.hub.send({cmd: msg.callback, status: "success", callback: "", payload: ""});
}
````

**Comment by jrobinso** [comment]
Yes, tracks can be re-loaded on zoom out,  although this should not happen with a non-indexed file since it would have all the data for the wider view from the initial load.    So that might be a bug, of sorts,  i.e. a needless reload.     That's a good hint.

**Comment by jrobinso** [comment]
BTW,  for generated static data we have added support for "data:" urls,  which encodes all the data for the track in a uuencoded blob in the page itself.   No file loads.   This is not documented,  but will be.     That might be of interest, or might not.

**Comment by jrobinso** [comment]
I can confirm that data for track is being loaded, which is a performance bug (but not a logical bug).  So there is a performance flaw on my side,  and a logical flaw on yours.   You should use distinct names because any indexed file type can reload on change of view,  it only loads what's needed.   I will fix the performance bug here,  it was a good catch.

**Comment by jrobinso** [comment]
Paul, this should be resolved now.  However, I do recommend a unique name for each track.
