### ISSUE TITLE
Network requests are made whenever the scroll-limit is reached

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#540]
I've setup a simple example with a BAM file, and I'm observing a weird behavior: whenever I reach the limit of what is rendered, a loading indicator appears and it seems that network requests are being made to redownload the **whole** files, everytime. I'm intrigued as to why it is necessary to have those requests, considering that the data has already been downloaded.

![screenshot from 2018-03-05 11-50-42](https://user-images.githubusercontent.com/1423607/36988401-c9e5b7a4-206c-11e8-9671-58a381deeb06.png)

Here is my steup:
```js
const div = document.querySelector('#igvDiv')

const options = {
  reference: {
    id: "hg19"
  },
  genome: "hg19",
  locus: "chr8:128,747,267-128,754,546",
  tracks: [
    {
      name: "Genes",
      type: "annotation",
      format: "bed",
      sourceType: "file",
      url: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz",
      indexURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/refGene.hg19.bed.gz.tbi",
      order: Number.MAX_VALUE,
      visibilityWindow: 300000000,
      displayMode: "EXPANDED"
    }, {
      url: 'http://localhost:5000/file.bam',
      name: 'Brain (BodyMap)'
    }
  ]
};

igv.createBrowser(div, options);
```

**Comment by romgrk** [comment]
I just noticed that the requests are made with the `Range: ...` header, even when it's not accepted by the other server, which explains this behavior.

**Comment by jrobinso** [comment]
Range header support is required.   You should have seen an error if the
other server did not respond with a 206 code.    Only the data in view is
requested,  when you move out of range it requests more data.   If it tried
to download an entire BAM file of typical length it would take several
hours.
