### ISSUE TITLE
React integration of IGV.js

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#543]
Hi,

I've integrated the IGV.js browser in a React application (with most of propTypes validation), I'm leaving a link to it here so anyone can re-use it. Might be interesting to mention it on the wiki:

https://gist.github.com/romgrk/87266e7fb0a6ed9058f25a8ed5375c23

Example usage:
```jsx
<IGVBrowser
  reference={{ id: 'hg19' }}
  locus='chr8:128,747,267-128,754,546'
  tracks={[
    {
      name: 'file',
      url: 'http://localhost:5000/file2.bam'
    }
  ]}
  showGenes={true}
/>
```

The `showGenes` options will add a genes track at the end of the list of tracks.

**Comment by jrobinso** [comment]
Yes thanks,  and I'll reconcile the doc with the examples.

**Comment by jrobinso** [comment]
@romgrk Can I still reference this example?   I also have examples for using require.js and ES6 imports.

**Comment by eweitz** [comment]
@jrobinso The gist linked above requires importing igv.js via script tag, which is rare in React apps.

The minimal example in the igv.js-React mashup in https://github.com/eweitz/igv.js-react, specifically https://github.com/eweitz/igv.js-react/blob/master/src/App.js#L15, is intended as a way to get React developers up and running with igv.js in a way that is familiar and conventional to their framework.  For example, it uses ES6 imports, is trivially runnable with standard React scaffolding, etc.  That said, my integration is quite basic.

Ideally, I think a React integration example would have the feature-richness of @romgrk's gist, with the structure of [eweitz/igv.js-react]( https://github.com/eweitz/igv.js-react).

**Comment by turner** [comment]
Neat. I like.

**Comment by romgrk** [comment]
Hey, my gist is MIT and you can reference anything without restriction.

I agree with @eweitz, script import is not idiomatic react. If you wish to make it idiomatic again, just add the following line at the top of the gist:
```js
import igv from 'xxxx';
```

**Comment by jrobinso** [comment]
@turner Nothing to do here, but this might be useful for reactifying IGV-web.

**Comment by jrobinso** [comment]
This was an interesting discussion but I'm not sure why the issue is till open.

**Comment by ChuanyiZ** [comment]
Just want to cross-ref to my [gist](https://gist.github.com/ChuanyiZ/215d1ea23b4828a0036387ee0c8c6da5) of how to implement this as a function component in newer react. Also mentioned in https://github.com/igvteam/igv.js/issues/1591#issuecomment-1602686221 .
