### ISSUE TITLE
some problems with bam track

### ISSUE THREAD

**Issue by desnar** [igvteam/igv.js#544]
Hi, 
    I find some problems when using the igv.js

    1. the code in bamUtils.js , cant get the blockQuals by wrong slice end
    2. when try to select the read in bamTrack, one base after the read end could also be selected

**Comment by kaushik51094** [comment]
Adding to this issue - the first base of a read is showing up as undefined. While browsing through the code, i found that you're adding 1 to the genomicLocation when showing on the UI, but the read is selected for the genomicLocation itself - and this genomicLocation is 1 less than the position shown on the UI. We can bypass this by adding 1 while reading the base as well - but a proper fix would be to fix the genomicLocation sent to the popupData function. I'll be happy to raise a PR if someone can confirm that this is a valid bug, thanks!
<img width="1440" alt="igv-browser" src="https://user-images.githubusercontent.com/6662132/45532088-55024600-b810-11e8-8bb7-2b4e93d017a4.png">
![Uploading IGV-code.png…]()

**Comment by jrobinso** [comment]
I'm not sure I'm following you, but the gist I guess is an off-by-one
location.   There are 2 conventions for genomic coordinates, the zero-based
UCSC style and 1-based.   The zero-based coordinates should be used
consistently throughout the code,  1 is added whenever we present that
location to a user.

Clearly there is an error here somewhere but it is correct to add 1 to
genomic location for presentation in the UI,  and conversely subtract 1
whenever coordinates are entered.    So what is passed to popupData is
correct in that regard.

**Comment by jrobinso** [comment]
@desnar I don't understand your issue.  I have fixed @kaushik51094 issue however.

**Comment by kaushik51094** [comment]
@jrobinso - the same change needs to be done for the qualityAt function as well - here's a PR : https://github.com/igvteam/igv.js/pull/733. Please merge it if it looks good, thanks :)

**Comment by jrobinso** [comment]
@kaushik51094 -- yes, correct, merged.
