### ISSUE TITLE
Retina display support

### ISSUE THREAD

**Issue by romanzenka** [igvteam/igv.js#545]
Hello,

I am using IGV on a Mac and I'm noticing blurry display thanks to not using the retina display.

I would be interested in contributing support for retina.

Is this something you are at all interested in / willing to support long term?
I believe these displays will only be more prevalent over time.

In order to keep display fidelity, I would make larger canvas, scale it down using CSS, then add a transformation to all current IGV drawing code that would make the drawings 2x larger in case of a retina display.

This would ideally be concentrated in the `igv-canvas.js` file as not to create large amount of code changes all across IGV.

Over time this can be optimized by making the IGV code dpi-aware - I believe that some of your visualizations would benefit from having 2x or even 3x resolution. Smartphones are definitely a platform that would benefit from this.

In case that this is not at all interesting to you, there is an option to use `image-rendering: pixelated` as the style on the canvas element that somewhat reduces the blur.

Before: 
![image](https://user-images.githubusercontent.com/66568/37064728-c23c808a-2163-11e8-97c9-115cbee97e73.png)

After:
![image](https://user-images.githubusercontent.com/66568/37064761-db555ea2-2163-11e8-800f-1efabf3b77c9.png)

**Comment by romgrk** [comment]
I 100% support @romanzenka, I've been thinking about this yesterday and I'm including here some things I found:
 - Canvas 2d text drawing will always be less perfect than DOM. It might be interesting to either render the text content through DOM, or through WebGL. WebGL could also be used to render lines, as it's made to be pixel perfect (albeit it's like shooting a target with a nuke)
 - [https://stackoverflow.com/a/40074278/6303229](https://stackoverflow.com/a/40074278/6303229) A good resource to understand how what is described by @romanzenka works

**Comment by jrobinso** [comment]
I haven't had time to study this yet.   Text is fuzzy on canvas, a solution
to that would be welcome.   We did an exhaustive performance study of
Canvas vs DOM approaches (mainly SVG) at the beginning of the project and
canvas won hands down for our use cases.   I think other similar projects,
including an IGV knock-off called "pileup.js" as well as "dalliance" used
an SVG approach initially and switched to canvas later for performance.
We support many track types and use cases,  not all of which you
necessarily use,  but at this point canvas based rendering is baked in and
is not going to be changed in the foreseeable future.

All the developers on the project (both of us) have Macs with Retina
screens and I haven't noticed any fuzziness other than with text.

I will respond to @romanzenka when I've had time to look at the issue,  in
general I am supportive of pull requests that improve the app but its
better if they are small and focused.   Resources are limited and
issues/requests are many.

**Comment by jrobinso** [comment]
Agree totally with both of you.  We've wanted to do something for high DPI screens for a while but other issues keep bumping it down.   We are exploring it a little, but I think the gist of your original ideas are the correct path.    We need to find the right place to implement them,  for minimal disruption.   The igv canvas class is a bit of a kludge,  I don't want to do it there,  more likely it will be a wrapper around canvas.context2D.    Be patient with us a few days,  as you say we want to get this right.   I don't want to encourage you do do a lot of work on a PR until we are confident about the path.

**Comment by romanzenka** [comment]
I am putting together a testing branch here:

https://github.com/romanzenka/igv.js/tree/retina

I have so far achieved "retina ideogram", you can see what changes were needed for that.

This is tested in Chrome and Safari on Mac OS X.

Before:
![image](https://user-images.githubusercontent.com/66568/37188316-1646076c-2314-11e8-9c3c-52634f1979b1.png)

After:
![image](https://user-images.githubusercontent.com/66568/37188291-fd641fd6-2313-11e8-866e-4641fd744478.png)

**Comment by jrobinso** [comment]
@romanzenka This looks great,  and I like the implementation.   Let me study how we could apply this to tracks with minimal disruption.  The cached bitmaps for tracks, as well as the drawing of that image,  is done in a central place (in viewport.js).

**Comment by jrobinso** [comment]
@romanzenka Do you have an opinion on this polyfill?  https://github.com/jondavidjohn/hidpi-canvas-polyfill

**Comment by jrobinso** [comment]
In general, I don't like overriding core javascript prototypes.   However, the polyfill has the advantage of doing the right thing for Safari,  which already handles high DPI screens correctly.    To do this it depends on non-standard properties for the backing store,  but it looks safe as that defaults to 1  (e.g. webkitBackingStorePixelRatio).

**Comment by jrobinso** [comment]
Never mind the polyfill,  it looks unnecessary and is mostly just manually applying scale.   Why not just use context.scale()?

**Comment by jrobinso** [comment]
@romanzenka -- unfortunately we did a major restructuring of the ideogram after you forked in support of multiple loci and it was not possible to do a merge.   I just pushed an update to ideogram following the approach your approach to the branch highDPI.   If you care to comment or suggest changes please fork it and submit a PR.    One change -- I disabled the image caching to simplify the implementation,  it doesn't appear to be necessary,  the ideogram redraws very fast.  Next, I will move on to tracks which will be more complex.

**Comment by romanzenka** [comment]
@jrobinso 
I would prefer to not use a polyfill simply because it adds a layer of indirection and there already is a layer of indirection in igv.js.
We can get inspired by what the polyfill does and mimic that if necessary. 

The polyfill is trying to give you an illusion that you have a magic retina canvas that does everything just right.
However, I think that advanced visualizations can be retina aware.
That is why you might sometimes want to switch the polyfill off, and that could get confusing. If you work with the raw canvas as is, at least you always know what are you doing.

**Comment by jrobinso** [comment]
Got it.  I've almost got this, with no polyfill.

**Comment by romanzenka** [comment]
I made a little bit of progress, but the existing code is somewhat confusing to me so I am not sure if I am doing it right. I kind of cringe every time I have to touch the canvas element to get its width/height - igv would ideally have these numbers in its model and force those upon the actual DOM elements, not vice versa. The only exception is when resize is triggered when you measure what happened to the DOM element *once* otherwise you do not touch the DOM.

That would take some more discussion to figure out cleanly though.

Before: 
![image](https://user-images.githubusercontent.com/66568/37379383-4be8346c-2701-11e8-9213-f6f6cf4e1da3.png)

After:
![image](https://user-images.githubusercontent.com/66568/37379421-6bf1ea64-2701-11e8-8f54-a6d003aaa8f9.png)

This is not a PR yet because so raw, but you can see it here: https://github.com/romanzenka/igv.js/tree/highDPI

**Comment by romanzenka** [comment]
I just noticed - the vertical scrollbars are not working... but that's broken in master as well so you probably know about this already?

**Comment by romanzenka** [comment]
Oh boy the three frame translate gets spectacularly messed up:
![image](https://user-images.githubusercontent.com/66568/37379920-16ea1c64-2704-11e8-9dda-808cfd9986bb.png)
I think this happens whenever the drawing code asks the canvas for dimension instead of taking the dimension from the drawConfiguration.pixelWidth / pixelHeight (??). That will take some time to clean up...

**Comment by jrobinso** [comment]
Thanks for your work on this, but viewport.js and related classes are being refactored now for multi-locus support,  so any work on high DPI would have to be redone after.  I have a good handle on it now and will tackle it when we finish multi-locus.   I'll look at your highDPI branch,  its really helpful but we couldn't merge a PR until post multi-locus.   We'll double-check the scrollbars post multi-locus as well.

**Comment by romanzenka** [comment]
That is okay, you are in no way obligated to use my work if it is not helpful right now.
I was simply curious to see what would IGV look like on retina and I like it a lot!

![image](https://user-images.githubusercontent.com/66568/37380777-2ea715ba-2708-11e8-8198-b9c82020c447.png)

Speaking of multi-locus, I am working on a project that displays mate pair data on a display with two windows for two chromosomes on top of each other/side by side. It sounds like you are working on pretty much exactly that functionality. That would be a game changer for what we're doing over here as we could use IGV out of the box for our work... very curious to see the new functionality!

**Comment by jrobinso** [comment]
Yes, that's exactly what we're doing.   Actually multi-locus has been
working for a while in beta igv,  and "View mate region"  from an alignment
is one of the options.  We have some newly introduced bugs however and are
fixing them and refactoring to clean up the model in general.   Until
that's done we can't handle high DPI changes because they are in the same
files (viewport.js chiefly).    So hang tight for a few days and
multi-locus will be working and we can finish off the highDPI.   I also
like how it looks a lot.

We will probably make highDPI optional,  maybe default on,  because it does
use 4X the memory and there might be some applications where that is a
problem.   There is no way that I know of in javascript to check memory
available and make intelligent run-time decisions.

**Comment by romgrk** [comment]
@jrobinso: I think it is safe to assume that desktop machines with high DPI have enough memory to handle a 4X canvas. I'm not sure if there are mobile devices with high DPI, but mobile devices are detectable anyway ([here](https://stackoverflow.com/a/3540295/6303229), [here](https://github.com/hgoebl/mobile-detect.js/)) so you can always disable high DPI for mobiles only. 

Note: On Chrome you can also detect available and used memory through the Performance API:

![screenshot from 2018-03-14 12-13-26](https://user-images.githubusercontent.com/1423607/37415287-7a4f006c-2781-11e8-8d7e-8cf9788ed223.png)

This property is still non-standard for the moment, but you can use it if you feature-detect it, and fallback to whatever behavior you feel is a sane default.

**Comment by romanzenka** [comment]
@romgrk I think there are worse things that can happen than heap size - the canvas needs to be uploaded to the graphics card so you are probably more likely to run out of graphics card space than out of RAM. I think there is some sort of hardware acceleration of the canvas commands, which would point to the canvas buffer being on GPU at least in some instances. 
I do not know enough about details of canvas rendering - is the buffer split into chunks? Where is it stored? How is it composited? Too many questions. I'll try to dig deeper, otherwise you will probably be waiting for users on underpowered systems with overly huge displays doing some insane visualizations to notify you of issues first.

**Comment by jrobinso** [comment]
I think this issue can be closed,  ideogram and tracks now support highDPI screens.    There are a few minor canvases, such as the X-axis for wig tracks,  that still need to be converted but they are noted elsewhere.  Thank you @romanzenka for your contributions.
