### ISSUE TITLE
Base count by strands

### ISSUE THREAD

**Issue by tsimakova** [igvteam/igv.js#547]
Hello,

is it possible to configure IGV lite to display base count by strands as it is done in the desktop IGV (please see the attached screenshot)?

![igv_igv-lite](https://user-images.githubusercontent.com/24565787/37084526-d1b87d98-2203-11e8-8ac7-6e2a056457bf.png)

Best regards,
Tamara

**Comment by crashete** [comment]
I was looking for this too, but as I couldn't find anything straightforward to display base count as IGV desktop does I just ended up modifying the source code to add negative and positive counts in the function that renders the text.

If it helps, you just need to modify the function CoverageTrack.prototype.popupData and do 
 `  // A
            tmp = coverage.posA + coverage.negA;
            if (tmp > 0)  tmp = tmp.toString() + " (" + Math.floor(((coverage.posA + coverage.negA) / coverage.total) * 100.0) + "%, "+coverage.posA+"+, "+coverage.negA+"- )";
            nameValues.push({name: 'A', value: tmp});`

for each nucleotide.

**Comment by tsimakova** [comment]
Dear crashete,

thanks for the tip. Could you please show how the result is look in IGV lite?

Best wishes,
Tamara

**Comment by crashete** [comment]
Sure. I just made it look like IGV desktop as my users are used to that (also that info is relevant for us).

![basecountbystrand](https://user-images.githubusercontent.com/5757138/37521188-1905cd0e-2920-11e8-8a7b-a2cfe7ce4483.PNG)

Best regards,
Sergio.

**Comment by jrobinso** [comment]
@crashete Very nice.  Could you make a pull request?

**Comment by crashete** [comment]
Sure, glad to help, even if it's a simple change as this :)

**Comment by jrobinso** [comment]
@crashete Everything helps, thanks.
