### ISSUE TITLE
cursor guide sometimes (rarely) prevents mouse drag

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#548]
When the user is moving it's mouse, then clicking, it happens that the cursor guide is still directly under the user mouse, and thus receives the click event.

Setting `pointer-events: none` on it should solve this.

[https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)

**Comment by romgrk** [comment]
I'm wondering if it's also because of this that the cursor guide location is wrong (as described in https://github.com/igvteam/igv.js/issues/280). 
Would you be open to re-consider displaying the cursor guide directly under the cursor?

**Comment by jrobinso** [comment]
I aligned the guide back with the cursor.   I can't recall why we offset it, it was on purpose, but 2 people now have considered it a bug.
