### ISSUE TITLE
unable to type multiple loci in the search box separated by a space

### ISSUE THREAD

**Issue by amolpshinde07** [igvteam/igv.js#550]
@jrobinso 
To see multiple location in split view, unable to type multiple loci in the search box separated by a space

old issue link #309

**Comment by jrobinso** [comment]
This is not a released feature, what version are you using?

**Comment by amolpshinde07** [comment]
We are using igv-1.0.9.js

**Comment by jrobinso** [comment]
That feature is not available in 1.0.9.   It is not released yet.

**Comment by gokulbontha** [comment]
When you are planning to include this feature in release?

**Comment by jrobinso** [comment]
Nothing is scheduled yet, but I would expect to release it this spring.

**Comment by sjsachinrj** [comment]
@jrobinso  When you are planning to release igv V2.0 and Is multi location split view will part of this release ?

**Comment by jrobinso** [comment]
There are release candidates available now,  the latest being
https://igv.org/web/release/2.0.0-rc3,  and less multi location split view
is part of the release.   See the wiki for updated dependencies (there are
none),  just the igv.js include.
https://github.com/igvteam/igv.js/wiki/Dependencies-2.0.

The "release candidate" tag will be removed when I think its ready,  I
can't give you an estimated time on that as soon as possible.   However
these "rc" builds are stable and will not be removed.

**Comment by jrobinso** [comment]
That's "yes" not "less" multi location.....

On Tue, Jul 24, 2018 at 9:47 PM, James Robinson <jrobinso@broadinstitute.org

**Comment by sjsachinrj** [comment]
@jrobinso Thank u for quick response

**Comment by sjsachinrj** [comment]
Hi  @jrobinso ,
We are planning to upgrade igv v 2.0rc5. Just for confirmation Are you planning to release igv v2.0 in this 1-2 weeks. I just read your comment.  If yes let us know date So we can wait for 2.0.
Thanks,
Sachin

**Comment by jrobinso** [comment]
Hi, 2.0 will be released on or before Oct 12.
