### ISSUE TITLE
Save high resolution image

### ISSUE THREAD

**Issue by ausinha** [igvteam/igv.js#563]
I understand the underlying tech is canvas so SVG will not be possible but I was wondering if there is a better way to get an image other than taking a browser screenshot.

**Comment by jrobinso** [comment]
Not at this time,  its an important feature we will add but it is not s
small development task.

**Comment by jrobinso** [comment]
It would be helpful to start gathering use cases here.   For example,  what elements are critical and optional in the screenshot?  It will be possible soon to save a .png of an individual track element (basically its canvas).   This is already possible in some browsers context menu.    But I am guessing you want a single screenshot of the complete browser.   Anyway,  enumerating use cases would be helpful.

**Comment by ausinha** [comment]
A good use case is a typical figure included in a manuscript, showing a few data tracks and the gene track. E.g., 
<img width="609" alt="screen shot 2018-03-22 at 12 31 50 am" src="https://user-images.githubusercontent.com/359261/37751377-8825e2ea-2d68-11e8-9cbf-372d93a61753.png">

**Comment by ausinha** [comment]
Another example from a paper:
<img width="358" alt="screen shot 2018-03-22 at 12 33 40 am" src="https://user-images.githubusercontent.com/359261/37751408-b5957f88-2d68-11e8-955d-5c25c22f2e21.png">

**Comment by jrobinso** [comment]
In the 2.0 you can right-click individual tracks and save as SVG.   Saving the whole browser image as SVG is coming in version 2.1
