### ISSUE TITLE
loadTrack error

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#564]
Hi Jim,

I'm playing around with the nightly build and I'm getting the following error while calling 
```
igv.browser.loadTrack({    
url:"http://data.broadinstitute.org/igvdata/1KG/b37/data/HG02450/alignment/HG02450.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam",
label: "HG02450"
});
```

Error: 
```
jQuery.Deferred exception: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined
    at new igv.TrackView (https://igv.org/web/test/dist/igv.js:49423:87)
    at igv.Browser.addTrack (https://igv.org/web/test/dist/igv.js:30011:21)
    at igv.Browser.loadTrack (https://igv.org/web/test/dist/igv.js:29982:18)
    at Object.<anonymous> (http://localhost:8080/?build=hg19&locus=chr13:32912453-32912553&data=example/sampleData.json:57:17)
    at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29375)
    at c (https://code.jquery.com/jquery-3.3.1.min.js:2:29677)
```

  | w.Deferred.exceptionHook | @ | jquery-3.3.1.min.js:2
-- | -- | -- | --
  | c | @ | jquery-3.3.1.min.js:2
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery-3.3.1.min.js:2
  | u | @ | jquery-3.3.1.min.js:2
  | fireWith | @ | jquery-3.3.1.min.js:2
  | fire | @ | jquery-3.3.1.min.js:2
  | u | @ | jquery-3.3.1.min.js:2
  | fireWith | @ | jquery-3.3.1.min.js:2
  | k | @ | jquery-3.3.1.min.js:2
  | (anonymous) | @ | jquery-3.3.1.min.js:2
  | load (async) |   |  
  | send | @ | jquery-3.3.1.min.js:2
  | ajax | @ | jquery-3.3.1.min.js:2
  | w.(anonymous function) | @ | jquery-3.3.1.min.js:2
  | getJSON | @ | jquery-3.3.1.min.js:2
  | getTrackList | @ | functions.js:2
  | (anonymous) | @ | ?build=hg19&locus=ch…/sampleData.json:34
  | l | @ | jquery-3.3.1.min.js:2
  | c | @ | jquery-3.3.1.min.js:2
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery-3.3.1.min.js:2
  | u | @ | jquery-3.3.1.min.js:2
  | fireWith | @ | jquery-3.3.1.min.js:2
  | fire | @ | jquery-3.3.1.min.js:2
  | u | @ | jquery-3.3.1.min.js:2
  | fireWith | @ | jquery-3.3.1.min.js:2
  | ready | @ | jquery-3.3.1.min.js:2
  | _ | @ | jquery-3.3.1.min.js:2

I'm using the following libraries:
```
  <!-- jQuery JS -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <!-- jQuery UI JS -->
  <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
  <!-- jQuery UI smoothness CSS -->
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">

  <!-- Bootstrap JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <!-- IGV JS-->
  <script type="text/javascript" src="https://igv.org/web/test/dist/igv.js"></script>
  <!-- IGV CSS -->
  <link rel="stylesheet" type="text/css" href="https://igv.org/web/test/dist/css/igv.css">
```

Any idea what I could do about this? This prevents me from loading additional tracks.

Thanks
M

**Comment by matthdsm** [comment]
Strangely enough, the following DOES work.
```
igv.browser.loadTracksWithConfigList([
{        url:"http://data.broadinstitute.org/igvdata/1KG/b37/data/HG02450/alignment/HG02450.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam",
label: "HG02450"
    }
])
```

**Comment by el1jaC** [comment]
I think you must also register the BAI file, in "indexURL" option.

**Comment by jrobinso** [comment]
I will look into it, but if using the nightly build the font-awesome link is no longer necessary.   Also, the css to us is "https://igv.org/web/test/dist/igv-all.css".   See https://igv.org/web/test/test.html for an example.  This will be documented on wiki before merging to master.    This is not the cause of your error though.   @el1jaC you do not have to specify the index for urls  if it follows the standard naming convention,  although it is recommended.   You DO have to specify the indesURL for local file blobs.

**Comment by jrobinso** [comment]
Mattias,  I can't reproduce your problem.  See http://igv.org/web/test/examples/api.html,  I added the bam to the "track" dropdown menu.  Also http://igv.org/web/test/examples/bam.html.

The current required includes for the test build are below.  Also, try clearing your cache.   The line number in your error message does not match the current igv.js.

```
<link rel="stylesheet" href="https://igv.org/web/test/dist/igv-all.css">
<script src="https://igv.org/web/test/dist/igv.js">
```

**Comment by matthdsm** [comment]
Hi Jim,

Thanks for looking into this. I suppose this error is caused by some sort of async process. The data in my app that feeds into loadTrackList is read from a json file, so that might be the cause.

**Comment by jrobinso** [comment]
If you can set up an example I can access I will see if I can debug it.

**Comment by matthdsm** [comment]
Hi Jim.

Thanks a lot for the offer. I've created a [repo with example code](https://github.com/matthdsm/IGVviewer-example). It also contains a Dockerfile for an image that should work out of the box.

It may be worth to note that everything works with version 1.0.9. It's only when using the test version that I get the error above.

Thanks again, you've already been a huge help.
M
