### ISSUE TITLE
changing genome builds

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#565]
Hi, 

Is it possible to change the genome build of the browser without removing and reloading it completely?
Also, is it possible to show the current genome build somewhere in the browser?

Thanks
M

**Comment by jrobinso** [comment]
Not currently.    Will add it.

**Comment by matthdsm** [comment]
Great! Thanks! 👍

**Comment by jrobinso** [comment]
You can't do this through the UI, but there is an API function to do it.   Also,  there is a menu item to select the genome in igv-webapp, which is probably the right place for it.
