### ISSUE TITLE
track/gear popup menu fails to show (mostly) in latest build

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#566]
I think I saw mention of fontawesome changes yesterday?   Maybe related to the sudden appearance today of the problem described in the subject line: when I click on the gear icon no in IGV.R's browser igv.js, I see no popup menu.

I fiddled with my css, creating a larger right margin, which worked once ... but no longer.

This may be interaction with my own css, and my own css may not be altogether sensible.

Any suggestions?

Thanks!

**Comment by jrobinso** [comment]
I noticed the icons do not work with jquery tabs,  it might be related, it
seems the font-awesome css does not work nicely with jquery-ui.

I'm completely redoing this now using svg and custom js code rather than
font-awesome css magic.   This should fix the problems.   Its tedious,  I
should have it done by later today.

**Comment by jrobinso** [comment]
@paul-shannon the font-awesome replacement is implemented in the branch Multi-locus_edits.  We are still testing before merging to master.   It seems to fix the jquery-ui / fa clash that was causing icons to not work.

**Comment by paul-shannon** [comment]
Hi Jim,
Success!   I am not using jQuery tabs at present - I'll get back to that once the Bioconductor IGV package is submitted Monday.   But I built  igv.js just now from the github source and the new non-fontawesome "gear" track icons work fine.

They fail only in one minor circumstance.  I have an R command

    setGenome(igv, "hg38|hg19|mm10|tair10")   # choose 1

which destroys any existing content of #igvDiv  creating the igv browser de novo.   When I do this, the second and subsequent calls to setGenome create an igv browser in which the track gear icons no longer respond.   

I just reproduced this is a simple minimal html/js-only web page.
The second time I call to   ````igv.createBrowser(igvDiv, options);```` produces (for me) non-responsive track gear icons.   I do this from the javascript console, using this code

````
    igvDiv = $("#igvDiv")[0];
    options = {locus: "MEF2C",
               minimumBases: 5,
               showRuler: true,
               reference: {id: "hg38",
                     fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa",
                  cytobandURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/cytoBandIdeo.txt"
                  },
               tracks: [
                 {name: 'Gencode v24',
                       url: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz",
                  indexURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz.tbi",
                  format: 'gtf',
                  visibilityWindow: 2000000,
                  displayMode: 'EXPANDED'
                  },
                 ]
              }; // options
        browser = igv.createBrowser(igvDiv, options);
````

**Comment by jrobinso** [comment]
Paul,  I assume you are re-creating the browser because we don't have a method to reset the session and load a different genome, correct?

**Comment by jrobinso** [comment]
@paul-shannon Could you try again?  I think its fixed, you can pull from master or use  our test distribution.   The includes now have changed, and are simplified,  no font-awesome just an igv css and js.  Note the name change for the css (igv-all.css)
```html
<link rel="stylesheet" href="https://igv.org/web/test/dist/igv-all.css">
<script src="https://igv.org/web/test/dist/igv.js"></script>
```

**Comment by jrobinso** [comment]
Great.  We should tag whatever you submit to Bioconductor as a "release" so we know precisely what was submitted.   In what form do you submit the igv.js js and css files,  via a copy or by reference to one of our urls?

**Comment by paul-shannon** [comment]
Tagging the version released in bioc makes good sense.

I now, in classic npm style, assemble igv.js and igv-all.css into the final igv.html  my package builds.

 I use an expedient github repo, https://github.com/paul-shannon/igv.js.npm, containing a copy of your latest igv.js and igv-all.css from a manual build I do after a fresh pull of your igv.js repo, so that npm can find your library.
All of this evolved six months ago as a temporary solution.   Maybe there is, or will be, a better way for me to get the latest build via npm?

**Comment by jrobinso** [comment]
IGV has an npm repository,  but I build it manually and it has the released
IGV.   After tagging I will attempt to update it.    This will be later
today (pacific time).
