### ISSUE TITLE
How to apply igv.js to the web side?

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#571]
For those who have not contacted igv before, only developed front-end developers of the mall, how to use igv.js for web-side development work？

**Comment by jrobinso** [comment]
@mofengfs I don't understand your question.   Have you reviewed the information on the wiki?

**Comment by el1jaC** [comment]
@mofengfs igv.js is a Javascript library, and you can link it like normal js file, or you can link the amazon URL.

Can you explain better what would you want to do?

**Comment by mofengfs** [comment]
@jrobinso @el1jaC

**Comment by mofengfs** [comment]
@jrobinso @el1jaC I am understanding the documentation in the wiki. Not bad. However, the documentation is still simple, such as no detailed description of the tracks object.

**Comment by jrobinso** [comment]
Look at the source code
