### ISSUE TITLE
magic error message occurs when crams are missing

### ISSUE THREAD

**Issue by bw2** [igvteam/igv.js#572]
I'm using the igv.js-flask server to serve crams. 

When a cram file is missing, the error popup shows "BAM header contains an invalid BAM magic". 
Can this be changed to something like "BAM header error: invalid BAM magic. This may also mean the file could not be found."   
https://github.com/igvteam/igv.js/blob/043d3d6b917353933cf05d5e68c72d8df3aa11e6/js/bam/bamUtils.js#L81

**Comment by jrobinso** [comment]
Done as a stop gap.   @ishanley if the cram file is missing the response should set the status code to "404" for file not found.

**Comment by bw2** [comment]
Thanks
