### ISSUE TITLE
Event change functions

### ISSUE THREAD

**Issue by toniher** [igvteam/igv.js#573]
Hello, I was checking documentation and so far I have not been able to find if there are any pre-built event change/obverse function (e.g., for triggering an action on changing coordinates or zooming)

Thanks!

**Comment by jrobinso** [comment]
Yes, apologies this is not documented, it is contributed functionality but that is no reason not to document it.  See the examples in this folder.  

http://igv.org/web/examples/events/

**Comment by brentp** [comment]
hi, regarding events, given a mouse event captured in the browser, is there a way in igv.js to know which track the mouse is over? this would be for events like `hover`, not e.g. `trackdrag` or other igv.js specific events.
