### ISSUE TITLE
How to import local files ？

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#577]

**Comment by jrobinso** [comment]
If you want help you need to to do more than offer a sentence fragment.   Please tell us what you want to do, and what you have tried.

**Comment by mofengfs** [comment]
What I mean is that igv browser can import files. How does igv.js web side import files?

**Comment by jrobinso** [comment]
@mofengfs igv.js is a pure javascript client program.  It loads files by XMLHttpRequest.   Everything a developer needs to know to imebed igv.js is explained in the wiki, and many have done so.  We don't have time or resources here to do basic web tutorials.
