### ISSUE TITLE
Locus search not working for certain gtf files

### ISSUE THREAD

**Issue by mikesafdieh** [igvteam/igv.js#580]
We have some of our own sorted gtf files (hosted on aws) for gene tracks. However, when we do a locus search by gene name we get an "Unrecognized locus" error message from IGV. Genomes where this happens are: tair10, taeGut2, danRer7, danRer10, and others. Below is a screenshot for tair10:

<img width="1075" alt="screen shot 2018-03-30 at 2 23 49 pm" src="https://user-images.githubusercontent.com/8171274/38149016-df4e45fc-3426-11e8-9479-ee04b5dea0c9.png">

Is this an IGV specific bug? Or do we need to format our gtf files in a certain way so that we can do a locus search by gene name?
NOTE: we can still search by chromosome (e.g. "chr2", "chr1:30,400,671-30,427,671") for all of these genomes, just not by the gene name.

We don't have this issue with hg19, mm10, and mm9. 

Any help will be very much appreciated.

**Comment by jrobinso** [comment]
Did you mark the annotation file as "searchable" in the config  (see
section 2 here https://github.com/igvteam/igv.js/wiki/Tracks)?

IGV uses a webservice for searches, and if that fails searches annotation
files that have been marked "searchable".    For the search to succeed the
annotation file cannot be indexed as it needs the entire contents in memory.

The search webservice we provide by default has entries for a few
assemblies,   the ones you mentioned plus hg38.   We will add entries for
other assemblies,  please submit a separate git request for this.   It is
also possible to provide your own search webservice,  see the search object
description here:  https://github.com/igvteam/igv.js/wiki/Browser

**Comment by mikesafdieh** [comment]
We ended up going with writing our own webservice for the unsupported aasemblies.
Thank you
