### ISSUE TITLE
minor issues: track label, center guide, color alignments, remove track popup

### ISSUE THREAD

**Issue by zengzheng123** [igvteam/igv.js#586]
Hi, I was testing the code built from master branch, and found some minor issues. 

1. When clicking the track label of an alignment track, the click event of the underneath element is also triggered(the coverage track). So the track label popup will show and disappear immediately, then the coverage popup will show.

2. The state of center guide toggle button is not properly set when IGV is initialized with center guide cursor turned on.

3. For the alignment track, changing the "color by" option does not immediately update the checkmark on the popup menu. (it is updated if you close and reopen the popup menu)

4. The remove track confirm window does not show the complete track name. And If I move the popup window, it disappears.

Best,
Zheng

**Comment by helgathorv** [comment]
Hi Zheng,

Thanks for the report. We already caught a couple of those in our testing, but not all - so this is much appreciated.

Helga

**Comment by turner** [comment]
As of commit b0ad489d all of these issues are resolved.
