### ISSUE TITLE
Zoom buttons and track settings not rendering in beta version

### ISSUE THREAD

**Issue by mikesafdieh** [igvteam/igv.js#594]
I'm using the beta version of IGV and the zoom buttons and track setting buttons are not rendering as shown below:

<img width="1087" alt="screen shot 2018-04-04 at 2 33 49 pm" src="https://user-images.githubusercontent.com/8171274/38327043-468aa62e-3815-11e8-9cb2-78c2c4008ead.png">

NOTE: If I use the links for the development branch (as described in #570) then the zoom and settings buttons appear. 

This was not an issue a few days ago and I have not changed our code at all. Is there anything different that I have to do (e.g. new css dependencies)?

**Comment by jrobinso** [comment]
Yes,  the dependencies have changed (much simpler now).   Scroll to the
bottom here  https://github.com/igvteam/igv.js/wiki/Dependencies

**Comment by mikesafdieh** [comment]
I changed the new dependencies and still having the same issue. The issue also occurs on the beta example page http://igv.org/web/examples/beta.html# 
I am using Chrome but had the same issue with the example page on safari. On Firefox the icons appeared oversized as shown below:

<img width="1274" alt="screen shot 2018-04-04 at 11 04 58 pm" src="https://user-images.githubusercontent.com/8171274/38345354-a6687110-385c-11e8-913d-50b6387067a9.png">

**Comment by jrobinso** [comment]
The beta page is incorrect, thanks for the report.   Updated examples are
here:  http://igv.org/web/test/examples/

Could you post your web page,  or at least the <head> section?

**Comment by mikesafdieh** [comment]
Here is our head section:

<img width="939" alt="screen shot 2018-04-05 at 2 19 52 pm" src="https://user-images.githubusercontent.com/8171274/38384266-ac164198-38dc-11e8-836d-056c4aabe27b.png">

And for the js, the end of our body:

<img width="933" alt="screen shot 2018-04-05 at 2 20 37 pm" src="https://user-images.githubusercontent.com/8171274/38384316-d0e27c62-38dc-11e8-827a-5e18fd9d0752.png">

**Comment by jrobinso** [comment]
If you want to run the nightly snapshot,  all you need is what is
documented in the page I referenced.  I see you have it there but its
commented out.   All other igv includes should be removed  (e.g.
igv-beta.min.js).    You may or may not need the jquery, bootstrap, and
font-awesome includes for your page, but they are not needed for igv.   Try

<link rel="stylesheet" type="text/css" href="
https://igv.org/web/test/dist/igv-all.css">
<script type="text/javascript" src="https://igv.org/web/test/dist/igv.min.js
"></script>
