### ISSUE TITLE
single/double center line

### ISSUE THREAD

**Issue by zengzheng123** [igvteam/igv.js#603]
Hi,

When I turned on center line on initiation of IGV, and set the initial locus to to a 41bp region. It only shows a single center line at the center of that base. And if I do a search, and move it to another 41bp region, it becomes two lines that frame the base. I know that IGV decides whether to show a single or double center line based on the resolution of the region. But in this case, they are both 41bp regions.

Best,
Zheng

**Comment by turner** [comment]
Fixed with commit cb619bf8
