### ISSUE TITLE
Remove console.log from production version

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#613]
Currently, IGV.js contains `console.log`s even in the minified production version.

**Comment by jrobinso** [comment]
Yes, we should remove them,  so do many other libraries but I agree we should remove them.

**Comment by romgrk** [comment]
Babel is great for transforming code, you could integrate a step in your production build script with the [remove-console plugin](https://babeljs.io/docs/plugins/transform-remove-console/).

**Comment by jrobinso** [comment]
I don't think all browsers are compatible with ES6+ yet.   "Modernizing" our codebase is not a priority.
