### ISSUE TITLE
Apache header response error

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#615]
"Request header field Range is not allowed by Access-Control-Allow-Headers in preflight response.", my apachea server, according to the rules in the document to configure, but reported this error, what is the matter? How to solve it?

**Comment by jrobinso** [comment]
Rules are listed here:  https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements.  You must set access control to allow the Range header.   This is not in igv.js problem, it is a server configuration problem.   Google "CORS" and you will get lots of links to read.

**Comment by jrobinso** [comment]
Also,  watch the network traffic (request and response), for example in Chrome tools.
