### ISSUE TITLE
invalid block type

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#616]
'invalid block type',What caused this error?

**Comment by el1jaC** [comment]
Hi @mofengfs ,
can you explain better, maybe with some screenshot/example?

**Comment by mofengfs** [comment]
![1](https://user-images.githubusercontent.com/16655229/38543708-e3d81f26-3cd7-11e8-9f8b-76231965727b.png)
![2](https://user-images.githubusercontent.com/16655229/38543710-e40e7ba2-3cd7-11e8-8c1f-90e48146eff5.png)

**Comment by el1jaC** [comment]
Hi @mofengfs ,
can you upload also he screenshot of browser console?
In most cases i browser console there is the clearest explanation.

**Comment by mofengfs** [comment]
Hi @el1jaC 
![3](https://user-images.githubusercontent.com/16655229/38546637-b92b6cee-3cdf-11e8-99f8-8817819210aa.png)
![4](https://user-images.githubusercontent.com/16655229/38546638-b95d462e-3cdf-11e8-9a51-25290254346f.png)
