### ISSUE TITLE
Use the same file source.Why is the difference between Desktop version of igv  and Html5 end result is so big? Html5 reported an error

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#622]
This question is related to #628

The same file source+chr7:128,486,170-128,486,210
![3603-1](https://user-images.githubusercontent.com/16655229/38660393-a8bb3c3c-3e5f-11e8-880f-74412b2f7e1c.png)
![3603](https://user-images.githubusercontent.com/16655229/38660670-a95d050c-3e60-11e8-91c7-0f67c52ded4e.png)
![image](https://user-images.githubusercontent.com/16655229/38665362-d196ac2c-3e6e-11e8-9875-1e9ea80ffb6c.png)
![image](https://user-images.githubusercontent.com/16655229/38662343-8b86867e-3e66-11e8-94e0-231d5c63f291.png)

**Comment by jrobinso** [comment]
I don't understand your question at all.  What is  "H5"?   Also, the screenshots you show are for different bam files.

**Comment by mofengfs** [comment]
Hi @jrobinso , 
Which bam file does the desktop version of igv use?
