### ISSUE TITLE
Array Buffer Allocation Failed 

### ISSUE THREAD

**Issue by hakanEdico** [igvteam/igv.js#624]
Uncaught (in promise) RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at typedArrayConstructByLength (<anonymous>)
    at new Uint8Array (/cgi-bin/native)
    at Object.igv.unbgzf (igv-beta.js:27642)
    at success (igv-beta.js:33315)

I am using the readFeatures function to extract information out of a vcf.gz file 
The first time I loaded the page, this worked fine and returned data. Now every time I get this error! In the debugger I found that is trying to make an array of size 112,792,266

I am using the beta version because I cannot get 1.0.9 working, and I used to use igv-all but that has another bug when trying to use readFeatures on a VCF (at some point there is a call - data.split("\n"), but data is already an array)

**Comment by jrobinso** [comment]
The old "beta" folder is obsolete and will be deleted soon.   Documentation is being updated.   

Try this release:  https://igv.org/web/release/2.0.0-beta1/dist/

You need only include the igv.min.js and igv-all.css files.    (https://github.com/igvteam/igv.js/wiki/Dependencies-2.0)

**Comment by hakanEdico** [comment]
Thank you for the suggestion. I can now see the request for the VCF being made, after it finishes, my browser locks up completely! Not sure what the issue is.

**Comment by hakanEdico** [comment]
Lock up is something on my side after the data is returned. I appreciate your help! One quick question - I am querying for chr1, position 1 - 249,250,621 and the request takes around 20 seconds to get 29MB of data, is this normal?
