### ISSUE TITLE
I do not understand the relationship between each file. Which of the following two methods is correct?

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#628]
This question is related to #622

![qq](https://user-images.githubusercontent.com/16655229/38785691-0a44d560-4155-11e8-881a-36d143b0f4a8.png)

![q2](https://user-images.githubusercontent.com/16655229/38785589-1e498110-4154-11e8-8a7e-65e604c2ef85.png)

**Comment by jrobinso** [comment]
You're question doesn't make any sense.   Do you understand the basics of a URL?

**Comment by mofengfs** [comment]
Hi @jrobinso ，
Yes, I understand that what I do not understand now is the role of the track file. For example, what does the hg19.bed file in your demo do? And the role of the HG01879*******.bam file. This is also the reason why I can't figure out #622.

**Comment by jrobinso** [comment]
If the documentation and examples are not enough for you I can't help you
further.

**Comment by mofengfs** [comment]
@jrobinso 
Sorry, reading English documents was a bit difficult for me. I also read through the documents, but it did not solve my problems. I'm very sorry to trouble you.
