### ISSUE TITLE
Add title attribute on track's label

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#634]
Use HTML `title` attribute to display the label name when it is too long rather than a popup that opens on click.
E.g.
```html
<div class="igv-track-label" title="My Label">My Label</div>
```

Current:
![screenshot from 2018-04-18 18-09-59](https://user-images.githubusercontent.com/1423607/38960814-f03c8768-4333-11e8-9aad-9140769e1f52.png)

Proposed:
![screenshot from 2018-04-18 18-09-53](https://user-images.githubusercontent.com/1423607/38960820-f5bf184a-4333-11e8-91e8-faf422460a6e.png)

**Comment by jrobinso** [comment]
@romgrk We can do the html title attribute but it is not a replacement for the popup.  Showing the name is default behavior but you can attach detailed track descriptions with links, etc.  Some portals make extensive use of this, for example the GTEX portal.

**Comment by romgrk** [comment]
@jrobinso Ok no problem, the [PR](https://github.com/igvteam/igv.js/pull/635) I've submitted adds the HTML attribute without removing the popup.
