### ISSUE TITLE
Display error message when track cannot be loaded

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#637]
Currently, there is no visual warning if a track could not be loaded (e.g. network error, server error, etc). It would be great if there was a message to let the user know that the track is not loaded, because the current display can mislead the user to think the track is just empty instead of not loaded.

Proposition:
![screenshot from 2018-04-19 12-20-30](https://user-images.githubusercontent.com/1423607/39004883-92dd437a-43cc-11e8-860e-c9974316b9b2.png)

@jrobinso if you're ok with this proposition I can submit a PR to make the changes

**Comment by jrobinso** [comment]
Yes, agreed.  Could you make the PR to the "development" branch?  This allows us to test before committing to master.
