### ISSUE TITLE
Amino acid error

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#643]
![qq 20180420112117](https://user-images.githubusercontent.com/16655229/39029158-f82bae2c-448c-11e8-9b61-c70f7dd5f68e.png)

**Comment by jrobinso** [comment]
What is the error?  Please do not open git issues with vague or incomplete
descriptions of the problem.  They will be closed.

**Comment by mofengfs** [comment]
Hi @jrobinso 
It should be from start to stop, but here is stop to stop.

**Comment by mofengfs** [comment]
![111](https://user-images.githubusercontent.com/16655229/39033297-efbc829a-44a3-11e8-9070-8aac0f496611.png)
After opening the first track, the second track has no content. Is this a bug?

**Comment by jrobinso** [comment]
That is not a bug,  what you are viewing is just the 3 frame translation table.
