### ISSUE TITLE
Is there no desktop version of igv.js this track?

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#650]
![q2](https://user-images.githubusercontent.com/16655229/39104006-cc700a5c-46e0-11e8-933a-f2547ae31594.png)
![q3](https://user-images.githubusercontent.com/16655229/39104080-2ef0089e-46e1-11e8-9405-5ed4fef6ec51.png)

**Comment by jrobinso** [comment]
No, you have some fundamental misunderstanding here.  You are pointing at
an annotation track in desktop.

**Comment by mofengfs** [comment]
Hi @jrobinso I just want the same track as the desktop version
