### ISSUE TITLE
This error is reported after selecting bam file.

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#653]
![q8](https://user-images.githubusercontent.com/16655229/39114152-8bb56b4e-4710-11e8-84f8-91505646f85d.png)

**Comment by jrobinso** [comment]
What version of igv.js are you using?

**Comment by mofengfs** [comment]
Hi @jrobinso

**Comment by mofengfs** [comment]
@jrobinso 
I use igv.js 2.0

**Comment by jrobinso** [comment]
Look at the console, the error is in your code not igv.js.  Please stop filing so many issues without doing a little study yourself first.   When you do file an issue be complete in your description, and supply test cases.

**Comment by mofengfs** [comment]
@jrobinso 
I checked my code and I didn't change anything, just the url of the calling file changed. This error is only occasionally present.

**Comment by mofengfs** [comment]
@jrobinso 
This error occurs when the translation option is selected.
![qq333](https://user-images.githubusercontent.com/16655229/39162387-d844a906-47a7-11e8-9d72-2415f0c98a59.png)

**Comment by mofengfs** [comment]
@jrobinso 
This error occurs occasionally. I suspect it is a problem with the network request.
