### ISSUE TITLE
I tried to load the transcript track but it was not displayed correctly.

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#656]
![transcript](https://user-images.githubusercontent.com/16655229/39162696-5dc685c6-47a9-11e8-8ae8-4fc6c53ee828.png)

This is my transcript
[refGene.txt](https://github.com/igvteam/igv.js/files/1940577/refGene.txt)

**Comment by jrobinso** [comment]
That is how transcripts are displayed in igv.js.  Amino acids are not supported.   This might come in a future release.

**Comment by mofengfs** [comment]
@jrobinso 
Yes, thanks, look forward to the next version.
