### ISSUE TITLE
Multiple tracks group autoscale (as in IGV desktop) possible?

### ISSUE THREAD

**Issue by jaime11** [igvteam/igv.js#658]
Hello,

Just wanted to check if it is possible to group Autoscale multiple tracks whether automatically when showing them or through manual multiple track selection and selecting autoscale.

Thanks!

**Comment by jaime11** [comment]
I just saw this, so I think this can be done through sessions, sorry:
https://github.com/igvteam/igv.js/blob/f05dc77dacc497b09c1b00bfe327502f96ba542c/dev/test.xml

**Comment by jrobinso** [comment]
I just pushed support for group autoscale to master.    This will be in the next 2.0 beta release.   See examples/groupAutoscale.html.
