### ISSUE TITLE
Deprecared beta igv.css file

### ISSUE THREAD

**Issue by gumuslab-mssm** [igvteam/igv.js#660]
Hi,

I have been using the css file located at https://igv.org/web/beta/igv.css 
and have built a massive application on top of it. I noticed that, that version has been deprecated and no longer available. As a result, my application breaks severely and (unless restored in some way) would need major revisions. I sincerely hope that you can share the above-mentioned css version (through a link or some other way), which I can download and have a local copy going forward. 

I would greatly appreciate your understanding and collaboration in this issue. 

Thanks!

Best,
Selim

**Comment by jrobinso** [comment]
I've restored the files from 3/27 -- tag in the repository is beta-3-27.   Again please consider this interim,  I can't offer much support for this build.
