### ISSUE TITLE
Reads are not shown in alignment track

### ISSUE THREAD

**Issue by kzoabi** [igvteam/igv.js#662]
Hi,

When scrolling down in the alignment track there are no reads loaded yet, IGV shows them only after zoomIn then zoomOut once.
What can I do to fix that?
 I'm using the master code.

Thanks,
Khaled

**Comment by jrobinso** [comment]
I can't reproduce the problem.  Can you reproduce it here?
http://igv.org/web/test/examples/bam.html

If you can prepare a test html file that reproduces the problem, zip, and
upload it I can look further.  You can use this public bam file for the
test.

'
https://data.broadinstitute.org/igvdata/1KG/b37/data/HG02450/alignment/HG02450.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam
'

**Comment by kzoabi** [comment]
Hi Jim,

I cannot prepare a test html page but I can enter screen shots:

![image](https://user-images.githubusercontent.com/3586425/39464360-78985ed4-4d25-11e8-999a-9820f44e2418.png)

when scrolling down (we don't see more reads):
![image](https://user-images.githubusercontent.com/3586425/39464384-9787a138-4d25-11e8-9258-5e4d4376eaf5.png)

After zooming:
![image](https://user-images.githubusercontent.com/3586425/39464424-e0fb8488-4d25-11e8-9238-9e36ba720f98.png)

I have tried a workaround that works for me so far, but it isn't an appropriate solution. The workaround is to call trackView.resize() method when the alignment finishes loading.

Thanks,
Khaled

**Comment by jrobinso** [comment]
Are you quite sure that you have pulled and are using the latest code in
master?   What is the commit tag you are using?
