### ISSUE TITLE
configure igv.js so that remove track menu does not need further confirmation?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#663]
3 mouse clicks are required to remove a track, starting with the "gear" icon menu for the target track.

 Can igv.js be configured so that the OK/Cancel dialog - the third click - is not needed?

**Comment by jrobinso** [comment]
I think we can dispense with the confirmation dialog.

**Comment by turner** [comment]
Fixed with commit 35939d3d
