### ISSUE TITLE
Browser gives RangeError when rendering inside a div with style display: none

### ISSUE THREAD

**Issue by MariaNattestad** [igvteam/igv.js#669]
IGV.js is super useful. Thanks for the great tool!

Since it takes a few seconds to load its tracks fully, I want to be able to let it load while looking at other tab content within the app. To do that, I'm hiding its container div with the CSS style "display: none" while it first starts loading, but then when I go to the tab (display: block) IGV.js gives an error saying "RangeError: Invalid array length". The error doesn't show up in the console until IGV.js is displayed.

![screen shot 2018-05-21 at 10 16 14 am](https://user-images.githubusercontent.com/7958077/40320295-083181b4-5ce0-11e8-8195-059a309394a0.png)

If I'm showing the tab while it loads, so it is "display: block" then it loads just fine, and if I use "visibility: hidden" instead, then it loads fine too (but it takes up space, so that's not ideal). I'm using the "beta" version of IGV currently available through NPM.

Here is the stack trace:
![screen shot 2018-05-21 at 10 33 06 am](https://user-images.githubusercontent.com/7958077/40321121-e2b5369e-5ce2-11e8-9349-37e5ba84bdbc.png)

Please let me know if there is a workaround for this issue. Thanks!

**Comment by jrobinso** [comment]
We are aware of this issue in other contexts.   There is no workaround
now.  The problem is igv uses the width of its container to compute the
genomic range in view,  and it is not happy with a width of zero.

In the meantime, until this is fixed, perhaps we could speed up your data
loading.   What types of file formats are you loading?

**Comment by MariaNattestad** [comment]
Thanks for the quick reply! Is there any way I can set an explicit width that won't be overridden by display: none? I tried doing this to the container and to the igvRoot div, but neither prevented the error. Can you point me to where in the code it is looking for this width? Maybe I could add in a fallback default width and submit a pull request.
The data loading time actually isn't the main issue, but rather that the tab containing IGV.js isn't always going to be selected when the page first loads, so I need to find some way to get it to quietly just work in the background. Thanks for your help!

**Comment by jrobinso** [comment]
This should now be fixed.  I created an example file to illustrate,  examples/tabs.html.   Note that if running from the github project you must first build with "grunt" before running examples.

**Comment by MariaNattestad** [comment]
Thanks, I'll check it out!

**Comment by jrobinso** [comment]
@MariaNattestad The key thing is to call igv.visibilityChange(),  or browser.visibilityChange(),  after changing the "display" attribute.

**Comment by MariaNattestad** [comment]
Awesome, thank you!
