### ISSUE TITLE
trackclick event somewhat erratically detected on single base (snp) objects

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#672]
Using the latest igv.js, pulled yesterday, for which I am developing a custom trackclick handler, I find that my mouse clicks, with even when apparently directly on the rendered snp, often do not enter my handler with the expected popoverData.  Instead, that data is empty.

If I zoom in to about a 6kb window, I think I see that when the mouse pointer's hotspot is clicked in the right half of the rendered snp, no popoverData arrives in my handler.   Clicking in the left half reliably yields popoverData on the snp.  The popoverData currently comes from a simple bed track I have loaded.

The problem appears to be more pronounced with a 14kb window:  only the leftmost quarter of the rendered snp responds to the click.

I must say that the the custom track click and popover capabilities are very useful!

 - Paul

**Comment by jrobinso** [comment]
Its an inconsitency between click "fudge" and rendering "fudge".  A snp at 14kb is of course a small fraction of a pixel wide.   So you can see something the features are drawn with a minimal pixel width of 3.  The tolerance for a click is tighter.   I will try to harmonize these.

**Comment by paul-shannon** [comment]
Better! And quite good enough for our purposes.  Thanks, Jim.
