### ISSUE TITLE
"data.splitLines is not a function" - using search on Rhodobacter sphaeroides gff file

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#673]
Delighted to discover the ease with which a gff.gz and gff.gz.tbi can be added to the latest igv.js, for what to me is a new organism, setting up the track like this:

 ````
type: "annotation",
nameField: "gene",
url: "http://trena.systemsbiology.net/rhos/GCF_000012905.2_ASM1290v2_genomic.gff.gz",
indexURL: "http://trena.systemsbiology.net/rhos/GCF_000012905.2_ASM1290v2_genomic.gff.gz.tbi",
format: 'gtf',
searchable: 'true',
````
and seeing gene names nicely displayed in EXPANDED displayMode, I nonetheless ran into this error
````
igv.js:31531 Uncaught TypeError: data.splitLines is not a function
    at parseSearchResults (igv.js:31531)
    at processSearchResult (igv.js:31358)
    at igv.js:31259
    at Array.forEach (<anonymous>)
    at igv.Browser.createGenomicStateList (igv.js:31253)
    at igv.Browser.search (igv.js:31162)
````
after entering one of the displayed gene names ("atpA") into the search box.

![image](https://user-images.githubusercontent.com/2480712/40877311-bf443ad4-6633-11e8-8f2d-823645ad0a6e.png)

**Comment by jrobinso** [comment]
I will track this down and fix it,  however you really cannot do a useful
search on an indexed track.   The search on track features is on the
features loaded into memory.   With an index this will be just what's in
view.    I realize that is the case here,  but if the gene were somewhere
else in the genome it would not be found.

The doc states that this field does not work for indexed files,  meaning
files with a tabix (.tbi) or tribble  (.idx) index.

**Comment by paul-shannon** [comment]
Thanks, Jim.  Sorry I failed to grasp that (now fairly obvious) point.

Is it good practice therefore to use a full, uncompressed gtf|gff annotation file for search?

 - Paul

**Comment by jrobinso** [comment]
Yes, but it can't be too large.   I would suggest stripping out all the
non-essential parts (CDS, exon, etc) to create a small track to load just
for searching.   In fact it would be a good idea to add an option for a
non-visible track.   Then load the full gff/gtf separately as an indexed
file.

I'm still uncertain what is causing the bug you referenced, that will need
fixed before any of this works.

**Comment by paul-shannon** [comment]
If indexed files do not support search - for those regions not currently in memory - could you explain why gene symbol search works flawlessly with this configuration?  Sorry to be slow on the uptake…

 - Paul

    options = {locus: "MEF2C",
               minimumBases: 5,
               showRuler: true,
               reference: {id: "hg38",
                     fastaURL: "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa",
                  cytobandURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/cytoBandIdeo.txt"
                  },
               tracks: [
                 {name: 'Gencode v24',
                       url: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz",
                  indexURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz.tbi",
                  format: 'gtf',
                  visibilityWindow: 2000000,
                  displayMode: 'EXPANDED'
                  },
                 ]
              }; // options

**Comment by jrobinso** [comment]
Gene search works on some common genomes because it uses our web service.
  It is possible to configure your own webservice to do this,  see
https://github.com/igvteam/igv.js/wiki/Browser-Configuration-2.0  (scroll
to the bottom).

**Comment by paul-shannon** [comment]
Thanks, Jim.  Good solution - but perhaps rather than maintain web services for species we might be interested, I’d be interested instead in the possible “invisible track” you mentioned.  Could this go on the requested features list?

 - Paul

**Comment by jrobinso** [comment]
Yes,  what should the property be?

visible:  false

invisible: true

hide: true

displayMode:  hide   (in addition to squish/collapse/expand).

I'm being really lazy.

**Comment by paul-shannon** [comment]
hidden: false   // the default

How’s that?

**Comment by jrobinso** [comment]
That works, its much easier to have properties with "false" as the default
since the absence of any value evaluates to "false" in javascript.
