### ISSUE TITLE
"invalid literal/length code" with vcf.gz and vcf.gz.tbi files from s3

### ISSUE THREAD

**Issue by desouzareis** [igvteam/igv.js#675]
![screen shot 2018-06-04 at 10 45 22](https://user-images.githubusercontent.com/29407033/40920993-93b263a2-67e4-11e8-8a96-2e7cb7e9867f.png)
I'm getting this error when trying to use vcf.gz and vcf.gz.tbi urls from s3 storage. I was able to open using the same urls on the desktop version. Could you help? 

Thank you.

**Comment by jrobinso** [comment]
Please include a igv.js version number with bug reports,  or commit ID,  or "latest from master".

Also,  could you include a test case in the form of a igv.js "config" object or better html page, or s3 urls?  We load many things from s3 so there is not a general problem.

**Comment by desouzareis** [comment]
Hi, thanks for the quick reply. 

I'm trying to open different vcf.gzip and vcf.gzip.tbi files from s3 using the latest version from master and getting different errors: 

- _invalid literal/length code_,
- _Cannot read property 'startsWith' of undefined_
- _oversubscribed dynamic bit lengths tree_

`igv-beta.min.js:43318 igv browser ready
igv-beta.min.js:54886 invalid literal/length code
(anonymous) @ igv-beta.min.js:54886
`

`igv.js:43318 igv browser ready
igv.js:54886 TypeError: Cannot read property 'startsWith' of undefined
    at igv.VcfParser.parseHeader (igv.js:54448)
    at igv.js:33642
(anonymous) @ igv.js:54886
Promise.catch (async)
igv.Viewport.loadFeatures @ igv.js:54885
(anonymous) @ igv.js:51089
igv.TrackView.updateViews @ igv.js:51088
igv.Browser.addTrack @ igv.js:30377
igv.Browser.loadTrack @ igv.js:30350
(anonymous) @ igv.js:30298
igv.Browser.loadTrackList @ igv.js:30297
(anonymous) @ igv.js:30007
Promise.then (async)
igv.Browser.loadSession @ igv.js:29997
doPromiseChain @ igv.js:43331
igv.createBrowser @ igv.js:43308
(anonymous) @ igv.js:250
$scope.generateIgvJs @ igv.js:211
(anonymous) @ igv.js:257
instantiate @ angular.js:4777
$controller @ angular.js:10533
(anonymous) @ angular-ui-router.js:4081
(anonymous) @ angular.js:1259
invokeLinkFn @ angular.js:10095
nodeLinkFn @ angular.js:9492
compositeLinkFn @ angular.js:8757
publicLinkFn @ angular.js:8637
lazyCompilation @ angular.js:8994
updateView @ angular-ui-router.js:4021
(anonymous) @ angular-ui-router.js:3959
$broadcast @ angular.js:18239
(anonymous) @ angular-ui-router.js:3352
processQueue @ angular.js:16606
(anonymous) @ angular.js:16622
$eval @ angular.js:17913
$digest @ angular.js:17727
$apply @ angular.js:18021
done @ angular.js:12002
completeRequest @ angular.js:12211
requestLoaded @ angular.js:12139
load (async)
(anonymous) @ angular.js:12122
sendReq @ angular.js:11947
serverRequest @ angular.js:11742
processQueue @ angular.js:16606
(anonymous) @ angular.js:16622
$eval @ angular.js:17913
$digest @ angular.js:17727
$apply @ angular.js:18021
bootstrapApply @ angular.js:1806
invoke @ angular.js:4762
doBootstrap @ angular.js:1804
bootstrap @ angular.js:1824
angularInit @ angular.js:1709
(anonymous) @ angular.js:32379
mightThrow @ jquery.js:3534
process @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888
igv.js:54886 TypeError: Cannot read property 'startsWith' of undefined
    at igv.VcfParser.parseHeader (igv.js:54448)
    at igv.js:33642
(anonymous) @ igv.js:54886
Promise.catch (async)
igv.Viewport.loadFeatures @ igv.js:54885
(anonymous) @ igv.js:51089
igv.TrackView.updateViews @ igv.js:51088
igv.TrackView.resize @ igv.js:51056
(anonymous) @ igv.js:30565
igv.Browser.resize @ igv.js:30564
(anonymous) @ igv.js:31701
(anonymous) @ igv.js:45406
dispatch @ igv.js:5265
elemData.handle @ igv.js:4918
`

`igv-beta.min.js:43318 igv browser ready
igv-beta.min.js:54170 Uncaught TypeError: Cannot read property 'queryFeatures' of undefined
    at igv.VariantTrack.contextMenuItemList (igv-beta.min.js:54170)
    at HTMLDivElement.<anonymous> (igv-beta.min.js:55127)
    at HTMLDivElement.dispatch (igv-beta.min.js:5265)
    at HTMLDivElement.elemData.handle (igv-beta.min.js:4918)
igv-beta.min.js:54170 Uncaught TypeError: Cannot read property 'queryFeatures' of undefined
    at igv.VariantTrack.contextMenuItemList (igv-beta.min.js:54170)
    at HTMLDivElement.<anonymous> (igv-beta.min.js:55127)
    at HTMLDivElement.dispatch (igv-beta.min.js:5265)
    at HTMLDivElement.elemData.handle (igv-beta.min.js:4918)
igv-beta.min.js:54886 oversubscribed dynamic bit lengths tree
(anonymous) @ igv-beta.min.js:54886
igv-beta.min.js:54886 oversubscribed dynamic bit lengths tree
(anonymous) @ igv-beta.min.js:54886
`

Is there a email I could send the s3 urls? thank you.

**Comment by jrobinso** [comment]
You can send them to igv-team  (at)   broadinstitute.org.   You will get a canned response which you can ignore.

**Comment by jrobinso** [comment]
BTW I see a reference to igv-beta.min.js ,  where is that coming from?

**Comment by desouzareis** [comment]
I just renamed the file in my project. I will send the files url to the email. thanks

**Comment by jrobinso** [comment]
Could you see if you can reproduce the problem with this public file?

```
{
  url: 'https://data.broadinstitute.org/igvdata/1KG/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz',
  indexURL: 'https://data.broadinstitute.org/igvdata/1KG/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi',
  visibilityWindow: 20000,
  name: '1KG Sites'
}
```

**Comment by jrobinso** [comment]
Why do yuo have to set the content-type?   Setting it to gzip can cause
problems.   In some cases the browser might gunzip it before IGV even sees
the data.   IGV expects to see binary (bgzipped) data.   If setting content
type the best choice would probably be application/octet-stream.

I host many files at Amazon and have never explicitly set a content type.

**Comment by desouzareis** [comment]
I changed the the content-type to application/octet-stream and also worked fine. I'm using boto3 in a django app to upload the files to the s3 bucket. I will further investigate how to set the content-type to application/octet-stream there. 

thanks once again.

**Comment by desouzareis** [comment]
Looking at the code of S3BotoStorageFile from storages.backends.s3boto3 it appears that content_type is guessed from the file extension. In my case `mimetypes.guess_type` was returning `('text/x-vcard', 'gzip')` that was setting the content-type to `text/x-vcard` and the `encoding-type` to `gzip`.
