### ISSUE TITLE
Show aberrations of type Fusions

### ISSUE THREAD

**Issue by kzoabi** [igvteam/igv.js#677]
Hi @jrobinso ,

I know that IGV.js supports aberrations of type Fusions side by side, but cannot find out an example or even the configuration which I can use for this purpose.
Is "FusionJuncSpan" type related to this? if yes, how can I use it?

Can you please help me to find out how to visualize fusion results with IGV.js?

I cannot see any example even here:
[IGV Examples](http://igv.org/web/examples/)

Thanks,
Khaled

**Comment by jrobinso** [comment]
Hi Khaled,

Sorry for the delay.   You can't do this explicitly,  but you can few multiple genomic regions side by side in by supplying an array for the "locus" property in the config. For example
```
locus: ["myc", "muc1"],
```
or
```
locus: ["chr1:1000-2000", "chr2:6000-7000"],
```
So if you know where your breakpoints are you can view both regions.   The FusionJuncSpan type is a specialized track for the Trinity Rna-Seq application,  not really applicable here.

You can also enter multiple loci from the UI (search / goto box) by separating loci with a space.

**Comment by jrobinso** [comment]
For an example see http://igv.org/web/test/examples/multi-locus.html
