### ISSUE TITLE
wig track, set data range popup menu, minimal value, if > 0, ignored

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#678]
Hoping to create an ad hoc filter on wig values, by setting the min value in the data range popup menu to a value great than zero - and thereby hiding all features with a smaller value - I found that min > 0 is interpreted as min = 0, and no features get hidden.   

![image](https://user-images.githubusercontent.com/2480712/41313654-5c2d7000-6e3f-11e8-885a-e2767bbc04d9.png)

Setting min to -3 does have an effect on the display, though coordinate labelling might be a little misleading:
![image](https://user-images.githubusercontent.com/2480712/41313878-f6922366-6e3f-11e8-9b0e-66d4fef1468b.png)

**Comment by jrobinso** [comment]
Hmm, repaint is part of the problem, not all.

On Wed, Jun 13, 2018 at 1:25 PM, James Robinson <jrobinso@broadinstitute.org
