### ISSUE TITLE
Error: Range-Byte Header Ignored When Loading Local File

### ISSUE THREAD

**Issue by sasankvemuri** [igvteam/igv.js#680]
I see that there is another issue with similar title. However it was posted a couple of years ago and there was no clear solution provided to it other than zooming in.

I am trying to load tracks after rendering flask output. I created a drop-down for loading 5-6 tracks and on clicking, there is no issue with large files (around 10-11mb in this case) however when I try to load tracks from files which are about 50-few 100 kb, I get this error

Error: Range-Byte Header Ignored When Loading Local File

Is there any solution to overcome this?

P.S thanks for this awesome tool. Much appreciated.

**Comment by jrobinso** [comment]
I don't really know what you mean by "local file",   is that the error message printed?    You have to enable range header support in your server, which I assume is flask in this instance.

We don't really support flask per se,  its just a web server as far as igv.js is concerned.   Requirements for web servers are listed in the wiki doc.

**Comment by sasankvemuri** [comment]
The exact error message is: "Error: Range-Byte Header Ignored for URL"

However if try to load a slightly bigger file, it works without any error.

**Comment by jrobinso** [comment]
You haven't specified what version of igv.js you are using or what type of file(s) you are loading.

I suspect the flask server is returning a 200 code, instead of a 206,  if the requested range is > the file size.    I do not think this is correct behavior but nonetheless we can probably work around it.   Could you zip up a sample file, and its index if applicable,  that is failing and attach it?

**Comment by sasankvemuri** [comment]
IGV Version: 1.0.9

File type: BED

I have attached the complete file below. 

Also the code I am using to load track is as shown below

`<a class="dropdown-item" href="#" onClick="igv.browser.loadTrack({
                                 format: 'bed',
                                 url: 'static/browser_data/modifications/{{ species }}/sorted_nm.bed.gz',
                                 indexURL: 'static/browser_data/modifications/{{ species }}/sorted_nm.bed.gz.tbi',
                                 visibilityWindow: 300000000,
                                 displayMode: 'EXPANDED',
                                 label: 'NAME'})">NAME</a>`


[mouse.zip](https://github.com/igvteam/igv.js/files/2111791/mouse.zip)

**Comment by jrobinso** [comment]
OK -- a suggestion,  if the files are small (say less than 1 mb) don't
index them,  don't supply a .tbi file and set "indexed" to false.   This
should solve your issue.

I will be sure this case works in the upcoming 2.0 release, but 1.0.9 will
not be patched.

**Comment by sasankvemuri** [comment]
Great. This works now, thanks for the fix.

Also I see that the igv (css and js file server) is down? Is it going to be patched?

**Comment by jrobinso** [comment]
@sasankvemuri I was going to try to reproduce the issue of small files with your data,  but mouse.zip is not a zip file.

**Comment by savemuri** [comment]
Hello the zip contains .bed.gz and .bed.gz.tbi files.

**Comment by jrobinso** [comment]
Yes, but its not a zip file.  Try unzipping it.

**Comment by jrobinso** [comment]
I've simulated this with my own data.   I'm going to fix it for completeness,  but I still recommend not indexing very small files, its inefficient.
