### ISSUE TITLE
Are genbank files supported for reference or annotation tracks?

### ISSUE THREAD

**Issue by tnrich** [igvteam/igv.js#689]
Hey there!

Again thanks for this awesome tool :) 

I am wondering if either the reference sequence or an annotation track can currently handle a genbank file. I know that the igv desktop version says it supports genbank files but I wasn't able to find any references to genbank files in this repo so my guess is that this functionality hasn't been implemented yet. 

Ideally for our use case we could simply provide a "genbankURL" and have a supporting annotation track created automatically. It would also be fine though to keep the fastaURL for the reference and just add an additional genbank annotation track ourselves. 

Thanks!

**Comment by jrobinso** [comment]
Genbank is not implemented yet,  partially because no one has requested it until now.

**Comment by tnrich** [comment]
Okay, let me know if there is anything I can do to help with this. For the moment we are just going to create a separate .bed file from the genbank file and use that as an annotation track.

**Comment by jrobinso** [comment]
This didn't quite make the 2.0 cut (release today), but I will get it in on a point release to follow shortly.  It is a priority, and will load both sequence and annotations.

**Comment by SchwarzMarek** [comment]
Hi,
I've noticed some code regarding genbank in the codebase. I wanted to ask if this would be drop-in replacement for indexed-fasta + indexed-gff combination regarding the load-speed or if it would be only usable for small files?
(I presume that the genbank file would need to be indexed.)

**Comment by jrobinso** [comment]
The genbank code is a work in progress,  but it will be a drop-in
replacement for the "reference" object, i.e. it will define the reference
fasta and associated annotations.  As far as I know there is not an index
for genbank files, so this will be limited to small genomes.

**Comment by jrobinso** [comment]
This is supported now and will be in the next release.  See the example here:

https://igv.org/web/snapshot/examples/genbank.html

To configure a genbank genome with annotations you enter the url as both the reference and annotation source.  Its smart enough to not load it twice.   This was the most straightforward way to fit this into the current framework.  

```
    const igvConfig = {
        reference: {
            gbkURL: "https://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Fungi/Candida_dubliniensis_CD36_uid38659/FM992689.gbk"
        },
        tracks: [
            {
                name: "Annotations",
                type: "annotation",
                format: "gbk",
                url: "https://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Fungi/Candida_dubliniensis_CD36_uid38659/FM992689.gbk",
            }
        ]
    }

    igv.createBrowser(document.getElementById('igvDiv'), igvConfig)
```

**Comment by tnrich** [comment]
Nice work @jrobinso ! Thanks for this!
