### ISSUE TITLE
After the canvas is loaded, I want to save the image automatically with saveImage, but I am getting an error when I call it. Can you give me some pointers?

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#690]
![qq 20180713112723](https://user-images.githubusercontent.com/16655229/42670842-c2144ac0-868f-11e8-942b-3a97344428a5.png)
![qq 20180713112919](https://user-images.githubusercontent.com/16655229/42670884-0459d350-8690-11e8-9c09-76e75a0a4e5b.png)

**Comment by jrobinso** [comment]
I think the error message you see is clear enough,  no time for javascript tutorials.   Here's a hint though, go study "prototype" and be sure you understand the concept.
