### ISSUE TITLE
I wrote a function that automatically retrieves image information, which can be obtained correctly in igv2.0.0-beta3, but not correctly in igv2.0.0-rc3. This is where this function is called.I want to get the information of the image automatically after the canvas rendering is completed.

### ISSUE THREAD

**Issue by mofengfs** [igvteam/igv.js#694]
1.igv2.0.0-beta3:
![1](https://user-images.githubusercontent.com/16655229/43249737-1561a4a8-90ee-11e8-8751-742a2701634d.png)
![1-1](https://user-images.githubusercontent.com/16655229/43249738-15a9d0b6-90ee-11e8-90b0-50ef894514db.png)
![1-2](https://user-images.githubusercontent.com/16655229/43251081-8c27a5b2-90f1-11e8-893c-ca4bf7f248c4.png)

2.igv2.0.0-rc3:
![2](https://user-images.githubusercontent.com/16655229/43249761-25f76f64-90ee-11e8-8708-bd82d71d4629.png)

**Comment by jrobinso** [comment]
Sorry that's not part of our API,  if you want to hack the code feel free but I can't debug it for you.   We have a "save image" function in the context menu for tracks.
