### ISSUE TITLE
API/docs for plotting data directly

### ISSUE THREAD

**Issue by brentp** [igvteam/igv.js#711]
igv.js works great if I have a BED file or some given format, but if I have some data in javascript that I want to plot, there's not apparent way to do that.

Is there some example I can look at for this or is this something that could be added? This would provide a lot of flexibility if there was a draw-able track.

thanks.

**Comment by jrobinso** [comment]
Brent,  I'm not sure exactly what you mean by "plot" but see issue #705

**Comment by brentp** [comment]
what you describe in #705 should work for me. thank you.
