### ISSUE TITLE
removeTrack(trackView.track)  on bed tracks: cannot unsubscribe, track.browser undefined

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#716]
I encounter this in programmatic calls to igv.removeTrack - with a bed track.  bedGraph  tracks remove without trouble.     Both track types display fine.   

Let me know if a tiny example is needed.

Thanks!
 - Paul

````
igv.js:33534 Uncaught TypeError: Cannot read property 'un' of undefined
    at unSubscribe (igv.js:33534)
    at igv.js:30110


        var unSubscribe = function (removedTrack) {
            if (track.browser.un && track === removedTrack) {
                track.browser.un('trackdrag', onDragEnd);
                track.browser.un('trackremoved', unSubscribe);
````

**Comment by jrobinso** [comment]
An example would be helpful.

**Comment by paul-shannon** [comment]
Absolutely.   Once I get past a couple of deadlines tomorrow I will put one together.  

 - Paul

**Comment by jrobinso** [comment]
Ping,  is this still an issue?

**Comment by paul-shannon** [comment]
Works perfectly now.  Thanks!
