### ISSUE TITLE
Update igv.js npm module

### ISSUE THREAD

**Issue by oyvinev** [igvteam/igv.js#717]
Hi,

Thanks for a brilliant piece of software. Could update the igv in npm, or even better, add npm module update to your release-procedure? Currently the npm version is v2.0.0-rc2, with some bugs that have been fixed in the latest version.

**Comment by jrobinso** [comment]
Yes, its part of the release procedure going forward.   I will be doing the
next release, 2.0.0-rc5,  in the next couple of days.

**Comment by Chris7** [comment]
A note on this, currently the git repo is uninstallable by npm because of the VERSION string in the repo's package.json. If this was removed, it would be much easier for users to access the bleeding edge. Currently, this error is raised:
```
yarn add git+https://github.com/igvteam/igv.js.git#d742ca3
yarn add v1.5.1
[1/4] Resolving packages...
error An unexpected error occurred: "Can't add \"igv\": invalid package version \"VERSION\".".
```

**Comment by jrobinso** [comment]
@Chris7 Ah, o.k.,  sorry I'm a nube with NPM.

Would it work if it had the version string of the last published version?   I hope so, because with the process going forward that is what it will have.   If the answer is yes I will add it.   Otherwise, what should the version number be for the latest un-tagged commit in master?

**Comment by Chris7** [comment]
That was fast, thanks!

For versions on a git branch, I don't know of any hard rules. But I follow the same practice you did and have seen most other packages following that paradigm as well. For me, if you are installing from a commit, you accept any risk that may take :).

**Comment by jrobinso** [comment]
OK then, problem solved.  My original worry was about jumping forward with as-of-yet unpublished version number,  lagging behind is safe.   On to other problems.
