### ISSUE TITLE
Support creation and removal of many browser instances

### ISSUE THREAD

**Issue by Chris7** [igvteam/igv.js#726]
We have the need to display sequencing data in an infinite scroll style where sequencing data is displayed dynamically by what is in the viewport. Our current setup is using React and I included a demo app here [igv-demo.zip](https://github.com/igvteam/igv.js/files/2310728/igv-demo.zip). The problem is after a few loads/unloads, chrome becomes completely unresponsive and hits an OOM memory (there are also some other errors in the console that are likely related to objects no longer existing or perhaps conflicts)

To get started:
* extract the attached zip
* install yarn from within the `igv-demo` directory: `npm install yarn`
* install dependencies with yarn: `./node_modules/.bin/yarn install`
* Build igv (github disttribution does not have compiled assets so this is necessary): `cd node_modules/igv/ && npm install && ./node_modules/.bin/grunt && cd -`
* Run the server: npm start
* Scroll around for a little bit, crash as memory keeps increasing

If this is something IGV is willing to work towards, it would be amazing.

**Comment by jrobinso** [comment]
That's not too surprising,  igv.js wasn't designed for continual construction/destruction of the browser app.   Many dom elements and listeners are created/destroyed each time.   We will work at at,  but in the meantime a more robust design might be to move the root browser div around the DOM tree as needed.

**Comment by jrobinso** [comment]
I've added a unit test BTW,  in test/testBrowser.js,  that creates and destroys 100 "igv.Browser" objects.

**Comment by jrobinso** [comment]
I tried the demo app, and its not clear what we are testing.   I don't see any removes, just additions, and can quickly get many browsers loading BAM files.   These xmlhttprequests are going to complete, they are not cancelled when the browser is removed.     This might be at the root of the issue.  It would be interesting to try creating and removing browsers,  but disable loading of bam files, to separate issues.

If you are triggering bam loads as "browsers" come into view while scrolling rapidly its going to be difficult to get this to work.

**Comment by Chris7** [comment]
The demo app has a method, `componentWillUnmount`, that is called when the element is removed from the div. This calls `igv.removeBrowser(this.browser)`, which removes the brower (there is also a remove in the promise of `componentDidMount` that will remove the browser in case the promise resolved after the component was removed).

What I am testing is browsing up and down the page without 1) crashes and 2) unbounded memory growth.

There are some app improvements, like delaying the load so components that are scrolled by fast never both loading, but this was just a demo. I'll see how things load w/o bam parsing.

**Comment by jrobinso** [comment]
I can make and remove 100 browser objects in quick succession, see the unit tests.   I think the rapid memory growth in your demo app iis from the spawning of many XMLHttpRequests for BAM data.

**Comment by jrobinso** [comment]
This design concept is going to be difficult to pull off,  you need something that loads fast, near instantly at least for the initial view.    Preloading the data in view and placing it in the page itself, as a data URI,  is one possibility.   See the project igv.js-reports, it does just that.   Also this example,  all of the data is in the page itself: http://igv.org/web/test/examples/dataURI/dataURI.html.

**Comment by Chris7** [comment]
The bamless one crashes as well, and doing a memory profile shows a constant increase in memory from loading gene tracks (with a corresponding increase in the number of objects allocated). I think the parser may be retaining state from every track loaded in.

**Comment by Chris7** [comment]
Thanks for that link as well, really cool to be able to use dataURIS!

**Comment by jrobinso** [comment]
The dataURIs are not official yet, but will definitely be supported, we are using that for an internal project.    WRT the leak, that's useful information,  that should be reproducible in a simple web page, which would be helpful.  Could you try modifying test/testBrowser.js to reproduce the problem?  Setting the initial locus for each created browser to a gene,  e.g. 'MYC',  should be enough.  If not different random locations.

**Comment by Chris7** [comment]
It appears there are quite a few things that aren't getting cleaned up from `removeBrowser` (which given that it wasn't something actively used, is not surprising :)).

I took some heap snapshots in chrome and you can see the increase in object allocations as each new browser is added (and you can see in the console at the bottom things being removed):
Heap1: 
![screenshot from 2018-08-22 15-25-19](https://user-images.githubusercontent.com/963909/44485920-271a4f00-a620-11e8-9f9c-430607dba712.png)
Heap2:
![screenshot from 2018-08-22 15-25-23](https://user-images.githubusercontent.com/963909/44485925-2b466c80-a620-11e8-9bd3-8aa6b3dcfb88.png)

**Comment by Chris7** [comment]
Also, I completely understand that this is all new ground for IGV and really appreciate your responsiveness and enthusiasm for extending it to new grounds (I don't mean just to complain!)

**Comment by jrobinso** [comment]
Thanks.  I find that difficult to interpret,  I don't know how many objects should be there for reference, and I am not seeing it dynamically.    A simple test case would be helpful, that could be run standalone, perhaps just modifying test/testBrowser.js.  I will give that a try when I have some time.

**Comment by Chris7** [comment]
Will do! No lingering objects should result in a constant number of object allocations, as we scroll the number of allocations keeps increasing even as browser objects are being removed (for instance, igv.Cytoband goes from 2586->8620 and if i scrolled again, would increase similarly).

**Comment by jrobinso** [comment]
I tried simulating with the snippet below but was not successful.  The # of objects was stable, and after the 100th iteration when the last browser was removed there were virtually no objects left.  Strangely Cytoband and Chromosome are hanging on to a few,  but that's all.   This might not be an equivalent test, but perhaps its a start.   

```javascript

        const n = 100;
        let i =0;

        createRemove();

        function createRemove() {

            igv.createBrowser(div, {
                genome: "hg19",
                locus: "myc"
            })
                .then(function (browser) {
                    igv.removeBrowser(browser);
                    if(++i < n) {
                        createRemove();
                    } 
                })
                .catch(function (error) {
                    console.error(error);
                })
        }

```

![screen shot 2018-08-22 at 1 04 35 pm](https://user-images.githubusercontent.com/933148/44487878-3b545100-a60c-11e8-8564-0df5073e097b.png)

**Comment by jrobinso** [comment]
Is it possible something in your application or React is hanging onto a reference to 'browser'?

**Comment by Chris7** [comment]
Thanks, I'll dig around. I am using live-reload and will see if a production build reproduces this (making prod builds is a bit of a pain because create-react-app fails if something is not transpiled to ES5)

**Comment by jrobinso** [comment]
OK,  I don't see any serious leaks in igv.js itself, but will keep trying.   One thing to do would be add a timer to the test to allow time for the browser to render before removal,  that might affect something.

**Comment by jrobinso** [comment]
I created a standalone test file,  test/testRemove.html,  that creates and removes a browser with gene track every 3 seconds.   Running 10 iterations with chrome dev tools I don't see any significant memory leaks.     So I don't think igv.js is holding onto objects.   Feel free to modify this test and send a PR.  
<img width="1597" alt="screen shot 2018-08-22 at 6 50 05 pm" src="https://user-images.githubusercontent.com/933148/44500406-1b895100-a63d-11e8-8e1b-48b9429eee01.png">

**Comment by Chris7** [comment]
I made a yarn compatible build to test a non live-reload build (if you are interesting in converting to ES5 at the end of your build chain, I can put a PR up). The memory usage is definitely more manageable now. The browser references persist, and it appears to be related to jquery event handlers. I'll dig around now that I can more easily insert dev builds to final builds.

**Comment by jrobinso** [comment]
If you pull the latest igv and run  "test/testRemove.html" you will see
that there are zero references to anything with igv. after the last browser
is removed.

Currently I'm working on canceling xmlhttprequests that are in progress
when a browser is removed.   I'm not sure yet if that will be easy, and in
this release, or hard and in a later release.   Even if it works spawning
xmlhttprequests for data just to abort them a fraction of a second later
can't be good for resources,  so factor that into your scrolling design.

**Comment by jrobinso** [comment]
No problems, testing is never a waste of time and I did find a few leaks.   However, I think the "cancel load" function is necessary before your scrolling application will work robustly.   I started a branch for that, abortable_http_requests.   I'll leave this issue open until that is done.
