### ISSUE TITLE
igv.FeatureTrack.prototype.popupData -- genomicData variable undefined?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#727]
From today's build, in the function named in the subject line above, I encounter a use of genomicLocation without obvious assignment.   clickState.genomicLocation **is** defined.  By assigning
````
   genomicLocation = clickState.genomicLocation 
````
in the js console, I succeed in getting the normal popup behavior.

![image](https://user-images.githubusercontent.com/2480712/44686768-1bee6700-aa04-11e8-8e2e-aa3939733098.png)

**Comment by jrobinso** [comment]
Good catch, and your solution is the correct one.  What feature type did you notice this on?  In most common cases the buggy code isn't called,  only when popupData is implemented on individual features.

**Comment by paul-shannon** [comment]
Thanks, Jim.
I right-clicked on an exon from this track:
````
        {name: 'Gencode v24',
         url: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz",
         indexURL: "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg38/genes/gencode.v24.annotation.sorted.gtf.gz.tbi",
         format: 'gtf',
         visibilityWindow: 2000000,
         displayMode: 'EXPANDED',
         height: 300
         },
````

**Comment by jrobinso** [comment]
OK, should be fixed now.   Right-clicking should bring up the context menu,  with a single item "Save Image" in most tracks.   I find right-clicking with a single button Mac mouse unreliable,  are you sure you right-clicked?  Hold ctrl down and click if a Mac.
