### ISSUE TITLE
There are inconsistencies in the reads for the same bam data

### ISSUE THREAD

**Issue by kzoabi** [igvteam/igv.js#728]
Hi @jrobinso,
We get the same data for the bam file for each request (with the same parameters or request header), and the IGV JS shows different reads on the alignments section for each load (with the same position and parameters). Please see the attached screenshots and the bam/bai files.
[alignments.bam.bai.txt](https://github.com/igvteam/igv.js/files/2331198/alignments.bam.bai.txt)

![alignments_1](https://user-images.githubusercontent.com/3586425/44772479-a6ef6e80-ab76-11e8-8946-90ef5ec18b79.PNG)
![alignments_2](https://user-images.githubusercontent.com/3586425/44772480-a6ef6e80-ab76-11e8-89f4-6c0ab23faf8c.PNG)

[alignments.bam.txt](https://github.com/igvteam/igv.js/files/2331186/alignments.bam.txt)

Thanks & regards,
Khaled Zoabi

**Comment by jrobinso** [comment]
This is normal.  The black bars under the coverage track indicates the reads have been downsampled, so igv is displaying a representative sample of the reads.  This is done in areas of deep coverage to keep your browser from crashing.   You can change downsampling parameters for the track, for example to see more reads, but you can't turn it off altogether as your browser is not capable of displaying an infinite number of reads.   See https://github.com/igvteam/igv.js/wiki/Tracks-1.0,  the "alignments" section,  particularly "samplingDepth" and "samplingWindowSize".
