### ISSUE TITLE
Performance Issues with own files

### ISSUE THREAD

**Issue by mnoyes68** [igvteam/igv.js#729]
Hello

I'm trying to set up IGV js to view bam files off of a server. The server has bam and bai files in a directory hosted by tomcat. We're having very slow performance on these files, and I'm wondering if anyone else has had these issues.

When I run IGV over my own files, they seem to run one major XHR load that takes about 100 seconds. In contrast, when I run IGV over the broad institute HG02450 file I see in all the examples, it runs multiple XHR loads with many more HTTP requests, and goes substantially faster, loading in about 2.5 seconds. I'm not sure if there's any additional configuration I need to do outside of range and CORS headers, but clearly I need to change something because this is crawling. Anyone who's had success loading their own files into IGV js, please let me know what you did!

**Comment by jrobinso** [comment]
How are you implementing support for Range requests?  My recollection is, and its been a long time, that Tomcat doesn't support that out of the box.   I remember implementing it once for tomcat.  Its most likely there is a a mistake here.

**Comment by mnoyes68** [comment]
I implemented it in the web.xml file in the ROOT directory, where I stored the BAM files. The text I used is this.
```
<init-param>
      <param-name>cors.allowed.headers</param-name>
      <param-value>RANGE,Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers</param-value>
</init-param>
```
It may be worth noting that not all my responses have range in the allowed headers. My code 200 response almost always come back with it, but I also get a lot of code 206 responses that don't have it. I certainly wouldn't be surprised to hear that I didn't implement this correctly, so if you have any ideas they would be more than welcome.

**Comment by jrobinso** [comment]
I know very little about tomcat,  I haven't used it in many years.    But speaking generally,  it looks like your xml is enabling CORS headers.   This is only neccessary if you are serving data files from a different host as the webpage containing igv.js.    Its critical though the Range headers are requested,  if igv.js requests the byte range 100-200 from the server it should only get that range back, 100 bytes,  not the entire file.    You can verify that this is happening from Chrome dev tools,  look at the request headers until you find on with a Range header.    Then look at the response size and be sure its the correct # of bytes.    Again, I have no specific tomcat knowledge, but this is one potential source of trouble.    You might try another server, like Flask,  to see if that solves the problem.

**Comment by mnoyes68** [comment]
So I was able to dig up the range headers and sure enough it seems to be feeding in the entire file, with a content length of 129710362 bytes. This is in contrast to the example pulling from https://data.broadinstitute.org/igvdata/1KG/b37/data/HG02450/alignment/HG02450.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam which sends a number of requests of 65001 bytes each (one has a little more). 

It might be worth noting that I switched to an apache server, and I still have the same issue, it works the same as it does on tomcat. Is there a server configuration I need to be aware of for my server to know that is should send a series of smaller requests as to a larger one? My code is the exact same for each one, just changing the URL.

**Comment by mnoyes68** [comment]
So a new thing that I realized, part of the issue may be the number of reads that exist in a given location. In the broad example, the data shows a range from 0-19 stacked reads in the section. For ours, we hav 1.5 million stacked reads. So I imagine we will begin downsampling. Does IGV js have a built in method to downsample a large sample like the ones I'm pulling?

**Comment by mnoyes68** [comment]
Also closing this issue because I realize this isn't a glitch with the server, its an artifact of my own huge reads

**Comment by jrobinso** [comment]
igv.js does downsample reads to prevent crashing the browser,  see the "Tracks" page in the documentation.   However it has to read them of course to downsample them,  so doing it in advance on the server is much more effecient.    You can reduce the "visibilityWindow" for the track so that it attempts to read a smaller region, again see the wiki doc for Tracks.
