### ISSUE TITLE
Problems moving track around

### ISSUE THREAD

**Issue by sveint** [igvteam/igv.js#734]
Hi,

using Chromium 69.0.3497.81 on Ubuntu I notice some really annoying dragging behavior. Basically, every now and then when dragging (moving) a track left and right, instead of firing off the normal mouse events, it would initiate a drag on the track itself. So instead of moving the position of the track, the mouse would then be dragging around a ghost image of the track in question.

After a lot of debugging I tracked it down to a missing css property
```css
.igv-viewport-container {
   user-select: none;
}
```
Adding this fixed the issue for me (also confirmed by adding it to the `css/igv.css` and recompiling igv.js). I can create a PR, but I wasn't sure whether this was the best solution to the issue?

**Comment by jrobinso** [comment]
Thanks for the report.   Yes I agree that property should be probably be set, will investigate.

**Comment by jrobinso** [comment]
Also,  many other minor bugs around mouse events have been fixed in the past few days.   Hopefully no new ones were introduced.
