### ISSUE TITLE
As of July 2018 apps with certain scopes must be approved by Google (read: IGV)

### ISSUE THREAD

**Issue by s-paquette** [igvteam/igv.js#735]
https://support.google.com/cloud/answer/7454865?authuser=0

This appears to be a project level setting.

**Comment by jrobinso** [comment]
Yes, I've tried to get help from Google people on this with no luck.   At some point IGV might just stop working.   I've expended a lot of time trying to get approval,  with no success.  At some point possibly soon IGV might just stopping working for Google resources.   There isn't anything I can do about it.

**Comment by jrobinso** [comment]
BTW,  if you are embedding igv.js in your own web application you will be using your own Google API Key and client ID.   From Google's point of view it is your app that needs approved, igv.js really isn't relevant.  The igv.js keys are only valid from the igv.org domain.

**Comment by s-paquette** [comment]
Woops, sorry Jim this was meant for a completely different GitHub repo. But thank you!

**Comment by jrobinso** [comment]
No problem, same problem here @s-paquette.
