### ISSUE TITLE
Embed only track(s) without header

### ISSUE THREAD

**Issue by anderspitman** [igvteam/igv.js#746]
Hi there. igv.js looks really good. We're working on adding a popup pileup view to [gene.iobio](http://gene.iobio.io/). I'm evaluating igv.js to see if it might work. The default view has far more information than we need. We really just need a pileup of the reads centered around a specific locus, with some basic colors to help evaluate alignment quality. From looking at the examples and glancing over the code, I'm not sure this is possible with igv.js as it currently is. Is that correct?

**Comment by jrobinso** [comment]
Have you looked at the documentation?
https://github.com/igvteam/igv.js/wiki/

**Comment by jrobinso** [comment]
Specially,  try setting showNavigation  and showRuler to false (
https://github.com/igvteam/igv.js/wiki/Browser-Configuration-2.0).   If
that doesn't do what you want this might not be the tool for you.

**Comment by jrobinso** [comment]
We'll look into the ruler.    If you don't want refseq genes define your own reference and don't supply any default tracks,  I assume you are using the genome ID shortcuts.

**Comment by jrobinso** [comment]
If you can sketch a mock-up of what you are trying to do I'll provide more guidance, if I can.

**Comment by anderspitman** [comment]
We're actually making great progress. I've successfully removed the RefSeq track using your instructions. It might not be necessary to remove the ruler. Gutting the ideogram might be nice since we're already indicating to the user outside the popup where they are in the genome.

**Comment by jrobinso** [comment]
Ah, found it.  try
  showControls: false,
  showIdeogram: false,
Looks like this is not documented,  I'll fix that.   Most of these options are listed in  "igv-create.js".

**Comment by anderspitman** [comment]
@jrobinso this is looking really good. We met today and agreed that the preliminary results are good enough to attempt embedding and see how it goes. Currently I'm having some strange CORS issues when igv.js tries to download this bam for an alignment track: `https://s3.amazonaws.com/iobio/samples/bam/NA12878.GRCh38.bam.bai`. It says the CORS server isn't providing the headers, but we use these files all the time from various apps. I'll double-check our configuration, but do you have any guesses what might be going on?

**Comment by jrobinso** [comment]
I just tried it and there are no CORS headers in the response.  Have you setup CORS for that bucket?  This issue only affects javascript apps.    You can see our Amazon settings here, scroll to the bottom:  https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements.     

Also see https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors

**Comment by anderspitman** [comment]
You're right. I put together a minimal fetch test and it can't access it either. I forgot that every time we access our bams we're actually doing so through our backend, which handles streaming and down-sampling. We must not have CORS configured on our buckets. Thanks!

**Comment by jrobinso** [comment]
Accessing your data through a webservice is also possible,  although it might require some customization on your end or in igv.js.

**Comment by anderspitman** [comment]
We shouldn't have a problem figuring out the data access side of things. Getting the visual part right was the greatest concern and you've been a big help with that.

**Comment by anderspitman** [comment]
I may have additional questions as I go along, but we're pretty close already.

**Comment by jrobinso** [comment]
OK, great, but long term if you have a back-end service we can use it.

**Comment by anderspitman** [comment]
Our backend requires a frontend library, ie it's not HTTP/REST. I'm sure it could be customized to work, as you say, but would most likely take some doing.

**Comment by jrobinso** [comment]
I think this issue has been resolved.

**Comment by anderspitman** [comment]
Hey @jrobinso I've almost got this working. I've created a Vue component for igv.js which you can see [here](https://github.com/anderspitman/vue-pileup). I'm trying to stick that component into a modal dialog, but for some reason if the dialog starts out hidden (display: none;), igv never renders. I'm currently debugging this but thought you might have some ideas.

**Comment by jrobinso** [comment]
Hi @anderspitman ,  yes that's a known problem.  There is no event fired when the display attribute changes.   The fix is to call igv.visibilityChange();  from your code whenever the modal becomes visible.  See examples/tabs.html,  different situation but the same issue.

**Comment by anderspitman** [comment]
Once again, the solution works beautifully. You guys really have built an impressively flexible tool here. Thanks again for all your help!

**Comment by anderspitman** [comment]
I might have spoken too soon haha. The reference and axes (for coverage and locus) aren't showing up when loading using igv.visibilityChange(). Any ideas?

**Comment by anderspitman** [comment]
More precisely, the canvas elements are there, but they all have height 0 except for the main view (even the loading icons don't show up). I'm looking through the visibilityChange code now to see if I can spot anything.

**Comment by jrobinso** [comment]
OK.  It was tested for tabs but not your situation.   Could you create a test case I can access and have a look?   

Also, after it appears, is the modal resizable?  If so try resizing it to see if that fixes it.   I'm not suggesting that is a viable solution, but it might be informative.

**Comment by anderspitman** [comment]
So actually it appears that your tabs demo doesn't work either. It looks like it might be specific to alignment tracks. To reproduce it add a bam track to tabs.html. I'm still debugging this and will be happy to do a pull request if I find a solution. Though obviously you know the code better and could likely fix it faster.

**Comment by anderspitman** [comment]
Also is there a way to do a faster debug build, as opposed to a full `npm run grunt`? Looking through the gruntfile it doesn't appear so but I figured I would ask.

**Comment by anderspitman** [comment]
Ok I think I've found the problem. Should probably move this discussion to #754.

**Comment by jrobinso** [comment]
@anderspitman RE debugging,  I just added a "quick-build" target that will build igv.js (only).   You can use this for debugging  ("grunt quick-build").

**Comment by jrobinso** [comment]
@anderspitman -- hmm, hold on,   don't use it yet -- there's a problem.   That will be the solution though, when I get it to work properly.
