### ISSUE TITLE
Ideogram (cytobands) not rendered

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#749]
Cytograms are not rendered correctly for some genomes,  example rn6

**Comment by yech1990** [comment]
the cytobands are in the wrong position for customized input.

**Comment by jrobinso** [comment]
@yech1990 that is not a useful bug report

**Comment by yech1990** [comment]
Sorry about that...

I create a cytoband file with a single record, and name it into `S288c.ideo.tsv`.
The contain of this file:

```
chrI	141908	162025	CEN1	gpos50
```

Then I render the ideogram in igv.js with these code:

```
      reference: {
        id: "S288C",
        name: "S. cerevisiae",
        fastaURL: xxxx
        indexURL: xxxx,
        cytobandURL: "/static/ref/cytoband/S288C.ideo.tsv"
      },
```

chrI is 219,929 bp in total, thus this customized feature is expected to be placed in the middle of the chromosome. But annotation always go into the terminal of the chromosome.

![image](https://user-images.githubusercontent.com/5415510/92766156-8ba3d480-f3c8-11ea-9102-519ffd387fde.png)

**Comment by jrobinso** [comment]
OK, it might be some time before I can look at this.   I am guessing a
workaround might be to put a record at the end of the chromosome, i.e.
ending at 219,929.  I suspect the code is taking the end of the last record
to be the extent, rather than the total length of the sequence from the
fasta file.

**Comment by jrobinso** [comment]
@yech1990 btw its best to create a new issue for a new problem we now have 2 issues mixed.
