### ISSUE TITLE
which function may I call to trigger redraw?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#756]
In my shinyApp, I sometimes rearrange widgets, sometimes giving igv a large portion or all of the screen, sometimes letting a DataTable dominate the display, sometimes hiding one or the other.  

igv does not seem to fully recognize this resizing, which I accomplish by changing the css class of its parent element.  When I manually resize my entire web browser, igv and  DataTables both arrange themselves nice.   Apparently manual resize triggers a cascade of redraw events which work their way down to the appropriate functions in igv and DataTable.

Is there an igv redraw function I can call directly?

**Comment by jrobinso** [comment]
Resizing dynamically by changing CSS classes is not going to trigger any
events igv.js can receive.   Try calling igv.visibilityChange(),  or
browser.resize();

**Comment by paul-shannon** [comment]
Solved, using your suggestion.   Thanks, Jim.

**Comment by Hamza-Yousuf** [comment]
i solved this issue by this browser.resize();
