### ISSUE TITLE
Add squish option to alignment track

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#758]

**Comment by iiiir** [comment]
Is squish/collapse option currently available for BAM files in igv-webapp?
I find some guidance in earlier discussions to define squish/expand options in the tracks.json file for individual tracks, but really want to be able to switch back-and-forth in the browser. 

![image](https://user-images.githubusercontent.com/4137873/80842607-e32e6a00-8bb6-11ea-9bab-f49e8b47e024.png)

Thank you,
Shuoguo

**Comment by chaninator** [comment]
@jrobinso Hello, is the expand option for BAM files being planned? I have only seen 1 or 2 posts about the matter but not much in the way of the past few years. Thank you!
