### ISSUE TITLE
customize IGV error

### ISSUE THREAD

**Issue by xinshuaiqi** [igvteam/igv.js#763]
Hi, 
I am trying to customize an IGV based on your github wiki. But not sure my steps are correct. Would you mind to provide some guidance?

1 clone the repo
> git clone https://github.com/igvteam/igv.js.git
cd igv.js
npm install
npm run grunt

2 edit the genomes.json file with my customized genome and tracks
>cd igv.js/resources
vim genomes.json

**3 What else should I do after that?**
I noticed the `igv.createBrowser` function in the https://github.com/igvteam/igv.js/wiki/Browser-Configuration-2.0, but not sure how to activate this function. 
I am not a javascript guy, so please provide guidance as specific as possible. 
Thank you.

**Comment by jrobinso** [comment]
Hi, why do you edit  the genomes.json file?   Where do you find that in the instructions?

igv.js is a javascript component for other developers to embed in their projects,  its use is fully documented in the wiki,  this is not an end-user tool.

**Comment by xinshuaiqi** [comment]
is it possible that IGV can't be used for genomes that aren't included in their reference set?

**Comment by jrobinso** [comment]
See https://github.com/igvteam/igv.js/wiki/Reference-Genome-2.0.   You need to supply a "reference" object in your configuration file, instead of a "genome" identifier.

**Comment by jrobinso** [comment]
Also see http://igv.org/web/release/2.0.0/examples/customReference.html,   or examples/customReference.html

**Comment by xinshuaiqi** [comment]
So how to create the configuration file, and where to put it? 
I don't see that from https://github.com/igvteam/igv.js/wiki/Reference-Genome-2.0

**Comment by jrobinso** [comment]
@xinshuaiqi If the examples and documentation are not enough this is not a component for you.

**Comment by xinshuaiqi** [comment]
Now it works for me. Thanks for your replies!
