### ISSUE TITLE
Issues with SVG output (pre-release testing)

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#765]
- [x] Whole Genome View - Ruler Track Not Drawn

- [x] No SVG file was created for the default view of this session: GTEX Eqtl multi-locus http://bit.ly/2CCK1DJ    If you zoom in to the point where the SNP track data loads and try the SVG again, then it is created correctly.

- [x] Axis label is drawn on each multi-locus panel, it should only appear on the left.  See screenshot below

- [x] We need a dividing line and/or gap between panels in multi-locus view

<img width="1484" alt="screen shot 2018-11-05 at 3 40 18 pm" src="https://user-images.githubusercontent.com/933148/48033728-4d289900-e111-11e8-80f6-a71ac7fbfc84.png">

**Comment by jrobinso** [comment]
RE the GTEX problem -- that session unfortunately has the dbSnp visibility window set to a value the browser just can't handle, leading to memory failures and random errors.    I set it to a lower value and it works fine,  try this session:   http://bit.ly/2yTDiBT.     

We need to protect from this somehow, perhaps by having a maximum window size allowed.

**Comment by turner** [comment]
closed with commit 0f8e46d0
