### ISSUE TITLE
More issues with SVG output (pre-release testing)

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#766]
- [x] Ruler sometimes messy (overlapping numbers)
- [x] Data range axes not drawn

- [ ] There's absolutely no separation or delimiter between panels in multi-locus view. Perhaps will look good enough if issue #764 is fixed.

- [ ] Centerline not drawn.

- [ ] Contact arcs not always the same as in the live IGV. See for example session http://bit.ly/2C8liWN . The SVG output of the initial view is fine. But zoom out and for some views the IGV arcs are much "shallower" than the SVG arcs.
- [ ] The scrollbar is not drawn (not sure if it even should be though).

**Comment by turner** [comment]
Closed with commit 9df2a857
