### ISSUE TITLE
Session files do not load from Google Drive.

### ISSUE THREAD

**Issue by turner** [igvteam/igv.js#767]
1) This is the programmatic URL for a session file hosted on Google Drive
`https://drive.google.com/file/d/1Uo6-wgoMSqdMi70YyqmoXX_hup8PKK8w/view?usp=drive_web`

2) This is the "Sharable Link" url:
`https://drive.google.com/open?id=1hJ-68Cci82ogSFU4c093JEkY1O7CTq7c`

1) is the url seen in code. 2) is the url seen in the GUI.

Both URLs can be pasted in the browser by hand and properly display the session json file.

**Comment by jrobinso** [comment]
@dturner The parameter on the end is incorrect (?usp=drive_web).  Try it without that.   I can't because the file has either been removed, or is private and not shared with me.  So please test and re-open if this is still a problem.
