### ISSUE TITLE
Track with scatter plot

### ISSUE THREAD

**Issue by robertaboukhalil** [igvteam/igv.js#770]
Hi there,

I'd like to show a track with a scatter plot of raw (non-segmented) copy number values across the genome. Is there a way to create a custom track type that would use functions like igv.graphics.fillCircle() to generate that plot?

Thanks!

Robert

**Comment by jrobinso** [comment]
Not currently but that's high on my list.  Actually  there are 2 things here.   (1)  a custom renderer, and (2) a "points" renderer for numerical data.   In igv.js numerical data is drawn in a "wig track".  

For custom rendering I think it would make sense to accept a function in the track config to do the rendering.   If you want to hack something up as a test you can try replacing "renderFeature" in feature/wigTrack.js,  line 212,  with your own function.   This is not time wasted as that is the function that will be configurable.

**Comment by jrobinso** [comment]
Custom track renderers are on my list,  but not available now.   However I am adding a "points" graphType option (UCSC lingo)  for "wig" type tracks.   I think this will do what you want,  the data would need to be in wig, bedGraph, or bigwig format.   Its configured as follows.   You can play with  this by pulling from master and building, or using igv.org/web/test/dist/igv.js.    Warning though, its not been thoroughly tested yet.

```
  {
    "url": "https://www.encodeproject.org/files/ENCFF754TJH/@@download/ENCFF754TJH.bigWig",
    "graphType": "points",
    "pointSize": 3,
    "name": "Encode bigwig points"
  }
```

**Comment by robertaboukhalil** [comment]
Thanks Jim, it looks great!

**Comment by jrobinso** [comment]
@robertaboukhalil  One caveat if using bigWig -- it will display aggregated values when zoomed out, that's the major point of the format and it works well with bar charts.     This is not usually what you want when viewing scatterplots, you want all the values.   For the time being this means using wig or bedgraph.    For large files you can tabix-index bedgraph.      

In the future I will probably make a change to fetch all raw data in view if graphType == points for a bigWig file.   I want to add some safety checks first so people don't freeze their browser with a huge download simply by changing graph type.
