### ISSUE TITLE
Display of long text string in Annotation track pop up

### ISSUE THREAD

**Issue by keithforest** [igvteam/igv.js#773]
I would like the user to be able to view a long text string from the 'Note' field of a gff3 file in the popup that occurs when hovering over a transcript.  Right now, the popup cuts the note field after ~30 characters.  Is there a way to show the entire text string?

**Comment by jrobinso** [comment]
Not currently,  I tagged it for the next release.     Put any thoughts on how to do that here.

**Comment by jrobinso** [comment]
@turner @helgathorv we need a solution for this.

**Comment by turner** [comment]
Closed with commit b1e948b
