### ISSUE TITLE
ES5 dist/igv.js file contains `const` keywork

### ISSUE THREAD

**Issue by dcardosods** [igvteam/igv.js#780]
I'm updating to latest version of IGV.js and have found this error in one of my app tests that run on PhantomJS "browser".

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at node_modules/igv/dist/igv.js:18670
```

The trouble line is at https://github.com/igvteam/igv.js/blob/master/vendor/canvas2svg.js#L267. Since it's on the `vendor` folder it's not being compiled by babel.

**Comment by jrobinso** [comment]
Thanks, will fix it.

**Comment by vrockai** [comment]
This is great! Do you plan to release a new version with this fix any time soon?
