### ISSUE TITLE
Get current locus

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#781]
Hi Jim, 

I'm sure I'm missing some already built in option somewhere, but is there a way to get the currently viewed locus through the API? This would be useful to add linkouts to UCSC and Ensembl for example?
All I'm looking for is the data displayed in the locus search box, so I can build op the URLs myself.

Thanks
M

**Comment by jrobinso** [comment]
Hi,  currently there is not a function.    I will add one.   In the meantime,  you can accomplish this with the following esoteric piece of code.    You can use this temporarily until the API is updated

```
    currentLocusString = function () {

        const locus = [];
        const anyTrackView = browser.trackViews[0];

        anyTrackView.viewports.forEach(function (viewport) {
            const genomicState = viewport.genomicState;
            const pixelWidth = viewport.$viewport[0].clientWidth;
            const locusString = genomicState.referenceFrame.showLocus(pixelWidth);
            locus.push(locusString);

        });
        return locus.join(' ')
    }
```

**Comment by matthdsm** [comment]
Hi Jim, 

Great! Thanks for the tip!

Cheers
M
