### ISSUE TITLE
queryParameters not working, error in wiki

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#782]
Hi Jim, 

I was having issues getting the `supportQueryParameters` option to work. On further investigation, I noticed that in the examples the option `queryParametersSupported` is used instead.

When using the latter, everything worked fine. I suppose this is a typo in the wiki? 
I'm using the latest dev version of igv.js, built today.

Cheers
M

**Comment by jrobinso** [comment]
Hi, sorry I missed closing this.  Yes it was a typo.
