### ISSUE TITLE
Viewport Hosted Track Data Popover is Not Properly Disposed Of.

### ISSUE THREAD

**Issue by turner** [igvteam/igv.js#783]
Any user interaction that requires deleting and then creating a viewport does result in proper deletion of the track data popover. The result is new instances popover are are continually being created.

**Comment by turner** [comment]
This branch has the fix https://github.com/igvteam/igv.js/tree/dat_git_issue_783_viewport_hosted_popover

**Comment by jrobinso** [comment]
@turner Was this ever merged?

**Comment by turner** [comment]
Closed with PR https://github.com/igvteam/igv.js/pull/867

**Comment by turner** [comment]
Yes this was merged. https://github.com/igvteam/igv.js/pull/867
