### ISSUE TITLE
bigWig reader possible constant typo

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#786]
https://github.com/igvteam/igv.js/blob/e6b71982f61e96a1f14697379ba13708a41977ea/js/bigwig/bwReader.js#L34-L35

Is it possible that `BIGWIG_MAGIC_HTL` last byte should rather be `0x88`?

**Comment by jrobinso** [comment]
Yes, its possible,  do you have a big-endian bigwig?   A small example would be good for the unit tests.

**Comment by romgrk** [comment]
No, just reading through the source, I don't have any available :/

**Comment by jrobinso** [comment]
I've never seen one.   I'm not sure how you would create one, on a PC maybe?   Those constants were copied from the original (Jim Kent's) "c" code, but there could have been a mistake of course.

**Comment by romgrk** [comment]
Probably on a big-endian machine, it wouldn't be OS dependent (I think). Sucks that the format didn't pick little-endian only :/

Kent's code [defines](https://github.com/ucscGenomeBrowser/kent/blob/master/src/inc/sig.h) only the little-endian magic and does the [swapping](https://github.com/ucscGenomeBrowser/kent/blob/master/src/lib/bbiRead.c#L54) with code, so it must have been swapped incorrectly when rewriting it.

**Comment by jrobinso** [comment]
OK well if you encounter one or have a test case let me know.   Otherwise, I don't know what to do with this issue.
