### ISSUE TITLE
Possible default param wrong initialization

### ISSUE THREAD

**Issue by romgrk** [igvteam/igv.js#788]
https://github.com/igvteam/igv.js/blob/e6b71982f61e96a1f14697379ba13708a41977ea/js/binary.js#L30-L32

Param `littleEndian` could be `false`. The correct way to initialize would be `littleEndian !== undefined ? littleEndian : true`.

Edit: basically, it's impossible to set it to false currently (even though big-endian bigwigs aren't tested against)

**Comment by jrobinso** [comment]
Yes,  you are correct.   Will fix it.
