### ISSUE TITLE
Issue with using the web-browser zoom in when viewing whole genome.

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#789]
When in whole-genome view, use the web browser's zoom-in control (e.g. command plus in safari on Mac) and the data panel is zoomed in, but there's no way to pan in whole genome view so that doesn't make sense. Also the whole-genome ruler is now off.

Before zoom-in
<img width="1307" alt="screen shot 2018-11-07 at 6 05 06 pm" src="https://user-images.githubusercontent.com/1265859/48166807-bc3ff200-e2b7-11e8-95c6-f23fd7ede45d.png">
After zoom-in
<img width="1307" alt="screen shot 2018-11-07 at 6 04 08 pm" src="https://user-images.githubusercontent.com/1265859/48166811-c104a600-e2b7-11e8-8c24-04068b702a13.png">

**Comment by jrobinso** [comment]
@turner I would look at browser.resize(), is it called on a browser (as in web browser) zoom,  and what is done when it is called and you are zoomed all the way out.  Either bpPerPixel is not calculated correctly,  or the canvas image is scaled in some way we don't expect.  

@helgathorv Isn't this also an issue at whole chromosome view if you are zoomed all the way out?

**Comment by turner** [comment]
Potential bug fix. See PR https://github.com/igvteam/igv.js/pull/791

**Comment by turner** [comment]
Fix with commit 508de822
