### ISSUE TITLE
Feature: reference genome with multiple id's

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv.js#793]
Hi Jim,

Would it be possible to support multiple genome id's for reference genomes?
e.g.
```
"id": ["hg19", "GRCh37"]
```
or to add an id alias to avoid breaking changes, e.g.
```
"id":"hg19",
"alias":"GRCh37"
```

This way, users could access reference genomes with both names, without having to know under which id a genome was added.

Thanks
M

**Comment by jrobinso** [comment]
I'll give it some thought,  but I'm not sure those are exactly identical.   The sequence for the main chromosomes are,  but the names differ (1 vs chr1),  and I'm not sure all the many minor sequences (the ones no one looks at) are the same, they definitely aren't named the same.   I think this might open a can of worms and be confusing.     In the meantime, you can just create 2 entries identical except for ID to accomplish that.

**Comment by jrobinso** [comment]
Well,  actually I just looked at UCSC and they list those as equivalent.  I had thought there were some minor differences in the assemblies, although the sequences for the main chromosomes are the same.  So yes this looks reasonable, probably like this, to allow multiple aliases

```
 "id":  "hg19"
 "aliases: "["GRCh37"]
```

Or is that too much flexibility?  Perhaps just allow 1 alias?
