### ISSUE TITLE
Separate variants by sample id?

### ISSUE THREAD

**Issue by anderspitman** [igvteam/igv.js#796]
Is there any way to filter variants by sample id, ie if you wanted to show a variant track with only variants from NA12878 but your vcf has samples from other individuals as well? I'm guessing this isn't possible, but wanted to check, since normal igv has a view for this:

![image](https://user-images.githubusercontent.com/7820200/48512770-8484fd00-e817-11e8-8a45-a3224627bcb3.png)

**Comment by jrobinso** [comment]
Not yet, but its an important topic.  We have done some prototype work on the general issue of filtering samples in the context of STR vcf files, but its not ready for release.     If you could articulate a use case here please do.   We do not have to follow IGV desktop exactly in this regard, which I think relies on sample information files.

**Comment by jrobinso** [comment]
@anderspitman -- for your present use case does this need to be dynamic, or would it be set in the track configuration?    I'm thinking along the lines of setting an array of sample names in the VCF track configuration to filter,  either keep or exclude.

**Comment by jrobinso** [comment]
@anderspitman Ahh, reading through the issue referenced this looks like a configuration parameter.  This is much easier.   Something like

   ``` includeSamples: ['NA12878',  'NA12879', 'NA12878']```

Actually this exists exactly for the (now deprectated) GA4GH API,   readGroupSetIDs === includeSamples.    

```
  {
    "sourceType": "ga4gh",
    "type": "bam",
    "url": "https://genomics.googleapis.com/v1",
    "readGroupSetIds": "CMvnhpKTFhCjz9_25e_lCw",
    "height": 200,
    "autoHeight": false,
    "viewAsPairs": false,
    "name": "Ga4gh alignments"
  }

**Comment by anderspitman** [comment]
@jrobinso if I'm understanding you correctly, this sounds like exactly what we need. As long as you can set the visible sample ids for each variant track individually, I can use that to insert a separate variant track for each sample we want to look at.

**Comment by jrobinso** [comment]
OK,  I'll get this in soon.

**Comment by anderspitman** [comment]
Awesome, thanks! No rush on it. This is not a big blocker for us, just a really nice-to-have

**Comment by jrobinso** [comment]
@anderspitman I've marked it for our next feature release, so it won't get forgotten, but if you need it sooner ping here again.

**Comment by anderspitman** [comment]
@jrobinso just wanted to follow up and let you know we changed our design (for unrelated reasons) and this has a reduced priority for us now (wasn't high to begin with), and we may not end up needing it at all.

**Comment by jrobinso** [comment]
@anderspitman OK thanks for letting me know but I am going to add it anyway,  its useful.   It is, however, inefficient to load a large # of genotypes then filter out most of them.

**Comment by jrobinso** [comment]
re-open if this is needed,  I've got 60+ open issues, time to trim.
