### ISSUE TITLE
Extract sequence and enable split window view

### ISSUE THREAD

**Issue by lye2** [igvteam/igv.js#806]
We have setup the IGV browser and successfully loaded various files. We have two questions:
(1)  Is there a function to extract genome sequence from the web browse? 
(2) When the mate of a read is mapped to a different chromosome, the split window view shows the right coordinates of the mate but the wrong chromosome name, which is the same as the read. 

Could you please see if you can help with them?

**Comment by jrobinso** [comment]
@lye2 Thanks for your report.  Always include the version of igv.js you are using, or if you built it yourself from which branch.

(1) -- no there is not
(2) -- that is definitely a bug.   I will leave this issue open until we fix it.

**Comment by jrobinso** [comment]
We can consider adding consensus sequence for alignment tracks,  please open a new git issue for that.   However, what do you mean by "genome sequences"?     Please describe your use case in more detail.

**Comment by lye2** [comment]
Sure. When fixing the split window view, please note that the reads are colored with different colors when their mates are mapped to different chromosomes.

**Comment by jrobinso** [comment]
RE coloring, you are referring to IGV desktop.  Yes I know that I developed
both views,  they don't do that yet in igv.js.   Its on my list.
