### ISSUE TITLE
Mutation track supporting the cBioPortal mutation data format

### ISSUE THREAD

**Issue by onursumer** [igvteam/igv.js#811]
A mutation track supporting the cBioPortal mutation data format would be ideal. Probably, something similar to the track for CIViC variants (http://bit.ly/2E5gRx4) would work for this.

See https://github.com/cBioPortal/cbioportal/issues/5392#issuecomment-445047200 for an example cBioPortal webservice query and response data.

**Comment by onursumer** [comment]
@jrobinso any update on this one?

**Comment by jrobinso** [comment]
No.   We might schedule this for our next "set aside" project, which is due to start shortly.     Will be in touch on that.

**Comment by jrobinso** [comment]
Finally we have an appropriate track type, "mut", which makes this easy.   I answered on the cBioPortal issue but will repeat here.  The basic idea is to query for features first, then supply these explicitly when configuring the igv.js track.

```

    import igv from "igv.esm.js";   // <- point to your copy

    igv.createBrowser(igvDiv, {genome: "hg19", showSampleNames: true})

        .then(async function (browser) {

            const sampleIds = ["TCGA-04-1331-01", "TCGA-04-1332-01", "TCGA-04-1336-01", "TCGA-04-1337-01", "TCGA-04-1338-01", "TCGA-04-1342-01"];

            const features = await fetchMutationData(sampleIds);

            browser.loadTrack({
                name: "cBIO mut example",
                type: "mut",
                features: features,
                height: 100,

            })

        })

    async function fetchMutationData(sampleIds) {

        const url = "https://www.cbioportal.org/api/molecular-profiles/ov_tcga_pub_mutations/mutations/fetch?projection=DETAILED";
        const body = JSON.stringify({"sampleIds": sampleIds});
        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: body
        })
        const json = await response.json();

        // Map to igv.js required attributes.
        for (let j of json) {
            j.start = j["startPosition"] - 1;
            j.end = j["endPosition"];
            j.sampleKey = j["uniqueSampleKey"];
            j.sample = j["sampleId"];
            j.value = j["mutationType"];  // This is somewhat arbitrary, "value" is used to set color
        }

        return json;
    }
```

**Comment by onursumer** [comment]
@jrobinso Thanks for the update!

When I try the example above I get an error message saying `Unknown file type: undefined`. Has this feature been included in the latest release or is it still in one of the development branches?

**Comment by jrobinso** [comment]
@onursumer I have no idea that was over a year ago,  which in return was responding to your mention a year before that.   I will short-circuit this pattern and investigate now, rather than wait a year :).

**Comment by jrobinso** [comment]
@onursumer Please see dev/cbio/cBioMut.html in the repository for a working example.    If after review you still have issues I will need to see your example code.

**Comment by onursumer** [comment]
@jrobinso I was able to make the example code work locally, thanks!

**Comment by onursumer** [comment]
@jrobinso Is there a way to customize the mutation colors? Ideally, we would like to map mutation types to certain fixed colors? Currently, coloring seems somewhat random each time IGV renders.

**Comment by jrobinso** [comment]
You can use a function for the track color, as shown below.   Also, if you could give me a table of type->color that would be helpful, perhaps I can make it the default.  

Example of using a function for color

```

            browser.loadTrack({
                name: "cBIO mut example",
                type: "mut",
                features: features,
                height: 50,
                color: function(f) {
                    const type = f.mutationType
                    if("Missense_Mutation" === type) {
                        return "red"
                    } else {
                        return "blue"
                    }
                }

            })
```

**Comment by jrobinso** [comment]
Having said this, they should not be random.   This is the default color table for track type "mut".  It is keyed off the "value" field for the feature, which you need to set since you are bypassing the "mut" parser.  Note in my example this value is set in fetchMutationData as follows

```
           j.value = j["mutationType"];  // This is somewhat arbitrary, "value" is used to set color
```

Default color table, overridable via the track property "colorTable"

```
    "indel": "rgb(0,200,0)",
    "targeted region": "rgb(236,155,43)",
    "truncating": "rgb(	150,0,0)",
    "non-coding transcript": "rgb(0,0,150)",

    // Colors from https://www.nature.com/articles/nature11404
    "synonymous": "rgb(109,165,95)",
    "silent": "rgb(109,135,80)",
    "missense_mutation": "rgb(72,130,187)",
    "missense": "rgb(72,130,187)",
    "splice site": "rgb(143,83,155)",
    "splice_region": "rgb(143,83,155)",
    "nonsense": "rgb(216, 57,81)",
    "nonsense_mutation": "rgb(216, 57,81)",
    "frame_shift_del": "rgb(226,135,65)",
    "frame_shift_ins": "rgb(226,135,65)",
    "in_frame_del": "rgb(247,235,94)",
    "in_frame_ins": "rgb(247,235,94)",
    "*other*": "rgb(159,91,50)"
```

**Comment by jrobinso** [comment]
@onursumer You can use the function, but you can also just explicitly set a color for each feature, or set a colorTable for the track and use some other property for "value". (other than mutationType).
