### ISSUE TITLE
Load specific samples

### ISSUE THREAD

**Issue by ShivaAlz** [igvteam/igv.js#814]
Hi,
Maybe there is this possibility already in the igv.js, but I'm not aware of it. Is there a possibility to just load/show specific samples in the segmented data track of igv (like giving a vector of desired samples to show)?
I really appreciate your help!

**Comment by jrobinso** [comment]
Sorry for the ridiculously long delay, I'm sure you have another solution by now.   This is implemented and will be released in 2.7.0.  Example below
```
                {
                    name: "Specific samples",
                    type: "seg",
                    format: "seg",
                    displayMode: "EXPANDED",
                    url: "https://s3.amazonaws.com/igv.org.demo/GBM-TP.seg.gz",
                    samples: [
                        "TCGA-02-0001-01C-01D-0182-01",
                        "TCGA-02-0003-01A-01D-0182-01",
                        "TCGA-02-0006-01B-01D-0182-01",
                        "TCGA-02-0007-01A-01D-0182-01",
                        "TCGA-02-0009-01A-01D-0182-01"]
                }
```
