### ISSUE TITLE
Enable supportsWholeGenome (all) view for BED/GFF files

### ISSUE THREAD

**Issue by blajoie** [igvteam/igv.js#820]
Would it make sense and or be possible to add support for 'supportsWholeGenome' (all) views of BED / GFF files?

Thinking about CNVs and utilizing a genome-wide view of all called events.  The file would be relatively small (1,000 - 10,000 entries) and would contain a pre-defined color according to the event type.

**Comment by jrobinso** [comment]
bed, gff, and other annotation tracks do support whole genome unless they are indexed.

**Comment by jrobinso** [comment]
@blajoie I'm not sure what to do this one as its already supported,  but I assume you are having some issue with it.

**Comment by jrobinso** [comment]
@blajoie ping,  what issue if any are you having here?

**Comment by blajoie** [comment]
Hi Jim - it could very simply be the fact that I am using compressed / indexed files. Had hoped to get to this before the holiday break but ran out of time. Just getting back from a long hiatus now - will f/u on Monday with more details.

**Comment by blajoie** [comment]
@jrobinso - sorry for the delay!

seg.gz and bigwig are working AOK for genome-wide, but I still cannot seem to get any *.bed to work, perhaps I am just not setting a track config param? (tried various visibilityWindow values, setting index:false, setting supportsWholeGenome:true etc without much luck)

Would it also be possible to also add GW support for compressed and indexed files IF the supportsWholeGenome param is set to true?  We generally try to compress and index all files in our genomic builds, so while some of the bed/gff files are quite small and could be fully loaded in, we'd still prefer to keep everything bgz+tbi to enable slicing access via s3 for a range of other tools.

test bed file below.

```
{
                    url: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeBroadHistone/wgEncodeBroadHistoneGm12878H3k4me3StdSig.bigWig',
                    name: 'GM12878 H3K4me3',
                    color: 'rgb(200,0,0)',
                    autoscaleGroup: '1',
                    graphType: 'points'
},
{
                    name: "CNV GW",
                    type: "annotation",
                    format: "bed",
                    url: "https://s3-us-west-2.amazonaws.com/ilmn.igv-test/afa1eee3f3244d4b8d532bb8123f35c1.cnv.bed",
                    order: 1,
                    visibilityWindow: 3000000000,
                    supportsWholeGenome: true,
},
{
                    url: 'https://data.broadinstitute.org/igvdata/test/igv-web/segmented_data_080520.seg.gz',
                    indexed: false,
                    isLog: true,
                    name: 'Segmented CN'
}

```

**Comment by jrobinso** [comment]
@blajoie There was a bug,  found just yesterday, that broke the WGV for some files.   I don't know when you tested but do a pull and try again. 

To see whole genome view for indexed files set "indexed: false".   You won't get any benefit to the index in igv if you view whole genome.    It doesn't matter if the file is actually indexed or not.    At least it shouldn't,  there might be some problem with the bgzipped files but there shouldn't be.  Try that anyway, if it doesn't work open a new git issue.

**Comment by blajoie** [comment]
Awesome, *.bed works for WGV now.  Thanks!  

bed.gz now also work as long as I add the indexed:false and set the visibilityWindow to a large enough value.

```
{
                    name: "CNV GW BED",
                    type: "annotation",
                    format: "bed",
                    url: "https://s3-us-west-2.amazonaws.com/ilmn.igv-test/afa1eee3f3244d4b8d532bb8123f35c1.cnv.bed",
                    order: 1,
                    indexed: false,
                    visibilityWindow: 30000000000,
                },
                {
                    name: "CNV GW BED.GZ",
                    type: "annotation",
                    format: "bed",
                    url: "https://s3-us-west-2.amazonaws.com/ilmn.igv-test/afa1eee3f3244d4b8d532bb8123f35c1.cnv.bed.gz",
                    indexURL: "https://s3-us-west-2.amazonaws.com/ilmn.igv-test/afa1eee3f3244d4b8d532bb8123f35c1.cnv.bed.gz.tbi",
                    order: 1,
                    indexed: false,
                    visibilityWindow: 30000000000,
}
```

**Comment by jrobinso** [comment]
I'm not sure why viz window would affect WGV,  I'll look at that.    You can leave viz window off altogether to see everything all the time.

**Comment by blajoie** [comment]
Hi Jim,

Re-opening this one.  Any insights into why the viz-window would affect WGV?
Still seeing the same effect in the latest master.

And does indexed:false cause the entire track to be loaded into mem during init?

When I want to view a track for the WG, there is no getting around loading the entire track into mem.  But it would be great if this would only happen when the users explicitly asks to view WG.  

i.e. can igv always use the index and only load into mem what is requested?  If I only request a 500kb slice on chr5, I would prefer to not have the WG sitting in mem.  Can WG only be loaded if/when the user requests WG view? (and then either cached or cleared after the user then navigates away from WG?)

TIA

**Comment by jrobinso** [comment]
Hi Brian,  "whole genome" is obviously not stored in the BED or GFF file,
it is computed and to see that you have to load the entire file.    So you
will not see whole genome view with indexed files, or files with a
visibility window set.

Could you clarify what it is you want to do?  Again if you want to use an
index you can't see "whole genome view",  if you don't use an index you
should see whole genome view automatically.    Setting a visibility window
without an index really doesn't make sense, and is not something I have
considered, but it would likely turn off whole genome view as well.


Jim

**Comment by blajoie** [comment]
Thanks Jim - 

Our use case:
All tracks we use are compressed + indexed (bed, bedgraph, bedpe, etc).  For some, we would like the ability to view the data for the WG (e.g. a bed file of all CNV/SV events).  But we do not want to to have to set indexed:false to enable this feature (as there is a performance hit).  Only rarely would a user want to view the WG, so we are looking to only load the entire file when the use makes the explicit request to view WG.  When the user is requesting small intervals, it would be preferable to use the index and keep the mem usage low (optimizing for 90% of use-cases).

e.g. being able view the WG w/ visibilityWindow:1000000000 and indexed:true.  I understand that this would cause the entire chromosome to be loaded no matter the interval size request (or could this be changed?), but perhaps that would be better than pre-loading in the entire file via indexed:false?

Hope that is clear!

**Comment by jrobinso** [comment]
Hi Brian,
If a file is sparse enough to make any sense at all at whole genome view then it doesn't need to be indexed.    How many features typically do you have in the files you want to view this way?   Whole genome views just break down after a few hundred features, no screen real estate,  a file with even a tens of thousands does not really need to be indexed.   Why not just turn indexing off?    

I don't have a quick solution other than that.   Before moving on to something more complicated, which will be hard to prioritize in any event,  I would like to know why the simple solution doesn't work.
