### ISSUE TITLE
Reference genome

### ISSUE THREAD

**Issue by yancychy** [igvteam/igv.js#824]
Hi, 
  In the Wiki, there are four hosted genome for IGV.js.  I just want to know whether you also provide other hosted genome? Thanks . 

Best regards,
Yang Chen 
id = "hg38"
id = "hg19"
id = "hg18"
id = "mm10"

**Comment by jrobinso** [comment]
That list was out of date,  I just updated it.   For the current list and
more details see  https://s3.amazonaws.com/igv.org.genomes/genomes.json

If you need a particular genome open a new issue for it.  If its not hosted
at UCSC include links to a fasta file,  plus any annotation tracks that
should be loaded.

**Comment by yancychy** [comment]
Great. Thanks very much.
