### ISSUE TITLE
Exon is UTR

### ISSUE THREAD

**Issue by dtsamitros** [igvteam/igv.js#827]
https://github.com/igvteam/igv.js/blob/91d4398e1dea0ff5128b98c5cb2c00539ad52564/js/feature/featureParsers.js#L569

Shouldn't this line be:

```js
if (feature.cdStart > eEnd || feature.cdEnd < eStart) exon.utr = true; 
```

much like

https://github.com/igvteam/igv.js/blob/91d4398e1dea0ff5128b98c5cb2c00539ad52564/js/feature/gffHelper.js#L333

**Comment by jrobinso** [comment]
Yes!  Thanks
