### ISSUE TITLE
how to show loops? 

### ISSUE THREAD

**Issue by yancychy** [igvteam/igv.js#828]
Hi, 
     I tired to visualize the loop in IGV.js.  The format of bed file is like following:
track graphType=arc
chr10	100008333	100068333	loop
chr10	100005000	100155000	loop
     But the result is not arc. I am not sure where is wrong. 
     Can you help me to visualize it? 
Thanks.

**Comment by jrobinso** [comment]
Hi, we don't yet support arcs from bed files, only bedpe files.   This is scheduled for the 2.1 release early in the new year.

**Comment by jrobinso** [comment]
Yes, that uses bedpe files (not bed files).    For bedpe files it will
connect a loop between the centroid of each side.

**Comment by yancychy** [comment]
Thank you very much. I will try bedpe.

**Comment by yancychy** [comment]
But I checked the Wiki, there is no bedpe. 

type = 'annotation'

File Formats
bed
gff
gtf
genePred
genePredExt
peaks
narrowPeak
broadPeak
bigBed

**Comment by jrobinso** [comment]
Its not officially released yet.
