### ISSUE TITLE
track info dialog mostly obscured (when an additional div is to the right)

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#829]
This may be my problem to solve, but perhaps you will have some suggestions.

When igv.js displays in a div which fully occupies the right border of the browser window, the track info dialog displays nicely.  See the first image below.   But when there is an additional div to the right of igv, the track info dialog is largely obscured.  See the second image below - which uses Shiny, which in turn (I think) uses bootstrap.  Perhaps the placement of the dialog is calculated with window width, rather than the width of the enclosing div?

![image](https://user-images.githubusercontent.com/2480712/50607591-8fa2f380-0e7e-11e9-8dde-3225e51b2b11.png)

![image](https://user-images.githubusercontent.com/2480712/50607383-dd6b2c00-0e7d-11e9-8cc7-5528e919da63.png)

**Comment by jrobinso** [comment]
I noticed a similar problem while working in igv.js-jupyter.  This is an igv bug.  @turner is out of town until next week,  we'll look at it then.

**Comment by jrobinso** [comment]
I think this is fixed, correct @turner ?

**Comment by turner** [comment]
Yes. Via https://github.com/igvteam/igv.js/pull/833
