### ISSUE TITLE
Alert message weirdness

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#835]
The alert message  (browser.presentAlert) can look weird for long messages.   Also, it would be nice to be able to pass html into this method to style the message a little.
<img width="254" alt="screen shot 2019-01-14 at 5 55 27 pm" src="https://user-images.githubusercontent.com/933148/51154042-5af04e00-1827-11e9-950f-bd3370941dc4.png">

**Comment by turner** [comment]
Closed with commit ec16067
