### ISSUE TITLE
BAM index file "is not a bai file"

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#843]
I've been trying to get igv.js working, and the test files all work just fine but I keep running into an error trying to use my own files that `[sample_name].bam.bai is not a bai file`.  Tracing the error back, it looks like my `magic` value matches `TABIX_MAGIC` for the `.bam` file but doesn't match for my `.bam.bai`. I get the same error trying to use associated `fasta` and `fasta.fai` files. Any tips on why this would happen or how to fix?

**Comment by jrobinso** [comment]
Are you able to load this bam file in other tools?

**Comment by athomson-archerdx** [comment]
Yes, I can open it via JBrowse through the server and open it in IGV desktop app locally.

**Comment by athomson-archerdx** [comment]
Here's the entirety of my test page and the files I'm trying to load:

```
<div>
    <span>This is to test igv.js</span>
    <button onclick="test_igv();">Test IGV.js</button>
</div>
<div id="igv-div">

</div>
<script src="https://cdn.jsdelivr.net/npm/igv@2.2.1/dist/igv.min.js"></script>
<script>
let igvDiv = $("#igv-div");
let options = {
    genome: "hg19",
    locus: "chr3:128,525,254-128,525,284",
    tracks: [
        {
            name: "TEST BAM",
            sourceType: "file",
            url: "HOOK3_11_RET_12_R1.molbar.trimmed.deduped.bam",
            indexURL: "HOOK3_11_RET_12_R1.molbar.trimmed.deduped.bam.bai",
            type: "alignment",
            format: "bam"
        }
    ]
};

function test_igv(){
    igv.createBrowser(igvDiv, options)
                .then(function (browser) {
                    console.log("Created IGV browser");
                })
}
</script>
```

[Fusion Smoke Test.zip](https://github.com/igvteam/igv.js/files/2789376/Fusion.Smoke.Test.zip)

**Comment by jrobinso** [comment]
It works for me, no issues, source below

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">

    <title>igv.js</title>

    <!-- IGV JS-->
    <script src="https://cdn.jsdelivr.net/npm/igv@2.2.1/dist/igv.min.js"></script>
</head>
<body>
<div id="igv-div"></div>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {

        let igvDiv = document.getElementById("igv-div");
        let options = {
            genome: "hg19",
            locus: "chr3:128,525,254-128,525,284",
            tracks: [
                {
                    name: "TEST BAM",
                    sourceType: "file",
                    url: "HOOK3_11_RET_12_R1.molbar.trimmed.deduped.bam",
                    indexURL: "HOOK3_11_RET_12_R1.molbar.trimmed.deduped.bam.bai",
                    type: "alignment",
                    format: "bam"
                }
            ]
        };

        igv.createBrowser(igvDiv, options)
            .then(function (browser) {
                console.log("Created IGV browser");
            })

    });
</script>
</body>
</html>
```

<img width="1524" alt="screen shot 2019-01-23 at 4 41 30 pm" src="https://user-images.githubusercontent.com/933148/51646544-d475f380-1f2d-11e9-89ea-e37f9cb37d26.png">

**Comment by jrobinso** [comment]
This could be an issue with your apache settings.  See https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements,  including the note on BAM mime type settings.    However, if that's the issue it should affect JBrowse as well.

**Comment by turner** [comment]
I have taken your config as is and used with local file paths and it works fine. I cannot reproduce this issue.

**Comment by athomson-archerdx** [comment]
Sorry, this is entirely my bad. I wasn't getting what I thought I was from the `indexURL` request - it was serving a rendered page instead of the file.

**Comment by 13269074211** [comment]
Hi, how do you solve the problem of not is a bai?

**Comment by 13269074211** [comment]
let options = {
        genome: "hg19",
        locus: "chr3:128,525,254-128,525,284",
        tracks: [
            {
              type: "alignment",
              format: "bam",
              name: "123",
              sourceType: "file",
              "url":"../../../../common/test/19C016624_WES002_CapNGS.rmdup.sorted.bam",
              "indexURL": "../../../../common/test/19C016624_WES002_CapNGS.rmdup.sorted.bam.bai"
            }
        ]
      };

**Comment by 13269074211** [comment]
creatIGV () {
      let igvDiv = document.getElementById('igv')
      let options = {
        genome: "hg19",
        locus: "chr3:128,525,254-128,525,284",
        tracks: [
            {
              type: "alignment",
              format: "bam",
              name: "123",
              sourceType: "file",
              url:"19C016624_WES002_CapNGS.bam",
              indexURL: "19C016624_WES002_CapNGS.bam.bai"
            }
        ]
      };
      let options =
        {
          "id": "hg19",
          "genome": "hg19",
          "name": "Human (hg19)",
          "fastaURL": "hg19.fa",
          "indexURL": "hg19.fa.fai",
          "cytobandURL": "hg19_cytoBand.txt",
          "tracks": [
            {
              type: "alignment",
              format: "bam",
              name: "123",
              sourceType: "file",
              "url": "10.10.1.82/ceshi/IGV/19C016623_WES002_CapNGS.rmdup.sorted.bam",
              "indexURL": "10.10.1.82/ceshi/IGV/19C016623_WES002_CapNGS.rmdup.sorted.bam.bai"
            }
          ]
        }
        console.log(options)
      igv.createBrowser(igvDiv, options)
        .then(function (browser) {
          console.log('Created IGV browser')
        })
    }

**Comment by athomson-archerdx** [comment]
@13269074211 My issue was that my request was returning a rendered page instead of the BAI file, once it was returning the file as it should it started working.

**Comment by 13269074211** [comment]
I also think it should be so that the file reference is no problem and our team confirms that no problem other software opens can also display normally. Only when I quote, it will be reported to 19C016623_WES002_CapNGS. rmdup. sorted. bam. Bai is not a Bai file. What is the possible cause of this problem? I looked at the error display of line 19412 if (magic == BAI_MAGIC | (tabix & Magic === TABIX_MAGIC)) and this error magic === BAI_MAGIC. Are they not equal, causing the problem of file errors or configuration errors?

**Comment by jrobinso** [comment]
I really don't know, and can't help you debug your server issues.   If you look at network traffic using Google chrome developer tools, or similar tools with other browsers,  it should be helpful.   Also please not that technically file paths are not supported at all, this is not possible in a browser, you must have a web server to serve these files.
