### ISSUE TITLE
Global css rules in igv.css?

### ISSUE THREAD

**Issue by devonbush** [igvteam/igv.js#844]
I installed igv using `yarn add igv` .  (which put igv ^2.2.1 in package.json)

and then imported it in my js with 

`import igv from 'igv/dist/igv.min'`

This brings in a css file specifies 
`* {
  -webkit-box-sizing: content-box !important;
  -moz-box-sizing: content-box !important;
  box-sizing: content-box !important; }

svg {
  max-width: 100% !important;
  height: auto !important; }

.igv-user-feedback {
 ... // remainder of igv-scoped rules
`
The global rules for * and svg are causing problems with my app--am I importing from the wrong place?  Or is there another way to get rid of those rules?

**Comment by devonbush** [comment]
ah, looks like importing from just `igv.min.js` fixes the issue, I didn't realize you didn't need the accompanying css files

**Comment by jrobinso** [comment]
@devonbush I don't use yarn,  what css files are included?  There shouldn't be any css files from the NPM distribution,  perhaps you had some remaining from a previous version?

If you are using ES6 import you need to use the ES6 module,  so it should be something like
```import igv from <path to dist>/igv.esm.min.js'```

I'm surpised using import with the non module package (igv.min.js) works

**Comment by jrobinso** [comment]
Oh, ouch,  I see now.   Those global rules are a mistake, apologies.   If you tell yarn to use version 2.2.0 they are not there.  We're working on removing them now, that should never have been released.

When I said there should be no css in the dist I meant "css" files.

I'm still puzzled that you can "import"  igv.min.js,  its not an ES6 module,  that's why we build igv.esm.min.js.   But that's another issue.

**Comment by devonbush** [comment]
Gotcha, thanks!  Yeah, I didn't fully understand how yarn imports work, and so thought it was bringing in a separate css file too, but the css node is being created from the js, like you say.  Thanks for your help and patience as we figured this out!

**Comment by jrobinso** [comment]
We removed the offending css, it was used to debug some issues in development we didn't intend to release that.   I will be doing a release for this tomorrow or this weekend,  in the meantime you can use 2.2.0 from NPM  or pull and build with "grunt".

I still don't understand how you can "import"  igv.min.js at all as its not an ES6 module.   Perhaps we don't need to make a module file  (igv.esm.min.js).
