### ISSUE TITLE
Annotation Track Mishandling Spaces in BED Name Column

### ISSUE THREAD

**Issue by dicara** [igvteam/igv.js#845]
We're providing a tab delimited BED file for the annotation track. If an annotation name contains a space, I would expect the whole name to appear with spaces. Instead, only that portion of the name prior to the space is displayed.

**Comment by jrobinso** [comment]
Is the name quoted?  Bed files are whitespace delimited, not tab delimited, so a space denotes a break between columns.

**Comment by jrobinso** [comment]
Have you tried displaying this file at UCSC?

**Comment by jrobinso** [comment]
I have an idea.   The overwhelming majority of bed files are tab delimited,  but we have seen space delimited files as well.   I think I'll change the parser to look for tabs, and if there are any tab-delimited parsing will be used.  This precludes mixing tabs and spaces as delimiters but that's o.k.

The track  line is always space delimited, btw.

**Comment by jrobinso** [comment]
Actually, you can specify the delimiter in the track config.  I had forgotten that.  Something like this should work with your files

```
 {
  type: 'annotation',
  format: 'bed',
  delimiter: '\t',
  url: '../test/data/bed/4_column.tabs.bed'
}
```

**Comment by dicara** [comment]
Thanks Jim! Adding a delimiter resolved my issue - I can now see annotations that contain spaces.

**Comment by odoublewen** [comment]
@dicara or @jrobinso  -- How do you get the label to show up in the browser track?  I also have 4-column tab-delim bed files, and I can see rectangles for all of my features, but when I click on them I can only see, e.g.:

![screen shot 2019-02-21 at 2 46 49 pm](https://user-images.githubusercontent.com/1421445/53207078-95e45f00-35e7-11e9-9a24-c3eb430d3ba6.png)

Is a header required?  I've tried with and without headers.  My bed file looks like [4_column.tabs.bed](https://github.com/igvteam/igv.js/blob/master/test/data/bed/4_column.tabs.bed). 

```
$ head protein_coding_genes_4col_header.bed
track name="Basic Features" color=255,0,0 height=50
chr1	65418	71585	OR4F5
chr1	450702	451697	OR4F29
chr1	685678	686673	OR4F16
chr1	923927	944581	SAMD11
chr1	944203	959309	NOC2L
```

And I'm specifying it like so:
```
      tracks: [
                     {
                        type: 'annotation',
                        name: 'protein_coding_genes_4col_header.bed',
                        format: 'bed',
                        delimiter: '\t',
                        url: 'https://dl.dnanex.us/F/D2/file-obfuscated',
                        headers: {"X-Authorization": "obfuscated"},
                    },
                   ]
```

Is there some setting to make the labels appear for bed files?  (I'm aware of `nameField` for gff files -- is there an analog for bed files?)

Maybe something needs to be set in `trackDefaults`?  The [browser configuration wiki](https://github.com/igvteam/igv.js/wiki/Browser-Configuration-2.0#browser-configuration-options) mentions `trackDefaults`:

> Option | Description
> -- | --
> trackDefaults | Embedded object defining default settings for specific track types (**see table below**).

But I can't seem to find any "table below" that pertains.

Thanks for any help!

**Comment by jrobinso** [comment]
@odoublewen You config is fine, that was a bug.  Just pushed a fix.

**Comment by odoublewen** [comment]
I built from source and can confirm that your fix works!  Thanks!
