### ISSUE TITLE
Enable Display of Verbose Annotation Names (e.g. via Hover)

### ISSUE THREAD

**Issue by dicara** [igvteam/igv.js#846]
We want to display user generated annotation labels that are often quite verbose. Even if a user clicks on the annotation, the name is abbreviated in the pop-up. As opposed to left/right labeling (as was suggested in https://github.com/igvteam/igv.js/issues/385), I was wondering if hover could be implemented. In other words, if a label doesn't fit under the annotation track, add as much of the label as will fit and suffix the label with an ellipsis to indicate it has been abbreviated. When a user hovers over the track, then the entire annotation label would appear.

**Comment by turner** [comment]
Closed with commit b1e948b
