### ISSUE TITLE
VCF overlay shows spurious link to CRAVAT for wrong locus 

### ISSUE THREAD

**Issue by GlyphDataServices** [igvteam/igv.js#848]
This can't be correct....
Load a VCF track with this variant. Clicking the variant brings up the following overlay.  The CRAVAT link on the bottom always seems to go to this BRAF variant instead of the actual variant call. 

http://www.cravat.us/CRAVAT/variant.html?variant=chr7_140808049_+_C_T

The variant call is at chr5:172915596

Chr chr5
--
Pos172915596
Namesrs145748219
RefC
AltT
Qual225
Filter.
Heterozygosity0.500
 
AC11
AC2
AF10.5
AN4
ANNT\|stop_gained\|HIGH\|ERGIC1\|ERGIC1\|transcript\|XM_011534598.2\|protein_coding\|6/8\|c.454C>T\|p.Gln152*\|622/1052\|454/852\|152/283\|\|,T\|stop_gained\|HIGH\|ERGIC1\|ERGIC1\|transcript\|XM_017009654.1\|protein_coding\|6/8\|c.526C>T\|p.Gln176*\|770/1200\|526/924\|176/307\|\|,T\|stop_gained\|HIGH\|ERGIC1\|ERGIC1\|transcript\|XM_017009655.1\|protein_coding\|6/8\|c.526C>T\|p.Gln176*\|763/1754\|526/840\|176/279\|\|,T\|intron_variant\|MODIFIER\|ERGIC1\|ERGIC1\|transcript\|XM_011534597.1\|protein_coding\|5/9\|c.447+758C>T\|\|\|\|\|\|,T\|intron_variant\|MODIFIER\|ERGIC1\|ERGIC1\|transcript\|NM_001031711.2\|protein_coding\|5/9\|c.375+758C>T\|\|\|\|\|\|,T\|intron_variant\|MODIFIER\|ERGIC1\|ERGIC1\|transcript\|XM_006714892.1\|protein_coding\|3/7\|c.99+758C>T\|\|\|\|\|\|,T\|non_coding_transcript_exon_variant\|MODIFIER\|ERGIC1\|ERGIC1\|transcript\|XR_001742159.1\|pseudogene\|6/11\|n.622C>T\|\|\|\|\|\|
ASPundefined
BQB0.625757
CAF0.9986,0.001398
COMMON1
DP462,42,54,44
DP268
FQ225.007
GENEINFOERGIC1:57222
INTundefined
KGPhase1undefined
KGPhase3undefined
LOF(ERGIC1\|ERGIC1\|7\|0.43)
MQ0F0
MQ60
MQB1
MQSB1
NMD(ERGIC1\|ERGIC1\|7\|0.43)
NSNundefined
PV40.690508,0.231545,1,1
REFundefined
RPB0.999948
RS145748219
RSPOS172915596
SAO0
SF0,1
SGB-0.693147
SSR0
TOPMED0.998042,0.00195755
VCSNV
VDB0.539818
VLDundefined
VP0x050000080605040036000100
WGT1
dbSNPBuildID134
 
Cravat C->T

**Comment by jrobinso** [comment]
Agreed, that can't be right.  WIll look into it.

**Comment by jrobinso** [comment]
Fixed

**Comment by GlyphDataServices** [comment]
> Fixed

Looks good from here 
(I see you also added config.filename in FeatureFileReader at some point :) 
Thanks much.
