### ISSUE TITLE
Indels VCF display position shifted

### ISSUE THREAD

**Issue by GlyphDataServices** [igvteam/igv.js#849]
Got another one for you....
Indels in a VCF track are sometimes shifted right of their called position. The call in the VCF matches up with the BAM alignments to the reference, but the rectangle representing the call is shifted. 

The VCF overlay text box shows the correct position which corresponds to the alignments.
This happens consistently in homopolymers but also in (seemingly) non-repeating sequences. 

![screenshot from 2019-01-27 12-56-45](https://user-images.githubusercontent.com/2752867/51804866-b5c87300-2233-11e9-85dc-86dcbc70d28e.png)

**Comment by jrobinso** [comment]
Interesting, but I'm not sure this is a bug,  it reflects an ambiguity in which "C" is missing.  The placement in the bam record is arbitrary,  as is the placement in IGV of the vcf record.   A better representation for both might be some representation spanning the entire homopolymer indicating that a base is missing somewhere.    The position field in a VCF files is the position of the reference allele (the "A" in this case).  

This is a hard one,  I could arbitrarily shift the vcf representation to match the convention in the alignment cigar string,  if that is a consistent convention.   If you have any information on this please let me know.   Also if you have other examples in non-repeating sequence post those.

**Comment by GlyphDataServices** [comment]
... one more thought to add- whether there is or isn't ambiguity around the mapping of a deletion with a short repeat, it should be consistent with the BAM in the positioning. I would recommend using the called position of the indel as the start position (I thought this was pretty standard, to  call the start position of a deletion?), rather than re-positioning the indel.

**Comment by jrobinso** [comment]
What's in the bam files is not relevant for the VCF track.   The only information that can be used are position, ref, and alt from in the VCF files.   Look at the VCF spec,  the position is the position of the reference allele, not the position of the variant.   Positioning of the variant is computed by a diff between alt and reference.     

What program created these VCF records? They actually look inconsistent with the BAM file to me.   That last case, for example, should list the alt as simply "G".    As shown it implies a deletion of "GTTA",  but the BAM record reflects a deletion of "TAGTTA".    I think that is the cause of what you are seeing.

**Comment by GlyphDataServices** [comment]
The confusion here seems to be related to the caller extending the ref allele beyond just one base to span the deletion. In these examples, it's doing this because on the other end of the deletion, the sequence is the same as the start sequence.   This is a little confusing but after looking at it again, I still think this is an incosistency issue in IGV.

In example 3, the call could be made in one of two ways:
 G**TAGT**TA -> G|TA
or 
 GT**AGTT**A -> GT|A

The BAM alignments are placed in the first manner.  The VCF call position also uses this method. 

IGV seems to be doing neither of these and instead subtracting the ref from alt and placing the box accordingly.  I haven't looked at exactly what's going on in the IGV code but it must be doing something like this rather than using the called variant position. 

The pipeline is BWA -> SAMTools -> BCFtools and iirc SAMtools is doing some indel recalibration.  

> What's in the bam files is not relevant for the VCF track. The only information that can be used are position, ref, and alt from in the VCF files. Look at the VCF spec, the position is the position of the reference allele, not the position of the variant. Positioning of the variant is computed by a diff between alt and reference.

Yes and for these calls, the call position is at the start of ref, which is where the reads are positioned, so if IGV would put the block at the start of the REF position, that would put the box in the right spot.

> 
> What program created these VCF records? They actually look inconsistent with the BAM file to me. That last case, for example, should list the alt as simply "G". As shown it implies a deletion of "GTTA", but the BAM record reflects a deletion of "TAGTTA". I think that is the cause of what you are seeing.

I think BCFtools is extending REF to surround the deletion to eliminate ambiguity from to the repeated sequence at start/end of the deletion.

**Comment by jrobinso** [comment]
Putting the block at the start of the REF position would potentially break many websites that have used IGV for a very long time, and would inconsitent with IGV desktop.   It would also shift the indel block to the left of the deletion for all simple deletions, as found for example in 1KG files.   IGV puts the block at the variant position,  its done this since the beginning of the 1KG project.  To change that would require getting a consensus from users and stakeholders, and I'm not sure this is the right forum to do that on.

**Comment by GlyphDataServices** [comment]
> Putting the block at the start of the REF position would potentially break many websites that have used IGV for a very long time,

To rephrase,  rather than looking at REF/ALT for the position, why not use the position of the call in the VCF?

**Comment by jrobinso** [comment]
@GlyphDataServices First,  all simple 1 based deletions, for sure,  would be positioned incorrectly.  Second, its been done this way for 8+ years now.  That doesn't mean its correct.    I need a rule consistent with the spec,  perhaps heng @lh3 will share some insight.  

And the position in the VCF file is the position of the reference,  it would be helpful I think to refer to it that way rather than "position of the variant" or "position of the call".    What you are suggesting is to ignore the alt-ref difference and just use that position,  obviously this only works for SNPs.   What is needed is a rule consistent with the specification.

**Comment by jrobinso** [comment]
@GlyphDataServices Let's start with something simple, and work up from there.   Let's see if we can make a rule for positioning the VCF block for a simple deletion such as

pos: 100
ref:  AC
alt:  A

From there it should be easy.

Currently IGV finds the variant position from "pos" (reference poistion) by subtracting the alt from ref, as you suggested.   What should the new rule be?

**Comment by jrobinso** [comment]
@GlyphDataServices I'm trying to absorbe Heng's general rule at the moment,  but need to stop for now.   I'll be back this evening.   In the meantime could you apply his rule to your examples and see if it would resolve them.

**Comment by GlyphDataServices** [comment]
> @GlyphDataServices I'm trying to absorb Heng's general rule at the moment, but need to stop for now. I'll be back this evening. In the meantime could you apply his rule to your examples and see if it would resolve them.

Ok thanks for your time. I think we have a good handle on the problem now.

**Comment by jrobinso** [comment]
@GlyphDataServices I think we do, but if you have time to work through Heng's rule application to see if it works give it a go.    I will try implementing it tonight.

**Comment by jrobinso** [comment]
@lh3 I think I got it, but can I restate your rule as follows?

The first base for both ref and alt is always the padding base,  so eliminate it first.

For remaining bases,  work from the end (right to left) eliminating identical bases.

> The REF is `GTAGTTA` and ALT is `GTA`. This should be thought as
> ```txt
> ref: GTAGTTA
> alt: G----TA
> ```
> You can see the general rule here: starting from the ends of both REF and ALT and eliminate identical bases.

**Comment by GlyphDataServices** [comment]
> I agree with @GlyphDataServices that this is a display issue. Take one of the screenshots as an example. The REF is `GTAGTTA` and ALT is `GTA`. This should be thought as
> 
> ```
> ref: GTAGTTA
> alt: G----TA
> ```
> 
> You can see the general rule here: starting from the ends of both REF and ALT and eliminate identical bases.

In this example, the issue is that it's not possible to say which T remains, the one at the start or end of the deletion. It could also be interpreted as:

> ref: GT**AGTT**A
> alt: GT----A

But given the choice, to be consistent with the BAM reads display, it should select the first possible interpretation of the call.

**Comment by lh3** [comment]
@jrobinso Yes, your statement is more accurate.

@GlyphDataServices 

> In this example, the issue is that it's not possible to say which T remains, the one at the start or end of the deletion. It could also be interpreted as:

You should eliminate all identical bases from the right. This leaves you with
```txt
ref: TAGT
alt: ----
```
i.e. one of REF and ALT is a pure gap. This works as long as the line describes a single indel. If after elimination, you don't get a pure gap, the VCF line is composed of two or more atomic events.

**Comment by GlyphDataServices** [comment]
@lh3 Agreed, right to left is the simplest way to describe it, and this is consistent with BAM reads display.

**Comment by lh3** [comment]
@jrobinso Another minor change to the rule, to make it more robust to incorrect records:

1. Eliminate the left-most base if they are identical (if not, the VCF line is non-compliant or it describes multiple events)
2. For remaining bases, work from the end (right to left) eliminating identical bases.
3. There should not be remaining bases given an atomic indel. If there are, work from the start again and eliminate identical bases.

The first two rules are the same as yours. The third rule deals with a problematic VCF line like:
```txt
ref: CGTAGTTA
alt: CG----TA
```
A proper variant caller shouldn't output a variant like this, but who knows what VCFs users may feed to IGV?

**Comment by jrobinso** [comment]
@GlyphDataServices Could you attach a VCF file with your 3 examples, or as many as you would like, for testing?  Thanks.

**Comment by GlyphDataServices** [comment]
@jrobinso sure thing.  There is a bgzipped vcf with just those indel calls, incl header + tabix index inside this zip.

[example-indels.zip](https://github.com/igvteam/igv.js/files/2801440/example-indels.zip)

**Comment by GlyphDataServices** [comment]
@jrobinso if you want more examples this has  all indels on chromosome 21
[example-indels2.zip](https://github.com/igvteam/igv.js/files/2801447/example-indels2.zip)

**Comment by jrobinso** [comment]
@GlyphDataServices thanks for the data files, but they are missing the mandatory #CHROM line.    I assume this is a copy/paste error?

**Comment by jrobinso** [comment]
@GlyphDataServices I created a #CHROM line, just letting you know.   I want to spend a bit of time testing tomorrow before pushing this.

**Comment by GlyphDataServices** [comment]
Ah my bad, I grepped ##  not # 

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  /var/runs/2018-01-29_21-14-19_GM1__MTgzNDgyMz/mapped-sorted-mkdup.bam   germline-variants-all-dbsnp_/var/runs/2018-01-29_21-14-19_GM1__MTgzNDgyMz/mapped-sorted-mkdup.bam

**Comment by GlyphDataServices** [comment]
> @GlyphDataServices I created a #CHROM line, just letting you know. I want to spend a bit of time testing tomorrow before pushing this.

I deleted and updated the files above with the #chrom line that was missing (in case anyone else comes along)

**Comment by jrobinso** [comment]
I implemented Heng's rule and it seems to work for the 4 examples in your test file, and a few non-conforming examples I made up.   

I do not understand why the extra padding on the right is needed.  In all these cases it looks like the same variant could be described unambiguously by simply removing the right padding from both alt and ref.  Perhaps its a signal to tools that a repeat is involved.

**Comment by GlyphDataServices** [comment]
@jrobinso 
console.log statement left on js/variant/variant.js:144
`console.log("Non-conforming VCF indel: " + JSON.stringify(variant));`

**Comment by jrobinso** [comment]
@GlyphDataServices That's normal, console.log statements are removed for the production build.  However, it is interesting if you are seeing log statements,  could you post the non-conforming variant?

**Comment by GlyphDataServices** [comment]
@jrobinso The default grunt task is leaving the comment in igv.min.js for whatever reason

Non-conforming VCF indel: 
{"chr":"chr1","pos":40374624,"names":".","referenceBases":"TGAGAGAGAGAGAGAGAGA","alternateBases":"TGAGAGAGAGAGAGAGAGAGA,TGAGAGAGAGAGAGA","quality":132,"filter":".","info":{"AC1":"1","AC":"2,0","AF1":"0.667194","AN":"4","ANN":"TGAGAGAGAGAGAGA|5_prime_UTR_variant|MODIFIER|SMAP2|SMAP2|transcript|NM_001198978.1|protein_coding|1/10|c.-57_-54delGAGA|||||54|,TGAGAGAGAGAGAGAGAGAGA|5_prime_UTR_variant|MODIFIER|SMAP2|SMAP2|transcript|NM_001198978.1|protein_coding|1/10|c.-55_-54dupGA|||||53|,TGAGAGAGAGAGAGA|intron_variant|MODIFIER|SMAP2|SMAP2|transcript|NM_022733.2|protein_coding|1/9|c.103+416_103+419delGAGA||||||,TGAGAGAGAGAGAGAGAGAGA|intron_variant|MODIFIER|SMAP2|SMAP2|transcript|NM_022733.2|protein_coding|1/9|c.103+418_103+419dupGA||||||,TGAGAGAGAGAGAGA|intron_variant|MODIFIER|SMAP2|SMAP2|transcript|XM_017002093.1|protein_coding|1/6|c.-85+416_-85+419delGAGA||||||,TGAGAGAGAGAGAGAGAGAGA|intron_variant|MODIFIER|SMAP2|SMAP2|transcript|XM_017002093.1|protein_coding|1/6|c.-85+418_-85+419dupGA||||||,TGAGAGAGAGAGAGA|intron_variant|MODIFIER|SMAP2|SMAP2|transcript|XM_011541960.1|protein_coding|1/10|c.-39+416_-39+419delGAGA||||||,TGAGAGAGAGAGAGAGAGAGA|intron_variant|MODIFIER|SMAP2|SMAP2|transcript|XM_011541960.1|protein_coding|1/10|c.-39+418_-39+419dupGA||||||","DP4":"0,2,14,6","DP":"62","FQ":"-31.528","IDV":"7","IMF":"0.166667","MQ0F":"0","MQ":"60","MQSB":"0.964642","PV4":"0.363636,0.397785,1,0.275259","SF":"0,1","SGB":"-0.670168","VDB":"0.0391189"},"alleles":["TGAGAGAGAGAGAGAGAGAGA","TGAGAGAGAGAGAGA"]}
igv-cjs.js:49705:40

Non-conforming VCF indel: `{"chr":"chr1","pos":54614939,"names":"rs71045199","referenceBases":"GGTGTGTGTGTGTGTG","alternateBases":"GGTGTGTGTGTG,GGTGTGTGTGTGTGTGTGTGTG","quality":72,"filter":".","info":{"AC1":"1","AC":"2,0","AF1":"0.500199","AN":"4","ANN":"GGTGTGTGTGTG|downstream_gene_variant|MODIFIER|ACOT11|ACOT11|transcript|NM_147161.3|protein_coding||c.*5839_*5842delTGTG|||||4619|,GGTGTGTGTGTGTGTGTGTGTG|downstream_gene_variant|MODIFIER|ACOT11|ACOT11|transcript|NM_147161.3|protein_coding||c.*5837_*5842dupTGTGTG|||||4623|,GGTGTGTGTGTG|intron_variant|MODIFIER|ACOT11|ACOT11|transcript|NM_015547.3|protein_coding|15/16|c.1629+6883_1629+6886delTGTG||||||,GGTGTGTGTGTGTGTGTGTGTG|intron_variant|MODIFIER|ACOT11|ACOT11|transcript|NM_015547.3|protein_coding|15/16|c.1629+6881_1629+6886dupTGTGTG||||||,GGTGTGTGTGTG|intron_variant|MODIFIER|FAM151A|FAM151A|transcript|NM_176782.2|protein_coding|3/7|c.416-95_416-92delCACA||||||,GGTGTGTGTGTGTGTGTGTGTG|intron_variant|MODIFIER|FAM151A|FAM151A|transcript|NM_176782.2|protein_coding|3/7|c.416-96_416-95insCACACA||||||,GGTGTGTGTGTG|intron_variant|MODIFIER|FAM151A|FAM151A|transcript|XM_006710599.3|protein_coding|4/8|c.338-95_338-92delCACA||||||,GGTGTGTGTGTGTGTGTGTGTG|intron_variant|MODIFIER|FAM151A|FAM151A|transcript|XM_006710599.3|protein_coding|4/8|c.338-96_338-95insCACACA||||||","DP4":"0,2,2,24","DP":"52","FQ":"-5.12076","GENEINFO":"ACOT11:26027|FAM151A:338094","IDV":"12","IMF":"0.461538","MQ0F":"0","MQ":"60","MQSB":"1","PV4":"1,1,1,0.346787","RS":"71045199","RSPOS":"54614954","SAO":"0","SF":"0,1","SGB":"-0.683931","SSR":"0","VC":"DIV","VDB":"0.0600954","VP":"0x050100080005000102000200","WGT":"1","dbSNPBuildID":"130"},"alleles":["GGTGTGTGTGTG"]}`

**Comment by jrobinso** [comment]
OK,  I'll look into that.  Are those records in the larger test file you gave me?   I think when I implemented Heng's rule  I neglected to account for insertions (alt base length > ref base length).   Further, this brings up another issue.  At what position does the BAM file (cigar)  indicate an insertion for this repeat?  I assume at the left end,  following the convention for deletions.

**Comment by lh3** [comment]
These are multi-allelic INDELs. To test conformity, you need to test each allele.

**Comment by jrobinso** [comment]
@lh3 yes, that also

**Comment by jrobinso** [comment]
@lh3 Also, I think the rule was that there should not be any "left over" bases (3. below) after matching,  which is not the case for an insertion.   

> 1. Eliminate the left-most base if they are identical (if not, the VCF line is non-compliant or it describes multiple events)
> 2. For remaining bases, work from the end (right to left) eliminating identical bases.
> 3. There should not be remaining bases given an atomic indel. If there are, work from the start again and eliminate identical bases.

**Comment by GlyphDataServices** [comment]
@jrobinso Ah yes in fact there are some in that chr21 example an the display is shifted
![screenshot from 2019-01-29 14-12-15](https://user-images.githubusercontent.com/2752867/51933779-1391c200-23d0-11e9-8840-79d5650dc17e.png)

**Comment by jrobinso** [comment]
@lh3 @GlyphDataServices got it -- rule works -- leftover alt bases are the insertion.

**Comment by jrobinso** [comment]
@lh3 @GlyphDataServices  The code was getting messy with too many special cases.   The following should hopefully work for all cases including snps.  This is done for each allele,  the total extent of the variant representation is the union of all the alleles.  

```
let altLength = alt.length;
let lengthOnRef = ref.length;

// Trim off matching bases.  Try first match, then right -> left,  then any remaining left -> right
let s = 0;
if (ref.charCodeAt(0) === alt.charCodeAt(0)) {
    s++;
    altLength--;
    lengthOnRef--;
 }

 // right -> left from end
 while (altLength > 0 && lengthOnRef > 0) {
     if (alt.charCodeAt(s + altLength - 1) === ref.charCodeAt(s + lengthOnRef - 1)) {
        altLength--;
        lengthOnRef--;
      } else {
        break;
     }
 }

 // if any remaining, left -> right
while (altLength > 0 && lengthOnRef > 0) {
    if (alt.charCodeAt(s + altLength - 1) === ref.charCodeAt(s + lengthOnRef - 1)) {
         s++;
         altLength--;
         lengthOnRef--;
    } else {
        break;
   }
}

alleleStart = variant.pos + s - 1;      // -1 for zero based coordinates
alleleEnd = alleleStart + Math.max(1, lengthOnRef)     // insertions have zero length on ref, but we give them 1

```

**Comment by GlyphDataServices** [comment]
@jrobinso This looks good so far.  Here's an oddball multi-allelic indel in a repeat.
PS After the update I can see that not having babel module installed was the cause of comments being left in the build.  
![screenshot from 2019-01-30 01-46-48](https://user-images.githubusercontent.com/2752867/51963805-a8c5a280-2432-11e9-8502-d8c13d95b50a.png)

**Comment by jrobinso** [comment]
@GlyphDataServices It's hard for me to comment without knowing what the VCF records are.   There can be distinct records at the same location,  this is different than a single record with multiple alleles,  I'm sure you know that.   There are 4 records shown there.

**Comment by jrobinso** [comment]
I think the major issue here was resolved long ago, if there are remaining issues please open a new issue,  with test data if possible.
