### ISSUE TITLE
Remove Google GA4GH references

### ISSUE THREAD

**Issue by mbookman** [igvteam/igv.js#851]
The demo here:

https://igv.org/web/current/examples/google-ga4gh-demo.html

No longer works. I'm not sure the specific cause of failure, but the Google GA4GH API is being turned down. See the deprecation notice here:

https://cloud.google.com/genomics/deprecation

Any part of IGV/IGV.js that used the Google Genomics reads or variants API can be removed.

An option for existing projects is use the existing capability in IGV.js to access BAMs and VCFs that are stored in Google Cloud Storage.

**Comment by mbookman** [comment]
FWIW, I found a working example at:

https://igv.org/web/examples/google-demo.html

I realize that the failure here:

https://igv.org/web/current/examples/google-ga4gh-demo.html

is due to "GOOGLE_API_KEY" being passed instead of an actual key.

That said, the deprecation of the Google Reads/Variants APIs still holds. The were expected to be turned down this quarter is my understanding.

**Comment by jrobinso** [comment]
Ah, o.k.,  that whole directory is way deprecated.   Did you get there by a link from our website, or just "googling"?

**Comment by mbookman** [comment]
Google Search for "igv demos" gave me the working example as the first hit.
I did a bunch of manual drilling down for the other one that didn't work; just because I already knew it was there.

I also see that there is a link that Google will need to update here:

https://googlegenomics.readthedocs.io/en/latest/use_cases/browse_genomic_data/igv.html

I'll let them know.

**Comment by jrobinso** [comment]
I'm going to rename this issue to "Remove Google GA4GH references".   There are some in desktop, some in igv.js

**Comment by jrobinso** [comment]
Explicit google GA4GH references are gone.  The generic ga4gh code remains, someone else might have a server although I doubt it.
