### ISSUE TITLE
Sub optimal ruler ticks

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#852]
Ruler ticks can be suboptimal for certain ranges.    See https://tinyurl.com/y6fe76l3

<img width="1930" alt="Screen Shot 2020-10-02 at 4 30 00 PM" src="https://user-images.githubusercontent.com/933148/94977188-8a982b80-04cc-11eb-999b-431fc934f088.png">

Same region in IGV desktop

<img width="1880" alt="Screen Shot 2020-10-02 at 4 31 17 PM" src="https://user-images.githubusercontent.com/933148/94977241-c03d1480-04cc-11eb-98d1-01b27824ede8.png">

**Comment by jrobinso** [comment]
Another example  https://tinyurl.com/y2x8cgdl   (chr8:127,734,435-127,743,951)

<img width="1687" alt="Screen Shot 2020-10-02 at 4 26 54 PM" src="https://user-images.githubusercontent.com/933148/94977094-22494a00-04cc-11eb-8c89-1fc3292b26e6.png">

Same region in IGV desktop

<img width="1896" alt="Screen Shot 2020-10-01 at 10 42 53 PM" src="https://user-images.githubusercontent.com/933148/94977129-4016af00-04cc-11eb-8961-a63dc2a89a7e.png">

**Comment by turner** [comment]
I took another look at the igv desktop ruler tick algorithm and tried to replicated in igvjs. I think this is pretty close

Example 0
![igv-git-852-example-0](https://user-images.githubusercontent.com/87169/121251705-2a386580-c875-11eb-87fd-a21cc7b6d6eb.png)

Example 1
![igv-git-852-example-1](https://user-images.githubusercontent.com/87169/121251725-30c6dd00-c875-11eb-8bba-36f4bb575dd9.png)

**Comment by jrobinso** [comment]
Appears to be fixed
