### ISSUE TITLE
statically sourced http

### ISSUE THREAD

**Issue by aubreybailey** [igvteam/igv.js#853]
http://igv.org/web/test/dist/igv.js (at least as seen in https://github.com/igvteam/igv.js-flask) is non-https and sources other non-https resources in this repository which are not loaded by default by most browsers for security reasons.

**Comment by jrobinso** [comment]
OK, thanks for the heads up.   I'll change it.

**Comment by jrobinso** [comment]
@aubreybailey I changed the 1 reference to http://igv.org... to https:// in igv.js-flask.   Its helpful if you open issues in the project for which are you making the report  (igv.js-flask in this case).

Resources from igv.org can be loaded by https or http.   That's not the case for all resources we reference.
