### ISSUE TITLE
build igv.js from Gruntfile (rather than igv.min.js)?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#855]
Possible?  It used to happen by default, and I am not sure whether, and with what arguments, I can build the unminified form.

Thanks!

**Comment by jrobinso** [comment]
Not anymore.   You should be able to debug as map files are created.   We now webpack, and webpack minimifies by default.   I could add a separate process to build igv.js if needed.

**Comment by jrobinso** [comment]
The code now uses advance js features such as async/await.  webpack transpiles the source to "ES5" so it works in all browsers.   An uniminified - untranspiled igv.js would work with the latest Chrome.   If that's a useful thing for development we could build it, but I would not distribute it.

**Comment by paul-shannon** [comment]
Thanks, Jim.  I’ll (happily) adjust.

 - Paul

**Comment by jrobinso** [comment]
@paul-shannon I know you're happy to adjust,  but it bugged me,  so I rearranged the build to keep a non-transpiled non-minified igv.js.   Let me emphasize that this uses advanced javascript,  the only browser I know it works on is Chrome.   So don't use it for a release.
