### ISSUE TITLE
Ability to selectively downsample reads

### ISSUE THREAD

**Issue by caalo** [igvteam/igv.js#856]
Hi IGV.js team,

I'm working with deep targeted sequencing data in which we want to look for rare variants (usually < 100 fragments) relative to wildtypes (usually 3000-6000 fragments). If I increase the samplingDepth to accommodate the depth, IGV.js becomes sluggish as expected, and I can never display all the fragments anyways due to limitation of canvas size (https://github.com/igvteam/igv.js/issues/234). What I am interested to do is to always show the rare variants at a loci, but downsample the wildtype fragments:

<img width="199" alt="screen shot 2019-02-12 at 9 48 32 pm" src="https://user-images.githubusercontent.com/17771008/52683500-010ba280-2f11-11e9-8978-e54276bf175b.png">

I would like to display fragment with the 'A' variant, and downsample the wildtype fragments, as I don't need to know every detail about the wildtypes, but want to know some general trends they follow.

I'm wondering if the team has any suggestions on making this possible: it seems that the way IGV.js sample reads is random, so right now the variant sometimes shows up when I sort by base, and sometimes doesn't show up. One possible brute force way is to put the rare variants in a separate bam, and load it in a separate track.

Lastly, what is the difference between samplingDepth and samplingWindowSize? Does changing one affect the other?

Thanks,
Chris

**Comment by jrobinso** [comment]
You will need to create a separate bam to accomplish this.   I can't think of any reasonable way to do this otherwise.    I do have on my to-do list a fix for the canvas issue,  so you would be able to keep all alignments then sort.

Alignments are downsampled in sliding windows,  specifically up to  "samplingDepth" alignments starting in each window of width "samplingWindowSize" are kept.

**Comment by caalo** [comment]
Ok, thanks, that's helpful to know.

I'm separating my alt fragments of interest into a separate bam, shown below. Is there any way to adjust the track height so that the first track has much smaller height compared to the second track?

<img width="1239" alt="screen shot 2019-02-13 at 5 20 44 pm" src="https://user-images.githubusercontent.com/17771008/52748192-df172c00-2fb3-11e9-89c6-2b8812fdbba2.png">

**Comment by jrobinso** [comment]
Just set the track height to whatever you want in the config.

**Comment by caalo** [comment]
Got it, thanks!
