### ISSUE TITLE
support for HTTP headers for authorization

### ISSUE THREAD

**Issue by odoublewen** [igvteam/igv.js#857]
Similar to #164, this is a question about how to serve data from a private URL.   In my case, I'm serving my data from DNAnexus.  [Their notes on generating HTTP download links](https://wiki.dnanexus.com/API-Specification-v1.0.0/Files#API-method:-/file-xxxx/download) make it sound like their http server has the [necessary capabilities](https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements):

> The download URL also honors the "Range" HTTP request headers, allowing clients to download only a particular byte range of the file.  The download URL has the following support for CORS....

The file objects are basically AWS S3 objects in the backend, with an API provided by DNAnexus.  To generate a URL, one uses the `get_download_url()` method.  I have two options: with or without preauthentication (i.e., the authentication is part of the URL string):

```python
>>> response = object.get_download_url(preauthenticated=True)
>>> response
('https://dl.dnanex.us/F/D/ALongLongAuthorizationEncodedURL', {})

>>> response = object.get_download_url(preauthenticated=False)
>>> response
('https://dl.dnanex.us/F/D2/file-123abcObfuscatedHash', 
 {'X-Authorization': '456xyzSomeOtherHash'})
```

I can get igv.js working for the first case, but not the second.  But I'd prefer the second case for security reasons.

According to their docs, the second part of the response with preauthenticated=False is: 
> [a mapping of] HTTP headers which MUST be supplied with any GET request to URL

Is there any way to supply HTTP headers in association with specific URLs?

**Comment by jrobinso** [comment]
Yes, use the "headers" property of the track config object, as described here  https://github.com/igvteam/igv.js/wiki/Tracks-2.0

**Comment by odoublewen** [comment]
Ah!  Thank you so much, I overlooked that!  So, it's working for track data.

But what about (custom) references?  I don't see the same "headers" property here:
https://github.com/igvteam/igv.js/wiki/Reference-Genome

Or does the headers track property also apply to references?

**Comment by jrobinso** [comment]
I'm not sure to be honest!   Since you have a test setup (I don't) give it a try.   I'll add it if it doesn't work.

**Comment by jrobinso** [comment]
From code inspection it looks like it should work.

**Comment by odoublewen** [comment]
Testing... hitting a problem... I don't fully understand CORS.  Getting error message:

```
Access to XMLHttpRequest at 'https://dl.dnanex.us/F/D/abc123ObfuscatedHash' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Request header field 0 is not allowed by Access-Control-Allow-Headers in preflight response
```

I get this error message when I provide the X-Auth json object to headers, whether or not I use the pre-authenticated URL.  What I think I understand is that when I manually supply the `headers` option, I need to supply all of the headers, including the [CORS stuff](https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements#cross-origin-resource-sharing-cors).   

Here are the full DNAnexus notes about CORS:

> The download URL has the following support for CORS:
> * If a GET request to download URL includes the "Origin" header, its contents will be propagated into the "Access-Control-Allow-Origin" header of the response.
> * Preflight requests (OPTIONS requests to a part upload URL, with appropriate extra headers as defined in the CORS draft) will be accepted if the value of the "Access-Control-Request-Method" header is "GET". The values of "Origin" and "Access-Control-Request-Headers" (if any) of the request, will be propagated to "Access-Control-Allow-Origin" and "Access-Control-Allow-Headers" respectively in the response. The "Access-Control-Max-Age" of the response is set to 1 hour.

I'm trying to sort out exactly what goes into my header....

**Comment by jrobinso** [comment]
Hi, first I suggest you educate yourself on CORS,  here's a short write-up:  https://flaviocopes.com/cors/.  There's lots of info on the web but some of its outdated,  look for recent articles.

WRT the error you are getting, this is probably a question only DNANexus can answer.  It looks like you are sending a header with the name "0",  is that correct?    This is not an allowed header, by that I mean DNANexus did not authorize this header in the preflight "OPTIONS" response.

To verify this watch the request and response traffic using Chrome developer tools, or equivalent if you use another browser.   Before your GET request you will see an OPTIONS request.   The Options response will include a list of headers that are allowed, in the field  "Access-Control-Allow_headers".  Headers not in that list will not be allowed.

**Comment by odoublewen** [comment]
Thanks again for the guidance.   My first problem was that my header was malformed -- I hesitate to write this because it is such a head-slappingly dumb mistake, but I was quoting the header rather than passing it in its native JSON...  time to put the JS back in to JSON! :)

So now it is working, sort of.  I can tell you that `headers` seems to be honored in the `reference` block, so perhaps add that to [these docs](https://github.com/igvteam/igv.js/wiki/Reference-Genome#details)?

But I say "sort of" because it only works in Safari, not Chrome.  This is because my dev work is being served from port 8000, and when I try to view it in Chrome, I get this message on the developer console:  

> Access to XMLHttpRequest at 'https://dl.dnanex.us/F/D2/file-obufuscatedhash' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://127.0.0.1' that is not equal to the supplied origin.

I can view exactly the same page in Safari just fine.  I guess there is some difference in the way the two browsers report the "supplied origin" (with or without port).  To that point, if I serve the page locally from port 80, it works fine in both browsers.

Anyway, this "issue" has digressed so I will close with this and please accept my thanks for your help and your very nice work on this project.

**Comment by jrobinso** [comment]
Hmm, that's interesting re Chrome.   When you test are you using 127.0.0.1:8000 for the page address, or localhost:8000.   That could matter.   

I'll add "headers" to the wiki for reference.

**Comment by odoublewen** [comment]
On a hint from some forum, I cleared Chrome's cache and voila, it works!!

Thanks very much, sorry to pester with my debugging.

**Comment by jrobinso** [comment]
No problem!  I learned something.

**Comment by odoublewen** [comment]
By the way, are you sure [this](https://github.com/igvteam/igv.js/wiki/Tracks-2.0#options-for-all-track-types) is correct?


> Property | Description
> -- | --
> headers | http headers to include with each request as an array of key-value pairs. For example `[{"foo": "bar"}]`


When I supply headers as an array, it doesn't work.  Seems like the object itself is what is required.  At least that is what gets it working for me.  In other words, `{"foo": "bar"}` not `[{"foo": "bar"}]`

**Comment by jrobinso** [comment]
You're correct, wiki is wrong.
