### ISSUE TITLE
IGV not displaying all reads from bam file in API example

### ISSUE THREAD

**Issue by tmdefreitas** [igvteam/igv.js#858]
I was using the API example here:
http://igv.org/web/release/current/examples/api.html

and added the 1KG Bam from the dropdown (HG02450). Note that the read depth for the default region is around 10. However in the 2.2.3 version here:

http://igv.org/web/release/2.2.3/examples/api.html, there are only one or two reads maximum for a given position. In addition, if you add the same track multiple times, the displayed reads are not the same even though the file + position is the same. See attached images:

 Current (2.0.0)

<img width="1157" alt="igvjs_current" src="https://user-images.githubusercontent.com/3845738/53104806-08791000-34fe-11e9-86fe-ce5e9175cfa4.png">

2.2.3

<img width="1146" alt="igvjs_2_2_3" src="https://user-images.githubusercontent.com/3845738/53104805-08791000-34fe-11e9-80db-3c256eff524f.png">

**Comment by jrobinso** [comment]
Thanks, something's not right.   Its curious,  I've tried other bams and don't see the problem, only this one.

**Comment by jrobinso** [comment]
Thanks for the report.  It took a particular combination of circumstances to trigger this bug, which the example bam file triggered.  There will be a new release later today (2.2.5) with the fix.

BTW,  how did you get to the "current" examples,  that's an old directory.   Did you follow links from any of our web pages?

**Comment by tmdefreitas** [comment]
I was trying to see which version caused the issue, and saw that this directory is public: http://igv.org/web/release/

I wasn't sure if "current" meant the last "official" release, so I used that in the report. Thanks for the quick fix!

**Comment by jrobinso** [comment]
OK,  I'll delete that directory.
