### ISSUE TITLE
chromosome dropdown widget not showing smaller records

### ISSUE THREAD

**Issue by odoublewen** [igvteam/igv.js#859]
Using custom genome in igv.js 2.2.4, I am not seeing all of the sequence IDs listed in the chromosome dropdown.

My reference fasta has 8 sequences in it, but only one shows up in the dropdown.  Text navigation works ~find~ fine.  See screenshot -- there is a sequence called `RNA18SN5` which I can navigate to via the text box, but only one sequence (`Ecoli_K12`) shows up in the dropdown.  (I should mention that of the 8 sequences, 7 are shorter than 7kb, while `Ecoli_K12` is ~4.6mb -- could that be relevant?)

![screen shot 2019-02-20 at 11 46 45 am](https://user-images.githubusercontent.com/1421445/53120301-627dd380-3506-11e9-9402-d41adbc41602.png)

I've pared this down to a simple case like the example code below, which I would expect to work.

```html
<script src="igv.min.js"></script>
<div id="igv-div" style=
"padding-top: 10px;padding-bottom: 10px; border:1px solid lightgray">
</div>
<script type="text/javascript">

  document.addEventListener("DOMContentLoaded", function () {

    var options =
        {
          reference: {
           fastaURL: "http://127.0.0.1/Public/custom.fasta",
          },
          showChromosomeWidget: true,
        };

    var igvDiv = document.getElementById("igv-div");

    igv.createBrowser(igvDiv, options)

  });

</script>

```

**Comment by jrobinso** [comment]
Yes the size is relevant.  There are some heuristics applied when populating the pulldown to prevent the thousands or tens of thousands of small contigs present in mammalian genomes to appear.   The heuristic is some % of the total.   There are a couple of things we could do here,  make that optional,  or just show all of them if the total # is < some value.

**Comment by odoublewen** [comment]
Ah!  Makes sense, but would be nice if there was a way to turn that heuristic off for custom applications.  Thanks.

**Comment by jrobinso** [comment]
The heuristic is also used in displaying the whole genome view.   Of
course, it doesn't have to be the same heuristic.   I'll provide some means
to turn it off.

**Comment by odoublewen** [comment]
Thanks @jrobinso!!

**Comment by jrobinso** [comment]
No problem @odoublewen .   I have a couple more bugs to fix before releasing this, probably tomorrow.
