### ISSUE TITLE
Feature request: view bigwigs in heatmap coloring

### ISSUE THREAD

**Issue by sooheelee** [igvteam/igv.js#865]
This request stems from the discussion in https://github.com/igvteam/igv-jupyter/issues/23. I understand this won't be a priority. Even still I think it will be useful to researchers down the road, and so here it is for a rainy day @jrobinso.

**Comment by jrobinso** [comment]
Not enough demand for this.

**Comment by auberginekenobi** [comment]
1 more demand for this

**Comment by MaryamMasoomi-byte** [comment]
1 more demand

**Comment by jrobinso** [comment]
This is supported already, update to the latest version.
