### ISSUE TITLE
Squich view in bedfiles is not working the same way as on normal IGV

### ISSUE THREAD

**Issue by duartemolha** [igvteam/igv.js#866]
Hi

I came across an issue that is really not very helpful for visualization of bed entries in IGV JS

You can compare the visualization of the same bed file on the 2 screenshots in the following link 

[IGV_comparison](https://drive.google.com/open?id=1KYN-6ZcKY-hFepRF9DDhO7CNKMbuPoH4)

Basically, it seems IGV JS is putting bookend bed entries all in a single line... but because there is no gap between them you can't really visualize that they are in fact multiple bed entries resulting in a single long interval.

ON the desktop IGV this does not occur.

Best regards

Duarte

**Comment by jrobinso** [comment]
@duartemolha could you provide a sample bed file corresponding to your figure?  That would be helpful.   Thanks.
