### ISSUE TITLE
useScore available for bed tracks?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#869]
@jrobinso I cannot find this option (available in IGV desktop, I think, described long ago [here](https://groups.google.com/forum/#!topic/igv-help/IyBzO5_j5E8)) along with viewLimits and color.

For background, and since there may be a better way to do this: my goal is to display a transcription factor motif match track, with a visual indication of the match score, and with the name of the motif available.  Then, after detecting the trackClick event, I can retrieve the motif name from the click event, and popup a motif logo .

I have been displaying these motif match segments in a bedGraph track, which renders track height as a function of motif match score,  but I never figured out how to include a name field in that track - bedGraph + name does not seem to be a sensible combination.

Thank you!

**Comment by SplitInf** [comment]
in case this may be helpful for others. Adding this line in the beginning of file works for me
track name="Test" useScore=1
