### ISSUE TITLE
not all GFF3 feature types are displayed

### ISSUE THREAD

**Issue by odoublewen** [igvteam/igv.js#870]
Created a simple GFF3 (believe it is valid) with 4 feature types:
```
##gff-version 3
chr1    internal        exon    1000    1100    .       +       1       ID=feature_with_type_exon
chr1    internal        CDS     1100    1200    .       +       1       ID=feature_with_type_CDS
chr1    internal        contig  1200    1300    .       +       1       ID=feature_with_type_contig
chr1    internal        gene    1300    1400    .       +       1       ID=feature_with_type_gene
```

Only 2 of the 4 types display in igv.js:

![screen shot 2019-03-04 at 3 14 37 pm](https://user-images.githubusercontent.com/1421445/53769281-47a94880-3e90-11e9-98f6-675331d419c2.png)

My test files for this issue are in this diff (comparing my fork of this project):
https://github.com/igvteam/igv.js/compare/master...odoublewen:master

**Comment by SchwarzMarek** [comment]
Hi, I've encountered I thing similar problem when converting sequence features from genbank to gff3. I've traced this down to `gffHelper.js` where some clever processing takes places but it results that almost all features categories are ignored.

```
Only these feature categories appears to be processed
        ['transcript', 'primary_transcript', 'processed_transcript', 'mRNA', 'mrna']
        ['CDS', 'cds', 'start_codon', 'stop_codon']
        ['5UTR', '3UTR', 'UTR', 'five_prime_UTR', 'three_prime_UTR', "3'-UTR", "5'-UTR"]
        ['exon', 'coding-exon']
```

Are there any plans to process any feature category? (with some exception i.e. `source` or `remark`)
I've found standard features for genbank format (http://www.insdc.org/files/feature_table.html).

I would like to have more feature categories drawn (at least in the scope of genbank) and I'm considering implementing them. Would you like PR for that?

Best regards

**Comment by jrobinso** [comment]
@SchwarzMarek The features you mention are considered part of a transcript or mRNA, according to the sequence ontology, and are combined into a single feature (usually a transcript or mRNA).   Other features should be displayed as is.     Its possible contig is filtered,  I haven't had time to look into this yet.    So I don't understand your question  "are there any plans to process any feature category".

If you have a valid gff3 file with features that are not being drawn attach it here,  I'll look at it along with the orginal posters file.   If possible run it through a gff3 validator first.   

Thanks

**Comment by odoublewen** [comment]
@jrobinso - Here's an update to the toy GFF3 example I used to open this issue. 
 The file attached (and printed inline below) is valid GFF3 according to http://genometools.org/cgi-bin/gff3validator.cgi

```
##gff-version 3
##sequence-region chr1 1 2000
chr1	internal	exon	1000	1100	.	+	1	ID=feature_with_type_exon
chr1	internal	CDS	1100	1200	.	+	1	ID=feature_with_type_CDS
chr1	internal	contig	1200	1300	.	+	1	ID=feature_with_type_contig
chr1	internal	gene	1300	1400	.	+	1	ID=feature_with_type_gene
```
[issue-870.gff3.txt](https://github.com/igvteam/igv.js/files/2985643/issue-870.gff3.txt)
(Naming file with .txt just so github will let me attach.)

**Comment by jrobinso** [comment]
Thanks @odoublewen ,  hoping to get a file from @SchwarzMarek as well.   IGV expects to see parents for CDS and exon features, that could be part of the issue,  but I will let you know.

**Comment by odoublewen** [comment]
Understood.  My toy example is sort of deliberately stripped down and thus non-conforming to the conventional use of the format to annotate transcripts.  

But I guess there is GFF3 format in the broad sense (i.e. a format for annotating generic feature) and the narrow sense (i.e. a format for annotating eukaryotic transcript/gene models).  I can understand that you'd want to do feature filtering when dealing with the latter.

**Comment by jrobinso** [comment]
Everything is tuned for the latter,  in 10 years this is the first time this issue has arose.   Plenty of issues have arising around transcripts,  there is too much freedom in gff and many ways to model.  Also unusual things like exons with multiple transcript parents.   That's how the code got so complicated.   I'm considering a new approach that would work for both,  but again this is the first time the issue has arose in 10 years so its hard to prioritize.    A less complex code base might be motivation enough, I will take a fresh look at it.

**Comment by SchwarzMarek** [comment]
Hi @jrobinso ,
as you've correctly pointed out, my gff3 file was not strictly gff3 valid. However, removing those problematic regions does not fix the underlying problem.

I'll attach full-fat cleaned file (with mandatory `.txt` as @odoublewen )
[CP006569.1.gff.txt](https://github.com/igvteam/igv.js/files/2987526/CP006569.1.gff.txt)

In my case I thing that processing the `gene` and `CDS` category together (if they at same coordinates) would be excellent. However, other features like `tRNA` - etc are filtered out - which is not so great at all.

From what I could access (And I might easily be wrong) the `gffHelper.js` returns only the `combinedFeatures` and these are only the ones mentioned in my earlier post.

I you don't want to change the behaviour significantly it still would be great to have some track option to set features to be displayed, potentially assign grouping options.

I can imagine something like
```
showFeatures = [
    "tRNA",
    "rRNA",
    ["gene", "CDS"], .....
]
```
Best regards

**Comment by jrobinso** [comment]
OK, thanks.  Filtering tRNA out is definitely a bug.   I can imagine
certain features, like stop codons without parents,  being filtered but not
many.  I will look into this.
