### ISSUE TITLE
Wig Track rendering bug. Feature color property is not valid rgb string

### ISSUE THREAD

**Issue by turner** [igvteam/igv.js#873]
Wig Track rendering bug. Feature color property is not valid rgb string. The result is features always render as black.

**Comment by jrobinso** [comment]
@turner Could you provide a test case to reproduce?   Have you looked into it?   Colors are not always an rgb string,  hex strings and symbols are also valid CSS colors.

**Comment by turner** [comment]
This is actually a BED track rendering bug. See branch https://github.com/igvteam/igv.js/tree/dat_issue_873. 

igv-dev.html. 

The BED track renderer in black should be the same color as the WIG track rendered in pink.

**Comment by turner** [comment]
The bug appears when rendering using FeatureTrack. The `feature.color` property has a meaningless value:

<img width="605" alt="Screen Shot 2019-03-15 at 9 07 45 AM" src="https://user-images.githubusercontent.com/87169/54433356-06bbfa00-4702-11e9-8777-db37d24ea67a.png">

**Comment by turner** [comment]
Closing issue for now to do more testing.
