### ISSUE TITLE
Improperly formatted BigBed file color field.

### ISSUE THREAD

**Issue by turner** [igvteam/igv.js#875]
When rendering BigBed files the color field some files is not valid rgb format resulting in black being used for the features.

Here is a session file which renders BigBed files from ENCODE. Many have invalid color:
https://www.dropbox.com/s/6dwhok5ytt7wqjy/bigbed-color-issue-session.json?dl=0

Here is a BED file with color converted to BigBed. Rendering is correct:
https://www.dropbox.com/s/6dwhok5ytt7wqjy/bigbed-color-issue-session.json?dl=0

**Comment by jrobinso** [comment]
The color field in this case is -1, so black is as appropriate as any other color.
