### ISSUE TITLE
Show reads behave differently via Nginx in version 2.x

### ISSUE THREAD

**Issue by SimonLi5601** [igvteam/igv.js#878]
We have a Django application which integrated IGV 2.x run on Gunicorn. The show reads (igv.browser.search(locus)) looks normal when browser access Gunicorn directly. But if we add a proxy pass layer(Nginx) between the user and Gunicorn, the track shows much less reads comparing to Gunicorn. I guessed it must be some configurations in the Nginx to prevent the IGV behave normal. But after I compared all the request and response from the Gunicorn and Nginx, they all look the same except the server type and connection. I changed the connection from keep-alive to close. Please see the attachment below. 
Different show reads,
![show_reads_nginx](https://user-images.githubusercontent.com/18488136/54930695-18658480-4eee-11e9-8d4a-07764b6a2c25.png)
![show_reads_gunicorn](https://user-images.githubusercontent.com/18488136/54930688-156a9400-4eee-11e9-9d81-1ec785b26bc8.png)

Similar response headers,
![nginx_response_header](https://user-images.githubusercontent.com/18488136/54929505-0be02c80-4eec-11e9-9762-840a038f5f2c.png)
![gunicorn_response_header](https://user-images.githubusercontent.com/18488136/54929526-14386780-4eec-11e9-9ea6-55ef0011f986.png)

Do you have any idea what might prevent IGV show all the reads? The down-sampling seems not even be trigger yet.

**Comment by jrobinso** [comment]
Its a good question, I don't know.  IGV is just displaying what is returned in the response,  it knows nothing about what's on the other side (obviously).   I don't know what the consequence of changing the connection-type to "close" will be,  but it will probably impact performance in a negative way. 

A couple of debugging suggestions:  The request/response you show is only for the BAM header,  I suggest comparing all request/responses.  There should be a series of requests for bam records,  usually 3 or 4 but could be as many as 15-20 for some bams.      Second suggestion is to try comparing output for the same region with samtools view.

**Comment by SimonLi5601** [comment]
Thanks fro the reply, Jim! For this region, it has 19 bytes range read to the server. Everything look the same with Gunicorn and Nginx for those 19 requests, in terms of headers and lengths. I was wondering do you need to assemble those byte reads before rendering display? How do you convert the binary data into reads? Another symptom I observed is, with Nginx, the display shows different reads (not complete) each time after I refresh the page and make the same call to igv.browser.search to the same locus.

**Comment by jrobinso** [comment]
That is very strange.   Could you try this with samtools view?    Redirect the output for each to a file then you can compare the bytes.    

To answer your question,  IGV uses the htsjdk to convert the bytes into alignment records.

**Comment by jrobinso** [comment]
How did you verify that everything looked the same "in terms of lengths"?   Its not enough to look at the content-length header,  you need to look at the actual bytes returned.  If nginix is, for example, closing the connection mid-stream it wouldn't be reflected in the header which has already been sent.

**Comment by SimonLi5601** [comment]
Yes, kind of checking the headers. I clicked through each one. But I also did pickup mostly of the request and looked the response content as well. Since it is binary, I checked the number of lines in response. They look the same. Probably I should have some programmatically checking to make it more accurate. I will do more checking. It must has something different. I can use samtools to look into it further.

**Comment by jrobinso** [comment]
The samtools experiment will be informative.   If its possible for you to setup something public I can reach I will have a look.   Also,  look in  the "igv.log" file for any messages.

**Comment by SimonLi5601** [comment]
I would like to have a quick update on this. One thing I need to correct is actually there could be the same issue with Gunicorn application as well. But it is just slower chance in my test environment, so I thought it didn't have problem. Adding a layer of Nginx seems to make the issue more significant. Here is what happened. By default, the Gunicorn has one [worker](https://docs.gunicorn.org/en/stable/settings.html?highlight=workers#workers) and uses sync mode, and if I increased the workers to 4, I can observe the same issue more frequently. Regardless the workers and if has Nginx or not, all the requests seems complete and has no issue. I can see they are calling fulfill function. I am still debugging what happens in the downstream. One thing I couldn't understand is why one worker might still cause problem, even much lower chance. I noticed the request in prior version (1.x) seems to be less segments (different bam) than the current one.  We didn't notice this issue with same application configurations. Thanks for any idea!

**Comment by SimonLi5601** [comment]
I traced down all the ways to AlignmentContainer and found the differences in the packedAlignmentRows and downsampledIntervals. I also print out the array size of Uint8Array. Both looks the same except the order which depends on when the Ajax request returns.
Gunicorn results,
![Gunicorn_alignment_container](https://user-images.githubusercontent.com/18488136/55105573-39bba180-50a3-11e9-8a07-2a3b537f0994.png)
Nginx results,
![Nginx_alignment_container](https://user-images.githubusercontent.com/18488136/55105580-3cb69200-50a3-11e9-9be7-544e4782d3b1.png)

**Comment by jrobinso** [comment]
I'm not sure I am understanding what you are saying, and I am not following the discussions about "worker" at all.    Of course there are going to be differences in alignments the visual screenshot is showing you that.  

Did you try samtools yet?

**Comment by SimonLi5601** [comment]
Hi Robinson, sorry about that if it adds more confusion. What I tried to say was the issue is not related to Gunicorn or Nginx directly. Basically multiple workers just means the web applications can handle multiple requests at the same time. I just came across this issue #858 and I think it should be the same cause. I will checkout your latest fix to see if it solve the problem. Thanks a lot!

**Comment by jrobinso** [comment]
Hi @SimonLi5601 I assume you are using the latest code, of so it has the fix for 858.    I'm asking about samtools because it will tell us if there is a server or client issue,  or at least yield more information.

**Comment by jrobinso** [comment]
@SimonLi5601 a key place to focus is here,  starting a line 83 of bamReader.js.   Do you get the same byte array in the same order in both cases?   If not we know where to look further.

```
            for (let i = 0; i < chunks.length; i++) {
                const compressed = compressedChunks[i]
                const c = chunks[i]
                var ba = new Uint8Array(igv.unbgzf(compressed)); //new Uint8Array(igv.unbgzf(compressed)); //, c.maxv.block - c.minv.block + 1));
                igv.BamUtils.decodeBamRecords(ba, c.minv.offset, alignmentContainer, this.indexToChr, chrId, bpStart, bpEnd, this.filter);

            }
```

**Comment by SimonLi5601** [comment]
@jrobinso Just tested it and it does solve my problem. I didn't realize the issue are relevant at the beginning. That explains all my questions above from the issue you described. Thanks for your time! I will close the ticket.

**Comment by jrobinso** [comment]
@SimonLi5601 Great, and apologies that I didn't make this connection.   I can't remember myself what the issue  or fix was to be honest but I will review that now.    Probably has to do with the order the chunks are processed, if they are processed out of order the AlignmentContainer will think it has finished a bucket when it hasn't.

**Comment by jrobinso** [comment]
Ah yes,  its exactly as I indicated above,  the fix forces processing of chunks in the correct order.
