### ISSUE TITLE
Reads filtering

### ISSUE THREAD

**Issue by lsantome** [igvteam/igv.js#879]
Hi igvteam,

I'm working with targeted NGS bam files and I've found differences between the display of embebbed and normal IGV, which I'm not able to understand. 

![19S01617](https://user-images.githubusercontent.com/7248178/55073327-b3e12b80-508d-11e9-8257-2fd77aecf0fe.jpeg)

![19S01617_embebido](https://user-images.githubusercontent.com/7248178/55073337-c0658400-508d-11e9-90df-7c694951f672.jpg)

These two pictures shows the same file and same genomic region. The embebbed IGV apparently is not showing soft-clipping reads. Is that a matter of display settings or is it filtering those reads?

Thank you in advance!

**Comment by jrobinso** [comment]
You need to use the "gear" menu and turn on "show soft clips".
