### ISSUE TITLE
Feature request: "Group by" for alignments

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv.js#888]
IGV Desktop can "group" alignments by various attributes. The same has been requested for igv.js. Especially group by read group and tag.

**Comment by milandomazet** [comment]
Hello,

Are there any updates related to this one or some way how to reproduce this behaviour with a different approach? Thanks!

**Comment by jrobinso** [comment]
No, but you have upvoted this one by virtue of asking.

**Comment by alexmathieu** [comment]
Please !!!!!!

**Comment by DevangThakkar** [comment]
This would be really great! This would make it easy to add this feature to igv-reports as well.

**Comment by jrobinso** [comment]
This is implemented but not released, you can try it by building from source or installing from https://igv.org/web/snapshot/dist/

**Comment by jrobinso** [comment]
An example configuration using groupBy:

```
                {
                    "type": "alignment",
                    "url": "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam",
                    "indexURL": "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam.bai",
                    "name": "Color by tag",
                    "format": "bam",
                    "colorBy": "tag:XT",
                    "groupBy": "tag:XT"
                }
```

Not all IGV desktop group options are supported, the current recognized groupBy values are:

```
'strand'
'firstOfPairStrand'
'mateChr'
'pairOrientation'
'chimeric'
'supplementary'
'readOrder'
'phase'
'tag:<tagname>'
```

**Comment by DevangThakkar** [comment]
Thank you!

**Comment by DevangThakkar** [comment]
Hi Jim, 

As a potential feature request, would it possible to add BASE as well as an option for grouping (desktop has it as `base_at_pos` but the sort function in igv.js has it as `BASE` so I refer to it as BASE for consistency)? It helps a lot with reviewing variants.

Thanks again,
Devang

**Comment by jrobinso** [comment]
@DevangThakkar How would that differ from sort by base?

**Comment by DevangThakkar** [comment]
In `group_by_pos`, the idea is to consider only the reads that have overlap with the position of interest. This creates three (or more) groups of interest - ref, alt, and non-overlapping. Besides the presence of side reads, the other issue is that once you sort by base, the reads are only pseudo-sorted by position - usually in the right place for around 75% of reads. IMO, the groupBy view is much cleaner. 


group_by_pos
![group_and_sort](https://github.com/igvteam/igv.js/assets/6257460/7efad5b6-1745-40ed-9888-c37d6b989608)
sort_by_base
![sort_only](https://github.com/igvteam/igv.js/assets/6257460/69bdcbd2-3b29-4750-8876-1b1203b4f172)

**Comment by jrobinso** [comment]
Group by position differs from group by base, so now I'm not sure what you are requesting.   I suppose group by position?    Base refers to the called base in the alignment at a position.  

I don't understand this statement at all,  grouping by position certainly doesn't have anything to do with the reference.

> This creates three (or more) groups of interest - ref, alt, and non-overlapping.

If you are requesting a group by position that does exactly what desktop does I can look into that.

**Comment by jrobinso** [comment]
Actually looking at desktop code I think you are referring to grouping by base at a position.  This will potentially create 5 groups, one for each potential base and no overlap.

**Comment by jrobinso** [comment]
BTW, reads are never sorted by position in a group, if they look that way its an accident, there is no  "right place" wrt position.     The real difference in sorting and grouping is the removal of alignments that do not overlap the position.

> the reads are only pseudo-sorted by position - usually in the right place for around 75% of reads

**Comment by jrobinso** [comment]
OK,  this is a bit confusing so I'll just post the desktop code here.  You are correct that 3 groups are created, but not based on "ref" and "alt" in the usual sense, rather any base at the position (reference or not) vs a gap at the position, which usually indicates a deletion.    If implemented in igv.js the same rules will be used.

```
            case BASE_AT_POS:
                // Use a string prefix to enforce grouping rules:
                //    1: alignments with a base at the position
                //    2: alignments with a gap at the position
                //    3: alignment that do not overlap the position (or are on a different chromosome)

                if (pos != null &&
                        al.getChr().equals(pos.getChr()) &&
                        al.getAlignmentStart() <= pos.getStart() &&
                        al.getAlignmentEnd() > pos.getStart()) {

                    byte[] baseAtPos = new byte[]{al.getBase(pos.getStart())};
                    if (baseAtPos[0] == 0) { // gap at position
                        return "2:";
                    } else { // base at position
                        return "1:" + new String(baseAtPos);
                    }
                } else { // does not overlap position
                    return "3:";
                }
```

**Comment by DevangThakkar** [comment]
Sorry about the confusion, I didn't realize group by base and group by position were different things. Going off the code, it seems like there are three groups described but in practice we do see a group for each base, so to confirm that I understand - this creates 6 groups (A,C,G,T,del,blank), is that correct? If so, that is exactly what I meant to ask for igv.js. This leaves out the case for insertions (you implemented a separate option for that [here](https://github.com/igvteam/igv/issues/1380#issuecomment-1700350849) but that's fine if we leave those as is, that works.

**Comment by jrobinso** [comment]
I would expect 6 groups based on the name, but from the code there is only 3.   I don't understand how you can see a group for each distinct read base,  as you can see above there are only 3 categories.    In your screenshot there are only 3.

We could create a group for each base, but that would differ from desktop behavior.

**Comment by jrobinso** [comment]
Now that I understand this use case a little more, a better solution might be to just eliminate (hide) non-overlapping alignments then sort the remaining by base,  which includes indels.    That would be a new thing though.   Grouping "by base" then sorting the resulting groups by base would achieve something similar, the non-overlapping alignments are hidden in the 3rd group at the bottom.

**Comment by jrobinso** [comment]
I'm going to be distracted for a few days now,  will return to this alter.

**Comment by DevangThakkar** [comment]
I was trying to dig up a multi-allelic example, here it is. There's a group for each alt base, the ref, and the blank. So the desktop does have a group for each base, despite the code grouping.
![multiallelic](https://github.com/igvteam/igv.js/assets/6257460/2356ce7d-e7a2-410c-a272-9b138504ec0e)

**Comment by jrobinso** [comment]
Interesting, well that makes more sense intuitively.  It looks like it goes in a set order irrespective of the reference, A,C,T and I imagine if present G.

**Comment by DevangThakkar** [comment]
Yeah, I think porting the group-by-base functionality from desktop to js as-is (three groups in code that lead to individual groups per base) would be preferred over this. Whenever you have the time, thank you!
> Now that I understand this use case a little more, a better solution might be to just eliminate (hide) non-overlapping alignments then sort the remaining by base, which includes indels. That would be a new thing though. Grouping "by base" then sorting the resulting groups by base would achieve something similar, the non-overlapping alignments are hidden in the 3rd group at the bottom.

**Comment by jrobinso** [comment]
This is done.  The option in the config looks like this

```
groupBy:  "base:chr1:155,142,814"
```

**Comment by DevangThakkar** [comment]
Thank you for the prompt response, I'll try it out, thanks!
