### ISSUE TITLE
GTEX IGV 2.2.x integration highlighting bug

### ISSUE THREAD

**Issue by dnguyen1193** [igvteam/igv.js#894]
Jim,

Thanks for getting the changes in for GTEx so quickly. I've done some more testing and found one small issue I'm not sure how to resolve.

Using the configurations we finalized in issue #874, I'm able to get things to work perfectly. However, if I remove the eqtl track from the configurations and try to use the IGV search box to search for a gene feature (e.g. ACTN3), the highlighting for the found gene doesn't appear in the Genes track. 

Configuration used:

```
let options = {
    type: "GTEX",
    reference: {
        id: 'hg19',
        fastaURL: "http://dn7ywbm9isq8j.cloudfront.net/genomes/seq/hg19/hg19.fasta",
        indexURL: "http://dn7ywbm9isq8j.cloudfront.net/genomes/seq/hg19/hg19.fasta.fai",
        cytobandURL: "http://dn7ywbm9isq8j.cloudfront.net/genomes/seq/hg19/cytoBand.txt",
        tracks: [
            {
                name: 'Genes',
                type: 'annotation',
                url: 'https://s3.amazonaws.com/igv.broadinstitute.org/annotations/hg19/genes/gencode.v19.genes.v7_model.patched_contigs.sorted.bed',
                displayMode: 'EXPANDED',
                height: 100,
                autoHeight: true,
                removable: false,
                order: Number.MAX_VALUE // pinning track to bottom
            }
        ]
    },
    //locus: params.location, // something like: chr1:1-500,000
    flanking: 75000,
    search: {
        url: 'https://gtexportal.org/rest/v1/reference/features/$FEATURE$',
        resultsField: 'features',
        geneField: 'geneSymbol',
        snpField: 'snpId'
    },
    tracks: [
        {
            name: 'GWAS Catalog',
            type: 'annotation',
            format: 'gtexgwas',
            url: 'http://dn7ywbm9isq8j.cloudfront.net/annotations/hg19/gwas/v2_newest_converted_GWAS_catalog_SNPs_Pval5E08_hg19_040115.bed',
            indexed: false,
            color: 'rgb(100,200,200)',
            displayMode: 'EXPANDED',
            order: Number.MAX_SAFE_INTEGER // 2nd to last track
        }
    ]
}
```

![Screen Shot 2019-04-02 at 5 53 53 PM](https://user-images.githubusercontent.com/8691599/55439112-94f10680-5571-11e9-8db5-c3254920eddb.png)

When I then add the "Muscle - Skeletal" track in, the eQTLs highlight, but the gene name remains unhighlighted until I search "ACTN3" again in the box.
![Screen Shot 2019-04-02 at 5 54 12 PM](https://user-images.githubusercontent.com/8691599/55439120-99b5ba80-5571-11e9-9db7-a003ae6e01ea.png)

Here is a screenshot of the old behavior:
![Screen Shot 2019-04-02 at 5 55 05 PM](https://user-images.githubusercontent.com/8691599/55439156-b651f280-5571-11e9-9fc1-c538683bc19a.png)

Am I missing some config to get it to highlight initially, as well?

**Comment by jrobinso** [comment]
Highlighting requires an EQTL track, it's a feature specific to EQTLs.    I
didn't consider this case (no EQTL tracks loaded).    For now there is
nothing you can do,  searching again after the track is loaded might be a
workaround.

**Comment by dnguyen1193** [comment]
Ok, thanks for the heads up. For now, maybe we'll just default to having a track open.

**Comment by jrobinso** [comment]
I could add a configuration parameter that explicitly says "this is GTEx"
rather than infer it from the tracks loaded.   This will be next release
though.

**Comment by dnguyen1193** [comment]
Something like adding `type: "GTEX"` to the configurations?
That sounds perfect. There's no rush on this!
Thanks for all your help, Jim.

**Comment by jrobinso** [comment]
Apologies for the long delay, this is implemented and will be in the next release.  The flag is a boolean,

```
gtex: true
```
