### ISSUE TITLE
BAM tag error

### ISSUE THREAD

**Issue by ggydush** [igvteam/igv.js#896]
In my BAM files, there are a few tags that contain arrays and when viewing in IGV.js, the first tag with an array shows "Error unknown type: B" and all other tags afterwards are not shown. 

In IGV, the tags with arrays show "[not shown]" and tags after the array tag are shown as well. It would be great if IGVJs would have the same behavior.

If an example BAM would be of use, I'd be happy to share via email.

**Comment by jrobinso** [comment]
OK,  I can probably do this without one but a small (or large) example BAM would be useful for testing.  You can email it to  igvteam (at) broadinstitute.org

**Comment by BuysDB** [comment]
I am experiencing this problem too.

#### Example alignment file
```
@SQ	SN:chr1	LN:1000
Q1	0	chr1	101	60	6M	*	0	0	ATCGGG	*	AA:Z:I am visible!
ReadWithIssue	0	chr1	101	60	6M	*	0	0	ATCGGG	*	AA:Z:I am visible!	AB:B:C,1,2,3	AC:Z:I am not visible!
```
Resulting reads in IGV.js
![igv_js_tag_bug](http://www.buysdb.nl/persistent/github/igv_js_tags/igv_js_bug_sc1.png)

I have attached the bam file for your convenience:
[igv_js_array_tag_test_bam_file.zip](https://github.com/igvteam/igv.js/files/4525011/igv_js_array_tag_test_bam_file.zip)

**Comment by jrobinso** [comment]
What version of igv.js are you using?
