### ISSUE TITLE
"RangeError: Offset is outside the bounds of the DataView"

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#897]
Loading a small 7k bam file, with associated index, I get this error:

![image](https://user-images.githubusercontent.com/2480712/55848369-82427880-5b01-11e9-9cb4-b31f8bf1bf5e.png)

With this track config
````
 var config = {name: trackName,
               type: "alignment",
               format: "bam",
               url: dataURL,
               indexed: false
               };
````
And this  bam file: 
[bam.zip](https://github.com/igvteam/igv.js/files/3061826/bam.zip)

 ```` samtools quickcheck```` is silent. ````samtools depth file.bam | tail -10```` reports
````
chr19	42879806	2
chr19	42879807	2
chr19	42879808	2
chr19	42879809	2
chr19	42879810	2
chr19	42879811	2
chr19	42879812	2
chr19	42879813	2
chr19	42879814	2
chr19	42879815	1
````
 suggesting that the file seems to be okay.  Any suggestions?
Thanks!
 - Paul

**Comment by paul-shannon** [comment]
@jrobinso It appears that this is due to my webserver (a minimal one built into the R httpuv package) is returning the bam file as text.  Let's close this issue, perhaps to reopen if need be.

**Comment by jrobinso** [comment]
See if you can set the content type header for the response to
"application/octet-stream" on the server side.
