### ISSUE TITLE
Got errors after upgrade to v2.2.8

### ISSUE THREAD

**Issue by SimonLi5601** [igvteam/igv.js#899]
I supposed to upgrade to the latest version of igv to 2.2.8, but got some errors for the same BAM file which was working for previous version on the dev environment. The reads can't show.   I couldn't open the example page for this version to verify if it is working on your site.
<img width="1417" alt="Screen Shot 2019-04-18 at 10 08 55 AM" src="https://user-images.githubusercontent.com/18488136/56366953-3a3aea00-61c2-11e9-8fe4-58bc4d4068e1.png">

Could you please look at this? Thanks!

**Comment by jrobinso** [comment]
Thanks for the report, looking into this.

**Comment by jrobinso** [comment]
Thanks again for the report.  Could you try v2.2.9, just released?

**Comment by SimonLi5601** [comment]
Yes, it solves the problem now. Thanks for the prompt response!
