### ISSUE TITLE
Aligning center guide to a particular base

### ISSUE THREAD

**Issue by mnoyes68** [igvteam/igv.js#900]
I am currently trying to create a 1bp guide around a particular base pair of interest. I've currently figured out how to set the center guide option using showCenterGuide: true, but this follows the browser, rather than sticking to the specified base pair. Is there a way to get this behavior on a specific base pair?

**Comment by helgathorv** [comment]
You could try doing this with a 'region of interest'. The regions are specified in a bed file, and they can be displayed either globally across all tracks or within a single track. This isn't documented yet in the wiki, but please see the code snippets in the following git issues: 
#850 includes sample code for regions that are displayed across all tracks, and 
#854 includes sample code for regions that are displayed in a single track only.

**Comment by mnoyes68** [comment]
Ok wonderful, thanks!
