### ISSUE TITLE
igv.version doesn't report version

### ISSUE THREAD

**Issue by tmdefreitas** [igvteam/igv.js#903]
Looks like it's hard coded to "@VERSION". 

https://github.com/igvteam/igv.js/blob/2b8618acce0298f158cb460a11bd84caab1dffed/js/igv-create.js#L29

I'm not familiar with webpack, but is there some way to get set this from the package info at build time?

https://github.com/igvteam/igv.js/blob/235c1b5b208d77483723528514635294199ee20d/package.json#L3

**Comment by jrobinso** [comment]
Hi, long delay but this is done, you can call  "igv.version()" to get the version number, and time, when built.
