### ISSUE TITLE
Zipped files of storage.googleapis.com don't work: add support for 'response-content-disposition'

### ISSUE THREAD

**Issue by roelnoten** [igvteam/igv.js#904]
When trying to use a file from a https://storage.google.apis.com url igv.js fails to detected wether the file is zipped. As a result it tries to handle the response as non-zipped and the track remains empty.
The cause is that such a url ends with a GUID (and a bunch of query parameters). 
The igv.getFilename function in igv-utils.js is used to determine the file name for a url and then a simple check to see whether it ends in .gz determines whether the response needs unzipping.  But the algorithm in  igv.getFilename is a simple substring between last / and ? thing which in this case returns the GUID and thus doesn't end in .gz

We do however add a response-content-disposition query parameter to the url: eg. ......&response-content-disposition=attachment%3B%20filename%3D%22cytoBandIdeo.txt.gz%22
When such a query parameter is present in the url, the depicted filename it contains should be returned, as 'cytoBandIdeo.txt.gz' in the example.

**Comment by jrobinso** [comment]
I don't like relying on custom content headers.   However we could look at the first few bytes for the gzip magic number.     Is the end user loading these files from a menu or other means in your application, or are you configuring them with a "config" object.   If the latter we could also add an explicit field that indicates the content is gzipped.

**Comment by roelnoten** [comment]
Thanks for the fast reply.

'response-content-disposition' is not really custom. It's a general practice and not only used for GCS but also for AWS S3.
You could maybe also look at the mime type to see wether i't s zip type.

I'm building an IGV session with a config object. Adding an explicit field indicating that content is zipped is nice for tracks, but in my case it was for instance already an issue for the cytoband; so that would mean such an explicit field would also be needed for that, and fastaURL, and indexURL, ....
When going for the explicit field it's cleaner to also support the option of providing the url as an object instead of a string. For example:
`"cytobandURL": "https://s3.amazonaws.com/igv.org.genomes/hg38/annotations/cytoBandIdeo.txt.gz",
`or 
```
"cytobandURL": {
    url: "https://storage.googleapis.com/tst-bluebee-com-dd24aca8-63b5-4d3b-9468-c941f4f47c4d/e5a1739c-c1b6-4034-8db7-4ecaec0........%2BfGULkjrQQX2KlA%3D%3D&response-content-disposition=attachment%3B%20filename%3D%22cytoBandIdeo.txt.gz%22",
    compression: 'GZIP'
}
```

where compression can be one of NONE, GZIP or BGZF.
This way more config can be added per file in the future if needed....

**Comment by jrobinso** [comment]
Yes, you are correct,  I am seeing it from S3.   So we can check for that.       Agree re your object vs string suggestion.   

If by mime-type you meant content-type usually this is binary/octet-stream.

**Comment by jrobinso** [comment]
@roelnoten I'm hopefully fixing this now.  I don't have a google storage account, if you could create and share a small gzipped file for testing it would be helpful.

**Comment by jrobinso** [comment]
@roelnoten I've discovered you can't access the "Content-Disposition" response header from javascript.  So that' can't be used.   I know you weren't suggesting that, you were suggesting parsing your parameter.    But while the Content-Disposition response header seems pretty standard,  the parameter you are using is not widespread among igv users,  it has no effect on igv or any javascript program.   From my limited understanding it is basically a request to the server to give a name to a downloaded file.   This name is not accessible to javascript programs.    So I don't want to rely on this.   What I've done instead, which should work for gzipped files, is just check the first 2 bytes of the response for the gzip magic number.

**Comment by jrobinso** [comment]
I think this is resolved with the magic number check.
