### ISSUE TITLE
which field in which track type can include a url?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#905]
I wish to include a url in a bed-type track.   I have added a custom trackclick handler to popup a link to a url.

The use case is a track of motifMatches.  The url will point to an image of the motif logo.  When the user clicks on the track item,  the image along with the sequence match score will be displayed in a popup.  

This is rather like custom-track-popover.html.   My question: how do I pass the url to the clickhandler?   Is the bed name field the only or the best option?

**Comment by jrobinso** [comment]
The name field is the only option that comes to mind with bed format.  You
could use gff3 which allows arbitrary properties in column 9.

**Comment by paul-shannon** [comment]
@jrobinso - thanks.   I will try both.

Tangentially related:  can I remove trackclick handlers as easily as I add them?  Query for the current set?

**Comment by jrobinso** [comment]
You can remove an event handler with "un",  but arguments have to match the
arguments on "on" exactly.    I'm going to change this to be more
consistent with jquery,  so "off",  but that is how you do it currently.

I don't know what you mean by query for the current set,  the answer is
probably no.

**Comment by paul-shannon** [comment]
“query for the current set” was my crypto-speak for “tell me the trackclick handlers already registered so I can maybe delete them"

**Comment by jrobinso** [comment]
No, but I just added off() methods similiar to jquery.   You should be able
to remove all handlers by calling browser.off() with no arguments.

**Comment by paul-shannon** [comment]
Could that be igvBrowser.off(“trackclick”) to remove all trackclick handlers?   I’d be sorry to lose a locuschange handler when trying to cleanup my trackclick handlers.

**Comment by jrobinso** [comment]
That should work, try it.   This is is not an official method yet and I
don't know when I'll have time to test it.

**Comment by paul-shannon** [comment]
It works great!

**Comment by paul-shannon** [comment]
If  I discover an image url in the popoverData name.name field, I show the image.
If I do not, I wish to display the default bed file popup.  

````custom-track-popover```` and ````custom-track-click```` sort of imply that returning true from my new trackclick handler would lead to that default display.   But neither ````true````  nor ````false```` gets me that result.  
Is it somehow possible to get the default bed track popup if I do not have cause to create a special popup?

**Comment by jrobinso** [comment]
Its a bit counter-intuitive, but returning "undefined"  will result in the
default behavior.  Any other value will block default behavior.   This is
how it's coded.

Its been this way for a long time,  and I don't want to change the meaning
of returning "false".   That would be a breaking change to the API and we
don't need to do that.   I will change the behavior so that returning
"true" will cause default behavior to occur.

So the ammended rules --

* return a string => igv.js will present that string
* return true => default behavior occurs (standard popup text).
* return false => default behavior is blocked

This does not break the API as "documented" in the examples.

**Comment by paul-shannon** [comment]
Thanks, Jim.   This gives me everything I need.   FWIW: I use the flexible popup capability you provide, concocting new handlers R,  sending the resulting javascript to igv.js in the browser, producing results like that shown below.   I will close this issue, marking it as completely resolved.  As always, many thanks.

![image](https://user-images.githubusercontent.com/2480712/57402543-62e44d00-718c-11e9-8763-451c85534002.png)

**Comment by jrobinso** [comment]
That's pretty cool.   BTW do you have a publication on your tools that
integrate igv.js?

**Comment by paul-shannon** [comment]
No publication yet, but hopes for one by September…
 
 - Paul
