### ISSUE TITLE
Error handling after browser creation

### ISSUE THREAD

**Issue by DoubleB123** [igvteam/igv.js#906]
After I successfully create a browser object, is there any way to catch errors so I can handle them with my app? For example, say I have a bam file on s3 which can only be accessed from certain IP addresses. Even if a user doesn't have access to the file, IGV will still launch, but upon zooming in, IGV makes a request to get the file and then it throws a 403. Is there any way to catch the errors emitted from IGV after the browser is created?

**Comment by jrobinso** [comment]
No, that would be complicated,  igv is an application not a function call.   Even if you caught errors on creation,  the 403 is not thrown then.   Actually that is not even an exception, strictly speaking, its just a status code on the response

For this specific use of igv you could write some code to access the file,  check the status code of the response, and check for 403 before launching IGV
