### ISSUE TITLE
Search not working for annotation names with space(s)

### ISSUE THREAD

**Issue by tiffanydai** [igvteam/igv.js#907]
Hey IGV.js team! 

`      const options = {
        reference: {
          fastaURL,
          indexURL,
          withCredentials: true
        },
        tracks: [
          {
            name: "Annotations",
            type: "annotation",
            format: "bed",
            delimiter: "\t",
            url,
            displayMode: "EXPANDED",
            autoHeight: true,
            maxHeight: 200,
            indexed: false,
            searchable: true,
            withCredentials: true
          }
        ]
      };`

![image](https://user-images.githubusercontent.com/35508772/57332694-1e937700-70d0-11e9-89fb-542ba667e252.png)

In setting up the annotation/bed track, I've included "delimiter: "\t"" in order to allow for spaces in feature names, which works well. However, searching for any feature that has a space in the name then doesn't seem to work. Can you try it out to see if you can reproduce the bug on your end? 

Thanks for your hard work on this awesome embeddable component!

**Comment by jrobinso** [comment]
Spaces are used to separate search terms,  you can search for multiple
terms to get split screen views.  So in your example a search is done for
"kan2"   and "marker" and neither are found.

Looking at the code we don't have a way to enter spaces currently.   I will
look into options to support this.

**Comment by tiffanydai** [comment]
Ah, I didn't know about multiple searches; the split-screen view is really cool. So feature names with spaces conflict with existing functionality...Maybe the search could default to the original functionality of searching for the terms separately, then check for the entire search term as one annotation name? Meaning that multi-search would not be supported for feature names containing spaces. Just a thought...thanks for looking into it!!

**Comment by jrobinso** [comment]
I just pushed a change that should allow for spaces.   If you are building
from source you can pull and try it now.   It does exactly what you
suggest,  it occure to me as well,  if the original search comes up empty
and the string has spaces try it again as a single-locus search.

**Comment by jrobinso** [comment]
If you're not building from source you can download from here:  http://igv.org/web/snapshot/dist/

Let me know if this works, or not.

**Comment by tiffanydai** [comment]
I recently switched over to importing from npm; does the latest version of https://www.npmjs.com/package/igv (v2.2.10) include the change that you pushed? Thanks for the lightning-quick turnaround :)

**Comment by jrobinso** [comment]
No, that will be in the next release.    You can import with node directly
from our repository, not recommended for production builds obviously, I
forgot the exact syntax but I think you just list our repository url as a
dependency.

Sometimes its faster to just do it.

**Comment by tiffanydai** [comment]
That's true, I'm switching back! 

I just tried it out (through igv.esm.min.js downloaded from http://igv.org/web/snapshot/dist/), and I do see a difference in behavior...the 'Unrecognized locus' dialog doesn't pop up anymore, so I assume that the browser does find the annotation? The view doesn't switch to the annotation though; it stays at whatever base pair range that you're currently on. 

This is the sequence that I'm using to test it: 
[testing.zip](https://github.com/igvteam/igv.js/files/3154805/testing.zip)
The .fasta and .fai are a bit customized (the .fasta doesn't have a header, and the .fai indexing starts at 0) because I'm directly responding to the range request rather than using files. But you can probably just use the bed file content with some other sequence to test the annotation name search? 

Thank you for your help, @jrobinso!!

**Comment by jrobinso** [comment]
Looking into this now.  One comment, your bed track line is not legal and
won't be parsed properly, a track line must start with "track",  not
"bedcontent"

**Comment by jrobinso** [comment]
sorry, stupid error, it should be working now

**Comment by tiffanydai** [comment]
@jrobinso Tested it out and can confirm that it's working now, thank you for being so responsive! Also, my bad for the 'bedContent' at the beginning of the .bed file...I had console.logged the info as bedContent and inadvertently copied it into the file. Thanks again for looking into this :)
