### ISSUE TITLE
VCF with END sub-field on INFO field

### ISSUE THREAD

**Issue by lmtani** [igvteam/igv.js#908]
Hello,

When loading a VCF file on java IGV the position of each CNV is rendered as an interval, where POSITION is the start and INFO.END is the end.

Example:

```
14	20007562	.	N	<DEL>	20	PASS	NS=1;SVTYPE=DEL;END=20404761;SVLEN=397200;RATIO=0.70	GT:AD:PGT:PID	0/1:0,0:0/1
```

Java IGV renders

![image](https://user-images.githubusercontent.com/12699242/57455344-54a43880-7241-11e9-99b2-9324bf4206ae.png)

IGV.js renders

![image](https://user-images.githubusercontent.com/12699242/57456195-5111b100-7243-11e9-9d28-a6e99eb2237a.png)

Is it possible to have the same representation on both apps? I saw in VCFv4.2 that 'END' is one of the reserved keys for the info field.

**Comment by jrobinso** [comment]
Thanks for pointing that our.   I'll look into it.    Do you happen to have a small (or large) vcf file I can test this with?

**Comment by lmtani** [comment]
Yes, it's available through the following links:

https://storage.googleapis.com/required-files/temp/ZHQ076-001.cnv.GRCh37.vcf.gz
https://storage.googleapis.com/required-files/temp/ZHQ076-001.cnv.GRCh37.vcf.gz.tbi

Thanks,

**Comment by lmtani** [comment]
@jrobinso I think we can close this issue. I verify that in the last release this feature is working (track cnv).

![image](https://user-images.githubusercontent.com/12699242/66127591-72908200-e5c2-11e9-8729-a28a50212d45.png)

Thanks!
