### ISSUE TITLE
routine addition of new genomes?

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#909]
@jrobinso Just got this request from an ````igvR```` user:
````
Do you plan to extend the list of supported genomes in the near future? 
Will it also be possible to load genomes from a file?
I would personally be very interested in support for the genome of 
the malaria parasite Plasmodium falciparum 3D7.
````
I host tair10 semi-privately - private only because the urls are not known to anybody.  I'd be glad to contribute that to a public host if that makes any sense.   
Any suggestions on how igvR users could also contribute genomes to a public host if they wanted to?

**Comment by jrobinso** [comment]
You can load genomes with the "browser.loadGenome" object,  typically an
app might present a pulldown list or other widget for selection then call
this function with a reference genome configuration object to load it.
See  https://github.com/igvteam/igv.js/wiki/Browser-Control-2.0

**Comment by jrobinso** [comment]
We use this API with our own app,   igv.org/app.   The code controlling the
genome pulldown is in genomeLoadController.js
https://github.com/igvteam/igv-webapp/blob/master/js/genomeLoadController.js

**Comment by jrobinso** [comment]
@paul-shannon I'm not familiar with igvR,  but perhaps providing a bridge function to the javascript browser.loadGenome function would also be a good idea,  then users can load anything they want.

**Comment by paul-shannon** [comment]
Jim,

Are all of the genomes listed here available on public webservers, ready to use with igv.js?

   https://software.broadinstitute.org/software/igv/Genomes

**Comment by jrobinso** [comment]
No, they are not, but the list of genomes in the webapp are.   Look at the
igv-webapp project,  under "resources/genomes.json".   This is also
available at https://igv.org/app/resources/genomes.json
<http://igv.org/app/resources/genomes.json>.   You can read and parse this
json to populate a menu,  the json objects in the array can be passed
directly to browser.loadGenome.

We can of course extend this list.

**Comment by paul-shannon** [comment]
> We can of course extend this list.

One of my users needs P.falciparum.   If I work that up, may I contribute it?

**Comment by jrobinso** [comment]
Yes,  if its all public and not embargoed etc.
