### ISSUE TITLE
wiki incorrectly says "firstInPairStrand"

### ISSUE THREAD

**Issue by odoublewen** [igvteam/igv.js#911]
The wiki [here](https://github.com/igvteam/igv.js/wiki/Alignment-Track) says:

Property | Description | Default
-- | -- | --
colorBy | Alignment color option: one of "none", "strand", "**firstInPairStrand**", or "tag". Specify tag with colorByTag | "none"

But the [code says](https://github.com/igvteam/igv.js/blob/master/js/bam/bamTrack.js#L1137) it should be `firstOfPairStrand`

**Comment by jrobinso** [comment]
corrected, thanks
