### ISSUE TITLE
webpack issue loading igv chunk in IE11

### ISSUE THREAD

**Issue by alisman** [igvteam/igv.js#913]
I'm loading igv.esm.js. We recently upgraded webpack 3->4 and now it's breaking in IE11.  Webpack chunk loading seems to barn on when it loads the igv chunk.  Anyone have any ideas?  It definately seems like it was the upgrade to webpack 4 that introduced this error

![image](https://user-images.githubusercontent.com/186521/58271359-de7ff580-7d59-11e9-812a-c5b1667a5fca.png)

**Comment by jrobinso** [comment]
Sorry no,  I don't have any idea.   Is this error specific to IE?

**Comment by alisman** [comment]
It is specific to IE11 yes.  I believe it has something to do with webpack 11 and the esm module code in igv.esm.js.   The bundle which is break (above) is the igv module.  Just wondering if anyone else has experienced this.

**Comment by cmdcolin** [comment]
Generally these "Loading chunk N failed" in IE11 are due to es6 code remaining in the distribution. Since the igv.esm.js code is definitely es6 code you will probably need to babelify it

**Comment by jrobinso** [comment]
Thanks @cmdcolin good catch.  The es6 module bundle is indeed es6 code,  if IE11 doesn't support es6 you will need to babel translate it.     It is assumed that any application using an es6 import supports es6.   You might try the non-es6 bundle,  igv.min.js.

**Comment by alisman** [comment]
I believe that even igv.min.js has something about it which is not friendly to IE11 or to the webpack loaders.  In other words, you have to run babel even on igv.min.js in order to get it to get it working in IE11.  It might just be the module wrapping itself.   I can only get it work (igv.min.js) when I run it through babel first.  This is not true of any of our other deps in node_modules, so I'm assuming that by convention, deps should not need transpilation to work in es5.  
I realize this is not exactly an emergency.

**Comment by jrobinso** [comment]
@alisman What rules do you use with babel?  The rules we use are below.    I'm surprised actually that it works in IE11 at all, its not a browser we officially support,  but if there is some simple change we can make to babel to make it work I'd like to know about it.

```
presets: [
                            ["@babel/preset-env", {
                                "targets": {
                                    // The % refers to the global coverage of users from browserslist
                                    "browsers":  ">0.1%"
                                }
                            }]
                        ]
```

**Comment by alisman** [comment]
Hi Jim, thanks for your attention.   The short answer is, I'm not totally sure what it is.  It's possible it's something to do with my own webpack configuration.   Anyway, I fixed it by configuring Webpack to run babel on igv.min.js even though it's in node_modules.  Probably you shouldn't waste too much time on it.   Thanks!

**Comment by jrobinso** [comment]
OK,  I'd like to get it to work out of the box if possible.   Do you use
any presets with babel?  If you don't mind sharing your babel or webpack
configuration I will see if I spot anything.

I might need to change the documentation because looking at my babel config
I don't technically target ES5,  the rule literally says target all
browsers with market share as defined by browserlist > 0.1%.   This should
include IE11 but maybe its not.

>

**Comment by alisman** [comment]
I just checked.  We are using preset-env but with no target specified.   That means it transpiles all 2015+ code.  (this is apparently not recommended by babel but, if anything, should produce OVER-compatibility).   I just tested your example (with igv.min.js loaded by script tag) in IE11 and it seems to work.  So my theory is that the problem lies in the instrumentation code which makes igv compatible with module loaders like webpack.  That would explain why it doesn't break when igv is loaded as an old fashioned js dep.

**Comment by nevace** [comment]
By convention, a node module is usually transpiled to es5 and webpack ignores the node_modules folder by default. To ensure this module is transpiled, you can exclude it from the 'exclude' rules.

`{
    test: /\.js$/,
    exclude: /node_modules(?!\/igv)/
    loader: 'babel-loader'
}`

**Comment by jrobinso** [comment]
Update, I've changed the bable rules to just use "preset-env" with no target.   I don't have access to IE11 to test (thus we don't officially support it),  but hopefully that resolves the issue.  If not re-open.
