### ISSUE TITLE
Different color between paired strands

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#916]
Hey IGV team,

I've been playing around with different view options to try to reach full parity with my team's current implementation of JBrowse and was wondering about something in the alignment track.  When viewing with `readAsPairs` enabled and `colorBy: 'strand'` there's a thin line connecting the end of the `posStrand` to the beginning of the `negStrand` when there is a gap between them.  This line seems to use the same color as `posStrandColor` which means if `alignmentRowHeight` is small there's no distinguishable difference between the end of the pos strand and the gap before the neg strand.  Can this connecting line get a separate color config option please?

`alignmentRowHeight: 10`:
![image](https://user-images.githubusercontent.com/38264214/59119472-208b6880-8910-11e9-8081-ae8f07c3b9b2.png)

`alignmentRowHeight: 3`:
![image](https://user-images.githubusercontent.com/38264214/59119488-28e3a380-8910-11e9-8b61-e650b8cbb293.png)

**Comment by jrobinso** [comment]
In general the goal is to be consistent with IGV desktop, but in this case we are not, coloring by + strand is a mistake.  IGV desktop colors the connecting line dark gray.    I'll make that change.    I'm not sure what JBrowse does but I think in general they are consistent with IGV for alignment viewing.

**Comment by athomson-archerdx** [comment]
Thanks @jrobinso !  Our JBrowse implementation has nothing shown between the strands so I was hoping to be able to set the color to white for the same effect.  Being dark grey instead of the same color as the + strand should be totally fine :+1:

**Comment by jrobinso** [comment]
I can add a config parameter to specify the color,  could you help me name
it?

**Comment by athomson-archerdx** [comment]
That's great news, thanks for the quick response!  My team came up with `nonOverlappingPairedReadConnectorColor` but if that's too verbose we're not picky about it.

**Comment by jrobinso** [comment]
I shortened it to pairConnectorColor

**Comment by athomson-archerdx** [comment]
Looking good when I apply those changes locally :+1:  Any estimate on when this will be included in the minified distribution?

**Comment by jrobinso** [comment]
Just released as 2.2.12

**Comment by jrobinso** [comment]
BTW the connector line color option is  ```pairConnectorColor```
