### ISSUE TITLE
Save whole image of genome browser as SVG

### ISSUE THREAD

**Issue by Alex-Willenbrink** [igvteam/igv.js#918]
I see that there's a way to export a single track to an svg if you right click it and save. Is there any way to save an svg of the whole genome browser though? 

In issue #563 it was mentioned this feature would be possible by version 2.1. Is this implemented? If so how do I do this?

Thanks!

**Comment by turner** [comment]
Alex, `browser.toSVG()` is what you want. This will save all tracks including cytoband and ruler.

**Comment by Alex-Willenbrink** [comment]
Just what I need. You da man!

**Comment by jrobinso** [comment]
@Alex-Willenbrink should point out this is not released,  I'll do so later today.   It's been there but not exposed as an API function.  toSVG() will return a string.   We're also adding an optional button on the toolbar that will download it to a file.

**Comment by Alex-Willenbrink** [comment]
Yeah, I was wondering why I couldn't find this function in the documentation or the browser object. 

The "file-saver" library makes converting a string to buffer and saving it locally a breeze so strings work great for me! Although, yes I agree in that making the default option to simply download the svg file probably makes more sense.

Thanks again for your help :)

**Comment by jrobinso** [comment]
Just released as 2.1.12

**Comment by turner** [comment]
Note, there are two SVG related functions:

- `browser.toSVG()` returns a serialized SVG object

- `browser.renderSVG()` saves the browser in SVG format to a file. 

Wiki: https://github.com/igvteam/igv.js/wiki/Browser-Control-2.0
