### ISSUE TITLE
IGV-Web application not showing URLs for external links

### ISSUE THREAD

**Issue by gitanoqevaporelmundoentero** [igvteam/igv.js#921]
When loading a bed file with following information:

```
track name=test_track type=bedDetail description="Custom track" db=hg19 visibility=3 url="http://testserver.edu/query?id=$$"
chr1	23803	24448	event1	1	+
chr1	26582	27137	event2	1	-
chr1	30693	31131	event3	1	+
chr1	31292	31754	event4	1	+
chr1	38058	40626	event5	1	+
chr1	38255	40294	event6	1	+
chr1	43242	45753	event7	1	+
chr1	54464	55608	event8	1	+
chr1	61695	62229	event9	1	-
```

Desktop application of IGV shows the external link (http://testserver.edu/query?id=eventX) when clicking on one of the regions of the bed file. But IGV-Web application doesn't show external links. Can this feature be enabled in IGV-Web? Or is it not yet implemented? If not, is it planned to implement this feature?

Thanx in advance!

**Comment by helgathorv** [comment]
Reopening this issue in igv.js (was in the IGV desktop repo)
