### ISSUE TITLE
Displaying exon numbers in IGV web app

### ISSUE THREAD

**Issue by dsonkin** [igvteam/igv.js#922]
Desktop version of IGV has very useful feature of displaying exon number when mouse pointer is over exon area of transcript reference track. Web app version of IGV shows information about transcript reference after clicking on exon area of transcript reference track, however it does not provide exon number. It would be very useful if IGV web app can also show exon numbers.

**Comment by skycolloredo** [comment]
This would be great!

**Comment by jrobinso** [comment]
When implementing this for IGV desktop I discovered there is no standard for exon number,  your exon number 3 might be someone else's exon number 4,  but I can investigate what we did and do the same.   It is our interpretation of exon number however, whatever we implement,  that is where my hesitancy comes from.

**Comment by skycolloredo** [comment]
Yes this makes complete sense. I would be interested in knowing how the determination is made in the desktop version.

**Comment by jrobinso** [comment]
It looks like it just counts from the 5' end, starting at 1.    This includes any UTRs before the first coding section.   The count is per transcript.   So the same exon on different isoforms of a gene can have different exon numbers.

**Comment by skycolloredo** [comment]
Ah yeah, that makes sense. Do you have plans to bring that over to the javascript implementation? Or too imprecise?

**Comment by jrobinso** [comment]
@skycolloredo It would be nice. The basic issue is there are 44 open issues here and slightly more in IGV desktop.   I can't do them all so they get prioritized, and this hasn't landed at the top yet.

**Comment by skycolloredo** [comment]
@jrobinso Yes completely understand, this is a huge amount of work and all tremendously valuable. Thank you for all that you do and your team do!

**Comment by bbarrick** [comment]
I just wanted to throw my support behind this feature. It would be great if it could accessed  programmatically.

**Comment by jrobinso** [comment]
This is implemented and will go out in the next release, probably by the end of the week.  To recap, it just counts exons from the 5' end starting at 1.  In some rare cases it might not be able to safely do this,  specifically if using an indexed GFF file and the parent feature is not completely contained in the query window (the "visibility window").   When that happens we might not have all the exons, so we really don't know what the numbers would be.   This could occur with a combination of large genes and small visibility windows.    This is never an issue with "bed" format as the entire transcript is a single feature (line).
