### ISSUE TITLE
igv.js:19426 Uncaught (in promise) TypeError: First argument to DataView constructor must be an ArrayBuffer

### ISSUE THREAD

**Issue by webxinl** [igvteam/igv.js#930]
use vue 
igvDiv err

**Comment by jrobinso** [comment]
@webxinl when submitting a git issue please provide details on how to reproduce, what version you are using, etc.

**Comment by webxinl** [comment]
Sorry, my English is not very good，in package.josn    "igv": "^2.2.12",    "vue": "2.5.17", 
use html  igv is Ok, but use vue is error。
in mounted() 
![igv](https://user-images.githubusercontent.com/42405865/60110052-0a99f680-979e-11e9-864e-055e916bc96c.png)
if igvDiv is stirng such as 'igvDiv'  No error reporting，about igvDiv remind igv.js:19426 Uncaught (in promise) TypeError: First argument to DataView constructor must be an ArrayBuffer
options is ok
I hope you can help me
thanks

**Comment by jrobinso** [comment]
@webxinl What is "vue"?

**Comment by jrobinso** [comment]
I will need a reproducible test case in plain html to help,  the error message is too generic to be of much value.
