### ISSUE TITLE
Initial zoom on searchable feature

### ISSUE THREAD

**Issue by athomson-archerdx** [igvteam/igv.js#931]
When I try to use a feature name from a searchable annotation track as the initial locus, it throws an error `Unrecognized locus [my_gene_name]`.  It loads showing the full reference genome, and after the searchable track has finished loading I can search by the gene name to zoom there.  Is there any way to use this searchable name as the initial locus?

**Comment by jrobinso** [comment]
That would be difficult as the app is initialized before the asynchronous load of tracks.  You can set the initial locus explicitly,  e.g.  chr1:1000-2000.
