### ISSUE TITLE
Possible vulnerabilities for page that counts the library's usage

### ISSUE THREAD

**Issue by callunity** [igvteam/igv.js#932]
We recently did a security audit on an application that uses igv.js, and it raised some concerns about the broadinstitute.org [page used to count the library's usage](https://github.com/igvteam/igv.js/blob/394ef66b73960972ba6bc5ad48c1b286e9e6e4db/js/igvxhr.js#L586). Do you know if it would be possible to update the settings for serving this page?

Thanks for all the work you've done on IGV, and to port it to JavaScript!

| Medium | X-Frame-Options Header Not Set |
|------------|-----------------------------------------------|
| Description | X-Frame-Options header is not included in the HTTP response to protect against 'ClickJacking' attacks. |
| URL | https://data.broadinstitute.org/igv/projects/current/counter_igvjs.php?version=0 |
|   Method | GET |
|   Parameter | X-Frame-Options |
| Solution | Most modern Web browsers support the X-Frame-Options HTTP header. Ensure it's set on all web pages returned by your site (if you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. ALLOW-FROM allows specific websites to frame the web page in supported web browsers). |
| Reference | http://blogs.msdn.com/b/ieinternals/archive/2010/03/30/combating-clickjacking-with-x-frame-options.aspx |
| CWE Id | 16 |
| WASC Id | 15 |
| Source ID | 3 |

| Low | Incomplete or No Cache-control and Pragma HTTP Header Set |
|------------|-----------------------------------------------|
| Description | The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content. |
| URL | https://data.broadinstitute.org/igv/projects/current/counter_igvjs.php?version=0 |
|   Method | GET |
|   Parameter | Cache-Control |
| Solution | Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate; and that the pragma HTTP header is set with no-cache. |
| Reference | https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching |
| CWE Id | 525 |
| WASC Id | 13 |
| Source ID | 3 |

| Low | X-Content-Type-Options Header Missing |
|------------|-----------------------------------------------|
| Description | The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing. |
| URL | https://data.broadinstitute.org/igv/projects/current/counter_igvjs.php?version=0 |
|   Method | GET |
|   Parameter | X-Content-Type-Options |
| Solution | Ensure that the application/web server sets the Content-Type header appropriately, and that it sets the X-Content-Type-Options header to 'nosniff' for all web pages. If possible, ensure that the end user uses a standards-compliant and modern web browser that does not perform MIME-sniffing at all, or that can be directed by the web application/web server to not perform MIME-sniffing. |
| Reference | http://msdn.microsoft.com/en-us/library/ie/gg622941%28v=vs.85%29.aspx<br>https://www.owasp.org/index.php/List_of_useful_HTTP_headers |
| CWE Id | 16 |
| WASC Id | 15 |
| Source ID | 3 |

| Low | Web Browser XSS Protection Not Enabled |
|------------|-----------------------------------------------|
| Description | Web Browser XSS Protection is not enabled, or is disabled by the configuration of the 'X-XSS-Protection' HTTP response header on the web server |
| URL | https://data.broadinstitute.org/igv/projects/current/counter_igvjs.php?version=0 |
|   Method | GET |
|   Parameter | X-XSS-Protection |
| Solution | Ensure that the web browser's XSS filter is enabled, by setting the X-XSS-Protection HTTP response header to '1'. |
| Other information | The X-XSS-Protection HTTP response header allows the web server to enable or disable the web browser's XSS protection mechanism. The following values would attempt to enable it:<br>X-XSS-Protection: 1; mode=block<br<X-XSS-Protection: 1; report=http://www.example.com/xss<br>The following values would disable it:<br>X-XSS-Protection: 0<br>The X-XSS-Protection HTTP response header is currently supported on Internet Explorer, Chrome and Safari (WebKit).<br>Note that this alert is only raised if the response body could potentially contain an XSS payload (with a text-based content type, with a non-zero length). |
| Reference | https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet<br>https://blog.veracode.com/2014/03/guidelines-for-setting-security-headers/ |
| CWE Id | 933 |
| WASC Id | 14 |
| Source ID | 3 |

**Comment by jrobinso** [comment]
We will ask the Broad IT department to determine which, if any, of these headers they are willing to set.  We load many resources from the Broad Institute's servers, I assume you will get the same report for any resource loaded from broadinstitute.org or igv.org.

**Comment by callunity** [comment]
Thanks for the update, that makes sense.

**Comment by jrobinso** [comment]
@callunity The headers should now be set on this page.

**Comment by jrobinso** [comment]
I think this is fixed, re-open if not.
