### ISSUE TITLE
Using the bigwig reader standalone?

### ISSUE THREAD

**Issue by endrebak** [igvteam/igv.js#933]
Hi and thanks for this great software. 

I have some bigwig data that I want to visualize in a custom way with D3. Is your bigwig-parsing code close to being able to be used in a stand-alone way? I am a fledgling js programmer so I cannot immediately tell.

If you had an example of using the bigwig reader without igv.js, that might be another potential source of cites.

Thanks anyways, and feel free to close if you feel this isn’t appropriate for the issues section.

**Comment by jrobinso** [comment]
Hi, its possible but igv.js is rather heavy for that.   I've started a new project for just this purpose called "streamcode" https://github.com/igvteam/streamcode",  but it is not released and packaged for web use yet.  When that is ready I'll update here. 

If you're only interested in bigwig you might try this, from the JBrowse project:  https://github.com/GMOD/bbi-js

**Comment by endrebak** [comment]
Thanks! So streamcode will do what exactly? Read bw into an array?

**Comment by jrobinso** [comment]
You can see what it does with this unit test, it returns a promise for an array of objects ("features") representing bigwig records.   The objects contain chr, start, end, and value fields.  https://github.com/igvteam/streamcode/blob/master/test/bwReader.test.js

As I noted this isn't released or packaged for web use yet.  You should also check out https://github.com/GMOD/bbi-js which is released.  Streamcode is to present a consistent interface for all IGV file types, and will become the igv.js file reading library.   If you are only interested in bigwig / bigbed the GMOD project might be a better choice.

**Comment by jrobinso** [comment]
@endrebak Sorry for the long delay, you probably have found a solution by now but I recommend the GMOD library referenced above.

**Comment by gaitat** [comment]
Streamcode is an excellent idea. Any idea when will it be released. I noticed there hasn't been too much activity.

**Comment by jrobinso** [comment]
@gaitat most of my time is spent on igv.js and IGV,  its not clear to me that "streamcode" is needed with the existence of the GMOD modules.   The long term plan is to break igv.js into multiple modules, one of which would be effectively "streamcode" but probably called something else.   We have made a small step in this direction with some of the UI components in igv-ui.   However I don't have an ETA for that,  this is a very small team.

**Comment by gaitat** [comment]
I did see the separation of `igv-ui`, `igv-util` and `data-modal` and thought that something like `igv-data` (or `streamcode`) that "presents a consistent interface for all IGV file types" would be natural. Do the GMOD modules provide such a consistency ?

**Comment by jrobinso** [comment]
You can check the GMOD modules out yourself,  I am not an expert in all of them, but in general they are more heterogenous in their output.

**Comment by gaitat** [comment]
@jrobinso You might find helpful our attempt at separating the `igv-data` parsing code from the rest of `igv`. You can take a look at https://github.com/dtsamitros/igv.js under the branch `saki/data`.
Basically we use a new index file https://github.com/dtsamitros/igv.js/blob/saki/data/src/main.js to generate a data parsing only bundle:
```
import FeatureFileReader from "../js/feature/featureFileReader";
import FeatureParser from "../js/feature/featureParser";
import FeatureSource from "../js/feature/featureSource";
import IntervalTree from "../js/intervalTree";

export {
    FeatureFileReader,
    FeatureParser,
    FeatureSource,
    IntervalTree,
}
```

and convert an `Alert()` message to a regular `alert()` (Since we didn't want ui code in the `igv-data` code).
