### ISSUE TITLE
variant data: separate color for missing genotype

### ISSUE THREAD

**Issue by ariloytynoja** [igvteam/igv.js#934]
Hi there,
It seems that missing genotypes (./.) are shown using "homvarColor". With less deeply sequenced data missing genotypes are rather frequent and displaying those sites as variants is confusing. Would it be possible to have a separate color for missing genotypes please. 

Regards, Ari

**Comment by jrobinso** [comment]
Hi, sorry for the long delay.  There is a new option "noCallColor" to be released with 1.4.0 shortly.  By default it is very light gray, almost white, but can be set in the config object.
