### ISSUE TITLE
Sort by base dont include softclip bases

### ISSUE THREAD

**Issue by desnar** [igvteam/igv.js#935]
Hi Igvjs Team,  

I find that sort by base in igv.js and igv desktop behave differently.
For example, I sort the same pos in same bam. In igv desktop, it shows
![image](https://user-images.githubusercontent.com/7296885/60646897-0e4d0d80-9e6f-11e9-96d6-b6a3c02b3aab.png)

And in igv.js, it shows
![image](https://user-images.githubusercontent.com/7296885/60646989-3b012500-9e6f-11e9-88a7-5a3adf644efd.png)

It seems that sort by base dont include softclip base, and variant base may also not be shown in top.

**Comment by jrobinso** [comment]
Sorry for the delay in responding.  Soft clipped bases don't actually have a genomic position, they are not aligned, they are soft clipped.  If IGV desktop is doing that it is incorrect.  I will look further into it.

**Comment by jrobinso** [comment]
Also, sorting by base toggles the previous sort, so if you do it multiple times variant bases will appear alternately at top and bottom.
