### ISSUE TITLE
Default variant visibilityWindow too large, not 1MB as documented

### ISSUE THREAD

**Issue by lrowe** [igvteam/igv.js#940]
The `visibilityWindow` default is documented to be "1 MB for variants, 30 KB for alignments, whole chromosome for other track types" in https://github.com/igvteam/igv.js/wiki/Tracks-2.0. However when unspecified I see it loading a vcf file at a 40MB zoom level which eventually causes the browser window to be killed in Chrome or pops up the slow script warning in Firefox.

**Comment by jrobinso** [comment]
Yes I think I see the problem.  The documentation is a bit simplified, or out of date,  it should be at most 1 MB but could be much smaller if there are lots of samples.   It looks like the bug occurs when  there are few or perhaps no genotypes.    How many samples, if any, are in your VCF file?

**Comment by jrobinso** [comment]
@lrowe Actually the bug affected all vcfs, samples or not.   Just pushed a fix.   So the default is 1MB for VCF files with no samples,  can be less in a multi-sample VCF

**Comment by lrowe** [comment]
Looks like 14 samples in a combined 8GB VCF file with ~100 scaffolds for a draft genome. (My description here might not be entirely accurate as I'm an engineer rather than a bioinformatician.)

**Comment by jrobinso** [comment]
OK thanks for the report,  this should be fixed in the next point release.

**Comment by lrowe** [comment]
This fix doesn't seem to work as it appears `computeVisibilityWindow` is being called too late in the game.

It looks like the visibilityWindow check happens in `igv.Viewport.prototype.checkZoomIn` called by `viewportsToReload` in `igv.TrackView.prototype.updateViews`. When the viewport is too small this prevents the call to `await vp.loadFeatures()`. But this guard does not apply when visibilityWindow is undefined.

In the case visibilityWindow is undefined, `vp.loadFeatures()` is called and `computeVisibilityWindow` is called from `VariantTrack.prototype.getFileHeader` called from `VariantTrack.prototype.getFeatures` which goes on to call `self.featureSource.getFeatures` and eventually `igv.FeatureFileReader.prototype.readFeatures` requests a ~125MByte range of the file for the whole ~40MBase displayed on screen.

**Comment by jrobinso** [comment]
Can you give me a test case to reproduce this?   In my tests it works.     I am assuming your vcf file is indexed.

**Comment by jrobinso** [comment]
In particular I don't understand what you mean by  "When the viewport is too small..."

**Comment by jrobinso** [comment]
Never mind I can reproduce this.  Stay tuned.

**Comment by lrowe** [comment]
Thanks! Can confirm this fixes the issue for me.
