### ISSUE TITLE
Three-frame translation of lowercase reference sequence

### ISSUE THREAD

**Issue by tiffanydai** [igvteam/igv.js#941]
Hey igv.js team, 

In the translateSequence function, self.translationDict doesn't recognize codons from a lowercase reference sequence (e.g. "cgg" instead of "CGG"). Not a huge deal since I'll just make sure to always uppercase the ref seq's nucleotides now, but just thought you might want to know in case you want to account for it. 

Thanks as always for your awesome work and responsiveness! :)

**Comment by jrobinso** [comment]
@tiffanydai Thanks for the heads up,  I'll take care of it.

**Comment by jrobinso** [comment]
fixed
