### ISSUE TITLE
Use the app without internet connexion

### ISSUE THREAD

**Issue by florealcab** [igvteam/igv.js#943]
Hi,

Thank you for this beautiful and so useful app. I have a problem: I want to use it on a server which has no internet connexion (server is accessible only over intranet). But if we search il locus search by gene name, it makes a call to https://portals.broadinstitute.org/webservices/igv/locus?genome=hg19&name=<gene_name> si this call failed.

Is there a way to make this call locally or with a local file?

**Comment by jrobinso** [comment]
Yes, broad institute service is the default but you can configure your own
search service,  see here (bottom of page):
https://github.com/igvteam/igv.js/wiki/Browser-Configuration-2.0.

Also, you can mark an annotation track as "searchable",  see
https://github.com/igvteam/igv.js/wiki/Annotation-Track

**Comment by florealcab** [comment]
Thanks a lot, it will indeed solve my problem :) I close the issue
