### ISSUE TITLE
Wig won't load, behaves different than Bam

### ISSUE THREAD

**Issue by mikaell** [igvteam/igv.js#956]
Hello,
I have an issue drawing wig files. If I configure like this:

```
{
    name: 'Bam',
    url: '/remote/static?file=%2FUsers%2FSome%2FPath%2Ffile.bam',
    indexURL: '/remote/static?file=%2FUsers%2FSome%2FPath%2Ffile.bam.bai',
    sourceType: 'file',
    type: "alignment"
},

{
    name: 'Coverage',
    url: '/remote/static?file=%2FUsers%2FSome%2FPath%2Fcoverage.wig',
    sourceType: 'file',
    type: "wig",
    max: 30.0,
    color: "rgb(0, 0, 150)"
},
```

Then calling `igv.createBrowser(...)` I get the bam picture to appear, but not the wig. Looking in Wireshark there are HTTP GETS for bams:

    GET /remote/static?file=%2FUsers%2FSome%2FPath%2Ffile.bam

-but not for wigs. Playing around I found out that changing 'url' will make it work:

    url: "http://localhost:5000/public/static/coverage.wig

Will get me

    GET /public/static/coverage.wig

How come no GET-request is sent with the original configuration? They are identical but the behave differently.

Is there a way to make igv.js more verbose?

Anybody got a clue?

**Comment by jrobinso** [comment]
Its very unusual for a wig file to have a "bam" extension, if tat is
correct you have to explicitly set the format to
'wig'.   See https://github.com/igvteam/igv.js/wiki/Tracks-2.0

**Comment by mikaell** [comment]
Sorry, made a typo (updated now) -it is "coverage.wig". Any other idea?

**Comment by jrobinso** [comment]
I don't know what you are using fot a server or how that relative url could get translated to the correct one in either case, so no I don't have any idea.

**Comment by mikaell** [comment]
Ok. Thanks for your reply. We're running a Flask server. I'll see if I can come up with a workaround.

**Comment by jrobinso** [comment]
We ran a flask server for an internal project a few years ago and put the code out as an example here: https://github.com/igvteam/igv.js-flask.   I didn't do this work personally and am not an expert, but I notice we dis not escape our  data urls where you do.  See https://github.com/igvteam/igv.js-flask/blob/master/igvjs/static/js/init.js

**Comment by mikaell** [comment]
Thanks! I'll have a look.

**Comment by mikaell** [comment]
Hi again!

Opening up this issue again -if it's alright. 

I tried igv.js-flask and I have the same problem. Local wig files are not displayed. My init.js is like this:

```
function initBrowser() {

  var div,
          options,
          browser;

  div = document.getElementById("myDiv");
  options = {
      genome: "hg19",
      //locus: "22:24,375,771-24,376,878",
      tracks: [
                  {
                      url: 'static/data/public/test.bw',
                      name: 'BigWig'
                  },
                  {
                      url: 'static/data/public/test.bedGraph',
                      name: 'bedgraph'
                  },
                                  {
                            type: "wig",
                            name: "WIG (this works)",
                            url: "https://www.encodeproject.org/files/ENCFF356YES/@@download/ENCFF356YES.bigWig",
                            min: "0",
                            max: "30",
                            color: "rgb(0, 0, 150)"
                        },

              ]
  };

  browser = igv.createBrowser(div, options);
}
```

Results in:

<img width="1302" alt="Screenshot 2019-11-20 at 22 14 38" src="https://user-images.githubusercontent.com/1150065/69278724-2e455980-0be3-11ea-8638-5e11c97e0d68.png">

Any idea why local wigs are not displayed? Other than adding a wig track in init.js the code is untouched.

All help appreciated!
/Mikael

**Comment by dnil** [comment]
For the record, in the end we met success with explicit `format: bigwig`or `format: wig` on each track. Something was a bit off with auto-detection using our flask solution for serving partial files.

**Comment by jrobinso** [comment]
Auto-detection simply looks  at the file extension, I don't see any reason that wouldn't work from a flask server but in any event its better to be explicit.   Thanks for the update.
