### ISSUE TITLE
Error "loading track data" if more than 10 tracks loaded 

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [igvteam/igv.js#958]
Hi, I get Error "loading track data" if more than 10 tracks are loaded simultaneously. Web developer gives 206 error (partial content)Since there isn't a max limit to the number of tracks one can load, how to fix this error?

Thanks!

**Comment by jrobinso** [comment]
206 is not an error.  To help you I need a reproducible case I can run.

**Comment by jrobinso** [comment]
I can no longer access the test case (401 forbidden error).  If this is still a problem could you re-open with a test case I can run?  Also, for the test case could you use non-minified versions of igv.js,  either "igv.js" or "igv.esm.js".  Thanks.
