### ISSUE TITLE
Locus Search function is not working for SNPs (rs id)

### ISSUE THREAD

**Issue by gumuslab-mssm** [igvteam/igv.js#964]
We are using a customized version of igv.js embedded within our project; but i think the following problem persists in other igv.js versions as well.

I was able to search for specific SNPs (e.g. rs10495207) using the 'Locus Search' option at the top-left IGV toolbar. Last few days I noticed this functionality is not working properly and if I were to search for a specific SNP, I get the following error message: "Unrecognized locus rs10495207".

Would it be possible to fix this issue? Thanks.

**Comment by jrobinso** [comment]
What genome assembly are you using?
