### ISSUE TITLE
hg19 gene symbol search appears broken

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#967]
@jrobinso   
Two symptoms:
 https://igv.org/web/release/2.2.17/examples/multi-locus.html "TREM2" not found
Javascript console reports "failed to load resource"

![image](https://user-images.githubusercontent.com/2480712/64299218-2c95bf00-cf2d-11e9-9d5b-994db78bdbdf.png)

**Comment by jrobinso** [comment]
Thanks for the report.  The same service is working here,
http://igv.org/app/, but looks misconfigured in those examples.

**Comment by paul-shannon** [comment]
Thanks, Jim.  Updating my hg19 configuration to the new (?) minimal form solved my problem.
