### ISSUE TITLE
Add option to sort by tag in the alignment track config

### ISSUE THREAD

**Issue by roelnoten** [igvteam/igv.js#969]
For my usecase it's important to sort the bam reads by a tag (ZS); like the desktop version can do.
This is currently not supported it seems.
We would use it together with the currently available colorByTag option.

I tried to circumvent it by sorting the bam with samtools on the tag and loading the bam without a bai (it's small) but the reads seem to show up in random order. For every browser refresh the reads can be in a different order vertically.

I understand this is not a bug but a feature request. Any idea on planning or guidance on implementing it ourselves would be highly appreciated.

**Comment by jrobinso** [comment]
I will add this, there is nothing you can do from your side.

**Comment by gavinkurgan** [comment]
Great to hear that this will be incorporated! We use this "sort by tag" function frequently in our group as well. Just out of curiosity Jim, do you have any sort of estimate on when this feature may be added?

**Comment by jrobinso** [comment]
if not there by end of month ping again.

**Comment by roelnoten** [comment]
Hi, is it possible to give an ETA, then we can feedback to our customer or need to find a workaround.
Thanks!

**Comment by jrobinso** [comment]
@roelnoten It didn't make this release because higher priority issues (i.e. bugs) arose.  So next release.  Generally feature releases are monthly, bug fix can be more frequent, but let's say 3-4 weeks.

**Comment by roelnoten** [comment]
Hi, 
We tried out the 2.3.1 release and stumbled on 2 issues concerning this sortbytag feature request:
- Our tag values are numbers, not strings. And then the sorting fails with an error, because you try to calculate the hashcode of the value which does a split() function which doesn't exist on a number. In case the tagvalue is a number BamAlignmentRow.prototype.calculateScore should just return it directly. 
- the sort by tag is now available in the popup menu. Could you also make it available in the track configuration json? We need to open IGV with the track already sorted. Or is there a way to trigger it ourselves after loadTrack() and search() ?

thanks

**Comment by jrobinso** [comment]
Sort-by-tag should now be working for numeric tags.  RE making it available in the track configuration, that is another topic that will require some throught.  Its not as straightforward as you might think.  Please open a separate issue for that as it really is a separate problem.

**Comment by roelnoten** [comment]
I've created https://github.com/igvteam/igv.js/issues/1001.

Meanwhile, is there a psibility to achieve this functionality by invoking javascript?
We tried something like:
                       browser.search('chr6').then(function() {
                            async function f() {
                                const alignmentContainer = await newTrack.alignmentTrack.featureSource.getAlignments("chr6", 2, 200);
                                var options= {chr: "chr6", position: 104, sortOption: "TAG", tag: "ZS", direction: true};
                                newTrack.alignmentTrack.sortAlignmentRows(options, alignmentContainer);
                            }
                            f();
                        });
When debugging i see this triggers the BamAlignmentRow.prototype.calculateScore function but we see no changes in the view. Is there a kind of refresh() or repaint() we need to call?

**Comment by jrobinso** [comment]
Try adding this after your call to "sortAlignmentRows".   Consider this a workaround while I work on an officially supported way to do this  (#1001)

```newTrack.trackView.repaintViews();```
