### ISSUE TITLE
function request, with Promise?   getTrackNames()

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#970]
I've been rewriting [igvR](https://bioconductor.org/packages/release/bioc/html/igvR.html)'s javascript code to use Promises - actually I use async + await.   This feature of igv.js is a huge help:  R users can, for instance, issue  commands in a script, confident that each of them waits for the corresponding igv.js browser operation to complete:
````
setGenome
loadTrack
set/GetGenomicLocation
````
I have a problem, however, with my R ````getTrackNames(igv)```` function.  It returns too soon, not yet blocking on (for example) any still-running calls to ````addTrack````.   Maybe this is because my javascript learns the names of existing tracks from un-Promised code?  

I had hoped that since ````addTrack```` blocks until the Javascript code is complete, ````getTracknames```` would only execute when all browser code has completed.  I may be misjudging, but it seems that ````igvBrowser.trackViews```` is not updated as part of ````igvBrowser.loadTrack```` call.  It seems to happen later, and my R code queries my javascript code before the update of trackViews is complete.

Here is my javascript code for getting the track names: 
````
   var result = [];
   var count = igvBrowser.trackViews.length;

   for(var i=0; i < count; i++){
      var trackName = igvBrowser.trackViews[i].track.name;
      if(trackName.length > 0){
         result.push(trackName)
	 }
      } // for i

   self.hub.send({cmd: msg.callback, status: "success", callback: "", payload: result});
````
Maybe igv.js could implement ````getTrackNames()```` using a Promise which does not resolve until other earlier Promises (like add track) resolve?

**Comment by jrobinso** [comment]
I see the issue, but not following your solution.  updateViews gets called
from addTrack, but it does not await the completion of the async
updataeViews.  I think that is what ou are seeing.  Ill look at that.

I assume you are awaiting the completion of load track.

**Comment by paul-shannon** [comment]
Hi Jim,

Yes, I am awaiting the completion of load track.

It *appears* (I may be judging this wrong) that when I

   o  await the completion of igvBrowser.loadTrack, this returns only when the track is visible in the browser
   o  when I subsequently, very quickly, query igvBrowser.trackViews, it is not yet been updated with the new track
   o  if I wait a few seconds, query igvBrowser.trackViews again, it is updated just fine, has the new track

- Paul

**Comment by jrobinso** [comment]
I can see how this might happen, but would like to reproduce it before fixing.  Otherwise I can't be sure it is fixed.  I'm trying with the snippet below, so far no luck.  Could you try tweaking it or giving me another working snippet that reproduces this?

```
igv.createBrowser(document.getElementById('igvDiv'), {
        genome: "hg19",
        locus: "chr8:128,747,267-128,754,546"

    })
        .then(async function (browser) {

            const track = await browser.loadTrack(                    {
                type: 'alignment',
                format: 'cram',
                url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram',
                indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai',
                name: 'HG00096'
            })

            var count = browser.trackViews.length;
            for(var i=0; i < count; i++){
                var trackName = browser.trackViews[i].track.name;
                console.log(trackName);
            }
        })
```

**Comment by jrobinso** [comment]
igvBrowser.trackViews is updated before loadTrack resolves

**Comment by paul-shannon** [comment]
Thanks for the demo script.   It works for me (thought with an "undefined" genome error, see below, which may not be relevant). 

My await failure (if that's what it in fact is) happens when I call loadTrack later, after the browser is already up and functioning.  It's in that circumstance that browser.trackViews is apparently slow to update.   I'll create an example of that (calling loadTrack after a few tracks are already loaded) tomorrow.

Here's the error I see (if it's interesting):
````
igv.min.js:37 Uncaught (in promise) TypeError: Cannot read property 'genome' of undefined
    at igv.min.js:37
    at x (igv.min.js:58)
    at Generator._invoke (igv.min.js:58)
    at Generator.t.<computed> [as next] (igv.min.js:58)
    at Ao (igv.min.js:37)
    at a (igv.min.js:37)
    at igv.min.js:37
    at new Promise (<anonymous>)
    at igv.min.js:37
    at h (igv.min.js:37)
````
And here's my full html/js file:
````
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
    <title>await demo</title>
    <script src="/Users/paul/github/igv.js/dist/igv.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>

<script type="text/javascript">
    var browser;
    $(document).ready(function () {
        console.log("ready");
        var div, options;
        div = $("#igvDiv")[0];
        igv.createBrowser(document.getElementById('igvDiv'), {
           genome: "hg19",
           locus: "chr8:128,747,267-128,754,546"
           })
        .then(async function (browser) {
            const track = await browser.loadTrack(                    {
                type: 'alignment',
                format: 'cram',
                url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram',
                indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai',
                name: 'HG00096'
            })

            var count = browser.trackViews.length;
            for(var i=0; i < count; i++){
                var trackName = browser.trackViews[i].track.name;
                console.log(trackName);
            }
        })

        browser = igv.createBrowser(div, options);
    });

</script>

</head>
<body>
<div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>
</body>

</html>
````

**Comment by paul-shannon** [comment]
that error is my fault - I left an extra createBrowser in the code.  please ignore all of that.
after-the-fact loadTrack example coming tomorrow.

**Comment by jrobinso** [comment]
ok, look forward to seeing it.  The example above is "after the fact".

**Comment by paul-shannon** [comment]
@jrobinso  Here's an elaboration of your example which illustrates the "track names not up to date when queried" problem.   It also shows how await browser.loadTrack() returns before the track is fully rendered.  

````
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
    <title>await demo</title>
    <script src="/Users/paul/github/igv.js/dist/igv.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>

<script type="text/javascript">
    var browser;
    $(document).ready(function () {
        console.log("ready");
        var div, options;
        div = $("#igvDiv")[0];
        igv.createBrowser(document.getElementById('igvDiv'), {
           genome: "hg19",
           locus: "chr8:128,747,267-128,754,546"
           })
        .then(async function (browser) {
            window.browser = browser;  // nasty hack
            const track = await browser.loadTrack(                    {
                type: 'alignment',
                format: 'cram',
                url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram',
                indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai',
                name: 'HG00096'
            })
            var count = browser.trackViews.length;
            for(var i=0; i < count; i++){
               var trackName = browser.trackViews[i].track.name;
               console.log(trackName);
               } // for i
            }) // then
    });

function loadAndList(){
  loadNewTrack()
  listTrackNames()
  }
async function loadNewTrack(){
   console.log("loadAndList")
   const config = {type: 'alignment',
                   format: 'cram',
                   url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram',
                   indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai',
                   name: 'HG00096_' + Math.random()
                  };
    await browser.loadTrack(config);
    } // loadAndList

function listTrackNames(){
   var count = browser.trackViews.length;
   for(var i=0; i < count; i++){
     var trackName = browser.trackViews[i].track.name;
     console.log(trackName);
     } // for i
} // listTrackNames
  
</script>

</head>
<body>
  <div id="controlDiv" style="border: 1px solid red; padding: 20px;">
    <button style="font-size: 24px" onclick="loadAndList()">Add Track, list names</button>
  </div>
  <div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>
</body>

</html>
````

**Comment by jrobinso** [comment]
Actually bundling doesn't seem to be the issue, rather how the code is loaded.  If you're curious pull and look at the files dev/loadTrack-ES2015.html and dev/loadTrack-ES6.html.  The former is your example, the latter tweaked to load igv as a module.  The latter works correctly.  Puzzling.

**Comment by jrobinso** [comment]
I pushed a fix, although I still don't understand what caused this fully.

ladTrack returns before rendering by design.  Loading a long list of tracks in parallel would be painfully slow otherwise.

**Comment by paul-shannon** [comment]
Thanks, Jim.  I'll try it out.

A fresh pull, grunt gets me this:
````
Running "embed-css" task
Warning: Unable to read "wrapper/embedCss.js" file (Error code: ENOENT). Use --force to continue.
````

**Comment by jrobinso** [comment]
sorry, try again.  Also, use "npm run build", not just grunt.  updating
readme now.






',

**Comment by paul-shannon** [comment]
````loadTrack returns before rendering by design.````
That makes sense.   But so far as I can tell, it leaves me in a bind when I do automated testing.

So I'd like to have "wait till rendering is complete" as an option to loadTrack.  Or some other solution maybe you can think of?

As it is now, these two R functions are called in sequence, each runs fine on its own, but they collide when run together. Each function starts with a destructive call to ````setGenome````, which reinitializes igv.
````
   test_displayVcfObject()
   test_displayVcfUrl()
````
Is there any way to block waiting for complete rendering?

**Comment by jrobinso** [comment]
No, await is a keyword,  you can't conditionally apply it (i.e. while-in-test block).  I would suggest just sleeping for a few seconds using setTimeout or similar techniques.
