### ISSUE TITLE
Empty genomicStateList leads to error on window resize

### ISSUE THREAD

**Issue by stefan-leye** [igvteam/igv.js#973]
Sometimes, if the browser is resized, while IGV is still loading, I get the following 

> TypeError: Cannot read property '0' of undefined at t.Browser.updateViews

This is due to genomicStateList being empty, while the resize method calls updateViews.
It can most probably fixed by adding an additional check to
https://github.com/igvteam/igv.js/blob/master/js/browser.js#L908

**Comment by jrobinso** [comment]
Thanks, its on my list to investigate.  The error doesn't seem to do any harm, other than the console message.

**Comment by jrobinso** [comment]
I think this is fixed.
