### ISSUE TITLE
Feature Request: Flip Genome

### ISSUE THREAD

**Issue by Alex-Willenbrink** [igvteam/igv.js#978]
Hello,

Would there be any way you guys could implement a feature that would allow us to flip the chromosomes so that genes and transcripts on the "-" strand could be viewed in the forward (left to right) direction?

Thanks,

-Alex

**Comment by jrobinso** [comment]
That would be difficult,  I'll leave this open as it would be a nice feature but don't have time to devote to it now.  We do enable reverse complementing the sequence.

**Comment by jrobinso** [comment]
This is going to be too difficult to realistically do in any reasonable time.
