### ISSUE TITLE
Wig file reading off by 1

### ISSUE THREAD

**Issue by dtsamitros** [igvteam/igv.js#986]
From documentation I read wig files that represent variableStep and fixedStep data are 1 based. I compared the output of igv.js with that of UCSC genome browser and IGV (java) (https://docs.google.com/document/d/1Vcr0EUO0jZLvCxbrJ-RqYSP0Rbt3pOoQ_vxvDUnAt6Q/edit) and it seems igv.js wig data reading is of by +1.

**Comment by jrobinso** [comment]
Thanks for the report, will check out and correct.  bedgraph is 0 based, perhaps that's where the error comes from.

**Comment by dtsamitros** [comment]
Thanks for the quick response. 

In the fix i noticed a small typo around line 341 in function `parseFixedStep`
```
        ss = parseInt(tokens[2].split("=")[1] - 1, 10),
```
the subtraction should probably go outside the parseInt ..

**Comment by jrobinso** [comment]
Good catch, surprisingly it worked or passed the unit test but that doesn't look right.

**Comment by jrobinso** [comment]
I think some type coercion was saving the day there, but fixed properly now
