### ISSUE TITLE
Remove global css rules in igv.css

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv.js#99]
We need to remove this, and any other "global" rules, from our css.   This will affect everything in the enclosing page,  our css needs to be limited to the igv component.

/* use border box sizing through out */
*, *:after, *:before {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

**Comment by devonbush** [comment]
This is currently causing problems for me -- we are trying to incorporate the IGV into a Broad myeloma research portal.  Can this be reopened?  I'd be happy to help with any effort involved.  thanks!

**Comment by helgathorv** [comment]
There are quite a lot changes to our css in the latest release, including to fix the problem reported in issue #829. Are you using the latest (2.2.1)? If you're having problems with that version, please go ahead open a new issues with a description of the problem(s) you are seeing.

**Comment by jrobinso** [comment]
@devonbush I'm a bit confused as well,  there is no CSS includes in igv.js since version 1.0.9,  although of course we define CSS in our javascript.   If you're having an issue with the current release please open a new git issue with a description.  Thanks.

**Comment by devonbush** [comment]
ah, now I think I realize what's going on, I thought those css files were needed, so I was importing from igv.min, rather than just igv.min.js.  thanks!
