### ISSUE TITLE
Make read sequences available

### ISSUE THREAD

**Issue by snewmanStJude** [igvteam/igv.js#990]
Hi All, awesome job on this so far! I do a lot of manual realignment of read sequences. The Desktop app makes it easy to grab individual sequences using "Copy Read Details to Clipboard", but I can see no equivalent functionality in IGV.js. Can we just expose the read sequence through the popup and have it appear directly below the read name? I'd very much appreciate it if you could. Thanks.

**Comment by jrobinso** [comment]
Coincidentally I just pushed a new menu item "view read sequence" to the
right-click menu.  Its not in the popup its in a separate menu.   This
isn't released yet but will be soon.

**Comment by snewmanStJude** [comment]
That's great. Right click menu works just as well. Thanks

**Comment by amanpatel** [comment]
This is great @jrobinso any estimate on the release this would be included in?

**Comment by jrobinso** [comment]
Actually this was in the last release (3 days ago, 2.3.0).   https://github.com/igvteam/igv.js/releases

**Comment by jrobinso** [comment]
Its released, 2.3.0
