### ISSUE TITLE
Browser Crashes when zooming bam file on AWS S3

### ISSUE THREAD

**Issue by hkutluay** [igvteam/igv.js#991]
Both Chrome, Opera and Edge crashes when zooming bam file (78 mb) on AWS S3. (Chrome gets "_Aw Snap!_", Edge refreshes the page)

**Machine**: Windows 10 Pro 64 bit, 16GB memory, Intel i7-6600U 2.60 GHz
**Chrome** : Version 77.0.3865.90 (Official Build) (64-bit)
**Microsoft Edge**: 44.17763.1.0
**Opera**: Version:63.0.3368.94 

There is no problem Chrome (Version 77.0.3865.90 (Official Build) (64-bit)) on Macbook Pro but Safari (13.0.1) gets "Error: Out of memory"

[Test Link](https://jsfiddle.net/hkutluay/bozpdaj6/1/)

**Comment by jrobinso** [comment]
Thanks for the report and test link.  I can reproduce the problem with this BAM, but not AWS bams generally.  For example the 1KG bams are fine.   Can you tell me how this index was created?

**Comment by jrobinso** [comment]
The "chunk size" in this bam index are huge,  ~10MB on disk, and when adjacent chunks are combined (normal optimization) are too large to load.  This is very unusual,  I've never seen an index which such large chunk sizes.  Normally they are in the range of a few hundred kb.   I'm working on some code to  handle this case,  but that's why I ask how the index was created.

**Comment by hkutluay** [comment]
I'm using picard.jar SortSam command to create index and bam then using MarkDuplicates.  Sample files generated using 2 commands below.

```
java -jar picard.jar SortSam INPUT=input.sam OUTPUT=output.bam CREATE_INDEX=true SORT_ORDER=coordinate

picard.jar MarkDuplicates METRICS_FILE=/out_metrics.txt CREATE_INDEX=true VALIDATION_STRINGENCY=LENIENT
```

**Comment by hkutluay** [comment]
By the way, still got same result with snapshot build. 

[Test Link ](https://jsfiddle.net/hkutluay/bozpdaj6/2/)with Snapshot build

**Comment by jrobinso** [comment]
Your fiddle works for me.   Try clearing your cache.     I have no idea why the chunks are so large in the bam,  I will look at picard and see if I can figure out what's going on.   This has nothing to do with AWS, same problem if you download it locally.   It is however working for me with snapshot (see screenshot).  
<img width="755" alt="Screen Shot 2019-10-03 at 1 05 58 AM" src="https://user-images.githubusercontent.com/933148/66109841-608af100-e57a-11e9-847e-44d614fa2904.png">

**Comment by jrobinso** [comment]
OK,  I think I know what's going on with this file.  You have a huge # of duplicates.  Coverage including duplicates are on the order of 5,000 - 10,000X.  Even though you've marked them they are still in the file and are queried for.  Its only after reading that the duplicate flag can be checked.  The file will be much more performant if you remove the duplicates, don't just mark them.  There isn't much, if anything, that can be done about this in the web client.

**Comment by hkutluay** [comment]
Cache cleared but still same result. As a evidence, see the screenshot, chrome not using cached one. 

![image](https://user-images.githubusercontent.com/1468775/66110996-95c22e00-e5d0-11e9-8df5-6ea055cf9185.png)

**Comment by jrobinso** [comment]
Perhaps messages crossed, you need to remove the duplicates from that file if you want it to be performant in a web client.  I hope my explanation is clear, if not feel free to ask questions.

**Comment by jrobinso** [comment]
@hkutluay I closed this as its not really a bug, or rather anything I can do anything about, but am happy to continue discussing it.    This is an unusual case,  and I've learned about more about the bam index in the process.   The file loads on my Mac + Chrome but that's going to be very individual.
