### ISSUE TITLE
missing `config` on event trigered ivg load

### ISSUE THREAD

**Issue by SchwarzMarek** [igvteam/igv.js#993]
Hi,
I'm trying to draw multiple `igv` browsers in the same webpage. I have dedicated webserver that responds to all the http requests that `ivg` makes. To reduce load on the browser I've implemented conditional loading of the `ivg` browser. 

However when the event is triggered, the `igv` loading crashes with `TypeError: config is undefined[Learn More] igv.js:19388:17`. Which **probably** coresponds to https://github.com/igvteam/igv.js/blob/299c689e0f509b7c4c4823eea3455d08c2f748d2/js/genome/genome.js#L36

The code in compiled igv.js looks like:
```
  var KNOWN_GENOMES;
  var GenomeUtils = {
    loadGenome: function () {
      var _loadGenome = _asyncToGenerator(
      /*#__PURE__*/
      regeneratorRuntime.mark(function _callee(config) {
        var cytobandUrl, aliasURL, sequence, cytobands, aliases;
        return regeneratorRuntime.wrap(function _callee$(_context) {
          while (1) {
            switch (_context.prev = _context.next) {
              case 0:
                cytobandUrl = config.cytobandURL;  /* < --- THIS LINE 19388 */
                aliasURL = config.aliasURL;
                sequence = new FastaSequence(config);
                _context.next = 5;
                return sequence.init();
```

The browser then says `Uknown genome id: xxxxxx`.

What bothers me is that I'm able to load correctly multiple igv browser instances on initial page load, but using the same code and input data I can't load any other `igv` instance. When consulting the "network" log for `http` requests I can see multiple requests for the initial browser instances but none for the one instance triggered by the event.

I'm unsure on how to provide minimal working example since lot of functionality depends on the back-end server. I'm sorry for that.

The main problem is that the `igv` does not make any attempts to contact the back-end server and crashes with the provided report and missing `config`. I'm asking information on `config` variable, and/or how to provide it. Also if you might have any tips on what might be the difference in initial loading and event-triggered loading.

Thank you
Best regards
Marek

Below is some supporting information

Correct load: 
![Screenshot_2019-10-08 Compute_correct](https://user-images.githubusercontent.com/25510773/66411717-7d00b080-e9f4-11e9-851c-4ee0688adcd3.png)

error:
![Screenshot_2019-10-08 Compute _err_msg](https://user-images.githubusercontent.com/25510773/66411744-8722af00-e9f4-11e9-81f0-b5ed292063f0.png)

data passed in json for the 2 examples to illustrate that the problem is not in the passed data
```
# success
accession: "CP006929.1"
divid: "uid2CP0069291fwigv"
end: 543755
locus: "CP006929.1:543073-544255"
requestid: "f5e20763-1ac9-4752-8397-d4f3aa674b72"
start: 543573

# fail
accession: "CP024780.1"
divid: "uid5CP0247801rcigv"
end: 2756358
locus: "CP024780.1:2755675-2756858"
requestid: "f5e20763-1ac9-4752-8397-d4f3aa674b72"
start: 2756175
```
Function handling the creation of `igv` browser instances.
```
    function (brid) {
      requestAnimationFrame( function() {
        var igvDiv = document.getElementById(brid["divid"]);
        console.log(brid)
        var options =
          {
            genome: brid["accession"],
            locus: brid["locus"],
            showRuler: false,
            showChromosomeWidget: false,
            genomeList: "backend/genomeheader/" + brid["accession"] + "?q=" + brid["requestid"]
          };
  
          igv.createBrowser(igvDiv, options)
            .then(function (browser) {
            })
      }
      )
    }
```

**Comment by jrobinso** [comment]
One suggestion I would make is to not use the "genome: <id>" option, rather use "reference" and put the genome information in place.   The link above document the reference object, it is actually the config object.    This would simplify the flow, and you would not need the "genomeList" variable.

**Comment by jrobinso** [comment]
The "genomeList" object is globally shared amongst all browser instances on a page.  This might be the root of the problem.    Either define it once and reference the individual records using the "genome: <id>" option, or don't use it at all and embed the genome objects using the "reference: {}" option.

**Comment by SchwarzMarek** [comment]
Thank you for the fast response. I wasn't aware that the `genomeList` is global. Switching to the `reference` solved the issue.

Thank you once again. (I've even found a note in the documentation about the `genomeList` being global, which I've missed before.)

**Comment by jrobinso** [comment]
@SchwarzMarek you didn't miss anything, I didn't realize that myself until reviewing for this issue.  I added the note.   I think the idea was to load the genome list once as a look up table, then genomes can be referred to by ID.     It should be a static function, not part of "browser config".
