### ISSUE TITLE
track config should take precedence of trackline

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#994]
With this config:
````
   var config = {format: "bed",
                 name: trackName,
                 url: url,
                 indexed:false,
                 displayMode: displayMode,
                 sourceType: "file",
                 color: color,
                 order: Number.MAX_VALUE,
		 height: trackHeight,
                 type: "annotation"};
````
and despite trackName being ````promoters```` I now see, when revisiting some old code, that the promoter track is always given the track label ````refGene````.  I cannot find any cause of this in my code (either R or javascript).   Any ideas?

The string "refGene"  does not appear in any of my code, neither in R nor Javascript.  
I see it mentioned once in the igv.js code base, in  ````featureParsers.js````:
````
* Decode a UCSC "genePredExt" record.  refGene files are in this format
````
The track I display is (in my R class structure) a UCSCBedAnnotationTrack.  So maybe it's not completely nuts for me to ask if featureParsers.js somehow substitutes "refGene" for my requested track name?

**Comment by jrobinso** [comment]
Does your bed file have a "track" line?  Can you share one having this
problem?

**Comment by paul-shannon** [comment]
@jrobinso   That was it - thanks.   An R library I use ("rtracklayer") uses an inherited track name when it exports an object to a file, creating a bed file track line with the default name.   I now simply overwrite that name with the user's choice.

**Comment by jrobinso** [comment]
Im going to reopen this because I think the track config should take precedence over the track line.

**Comment by jrobinso** [comment]
This has been corrected, track config parameters now have precedence over track line parameters.
