### ISSUE TITLE
alignment (bam) track blocking load example

### ISSUE THREAD

**Issue by paul-shannon** [igvteam/igv.js#997]
@jrobinso 
This html file demonstrates either that I don't understand how to use the new ````sync: true```` track load & render feature, or that maybe it doesn't  yet block on track rendering in the way I thought was intended.

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
    <title>await demo</title>
    <script src="https://igv.org/web/current/dist/igv.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>

<script type="text/javascript">
    var browser;
    $(document).ready(function () {
        console.log("ready");
        var div, options;
        div = $("#igvDiv")[0];
        igv.createBrowser(document.getElementById('igvDiv'), {
           genome: "hg19",
           locus: "chr8:128,306,385-129,129,504"
           })
        .then(async function (browser) {
          window.browser = browser;  // nasty hack
          }) // then
    });

async function loadNewTrack(){
   console.log("loadAndList")
   const config = {type: 'alignment',
                   format: 'cram',
                   url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam',
                   indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.bai',
                   name: 'HG00096_' + Math.random(),
                   visibilityWindow: 1000000,
                   sync: true,
                   order: Number.MAX_VALUE,
                  };
    await browser.loadTrack(config);
    } // loadAndList

function loadAndList(){
  loadNewTrack()
  listTrackNames()
  }

function listTrackNames(){
   var count = browser.trackViews.length;
   for(var i=0; i < count; i++){
     var trackName = browser.trackViews[i].track.name;
     console.log(trackName);
     } // for i
} // listTrackNames
  
</script>

</head>
<body>
  <div id="controlDiv" style="border: 1px solid red; padding: 20px;">
    <button style="font-size: 24px" onclick="loadAndList()">Add Track, list names</button>
  </div>
  <div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>
</body>

</html>

**Comment by jrobinso** [comment]
@paul-shannon the line feeds are lost in that snippet which makes it hard to interpret with all the comments.   Could you repost in code quotes (```)?

**Comment by paul-shannon** [comment]
I am now 0/2 on giving you want you need.   Sorry.  I hope this is complete and useful.
To reproduce the problem I see, try this:

 - load the code into your browser
 - open up the javascript console
 - type ````loadAndList()```` into the console, or
 - click the ````Add Track, list names```` button
 - I think you will see that a list of the current track names appears in the console before the pileup rendering completes. 
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
    <title>await demo</title>
    <script src="https://igv.org/web/current/dist/igv.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>

<script type="text/javascript">
    var browser;
    $(document).ready(function () {
        console.log("ready");
        var div, options;
        div = $("#igvDiv")[0];
        igv.createBrowser(document.getElementById('igvDiv'), {
           genome: "hg19",
           locus: "chr8:128,306,385-129,129,504"
           })
        .then(async function (browser) {
          window.browser = browser;  // nasty hack
          }) // then
    });

async function loadNewTrack(){
   console.log("loadAndList")
   const config = {type: 'alignment',
                   format: 'cram',
                   url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam',
                   indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.bai',
                   name: 'HG00096_' + Math.random(),
                   visibilityWindow: 1000000,
                   sync: true,
                   order: Number.MAX_VALUE,
                  };
    await browser.loadTrack(config);
    } // loadAndList

function loadAndList(){
  loadNewTrack()
  listTrackNames()
  }


function listTrackNames(){
   var count = browser.trackViews.length;
   for(var i=0; i < count; i++){
     var trackName = browser.trackViews[i].track.name;
     console.log(trackName);
     } // for i
} // listTrackNames
  
</script>

</head>
<body>
  <div id="controlDiv" style="border: 1px solid red; padding: 20px;">
    <button style="font-size: 24px" onclick="loadAndList()">Add Track, list names</button>
  </div>
  <div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>
</body>

</html>
```

**Comment by jrobinso** [comment]
will do.  BTW right away I see your not awaiting loadNewTrack.  It is usually a bug to not await (or "then") an async function.

**Comment by jrobinso** [comment]
OK, I think the problem is you were not awaiting the resolution of the promise returned by loadNewTrack.  All "async" functions return a promise.    Its usually a bug to ignore the promise, unless the call is at the end of a chain and you don't use the returned result. 

try either this
```
        async function loadAndList(){
            await loadNewTrack()
            listTrackNames()
        }
```

or 

```
        function loadAndList(){
            loadNewTrack()
                .then(function (ignore) {
                    listTrackNames()
                })
        }
```

**Comment by jrobinso** [comment]
@paul-shannon other thing, igv.js in your example is very old,  I will delete that directory.  This one is built automatically and up to date  `http://igv.org/web/snapshot/dist/igv.min.js`

**Comment by jrobinso** [comment]
complete working example

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://igv.org/web/img/favicon.ico">
    <title>await demo</title>
    <script src="http://igv.org/web/snapshot/dist/igv.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"></script>

    <script type="text/javascript">
        var browser;
        $(document).ready(function () {
            console.log("ready");
            var div, options;
            div = $("#igvDiv")[0];
            igv.createBrowser(document.getElementById('igvDiv'), {
                genome: "hg19",
                locus: "chr8:128,306,385-129,129,504"
            })
                .then(async function (browser) {
                    window.browser = browser;  // nasty hack
                }) // then
        });

        async function loadNewTrack(){
            console.log("loadAndList")
            const config = {type: 'alignment',
                format: 'bam',
                url: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam',
                indexURL: 'https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.bai',
                name: 'HG00096_' + Math.random(),
                visibilityWindow: 1000000,
                sync: true,
                order: Number.MAX_VALUE,
            };
            await browser.loadTrack(config);
        } // loadAndList

        async function loadAndList(){
            await loadNewTrack()
            listTrackNames()
        }


        function listTrackNames(){
            var count = browser.trackViews.length;
            for(var i=0; i < count; i++){
                var trackName = browser.trackViews[i].track.name;
                console.log(trackName);
            } // for i
        } // listTrackNames

    </script>

</head>
<body>
<div id="controlDiv" style="border: 1px solid red; padding: 20px;">
    <button style="font-size: 24px" onclick="loadAndList()">Add Track, list names</button>
</div>
<div id="igvDiv" style="padding-top: 50px;padding-bottom: 20px; height: auto"></div>
</body>

</html>
```

**Comment by paul-shannon** [comment]
Hi Jim,

Your example works fine but for reasons I have looked and looked to understand, my own version does not.   Here is the javascript function igvR calls to load a bam file.   Do you see my mistake?  I'd be grateful if you could point it out.   Promises remain a little opaque to me.

 - Paul
```
async function displayAlignmentTrackFromUrl(msg)
{
   var self = this;
   checkSignature(self, "displayAlignmentTrackFromUrl")

   var trackName = msg.payload.name;
   var trackHeight = msg.payload.trackHeight;
   var dataURL = msg.payload.dataURL;
   var visibilityWindow = msg.payload.visibilityWindow;

   console.log("==== bam visibilityWindow: " + visibilityWindow);
   console.log("==== bam height: " + trackHeight);
    
   console.log("dataURL: " + dataURL)

   var indexURL = msg.payload.indexURL;
   var indexed = indexURL.length > 0;
   var color = msg.payload.color;

   var config = {name: trackName,
                 type: "alignment",
                 format: "bam",
                 url: dataURL,
                 sync: true,
                 order: Number.MAX_VALUE,
                 visibilityWindow: visibilityWindow,
		 height: trackHeight,
                 color: color,
                 indexed: false
                 };

   console.log(JSON.stringify(config));

   async function blockingLoad(config) {
      await window.igvBrowser.loadTrack(config);
      };

   try{
      console.log(" about to call 'await blockingLoad(config)'");
      await blockingLoad(config);
      self.hub.send({cmd: msg.callback, status: "success", callback: "", payload: ""});
      }
   catch(error){
      console.log("=== load bed track error")
      console.log(error)
      self.hub.send({cmd: msg.callback, status: "failure", callback: "", payload: error});
      }

} // displayAlignmentTrackFromUrl

```

**Comment by jrobinso** [comment]
@paul-shannon Looking at it, but the "indexed: false" setting will cause issues.

**Comment by jrobinso** [comment]
@paul-shannon other than the "indexed: false", which causes igv.js to try to read the entire bam file, I didn't find anything important wrong here.   I've pushed 2 slightly modified versions of your file to the "dev" folder,  blocking-await.html and blocking-then.html.   The first uses async/await, the second promise chains, but they accomplish the same thing.   If you are not running your javascript through babel the promise chain version will work in more browsers.  async/await is pretty well supported in modern browsers but is newer.

In lieu of "self.hub.send"  I am just printing track names.

Pull and have a look at those test files.

**Comment by jrobinso** [comment]
Hi Paul,  the examples were for your use, I will update with a PR or not, your choice.
